.TH "_7z_folder" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_7z_folder
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_7z_coder\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBnumCoders\fP"
.br
.ti -1c
.RI "struct \fB_7z_folder::_7z_coder\fP * \fBcoders\fP"
.br
.ti -1c
.RI "uint64_t \fBnumBindPairs\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint64_t \fBinIndex\fP"
.br
.ti -1c
.RI "   uint64_t \fBoutIndex\fP"
.br
.ti -1c
.RI "} * \fBbindPairs\fP"
.br
.ti -1c
.RI "uint64_t \fBnumPackedStreams\fP"
.br
.ti -1c
.RI "uint64_t * \fBpackedStreams\fP"
.br
.ti -1c
.RI "uint64_t \fBnumInStreams\fP"
.br
.ti -1c
.RI "uint64_t \fBnumOutStreams\fP"
.br
.ti -1c
.RI "uint64_t * \fBunPackSize\fP"
.br
.ti -1c
.RI "unsigned char \fBdigest_defined\fP"
.br
.ti -1c
.RI "uint32_t \fBdigest\fP"
.br
.ti -1c
.RI "uint64_t \fBnumUnpackStreams\fP"
.br
.ti -1c
.RI "uint32_t \fBpackIndex\fP"
.br
.ti -1c
.RI "uint64_t \fBskipped_bytes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
