.TH "_7z_folder::_7z_coder" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_7z_folder::_7z_coder
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBcodec\fP"
.br
.ti -1c
.RI "uint64_t \fBnumInStreams\fP"
.br
.ti -1c
.RI "uint64_t \fBnumOutStreams\fP"
.br
.ti -1c
.RI "uint64_t \fBpropertiesSize\fP"
.br
.ti -1c
.RI "unsigned char * \fBproperties\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
