.TH "_7z_stream_info" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_7z_stream_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fB_7z_pack_info\fP \fBpi\fP"
.br
.ti -1c
.RI "struct \fB_7z_coders_info\fP \fBci\fP"
.br
.ti -1c
.RI "struct \fB_7z_substream_info\fP \fBss\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
