.TH "_7zip" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_7zip
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fB_7z_stream_info\fP \fBsi\fP"
.br
.ti -1c
.RI "int \fBheader_is_being_read\fP"
.br
.ti -1c
.RI "int \fBheader_is_encoded\fP"
.br
.ti -1c
.RI "uint64_t \fBheader_bytes_remaining\fP"
.br
.ti -1c
.RI "unsigned long \fBheader_crc32\fP"
.br
.ti -1c
.RI "uint64_t \fBheader_offset\fP"
.br
.ti -1c
.RI "uint64_t \fBseek_base\fP"
.br
.ti -1c
.RI "size_t \fBentries_remaining\fP"
.br
.ti -1c
.RI "uint64_t \fBnumFiles\fP"
.br
.ti -1c
.RI "struct \fB_7zip_entry\fP * \fBentries\fP"
.br
.ti -1c
.RI "struct \fB_7zip_entry\fP * \fBentry\fP"
.br
.ti -1c
.RI "unsigned char * \fBentry_names\fP"
.br
.ti -1c
.RI "int64_t \fBentry_offset\fP"
.br
.ti -1c
.RI "uint64_t \fBentry_bytes_remaining\fP"
.br
.ti -1c
.RI "unsigned long \fBentry_crc32\fP"
.br
.ti -1c
.RI "char \fBend_of_entry\fP"
.br
.ti -1c
.RI "unsigned char * \fBuncompressed_buffer\fP"
.br
.ti -1c
.RI "unsigned char * \fBuncompressed_buffer_pointer\fP"
.br
.ti -1c
.RI "size_t \fBuncompressed_buffer_size\fP"
.br
.ti -1c
.RI "size_t \fBuncompressed_buffer_bytes_remaining\fP"
.br
.ti -1c
.RI "int64_t \fBstream_offset\fP"
.br
.ti -1c
.RI "unsigned \fBfolder_index\fP"
.br
.ti -1c
.RI "uint64_t \fBfolder_outbytes_remaining\fP"
.br
.ti -1c
.RI "unsigned \fBpack_stream_index\fP"
.br
.ti -1c
.RI "unsigned \fBpack_stream_remaining\fP"
.br
.ti -1c
.RI "uint64_t \fBpack_stream_inbytes_remaining\fP"
.br
.ti -1c
.RI "size_t \fBpack_stream_bytes_unconsumed\fP"
.br
.ti -1c
.RI "unsigned long \fBcodec\fP"
.br
.ti -1c
.RI "unsigned long \fBcodec2\fP"
.br
.ti -1c
.RI "int \fBppmd7_stat\fP"
.br
.ti -1c
.RI "\fBCPpmd7\fP \fBppmd7_context\fP"
.br
.ti -1c
.RI "\fBCPpmd7z_RangeDec\fP \fBrange_dec\fP"
.br
.ti -1c
.RI "\fBIByteIn\fP \fBbytein\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   const unsigned char * \fBnext_in\fP"
.br
.ti -1c
.RI "   int64_t \fBavail_in\fP"
.br
.ti -1c
.RI "   int64_t \fBtotal_in\fP"
.br
.ti -1c
.RI "   int64_t \fBstream_in\fP"
.br
.ti -1c
.RI "   unsigned char * \fBnext_out\fP"
.br
.ti -1c
.RI "   int64_t \fBavail_out\fP"
.br
.ti -1c
.RI "   int64_t \fBtotal_out\fP"
.br
.ti -1c
.RI "   int \fBoverconsumed\fP"
.br
.ti -1c
.RI "} \fBppstream\fP"
.br
.ti -1c
.RI "int \fBppmd7_valid\fP"
.br
.ti -1c
.RI "uint32_t \fBbcj_state\fP"
.br
.ti -1c
.RI "size_t \fBodd_bcj_size\fP"
.br
.ti -1c
.RI "unsigned char \fBodd_bcj\fP [4]"
.br
.ti -1c
.RI "size_t \fBbcj_prevPosT\fP"
.br
.ti -1c
.RI "uint32_t \fBbcj_prevMask\fP"
.br
.ti -1c
.RI "uint32_t \fBbcj_ip\fP"
.br
.ti -1c
.RI "size_t \fBmain_stream_bytes_remaining\fP"
.br
.ti -1c
.RI "unsigned char * \fBsub_stream_buff\fP [3]"
.br
.ti -1c
.RI "size_t \fBsub_stream_size\fP [3]"
.br
.ti -1c
.RI "size_t \fBsub_stream_bytes_remaining\fP [3]"
.br
.ti -1c
.RI "unsigned char * \fBtmp_stream_buff\fP"
.br
.ti -1c
.RI "size_t \fBtmp_stream_buff_size\fP"
.br
.ti -1c
.RI "size_t \fBtmp_stream_bytes_avail\fP"
.br
.ti -1c
.RI "size_t \fBtmp_stream_bytes_remaining\fP"
.br
.ti -1c
.RI "CProb \fBbcj2_p\fP [256+2]"
.br
.ti -1c
.RI "uint8_t \fBbcj2_prevByte\fP"
.br
.ti -1c
.RI "uint32_t \fBbcj2_range\fP"
.br
.ti -1c
.RI "uint32_t \fBbcj2_code\fP"
.br
.ti -1c
.RI "uint64_t \fBbcj2_outPos\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv\fP"
.br
.ti -1c
.RI "char \fBformat_name\fP [64]"
.br
.ti -1c
.RI "int \fBhas_encrypted_entries\fP"
.br
.ti -1c
.RI "int \fBtemp_fd\fP"
.br
.ti -1c
.RI "uint64_t \fBtemp_offset\fP"
.br
.ti -1c
.RI "struct \fBfile\fP * \fBcur_file\fP"
.br
.ti -1c
.RI "size_t \fBtotal_number_entry\fP"
.br
.ti -1c
.RI "size_t \fBtotal_number_nonempty_entry\fP"
.br
.ti -1c
.RI "size_t \fBtotal_number_empty_entry\fP"
.br
.ti -1c
.RI "size_t \fBtotal_number_dir_entry\fP"
.br
.ti -1c
.RI "size_t \fBtotal_bytes_entry_name\fP"
.br
.ti -1c
.RI "size_t \fBtotal_number_time_defined\fP [3]"
.br
.ti -1c
.RI "uint64_t \fBtotal_bytes_compressed\fP"
.br
.ti -1c
.RI "uint64_t \fBtotal_bytes_uncompressed\fP"
.br
.ti -1c
.RI "uint32_t \fBentry_crc32\fP"
.br
.ti -1c
.RI "uint32_t \fBprecode_crc32\fP"
.br
.ti -1c
.RI "uint32_t \fBencoded_crc32\fP"
.br
.ti -1c
.RI "int \fBcrc32flg\fP"
.br
.ti -1c
.RI "unsigned \fBopt_compression\fP"
.br
.ti -1c
.RI "int \fBopt_compression_level\fP"
.br
.ti -1c
.RI "struct \fBla_zstream\fP \fBstream\fP"
.br
.ti -1c
.RI "struct \fBcoder\fP \fBcoder\fP"
.br
.ti -1c
.RI "unsigned char \fBwbuff\fP [512 *20 *6]"
.br
.ti -1c
.RI "size_t \fBwbuff_remaining\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBfile\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBfile\fP ** \fBlast\fP"
.br
.ti -1c
.RI "} \fBfile_list\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBfile\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBfile\fP ** \fBlast\fP"
.br
.ti -1c
.RI "} \fBempty_list\fP"
.br
.ti -1c
.RI "struct \fBarchive_rb_tree\fP \fBrbtree\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
