.TH "_7zip_entry" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_7zip_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBname_len\fP"
.br
.ti -1c
.RI "unsigned char * \fButf16name\fP"
.br
.ti -1c
.RI "uint32_t \fBfolderIndex\fP"
.br
.ti -1c
.RI "uint32_t \fBssIndex\fP"
.br
.ti -1c
.RI "unsigned \fBflg\fP"
.br
.ti -1c
.RI "time_t \fBmtime\fP"
.br
.ti -1c
.RI "time_t \fBatime\fP"
.br
.ti -1c
.RI "time_t \fBctime\fP"
.br
.ti -1c
.RI "long \fBmtime_ns\fP"
.br
.ti -1c
.RI "long \fBatime_ns\fP"
.br
.ti -1c
.RI "long \fBctime_ns\fP"
.br
.ti -1c
.RI "uint32_t \fBmode\fP"
.br
.ti -1c
.RI "uint32_t \fBattr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
