.TH "__TAGE" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__TAGE
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEXTENSIONBASE\fP \fBpkBase\fP"
.br
.ti -1c
.RI "\fBEXPKEYSDATA\fP \fBpkExpKeys\fP"
.br
.ti -1c
.RI "\fBSLIDERDATA\fP \fBpkTouchStrip\fP"
.br
.ti -1c
.RI "\fBSLIDERDATA\fP \fBpkTouchRing\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
