.TH "_bmp_source_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_bmp_source_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBcjpeg_source_struct\fP \fBpub\fP"
.br
.ti -1c
.RI "\fBj_compress_ptr\fP \fBcinfo\fP"
.br
.ti -1c
.RI "JSAMPARRAY \fBcolormap\fP"
.br
.ti -1c
.RI "\fBjvirt_sarray_ptr\fP \fBwhole_image\fP"
.br
.ti -1c
.RI "JDIMENSION \fBsource_row\fP"
.br
.ti -1c
.RI "JDIMENSION \fBrow_width\fP"
.br
.ti -1c
.RI "int \fBbits_per_pixel\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
