.TH "_draw_data_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_draw_data_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBpath_len\fP"
.br
.ti -1c
.RI "float \fBpath_start_x\fP"
.br
.ti -1c
.RI "float \fBpath_start_y\fP"
.br
.ti -1c
.RI "float \fBpath_last_x\fP"
.br
.ti -1c
.RI "float \fBpath_last_y\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
