.TH "_GlobalInfo" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GlobalInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBepfd\fP"
.br
.ti -1c
.RI "int \fBtfd\fP"
.br
.ti -1c
.RI "int \fBfifofd\fP"
.br
.ti -1c
.RI "CURLM * \fBmulti\fP"
.br
.ti -1c
.RI "int \fBstill_running\fP"
.br
.ti -1c
.RI "FILE * \fBinput\fP"
.br
.ti -1c
.RI "struct ev_loop * \fBloop\fP"
.br
.ti -1c
.RI "struct ev_io \fBfifo_event\fP"
.br
.ti -1c
.RI "struct ev_timer \fBtimer_event\fP"
.br
.ti -1c
.RI "guint \fBtimer_event\fP"
.br
.ti -1c
.RI "struct event_base * \fBevbase\fP"
.br
.ti -1c
.RI "struct event \fBfifo_event\fP"
.br
.ti -1c
.RI "struct event \fBtimer_event\fP"
.br
.ti -1c
.RI "int \fBstopped\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
