.TH "_hb_var_int_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_hb_var_int_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBu32\fP"
.br
.ti -1c
.RI "int32_t \fBi32\fP"
.br
.ti -1c
.RI "uint16_t \fBu16\fP [2]"
.br
.ti -1c
.RI "int16_t \fBi16\fP [2]"
.br
.ti -1c
.RI "uint8_t \fBu8\fP [4]"
.br
.ti -1c
.RI "int8_t \fBi8\fP [4]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
