.TH "_hb_null_size< T, hb_void_t< decltype(T::min_size)> >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_hb_null_size< T, hb_void_t< decltype(T::min_size)> >
.SH SYNOPSIS
.br
.PP
.PP
Inherits hb_integral_constant< unsigned,(sizeof(T) > T::null_size ? sizeof(T) :T::null_size)>\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
