.TH "_hb_unwrap_type< T, hb_void_t< typename T::type > >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_hb_unwrap_type< T, hb_void_t< typename T::type > >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fB_hb_unwrap_type< T::type, void >\fP\&.
.SS "Additional Inherited Members"


Public Types inherited from \fBhb_type_identity_t< T >\fP
.in +1c
.ti -1c
.RI "typedef T \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
