.TH "_mainprog_info" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_mainprog_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBdisplay_exponent\fP"
.br
.ti -1c
.RI "ulg \fBwidth\fP"
.br
.ti -1c
.RI "ulg \fBheight\fP"
.br
.ti -1c
.RI "void * \fBpng_ptr\fP"
.br
.ti -1c
.RI "void * \fBinfo_ptr\fP"
.br
.ti -1c
.RI "void(* \fBmainprog_init\fP )(void)"
.br
.ti -1c
.RI "void(* \fBmainprog_display_row\fP )(ulg row_num)"
.br
.ti -1c
.RI "void(* \fBmainprog_finish_display\fP )(void)"
.br
.ti -1c
.RI "uch * \fBimage_data\fP"
.br
.ti -1c
.RI "uch ** \fBrow_pointers\fP"
.br
.ti -1c
.RI "jmp_buf \fBjmpbuf\fP"
.br
.ti -1c
.RI "int \fBpasses\fP"
.br
.ti -1c
.RI "int \fBpass\fP"
.br
.ti -1c
.RI "int \fBrowbytes\fP"
.br
.ti -1c
.RI "int \fBchannels\fP"
.br
.ti -1c
.RI "int \fBneed_bgcolor\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "uch \fBbg_red\fP"
.br
.ti -1c
.RI "uch \fBbg_green\fP"
.br
.ti -1c
.RI "uch \fBbg_blue\fP"
.br
.ti -1c
.RI "double \fBgamma\fP"
.br
.ti -1c
.RI "long \fBwidth\fP"
.br
.ti -1c
.RI "long \fBheight\fP"
.br
.ti -1c
.RI "time_t \fBmodtime\fP"
.br
.ti -1c
.RI "FILE * \fBinfile\fP"
.br
.ti -1c
.RI "FILE * \fBoutfile\fP"
.br
.ti -1c
.RI "char * \fBtitle\fP"
.br
.ti -1c
.RI "char * \fBauthor\fP"
.br
.ti -1c
.RI "char * \fBdesc\fP"
.br
.ti -1c
.RI "char * \fBcopyright\fP"
.br
.ti -1c
.RI "char * \fBemail\fP"
.br
.ti -1c
.RI "char * \fBurl\fP"
.br
.ti -1c
.RI "int \fBfilter\fP"
.br
.ti -1c
.RI "int \fBpnmtype\fP"
.br
.ti -1c
.RI "int \fBsample_depth\fP"
.br
.ti -1c
.RI "int \fBinterlaced\fP"
.br
.ti -1c
.RI "int \fBhave_bg\fP"
.br
.ti -1c
.RI "int \fBhave_time\fP"
.br
.ti -1c
.RI "int \fBhave_text\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
