.TH "_SockInfo" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SockInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "curl_socket_t \fBsockfd\fP"
.br
.ti -1c
.RI "CURL * \fBeasy\fP"
.br
.ti -1c
.RI "int \fBaction\fP"
.br
.ti -1c
.RI "long \fBtimeout\fP"
.br
.ti -1c
.RI "\fBGlobalInfo\fP * \fBglobal\fP"
.br
.ti -1c
.RI "struct ev_io \fBev\fP"
.br
.ti -1c
.RI "int \fBevset\fP"
.br
.ti -1c
.RI "GIOChannel * \fBch\fP"
.br
.ti -1c
.RI "guint \fBev\fP"
.br
.ti -1c
.RI "struct event \fBev\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
