.TH "_tga_source_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_tga_source_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, read_pixel,(\fBtga_source_ptr\fP sinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (JDIMENSION, get_pixel_rows,(\fBj_compress_ptr\fP cinfo, \fBcjpeg_source_ptr\fP sinfo))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBcjpeg_source_struct\fP \fBpub\fP"
.br
.ti -1c
.RI "\fBj_compress_ptr\fP \fBcinfo\fP"
.br
.ti -1c
.RI "JSAMPARRAY \fBcolormap\fP"
.br
.ti -1c
.RI "\fBjvirt_sarray_ptr\fP \fBwhole_image\fP"
.br
.ti -1c
.RI "JDIMENSION \fBcurrent_row\fP"
.br
.ti -1c
.RI "U_CHAR \fBtga_pixel\fP [4]"
.br
.ti -1c
.RI "int \fBpixel_size\fP"
.br
.ti -1c
.RI "int \fBblock_count\fP"
.br
.ti -1c
.RI "int \fBdup_pixel_count\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
