.TH "a" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
a
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBcurltime\fP \fBfirst\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBsecond\fP"
.br
.ti -1c
.RI "time_t \fBresult\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
