.TH "abstract" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
abstract
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBf\fP ()=0"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "auto \fBoperator<<\fP (std::ostream &os, const \fBabstract\fP &) \-> std::ostream &"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
