.TH "AF_FaceGlobalsRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_FaceGlobalsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Face\fP \fBface\fP"
.br
.ti -1c
.RI "FT_Long \fBglyph_count\fP"
.br
.ti -1c
.RI "FT_UShort * \fBglyph_styles\fP"
.br
.ti -1c
.RI "FT_UInt \fBincrease_x_height\fP"
.br
.ti -1c
.RI "\fBAF_StyleMetrics\fP \fBmetrics\fP [AF_STYLE_MAX]"
.br
.ti -1c
.RI "FT_UShort \fBstem_darkening_for_ppem\fP"
.br
.ti -1c
.RI "FT_Pos \fBstandard_vertical_width\fP"
.br
.ti -1c
.RI "FT_Pos \fBstandard_horizontal_width\fP"
.br
.ti -1c
.RI "FT_Pos \fBdarken_x\fP"
.br
.ti -1c
.RI "FT_Pos \fBdarken_y\fP"
.br
.ti -1c
.RI "FT_Fixed \fBscale_down_factor\fP"
.br
.ti -1c
.RI "AF_Module \fBmodule\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
