.TH "AF_LatinBlueRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_LatinBlueRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AF_WidthRec \fBref\fP"
.br
.ti -1c
.RI "AF_WidthRec \fBshoot\fP"
.br
.ti -1c
.RI "FT_Pos \fBascender\fP"
.br
.ti -1c
.RI "FT_Pos \fBdescender\fP"
.br
.ti -1c
.RI "FT_UInt \fBflags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
