.TH "AF_StyleClassRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_StyleClassRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AF_Style \fBstyle\fP"
.br
.ti -1c
.RI "AF_WritingSystem \fBwriting_system\fP"
.br
.ti -1c
.RI "AF_Script \fBscript\fP"
.br
.ti -1c
.RI "AF_Blue_Stringset \fBblue_stringset\fP"
.br
.ti -1c
.RI "AF_Coverage \fBcoverage\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
