.TH "AF_ScriptClassRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_ScriptClassRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AF_Script \fBscript\fP"
.br
.ti -1c
.RI "\fBAF_Script_UniRange\fP \fBscript_uni_ranges\fP"
.br
.ti -1c
.RI "\fBAF_Script_UniRange\fP \fBscript_uni_nonbase_ranges\fP"
.br
.ti -1c
.RI "FT_Bool \fBtop_to_bottom_hinting\fP"
.br
.ti -1c
.RI "const char * \fBstandard_charstring\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
