.TH "AF_ScalerRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_ScalerRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Face\fP \fBface\fP"
.br
.ti -1c
.RI "FT_Fixed \fBx_scale\fP"
.br
.ti -1c
.RI "FT_Fixed \fBy_scale\fP"
.br
.ti -1c
.RI "FT_Pos \fBx_delta\fP"
.br
.ti -1c
.RI "FT_Pos \fBy_delta\fP"
.br
.ti -1c
.RI "FT_Render_Mode \fBrender_mode\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBflags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
