.TH "AF_WritingSystemClassRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AF_WritingSystemClassRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AF_WritingSystem \fBwriting_system\fP"
.br
.ti -1c
.RI "FT_Offset \fBstyle_metrics_size\fP"
.br
.ti -1c
.RI "AF_WritingSystem_InitMetricsFunc \fBstyle_metrics_init\fP"
.br
.ti -1c
.RI "AF_WritingSystem_ScaleMetricsFunc \fBstyle_metrics_scale\fP"
.br
.ti -1c
.RI "AF_WritingSystem_DoneMetricsFunc \fBstyle_metrics_done\fP"
.br
.ti -1c
.RI "AF_WritingSystem_GetStdWidthsFunc \fBstyle_metrics_getstdw\fP"
.br
.ti -1c
.RI "AF_WritingSystem_InitHintsFunc \fBstyle_hints_init\fP"
.br
.ti -1c
.RI "AF_WritingSystem_ApplyHintsFunc \fBstyle_hints_apply\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
