.TH "AFM_FontInfoRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFM_FontInfoRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Bool \fBIsCIDFont\fP"
.br
.ti -1c
.RI "\fBFT_BBox\fP \fBFontBBox\fP"
.br
.ti -1c
.RI "FT_Fixed \fBAscender\fP"
.br
.ti -1c
.RI "FT_Fixed \fBDescender\fP"
.br
.ti -1c
.RI "\fBAFM_TrackKern\fP \fBTrackKerns\fP"
.br
.ti -1c
.RI "FT_UInt \fBNumTrackKern\fP"
.br
.ti -1c
.RI "\fBAFM_KernPair\fP \fBKernPairs\fP"
.br
.ti -1c
.RI "FT_UInt \fBNumKernPair\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
