.TH "AFM_TrackKernRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFM_TrackKernRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Int \fBdegree\fP"
.br
.ti -1c
.RI "FT_Fixed \fBmin_ptsize\fP"
.br
.ti -1c
.RI "FT_Fixed \fBmin_kern\fP"
.br
.ti -1c
.RI "FT_Fixed \fBmax_ptsize\fP"
.br
.ti -1c
.RI "FT_Fixed \fBmax_kern\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
