.TH "allocator_ref< Allocator >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
allocator_ref< Allocator >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBvalue_type\fP = typename Allocator::value_type"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBallocator_ref\fP (Allocator *alloc=nullptr)"
.br
.ti -1c
.RI "\fBallocator_ref\fP (const \fBallocator_ref\fP &other)"
.br
.ti -1c
.RI "\fBallocator_ref\fP (\fBallocator_ref\fP &&other)"
.br
.ti -1c
.RI "\fBallocator_ref\fP & \fBoperator=\fP (\fBallocator_ref\fP &&other)"
.br
.ti -1c
.RI "\fBallocator_ref\fP & \fBoperator=\fP (const \fBallocator_ref\fP &other)"
.br
.ti -1c
.RI "Allocator * \fBget\fP () const"
.br
.ti -1c
.RI "value_type * \fBallocate\fP (size_t n)"
.br
.ti -1c
.RI "void \fBdeallocate\fP (value_type *p, size_t n)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
