.TH "ALPHDecoder" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ALPHDecoder
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth_\fP"
.br
.ti -1c
.RI "int \fBheight_\fP"
.br
.ti -1c
.RI "int \fBmethod_\fP"
.br
.ti -1c
.RI "WEBP_FILTER_TYPE \fBfilter_\fP"
.br
.ti -1c
.RI "int \fBpre_processing_\fP"
.br
.ti -1c
.RI "struct \fBVP8LDecoder\fP * \fBvp8l_dec_\fP"
.br
.ti -1c
.RI "\fBVP8Io\fP \fBio_\fP"
.br
.ti -1c
.RI "int \fBuse_8b_decode_\fP"
.br
.ti -1c
.RI "uint8_t * \fBoutput_\fP"
.br
.ti -1c
.RI "const uint8_t * \fBprev_line_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
