.TH "altsvc" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
altsvc
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBalthost\fP \fBsrc\fP"
.br
.ti -1c
.RI "struct \fBalthost\fP \fBdst\fP"
.br
.ti -1c
.RI "time_t \fBexpires\fP"
.br
.ti -1c
.RI "bool \fBpersist\fP"
.br
.ti -1c
.RI "int \fBprio\fP"
.br
.ti -1c
.RI "struct \fBCurl_llist_element\fP \fBnode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
