.TH "AnimatedImage" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnimatedImage
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AnimatedFileFormat \fBformat\fP"
.br
.ti -1c
.RI "uint32_t \fBcanvas_width\fP"
.br
.ti -1c
.RI "uint32_t \fBcanvas_height\fP"
.br
.ti -1c
.RI "uint32_t \fBbgcolor\fP"
.br
.ti -1c
.RI "uint32_t \fBloop_count\fP"
.br
.ti -1c
.RI "\fBDecodedFrame\fP * \fBframes\fP"
.br
.ti -1c
.RI "uint32_t \fBnum_frames\fP"
.br
.ti -1c
.RI "void * \fBraw_mem\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
