.TH "ansi_color_escape< Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ansi_color_escape< Char >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBansi_color_escape\fP (detail::color_type text_color, const char *esc) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBansi_color_escape\fP (emphasis em) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBoperator const Char *\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR const Char * \fBbegin\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR_CHAR_TRAITS const Char * \fBend\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBansi_color_escape\fP (detail::color_type text_color, const char *esc) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBansi_color_escape\fP (emphasis em) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBoperator const Char *\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR const Char * \fBbegin\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR_CHAR_TRAITS const Char * \fBend\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBansi_color_escape\fP (detail::color_type text_color, const char *esc) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBansi_color_escape\fP (emphasis em) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBoperator const Char *\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR const Char * \fBbegin\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR_CHAR_TRAITS const Char * \fBend\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBansi_color_escape\fP (detail::color_type text_color, const char *esc) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBansi_color_escape\fP (emphasis em) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBoperator const Char *\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR const Char * \fBbegin\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR_CHAR_TRAITS const Char * \fBend\fP () const noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
