.TH "app_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GtkBuilder * \fBbuilder\fP"
.br
.ti -1c
.RI "\fBpixman_image_t\fP * \fBoriginal\fP"
.br
.ti -1c
.RI "pixman_format_code_t \fBformat\fP"
.br
.ti -1c
.RI "pixman_dither_t \fBdither\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "GtkAdjustment * \fBscale_x_adjustment\fP"
.br
.ti -1c
.RI "GtkAdjustment * \fBscale_y_adjustment\fP"
.br
.ti -1c
.RI "GtkAdjustment * \fBrotate_adjustment\fP"
.br
.ti -1c
.RI "GtkAdjustment * \fBsubsample_adjustment\fP"
.br
.ti -1c
.RI "int \fBscaled_width\fP"
.br
.ti -1c
.RI "int \fBscaled_height\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
