.TH "AppDelegateOSX" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppDelegateOSX
.SH SYNOPSIS
.br
.PP
.PP
Inherits NSObject, and <NSApplicationDelegate>\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(NSApplicationTerminateReply) \- \fBapplicationShouldTerminate:\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBapplicationShouldTerminateAfterLastWindowClosed:\fP"
.br
.ti -1c
.RI "(void) \- \fBapplicationWillTerminate:\fP"
.br
.ti -1c
.RI "(void) \- \fBapplicationWillResignActive:\fP"
.br
.ti -1c
.RI "(void) \- \fBapplicationDidBecomeActive:\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBapplication:openFiles:\fP"
.br
.ti -1c
.RI "(void) \- \fBexecuteMenuItem:\fP"
.br
.ti -1c
.RI "(BOOL) \- \fBvalidateMenuItem:\fP"
.br
.ti -1c
.RI "(void) \- \fBmarkCliFileAsProcessed:\fP"
.br
.ti -1c
.RI "(void) \- \fBresetCliFiles\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::set< std::string > \fBm_cliFiles\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
