.TH "appender" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
appender
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::back_insert_iterator< detail::buffer< char > >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBappender\fP (base it) noexcept"
.br
.ti -1c
.RI "\fBFMT_UNCHECKED_ITERATOR\fP (\fBappender\fP)"
.br
.ti -1c
.RI "auto \fBoperator++\fP () noexcept \-> \fBappender\fP &"
.br
.ti -1c
.RI "auto \fBoperator++\fP (int) noexcept \-> \fBappender\fP"
.br
.ti -1c
.RI "\fBappender\fP (base it) noexcept"
.br
.ti -1c
.RI "\fBFMT_UNCHECKED_ITERATOR\fP (\fBappender\fP)"
.br
.ti -1c
.RI "auto \fBoperator++\fP () noexcept \-> \fBappender\fP &"
.br
.ti -1c
.RI "auto \fBoperator++\fP (int) noexcept \-> \fBappender\fP"
.br
.ti -1c
.RI "\fBappender\fP (base it) noexcept"
.br
.ti -1c
.RI "\fBFMT_UNCHECKED_ITERATOR\fP (\fBappender\fP)"
.br
.ti -1c
.RI "auto \fBoperator++\fP () noexcept \-> \fBappender\fP &"
.br
.ti -1c
.RI "auto \fBoperator++\fP (int) noexcept \-> \fBappender\fP"
.br
.ti -1c
.RI "\fBappender\fP (base it) noexcept"
.br
.ti -1c
.RI "\fBFMT_UNCHECKED_ITERATOR\fP (\fBappender\fP)"
.br
.ti -1c
.RI "auto \fBoperator++\fP () noexcept \-> \fBappender\fP &"
.br
.ti -1c
.RI "auto \fBoperator++\fP (int) noexcept \-> \fBappender\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename T > auto \fBget_buffer\fP (\fBappender\fP out) \-> detail::buffer< char > &"
.br
.ti -1c
.RI "template<typename T > auto \fBget_buffer\fP (\fBappender\fP out) \-> detail::buffer< char > &"
.br
.ti -1c
.RI "template<typename T > auto \fBget_buffer\fP (\fBappender\fP out) \-> detail::buffer< char > &"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
