.TH "ar" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ar
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBentry_bytes_remaining\fP"
.br
.ti -1c
.RI "size_t \fBentry_bytes_unconsumed\fP"
.br
.ti -1c
.RI "int64_t \fBentry_offset\fP"
.br
.ti -1c
.RI "int64_t \fBentry_padding\fP"
.br
.ti -1c
.RI "char * \fBstrtab\fP"
.br
.ti -1c
.RI "size_t \fBstrtab_size\fP"
.br
.ti -1c
.RI "char \fBread_global_header\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
