.TH "ar_w" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ar_w
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBentry_bytes_remaining\fP"
.br
.ti -1c
.RI "uint64_t \fBentry_padding\fP"
.br
.ti -1c
.RI "int \fBis_strtab\fP"
.br
.ti -1c
.RI "int \fBhas_strtab\fP"
.br
.ti -1c
.RI "char \fBwrote_global_header\fP"
.br
.ti -1c
.RI "char * \fBstrtab\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
