.TH "arabic_fallback_plan_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arabic_fallback_plan_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBnum_lookups\fP"
.br
.ti -1c
.RI "bool \fBfree_lookups\fP"
.br
.ti -1c
.RI "hb_mask_t \fBmask_array\fP [ARABIC_FALLBACK_MAX_LOOKUPS]"
.br
.ti -1c
.RI "\fBOT::SubstLookup\fP * \fBlookup_array\fP [ARABIC_FALLBACK_MAX_LOOKUPS]"
.br
.ti -1c
.RI "\fBOT::hb_ot_layout_lookup_accelerator_t\fP \fBaccel_array\fP [ARABIC_FALLBACK_MAX_LOOKUPS]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
