.TH "archive_entry" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_entry
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBaest\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive\fP * \fBarchive\fP"
.br
.ti -1c
.RI "void * \fBstat\fP"
.br
.ti -1c
.RI "int \fBstat_valid\fP"
.br
.ti -1c
.RI "struct \fBarchive_entry::aest\fP \fBae_stat\fP"
.br
.ti -1c
.RI "int \fBae_set\fP"
.br
.ti -1c
.RI "struct \fBarchive_mstring\fP \fBae_fflags_text\fP"
.br
.ti -1c
.RI "unsigned long \fBae_fflags_set\fP"
.br
.ti -1c
.RI "unsigned long \fBae_fflags_clear\fP"
.br
.ti -1c
.RI "struct \fBarchive_mstring\fP \fBae_gname\fP"
.br
.ti -1c
.RI "struct \fBarchive_mstring\fP \fBae_hardlink\fP"
.br
.ti -1c
.RI "struct \fBarchive_mstring\fP \fBae_pathname\fP"
.br
.ti -1c
.RI "struct \fBarchive_mstring\fP \fBae_symlink\fP"
.br
.ti -1c
.RI "struct \fBarchive_mstring\fP \fBae_uname\fP"
.br
.ti -1c
.RI "struct \fBarchive_mstring\fP \fBae_sourcepath\fP"
.br
.ti -1c
.RI "char \fBencryption\fP"
.br
.ti -1c
.RI "void * \fBmac_metadata\fP"
.br
.ti -1c
.RI "size_t \fBmac_metadata_size\fP"
.br
.ti -1c
.RI "struct \fBae_digest\fP \fBdigest\fP"
.br
.ti -1c
.RI "struct \fBarchive_acl\fP \fBacl\fP"
.br
.ti -1c
.RI "struct \fBae_xattr\fP * \fBxattr_head\fP"
.br
.ti -1c
.RI "struct \fBae_xattr\fP * \fBxattr_p\fP"
.br
.ti -1c
.RI "struct \fBae_sparse\fP * \fBsparse_head\fP"
.br
.ti -1c
.RI "struct \fBae_sparse\fP * \fBsparse_tail\fP"
.br
.ti -1c
.RI "struct \fBae_sparse\fP * \fBsparse_p\fP"
.br
.ti -1c
.RI "char \fBstrmode\fP [12]"
.br
.ti -1c
.RI "int \fBae_symlink_type\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
