.TH "archive_cryptor" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_cryptor
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int(* \fBpbkdf2sha1\fP )(const char *pw, size_t pw_len, const uint8_t *salt, size_t salt_len, unsigned rounds, uint8_t *derived_key, size_t derived_key_len)"
.br
.ti -1c
.RI "int(* \fBdecrypto_aes_ctr_init\fP )(archive_crypto_ctx *, const uint8_t *, size_t)"
.br
.ti -1c
.RI "int(* \fBdecrypto_aes_ctr_update\fP )(archive_crypto_ctx *, const uint8_t *, size_t, uint8_t *, size_t *)"
.br
.ti -1c
.RI "int(* \fBdecrypto_aes_ctr_release\fP )(archive_crypto_ctx *)"
.br
.ti -1c
.RI "int(* \fBencrypto_aes_ctr_init\fP )(archive_crypto_ctx *, const uint8_t *, size_t)"
.br
.ti -1c
.RI "int(* \fBencrypto_aes_ctr_update\fP )(archive_crypto_ctx *, const uint8_t *, size_t, uint8_t *, size_t *)"
.br
.ti -1c
.RI "int(* \fBencrypto_aes_ctr_release\fP )(archive_crypto_ctx *)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
