.TH "archive_entry_linkresolver" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_entry_linkresolver
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBlinks_entry\fP ** \fBbuckets\fP"
.br
.ti -1c
.RI "struct \fBlinks_entry\fP * \fBspare\fP"
.br
.ti -1c
.RI "unsigned long \fBnumber_entries\fP"
.br
.ti -1c
.RI "size_t \fBnumber_buckets\fP"
.br
.ti -1c
.RI "int \fBstrategy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
