.TH "archive_write_filter" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_write_filter
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBbytes_written\fP"
.br
.ti -1c
.RI "struct \fBarchive\fP * \fBarchive\fP"
.br
.ti -1c
.RI "struct \fBarchive_write_filter\fP * \fBnext_filter\fP"
.br
.ti -1c
.RI "int(* \fBoptions\fP )(struct \fBarchive_write_filter\fP *, const char *key, const char *\fBvalue\fP)"
.br
.ti -1c
.RI "int(* \fBopen\fP )(struct \fBarchive_write_filter\fP *)"
.br
.ti -1c
.RI "int(* \fBwrite\fP )(struct \fBarchive_write_filter\fP *, const void *, size_t)"
.br
.ti -1c
.RI "int(* \fBclose\fP )(struct \fBarchive_write_filter\fP *)"
.br
.ti -1c
.RI "int(* \fBfree\fP )(struct \fBarchive_write_filter\fP *)"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "int \fBbytes_per_block\fP"
.br
.ti -1c
.RI "int \fBbytes_in_last_block\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
