.TH "archive_vtable" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_vtable
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int(* \fBarchive_close\fP )(struct \fBarchive\fP *)"
.br
.ti -1c
.RI "int(* \fBarchive_free\fP )(struct \fBarchive\fP *)"
.br
.ti -1c
.RI "int(* \fBarchive_write_header\fP )(struct \fBarchive\fP *, struct \fBarchive_entry\fP *)"
.br
.ti -1c
.RI "int(* \fBarchive_write_finish_entry\fP )(struct \fBarchive\fP *)"
.br
.ti -1c
.RI "ssize_t(* \fBarchive_write_data\fP )(struct \fBarchive\fP *, const void *, size_t)"
.br
.ti -1c
.RI "ssize_t(* \fBarchive_write_data_block\fP )(struct \fBarchive\fP *, const void *, size_t, int64_t)"
.br
.ti -1c
.RI "int(* \fBarchive_read_next_header\fP )(struct \fBarchive\fP *, struct \fBarchive_entry\fP **)"
.br
.ti -1c
.RI "int(* \fBarchive_read_next_header2\fP )(struct \fBarchive\fP *, struct \fBarchive_entry\fP *)"
.br
.ti -1c
.RI "int(* \fBarchive_read_data_block\fP )(struct \fBarchive\fP *, const void **, size_t *, int64_t *)"
.br
.ti -1c
.RI "int(* \fBarchive_filter_count\fP )(struct \fBarchive\fP *)"
.br
.ti -1c
.RI "int64_t(* \fBarchive_filter_bytes\fP )(struct \fBarchive\fP *, int)"
.br
.ti -1c
.RI "int(* \fBarchive_filter_code\fP )(struct \fBarchive\fP *, int)"
.br
.ti -1c
.RI "const char *(* \fBarchive_filter_name\fP )(struct \fBarchive\fP *, int)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
