.TH "archive_read_filter_vtable" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_read_filter_vtable
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ssize_t(* \fBread\fP )(struct \fBarchive_read_filter\fP *, const void **)"
.br
.ti -1c
.RI "int(* \fBclose\fP )(struct \fBarchive_read_filter\fP *self)"
.br
.ti -1c
.RI "int(* \fBread_header\fP )(struct \fBarchive_read_filter\fP *self, struct \fBarchive_entry\fP *\fBentry\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
