.TH "archive_digest" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_digest
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int(* \fBmd5init\fP )(archive_md5_ctx *ctx)"
.br
.ti -1c
.RI "int(* \fBmd5update\fP )(archive_md5_ctx *, const void *, size_t)"
.br
.ti -1c
.RI "int(* \fBmd5final\fP )(archive_md5_ctx *, void *)"
.br
.ti -1c
.RI "int(* \fBrmd160init\fP )(archive_rmd160_ctx *)"
.br
.ti -1c
.RI "int(* \fBrmd160update\fP )(archive_rmd160_ctx *, const void *, size_t)"
.br
.ti -1c
.RI "int(* \fBrmd160final\fP )(archive_rmd160_ctx *, void *)"
.br
.ti -1c
.RI "int(* \fBsha1init\fP )(archive_sha1_ctx *)"
.br
.ti -1c
.RI "int(* \fBsha1update\fP )(archive_sha1_ctx *, const void *, size_t)"
.br
.ti -1c
.RI "int(* \fBsha1final\fP )(archive_sha1_ctx *, void *)"
.br
.ti -1c
.RI "int(* \fBsha256init\fP )(archive_sha256_ctx *)"
.br
.ti -1c
.RI "int(* \fBsha256update\fP )(archive_sha256_ctx *, const void *, size_t)"
.br
.ti -1c
.RI "int(* \fBsha256final\fP )(archive_sha256_ctx *, void *)"
.br
.ti -1c
.RI "int(* \fBsha384init\fP )(archive_sha384_ctx *)"
.br
.ti -1c
.RI "int(* \fBsha384update\fP )(archive_sha384_ctx *, const void *, size_t)"
.br
.ti -1c
.RI "int(* \fBsha384final\fP )(archive_sha384_ctx *, void *)"
.br
.ti -1c
.RI "int(* \fBsha512init\fP )(archive_sha512_ctx *)"
.br
.ti -1c
.RI "int(* \fBsha512update\fP )(archive_sha512_ctx *, const void *, size_t)"
.br
.ti -1c
.RI "int(* \fBsha512final\fP )(archive_sha512_ctx *, void *)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
