.TH "archive_dir_entry" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_dir_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive_dir_entry\fP * \fBnext\fP"
.br
.ti -1c
.RI "time_t \fBmtime_sec\fP"
.br
.ti -1c
.RI "int \fBmtime_nsec\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
