.TH "archive_read::archive_format_descriptor" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_read::archive_format_descriptor
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int(* \fBbid\fP )(struct \fBarchive_read\fP *, int best_bid)"
.br
.ti -1c
.RI "int(* \fBoptions\fP )(struct \fBarchive_read\fP *, const char *key, const char *\fBvalue\fP)"
.br
.ti -1c
.RI "int(* \fBread_header\fP )(struct \fBarchive_read\fP *, struct \fBarchive_entry\fP *)"
.br
.ti -1c
.RI "int(* \fBread_data\fP )(struct \fBarchive_read\fP *, const void **, size_t *, int64_t *)"
.br
.ti -1c
.RI "int(* \fBread_data_skip\fP )(struct \fBarchive_read\fP *)"
.br
.ti -1c
.RI "int64_t(* \fBseek_data\fP )(struct \fBarchive_read\fP *, int64_t, int)"
.br
.ti -1c
.RI "int(* \fBcleanup\fP )(struct \fBarchive_read\fP *)"
.br
.ti -1c
.RI "int(* \fBformat_capabilties\fP )(struct \fBarchive_read\fP *)"
.br
.ti -1c
.RI "int(* \fBhas_encrypted_entries\fP )(struct \fBarchive_read\fP *)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
