.TH "archive_read_client" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_read_client
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "archive_open_callback * \fBopener\fP"
.br
.ti -1c
.RI "archive_read_callback * \fBreader\fP"
.br
.ti -1c
.RI "archive_skip_callback * \fBskipper\fP"
.br
.ti -1c
.RI "archive_seek_callback * \fBseeker\fP"
.br
.ti -1c
.RI "archive_close_callback * \fBcloser\fP"
.br
.ti -1c
.RI "archive_switch_callback * \fBswitcher\fP"
.br
.ti -1c
.RI "unsigned int \fBnodes\fP"
.br
.ti -1c
.RI "unsigned int \fBcursor\fP"
.br
.ti -1c
.RI "int64_t \fBposition\fP"
.br
.ti -1c
.RI "struct \fBarchive_read_data_node\fP * \fBdataset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
