.TH "archive_write_disk" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_write_disk
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive\fP \fBarchive\fP"
.br
.ti -1c
.RI "mode_t \fBuser_umask\fP"
.br
.ti -1c
.RI "struct \fBfixup_entry\fP * \fBfixup_list\fP"
.br
.ti -1c
.RI "struct \fBfixup_entry\fP * \fBcurrent_fixup\fP"
.br
.ti -1c
.RI "int64_t \fBuser_uid\fP"
.br
.ti -1c
.RI "int \fBskip_file_set\fP"
.br
.ti -1c
.RI "int64_t \fBskip_file_dev\fP"
.br
.ti -1c
.RI "int64_t \fBskip_file_ino\fP"
.br
.ti -1c
.RI "time_t \fBstart_time\fP"
.br
.ti -1c
.RI "int64_t(* \fBlookup_gid\fP )(void *private, const char *gname, int64_t gid)"
.br
.ti -1c
.RI "void(* \fBcleanup_gid\fP )(void *private)"
.br
.ti -1c
.RI "void * \fBlookup_gid_data\fP"
.br
.ti -1c
.RI "int64_t(* \fBlookup_uid\fP )(void *private, const char *uname, int64_t uid)"
.br
.ti -1c
.RI "void(* \fBcleanup_uid\fP )(void *private)"
.br
.ti -1c
.RI "void * \fBlookup_uid_data\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBpath_safe\fP"
.br
.ti -1c
.RI "struct stat \fBst\fP"
.br
.ti -1c
.RI "struct stat * \fBpst\fP"
.br
.ti -1c
.RI "struct \fBarchive_entry\fP * \fBentry\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fB_name_data\fP"
.br
.ti -1c
.RI "char * \fBtmpname\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fB_tmpname_data\fP"
.br
.ti -1c
.RI "int \fBtodo\fP"
.br
.ti -1c
.RI "int \fBdeferred\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "int64_t \fBoffset\fP"
.br
.ti -1c
.RI "int64_t \fBfd_offset\fP"
.br
.ti -1c
.RI "int64_t \fBtotal_bytes_written\fP"
.br
.ti -1c
.RI "int64_t \fBfilesize\fP"
.br
.ti -1c
.RI "int \fBrestore_pwd\fP"
.br
.ti -1c
.RI "mode_t \fBmode\fP"
.br
.ti -1c
.RI "int64_t \fBuid\fP"
.br
.ti -1c
.RI "int64_t \fBgid\fP"
.br
.ti -1c
.RI "uint32_t \fBdecmpfs_attr_size\fP"
.br
.ti -1c
.RI "unsigned char * \fBdecmpfs_header_p\fP"
.br
.ti -1c
.RI "int \fBrsrc_xattr_options\fP"
.br
.ti -1c
.RI "unsigned char * \fBresource_fork\fP"
.br
.ti -1c
.RI "size_t \fBresource_fork_allocated_size\fP"
.br
.ti -1c
.RI "unsigned int \fBdecmpfs_block_count\fP"
.br
.ti -1c
.RI "uint32_t * \fBdecmpfs_block_info\fP"
.br
.ti -1c
.RI "unsigned char * \fBcompressed_buffer\fP"
.br
.ti -1c
.RI "size_t \fBcompressed_buffer_size\fP"
.br
.ti -1c
.RI "size_t \fBcompressed_buffer_remaining\fP"
.br
.ti -1c
.RI "uint32_t \fBcompressed_rsrc_position\fP"
.br
.ti -1c
.RI "uint32_t \fBcompressed_rsrc_position_v\fP"
.br
.ti -1c
.RI "char * \fBuncompressed_buffer\fP"
.br
.ti -1c
.RI "size_t \fBblock_remaining_bytes\fP"
.br
.ti -1c
.RI "size_t \fBfile_remaining_bytes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
