.TH "archive" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBmagic\fP"
.br
.ti -1c
.RI "unsigned int \fBstate\fP"
.br
.ti -1c
.RI "const struct \fBarchive_vtable\fP * \fBvtable\fP"
.br
.ti -1c
.RI "int \fBarchive_format\fP"
.br
.ti -1c
.RI "const char * \fBarchive_format_name\fP"
.br
.ti -1c
.RI "int \fBfile_count\fP"
.br
.ti -1c
.RI "int \fBarchive_error_number\fP"
.br
.ti -1c
.RI "const char * \fBerror\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBerror_string\fP"
.br
.ti -1c
.RI "char * \fBcurrent_code\fP"
.br
.ti -1c
.RI "unsigned \fBcurrent_codepage\fP"
.br
.ti -1c
.RI "unsigned \fBcurrent_oemcp\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv\fP"
.br
.ti -1c
.RI "const char * \fBread_data_block\fP"
.br
.ti -1c
.RI "int64_t \fBread_data_offset\fP"
.br
.ti -1c
.RI "int64_t \fBread_data_output_offset\fP"
.br
.ti -1c
.RI "size_t \fBread_data_remaining\fP"
.br
.ti -1c
.RI "char \fBread_data_is_posix_read\fP"
.br
.ti -1c
.RI "size_t \fBread_data_requested\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
