.TH "archive_acl" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_acl
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "mode_t \fBmode\fP"
.br
.ti -1c
.RI "struct \fBarchive_acl_entry\fP * \fBacl_head\fP"
.br
.ti -1c
.RI "struct \fBarchive_acl_entry\fP * \fBacl_p\fP"
.br
.ti -1c
.RI "int \fBacl_state\fP"
.br
.ti -1c
.RI "wchar_t * \fBacl_text_w\fP"
.br
.ti -1c
.RI "char * \fBacl_text\fP"
.br
.ti -1c
.RI "int \fBacl_types\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
