.TH "archive_acl_entry" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_acl_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive_acl_entry\fP * \fBnext\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBtag\fP"
.br
.ti -1c
.RI "int \fBpermset\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "struct \fBarchive_mstring\fP \fBname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
