.TH "archive_xxhash" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_xxhash
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int(* \fBXXH32\fP )(const void *\fBinput\fP, unsigned int len, unsigned int seed)"
.br
.ti -1c
.RI "void *(* \fBXXH32_init\fP )(unsigned int seed)"
.br
.ti -1c
.RI "XXH_errorcode(* \fBXXH32_update\fP )(void *\fBstate\fP, const void *\fBinput\fP, unsigned int len)"
.br
.ti -1c
.RI "unsigned int(* \fBXXH32_digest\fP )(void *\fBstate\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
