.TH "archive_rb_tree_ops" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_rb_tree_ops
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "archive_rbto_compare_nodes_fn \fBrbto_compare_nodes\fP"
.br
.ti -1c
.RI "archive_rbto_compare_key_fn \fBrbto_compare_key\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
