.TH "archive_read_disk" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_read_disk
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive\fP \fBarchive\fP"
.br
.ti -1c
.RI "struct \fBarchive_entry\fP * \fBentry\fP"
.br
.ti -1c
.RI "char \fBsymlink_mode\fP"
.br
.ti -1c
.RI "char \fBfollow_symlinks\fP"
.br
.ti -1c
.RI "struct \fBtree\fP * \fBtree\fP"
.br
.ti -1c
.RI "int(* \fBopen_on_current_dir\fP )(struct \fBtree\fP *, const char *, int)"
.br
.ti -1c
.RI "int(* \fBtree_current_dir_fd\fP )(struct \fBtree\fP *)"
.br
.ti -1c
.RI "int(* \fBtree_enter_working_dir\fP )(struct \fBtree\fP *)"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "const char *(* \fBlookup_gname\fP )(void *private, int64_t gid)"
.br
.ti -1c
.RI "void(* \fBcleanup_gname\fP )(void *private)"
.br
.ti -1c
.RI "void * \fBlookup_gname_data\fP"
.br
.ti -1c
.RI "const char *(* \fBlookup_uname\fP )(void *private, int64_t uid)"
.br
.ti -1c
.RI "void(* \fBcleanup_uname\fP )(void *private)"
.br
.ti -1c
.RI "void * \fBlookup_uname_data\fP"
.br
.ti -1c
.RI "int(* \fBmetadata_filter_func\fP )(struct \fBarchive\fP *, void *, struct \fBarchive_entry\fP *)"
.br
.ti -1c
.RI "void * \fBmetadata_filter_data\fP"
.br
.ti -1c
.RI "struct \fBarchive\fP * \fBmatching\fP"
.br
.ti -1c
.RI "void(* \fBexcluded_cb_func\fP )(struct \fBarchive\fP *, void *, struct \fBarchive_entry\fP *)"
.br
.ti -1c
.RI "void * \fBexcluded_cb_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
