.TH "archive_entry::aest" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_entry::aest
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBaest_atime\fP"
.br
.ti -1c
.RI "uint32_t \fBaest_atime_nsec\fP"
.br
.ti -1c
.RI "int64_t \fBaest_ctime\fP"
.br
.ti -1c
.RI "uint32_t \fBaest_ctime_nsec\fP"
.br
.ti -1c
.RI "int64_t \fBaest_mtime\fP"
.br
.ti -1c
.RI "uint32_t \fBaest_mtime_nsec\fP"
.br
.ti -1c
.RI "int64_t \fBaest_birthtime\fP"
.br
.ti -1c
.RI "uint32_t \fBaest_birthtime_nsec\fP"
.br
.ti -1c
.RI "int64_t \fBaest_gid\fP"
.br
.ti -1c
.RI "int64_t \fBaest_ino\fP"
.br
.ti -1c
.RI "uint32_t \fBaest_nlink\fP"
.br
.ti -1c
.RI "uint64_t \fBaest_size\fP"
.br
.ti -1c
.RI "int64_t \fBaest_uid\fP"
.br
.ti -1c
.RI "int \fBaest_dev_is_broken_down\fP"
.br
.ti -1c
.RI "dev_t \fBaest_dev\fP"
.br
.ti -1c
.RI "dev_t \fBaest_devmajor\fP"
.br
.ti -1c
.RI "dev_t \fBaest_devminor\fP"
.br
.ti -1c
.RI "int \fBaest_rdev_is_broken_down\fP"
.br
.ti -1c
.RI "dev_t \fBaest_rdev\fP"
.br
.ti -1c
.RI "dev_t \fBaest_rdevmajor\fP"
.br
.ti -1c
.RI "dev_t \fBaest_rdevminor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
