.TH "archive_write" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_write
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive\fP \fBarchive\fP"
.br
.ti -1c
.RI "int \fBskip_file_set\fP"
.br
.ti -1c
.RI "int64_t \fBskip_file_dev\fP"
.br
.ti -1c
.RI "int64_t \fBskip_file_ino\fP"
.br
.ti -1c
.RI "const unsigned char * \fBnulls\fP"
.br
.ti -1c
.RI "size_t \fBnull_length\fP"
.br
.ti -1c
.RI "archive_open_callback * \fBclient_opener\fP"
.br
.ti -1c
.RI "archive_write_callback * \fBclient_writer\fP"
.br
.ti -1c
.RI "archive_close_callback * \fBclient_closer\fP"
.br
.ti -1c
.RI "archive_free_callback * \fBclient_freer\fP"
.br
.ti -1c
.RI "void * \fBclient_data\fP"
.br
.ti -1c
.RI "int \fBbytes_per_block\fP"
.br
.ti -1c
.RI "int \fBbytes_in_last_block\fP"
.br
.ti -1c
.RI "struct \fBarchive_write_filter\fP * \fBfilter_first\fP"
.br
.ti -1c
.RI "struct \fBarchive_write_filter\fP * \fBfilter_last\fP"
.br
.ti -1c
.RI "void * \fBformat_data\fP"
.br
.ti -1c
.RI "const char * \fBformat_name\fP"
.br
.ti -1c
.RI "int(* \fBformat_init\fP )(struct \fBarchive_write\fP *)"
.br
.ti -1c
.RI "int(* \fBformat_options\fP )(struct \fBarchive_write\fP *, const char *key, const char *\fBvalue\fP)"
.br
.ti -1c
.RI "int(* \fBformat_finish_entry\fP )(struct \fBarchive_write\fP *)"
.br
.ti -1c
.RI "int(* \fBformat_write_header\fP )(struct \fBarchive_write\fP *, struct \fBarchive_entry\fP *)"
.br
.ti -1c
.RI "ssize_t(* \fBformat_write_data\fP )(struct \fBarchive_write\fP *, const void *buff, size_t)"
.br
.ti -1c
.RI "int(* \fBformat_close\fP )(struct \fBarchive_write\fP *)"
.br
.ti -1c
.RI "int(* \fBformat_free\fP )(struct \fBarchive_write\fP *)"
.br
.ti -1c
.RI "char * \fBpassphrase\fP"
.br
.ti -1c
.RI "archive_passphrase_callback * \fBpassphrase_callback\fP"
.br
.ti -1c
.RI "void * \fBpassphrase_client_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
