.TH "archive_read_filter" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_read_filter
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBposition\fP"
.br
.ti -1c
.RI "struct \fBarchive_read_filter_bidder\fP * \fBbidder\fP"
.br
.ti -1c
.RI "struct \fBarchive_read_filter\fP * \fBupstream\fP"
.br
.ti -1c
.RI "struct \fBarchive_read\fP * \fBarchive\fP"
.br
.ti -1c
.RI "const struct \fBarchive_read_filter_vtable\fP * \fBvtable\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "int \fBcan_skip\fP"
.br
.ti -1c
.RI "int \fBcan_seek\fP"
.br
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.ti -1c
.RI "size_t \fBbuffer_size\fP"
.br
.ti -1c
.RI "char * \fBnext\fP"
.br
.ti -1c
.RI "size_t \fBavail\fP"
.br
.ti -1c
.RI "const void * \fBclient_buff\fP"
.br
.ti -1c
.RI "size_t \fBclient_total\fP"
.br
.ti -1c
.RI "const char * \fBclient_next\fP"
.br
.ti -1c
.RI "size_t \fBclient_avail\fP"
.br
.ti -1c
.RI "char \fBend_of_file\fP"
.br
.ti -1c
.RI "char \fBclosed\fP"
.br
.ti -1c
.RI "char \fBfatal\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
