.TH "archive_match" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_match
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive\fP \fBarchive\fP"
.br
.ti -1c
.RI "int \fBsetflag\fP"
.br
.ti -1c
.RI "int \fBrecursive_include\fP"
.br
.ti -1c
.RI "struct \fBmatch_list\fP \fBexclusions\fP"
.br
.ti -1c
.RI "struct \fBmatch_list\fP \fBinclusions\fP"
.br
.ti -1c
.RI "time_t \fBnow\fP"
.br
.ti -1c
.RI "int \fBnewer_mtime_filter\fP"
.br
.ti -1c
.RI "time_t \fBnewer_mtime_sec\fP"
.br
.ti -1c
.RI "long \fBnewer_mtime_nsec\fP"
.br
.ti -1c
.RI "int \fBnewer_ctime_filter\fP"
.br
.ti -1c
.RI "time_t \fBnewer_ctime_sec\fP"
.br
.ti -1c
.RI "long \fBnewer_ctime_nsec\fP"
.br
.ti -1c
.RI "int \fBolder_mtime_filter\fP"
.br
.ti -1c
.RI "time_t \fBolder_mtime_sec\fP"
.br
.ti -1c
.RI "long \fBolder_mtime_nsec\fP"
.br
.ti -1c
.RI "int \fBolder_ctime_filter\fP"
.br
.ti -1c
.RI "time_t \fBolder_ctime_sec\fP"
.br
.ti -1c
.RI "long \fBolder_ctime_nsec\fP"
.br
.ti -1c
.RI "struct \fBarchive_rb_tree\fP \fBexclusion_tree\fP"
.br
.ti -1c
.RI "struct \fBentry_list\fP \fBexclusion_entry_list\fP"
.br
.ti -1c
.RI "struct \fBid_array\fP \fBinclusion_uids\fP"
.br
.ti -1c
.RI "struct \fBid_array\fP \fBinclusion_gids\fP"
.br
.ti -1c
.RI "struct \fBmatch_list\fP \fBinclusion_unames\fP"
.br
.ti -1c
.RI "struct \fBmatch_list\fP \fBinclusion_gnames\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
