.TH "archive_read" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_read
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBarchive_format_descriptor\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive\fP \fBarchive\fP"
.br
.ti -1c
.RI "struct \fBarchive_entry\fP * \fBentry\fP"
.br
.ti -1c
.RI "int \fBskip_file_set\fP"
.br
.ti -1c
.RI "int64_t \fBskip_file_dev\fP"
.br
.ti -1c
.RI "int64_t \fBskip_file_ino\fP"
.br
.ti -1c
.RI "struct \fBarchive_read_client\fP \fBclient\fP"
.br
.ti -1c
.RI "struct \fBarchive_read_filter_bidder\fP \fBbidders\fP [16]"
.br
.ti -1c
.RI "struct \fBarchive_read_filter\fP * \fBfilter\fP"
.br
.ti -1c
.RI "int \fBbypass_filter_bidding\fP"
.br
.ti -1c
.RI "int64_t \fBheader_position\fP"
.br
.ti -1c
.RI "unsigned int \fBdata_start_node\fP"
.br
.ti -1c
.RI "unsigned int \fBdata_end_node\fP"
.br
.ti -1c
.RI "struct \fBarchive_read::archive_format_descriptor\fP \fBformats\fP [16]"
.br
.ti -1c
.RI "struct \fBarchive_format_descriptor\fP * \fBformat\fP"
.br
.ti -1c
.RI "struct \fBarchive_read_extract\fP * \fBextract\fP"
.br
.ti -1c
.RI "int(* \fBcleanup_archive_extract\fP )(struct \fBarchive_read\fP *)"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBarchive_read_passphrase\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBarchive_read_passphrase\fP ** \fBlast\fP"
.br
.ti -1c
.RI "   int \fBcandidate\fP"
.br
.ti -1c
.RI "   archive_passphrase_callback * \fBcallback\fP"
.br
.ti -1c
.RI "   void * \fBclient_data\fP"
.br
.ti -1c
.RI "} \fBpassphrases\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
