.TH "archive_entry_header_gnutar" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_entry_header_gnutar
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBname\fP [100]"
.br
.ti -1c
.RI "char \fBmode\fP [8]"
.br
.ti -1c
.RI "char \fBuid\fP [8]"
.br
.ti -1c
.RI "char \fBgid\fP [8]"
.br
.ti -1c
.RI "char \fBsize\fP [12]"
.br
.ti -1c
.RI "char \fBmtime\fP [12]"
.br
.ti -1c
.RI "char \fBchecksum\fP [8]"
.br
.ti -1c
.RI "char \fBtypeflag\fP [1]"
.br
.ti -1c
.RI "char \fBlinkname\fP [100]"
.br
.ti -1c
.RI "char \fBmagic\fP [8]"
.br
.ti -1c
.RI "char \fBuname\fP [32]"
.br
.ti -1c
.RI "char \fBgname\fP [32]"
.br
.ti -1c
.RI "char \fBrdevmajor\fP [8]"
.br
.ti -1c
.RI "char \fBrdevminor\fP [8]"
.br
.ti -1c
.RI "char \fBatime\fP [12]"
.br
.ti -1c
.RI "char \fBctime\fP [12]"
.br
.ti -1c
.RI "char \fBoffset\fP [12]"
.br
.ti -1c
.RI "char \fBlongnames\fP [4]"
.br
.ti -1c
.RI "char \fBunused\fP [1]"
.br
.ti -1c
.RI "struct \fBgnu_sparse\fP \fBsparse\fP [4]"
.br
.ti -1c
.RI "char \fBisextended\fP [1]"
.br
.ti -1c
.RI "char \fBrealsize\fP [12]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
