.TH "archive_mstring" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_mstring
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive_string\fP \fBaes_mbs\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBaes_utf8\fP"
.br
.ti -1c
.RI "struct \fBarchive_wstring\fP \fBaes_wcs\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBaes_mbs_in_locale\fP"
.br
.ti -1c
.RI "int \fBaes_set\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
