.TH "archive_string_conv" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
archive_string_conv
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBfrom_charset\fP"
.br
.ti -1c
.RI "char * \fBto_charset\fP"
.br
.ti -1c
.RI "unsigned \fBfrom_cp\fP"
.br
.ti -1c
.RI "unsigned \fBto_cp\fP"
.br
.ti -1c
.RI "int \fBsame\fP"
.br
.ti -1c
.RI "int \fBflag\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fButftmp\fP"
.br
.ti -1c
.RI "int(* \fBconverter\fP [2])(struct \fBarchive_string\fP *, const void *, size_t, struct \fBarchive_string_conv\fP *)"
.br
.ti -1c
.RI "int \fBnconverter\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
