.TH "arg_ref< Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg_ref< Char >
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBvalue\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBarg_ref\fP (int index)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBarg_ref\fP (\fBbasic_string_view\fP< Char > name)"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBoperator=\fP (int idx) \-> \fBarg_ref\fP &"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBarg_ref\fP (int index)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBarg_ref\fP (\fBbasic_string_view\fP< Char > name)"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBoperator=\fP (int idx) \-> \fBarg_ref\fP &"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBarg_ref\fP (int index)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBarg_ref\fP (\fBbasic_string_view\fP< Char > name)"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBoperator=\fP (int idx) \-> \fBarg_ref\fP &"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBarg_ref\fP (int index)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBarg_ref\fP (\fBbasic_string_view\fP< Char > name)"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBoperator=\fP (int idx) \-> \fBarg_ref\fP &"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "arg_id_kind \fBkind\fP"
.br
.ti -1c
.RI "union \fBarg_ref::value\fP \fBval\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
