.TH "arg_data< T, Char, NUM_ARGS, NUM_NAMED_ARGS >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg_data< T, Char, NUM_ARGS, NUM_NAMED_ARGS >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. U> \fBarg_data\fP (const U &\&.\&.\&. init)"
.br
.ti -1c
.RI "\fBarg_data\fP (const \fBarg_data\fP &other)=delete"
.br
.ti -1c
.RI "auto \fBargs\fP () const \-> const T *"
.br
.ti -1c
.RI "auto \fBnamed_args\fP () \-> \fBnamed_arg_info\fP< Char > *"
.br
.ti -1c
.RI "template<typename\&.\&.\&. U> \fBarg_data\fP (const U &\&.\&.\&. init)"
.br
.ti -1c
.RI "\fBarg_data\fP (const \fBarg_data\fP &other)=delete"
.br
.ti -1c
.RI "auto \fBargs\fP () const \-> const T *"
.br
.ti -1c
.RI "auto \fBnamed_args\fP () \-> \fBnamed_arg_info\fP< Char > *"
.br
.ti -1c
.RI "template<typename\&.\&.\&. U> \fBarg_data\fP (const U &\&.\&.\&. init)"
.br
.ti -1c
.RI "\fBarg_data\fP (const \fBarg_data\fP &other)=delete"
.br
.ti -1c
.RI "auto \fBargs\fP () const \-> const T *"
.br
.ti -1c
.RI "auto \fBnamed_args\fP () \-> \fBnamed_arg_info\fP< Char > *"
.br
.ti -1c
.RI "template<typename\&.\&.\&. U> \fBarg_data\fP (const U &\&.\&.\&. init)"
.br
.ti -1c
.RI "\fBarg_data\fP (const \fBarg_data\fP &other)=delete"
.br
.ti -1c
.RI "auto \fBargs\fP () const \-> const T *"
.br
.ti -1c
.RI "auto \fBnamed_args\fP () \-> \fBnamed_arg_info\fP< Char > *"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBargs_\fP [1+(NUM_ARGS !=0 ? NUM_ARGS :+1)]"
.br
.ti -1c
.RI "\fBnamed_arg_info\fP< Char > \fBnamed_args_\fP [NUM_NAMED_ARGS]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
