.TH "arg_ref< Char >::value" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg_ref< Char >::value
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBvalue\fP (int id=0)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBvalue\fP (\fBbasic_string_view\fP< Char > n)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBvalue\fP (int id=0)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBvalue\fP (\fBbasic_string_view\fP< Char > n)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBvalue\fP (int id=0)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBvalue\fP (\fBbasic_string_view\fP< Char > n)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBvalue\fP (int id=0)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBvalue\fP (\fBbasic_string_view\fP< Char > n)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "\fBbasic_string_view\fP< Char > \fBname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
