.TH "arg_formatter< Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg_formatter< Char >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBprintf_arg_formatter< OutputIt, Char >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBiterator\fP = buffer_appender< Char >"
.br
.ti -1c
.RI "using \fBcontext\fP = \fBbuffer_context\fP< Char >"
.br
.ti -1c
.RI "using \fBiterator\fP = buffer_appender< Char >"
.br
.ti -1c
.RI "using \fBcontext\fP = \fBbuffer_context\fP< Char >"
.br
.ti -1c
.RI "using \fBiterator\fP = buffer_appender< Char >"
.br
.ti -1c
.RI "using \fBcontext\fP = \fBbuffer_context\fP< Char >"
.br
.ti -1c
.RI "using \fBiterator\fP = buffer_appender< Char >"
.br
.ti -1c
.RI "using \fBcontext\fP = \fBbuffer_context\fP< Char >"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > FMT_CONSTEXPR FMT_INLINE auto \fBoperator()\fP (T \fBvalue\fP) \-> iterator"
.br
.ti -1c
.RI "auto \fBoperator()\fP (typename \fBbasic_format_arg\fP< \fBcontext\fP >::handle) \-> iterator"
.br
.ti -1c
.RI "template<typename T > FMT_CONSTEXPR FMT_INLINE auto \fBoperator()\fP (T \fBvalue\fP) \-> iterator"
.br
.ti -1c
.RI "auto \fBoperator()\fP (typename \fBbasic_format_arg\fP< \fBcontext\fP >::handle) \-> iterator"
.br
.ti -1c
.RI "template<typename T > FMT_CONSTEXPR FMT_INLINE auto \fBoperator()\fP (T \fBvalue\fP) \-> iterator"
.br
.ti -1c
.RI "auto \fBoperator()\fP (typename \fBbasic_format_arg\fP< \fBcontext\fP >::handle) \-> iterator"
.br
.ti -1c
.RI "template<typename T > FMT_CONSTEXPR FMT_INLINE auto \fBoperator()\fP (T \fBvalue\fP) \-> iterator"
.br
.ti -1c
.RI "auto \fBoperator()\fP (typename \fBbasic_format_arg\fP< \fBcontext\fP >::handle) \-> iterator"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "iterator \fBout\fP"
.br
.ti -1c
.RI "const \fBbasic_format_specs\fP< Char > & \fBspecs\fP"
.br
.ti -1c
.RI "\fBlocale_ref\fP \fBlocale\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
