.TH "arg_data< T, Char, NUM_ARGS, 0 >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg_data< T, Char, NUM_ARGS, 0 >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. U> FMT_CONSTEXPR FMT_INLINE \fBarg_data\fP (const U &\&.\&.\&. init)"
.br
.ti -1c
.RI "FMT_CONSTEXPR FMT_INLINE auto \fBargs\fP () const \-> const T *"
.br
.ti -1c
.RI "FMT_CONSTEXPR FMT_INLINE auto \fBnamed_args\fP () \-> std::nullptr_t"
.br
.ti -1c
.RI "template<typename\&.\&.\&. U> FMT_CONSTEXPR FMT_INLINE \fBarg_data\fP (const U &\&.\&.\&. init)"
.br
.ti -1c
.RI "FMT_CONSTEXPR FMT_INLINE auto \fBargs\fP () const \-> const T *"
.br
.ti -1c
.RI "FMT_CONSTEXPR FMT_INLINE auto \fBnamed_args\fP () \-> std::nullptr_t"
.br
.ti -1c
.RI "template<typename\&.\&.\&. U> FMT_CONSTEXPR FMT_INLINE \fBarg_data\fP (const U &\&.\&.\&. init)"
.br
.ti -1c
.RI "FMT_CONSTEXPR FMT_INLINE auto \fBargs\fP () const \-> const T *"
.br
.ti -1c
.RI "FMT_CONSTEXPR FMT_INLINE auto \fBnamed_args\fP () \-> std::nullptr_t"
.br
.ti -1c
.RI "template<typename\&.\&.\&. U> FMT_CONSTEXPR FMT_INLINE \fBarg_data\fP (const U &\&.\&.\&. init)"
.br
.ti -1c
.RI "FMT_CONSTEXPR FMT_INLINE auto \fBargs\fP () const \-> const T *"
.br
.ti -1c
.RI "FMT_CONSTEXPR FMT_INLINE auto \fBnamed_args\fP () \-> std::nullptr_t"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBargs_\fP [NUM_ARGS !=0 ? NUM_ARGS :+1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
