.TH "arg_converter< T, Context >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg_converter< T, Context >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBarg_converter\fP (\fBbasic_format_arg\fP< \fBContext\fP > &arg, char_type type)"
.br
.ti -1c
.RI "void \fBoperator()\fP (bool \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename U , FMT_ENABLE_IF(std::is_integral< U >\fB::value\fP) > void \fBoperator()\fP (U \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename U , FMT_ENABLE_IF(!std::is_integral< U >\fB::value\fP) > void \fBoperator()\fP (U)"
.br
.ti -1c
.RI "\fBarg_converter\fP (\fBbasic_format_arg\fP< \fBContext\fP > &arg, char_type type)"
.br
.ti -1c
.RI "void \fBoperator()\fP (bool \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename U , FMT_ENABLE_IF(std::is_integral< U >\fB::value\fP) > void \fBoperator()\fP (U \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename U , FMT_ENABLE_IF(!std::is_integral< U >\fB::value\fP) > void \fBoperator()\fP (U)"
.br
.ti -1c
.RI "\fBarg_converter\fP (\fBbasic_format_arg\fP< \fBContext\fP > &arg, char_type type)"
.br
.ti -1c
.RI "void \fBoperator()\fP (bool \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename U , FMT_ENABLE_IF(std::is_integral< U >\fB::value\fP) > void \fBoperator()\fP (U \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename U , FMT_ENABLE_IF(!std::is_integral< U >\fB::value\fP) > void \fBoperator()\fP (U)"
.br
.ti -1c
.RI "\fBarg_converter\fP (\fBbasic_format_arg\fP< \fBContext\fP > &arg, char_type type)"
.br
.ti -1c
.RI "void \fBoperator()\fP (bool \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename U , FMT_ENABLE_IF(std::is_integral< U >\fB::value\fP) > void \fBoperator()\fP (U \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename U , FMT_ENABLE_IF(!std::is_integral< U >\fB::value\fP) > void \fBoperator()\fP (U)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
