.TH "arg_mapper< Context >::formattable< T, U >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg_mapper< Context >::formattable< T, U >
.SH SYNOPSIS
.br
.PP
.PP
Inherits bool_constant< has_const_formatter< remove_cvref_t< T >, Context >()||!std::is_const< remove_reference_t< T > >::value||has_fallback_formatter< remove_cvref_t< T >, char_type >::value >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
