.TH "AsepriteThumbCreator" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AsepriteThumbCreator
.SH SYNOPSIS
.br
.PP
.PP
Inherits ThumbCreator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBcreate\fP (const QString &path, int width, int height, QImage &img) override"
.br
.ti -1c
.RI "Flags \fBflags\fP () const override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
