.TH "att_counter_set" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
att_counter_set
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBattr_counter\fP * \fBuid_list\fP"
.br
.ti -1c
.RI "struct \fBattr_counter\fP * \fBgid_list\fP"
.br
.ti -1c
.RI "struct \fBattr_counter\fP * \fBmode_list\fP"
.br
.ti -1c
.RI "struct \fBattr_counter\fP * \fBflags_list\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
