.TH "audio_state" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
audio_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int8_t \fBweight\fP [5]"
.br
.ti -1c
.RI "int16_t \fBdelta\fP [4]"
.br
.ti -1c
.RI "int8_t \fBlastdelta\fP"
.br
.ti -1c
.RI "int \fBerror\fP [11]"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "uint8_t \fBlastbyte\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
