.TH "auth" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
auth
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBIT\fP (done)"
.br
.ti -1c
.RI "\fBBIT\fP (multipass)"
.br
.ti -1c
.RI "\fBBIT\fP (iestyle)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBwant\fP"
.br
.ti -1c
.RI "unsigned long \fBpicked\fP"
.br
.ti -1c
.RI "unsigned long \fBavail\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
