.TH "backing_store_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
backing_store_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, read_backing_store,(\fBj_common_ptr\fP cinfo, \fBbacking_store_ptr\fP info, void FAR *buffer_address, long file_offset, long byte_count))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, write_backing_store,(\fBj_common_ptr\fP cinfo, \fBbacking_store_ptr\fP info, void FAR *buffer_address, long file_offset, long byte_count))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, close_backing_store,(\fBj_common_ptr\fP cinfo, \fBbacking_store_ptr\fP info))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBtemp_file\fP"
.br
.ti -1c
.RI "char \fBtemp_name\fP [TEMP_NAME_LENGTH]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
