.TH "basic_fp< F >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_fp< F >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBbasic_fp\fP (uint64_t f_val, int e_val)"
.br
.ti -1c
.RI "template<typename Float > FMT_CONSTEXPR \fBbasic_fp\fP (Float n)"
.br
.ti -1c
.RI "template<typename Float , FMT_ENABLE_IF(!is_double_double< Float >\fB::value\fP) > FMT_CONSTEXPR auto \fBassign\fP (Float n) \-> bool"
.br
.ti -1c
.RI "template<typename Float , FMT_ENABLE_IF(is_double_double< Float >\fB::value\fP) > FMT_CONSTEXPR auto \fBassign\fP (Float n) \-> bool"
.br
.ti -1c
.RI "constexpr \fBbasic_fp\fP (uint64_t f_val, int e_val)"
.br
.ti -1c
.RI "template<typename Float > FMT_CONSTEXPR \fBbasic_fp\fP (Float n)"
.br
.ti -1c
.RI "template<typename Float , FMT_ENABLE_IF(!is_double_double< Float >\fB::value\fP) > FMT_CONSTEXPR auto \fBassign\fP (Float n) \-> bool"
.br
.ti -1c
.RI "template<typename Float , FMT_ENABLE_IF(is_double_double< Float >\fB::value\fP) > FMT_CONSTEXPR auto \fBassign\fP (Float n) \-> bool"
.br
.ti -1c
.RI "constexpr \fBbasic_fp\fP (uint64_t f_val, int e_val)"
.br
.ti -1c
.RI "template<typename Float > FMT_CONSTEXPR \fBbasic_fp\fP (Float n)"
.br
.ti -1c
.RI "template<typename Float , FMT_ENABLE_IF(!is_double_double< Float >\fB::value\fP) > FMT_CONSTEXPR auto \fBassign\fP (Float n) \-> bool"
.br
.ti -1c
.RI "template<typename Float , FMT_ENABLE_IF(is_double_double< Float >\fB::value\fP) > FMT_CONSTEXPR auto \fBassign\fP (Float n) \-> bool"
.br
.ti -1c
.RI "constexpr \fBbasic_fp\fP (uint64_t f_val, int e_val)"
.br
.ti -1c
.RI "template<typename Float > FMT_CONSTEXPR \fBbasic_fp\fP (Float n)"
.br
.ti -1c
.RI "template<typename Float , FMT_ENABLE_IF(!is_double_double< Float >\fB::value\fP) > FMT_CONSTEXPR auto \fBassign\fP (Float n) \-> bool"
.br
.ti -1c
.RI "template<typename Float , FMT_ENABLE_IF(is_double_double< Float >\fB::value\fP) > FMT_CONSTEXPR auto \fBassign\fP (Float n) \-> bool"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "F \fBf\fP"
.br
.ti -1c
.RI "int \fBe\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr const int \fBnum_significand_bits\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename F > static constexpr const int \fBbasic_fp\fP< F >::num_significand_bits\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
      static_cast<int>(sizeof(F) * num_bits<unsigned char>())
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
