.TH "basic_ostream_formatter< Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_ostream_formatter< Char >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBformatter< basic_string_view< Char >, Char >\fP\&.
.PP
Inherited by \fBdetail::fallback_formatter< T, Char, enable_if_t< is_streamable< T, Char >::value > >\fP, \fBfmt::formatter< abstract >\fP, \fBfmt::formatter< copyfmt_test >\fP, \fBfmt::formatter< date >\fP, \fBfmt::formatter< empty_test >\fP, \fBfmt::formatter< fmt_test::abc >\fP, \fBfmt::formatter< streamable_enum >\fP, \fBfmt::formatter< test_string >\fP, \fBformatter< detail::streamed_view< T >, Char >\fP, and \fBformatter< std::thread::id, Char >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_debug_format\fP ()=delete"
.br
.ti -1c
.RI "template<typename T , typename OutputIt > auto \fBformat\fP (const T &\fBvalue\fP, \fBbasic_format_context\fP< OutputIt, Char > &ctx) const \-> OutputIt"
.br
.ti -1c
.RI "void \fBset_debug_format\fP ()=delete"
.br
.ti -1c
.RI "template<typename T , typename OutputIt > auto \fBformat\fP (const T &\fBvalue\fP, \fBbasic_format_context\fP< OutputIt, Char > &ctx) const \-> OutputIt"
.br
.ti -1c
.RI "void \fBset_debug_format\fP ()=delete"
.br
.ti -1c
.RI "template<typename T , typename OutputIt > auto \fBformat\fP (const T &\fBvalue\fP, \fBbasic_format_context\fP< OutputIt, Char > &ctx) const \-> OutputIt"
.br
.ti -1c
.RI "void \fBset_debug_format\fP ()=delete"
.br
.ti -1c
.RI "template<typename T , typename OutputIt > auto \fBformat\fP (const T &\fBvalue\fP, \fBbasic_format_context\fP< OutputIt, Char > &ctx) const \-> OutputIt"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
