.TH "basic_format_arg< Context >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_format_arg< Context >
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBhandle\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBoperator bool\fP () const noexcept"
.br
.ti -1c
.RI "auto \fBtype\fP () const \-> detail::type"
.br
.ti -1c
.RI "auto \fBis_integral\fP () const \-> bool"
.br
.ti -1c
.RI "auto \fBis_arithmetic\fP () const \-> bool"
.br
.ti -1c
.RI "constexpr \fBoperator bool\fP () const noexcept"
.br
.ti -1c
.RI "auto \fBtype\fP () const \-> detail::type"
.br
.ti -1c
.RI "auto \fBis_integral\fP () const \-> bool"
.br
.ti -1c
.RI "auto \fBis_arithmetic\fP () const \-> bool"
.br
.ti -1c
.RI "constexpr \fBoperator bool\fP () const noexcept"
.br
.ti -1c
.RI "auto \fBtype\fP () const \-> detail::type"
.br
.ti -1c
.RI "auto \fBis_integral\fP () const \-> bool"
.br
.ti -1c
.RI "auto \fBis_arithmetic\fP () const \-> bool"
.br
.ti -1c
.RI "constexpr \fBoperator bool\fP () const noexcept"
.br
.ti -1c
.RI "auto \fBtype\fP () const \-> detail::type"
.br
.ti -1c
.RI "auto \fBis_integral\fP () const \-> bool"
.br
.ti -1c
.RI "auto \fBis_arithmetic\fP () const \-> bool"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBbasic_format_args< Context >\fP"
.br
.ti -1c
.RI "class \fBdynamic_format_arg_store< Context >\fP"
.br
.ti -1c
.RI "template<typename T , typename Char , size_t NUM_ARGS, size_t NUM_NAMED_ARGS> struct \fBdetail::arg_data\fP"
.br
.ti -1c
.RI "template<typename ContextType , typename T > FMT_CONSTEXPR auto \fBdetail::make_arg\fP (T &&\fBvalue\fP) \-> \fBbasic_format_arg\fP< ContextType >"
.br
.ti -1c
.RI "template<typename Visitor , typename Ctx > FMT_CONSTEXPR auto \fBvisit_format_arg\fP (Visitor &&vis, const \fBbasic_format_arg\fP< Ctx > &arg) \-> decltype(vis(0))"
.br
.ti -1c
.RI "template<typename ContextType , typename T > FMT_CONSTEXPR auto \fBdetail::make_arg\fP (T &&\fBvalue\fP) \-> \fBbasic_format_arg\fP< ContextType >"
.br
.ti -1c
.RI "template<typename Visitor , typename Ctx > FMT_CONSTEXPR auto \fBvisit_format_arg\fP (Visitor &&vis, const \fBbasic_format_arg\fP< Ctx > &arg) \-> decltype(vis(0))"
.br
.ti -1c
.RI "template<typename ContextType , typename T > FMT_CONSTEXPR auto \fBdetail::make_arg\fP (T &&\fBvalue\fP) \-> \fBbasic_format_arg\fP< ContextType >"
.br
.ti -1c
.RI "template<typename Visitor , typename Ctx > FMT_CONSTEXPR auto \fBvisit_format_arg\fP (Visitor &&vis, const \fBbasic_format_arg\fP< Ctx > &arg) \-> decltype(vis(0))"
.br
.ti -1c
.RI "template<typename ContextType , typename T > FMT_CONSTEXPR auto \fBdetail::make_arg\fP (T &&\fBvalue\fP) \-> \fBbasic_format_arg\fP< ContextType >"
.br
.ti -1c
.RI "template<typename Visitor , typename Ctx > FMT_CONSTEXPR auto \fBvisit_format_arg\fP (Visitor &&vis, const \fBbasic_format_arg\fP< Ctx > &arg) \-> decltype(vis(0))"
.br
.ti -1c
.RI "template<typename T , typename Char , size_t NUM_ARGS, size_t NUM_NAMED_ARGS> struct \fBdetail::arg_data\fP"
.br
.ti -1c
.RI "template<typename T , typename Char , size_t NUM_ARGS, size_t NUM_NAMED_ARGS> struct \fBdetail::arg_data\fP"
.br
.ti -1c
.RI "template<typename T , typename Char , size_t NUM_ARGS, size_t NUM_NAMED_ARGS> struct \fBdetail::arg_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
