.TH "basic_data< T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_data< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdata\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr uint64_t \fBpow10_significands\fP [87]"
.br
.ti -1c
.RI "static constexpr int16_t \fBpow10_exponents\fP [87]"
.br
.ti -1c
.RI "static constexpr uint64_t \fBpower_of_10_64\fP [20]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename T > constexpr int16_t \fBbasic_data\fP< T >::pow10_exponents\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
= {
      \-1220, \-1193, \-1166, \-1140, \-1113, \-1087, \-1060, \-1034, \-1007, \-980, \-954,
      \-927,  \-901,  \-874,  \-847,  \-821,  \-794,  \-768,  \-741,  \-715,  \-688, \-661,
      \-635,  \-608,  \-582,  \-555,  \-529,  \-502,  \-475,  \-449,  \-422,  \-396, \-369,
      \-343,  \-316,  \-289,  \-263,  \-236,  \-210,  \-183,  \-157,  \-130,  \-103, \-77,
      \-50,   \-24,   3,     30,    56,    83,    109,   136,   162,   189,  216,
      242,   269,   295,   322,   348,   375,   402,   428,   455,   481,  508,
      534,   561,   588,   614,   641,   667,   694,   720,   747,   774,  800,
      827,   853,   880,   907,   933,   960,   986,   1013,  1039,  1066}
.fi

.SS "template<typename T > constexpr uint64_t \fBbasic_data\fP< T >::power_of_10_64\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
= {
      1, FMT_POWERS_OF_10(1ULL), FMT_POWERS_OF_10(1000000000ULL),
      10000000000000000000ULL}
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
