.TH "basic_format_specs< Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_format_specs< Char >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdynamic_format_specs< char_type >\fP, and \fBdynamic_format_specs< Char >\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBprecision\fP"
.br
.ti -1c
.RI "presentation_type \fBtype\fP"
.br
.ti -1c
.RI "align_t \fBalign\fP: 4"
.br
.ti -1c
.RI "sign_t \fBsign\fP: 3"
.br
.ti -1c
.RI "bool \fBalt\fP: 1"
.br
.ti -1c
.RI "bool \fBlocalized\fP: 1"
.br
.ti -1c
.RI "detail::fill_t< Char > \fBfill\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
