.TH "basic_format_string< Char, Args >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basic_format_string< Char, Args >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename S , FMT_ENABLE_IF( std::is_convertible< const S &, \fBbasic_string_view\fP< Char > >\fB::value\fP) > FMT_CONSTEVAL FMT_INLINE \fBbasic_format_string\fP (const S &s)"
.br
.ti -1c
.RI "\fBbasic_format_string\fP (\fBbasic_runtime\fP< Char > r)"
.br
.ti -1c
.RI "FMT_INLINE \fBoperator basic_string_view< Char >\fP () const"
.br
.ti -1c
.RI "template<typename S , FMT_ENABLE_IF( std::is_convertible< const S &, \fBbasic_string_view\fP< Char > >\fB::value\fP) > FMT_CONSTEVAL FMT_INLINE \fBbasic_format_string\fP (const S &s)"
.br
.ti -1c
.RI "\fBbasic_format_string\fP (\fBbasic_runtime\fP< Char > r)"
.br
.ti -1c
.RI "FMT_INLINE \fBoperator basic_string_view< Char >\fP () const"
.br
.ti -1c
.RI "template<typename S , FMT_ENABLE_IF( std::is_convertible< const S &, \fBbasic_string_view\fP< Char > >\fB::value\fP) > FMT_CONSTEVAL FMT_INLINE \fBbasic_format_string\fP (const S &s)"
.br
.ti -1c
.RI "\fBbasic_format_string\fP (\fBbasic_runtime\fP< Char > r)"
.br
.ti -1c
.RI "FMT_INLINE \fBoperator basic_string_view< Char >\fP () const"
.br
.ti -1c
.RI "template<typename S , FMT_ENABLE_IF( std::is_convertible< const S &, \fBbasic_string_view\fP< Char > >\fB::value\fP) > FMT_CONSTEVAL FMT_INLINE \fBbasic_format_string\fP (const S &s)"
.br
.ti -1c
.RI "\fBbasic_format_string\fP (\fBbasic_runtime\fP< Char > r)"
.br
.ti -1c
.RI "FMT_INLINE \fBoperator basic_string_view< Char >\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Char, typename\&.\&.\&. Args>
.br
class basic_format_string< Char, Args >"\fBA\fP compile-time format string\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
