.TH "BDF_FaceRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BDF_FaceRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_FaceRec\fP \fBroot\fP"
.br
.ti -1c
.RI "char * \fBcharset_encoding\fP"
.br
.ti -1c
.RI "char * \fBcharset_registry\fP"
.br
.ti -1c
.RI "\fBbdf_font_t\fP * \fBbdffont\fP"
.br
.ti -1c
.RI "BDF_encoding_el * \fBen_table\fP"
.br
.ti -1c
.RI "FT_UInt \fBdefault_glyph\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
