.TH "bench_info" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bench_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pixman_op_t \fBop\fP"
.br
.ti -1c
.RI "\fBpixman_transform_t\fP \fBtransform\fP"
.br
.ti -1c
.RI "\fBpixman_image_t\fP * \fBsrc_image\fP"
.br
.ti -1c
.RI "\fBpixman_image_t\fP * \fBmask_image\fP"
.br
.ti -1c
.RI "\fBpixman_image_t\fP * \fBdest_image\fP"
.br
.ti -1c
.RI "int32_t \fBsrc_x\fP"
.br
.ti -1c
.RI "int32_t \fBsrc_y\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
