.TH "bigint" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bigint
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbigint\fP (uint64_t n)"
.br
.ti -1c
.RI "\fBbigint\fP (const \fBbigint\fP &)=delete"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBbigint\fP &)=delete"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBassign\fP (const \fBbigint\fP &other)"
.br
.ti -1c
.RI "template<typename Int > FMT_CONSTEXPR20 void \fBoperator=\fP (Int n)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBnum_bigits\fP () const"
.br
.ti -1c
.RI "FMT_NOINLINE FMT_CONSTEXPR20 \fBbigint\fP & \fBoperator<<=\fP (int shift)"
.br
.ti -1c
.RI "template<typename Int > FMT_CONSTEXPR20 \fBbigint\fP & \fBoperator*=\fP (Int \fBvalue\fP)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBassign_pow10\fP (int exp)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBsquare\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBalign\fP (const \fBbigint\fP &other)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBdivmod_assign\fP (const \fBbigint\fP &divisor)"
.br
.ti -1c
.RI "\fBbigint\fP (uint64_t n)"
.br
.ti -1c
.RI "\fBbigint\fP (const \fBbigint\fP &)=delete"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBbigint\fP &)=delete"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBassign\fP (const \fBbigint\fP &other)"
.br
.ti -1c
.RI "template<typename Int > FMT_CONSTEXPR20 void \fBoperator=\fP (Int n)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBnum_bigits\fP () const"
.br
.ti -1c
.RI "FMT_NOINLINE FMT_CONSTEXPR20 \fBbigint\fP & \fBoperator<<=\fP (int shift)"
.br
.ti -1c
.RI "template<typename Int > FMT_CONSTEXPR20 \fBbigint\fP & \fBoperator*=\fP (Int \fBvalue\fP)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBassign_pow10\fP (int exp)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBsquare\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBalign\fP (const \fBbigint\fP &other)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBdivmod_assign\fP (const \fBbigint\fP &divisor)"
.br
.ti -1c
.RI "\fBbigint\fP (uint64_t n)"
.br
.ti -1c
.RI "\fBbigint\fP (const \fBbigint\fP &)=delete"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBbigint\fP &)=delete"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBassign\fP (const \fBbigint\fP &other)"
.br
.ti -1c
.RI "template<typename Int > FMT_CONSTEXPR20 void \fBoperator=\fP (Int n)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBnum_bigits\fP () const"
.br
.ti -1c
.RI "FMT_NOINLINE FMT_CONSTEXPR20 \fBbigint\fP & \fBoperator<<=\fP (int shift)"
.br
.ti -1c
.RI "template<typename Int > FMT_CONSTEXPR20 \fBbigint\fP & \fBoperator*=\fP (Int \fBvalue\fP)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBassign_pow10\fP (int exp)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBsquare\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBalign\fP (const \fBbigint\fP &other)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBdivmod_assign\fP (const \fBbigint\fP &divisor)"
.br
.ti -1c
.RI "\fBbigint\fP (uint64_t n)"
.br
.ti -1c
.RI "\fBbigint\fP (const \fBbigint\fP &)=delete"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBbigint\fP &)=delete"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBassign\fP (const \fBbigint\fP &other)"
.br
.ti -1c
.RI "template<typename Int > FMT_CONSTEXPR20 void \fBoperator=\fP (Int n)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBnum_bigits\fP () const"
.br
.ti -1c
.RI "FMT_NOINLINE FMT_CONSTEXPR20 \fBbigint\fP & \fBoperator<<=\fP (int shift)"
.br
.ti -1c
.RI "template<typename Int > FMT_CONSTEXPR20 \fBbigint\fP & \fBoperator*=\fP (Int \fBvalue\fP)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBassign_pow10\fP (int exp)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBsquare\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 void \fBalign\fP (const \fBbigint\fP &other)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBdivmod_assign\fP (const \fBbigint\fP &divisor)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "struct \fBformatter< bigint >\fP"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBcompare\fP (const \fBbigint\fP &lhs, const \fBbigint\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBadd_compare\fP (const \fBbigint\fP &lhs1, const \fBbigint\fP &lhs2, const \fBbigint\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBcompare\fP (const \fBbigint\fP &lhs, const \fBbigint\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBadd_compare\fP (const \fBbigint\fP &lhs1, const \fBbigint\fP &lhs2, const \fBbigint\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBcompare\fP (const \fBbigint\fP &lhs, const \fBbigint\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBadd_compare\fP (const \fBbigint\fP &lhs1, const \fBbigint\fP &lhs2, const \fBbigint\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBcompare\fP (const \fBbigint\fP &lhs, const \fBbigint\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR20 int \fBadd_compare\fP (const \fBbigint\fP &lhs1, const \fBbigint\fP &lhs2, const \fBbigint\fP &rhs)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
