.TH "biimage_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
biimage_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbiimage_t\fP (unsigned int width, unsigned int height)"
.br
.ti -1c
.RI "void \fBset\fP (const \fBimage_t\fP &image)"
.br
.ti -1c
.RI "uint8_t & \fBoperator()\fP (unsigned int x, unsigned int y)"
.br
.ti -1c
.RI "uint8_t \fBoperator()\fP (unsigned int x, unsigned int y) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "const unsigned int \fBheight\fP"
.br
.ti -1c
.RI "unsigned int \fBbg\fP"
.br
.ti -1c
.RI "unsigned int \fBfg\fP"
.br
.ti -1c
.RI "bool \fBunicolor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
