.TH "bilinear_info_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bilinear_info_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBline_t\fP \fBlines\fP [2]"
.br
.ti -1c
.RI "pixman_fixed_t \fBy\fP"
.br
.ti -1c
.RI "pixman_fixed_t \fBx\fP"
.br
.ti -1c
.RI "uint64_t \fBdata\fP [1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
