.TH "bitread_working_state" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bitread_working_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const JOCTET * \fBnext_input_byte\fP"
.br
.ti -1c
.RI "size_t \fBbytes_in_buffer\fP"
.br
.ti -1c
.RI "bit_buf_type \fBget_buffer\fP"
.br
.ti -1c
.RI "int \fBbits_left\fP"
.br
.ti -1c
.RI "\fBj_decompress_ptr\fP \fBcinfo\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
