.TH "bits_image" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bits_image
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBimage_common_t\fP \fBcommon\fP"
.br
.ti -1c
.RI "pixman_format_code_t \fBformat\fP"
.br
.ti -1c
.RI "const \fBpixman_indexed_t\fP * \fBindexed\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "uint32_t * \fBbits\fP"
.br
.ti -1c
.RI "uint32_t * \fBfree_me\fP"
.br
.ti -1c
.RI "int \fBrowstride\fP"
.br
.ti -1c
.RI "pixman_dither_t \fBdither\fP"
.br
.ti -1c
.RI "uint32_t \fBdither_offset_y\fP"
.br
.ti -1c
.RI "uint32_t \fBdither_offset_x\fP"
.br
.ti -1c
.RI "fetch_scanline_t \fBfetch_scanline_32\fP"
.br
.ti -1c
.RI "fetch_pixel_32_t \fBfetch_pixel_32\fP"
.br
.ti -1c
.RI "store_scanline_t \fBstore_scanline_32\fP"
.br
.ti -1c
.RI "fetch_scanline_t \fBfetch_scanline_float\fP"
.br
.ti -1c
.RI "fetch_pixel_float_t \fBfetch_pixel_float\fP"
.br
.ti -1c
.RI "store_scanline_t \fBstore_scanline_float\fP"
.br
.ti -1c
.RI "pixman_read_memory_func_t \fBread_func\fP"
.br
.ti -1c
.RI "pixman_write_memory_func_t \fBwrite_func\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
