.TH "black_TWorker_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
black_TWorker_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Int \fBprecision_bits\fP"
.br
.ti -1c
.RI "Int \fBprecision\fP"
.br
.ti -1c
.RI "Int \fBprecision_half\fP"
.br
.ti -1c
.RI "Int \fBprecision_scale\fP"
.br
.ti -1c
.RI "Int \fBprecision_step\fP"
.br
.ti -1c
.RI "Int \fBprecision_jitter\fP"
.br
.ti -1c
.RI "PLong \fBbuff\fP"
.br
.ti -1c
.RI "PLong \fBsizeBuff\fP"
.br
.ti -1c
.RI "PLong \fBmaxBuff\fP"
.br
.ti -1c
.RI "PLong \fBtop\fP"
.br
.ti -1c
.RI "FT_Error \fBerror\fP"
.br
.ti -1c
.RI "Int \fBnumTurns\fP"
.br
.ti -1c
.RI "Byte \fBdropOutControl\fP"
.br
.ti -1c
.RI "UShort \fBbWidth\fP"
.br
.ti -1c
.RI "PByte \fBbOrigin\fP"
.br
.ti -1c
.RI "PByte \fBbLine\fP"
.br
.ti -1c
.RI "Long \fBlastX\fP"
.br
.ti -1c
.RI "Long \fBlastY\fP"
.br
.ti -1c
.RI "Long \fBminY\fP"
.br
.ti -1c
.RI "Long \fBmaxY\fP"
.br
.ti -1c
.RI "UShort \fBnum_Profs\fP"
.br
.ti -1c
.RI "\fBBool\fP \fBfresh\fP"
.br
.ti -1c
.RI "\fBBool\fP \fBjoint\fP"
.br
.ti -1c
.RI "\fBPProfile\fP \fBcProfile\fP"
.br
.ti -1c
.RI "\fBPProfile\fP \fBfProfile\fP"
.br
.ti -1c
.RI "\fBPProfile\fP \fBgProfile\fP"
.br
.ti -1c
.RI "TStates \fBstate\fP"
.br
.ti -1c
.RI "\fBFT_Bitmap\fP \fBtarget\fP"
.br
.ti -1c
.RI "\fBFT_Outline\fP \fBoutline\fP"
.br
.ti -1c
.RI "Function_Sweep_Init * \fBProc_Sweep_Init\fP"
.br
.ti -1c
.RI "Function_Sweep_Span * \fBProc_Sweep_Span\fP"
.br
.ti -1c
.RI "Function_Sweep_Span * \fBProc_Sweep_Drop\fP"
.br
.ti -1c
.RI "Function_Sweep_Step * \fBProc_Sweep_Step\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
