.TH "blake2sp_state__" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
blake2sp_state__
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBblake2s_state\fP \fBS\fP [8][1]"
.br
.ti -1c
.RI "\fBblake2s_state\fP \fBR\fP [1]"
.br
.ti -1c
.RI "uint8_t \fBbuf\fP [8 *BLAKE2S_BLOCKBYTES]"
.br
.ti -1c
.RI "size_t \fBbuflen\fP"
.br
.ti -1c
.RI "size_t \fBoutlen\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
