.TH "BlockCnt" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockCnt
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBBlockCnt\fP * \fBprevious\fP"
.br
.ti -1c
.RI "int \fBfirstlabel\fP"
.br
.ti -1c
.RI "int \fBfirstgoto\fP"
.br
.ti -1c
.RI "lu_byte \fBnactvar\fP"
.br
.ti -1c
.RI "lu_byte \fBupval\fP"
.br
.ti -1c
.RI "lu_byte \fBisloop\fP"
.br
.ti -1c
.RI "lu_byte \fBinsidetbc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
