.TH "BM_Fixture< T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BM_Fixture< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbenchmark::Fixture\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBbenchmark::Fixture\fP
.in +1c
.ti -1c
.RI "virtual void \fBRun\fP (\fBState\fP &st)"
.br
.ti -1c
.RI "virtual void \fBSetUp\fP (const \fBState\fP &)"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP (const \fBState\fP &)"
.br
.ti -1c
.RI "virtual void \fBSetUp\fP (\fBState\fP &st)"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP (\fBState\fP &st)"
.br
.in -1c

Public Member Functions inherited from \fBbenchmark::internal::Benchmark\fP
.in +1c
.ti -1c
.RI "\fBBenchmark\fP * \fBArg\fP (int64_t x)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBUnit\fP (TimeUnit unit)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBRange\fP (int64_t start, int64_t limit)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBDenseRange\fP (int64_t start, int64_t limit, int step=1)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBArgs\fP (const std::vector< int64_t > &args)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBArgPair\fP (int64_t x, int64_t y)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBRanges\fP (const std::vector< std::pair< int64_t, int64_t > > &ranges)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBArgName\fP (const std::string &name)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBArgNames\fP (const std::vector< std::string > &names)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBRangePair\fP (int64_t lo1, int64_t hi1, int64_t lo2, int64_t hi2)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBApply\fP (void(*func)(\fBBenchmark\fP *benchmark))"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBRangeMultiplier\fP (int multiplier)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBMinTime\fP (double t)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBIterations\fP (size_t n)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBRepetitions\fP (int n)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBReportAggregatesOnly\fP (bool \fBvalue\fP=true)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBUseRealTime\fP ()"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBUseManualTime\fP ()"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBComplexity\fP (BigO complexity=benchmark::oAuto)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBComplexity\fP (BigOFunc *complexity)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBComputeStatistics\fP (std::string name, StatisticsFunc *statistics)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBThreads\fP (int t)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBThreadRange\fP (int min_threads, int max_threads)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBDenseThreadRange\fP (int min_threads, int max_threads, int stride=1)"
.br
.ti -1c
.RI "\fBBenchmark\fP * \fBThreadPerCpu\fP ()"
.br
.ti -1c
.RI "virtual void \fBRun\fP (\fBState\fP &\fBstate\fP)=0"
.br
.in -1c

Protected Member Functions inherited from \fBbenchmark::Fixture\fP
.in +1c
.ti -1c
.RI "virtual void \fBBenchmarkCase\fP (\fBState\fP &)=0"
.br
.in -1c

Protected Member Functions inherited from \fBbenchmark::internal::Benchmark\fP
.in +1c
.ti -1c
.RI "\fBBenchmark\fP (const char *name)"
.br
.ti -1c
.RI "\fBBenchmark\fP (\fBBenchmark\fP const &)"
.br
.ti -1c
.RI "void \fBSetName\fP (const char *name)"
.br
.ti -1c
.RI "int \fBArgsCnt\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
