.TH "bmp_dest_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmp_dest_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBdjpeg_dest_struct\fP \fBpub\fP"
.br
.ti -1c
.RI "boolean \fBis_os2\fP"
.br
.ti -1c
.RI "\fBjvirt_sarray_ptr\fP \fBwhole_image\fP"
.br
.ti -1c
.RI "JDIMENSION \fBdata_width\fP"
.br
.ti -1c
.RI "JDIMENSION \fBrow_width\fP"
.br
.ti -1c
.RI "int \fBpad_bytes\fP"
.br
.ti -1c
.RI "JDIMENSION \fBcur_output_row\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
