.TH "Bool" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bool
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBool\fP (int val)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (int n) const"
.br
.ti -1c
.RI "\fBBool\fP \fBoperator+\fP (const \fBBool\fP &rhs) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBBool\fP &rhs) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
