.TH "bounds_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bounds_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP (const \fBpoint_t\fP &pt)"
.br
.ti -1c
.RI "void \fBmerge\fP (const \fBbounds_t\fP &b)"
.br
.ti -1c
.RI "void \fBoffset\fP (const \fBpoint_t\fP &delta)"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpoint_t\fP \fBmin\fP"
.br
.ti -1c
.RI "\fBpoint_t\fP \fBmax\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
