.TH "box" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
box
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBc0min\fP"
.br
.ti -1c
.RI "int \fBc0max\fP"
.br
.ti -1c
.RI "int \fBc1min\fP"
.br
.ti -1c
.RI "int \fBc1max\fP"
.br
.ti -1c
.RI "int \fBc2min\fP"
.br
.ti -1c
.RI "int \fBc2max\fP"
.br
.ti -1c
.RI "INT32 \fBvolume\fP"
.br
.ti -1c
.RI "long \fBcolorcount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
