.TH "bracket" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bracket
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBbracket\fP * \fBprevious\fP"
.br
.ti -1c
.RI "struct \fBdelimiter\fP * \fBprevious_delimiter\fP"
.br
.ti -1c
.RI "\fBcmark_node\fP * \fBinl_text\fP"
.br
.ti -1c
.RI "bufsize_t \fBposition\fP"
.br
.ti -1c
.RI "bool \fBimage\fP"
.br
.ti -1c
.RI "bool \fBactive\fP"
.br
.ti -1c
.RI "bool \fBbracket_after\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
