.TH "bsdtar" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bsdtar
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBfilename\fP"
.br
.ti -1c
.RI "char * \fBpending_chdir\fP"
.br
.ti -1c
.RI "const char * \fBnames_from_file\fP"
.br
.ti -1c
.RI "int \fBbytes_per_block\fP"
.br
.ti -1c
.RI "int \fBbytes_in_last_block\fP"
.br
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.ti -1c
.RI "int \fBextract_flags\fP"
.br
.ti -1c
.RI "int \fBreaddisk_flags\fP"
.br
.ti -1c
.RI "int \fBstrip_components\fP"
.br
.ti -1c
.RI "int \fBgid\fP"
.br
.ti -1c
.RI "const char * \fBgname\fP"
.br
.ti -1c
.RI "int \fBuid\fP"
.br
.ti -1c
.RI "const char * \fBuname\fP"
.br
.ti -1c
.RI "const char * \fBpassphrase\fP"
.br
.ti -1c
.RI "char \fBmode\fP"
.br
.ti -1c
.RI "char \fBsymlink_mode\fP"
.br
.ti -1c
.RI "const char * \fBoption_options\fP"
.br
.ti -1c
.RI "char \fBday_first\fP"
.br
.ti -1c
.RI "struct \fBcreation_set\fP * \fBcset\fP"
.br
.ti -1c
.RI "int \fBgetopt_state\fP"
.br
.ti -1c
.RI "char * \fBgetopt_word\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "int \fBargc\fP"
.br
.ti -1c
.RI "char ** \fBargv\fP"
.br
.ti -1c
.RI "const char * \fBargument\fP"
.br
.ti -1c
.RI "size_t \fBgs_width\fP"
.br
.ti -1c
.RI "size_t \fBu_width\fP"
.br
.ti -1c
.RI "uid_t \fBuser_uid\fP"
.br
.ti -1c
.RI "int \fBreturn_value\fP"
.br
.ti -1c
.RI "char \fBwarned_lead_slash\fP"
.br
.ti -1c
.RI "char \fBnext_line_is_dir\fP"
.br
.ti -1c
.RI "struct \fBarchive\fP * \fBdiskreader\fP"
.br
.ti -1c
.RI "struct \fBarchive_entry_linkresolver\fP * \fBresolver\fP"
.br
.ti -1c
.RI "struct \fBarchive_dir\fP * \fBarchive_dir\fP"
.br
.ti -1c
.RI "struct \fBname_cache\fP * \fBgname_cache\fP"
.br
.ti -1c
.RI "char * \fBbuff\fP"
.br
.ti -1c
.RI "size_t \fBbuff_size\fP"
.br
.ti -1c
.RI "int \fBfirst_fs\fP"
.br
.ti -1c
.RI "struct \fBarchive\fP * \fBmatching\fP"
.br
.ti -1c
.RI "struct security * \fBsecurity\fP"
.br
.ti -1c
.RI "struct \fBname_cache\fP * \fBuname_cache\fP"
.br
.ti -1c
.RI "struct siginfo_data * \fBsiginfo\fP"
.br
.ti -1c
.RI "struct substitution * \fBsubstitution\fP"
.br
.ti -1c
.RI "char * \fBppbuff\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
