.TH "bufref" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bufref
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBdtor\fP )(void *)"
.br
.ti -1c
.RI "const unsigned char * \fBptr\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
