.TH "cab" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cab
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBentry_offset\fP"
.br
.ti -1c
.RI "int64_t \fBentry_bytes_remaining\fP"
.br
.ti -1c
.RI "int64_t \fBentry_unconsumed\fP"
.br
.ti -1c
.RI "int64_t \fBentry_compressed_bytes_read\fP"
.br
.ti -1c
.RI "int64_t \fBentry_uncompressed_bytes_read\fP"
.br
.ti -1c
.RI "struct \fBcffolder\fP * \fBentry_cffolder\fP"
.br
.ti -1c
.RI "struct \fBcffile\fP * \fBentry_cffile\fP"
.br
.ti -1c
.RI "struct \fBcfdata\fP * \fBentry_cfdata\fP"
.br
.ti -1c
.RI "int64_t \fBcab_offset\fP"
.br
.ti -1c
.RI "struct \fBcfheader\fP \fBcfheader\fP"
.br
.ti -1c
.RI "struct \fBarchive_wstring\fP \fBws\fP"
.br
.ti -1c
.RI "char \fBfound_header\fP"
.br
.ti -1c
.RI "char \fBend_of_archive\fP"
.br
.ti -1c
.RI "char \fBend_of_entry\fP"
.br
.ti -1c
.RI "char \fBend_of_entry_cleanup\fP"
.br
.ti -1c
.RI "char \fBread_data_invoked\fP"
.br
.ti -1c
.RI "int64_t \fBbytes_skipped\fP"
.br
.ti -1c
.RI "unsigned char * \fBuncompressed_buffer\fP"
.br
.ti -1c
.RI "size_t \fBuncompressed_buffer_size\fP"
.br
.ti -1c
.RI "int \fBinit_default_conversion\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_default\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_utf8\fP"
.br
.ti -1c
.RI "char \fBformat_name\fP [64]"
.br
.ti -1c
.RI "struct \fBlzx_stream\fP \fBxstrm\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
