.TH "cache_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cache_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBpixman_implementation_t\fP * \fBimp\fP"
.br
.ti -1c
.RI "   \fBpixman_fast_path_t\fP \fBfast_path\fP"
.br
.ti -1c
.RI "} \fBcache\fP [N_CACHED_FAST_PATHS]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
