.TH "CameraView" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraView
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetFramebufferSize\fP (\fBvec2\fP the_framebuffer_size) noexcept"
.br
.ti -1c
.RI "void \fBSetFramebufferSize\fP (int new_framebuffer_width, int new_framebuffer_height) noexcept"
.br
.ti -1c
.RI "\fBvec2\fP \fBGetViewSize\fP () const"
.br
.ti -1c
.RI "void \fBSetZoom\fP (float new_zoom) noexcept"
.br
.ti -1c
.RI "\fBvec2\fP \fBCalcViewSizeWithZoom\fP () const noexcept"
.br
.ti -1c
.RI "float \fBGetZoom\fP () const noexcept"
.br
.ti -1c
.RI "\fBmat3\fP \fBBuildCameraToNDC\fP () const noexcept"
.br
.ti -1c
.RI "\fBmat3\fP \fBBuildWindowDeviceToCamera\fP () const noexcept"
.br
.ti -1c
.RI "void \fBSetFramebufferSize\fP (\fBvec2\fP the_framebuffer_size) noexcept"
.br
.ti -1c
.RI "void \fBSetFramebufferSize\fP (int new_framebuffer_width, int new_framebuffer_height) noexcept"
.br
.ti -1c
.RI "\fBvec2\fP \fBGetViewSize\fP () const"
.br
.ti -1c
.RI "void \fBSetZoom\fP (float new_zoom) noexcept"
.br
.ti -1c
.RI "\fBvec2\fP \fBCalcViewSizeWithZoom\fP () const noexcept"
.br
.ti -1c
.RI "float \fBGetZoom\fP () const noexcept"
.br
.ti -1c
.RI "\fBmat3\fP \fBBuildCameraToNDC\fP () const noexcept"
.br
.ti -1c
.RI "\fBmat3\fP \fBBuildWindowDeviceToCamera\fP () const noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
