.TH "Camera" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Camera
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCamera\fP (\fBvec2\fP camera_position, \fBvec2\fP camera_up) noexcept"
.br
.ti -1c
.RI "\fBvec2\fP \fBGetUp\fP () const noexcept"
.br
.ti -1c
.RI "\fBvec2\fP \fBGetRight\fP () const noexcept"
.br
.ti -1c
.RI "float \fBGetOrientation\fP () const noexcept"
.br
.ti -1c
.RI "void \fBSetUp\fP (\fBvec2\fP camera_up={0, 1}) noexcept"
.br
.ti -1c
.RI "void \fBSetOrientation\fP (float angle_radians) noexcept"
.br
.ti -1c
.RI "void \fBMoveUp\fP (float distance) noexcept"
.br
.ti -1c
.RI "void \fBMoveRight\fP (float distance) noexcept"
.br
.ti -1c
.RI "void \fBRotate\fP (float angle_radians) noexcept"
.br
.ti -1c
.RI "\fBmat3\fP \fBBuildCameraToWorld\fP () const noexcept"
.br
.ti -1c
.RI "\fBmat3\fP \fBBuildWorldToCamera\fP () const noexcept"
.br
.ti -1c
.RI "\fBCamera\fP (\fBvec2\fP camera_position, \fBvec2\fP camera_up) noexcept"
.br
.ti -1c
.RI "\fBvec2\fP \fBGetUp\fP () const noexcept"
.br
.ti -1c
.RI "\fBvec2\fP \fBGetRight\fP () const noexcept"
.br
.ti -1c
.RI "float \fBGetOrientation\fP () const noexcept"
.br
.ti -1c
.RI "void \fBSetUp\fP (\fBvec2\fP camera_up={0, 1}) noexcept"
.br
.ti -1c
.RI "void \fBSetOrientation\fP (float angle_radians) noexcept"
.br
.ti -1c
.RI "void \fBMoveUp\fP (float distance) noexcept"
.br
.ti -1c
.RI "void \fBMoveRight\fP (float distance) noexcept"
.br
.ti -1c
.RI "void \fBRotate\fP (float angle_radians) noexcept"
.br
.ti -1c
.RI "\fBmat3\fP \fBBuildCameraToWorld\fP () const noexcept"
.br
.ti -1c
.RI "\fBmat3\fP \fBBuildWorldToCamera\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvec2\fP \fBPosition\fP {}"
.br
.ti -1c
.RI "bool \fBIsFirstPerson\fP {false}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
