.TH "cb_data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cb_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CURL * \fBeasy_handle\fP"
.br
.ti -1c
.RI "int \fBresponse_received\fP"
.br
.ti -1c
.RI "int \fBpaused\fP"
.br
.ti -1c
.RI "size_t \fBremaining_bytes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
