.TH "cdeque" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cdeque
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBbeg_pos\fP"
.br
.ti -1c
.RI "uint16_t \fBend_pos\fP"
.br
.ti -1c
.RI "uint16_t \fBcap_mask\fP"
.br
.ti -1c
.RI "uint16_t \fBsize\fP"
.br
.ti -1c
.RI "size_t * \fBarr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
