.TH "CF2_StemHintRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_StemHintRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Bool \fBused\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBmin\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBmax\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBminDS\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBmaxDS\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
