.TH "CF2_BlueRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_BlueRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CF2_Fixed \fBcsBottomEdge\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBcsTopEdge\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBcsFlatEdge\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBdsFlatEdge\fP"
.br
.ti -1c
.RI "FT_Bool \fBbottomZone\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
