.TH "CF2_StackRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_StackRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_Error * \fBerror\fP"
.br
.ti -1c
.RI "CF2_StackNumber * \fBbuffer\fP"
.br
.ti -1c
.RI "CF2_StackNumber * \fBtop\fP"
.br
.ti -1c
.RI "FT_UInt \fBstackSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
