.TH "CF2_BluesRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_BluesRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CF2_Fixed \fBscale\fP"
.br
.ti -1c
.RI "CF2_UInt \fBcount\fP"
.br
.ti -1c
.RI "FT_Bool \fBsuppressOvershoot\fP"
.br
.ti -1c
.RI "FT_Bool \fBdoEmBoxHints\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBblueScale\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBblueShift\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBblueFuzz\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBboost\fP"
.br
.ti -1c
.RI "\fBCF2_HintRec\fP \fBemBoxTopEdge\fP"
.br
.ti -1c
.RI "\fBCF2_HintRec\fP \fBemBoxBottomEdge\fP"
.br
.ti -1c
.RI "\fBCF2_BlueRec\fP \fBzone\fP [CF2_MAX_BLUES+CF2_MAX_OTHERBLUES]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
