.TH "CF2_HintMaskRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_HintMaskRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Error * \fBerror\fP"
.br
.ti -1c
.RI "FT_Bool \fBisValid\fP"
.br
.ti -1c
.RI "FT_Bool \fBisNew\fP"
.br
.ti -1c
.RI "size_t \fBbitCount\fP"
.br
.ti -1c
.RI "size_t \fBbyteCount\fP"
.br
.ti -1c
.RI "FT_Byte \fBmask\fP [(CF2_MAX_HINTS+7)/8]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
