.TH "CF2_HintMapRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CF2_HintMapRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCF2_Font\fP \fBfont\fP"
.br
.ti -1c
.RI "struct \fBCF2_HintMapRec_\fP * \fBinitialHintMap\fP"
.br
.ti -1c
.RI "CF2_ArrStack \fBhintMoves\fP"
.br
.ti -1c
.RI "FT_Bool \fBisValid\fP"
.br
.ti -1c
.RI "FT_Bool \fBhinted\fP"
.br
.ti -1c
.RI "CF2_Fixed \fBscale\fP"
.br
.ti -1c
.RI "CF2_UInt \fBcount\fP"
.br
.ti -1c
.RI "CF2_UInt \fBlastIndex\fP"
.br
.ti -1c
.RI "\fBCF2_HintRec\fP \fBedge\fP [CF2_MAX_HINT_EDGES]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
