.TH "cfdata" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfdata
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBsum\fP"
.br
.ti -1c
.RI "uint16_t \fBcompressed_size\fP"
.br
.ti -1c
.RI "uint16_t \fBcompressed_bytes_remaining\fP"
.br
.ti -1c
.RI "uint16_t \fBuncompressed_size\fP"
.br
.ti -1c
.RI "uint16_t \fBuncompressed_bytes_remaining\fP"
.br
.ti -1c
.RI "uint16_t \fBuncompressed_avail\fP"
.br
.ti -1c
.RI "uint16_t \fBread_offset\fP"
.br
.ti -1c
.RI "int64_t \fBunconsumed\fP"
.br
.ti -1c
.RI "size_t \fBmemimage_size\fP"
.br
.ti -1c
.RI "unsigned char * \fBmemimage\fP"
.br
.ti -1c
.RI "uint32_t \fBsum_calculated\fP"
.br
.ti -1c
.RI "unsigned char \fBsum_extra\fP [4]"
.br
.ti -1c
.RI "int \fBsum_extra_avail\fP"
.br
.ti -1c
.RI "const void * \fBsum_ptr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
