.TH "cff1_cs_opset_extents_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cff1_cs_opset_extents_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCFF::cff1_cs_opset_t< cff1_cs_opset_extents_t, cff1_extents_param_t, cff1_path_procs_extents_t >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBprocess_seac\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_extents_param_t\fP &param)"
.br
.in -1c

Static Public Member Functions inherited from \fBCFF::cff1_cs_opset_t< cff1_cs_opset_extents_t, cff1_extents_param_t, cff1_path_procs_extents_t >\fP
.in +1c
.ti -1c
.RI "static void \fBprocess_op\fP (op_code_t op, \fBcff1_cs_interp_env_t\fP &env, \fBcff1_extents_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBcheck_width\fP (op_code_t op, \fBcff1_cs_interp_env_t\fP &env, \fBcff1_extents_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBprocess_seac\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_extents_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBflush_args\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_extents_param_t\fP &param)"
.br
.in -1c

Static Public Member Functions inherited from \fBCFF::cs_opset_t< ARG, OPSET, ENV, PARAM, PATH >\fP
.in +1c
.ti -1c
.RI "static void \fBprocess_op\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_hstem\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_vstem\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_hintmask\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_post_flex\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBcheck_width\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_post_move\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_post_path\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBflush_args_and_op\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBflush_args\fP (ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBflush_op\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBflush_hintmask\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static bool \fBis_number_op\fP (op_code_t op)"
.br
.in -1c

Static Public Member Functions inherited from \fBCFF::opset_t< ARG >\fP
.in +1c
.ti -1c
.RI "static void \fBprocess_op\fP (op_code_t op, \fBinterp_env_t\fP< ARG > &env)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Types inherited from \fBCFF::cs_opset_t< ARG, OPSET, ENV, PARAM, PATH >\fP
.in +1c
.ti -1c
.RI "typedef \fBopset_t\fP< ARG > \fBSUPER\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
