.TH "cff1_font_dict_op_serializer_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cff1_font_dict_op_serializer_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCFF::cff_font_dict_op_serializer_t\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBserialize\fP (\fBhb_serialize_context_t\fP *c, const \fBop_str_t\fP &opstr, const \fBcff1_font_dict_values_mod_t\fP &mod) const"
.br
.in -1c

Public Member Functions inherited from \fBCFF::cff_font_dict_op_serializer_t\fP
.in +1c
.ti -1c
.RI "bool \fBserialize\fP (\fBhb_serialize_context_t\fP *c, const \fBop_str_t\fP &opstr, const \fBtable_info_t\fP &privateDictInfo) const"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBCFF::op_serializer_t\fP
.in +1c
.ti -1c
.RI "bool \fBcopy_opstr\fP (\fBhb_serialize_context_t\fP *c, const \fBop_str_t\fP &opstr) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
