.TH "cff1_top_dict_values_mod_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cff1_top_dict_values_mod_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCFF::cff1_top_dict_values_t\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (const \fBcff1_top_dict_values_t\fP *base_=&\fBNull\fP(\fBcff1_top_dict_values_t\fP))"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.ti -1c
.RI "unsigned \fBget_count\fP () const"
.br
.ti -1c
.RI "const \fBcff1_top_dict_val_t\fP & \fBget_value\fP (unsigned int i) const"
.br
.ti -1c
.RI "const \fBcff1_top_dict_val_t\fP & \fBoperator[]\fP (unsigned int i) const"
.br
.ti -1c
.RI "void \fBreassignSIDs\fP (const \fBremap_sid_t\fP &sidmap)"
.br
.in -1c

Public Member Functions inherited from \fBCFF::cff1_top_dict_values_t\fP
.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.ti -1c
.RI "bool \fBis_CID\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBCFF::top_dict_values_t< cff1_top_dict_val_t >\fP
.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBCFF::parsed_values_t< VAL >\fP
.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.ti -1c
.RI "void \fBadd_op\fP (op_code_t op, const \fBbyte_str_ref_t\fP &str_ref=\fBbyte_str_ref_t\fP())"
.br
.ti -1c
.RI "void \fBadd_op\fP (op_code_t op, const \fBbyte_str_ref_t\fP &str_ref, const VAL &v)"
.br
.ti -1c
.RI "bool \fBhas_op\fP (op_code_t op) const"
.br
.ti -1c
.RI "unsigned \fBget_count\fP () const"
.br
.ti -1c
.RI "const VAL & \fBget_value\fP (unsigned int i) const"
.br
.ti -1c
.RI "const VAL & \fBoperator[]\fP (unsigned int i) const"
.br
.in -1c
.SS "Protected Types"

.in +1c
.ti -1c
.RI "typedef \fBcff1_top_dict_values_t\fP \fBSUPER\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const \fBcff1_top_dict_values_t\fP * \fBbase\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBCFF::cff1_top_dict_values_t\fP
.in +1c
.ti -1c
.RI "\fBname_dict_values_t\fP \fBnameSIDs\fP"
.br
.ti -1c
.RI "unsigned int \fBros_supplement_offset\fP"
.br
.ti -1c
.RI "unsigned int \fBros_supplement\fP"
.br
.ti -1c
.RI "unsigned int \fBcidCount\fP"
.br
.ti -1c
.RI "unsigned int \fBEncodingOffset\fP"
.br
.ti -1c
.RI "unsigned int \fBCharsetOffset\fP"
.br
.ti -1c
.RI "unsigned int \fBFDSelectOffset\fP"
.br
.ti -1c
.RI "\fBtable_info_t\fP \fBprivateDictInfo\fP"
.br
.in -1c

Public Attributes inherited from \fBCFF::top_dict_values_t< cff1_top_dict_val_t >\fP
.in +1c
.ti -1c
.RI "unsigned int \fBcharStringsOffset\fP"
.br
.ti -1c
.RI "unsigned int \fBFDArrayOffset\fP"
.br
.in -1c

Public Attributes inherited from \fBCFF::parsed_values_t< VAL >\fP
.in +1c
.ti -1c
.RI "unsigned int \fBopStart\fP"
.br
.ti -1c
.RI "\fBhb_vector_t\fP< VAL > \fBvalues\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
