.TH "cff1_extents_param_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cff1_extents_param_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (const \fBOT::cff1::accelerator_t\fP *_cff)"
.br
.ti -1c
.RI "void \fBstart_path\fP ()"
.br
.ti -1c
.RI "void \fBend_path\fP ()"
.br
.ti -1c
.RI "bool \fBis_path_open\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBpath_open\fP"
.br
.ti -1c
.RI "\fBbounds_t\fP \fBbounds\fP"
.br
.ti -1c
.RI "const \fBOT::cff1::accelerator_t\fP * \fBcff\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
