.TH "cff1_subr_subsetter_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cff1_subr_subsetter_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCFF::subr_subsetter_t< cff1_subr_subsetter_t, CFF1Subrs, const OT::cff1::accelerator_subset_t, cff1_cs_interp_env_t, cff1_cs_opset_subr_subset_t, OpCode_endchar >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcff1_subr_subsetter_t\fP (const \fBOT::cff1::accelerator_subset_t\fP &acc_, const \fBhb_subset_plan_t\fP *plan_)"
.br
.in -1c

Public Member Functions inherited from \fBCFF::subr_subsetter_t< cff1_subr_subsetter_t, CFF1Subrs, const OT::cff1::accelerator_subset_t, cff1_cs_interp_env_t, cff1_cs_opset_subr_subset_t, OpCode_endchar >\fP
.in +1c
.ti -1c
.RI "\fBsubr_subsetter_t\fP (const \fBOT::cff1::accelerator_subset_t\fP &acc_, const \fBhb_subset_plan_t\fP *plan_)"
.br
.ti -1c
.RI "bool \fBsubset\fP (void)"
.br
.ti -1c
.RI "bool \fBencode_charstrings\fP (\fBstr_buff_vec_t\fP &buffArray) const"
.br
.ti -1c
.RI "bool \fBencode_subrs\fP (const \fBparsed_cs_str_vec_t\fP &subrs, const \fBsubr_remap_t\fP &remap, unsigned int fd, \fBstr_buff_vec_t\fP &buffArray) const"
.br
.ti -1c
.RI "bool \fBencode_globalsubrs\fP (\fBstr_buff_vec_t\fP &buffArray)"
.br
.ti -1c
.RI "bool \fBencode_localsubrs\fP (unsigned int fd, \fBstr_buff_vec_t\fP &buffArray) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBcomplete_parsed_str\fP (\fBcff1_cs_interp_env_t\fP &env, \fBsubr_subset_param_t\fP &param, \fBparsed_cs_str_t\fP &charstring)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBCFF::subr_subsetter_t< cff1_subr_subsetter_t, CFF1Subrs, const OT::cff1::accelerator_subset_t, cff1_cs_interp_env_t, cff1_cs_opset_subr_subset_t, OpCode_endchar >\fP
.in +1c
.ti -1c
.RI "bool \fBdrop_hints_in_subr\fP (\fBparsed_cs_str_t\fP &str, unsigned int pos, \fBparsed_cs_str_vec_t\fP &subrs, unsigned int subr_num, const \fBsubr_subset_param_t\fP &param, drop_hints_param_t &drop)"
.br
.ti -1c
.RI "bool \fBdrop_hints_in_str\fP (\fBparsed_cs_str_t\fP &str, const \fBsubr_subset_param_t\fP &param, drop_hints_param_t &drop)"
.br
.ti -1c
.RI "void \fBcollect_subr_refs_in_subr\fP (\fBparsed_cs_str_t\fP &str, unsigned int pos, unsigned int subr_num, \fBparsed_cs_str_vec_t\fP &subrs, \fBhb_set_t\fP *closure, const \fBsubr_subset_param_t\fP &param)"
.br
.ti -1c
.RI "void \fBcollect_subr_refs_in_str\fP (\fBparsed_cs_str_t\fP &str, const \fBsubr_subset_param_t\fP &param)"
.br
.ti -1c
.RI "bool \fBencode_str\fP (const \fBparsed_cs_str_t\fP &str, const unsigned int fd, \fBstr_buff_t\fP &buff) const"
.br
.in -1c

Protected Attributes inherited from \fBCFF::subr_subsetter_t< cff1_subr_subsetter_t, CFF1Subrs, const OT::cff1::accelerator_subset_t, cff1_cs_interp_env_t, cff1_cs_opset_subr_subset_t, OpCode_endchar >\fP
.in +1c
.ti -1c
.RI "const const \fBOT::cff1::accelerator_subset_t\fP & \fBacc\fP"
.br
.ti -1c
.RI "const \fBhb_subset_plan_t\fP * \fBplan\fP"
.br
.ti -1c
.RI "\fBsubr_closures_t\fP \fBclosures\fP"
.br
.ti -1c
.RI "\fBparsed_cs_str_vec_t\fP \fBparsed_charstrings\fP"
.br
.ti -1c
.RI "\fBparsed_cs_str_vec_t\fP \fBparsed_global_subrs\fP"
.br
.ti -1c
.RI "\fBhb_vector_t\fP< \fBparsed_cs_str_vec_t\fP > \fBparsed_local_subrs\fP"
.br
.ti -1c
.RI "\fBsubr_remaps_t\fP \fBremaps\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
