.TH "cff1_path_procs_path_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cff1_path_procs_path_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCFF::path_procs_t< cff1_path_procs_path_t, cff1_cs_interp_env_t, cff1_path_param_t >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmoveto\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param, const \fBpoint_t\fP &pt)"
.br
.ti -1c
.RI "static void \fBline\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param, const \fBpoint_t\fP &pt1)"
.br
.ti -1c
.RI "static void \fBcurve\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param, const \fBpoint_t\fP &pt1, const \fBpoint_t\fP &pt2, const \fBpoint_t\fP &pt3)"
.br
.in -1c

Static Public Member Functions inherited from \fBCFF::path_procs_t< cff1_path_procs_path_t, cff1_cs_interp_env_t, cff1_path_param_t >\fP
.in +1c
.ti -1c
.RI "static void \fBrmoveto\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBhmoveto\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBvmoveto\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBrlineto\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBhlineto\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBvlineto\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBrrcurveto\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBrcurveline\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBrlinecurve\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBvvcurveto\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBhhcurveto\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBvhcurveto\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBhvcurveto\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBmoveto\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param, const \fBpoint_t\fP &pt)"
.br
.ti -1c
.RI "static void \fBline\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param, const \fBpoint_t\fP &pt1)"
.br
.ti -1c
.RI "static void \fBcurve\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param, const \fBpoint_t\fP &pt1, const \fBpoint_t\fP &pt2, const \fBpoint_t\fP &pt3)"
.br
.ti -1c
.RI "static void \fBhflex\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBflex\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBhflex1\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBflex1\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param)"
.br
.in -1c
.SS "Additional Inherited Members"


Static Protected Member Functions inherited from \fBCFF::path_procs_t< cff1_path_procs_path_t, cff1_cs_interp_env_t, cff1_path_param_t >\fP
.in +1c
.ti -1c
.RI "static void \fBcurve2\fP (\fBcff1_cs_interp_env_t\fP &env, \fBcff1_path_param_t\fP &param, const \fBpoint_t\fP &pt1, const \fBpoint_t\fP &pt2, const \fBpoint_t\fP &pt3, const \fBpoint_t\fP &pt4, const \fBpoint_t\fP &pt5, const \fBpoint_t\fP &pt6)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
