.TH "cff2_sub_table_info_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cff2_sub_table_info_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCFF::cff_sub_table_info_t\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "objidx_t \fBvar_store_link\fP"
.br
.in -1c

Public Attributes inherited from \fBCFF::cff_sub_table_info_t\fP
.in +1c
.ti -1c
.RI "\fBtable_info_t\fP \fBfd_select\fP"
.br
.ti -1c
.RI "objidx_t \fBfd_array_link\fP"
.br
.ti -1c
.RI "objidx_t \fBchar_strings_link\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
