.TH "cff2_path_param_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cff2_path_param_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcff2_path_param_t\fP (\fBhb_font_t\fP *font_, \fBhb_draw_session_t\fP &draw_session_)"
.br
.ti -1c
.RI "void \fBmove_to\fP (const \fBpoint_t\fP &p)"
.br
.ti -1c
.RI "void \fBline_to\fP (const \fBpoint_t\fP &p)"
.br
.ti -1c
.RI "void \fBcubic_to\fP (const \fBpoint_t\fP &p1, const \fBpoint_t\fP &p2, const \fBpoint_t\fP &p3)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBhb_draw_session_t\fP * \fBdraw_session\fP"
.br
.ti -1c
.RI "\fBhb_font_t\fP * \fBfont\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
