.TH "cff2_cs_opset_subr_subset_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cff2_cs_opset_subr_subset_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCFF::cff2_cs_opset_t< cff2_cs_opset_subr_subset_t, subr_subset_param_t >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBprocess_op\fP (op_code_t op, \fBcff2_cs_interp_env_t\fP &env, \fBsubr_subset_param_t\fP &param)"
.br
.in -1c

Static Public Member Functions inherited from \fBCFF::cff2_cs_opset_t< cff2_cs_opset_subr_subset_t, subr_subset_param_t >\fP
.in +1c
.ti -1c
.RI "static void \fBprocess_op\fP (op_code_t op, \fBcff2_cs_interp_env_t\fP &env, \fBsubr_subset_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBprocess_blend\fP (\fBcff2_cs_interp_env_t\fP &env, \fBsubr_subset_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBprocess_vsindex\fP (\fBcff2_cs_interp_env_t\fP &env, \fBsubr_subset_param_t\fP &param)"
.br
.in -1c

Static Public Member Functions inherited from \fBCFF::cs_opset_t< ARG, OPSET, ENV, PARAM, PATH >\fP
.in +1c
.ti -1c
.RI "static void \fBprocess_op\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_hstem\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_vstem\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_hintmask\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_post_flex\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBcheck_width\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_post_move\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_post_path\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBflush_args_and_op\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBflush_args\fP (ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBflush_op\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBflush_hintmask\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static bool \fBis_number_op\fP (op_code_t op)"
.br
.in -1c

Static Public Member Functions inherited from \fBCFF::opset_t< ARG >\fP
.in +1c
.ti -1c
.RI "static void \fBprocess_op\fP (op_code_t op, \fBinterp_env_t\fP< ARG > &env)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBprocess_call_subr\fP (op_code_t op, cs_type_t type, \fBcff2_cs_interp_env_t\fP &env, \fBsubr_subset_param_t\fP &param, \fBcff2_biased_subrs_t\fP &subrs, \fBhb_set_t\fP *closure)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Types inherited from \fBCFF::cs_opset_t< ARG, OPSET, ENV, PARAM, PATH >\fP
.in +1c
.ti -1c
.RI "typedef \fBopset_t\fP< ARG > \fBSUPER\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
