.TH "cff2_cs_opset_path_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cff2_cs_opset_path_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCFF::cff2_cs_opset_t< cff2_cs_opset_path_t, cff2_path_param_t, cff2_path_procs_path_t >\fP\&.
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBCFF::cff2_cs_opset_t< cff2_cs_opset_path_t, cff2_path_param_t, cff2_path_procs_path_t >\fP
.in +1c
.ti -1c
.RI "static void \fBprocess_op\fP (op_code_t op, \fBcff2_cs_interp_env_t\fP &env, \fBcff2_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBprocess_blend\fP (\fBcff2_cs_interp_env_t\fP &env, \fBcff2_path_param_t\fP &param)"
.br
.ti -1c
.RI "static void \fBprocess_vsindex\fP (\fBcff2_cs_interp_env_t\fP &env, \fBcff2_path_param_t\fP &param)"
.br
.in -1c

Static Public Member Functions inherited from \fBCFF::cs_opset_t< ARG, OPSET, ENV, PARAM, PATH >\fP
.in +1c
.ti -1c
.RI "static void \fBprocess_op\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_hstem\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_vstem\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_hintmask\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_post_flex\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBcheck_width\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_post_move\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBprocess_post_path\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBflush_args_and_op\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBflush_args\fP (ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBflush_op\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static void \fBflush_hintmask\fP (op_code_t op, ENV &env, PARAM &param)"
.br
.ti -1c
.RI "static bool \fBis_number_op\fP (op_code_t op)"
.br
.in -1c

Static Public Member Functions inherited from \fBCFF::opset_t< ARG >\fP
.in +1c
.ti -1c
.RI "static void \fBprocess_op\fP (op_code_t op, \fBinterp_env_t\fP< ARG > &env)"
.br
.in -1c

Protected Types inherited from \fBCFF::cs_opset_t< ARG, OPSET, ENV, PARAM, PATH >\fP
.in +1c
.ti -1c
.RI "typedef \fBopset_t\fP< ARG > \fBSUPER\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
