.TH "CFF_InternalRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_InternalRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PSH_Globals \fBtopfont\fP"
.br
.ti -1c
.RI "PSH_Globals \fBsubfonts\fP [CFF_MAX_CID_FONTS]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
