.TH "CFF_Decoder_FuncsRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_Decoder_FuncsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBinit\fP )(\fBCFF_Decoder\fP *decoder, \fBTT_Face\fP face, \fBCFF_Size\fP size, \fBCFF_GlyphSlot\fP slot, FT_Bool hinting, FT_Render_Mode hint_mode, CFF_Decoder_Get_Glyph_Callback get_callback, CFF_Decoder_Free_Glyph_Callback free_callback)"
.br
.ti -1c
.RI "FT_Error(* \fBprepare\fP )(\fBCFF_Decoder\fP *decoder, \fBCFF_Size\fP size, FT_UInt glyph_index)"
.br
.ti -1c
.RI "FT_Error(* \fBparse_charstrings\fP )(\fBPS_Decoder\fP *decoder, FT_Byte *charstring_base, FT_ULong charstring_len)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
