.TH "cff_subset_plan" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cff_subset_plan
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBplan_subset_encoding\fP (const \fBOT::cff1::accelerator_subset_t\fP &acc, \fBhb_subset_plan_t\fP *plan)"
.br
.ti -1c
.RI "void \fBplan_subset_charset\fP (const \fBOT::cff1::accelerator_subset_t\fP &acc, \fBhb_subset_plan_t\fP *plan)"
.br
.ti -1c
.RI "bool \fBcollect_sids_in_dicts\fP (const \fBOT::cff1::accelerator_subset_t\fP &acc)"
.br
.ti -1c
.RI "bool \fBcreate\fP (const \fBOT::cff1::accelerator_subset_t\fP &acc, \fBhb_subset_plan_t\fP *plan)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcff1_top_dict_values_mod_t\fP \fBtopdict_mod\fP"
.br
.ti -1c
.RI "\fBcff1_sub_table_info_t\fP \fBinfo\fP"
.br
.ti -1c
.RI "unsigned int \fBnum_glyphs\fP"
.br
.ti -1c
.RI "unsigned int \fBorig_fdcount\fP = 0"
.br
.ti -1c
.RI "unsigned int \fBsubset_fdcount\fP = 1"
.br
.ti -1c
.RI "unsigned int \fBsubset_fdselect_format\fP = 0"
.br
.ti -1c
.RI "\fBhb_vector_t\fP< \fBcode_pair_t\fP > \fBsubset_fdselect_ranges\fP"
.br
.ti -1c
.RI "\fBhb_inc_bimap_t\fP \fBfdmap\fP"
.br
.ti -1c
.RI "\fBstr_buff_vec_t\fP \fBsubset_charstrings\fP"
.br
.ti -1c
.RI "\fBstr_buff_vec_t\fP \fBsubset_globalsubrs\fP"
.br
.ti -1c
.RI "\fBhb_vector_t\fP< \fBstr_buff_vec_t\fP > \fBsubset_localsubrs\fP"
.br
.ti -1c
.RI "\fBhb_vector_t\fP< \fBcff1_font_dict_values_mod_t\fP > \fBfontdicts_mod\fP"
.br
.ti -1c
.RI "bool \fBdrop_hints\fP = false"
.br
.ti -1c
.RI "bool \fBgid_renum\fP"
.br
.ti -1c
.RI "bool \fBsubset_encoding\fP"
.br
.ti -1c
.RI "uint8_t \fBsubset_enc_format\fP"
.br
.ti -1c
.RI "unsigned int \fBsubset_enc_num_codes\fP"
.br
.ti -1c
.RI "\fBrange_list_t\fP \fBsubset_enc_code_ranges\fP"
.br
.ti -1c
.RI "\fBhb_vector_t\fP< \fBcode_pair_t\fP > \fBsubset_enc_supp_codes\fP"
.br
.ti -1c
.RI "uint8_t \fBsubset_charset_format\fP"
.br
.ti -1c
.RI "\fBrange_list_t\fP \fBsubset_charset_ranges\fP"
.br
.ti -1c
.RI "bool \fBsubset_charset\fP"
.br
.ti -1c
.RI "\fBremap_sid_t\fP \fBsidmap\fP"
.br
.ti -1c
.RI "unsigned int \fBtopDictModSIDs\fP [name_dict_values_t::ValCount]"
.br
.ti -1c
.RI "bool \fBdesubroutinize\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
