.TH "CFF_CharsetRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_CharsetRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBformat\fP"
.br
.ti -1c
.RI "FT_ULong \fBoffset\fP"
.br
.ti -1c
.RI "FT_UShort * \fBsids\fP"
.br
.ti -1c
.RI "FT_UShort * \fBcids\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_cid\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_glyphs\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
