.TH "CFF_Builder_FuncsRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_Builder_FuncsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBinit\fP )(\fBCFF_Builder\fP *builder, \fBTT_Face\fP face, \fBCFF_Size\fP size, \fBCFF_GlyphSlot\fP glyph, FT_Bool hinting)"
.br
.ti -1c
.RI "void(* \fBdone\fP )(\fBCFF_Builder\fP *builder)"
.br
.ti -1c
.RI "CFF_Builder_Check_Points_Func \fBcheck_points\fP"
.br
.ti -1c
.RI "CFF_Builder_Add_Point_Func \fBadd_point\fP"
.br
.ti -1c
.RI "CFF_Builder_Add_Point1_Func \fBadd_point1\fP"
.br
.ti -1c
.RI "CFF_Builder_Add_Contour_Func \fBadd_contour\fP"
.br
.ti -1c
.RI "CFF_Builder_Start_Point_Func \fBstart_point\fP"
.br
.ti -1c
.RI "CFF_Builder_Close_Contour_Func \fBclose_contour\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
