.TH "CFF_BlendRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFF_BlendRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Bool \fBbuiltBV\fP"
.br
.ti -1c
.RI "FT_Bool \fBusedBV\fP"
.br
.ti -1c
.RI "\fBCFF_Font\fP \fBfont\fP"
.br
.ti -1c
.RI "FT_UInt \fBlastVsindex\fP"
.br
.ti -1c
.RI "FT_UInt \fBlenNDV\fP"
.br
.ti -1c
.RI "FT_Fixed * \fBlastNDV\fP"
.br
.ti -1c
.RI "FT_UInt \fBlenBV\fP"
.br
.ti -1c
.RI "FT_Int32 * \fBBV\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
