.TH "cffile" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cffile
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBuncompressed_size\fP"
.br
.ti -1c
.RI "uint32_t \fBoffset\fP"
.br
.ti -1c
.RI "time_t \fBmtime\fP"
.br
.ti -1c
.RI "uint16_t \fBfolder\fP"
.br
.ti -1c
.RI "unsigned char \fBattr\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBpathname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
