.TH "cfheader" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfheader
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBtotal_bytes\fP"
.br
.ti -1c
.RI "uint32_t \fBfiles_offset\fP"
.br
.ti -1c
.RI "uint16_t \fBfolder_count\fP"
.br
.ti -1c
.RI "uint16_t \fBfile_count\fP"
.br
.ti -1c
.RI "uint16_t \fBflags\fP"
.br
.ti -1c
.RI "uint16_t \fBsetid\fP"
.br
.ti -1c
.RI "uint16_t \fBcabinet\fP"
.br
.ti -1c
.RI "unsigned char \fBmajor\fP"
.br
.ti -1c
.RI "unsigned char \fBminor\fP"
.br
.ti -1c
.RI "unsigned char \fBcffolder\fP"
.br
.ti -1c
.RI "unsigned char \fBcfdata\fP"
.br
.ti -1c
.RI "struct \fBcffolder\fP * \fBfolder_array\fP"
.br
.ti -1c
.RI "struct \fBcffile\fP * \fBfile_array\fP"
.br
.ti -1c
.RI "int \fBfile_index\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
