.TH "char_t_impl< S, enable_if_t< is_string< S >::value > >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
char_t_impl< S, enable_if_t< is_string< S >::value > >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBresult\fP = decltype(to_string_view(std::declval< S >()))"
.br
.ti -1c
.RI "using \fBtype\fP = typename result::value_type"
.br
.ti -1c
.RI "using \fBresult\fP = decltype(to_string_view(std::declval< S >()))"
.br
.ti -1c
.RI "using \fBtype\fP = typename result::value_type"
.br
.ti -1c
.RI "using \fBresult\fP = decltype(to_string_view(std::declval< S >()))"
.br
.ti -1c
.RI "using \fBtype\fP = typename result::value_type"
.br
.ti -1c
.RI "using \fBresult\fP = decltype(to_string_view(std::declval< S >()))"
.br
.ti -1c
.RI "using \fBtype\fP = typename result::value_type"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
