.TH "char_converter< Context >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
char_converter< Context >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBchar_converter\fP (\fBbasic_format_arg\fP< \fBContext\fP > &arg)"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(std::is_integral< T >\fB::value\fP) > void \fBoperator()\fP (T \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(!std::is_integral< T >\fB::value\fP) > void \fBoperator()\fP (T)"
.br
.ti -1c
.RI "\fBchar_converter\fP (\fBbasic_format_arg\fP< \fBContext\fP > &arg)"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(std::is_integral< T >\fB::value\fP) > void \fBoperator()\fP (T \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(!std::is_integral< T >\fB::value\fP) > void \fBoperator()\fP (T)"
.br
.ti -1c
.RI "\fBchar_converter\fP (\fBbasic_format_arg\fP< \fBContext\fP > &arg)"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(std::is_integral< T >\fB::value\fP) > void \fBoperator()\fP (T \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(!std::is_integral< T >\fB::value\fP) > void \fBoperator()\fP (T)"
.br
.ti -1c
.RI "\fBchar_converter\fP (\fBbasic_format_arg\fP< \fBContext\fP > &arg)"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(std::is_integral< T >\fB::value\fP) > void \fBoperator()\fP (T \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(!std::is_integral< T >\fB::value\fP) > void \fBoperator()\fP (T)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
