.TH "checkfp_command" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
checkfp_command
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBnumber\fP [1024]"
.br
.ti -1c
.RI "int \fBlimit\fP"
.br
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "int \fBctimes\fP"
.br
.ti -1c
.RI "int \fBcmillions\fP"
.br
.ti -1c
.RI "int \fBcinvalid\fP"
.br
.ti -1c
.RI "int \fBcnoaccept\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
