.TH "checker" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
checker
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive\fP * \fBshort_archive\fP"
.br
.ti -1c
.RI "char * \fBshortbuf\fP"
.br
.ti -1c
.RI "size_t \fBshortbuf_len\fP"
.br
.ti -1c
.RI "struct \fBarchive\fP * \fBfull_archive\fP"
.br
.ti -1c
.RI "char * \fBfullbuf\fP"
.br
.ti -1c
.RI "size_t \fBfullbuf_len\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
