.TH "checkfp_control" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
checkfp_control
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcnumber\fP"
.br
.ti -1c
.RI "checkfp_state \fBcheck_state\fP"
.br
.ti -1c
.RI "int \fBat_start\fP"
.br
.ti -1c
.RI "int \fBcdigits_in_state\fP"
.br
.ti -1c
.RI "int \fBlimit\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "int \fBis_negative\fP"
.br
.ti -1c
.RI "int \fBis_zero\fP"
.br
.ti -1c
.RI "int \fBnumber_was_valid\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
