.TH "CheckStrings" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CheckStrings
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBloadStrings\fP (const std::string &dir)"
.br
.ti -1c
.RI "void \fBcheckStringsOnWidgets\fP (const std::string &dir)"
.br
.ti -1c
.RI "void \fBcheckStringsOnGuiFile\fP (const std::string &fullFn)"
.br
.ti -1c
.RI "void \fBcheckString\fP (\fBTiXmlElement\fP *elem, const char *text)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
