.TH "chrono_format_checker" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chrono_format_checker
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBnull_chrono_spec_handler< chrono_format_checker >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_NORETURN void \fBunsupported\fP ()"
.br
.ti -1c
.RI "template<typename Char > FMT_CONSTEXPR void \fBon_text\fP (const Char *, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_minute\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_second\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_am_pm\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_value\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_unit\fP ()"
.br
.ti -1c
.RI "FMT_NORETURN void \fBunsupported\fP ()"
.br
.ti -1c
.RI "template<typename Char > FMT_CONSTEXPR void \fBon_text\fP (const Char *, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_minute\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_second\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_am_pm\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_value\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_unit\fP ()"
.br
.ti -1c
.RI "FMT_NORETURN void \fBunsupported\fP ()"
.br
.ti -1c
.RI "template<typename Char > FMT_CONSTEXPR void \fBon_text\fP (const Char *, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_minute\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_second\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_am_pm\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_value\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_unit\fP ()"
.br
.ti -1c
.RI "FMT_NORETURN void \fBunsupported\fP ()"
.br
.ti -1c
.RI "template<typename Char > FMT_CONSTEXPR void \fBon_text\fP (const Char *, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_minute\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_second\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_am_pm\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_value\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_unit\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBnull_chrono_spec_handler< chrono_format_checker >\fP
.in +1c
.ti -1c
.RI "FMT_CONSTEXPR void \fBunsupported\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBunsupported\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBunsupported\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBunsupported\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_short_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_short_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_short_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_short_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_offset_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_offset_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_offset_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_offset_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_century\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_century\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_century\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_century\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_week_based_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_week_based_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_week_based_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_week_based_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_week_based_short_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_week_based_short_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_week_based_short_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_week_based_short_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_abbr_weekday\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_abbr_weekday\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_abbr_weekday\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_abbr_weekday\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_full_weekday\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_full_weekday\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_full_weekday\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_full_weekday\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec0_weekday\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec0_weekday\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec0_weekday\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec0_weekday\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec1_weekday\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec1_weekday\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec1_weekday\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec1_weekday\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_abbr_month\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_abbr_month\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_abbr_month\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_abbr_month\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_full_month\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_full_month\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_full_month\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_full_month\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec_month\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec_month\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec_month\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec_month\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec0_week_of_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec0_week_of_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec0_week_of_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec0_week_of_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec1_week_of_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec1_week_of_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec1_week_of_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_dec1_week_of_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_week_of_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_week_of_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_week_of_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_week_of_year\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_day_of_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_day_of_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_day_of_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_day_of_year\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_day_of_month\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_day_of_month\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_day_of_month\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_day_of_month\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_day_of_month_space\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_day_of_month_space\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_day_of_month_space\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_day_of_month_space\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_minute\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_minute\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_minute\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_minute\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_second\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_second\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_second\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_second\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_datetime\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_datetime\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_datetime\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_datetime\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_loc_date\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_loc_date\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_loc_date\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_loc_date\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_loc_time\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_loc_time\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_loc_time\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_loc_time\fP (numeric_system)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_us_date\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_us_date\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_us_date\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_us_date\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_date\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_date\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_date\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_date\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_12_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_24_hour_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_iso_time\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_am_pm\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_am_pm\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_am_pm\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_am_pm\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_value\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_value\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_value\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_value\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_unit\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_unit\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_unit\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_duration_unit\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_utc_offset\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_utc_offset\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_utc_offset\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_utc_offset\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_tz_name\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_tz_name\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_tz_name\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_tz_name\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
