.TH "ChunkParser" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkParser
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBid\fP [4]"
.br
.ti -1c
.RI "ParseStatus(* \fBparse\fP )(\fBWebPDemuxer\fP *const dmux)"
.br
.ti -1c
.RI "int(* \fBvalid\fP )(const \fBWebPDemuxer\fP *const dmux)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
