.TH "chunk_insert" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chunk_insert
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBchunk_insert\fP * \fBnext\fP"
.br
.ti -1c
.RI "void(* \fBinsert\fP )(\fBpng_structp\fP, \fBpng_infop\fP, int, png_charpp)"
.br
.ti -1c
.RI "int \fBnparams\fP"
.br
.ti -1c
.RI "png_charp \fBparameters\fP [1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
