.TH "CID_GlyphSlotRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CID_GlyphSlotRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_GlyphSlotRec\fP \fBroot\fP"
.br
.ti -1c
.RI "FT_Bool \fBhint\fP"
.br
.ti -1c
.RI "FT_Bool \fBscaled\fP"
.br
.ti -1c
.RI "FT_Fixed \fBx_scale\fP"
.br
.ti -1c
.RI "FT_Fixed \fBy_scale\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
