.TH "cjpeg_source_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cjpeg_source_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, start_input,(\fBj_compress_ptr\fP cinfo, \fBcjpeg_source_ptr\fP sinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (JDIMENSION, get_pixel_rows,(\fBj_compress_ptr\fP cinfo, \fBcjpeg_source_ptr\fP sinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, finish_input,(\fBj_compress_ptr\fP cinfo, \fBcjpeg_source_ptr\fP sinfo))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBinput_file\fP"
.br
.ti -1c
.RI "JSAMPARRAY \fBbuffer\fP"
.br
.ti -1c
.RI "JDIMENSION \fBbuffer_height\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
