.TH "CliTestDelegate" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CliTestDelegate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBapp::CliDelegate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBshowHelp\fP (const \fBAppOptions\fP &options) override"
.br
.ti -1c
.RI "void \fBshowVersion\fP () override"
.br
.ti -1c
.RI "void \fBuiMode\fP () override"
.br
.ti -1c
.RI "void \fBshellMode\fP () override"
.br
.ti -1c
.RI "void \fBbatchMode\fP () override"
.br
.ti -1c
.RI "void \fBbeforeOpenFile\fP (const \fBCliOpenFile\fP &cof) override"
.br
.ti -1c
.RI "void \fBafterOpenFile\fP (const \fBCliOpenFile\fP &cof) override"
.br
.ti -1c
.RI "void \fBsaveFile\fP (\fBContext\fP *ctx, const \fBCliOpenFile\fP &cof) override"
.br
.ti -1c
.RI "void \fBexportFiles\fP (\fBContext\fP *ctx, \fBDocExporter\fP &exporter) override"
.br
.ti -1c
.RI "bool \fBhelpWasShown\fP () const"
.br
.ti -1c
.RI "bool \fBversionWasShown\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBapp::CliDelegate\fP
.in +1c
.ti -1c
.RI "virtual void \fBshowHelp\fP (const \fBAppOptions\fP &options)"
.br
.ti -1c
.RI "virtual void \fBshowVersion\fP ()"
.br
.ti -1c
.RI "virtual void \fBuiMode\fP ()"
.br
.ti -1c
.RI "virtual void \fBshellMode\fP ()"
.br
.ti -1c
.RI "virtual void \fBbatchMode\fP ()"
.br
.ti -1c
.RI "virtual void \fBbeforeOpenFile\fP (const \fBCliOpenFile\fP &cof)"
.br
.ti -1c
.RI "virtual void \fBafterOpenFile\fP (const \fBCliOpenFile\fP &cof)"
.br
.ti -1c
.RI "virtual void \fBsaveFile\fP (\fBContext\fP *ctx, const \fBCliOpenFile\fP &cof)"
.br
.ti -1c
.RI "virtual void \fBloadPalette\fP (\fBContext\fP *ctx, const std::string &filename)"
.br
.ti -1c
.RI "virtual void \fBexportFiles\fP (\fBContext\fP *ctx, \fBDocExporter\fP &exporter)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void CliTestDelegate::afterOpenFile (const \fBCliOpenFile\fP & cof)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBapp::CliDelegate\fP\&.
.SS "void CliTestDelegate::batchMode ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBapp::CliDelegate\fP\&.
.SS "void CliTestDelegate::beforeOpenFile (const \fBCliOpenFile\fP & cof)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBapp::CliDelegate\fP\&.
.SS "void CliTestDelegate::exportFiles (\fBContext\fP * ctx, \fBDocExporter\fP & exporter)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBapp::CliDelegate\fP\&.
.SS "void CliTestDelegate::saveFile (\fBContext\fP * ctx, const \fBCliOpenFile\fP & cof)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBapp::CliDelegate\fP\&.
.SS "void CliTestDelegate::shellMode ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBapp::CliDelegate\fP\&.
.SS "void CliTestDelegate::showHelp (const \fBAppOptions\fP & options)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBapp::CliDelegate\fP\&.
.SS "void CliTestDelegate::showVersion ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBapp::CliDelegate\fP\&.
.SS "void CliTestDelegate::uiMode ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBapp::CliDelegate\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
