.TH "cmark_strbuf" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmark_strbuf
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcmark_mem\fP * \fBmem\fP"
.br
.ti -1c
.RI "unsigned char * \fBptr\fP"
.br
.ti -1c
.RI "bufsize_t \fBasize\fP"
.br
.ti -1c
.RI "bufsize_t \fBsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
