.TH "cmark_renderer" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmark_renderer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBoptions\fP"
.br
.ti -1c
.RI "\fBcmark_mem\fP * \fBmem\fP"
.br
.ti -1c
.RI "\fBcmark_strbuf\fP * \fBbuffer\fP"
.br
.ti -1c
.RI "\fBcmark_strbuf\fP * \fBprefix\fP"
.br
.ti -1c
.RI "int \fBcolumn\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBneed_cr\fP"
.br
.ti -1c
.RI "bufsize_t \fBlast_breakable\fP"
.br
.ti -1c
.RI "bool \fBbegin_line\fP"
.br
.ti -1c
.RI "bool \fBbegin_content\fP"
.br
.ti -1c
.RI "bool \fBno_linebreaks\fP"
.br
.ti -1c
.RI "bool \fBin_tight_list_item\fP"
.br
.ti -1c
.RI "void(* \fBoutc\fP )(struct \fBcmark_renderer\fP *, cmark_escaping, int32_t, unsigned char)"
.br
.ti -1c
.RI "void(* \fBcr\fP )(struct \fBcmark_renderer\fP *)"
.br
.ti -1c
.RI "void(* \fBblankline\fP )(struct \fBcmark_renderer\fP *)"
.br
.ti -1c
.RI "void(* \fBout\fP )(struct \fBcmark_renderer\fP *, const char *, bool, cmark_escaping)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
