.TH "cmark_code" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmark_code
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char * \fBinfo\fP"
.br
.ti -1c
.RI "uint8_t \fBfence_length\fP"
.br
.ti -1c
.RI "uint8_t \fBfence_offset\fP"
.br
.ti -1c
.RI "unsigned char \fBfence_char\fP"
.br
.ti -1c
.RI "int8_t \fBfenced\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
