.TH "cmark_list" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmark_list
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmarker_offset\fP"
.br
.ti -1c
.RI "int \fBpadding\fP"
.br
.ti -1c
.RI "int \fBstart\fP"
.br
.ti -1c
.RI "unsigned char \fBlist_type\fP"
.br
.ti -1c
.RI "unsigned char \fBdelimiter\fP"
.br
.ti -1c
.RI "unsigned char \fBbullet_char\fP"
.br
.ti -1c
.RI "bool \fBtight\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
