.TH "cmark_parser" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmark_parser
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBcmark_mem\fP * \fBmem\fP"
.br
.ti -1c
.RI "struct \fBcmark_reference_map\fP * \fBrefmap\fP"
.br
.ti -1c
.RI "struct \fBcmark_node\fP * \fBroot\fP"
.br
.ti -1c
.RI "struct \fBcmark_node\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "int \fBline_number\fP"
.br
.ti -1c
.RI "bufsize_t \fBoffset\fP"
.br
.ti -1c
.RI "bufsize_t \fBcolumn\fP"
.br
.ti -1c
.RI "bufsize_t \fBfirst_nonspace\fP"
.br
.ti -1c
.RI "bufsize_t \fBfirst_nonspace_column\fP"
.br
.ti -1c
.RI "bufsize_t \fBthematic_break_kill_pos\fP"
.br
.ti -1c
.RI "int \fBindent\fP"
.br
.ti -1c
.RI "bool \fBblank\fP"
.br
.ti -1c
.RI "bool \fBpartially_consumed_tab\fP"
.br
.ti -1c
.RI "\fBcmark_strbuf\fP \fBcurline\fP"
.br
.ti -1c
.RI "bufsize_t \fBlast_line_length\fP"
.br
.ti -1c
.RI "\fBcmark_strbuf\fP \fBlinebuf\fP"
.br
.ti -1c
.RI "\fBcmark_strbuf\fP \fBcontent\fP"
.br
.ti -1c
.RI "int \fBoptions\fP"
.br
.ti -1c
.RI "bool \fBlast_buffer_ended_with_cr\fP"
.br
.ti -1c
.RI "unsigned int \fBtotal_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
