.TH "cmark_mem" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmark_mem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmark\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void *(* \fBcalloc\fP )(size_t, size_t)"
.br
.ti -1c
.RI "void *(* \fBrealloc\fP )(void *, size_t)"
.br
.ti -1c
.RI "void(* \fBfree\fP )(void *)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "Custom memory allocator support"
Defines the memory allocation functions to be used by CMark when parsing and allocating a document tree 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
