.TH "cmark_reference_map" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmark_reference_map
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcmark_mem\fP * \fBmem\fP"
.br
.ti -1c
.RI "\fBcmark_reference\fP * \fBrefs\fP"
.br
.ti -1c
.RI "\fBcmark_reference\fP ** \fBsorted\fP"
.br
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.ti -1c
.RI "unsigned int \fBref_size\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_ref_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
