.TH "cmark_node" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmark_node
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcmark_mem\fP * \fBmem\fP"
.br
.ti -1c
.RI "struct \fBcmark_node\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBcmark_node\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBcmark_node\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct \fBcmark_node\fP * \fBfirst_child\fP"
.br
.ti -1c
.RI "struct \fBcmark_node\fP * \fBlast_child\fP"
.br
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.ti -1c
.RI "bufsize_t \fBlen\fP"
.br
.ti -1c
.RI "int \fBstart_line\fP"
.br
.ti -1c
.RI "int \fBstart_column\fP"
.br
.ti -1c
.RI "int \fBend_line\fP"
.br
.ti -1c
.RI "int \fBend_column\fP"
.br
.ti -1c
.RI "int \fBinternal_offset\fP"
.br
.ti -1c
.RI "uint16_t \fBtype\fP"
.br
.ti -1c
.RI "uint16_t \fBflags\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBcmark_list\fP \fBlist\fP"
.br
.ti -1c
.RI "   \fBcmark_code\fP \fBcode\fP"
.br
.ti -1c
.RI "   \fBcmark_heading\fP \fBheading\fP"
.br
.ti -1c
.RI "   \fBcmark_link\fP \fBlink\fP"
.br
.ti -1c
.RI "   \fBcmark_custom\fP \fBcustom\fP"
.br
.ti -1c
.RI "   int \fBhtml_block_type\fP"
.br
.ti -1c
.RI "} \fBas\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
