.TH "Cmd" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cmd
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBundo::UndoCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCmd\fP (int &model, int redo_value, int undo_value)"
.br
.ti -1c
.RI "void \fBredo\fP () override"
.br
.ti -1c
.RI "void \fBundo\fP () override"
.br
.ti -1c
.RI "void \fBdispose\fP () override"
.br
.in -1c
.in +1c
.ti -1c
.RI "virtual void \fBundo\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBredo\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBdispose\fP ()=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Cmd::dispose ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBundo::UndoCommand\fP\&.
.SS "void Cmd::redo ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBundo::UndoCommand\fP\&.
.SS "void Cmd::undo ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBundo::UndoCommand\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
