.TH "ColorMapObject" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorMapObject
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBColorCount\fP"
.br
.ti -1c
.RI "int \fBBitsPerPixel\fP"
.br
.ti -1c
.RI "bool \fBSortFlag\fP"
.br
.ti -1c
.RI "\fBGifColorType\fP * \fBColors\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
