.TH "color_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
color_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBto_ansi\fP ()"
.br
.ti -1c
.RI "\fBcolor_diff_t\fP \fBdiff\fP (const \fBcolor_t\fP &o)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcolor_t\fP \fBfrom_ansi\fP (unsigned int x)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBv\fP"
.br
.ti -1c
.RI "double \fBr\fP"
.br
.ti -1c
.RI "double \fBg\fP"
.br
.ti -1c
.RI "double \fBb\fP"
.br
.ti -1c
.RI "double \fBa\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
