.TH "color_type" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
color_type
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBcolor_union\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (color rgb_color) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (\fBrgb\fP rgb_color) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (terminal_color term_color) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (color rgb_color) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (\fBrgb\fP rgb_color) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (terminal_color term_color) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (color rgb_color) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (\fBrgb\fP rgb_color) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (terminal_color term_color) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (color rgb_color) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (\fBrgb\fP rgb_color) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBcolor_type\fP (terminal_color term_color) noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBis_rgb\fP"
.br
.ti -1c
.RI "union \fBcolor_type::color_union\fP \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
