.TH "CommandLineArguments" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandLineArguments
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBargc_\fP"
.br
.ti -1c
.RI "const char ** \fBargv_\fP"
.br
.ti -1c
.RI "\fBWebPData\fP \fBargv_data_\fP"
.br
.ti -1c
.RI "int \fBown_argv_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
