.TH "comp_state" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
comp_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBinitialized\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBall_filters_applied\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBswitch_multivolume\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBblock_parsing_finished\fP: 1"
.br
.ti -1c
.RI "signed int \fBnotused\fP: 4"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int \fBmethod\fP"
.br
.ti -1c
.RI "int \fBversion\fP"
.br
.ti -1c
.RI "ssize_t \fBwindow_size\fP"
.br
.ti -1c
.RI "uint8_t * \fBwindow_buf\fP"
.br
.ti -1c
.RI "uint8_t * \fBfiltered_buf\fP"
.br
.ti -1c
.RI "const uint8_t * \fBblock_buf\fP"
.br
.ti -1c
.RI "size_t \fBwindow_mask\fP"
.br
.ti -1c
.RI "int64_t \fBwrite_ptr\fP"
.br
.ti -1c
.RI "int64_t \fBlast_write_ptr\fP"
.br
.ti -1c
.RI "int64_t \fBlast_unstore_ptr\fP"
.br
.ti -1c
.RI "int64_t \fBsolid_offset\fP"
.br
.ti -1c
.RI "ssize_t \fBcur_block_size\fP"
.br
.ti -1c
.RI "int \fBlast_len\fP"
.br
.ti -1c
.RI "struct \fBdecode_table\fP \fBbd\fP"
.br
.ti -1c
.RI "struct \fBdecode_table\fP \fBld\fP"
.br
.ti -1c
.RI "struct \fBdecode_table\fP \fBdd\fP"
.br
.ti -1c
.RI "struct \fBdecode_table\fP \fBldd\fP"
.br
.ti -1c
.RI "struct \fBdecode_table\fP \fBrd\fP"
.br
.ti -1c
.RI "struct \fBcdeque\fP \fBfilters\fP"
.br
.ti -1c
.RI "int64_t \fBlast_block_start\fP"
.br
.ti -1c
.RI "ssize_t \fBlast_block_length\fP"
.br
.ti -1c
.RI "int \fBdist_cache\fP [4]"
.br
.ti -1c
.RI "struct \fBdata_ready\fP \fBdready\fP [2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
