.TH "config_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ush \fBgood_length\fP"
.br
.ti -1c
.RI "ush \fBmax_lazy\fP"
.br
.ti -1c
.RI "ush \fBnice_length\fP"
.br
.ti -1c
.RI "ush \fBmax_chain\fP"
.br
.ti -1c
.RI "compress_func \fBfunc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
