.TH "configurable" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configurable
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBversion\fP"
.br
.ti -1c
.RI "bool \fBpublish_before_suback\fP"
.br
.ti -1c
.RI "bool \fBshort_publish\fP"
.br
.ti -1c
.RI "bool \fBexcessive_remaining\fP"
.br
.ti -1c
.RI "unsigned char \fBerror_connack\fP"
.br
.ti -1c
.RI "int \fBtestnum\fP"
.br
.ti -1c
.RI "unsigned char \fBnmethods_min\fP"
.br
.ti -1c
.RI "unsigned char \fBnmethods_max\fP"
.br
.ti -1c
.RI "unsigned char \fBresponseversion\fP"
.br
.ti -1c
.RI "unsigned char \fBresponsemethod\fP"
.br
.ti -1c
.RI "unsigned char \fBreqcmd\fP"
.br
.ti -1c
.RI "unsigned char \fBconnectrep\fP"
.br
.ti -1c
.RI "unsigned short \fBport\fP"
.br
.ti -1c
.RI "char \fBaddr\fP [32]"
.br
.ti -1c
.RI "char \fBuser\fP [256]"
.br
.ti -1c
.RI "char \fBpassword\fP [256]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
