.TH "Config" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCommandLineArguments\fP \fBcmd_args_\fP"
.br
.ti -1c
.RI "ActionType \fBaction_type_\fP"
.br
.ti -1c
.RI "const char * \fBinput_\fP"
.br
.ti -1c
.RI "const char * \fBoutput_\fP"
.br
.ti -1c
.RI "FeatureType \fBtype_\fP"
.br
.ti -1c
.RI "\fBFeatureArg\fP * \fBargs_\fP"
.br
.ti -1c
.RI "int \fBarg_count_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
