.TH "conf_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conf_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBhttp_proxy\fP [MAX_STRING1]"
.br
.ti -1c
.RI "char \fBproxy_user\fP [MAX_STRING1]"
.br
.ti -1c
.RI "char \fBtimeserver\fP [MAX_STRING1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
