.TH "conical_gradient" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conical_gradient
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBgradient_t\fP \fBcommon\fP"
.br
.ti -1c
.RI "\fBpixman_point_fixed_t\fP \fBcenter\fP"
.br
.ti -1c
.RI "double \fBangle\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
