.TH "conjunction< P1, Pn... >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conjunction< P1, Pn... >
.SH SYNOPSIS
.br
.PP
.PP
Inherits conditional_t< bool(P1::value), conjunction< Pn\&.\&.\&. >, P1 >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
