.TH "ConnectBits" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConnectBits
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBIT\fP (httpproxy)"
.br
.ti -1c
.RI "\fBBIT\fP (socksproxy)"
.br
.ti -1c
.RI "\fBBIT\fP (proxy_user_passwd)"
.br
.ti -1c
.RI "\fBBIT\fP (tunnel_proxy)"
.br
.ti -1c
.RI "\fBBIT\fP (proxy_connect_closed)"
.br
.ti -1c
.RI "\fBBIT\fP (close)"
.br
.ti -1c
.RI "\fBBIT\fP (reuse)"
.br
.ti -1c
.RI "\fBBIT\fP (altused)"
.br
.ti -1c
.RI "\fBBIT\fP (conn_to_host)"
.br
.ti -1c
.RI "\fBBIT\fP (conn_to_port)"
.br
.ti -1c
.RI "\fBBIT\fP (proxy)"
.br
.ti -1c
.RI "\fBBIT\fP (user_passwd)"
.br
.ti -1c
.RI "\fBBIT\fP (ipv6_ip)"
.br
.ti -1c
.RI "\fBBIT\fP (ipv6)"
.br
.ti -1c
.RI "\fBBIT\fP (do_more)"
.br
.ti -1c
.RI "\fBBIT\fP (protoconnstart)"
.br
.ti -1c
.RI "\fBBIT\fP (retry)"
.br
.ti -1c
.RI "\fBBIT\fP (authneg)"
.br
.ti -1c
.RI "\fBBIT\fP (rewindaftersend)"
.br
.ti -1c
.RI "\fBBIT\fP (ftp_use_epsv)"
.br
.ti -1c
.RI "\fBBIT\fP (ftp_use_eprt)"
.br
.ti -1c
.RI "\fBBIT\fP (ftp_use_data_ssl)"
.br
.ti -1c
.RI "\fBBIT\fP (ftp_use_control_ssl)"
.br
.ti -1c
.RI "\fBBIT\fP (netrc)"
.br
.ti -1c
.RI "\fBBIT\fP (bound)"
.br
.ti -1c
.RI "\fBBIT\fP (multiplex)"
.br
.ti -1c
.RI "\fBBIT\fP (tcp_fastopen)"
.br
.ti -1c
.RI "\fBBIT\fP (tls_enable_npn)"
.br
.ti -1c
.RI "\fBBIT\fP (tls_enable_alpn)"
.br
.ti -1c
.RI "\fBBIT\fP (connect_only)"
.br
.ti -1c
.RI "\fBBIT\fP (doh)"
.br
.ti -1c
.RI "\fBBIT\fP (tls_upgraded)"
.br
.ti -1c
.RI "\fBBIT\fP (sock_accepted)"
.br
.ti -1c
.RI "\fBBIT\fP (parallel_connect)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBtcpconnect\fP [2]"
.br
.ti -1c
.RI "bool \fBproxy_ssl_connected\fP [2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
