.TH "connectdata" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
connectdata
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBTRNSPRT_TCP\fP = 3, \fBTRNSPRT_UDP\fP = 4, \fBTRNSPRT_QUIC\fP = 5 }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBconnstate\fP \fBcnnct\fP"
.br
.ti -1c
.RI "struct \fBCurl_llist_element\fP \fBbundle_node\fP"
.br
.ti -1c
.RI "struct \fBCurl_chunker\fP \fBchunk\fP"
.br
.ti -1c
.RI "curl_closesocket_callback \fBfclosesocket\fP"
.br
.ti -1c
.RI "void * \fBclosesocket_client\fP"
.br
.ti -1c
.RI "long \fBconnection_id\fP"
.br
.ti -1c
.RI "struct \fBCurl_dns_entry\fP * \fBdns_entry\fP"
.br
.ti -1c
.RI "struct \fBCurl_addrinfo\fP * \fBip_addr\fP"
.br
.ti -1c
.RI "struct \fBCurl_addrinfo\fP * \fBtempaddr\fP [2]"
.br
.ti -1c
.RI "unsigned int \fBscope_id\fP"
.br
.ti -1c
.RI "enum connectdata:: { \&.\&.\&. }  \fBtransport\fP"
.br
.ti -1c
.RI "struct \fBhostname\fP \fBhost\fP"
.br
.ti -1c
.RI "char * \fBhostname_resolve\fP"
.br
.ti -1c
.RI "char * \fBsecondaryhostname\fP"
.br
.ti -1c
.RI "struct \fBhostname\fP \fBconn_to_host\fP"
.br
.ti -1c
.RI "struct \fBproxy_info\fP \fBsocks_proxy\fP"
.br
.ti -1c
.RI "struct \fBproxy_info\fP \fBhttp_proxy\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "int \fBremote_port\fP"
.br
.ti -1c
.RI "int \fBconn_to_port\fP"
.br
.ti -1c
.RI "unsigned short \fBsecondary_port\fP"
.br
.ti -1c
.RI "char \fBprimary_ip\fP [MAX_IPADR_LEN]"
.br
.ti -1c
.RI "unsigned char \fBip_version\fP"
.br
.ti -1c
.RI "char * \fBuser\fP"
.br
.ti -1c
.RI "char * \fBpasswd\fP"
.br
.ti -1c
.RI "char * \fBoptions\fP"
.br
.ti -1c
.RI "char * \fBsasl_authzid\fP"
.br
.ti -1c
.RI "unsigned char \fBhttpversion\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBnow\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBcreated\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBlastused\fP"
.br
.ti -1c
.RI "curl_socket_t \fBsock\fP [2]"
.br
.ti -1c
.RI "curl_socket_t \fBtempsock\fP [2]"
.br
.ti -1c
.RI "int \fBtempfamily\fP [2]"
.br
.ti -1c
.RI "Curl_recv * \fBrecv\fP [2]"
.br
.ti -1c
.RI "Curl_send * \fBsend\fP [2]"
.br
.ti -1c
.RI "struct \fBssl_connect_data\fP \fBssl\fP [2]"
.br
.ti -1c
.RI "struct \fBssl_connect_data\fP \fBproxy_ssl\fP [2]"
.br
.ti -1c
.RI "struct \fBssl_primary_config\fP \fBssl_config\fP"
.br
.ti -1c
.RI "struct \fBssl_primary_config\fP \fBproxy_ssl_config\fP"
.br
.ti -1c
.RI "struct \fBConnectBits\fP \fBbits\fP"
.br
.ti -1c
.RI "int \fBnum_addr\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBconnecttime\fP"
.br
.ti -1c
.RI "timediff_t \fBtimeoutms_per_addr\fP [2]"
.br
.ti -1c
.RI "const struct \fBCurl_handler\fP * \fBhandler\fP"
.br
.ti -1c
.RI "const struct \fBCurl_handler\fP * \fBgiven\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBkeepalive\fP"
.br
.ti -1c
.RI "curl_socket_t \fBsockfd\fP"
.br
.ti -1c
.RI "curl_socket_t \fBwritesockfd\fP"
.br
.ti -1c
.RI "struct \fBCurl_llist\fP \fBeasyq\fP"
.br
.ti -1c
.RI "curl_seek_callback \fBseek_func\fP"
.br
.ti -1c
.RI "void * \fBseek_client\fP"
.br
.ti -1c
.RI "struct \fBdynbuf\fP \fBtrailer\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct \fBftp_conn\fP \fBftpc\fP"
.br
.ti -1c
.RI "   struct \fBhttp_conn\fP \fBhttpc\fP"
.br
.ti -1c
.RI "   struct \fBssh_conn\fP \fBsshc\fP"
.br
.ti -1c
.RI "   struct \fBtftp_state_data\fP * \fBtftpc\fP"
.br
.ti -1c
.RI "   struct \fBimap_conn\fP \fBimapc\fP"
.br
.ti -1c
.RI "   struct \fBpop3_conn\fP \fBpop3c\fP"
.br
.ti -1c
.RI "   struct \fBsmtp_conn\fP \fBsmtpc\fP"
.br
.ti -1c
.RI "   struct \fBrtsp_conn\fP \fBrtspc\fP"
.br
.ti -1c
.RI "   struct \fBsmb_conn\fP \fBsmbc\fP"
.br
.ti -1c
.RI "   void * \fBrtmp\fP"
.br
.ti -1c
.RI "   struct ldapconninfo * \fBldapc\fP"
.br
.ti -1c
.RI "   struct \fBmqtt_conn\fP \fBmqtt\fP"
.br
.ti -1c
.RI "} \fBproto\fP"
.br
.ti -1c
.RI "struct \fBhttp_connect_state\fP * \fBconnect_state\fP"
.br
.ti -1c
.RI "struct \fBconnectbundle\fP * \fBbundle\fP"
.br
.ti -1c
.RI "char * \fBlocaldev\fP"
.br
.ti -1c
.RI "int \fBlocalportrange\fP"
.br
.ti -1c
.RI "int \fBcselect_bits\fP"
.br
.ti -1c
.RI "int \fBwaitfor\fP"
.br
.ti -1c
.RI "int \fBnegnpn\fP"
.br
.ti -1c
.RI "unsigned short \fBlocalport\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
