.TH "ConstructFromT< T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstructFromT< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstructFromT\fP (const T &t)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args, typename std::enable_if< sizeof\&.\&.\&.(Args) !=1, int >::type  = 0> \fBConstructFromT\fP (Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBConstructFromT\fP &other) const"
.br
.ti -1c
.RI "const T & \fBget\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
