.TH "contenc_writer" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contenc_writer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const struct \fBcontent_encoding\fP * \fBhandler\fP"
.br
.ti -1c
.RI "struct \fBcontenc_writer\fP * \fBdownstream\fP"
.br
.ti -1c
.RI "void * \fBparams\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
