.TH "CookieInfo" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CookieInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBCookie\fP * \fBcookies\fP [COOKIE_HASH_SIZE]"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "long \fBnumcookies\fP"
.br
.ti -1c
.RI "bool \fBrunning\fP"
.br
.ti -1c
.RI "bool \fBnewsession\fP"
.br
.ti -1c
.RI "int \fBlastct\fP"
.br
.ti -1c
.RI "curl_off_t \fBnext_expiration\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
