.TH "Cookie" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cookie
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBCookie\fP * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "char * \fBspath\fP"
.br
.ti -1c
.RI "char * \fBdomain\fP"
.br
.ti -1c
.RI "curl_off_t \fBexpires\fP"
.br
.ti -1c
.RI "char * \fBexpirestr\fP"
.br
.ti -1c
.RI "char * \fBversion\fP"
.br
.ti -1c
.RI "char * \fBmaxage\fP"
.br
.ti -1c
.RI "bool \fBtailmatch\fP"
.br
.ti -1c
.RI "bool \fBsecure\fP"
.br
.ti -1c
.RI "bool \fBlivecookie\fP"
.br
.ti -1c
.RI "bool \fBhttponly\fP"
.br
.ti -1c
.RI "int \fBcreationtime\fP"
.br
.ti -1c
.RI "unsigned char \fBprefix\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
