.TH "CostManager" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CostManager
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCostInterval\fP * \fBhead_\fP"
.br
.ti -1c
.RI "int \fBcount_\fP"
.br
.ti -1c
.RI "\fBCostCacheInterval\fP * \fBcache_intervals_\fP"
.br
.ti -1c
.RI "size_t \fBcache_intervals_size_\fP"
.br
.ti -1c
.RI "double \fBcost_cache_\fP [MAX_LENGTH]"
.br
.ti -1c
.RI "float * \fBcosts_\fP"
.br
.ti -1c
.RI "uint16_t * \fBdist_array_\fP"
.br
.ti -1c
.RI "\fBCostInterval\fP \fBintervals_\fP [COST_MANAGER_MAX_FREE_LIST]"
.br
.ti -1c
.RI "\fBCostInterval\fP * \fBfree_intervals_\fP"
.br
.ti -1c
.RI "\fBCostInterval\fP * \fBrecycled_intervals_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
