.TH "CostModel" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CostModel
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBalpha_\fP [VALUES_IN_BYTE]"
.br
.ti -1c
.RI "double \fBred_\fP [VALUES_IN_BYTE]"
.br
.ti -1c
.RI "double \fBblue_\fP [VALUES_IN_BYTE]"
.br
.ti -1c
.RI "double \fBdistance_\fP [NUM_DISTANCE_CODES]"
.br
.ti -1c
.RI "double * \fBliteral_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
