.TH "count_fractional_digits< Num, Den, N, Enabled >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
count_fractional_digits< Num, Den, N, Enabled >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr int \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<long long Num, long long Den, int N = 0, bool Enabled = (N < 19) && (Num <= max_value<long long>() / 10)> static constexpr int \fBcount_fractional_digits\fP< Num, Den, N, Enabled >\fB::value\fP\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
      Num % Den == 0 ? N : count_fractional_digits<Num * 10, Den, N + 1>::value
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
