.TH "cpio" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cpio
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBargument\fP"
.br
.ti -1c
.RI "int \fBadd_filter\fP"
.br
.ti -1c
.RI "const char * \fBfilename\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBcompress\fP"
.br
.ti -1c
.RI "const char * \fBformat\fP"
.br
.ti -1c
.RI "int \fBbytes_per_block\fP"
.br
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "int \fBdot\fP"
.br
.ti -1c
.RI "int \fBquiet\fP"
.br
.ti -1c
.RI "int \fBextract_flags\fP"
.br
.ti -1c
.RI "const char * \fBcompress_program\fP"
.br
.ti -1c
.RI "int \fBoption_append\fP"
.br
.ti -1c
.RI "int \fBoption_atime_restore\fP"
.br
.ti -1c
.RI "int \fBoption_follow_links\fP"
.br
.ti -1c
.RI "int \fBoption_link\fP"
.br
.ti -1c
.RI "int \fBoption_list\fP"
.br
.ti -1c
.RI "char \fBoption_null\fP"
.br
.ti -1c
.RI "int \fBoption_numeric_uid_gid\fP"
.br
.ti -1c
.RI "int \fBoption_pwb\fP"
.br
.ti -1c
.RI "int \fBoption_rename\fP"
.br
.ti -1c
.RI "char * \fBdestdir\fP"
.br
.ti -1c
.RI "size_t \fBdestdir_len\fP"
.br
.ti -1c
.RI "size_t \fBpass_destpath_alloc\fP"
.br
.ti -1c
.RI "char * \fBpass_destpath\fP"
.br
.ti -1c
.RI "int \fBuid_override\fP"
.br
.ti -1c
.RI "char * \fBuname_override\fP"
.br
.ti -1c
.RI "int \fBgid_override\fP"
.br
.ti -1c
.RI "char * \fBgname_override\fP"
.br
.ti -1c
.RI "int \fBday_first\fP"
.br
.ti -1c
.RI "const char * \fBpassphrase\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "struct \fBarchive\fP * \fBarchive\fP"
.br
.ti -1c
.RI "struct \fBarchive\fP * \fBarchive_read_disk\fP"
.br
.ti -1c
.RI "int \fBargc\fP"
.br
.ti -1c
.RI "char ** \fBargv\fP"
.br
.ti -1c
.RI "int \fBreturn_value\fP"
.br
.ti -1c
.RI "struct \fBarchive_entry_linkresolver\fP * \fBlinkresolver\fP"
.br
.ti -1c
.RI "struct \fBname_cache\fP * \fBuname_cache\fP"
.br
.ti -1c
.RI "struct \fBname_cache\fP * \fBgname_cache\fP"
.br
.ti -1c
.RI "struct \fBarchive\fP * \fBmatching\fP"
.br
.ti -1c
.RI "char * \fBbuff\fP"
.br
.ti -1c
.RI "size_t \fBbuff_size\fP"
.br
.ti -1c
.RI "char * \fBppbuff\fP"
.br
.ti -1c
.RI "int \fBmagic\fP"
.br
.ti -1c
.RI "int(* \fBread_header\fP )(struct \fBarchive_read\fP *, struct \fBcpio\fP *, struct \fBarchive_entry\fP *, size_t *, size_t *)"
.br
.ti -1c
.RI "struct \fBlinks_entry\fP * \fBlinks_head\fP"
.br
.ti -1c
.RI "int64_t \fBentry_bytes_remaining\fP"
.br
.ti -1c
.RI "int64_t \fBentry_bytes_unconsumed\fP"
.br
.ti -1c
.RI "int64_t \fBentry_offset\fP"
.br
.ti -1c
.RI "int64_t \fBentry_padding\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBopt_sconv\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_default\fP"
.br
.ti -1c
.RI "int \fBinit_default_conversion\fP"
.br
.ti -1c
.RI "uint64_t \fBentry_bytes_remaining\fP"
.br
.ti -1c
.RI "int64_t \fBino_next\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int64_t \fBold\fP"
.br
.ti -1c
.RI "   int \fBnew\fP"
.br
.ti -1c
.RI "} * \fBino_list\fP"
.br
.ti -1c
.RI "size_t \fBino_list_size\fP"
.br
.ti -1c
.RI "size_t \fBino_list_next\fP"
.br
.ti -1c
.RI "int \fBpadding\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int64_t \fBold\fP"
.br
.ti -1c
.RI "   int \fBnew\fP"
.br
.ti -1c
.RI "} * \fBino_list\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
