.TH "CPpmd7z_RangeEnc" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CPpmd7z_RangeEnc
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UInt64 \fBLow\fP"
.br
.ti -1c
.RI "UInt32 \fBRange\fP"
.br
.ti -1c
.RI "Byte \fBCache\fP"
.br
.ti -1c
.RI "UInt64 \fBCacheSize\fP"
.br
.ti -1c
.RI "\fBIByteOut\fP * \fBStream\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
