.TH "CPpmd7_Context_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CPpmd7_Context_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UInt16 \fBNumStats\fP"
.br
.ti -1c
.RI "UInt16 \fBSummFreq\fP"
.br
.ti -1c
.RI "CPpmd_State_Ref \fBStats\fP"
.br
.ti -1c
.RI "CPpmd7_Context_Ref \fBSuffix\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
