.TH "CPpmd7" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CPpmd7
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCPpmd7_Context\fP * \fBMinContext\fP"
.br
.ti -1c
.RI "\fBCPpmd7_Context\fP * \fBMaxContext\fP"
.br
.ti -1c
.RI "\fBCPpmd_State\fP * \fBFoundState\fP"
.br
.ti -1c
.RI "unsigned \fBOrderFall\fP"
.br
.ti -1c
.RI "unsigned \fBInitEsc\fP"
.br
.ti -1c
.RI "unsigned \fBPrevSuccess\fP"
.br
.ti -1c
.RI "unsigned \fBMaxOrder\fP"
.br
.ti -1c
.RI "unsigned \fBHiBitsFlag\fP"
.br
.ti -1c
.RI "Int32 \fBRunLength\fP"
.br
.ti -1c
.RI "Int32 \fBInitRL\fP"
.br
.ti -1c
.RI "UInt32 \fBSize\fP"
.br
.ti -1c
.RI "UInt32 \fBGlueCount\fP"
.br
.ti -1c
.RI "Byte * \fBBase\fP"
.br
.ti -1c
.RI "Byte * \fBLoUnit\fP"
.br
.ti -1c
.RI "Byte * \fBHiUnit\fP"
.br
.ti -1c
.RI "Byte * \fBText\fP"
.br
.ti -1c
.RI "Byte * \fBUnitsStart\fP"
.br
.ti -1c
.RI "UInt32 \fBAlignOffset\fP"
.br
.ti -1c
.RI "Byte \fBIndx2Units\fP [PPMD_NUM_INDEXES]"
.br
.ti -1c
.RI "Byte \fBUnits2Indx\fP [128]"
.br
.ti -1c
.RI "CPpmd_Void_Ref \fBFreeList\fP [PPMD_NUM_INDEXES]"
.br
.ti -1c
.RI "Byte \fBNS2Indx\fP [256]"
.br
.ti -1c
.RI "Byte \fBNS2BSIndx\fP [256]"
.br
.ti -1c
.RI "Byte \fBHB2Flag\fP [256]"
.br
.ti -1c
.RI "\fBCPpmd_See\fP \fBDummySee\fP"
.br
.ti -1c
.RI "\fBCPpmd_See\fP \fBSee\fP [25][16]"
.br
.ti -1c
.RI "UInt16 \fBBinSumm\fP [128][64]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
