.TH "creation_set" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
creation_set
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBfilter_set\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBcreate_format\fP"
.br
.ti -1c
.RI "struct \fBcreation_set::filter_set\fP * \fBfilters\fP"
.br
.ti -1c
.RI "int \fBfilter_count\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
