.TH "CrunchConfig" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CrunchConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBentropy_idx_\fP"
.br
.ti -1c
.RI "PaletteSorting \fBpalette_sorting_type_\fP"
.br
.ti -1c
.RI "\fBCrunchSubConfig\fP \fBsub_configs_\fP [CRUNCH_SUBCONFIGS_MAX]"
.br
.ti -1c
.RI "int \fBsub_configs_size_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
