.TH "ct_data_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ct_data_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   ush \fBfreq\fP"
.br
.ti -1c
.RI "   ush \fBcode\fP"
.br
.ti -1c
.RI "} \fBfc\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   ush \fBdad\fP"
.br
.ti -1c
.RI "   ush \fBlen\fP"
.br
.ti -1c
.RI "} \fBdl\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
