.TH "ctl_extr_rec" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctl_extr_rec
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBuse_extr\fP"
.br
.ti -1c
.RI "unsigned char * \fBbp\fP"
.br
.ti -1c
.RI "struct \fBisoent\fP * \fBisoent\fP"
.br
.ti -1c
.RI "unsigned char * \fBce_ptr\fP"
.br
.ti -1c
.RI "int \fBcur_len\fP"
.br
.ti -1c
.RI "int \fBdr_len\fP"
.br
.ti -1c
.RI "int \fBlimit\fP"
.br
.ti -1c
.RI "int \fBextr_off\fP"
.br
.ti -1c
.RI "int \fBextr_loc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
