.TH "curfile64_info" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curfile64_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBz_stream\fP \fBstream\fP"
.br
.ti -1c
.RI "int \fBstream_initialised\fP"
.br
.ti -1c
.RI "uInt \fBpos_in_buffered_data\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBpos_local_header\fP"
.br
.ti -1c
.RI "char * \fBcentral_header\fP"
.br
.ti -1c
.RI "uLong \fBsize_centralExtra\fP"
.br
.ti -1c
.RI "uLong \fBsize_centralheader\fP"
.br
.ti -1c
.RI "uLong \fBsize_centralExtraFree\fP"
.br
.ti -1c
.RI "uLong \fBflag\fP"
.br
.ti -1c
.RI "int \fBmethod\fP"
.br
.ti -1c
.RI "int \fBraw\fP"
.br
.ti -1c
.RI "Byte \fBbuffered_data\fP [Z_BUFSIZE]"
.br
.ti -1c
.RI "uLong \fBdosDate\fP"
.br
.ti -1c
.RI "uLong \fBcrc32\fP"
.br
.ti -1c
.RI "int \fBencrypt\fP"
.br
.ti -1c
.RI "int \fBzip64\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBpos_zip64extrainfo\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBtotalCompressedData\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBtotalUncompressedData\fP"
.br
.ti -1c
.RI "unsigned long \fBkeys\fP [3]"
.br
.ti -1c
.RI "const z_crc_t * \fBpcrc_32_tab\fP"
.br
.ti -1c
.RI "int \fBcrypt_header_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
