.TH "Curl_sec_client_mech" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Curl_sec_client_mech
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "int(* \fBinit\fP )(void *)"
.br
.ti -1c
.RI "int(* \fBauth\fP )(void *, struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *)"
.br
.ti -1c
.RI "void(* \fBend\fP )(void *)"
.br
.ti -1c
.RI "int(* \fBcheck_prot\fP )(void *, int)"
.br
.ti -1c
.RI "int(* \fBencode\fP )(void *, const void *, int, int, void **)"
.br
.ti -1c
.RI "int(* \fBdecode\fP )(void *, void *, int, int, struct \fBconnectdata\fP *)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
