.TH "Curl_async" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Curl_async
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBIT\fP (done)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBhostname\fP"
.br
.ti -1c
.RI "struct \fBCurl_dns_entry\fP * \fBdns\fP"
.br
.ti -1c
.RI "struct thread_data * \fBtdata\fP"
.br
.ti -1c
.RI "void * \fBresolver\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
