.TH "curl_context_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curl_context_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct event * \fBevent\fP"
.br
.ti -1c
.RI "curl_socket_t \fBsockfd\fP"
.br
.ti -1c
.RI "uv_poll_t \fBpoll_handle\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
