.TH "Curl_share" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Curl_share
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBmagic\fP"
.br
.ti -1c
.RI "unsigned int \fBspecifier\fP"
.br
.ti -1c
.RI "CURL_VOLATILE unsigned int \fBdirty\fP"
.br
.ti -1c
.RI "curl_lock_function \fBlockfunc\fP"
.br
.ti -1c
.RI "curl_unlock_function \fBunlockfunc\fP"
.br
.ti -1c
.RI "void * \fBclientdata\fP"
.br
.ti -1c
.RI "struct \fBconncache\fP \fBconn_cache\fP"
.br
.ti -1c
.RI "struct \fBCurl_hash\fP \fBhostcache\fP"
.br
.ti -1c
.RI "struct \fBCookieInfo\fP * \fBcookies\fP"
.br
.ti -1c
.RI "struct \fBCurl_ssl_session\fP * \fBsslsession\fP"
.br
.ti -1c
.RI "size_t \fBmax_ssl_sessions\fP"
.br
.ti -1c
.RI "long \fBsessionage\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
