.TH "curl_httppost" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curl_httppost
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBcurl_httppost\fP * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "long \fBnamelength\fP"
.br
.ti -1c
.RI "char * \fBcontents\fP"
.br
.ti -1c
.RI "long \fBcontentslength\fP"
.br
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.ti -1c
.RI "long \fBbufferlength\fP"
.br
.ti -1c
.RI "char * \fBcontenttype\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBcontentheader\fP"
.br
.ti -1c
.RI "struct \fBcurl_httppost\fP * \fBmore\fP"
.br
.ti -1c
.RI "long \fBflags\fP"
.br
.ti -1c
.RI "char * \fBshowfilename\fP"
.br
.ti -1c
.RI "void * \fBuserp\fP"
.br
.ti -1c
.RI "curl_off_t \fBcontentlen\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
