.TH "curl_fileinfo" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curl_fileinfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "curlfiletype \fBfiletype\fP"
.br
.ti -1c
.RI "time_t \fBtime\fP"
.br
.ti -1c
.RI "unsigned int \fBperm\fP"
.br
.ti -1c
.RI "int \fBuid\fP"
.br
.ti -1c
.RI "int \fBgid\fP"
.br
.ti -1c
.RI "curl_off_t \fBsize\fP"
.br
.ti -1c
.RI "long int \fBhardlinks\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   char * \fBtime\fP"
.br
.ti -1c
.RI "   char * \fBperm\fP"
.br
.ti -1c
.RI "   char * \fBuser\fP"
.br
.ti -1c
.RI "   char * \fBgroup\fP"
.br
.ti -1c
.RI "   char * \fBtarget\fP"
.br
.ti -1c
.RI "} \fBstrings\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.ti -1c
.RI "char * \fBb_data\fP"
.br
.ti -1c
.RI "size_t \fBb_size\fP"
.br
.ti -1c
.RI "size_t \fBb_used\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
