.TH "curl_mime" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curl_mime
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBCurl_easy\fP * \fBeasy\fP"
.br
.ti -1c
.RI "\fBcurl_mimepart\fP * \fBparent\fP"
.br
.ti -1c
.RI "\fBcurl_mimepart\fP * \fBfirstpart\fP"
.br
.ti -1c
.RI "\fBcurl_mimepart\fP * \fBlastpart\fP"
.br
.ti -1c
.RI "char \fBboundary\fP [MIME_BOUNDARY_LEN]"
.br
.ti -1c
.RI "struct \fBmime_state\fP \fBstate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
