.TH "curl_version_info_data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curl_version_info_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CURLversion \fBage\fP"
.br
.ti -1c
.RI "const char * \fBversion\fP"
.br
.ti -1c
.RI "unsigned int \fBversion_num\fP"
.br
.ti -1c
.RI "const char * \fBhost\fP"
.br
.ti -1c
.RI "int \fBfeatures\fP"
.br
.ti -1c
.RI "const char * \fBssl_version\fP"
.br
.ti -1c
.RI "long \fBssl_version_num\fP"
.br
.ti -1c
.RI "const char * \fBlibz_version\fP"
.br
.ti -1c
.RI "const char *const  * \fBprotocols\fP"
.br
.ti -1c
.RI "const char * \fBares\fP"
.br
.ti -1c
.RI "int \fBares_num\fP"
.br
.ti -1c
.RI "const char * \fBlibidn\fP"
.br
.ti -1c
.RI "int \fBiconv_ver_num\fP"
.br
.ti -1c
.RI "const char * \fBlibssh_version\fP"
.br
.ti -1c
.RI "unsigned int \fBbrotli_ver_num\fP"
.br
.ti -1c
.RI "const char * \fBbrotli_version\fP"
.br
.ti -1c
.RI "unsigned int \fBnghttp2_ver_num\fP"
.br
.ti -1c
.RI "const char * \fBnghttp2_version\fP"
.br
.ti -1c
.RI "const char * \fBquic_version\fP"
.br
.ti -1c
.RI "const char * \fBcainfo\fP"
.br
.ti -1c
.RI "const char * \fBcapath\fP"
.br
.ti -1c
.RI "unsigned int \fBzstd_ver_num\fP"
.br
.ti -1c
.RI "const char * \fBzstd_version\fP"
.br
.ti -1c
.RI "const char * \fBhyper_version\fP"
.br
.ti -1c
.RI "const char * \fBgsasl_version\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
