.TH "curl_sockaddr" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curl_sockaddr
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfamily\fP"
.br
.ti -1c
.RI "int \fBsocktype\fP"
.br
.ti -1c
.RI "int \fBprotocol\fP"
.br
.ti -1c
.RI "unsigned int \fBaddrlen\fP"
.br
.ti -1c
.RI "struct sockaddr \fBaddr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
