.TH "Curl_addrinfo" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Curl_addrinfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBai_flags\fP"
.br
.ti -1c
.RI "int \fBai_family\fP"
.br
.ti -1c
.RI "int \fBai_socktype\fP"
.br
.ti -1c
.RI "int \fBai_protocol\fP"
.br
.ti -1c
.RI "curl_socklen_t \fBai_addrlen\fP"
.br
.ti -1c
.RI "char * \fBai_canonname\fP"
.br
.ti -1c
.RI "struct sockaddr * \fBai_addr\fP"
.br
.ti -1c
.RI "struct \fBCurl_addrinfo\fP * \fBai_next\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
