.TH "Curl_sockaddr_ex" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Curl_sockaddr_ex
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfamily\fP"
.br
.ti -1c
.RI "int \fBsocktype\fP"
.br
.ti -1c
.RI "int \fBprotocol\fP"
.br
.ti -1c
.RI "unsigned int \fBaddrlen\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct sockaddr \fBaddr\fP"
.br
.ti -1c
.RI "   struct \fBCurl_sockaddr_storage\fP \fBbuff\fP"
.br
.ti -1c
.RI "} \fB_sa_ex_u\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
