.TH "Curl_ssl" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Curl_ssl
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcurl_ssl_backend\fP \fBinfo\fP"
.br
.ti -1c
.RI "unsigned int \fBsupports\fP"
.br
.ti -1c
.RI "size_t \fBsizeof_ssl_backend_data\fP"
.br
.ti -1c
.RI "int(* \fBinit\fP )(void)"
.br
.ti -1c
.RI "void(* \fBcleanup\fP )(void)"
.br
.ti -1c
.RI "size_t(* \fBversion\fP )(char *\fBbuffer\fP, size_t size)"
.br
.ti -1c
.RI "int(* \fBcheck_cxn\fP )(struct \fBconnectdata\fP *cxn)"
.br
.ti -1c
.RI "int(* \fBshut_down\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, int sockindex)"
.br
.ti -1c
.RI "bool(* \fBdata_pending\fP )(const struct \fBconnectdata\fP *conn, int connindex)"
.br
.ti -1c
.RI "CURLcode(* \fBrandom\fP )(struct \fBCurl_easy\fP *\fBdata\fP, unsigned char *entropy, size_t length)"
.br
.ti -1c
.RI "bool(* \fBcert_status_request\fP )(void)"
.br
.ti -1c
.RI "CURLcode(* \fBconnect_blocking\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, int sockindex)"
.br
.ti -1c
.RI "CURLcode(* \fBconnect_nonblocking\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, int sockindex, bool *done)"
.br
.ti -1c
.RI "int(* \fBgetsock\fP )(struct \fBconnectdata\fP *conn, curl_socket_t *socks)"
.br
.ti -1c
.RI "void *(* \fBget_internals\fP )(struct \fBssl_connect_data\fP *connssl, CURLINFO info)"
.br
.ti -1c
.RI "void(* \fBclose_one\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, int sockindex)"
.br
.ti -1c
.RI "void(* \fBclose_all\fP )(struct \fBCurl_easy\fP *\fBdata\fP)"
.br
.ti -1c
.RI "void(* \fBsession_free\fP )(void *ptr)"
.br
.ti -1c
.RI "CURLcode(* \fBset_engine\fP )(struct \fBCurl_easy\fP *\fBdata\fP, const char *engine)"
.br
.ti -1c
.RI "CURLcode(* \fBset_engine_default\fP )(struct \fBCurl_easy\fP *\fBdata\fP)"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP *(* \fBengines_list\fP )(struct \fBCurl_easy\fP *\fBdata\fP)"
.br
.ti -1c
.RI "bool(* \fBfalse_start\fP )(void)"
.br
.ti -1c
.RI "CURLcode(* \fBsha256sum\fP )(const unsigned char *\fBinput\fP, size_t inputlen, unsigned char *sha256sum, size_t sha256sumlen)"
.br
.ti -1c
.RI "void(* \fBassociate_connection\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, int sockindex)"
.br
.ti -1c
.RI "void(* \fBdisassociate_connection\fP )(struct \fBCurl_easy\fP *\fBdata\fP, int sockindex)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
