.TH "curl_mimepart" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curl_mimepart
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBCurl_easy\fP * \fBeasy\fP"
.br
.ti -1c
.RI "\fBcurl_mime\fP * \fBparent\fP"
.br
.ti -1c
.RI "\fBcurl_mimepart\fP * \fBnextpart\fP"
.br
.ti -1c
.RI "enum mimekind \fBkind\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.ti -1c
.RI "char * \fBdata\fP"
.br
.ti -1c
.RI "curl_read_callback \fBreadfunc\fP"
.br
.ti -1c
.RI "curl_seek_callback \fBseekfunc\fP"
.br
.ti -1c
.RI "curl_free_callback \fBfreefunc\fP"
.br
.ti -1c
.RI "void * \fBarg\fP"
.br
.ti -1c
.RI "FILE * \fBfp\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBcurlheaders\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBuserheaders\fP"
.br
.ti -1c
.RI "char * \fBmimetype\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "curl_off_t \fBdatasize\fP"
.br
.ti -1c
.RI "struct \fBmime_state\fP \fBstate\fP"
.br
.ti -1c
.RI "const struct \fBmime_encoder\fP * \fBencoder\fP"
.br
.ti -1c
.RI "struct \fBmime_encoder_state\fP \fBencstate\fP"
.br
.ti -1c
.RI "size_t \fBlastreadstatus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
