.TH "Curl_tree" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Curl_tree
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBCurl_tree\fP * \fBsmaller\fP"
.br
.ti -1c
.RI "struct \fBCurl_tree\fP * \fBlarger\fP"
.br
.ti -1c
.RI "struct \fBCurl_tree\fP * \fBsamen\fP"
.br
.ti -1c
.RI "struct \fBCurl_tree\fP * \fBsamep\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBkey\fP"
.br
.ti -1c
.RI "void * \fBpayload\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
