.TH "Curl_ssl_session" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Curl_ssl_session
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBconn_to_host\fP"
.br
.ti -1c
.RI "const char * \fBscheme\fP"
.br
.ti -1c
.RI "void * \fBsessionid\fP"
.br
.ti -1c
.RI "size_t \fBidsize\fP"
.br
.ti -1c
.RI "long \fBage\fP"
.br
.ti -1c
.RI "int \fBremote_port\fP"
.br
.ti -1c
.RI "int \fBconn_to_port\fP"
.br
.ti -1c
.RI "struct \fBssl_primary_config\fP \fBssl_config\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
