.TH "Curl_multi" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Curl_multi
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBmagic\fP"
.br
.ti -1c
.RI "struct \fBCurl_easy\fP * \fBeasyp\fP"
.br
.ti -1c
.RI "struct \fBCurl_easy\fP * \fBeasylp\fP"
.br
.ti -1c
.RI "int \fBnum_easy\fP"
.br
.ti -1c
.RI "int \fBnum_alive\fP"
.br
.ti -1c
.RI "struct \fBCurl_llist\fP \fBmsglist\fP"
.br
.ti -1c
.RI "struct \fBCurl_llist\fP \fBpending\fP"
.br
.ti -1c
.RI "curl_socket_callback \fBsocket_cb\fP"
.br
.ti -1c
.RI "void * \fBsocket_userp\fP"
.br
.ti -1c
.RI "curl_push_callback \fBpush_cb\fP"
.br
.ti -1c
.RI "void * \fBpush_userp\fP"
.br
.ti -1c
.RI "struct \fBCurl_hash\fP \fBhostcache\fP"
.br
.ti -1c
.RI "struct \fBCurl_tree\fP * \fBtimetree\fP"
.br
.ti -1c
.RI "struct \fBCurl_hash\fP \fBsockhash\fP"
.br
.ti -1c
.RI "struct \fBconncache\fP \fBconn_cache\fP"
.br
.ti -1c
.RI "long \fBmaxconnects\fP"
.br
.ti -1c
.RI "long \fBmax_host_connections\fP"
.br
.ti -1c
.RI "long \fBmax_total_connections\fP"
.br
.ti -1c
.RI "curl_multi_timer_callback \fBtimer_cb\fP"
.br
.ti -1c
.RI "void * \fBtimer_userp\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBtimer_lastcall\fP"
.br
.ti -1c
.RI "unsigned int \fBmax_concurrent_streams\fP"
.br
.ti -1c
.RI "curl_socket_t \fBwakeup_pair\fP [2]"
.br
.ti -1c
.RI "bool \fBmultiplexing\fP"
.br
.ti -1c
.RI "bool \fBrecheckstate\fP"
.br
.ti -1c
.RI "bool \fBin_callback\fP"
.br
.ti -1c
.RI "bool \fBipv6_works\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
