.TH "Curl_handler" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Curl_handler
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBscheme\fP"
.br
.ti -1c
.RI "CURLcode(* \fBsetup_connection\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn)"
.br
.ti -1c
.RI "CURLcode(* \fBdo_it\fP )(struct \fBCurl_easy\fP *\fBdata\fP, bool *done)"
.br
.ti -1c
.RI "CURLcode(* \fBdone\fP )(struct \fBCurl_easy\fP *, CURLcode, bool)"
.br
.ti -1c
.RI "CURLcode(* \fBdo_more\fP )(struct \fBCurl_easy\fP *, int *)"
.br
.ti -1c
.RI "CURLcode(* \fBconnect_it\fP )(struct \fBCurl_easy\fP *\fBdata\fP, bool *done)"
.br
.ti -1c
.RI "CURLcode(* \fBconnecting\fP )(struct \fBCurl_easy\fP *\fBdata\fP, bool *done)"
.br
.ti -1c
.RI "CURLcode(* \fBdoing\fP )(struct \fBCurl_easy\fP *\fBdata\fP, bool *done)"
.br
.ti -1c
.RI "int(* \fBproto_getsock\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, curl_socket_t *socks)"
.br
.ti -1c
.RI "int(* \fBdoing_getsock\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, curl_socket_t *socks)"
.br
.ti -1c
.RI "int(* \fBdomore_getsock\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, curl_socket_t *socks)"
.br
.ti -1c
.RI "int(* \fBperform_getsock\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, curl_socket_t *socks)"
.br
.ti -1c
.RI "CURLcode(* \fBdisconnect\fP )(struct \fBCurl_easy\fP *, struct \fBconnectdata\fP *, bool dead_connection)"
.br
.ti -1c
.RI "CURLcode(* \fBreadwrite\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, ssize_t *nread, bool *readmore)"
.br
.ti -1c
.RI "unsigned int(* \fBconnection_check\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, unsigned int checks_to_perform)"
.br
.ti -1c
.RI "void(* \fBattach\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn)"
.br
.ti -1c
.RI "int \fBdefport\fP"
.br
.ti -1c
.RI "unsigned int \fBprotocol\fP"
.br
.ti -1c
.RI "unsigned int \fBfamily\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
