.TH "Curl_sh_entry" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Curl_sh_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBCurl_hash\fP \fBtransfers\fP"
.br
.ti -1c
.RI "unsigned int \fBaction\fP"
.br
.ti -1c
.RI "unsigned int \fBusers\fP"
.br
.ti -1c
.RI "void * \fBsocketp\fP"
.br
.ti -1c
.RI "unsigned int \fBreaders\fP"
.br
.ti -1c
.RI "unsigned int \fBwriters\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
