.TH "Curl_easy" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Curl_easy
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBmagic\fP"
.br
.ti -1c
.RI "struct \fBCurl_easy\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBCurl_easy\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBconnectdata\fP * \fBconn\fP"
.br
.ti -1c
.RI "struct \fBCurl_llist_element\fP \fBconnect_queue\fP"
.br
.ti -1c
.RI "struct \fBCurl_llist_element\fP \fBconn_queue\fP"
.br
.ti -1c
.RI "CURLMstate \fBmstate\fP"
.br
.ti -1c
.RI "CURLcode \fBresult\fP"
.br
.ti -1c
.RI "struct \fBCurl_message\fP \fBmsg\fP"
.br
.ti -1c
.RI "curl_socket_t \fBsockets\fP [MAX_SOCKSPEREASYHANDLE]"
.br
.ti -1c
.RI "unsigned char \fBactions\fP [MAX_SOCKSPEREASYHANDLE]"
.br
.ti -1c
.RI "int \fBnumsocks\fP"
.br
.ti -1c
.RI "struct \fBNames\fP \fBdns\fP"
.br
.ti -1c
.RI "struct \fBCurl_multi\fP * \fBmulti\fP"
.br
.ti -1c
.RI "struct \fBCurl_multi\fP * \fBmulti_easy\fP"
.br
.ti -1c
.RI "struct \fBCurl_share\fP * \fBshare\fP"
.br
.ti -1c
.RI "struct \fBSingleRequest\fP \fBreq\fP"
.br
.ti -1c
.RI "struct \fBUserDefined\fP \fBset\fP"
.br
.ti -1c
.RI "struct \fBCookieInfo\fP * \fBcookies\fP"
.br
.ti -1c
.RI "struct \fBhsts\fP * \fBhsts\fP"
.br
.ti -1c
.RI "struct \fBaltsvcinfo\fP * \fBasi\fP"
.br
.ti -1c
.RI "struct \fBProgress\fP \fBprogress\fP"
.br
.ti -1c
.RI "struct \fBUrlState\fP \fBstate\fP"
.br
.ti -1c
.RI "struct \fBWildcardData\fP \fBwildcard\fP"
.br
.ti -1c
.RI "struct \fBPureInfo\fP \fBinfo\fP"
.br
.ti -1c
.RI "struct \fBcurl_tlssessioninfo\fP \fBtsi\fP"
.br
.ti -1c
.RI "int \fBfake\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
