.TH "curl_hstsentry" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curl_hstsentry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "size_t \fBnamelen\fP"
.br
.ti -1c
.RI "unsigned int \fBincludeSubDomains\fP:1"
.br
.ti -1c
.RI "char \fBexpire\fP [18]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
