.TH "custom_context" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
custom_context
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBformatter_type\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBchar_type\fP = char"
.br
.ti -1c
.RI "using \fBparse_context_type\fP = fmt::format_parse_context"
.br
.ti -1c
.RI "using \fBchar_type\fP = char"
.br
.ti -1c
.RI "using \fBparse_context_type\fP = fmt::format_parse_context"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadvance_to\fP (const char *)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBcalled\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
