.TH "custom_context::formatter_type< T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
custom_context::formatter_type< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBparse\fP (fmt::format_parse_context &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "const char * \fBformat\fP (const T &, \fBcustom_context\fP &ctx)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
