.TH "custom_formatter< Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
custom_formatter< Char >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (typename \fBbasic_format_arg\fP< \fBbuffer_context\fP< Char > >::handle h) const"
.br
.ti -1c
.RI "template<typename T > void \fBoperator()\fP (T) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (typename \fBbasic_format_arg\fP< \fBbuffer_context\fP< Char > >::handle h) const"
.br
.ti -1c
.RI "template<typename T > void \fBoperator()\fP (T) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (typename \fBbasic_format_arg\fP< \fBbuffer_context\fP< Char > >::handle h) const"
.br
.ti -1c
.RI "template<typename T > void \fBoperator()\fP (T) const"
.br
.ti -1c
.RI "void \fBoperator()\fP (typename \fBbasic_format_arg\fP< \fBbuffer_context\fP< Char > >::handle h) const"
.br
.ti -1c
.RI "template<typename T > void \fBoperator()\fP (T) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbasic_format_parse_context\fP< Char > & \fBparse_ctx\fP"
.br
.ti -1c
.RI "\fBbuffer_context\fP< Char > & \fBctx\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
