.TH "d_derived_tbl" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
d_derived_tbl
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "INT32 \fBmaxcode\fP [18]"
.br
.ti -1c
.RI "INT32 \fBvaloffset\fP [17]"
.br
.ti -1c
.RI "\fBJHUFF_TBL\fP * \fBpub\fP"
.br
.ti -1c
.RI "int \fBlook_nbits\fP [1<< HUFF_LOOKAHEAD]"
.br
.ti -1c
.RI "UINT8 \fBlook_sym\fP [1<< HUFF_LOOKAHEAD]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
