.TH "data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbasic_data< T >\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBtrace_ascii\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBbasic_data< T >\fP
.in +1c
.ti -1c
.RI "static constexpr uint64_t \fBpow10_significands\fP [87]"
.br
.ti -1c
.RI "static constexpr int16_t \fBpow10_exponents\fP [87]"
.br
.ti -1c
.RI "static constexpr uint64_t \fBpower_of_10_64\fP [20]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
