.TH "data_to_string" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_to_string
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdata_to_string\fP (const uint8_t *\fBdata\fP, size_t size, bool add_terminator=false)"
.br
.ti -1c
.RI "fmt::string_view \fBget\fP () const"
.br
.ti -1c
.RI "const char * \fBdata\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< char > \fBbuffer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
