.TH "decode_table" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decode_table
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.ti -1c
.RI "int32_t \fBdecode_len\fP [16]"
.br
.ti -1c
.RI "uint32_t \fBdecode_pos\fP [16]"
.br
.ti -1c
.RI "uint32_t \fBquick_bits\fP"
.br
.ti -1c
.RI "uint8_t \fBquick_len\fP [1<< 10]"
.br
.ti -1c
.RI "uint16_t \fBquick_num\fP [1<< 10]"
.br
.ti -1c
.RI "uint16_t \fBdecode_num\fP [306]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
