.TH "derived_from_string_view< Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
derived_from_string_view< Char >
.SH SYNOPSIS
.br
.PP
.PP
Inherits fmt::basic_string_view< Char >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
