.TH "DevNullClientCli" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevNullClientCli
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static async Task< byte[]> \fBReceiveAsync\fP (ClientWebSocket ws, CancellationToken \fBtoken\fP)"
.br
.ti -1c
.RI "static async Task \fBReceiveMessagesAsync\fP (string url)"
.br
.ti -1c
.RI "static async Task \fBMain\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
