.TH "digestdata" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
digestdata
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBIT\fP (stale)"
.br
.ti -1c
.RI "\fBBIT\fP (userhash)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBnonce\fP"
.br
.ti -1c
.RI "char * \fBcnonce\fP"
.br
.ti -1c
.RI "char * \fBrealm\fP"
.br
.ti -1c
.RI "int \fBalgo\fP"
.br
.ti -1c
.RI "char * \fBopaque\fP"
.br
.ti -1c
.RI "char * \fBqop\fP"
.br
.ti -1c
.RI "char * \fBalgorithm\fP"
.br
.ti -1c
.RI "int \fBnc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
