.TH "digit_grouping< Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
digit_grouping< Char >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdigit_grouping\fP (\fBlocale_ref\fP loc, bool localized=true)"
.br
.ti -1c
.RI "\fBdigit_grouping\fP (std::string grouping, std::basic_string< Char > sep)"
.br
.ti -1c
.RI "bool \fBhas_separator\fP () const"
.br
.ti -1c
.RI "int \fBcount_separators\fP (int num_digits) const"
.br
.ti -1c
.RI "template<typename Out , typename C > Out \fBapply\fP (Out out, \fBbasic_string_view\fP< C > digits) const"
.br
.ti -1c
.RI "\fBdigit_grouping\fP (\fBlocale_ref\fP loc, bool localized=true)"
.br
.ti -1c
.RI "\fBdigit_grouping\fP (\fBthousands_sep_result\fP< Char > sep)"
.br
.ti -1c
.RI "Char \fBseparator\fP () const"
.br
.ti -1c
.RI "int \fBcount_separators\fP (int num_digits) const"
.br
.ti -1c
.RI "template<typename Out , typename C > Out \fBapply\fP (Out out, \fBbasic_string_view\fP< C > digits) const"
.br
.ti -1c
.RI "\fBdigit_grouping\fP (\fBlocale_ref\fP loc, bool localized=true)"
.br
.ti -1c
.RI "\fBdigit_grouping\fP (\fBthousands_sep_result\fP< Char > sep)"
.br
.ti -1c
.RI "Char \fBseparator\fP () const"
.br
.ti -1c
.RI "int \fBcount_separators\fP (int num_digits) const"
.br
.ti -1c
.RI "template<typename Out , typename C > Out \fBapply\fP (Out out, \fBbasic_string_view\fP< C > digits) const"
.br
.ti -1c
.RI "\fBdigit_grouping\fP (\fBlocale_ref\fP loc, bool localized=true)"
.br
.ti -1c
.RI "\fBdigit_grouping\fP (\fBthousands_sep_result\fP< Char > sep)"
.br
.ti -1c
.RI "Char \fBseparator\fP () const"
.br
.ti -1c
.RI "int \fBcount_separators\fP (int num_digits) const"
.br
.ti -1c
.RI "template<typename Out , typename C > Out \fBapply\fP (Out out, \fBbasic_string_view\fP< C > digits) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
