.TH "DistoStats" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DistoStats
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.ti -1c
.RI "uint32_t \fBxm\fP"
.br
.ti -1c
.RI "uint32_t \fBym\fP"
.br
.ti -1c
.RI "uint32_t \fBxxm\fP"
.br
.ti -1c
.RI "uint32_t \fBxym\fP"
.br
.ti -1c
.RI "uint32_t \fByym\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
