.TH "dlg_style" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlg_style
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum dlg_text_style \fBstyle\fP"
.br
.ti -1c
.RI "enum dlg_color \fBfg\fP"
.br
.ti -1c
.RI "enum dlg_color \fBbg\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
