.TH "dlg_origin" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlg_origin
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBfile\fP"
.br
.ti -1c
.RI "unsigned int \fBline\fP"
.br
.ti -1c
.RI "const char * \fBfunc\fP"
.br
.ti -1c
.RI "enum dlg_level \fBlevel\fP"
.br
.ti -1c
.RI "const char ** \fBtags\fP"
.br
.ti -1c
.RI "const char * \fBexpr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
