.TH "dnsprobe" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dnsprobe
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CURL * \fBeasy\fP"
.br
.ti -1c
.RI "int \fBdnstype\fP"
.br
.ti -1c
.RI "unsigned char \fBdohbuffer\fP [512]"
.br
.ti -1c
.RI "size_t \fBdohlen\fP"
.br
.ti -1c
.RI "struct \fBdynbuf\fP \fBserverdoh\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
