.TH "DogAdder" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DogAdder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDogAdder\fP (const char *a_value)"
.br
.ti -1c
.RI "\fBDogAdder\fP (const \fBDogAdder\fP &other)"
.br
.ti -1c
.RI "\fBDogAdder\fP \fBoperator=\fP (const \fBDogAdder\fP &other)"
.br
.ti -1c
.RI "\fBDogAdder\fP \fBoperator+\fP (const \fBDogAdder\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBDogAdder\fP &other) const"
.br
.ti -1c
.RI "const std::string & \fBvalue\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
