.TH "dohdata" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dohdata
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBheaders\fP"
.br
.ti -1c
.RI "struct \fBdnsprobe\fP \fBprobe\fP [DOH_PROBE_SLOTS]"
.br
.ti -1c
.RI "unsigned int \fBpending\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "const char * \fBhost\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
