.TH "DominantCostRange" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DominantCostRange
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBliteral_max_\fP"
.br
.ti -1c
.RI "double \fBliteral_min_\fP"
.br
.ti -1c
.RI "double \fBred_max_\fP"
.br
.ti -1c
.RI "double \fBred_min_\fP"
.br
.ti -1c
.RI "double \fBblue_max_\fP"
.br
.ti -1c
.RI "double \fBblue_min_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
