.TH "Dragon" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dragon
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "DRAGON_API void \fBTestFunc\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DRAGON_API void Dragon::TestFunc ()"

.PP
Definition at line \fB7\fP of file \fBtesting\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
