.TH "error_group" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
error_group \- Errors
.PP
 \- Errors thrown by CLI11\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCLI::Error\fP"
.br
.RI "All errors derive from this one\&. "
.ti -1c
.RI "class \fBCLI::ConstructionError\fP"
.br
.RI "Construction errors (not in parsing) "
.ti -1c
.RI "class \fBCLI::IncorrectConstruction\fP"
.br
.RI "Thrown when an option is set to conflicting values (non-vector and multi args, for example) "
.ti -1c
.RI "class \fBCLI::BadNameString\fP"
.br
.RI "Thrown on construction of a bad name\&. "
.ti -1c
.RI "class \fBCLI::OptionAlreadyAdded\fP"
.br
.RI "Thrown when an option already exists\&. "
.ti -1c
.RI "class \fBCLI::ParseError\fP"
.br
.RI "Anything that can error in Parse\&. "
.ti -1c
.RI "class \fBCLI::Success\fP"
.br
.RI "This is a successful completion on parsing, supposed to exit\&. "
.ti -1c
.RI "class \fBCLI::CallForHelp\fP"
.br
.RI "-h or --help on command line "
.ti -1c
.RI "class \fBCLI::CallForAllHelp\fP"
.br
.RI "Usually something like --help-all on command line\&. "
.ti -1c
.RI "class \fBCLI::CallForVersion\fP"
.br
.RI "-v or --version on command line "
.ti -1c
.RI "class \fBCLI::RuntimeError\fP"
.br
.RI "Does not output a diagnostic in CLI11_PARSE, but allows main() to return with a specific error code\&. "
.ti -1c
.RI "class \fBCLI::FileError\fP"
.br
.RI "Thrown when parsing an INI file and it is missing\&. "
.ti -1c
.RI "class \fBCLI::ConversionError\fP"
.br
.RI "Thrown when conversion call back fails, such as when an int fails to coerce to a string\&. "
.ti -1c
.RI "class \fBCLI::ValidationError\fP"
.br
.RI "Thrown when validation of results fails\&. "
.ti -1c
.RI "class \fBCLI::RequiredError\fP"
.br
.RI "Thrown when a required option is missing\&. "
.ti -1c
.RI "class \fBCLI::ArgumentMismatch\fP"
.br
.RI "Thrown when the wrong number of arguments has been received\&. "
.ti -1c
.RI "class \fBCLI::RequiresError\fP"
.br
.RI "Thrown when a requires option is missing\&. "
.ti -1c
.RI "class \fBCLI::ExcludesError\fP"
.br
.RI "Thrown when an excludes option is present\&. "
.ti -1c
.RI "class \fBCLI::ExtrasError\fP"
.br
.RI "Thrown when too many positionals or options are found\&. "
.ti -1c
.RI "class \fBCLI::ConfigError\fP"
.br
.RI "Thrown when extra values are found in an INI file\&. "
.ti -1c
.RI "class \fBCLI::InvalidError\fP"
.br
.RI "Thrown when validation fails before parsing\&. "
.ti -1c
.RI "class \fBCLI::HorribleError\fP"
.br
.ti -1c
.RI "class \fBCLI::OptionNotFound\fP"
.br
.RI "Thrown when counting a non-existent option\&. "
.in -1c
.SH "Detailed Description"
.PP 
Errors thrown by CLI11\&. 

These are the errors that can be thrown\&. Some of them, like \fBCLI::Success\fP, are not really errors\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
