.TH "expdesc" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
expdesc
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "expkind \fBk\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   lua_Integer \fBival\fP"
.br
.ti -1c
.RI "   lua_Number \fBnval\fP"
.br
.ti -1c
.RI "   \fBTString\fP * \fBstrval\fP"
.br
.ti -1c
.RI "   int \fBinfo\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      short \fBidx\fP"
.br
.ti -1c
.RI "      lu_byte \fBt\fP"
.br
.ti -1c
.RI "   } \fBind\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      lu_byte \fBridx\fP"
.br
.ti -1c
.RI "      unsigned short \fBvidx\fP"
.br
.ti -1c
.RI "   } \fBvar\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "int \fBt\fP"
.br
.ti -1c
.RI "int \fBf\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
