.TH "face_options_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
face_options_t
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBfont_options_t\fP, and \fBsubset_main_t\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcache_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_face\fP (\fBhb_face_t\fP *face_)"
.br
.ti -1c
.RI "void \fBadd_options\fP (\fBoption_parser_t\fP *parser)"
.br
.ti -1c
.RI "void \fBpost_parse\fP (GError **error)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBfont_file\fP = nullptr"
.br
.ti -1c
.RI "unsigned \fBface_index\fP = 0"
.br
.ti -1c
.RI "\fBhb_blob_t\fP * \fBblob\fP = nullptr"
.br
.ti -1c
.RI "\fBhb_face_t\fP * \fBface\fP = nullptr"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static struct face_options_t::cache_t \fBcache\fP {}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
