.TH "FailedTest" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FailedTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTest\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBTest\fP
.in +1c
.ti -1c
.RI "\fBTest\fP (const char *a_pszName)"
.br
.ti -1c
.RI "bool \fBSuccess\fP ()"
.br
.ti -1c
.RI "bool \fBFailure\fP (const char *pszReason)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
