.TH "fallback_digit_grouping< Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fallback_digit_grouping< Char >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBfallback_digit_grouping\fP (\fBlocale_ref\fP, bool)"
.br
.ti -1c
.RI "constexpr bool \fBhas_separator\fP () const"
.br
.ti -1c
.RI "constexpr int \fBcount_separators\fP (int) const"
.br
.ti -1c
.RI "template<typename Out , typename C > constexpr Out \fBapply\fP (Out out, \fBbasic_string_view\fP< C >) const"
.br
.ti -1c
.RI "constexpr \fBfallback_digit_grouping\fP (\fBlocale_ref\fP, bool)"
.br
.ti -1c
.RI "constexpr Char \fBseparator\fP () const"
.br
.ti -1c
.RI "constexpr int \fBcount_separators\fP (int) const"
.br
.ti -1c
.RI "template<typename Out , typename C > constexpr Out \fBapply\fP (Out out, \fBbasic_string_view\fP< C >) const"
.br
.ti -1c
.RI "constexpr \fBfallback_digit_grouping\fP (\fBlocale_ref\fP, bool)"
.br
.ti -1c
.RI "constexpr Char \fBseparator\fP () const"
.br
.ti -1c
.RI "constexpr int \fBcount_separators\fP (int) const"
.br
.ti -1c
.RI "template<typename Out , typename C > constexpr Out \fBapply\fP (Out out, \fBbasic_string_view\fP< C >) const"
.br
.ti -1c
.RI "constexpr \fBfallback_digit_grouping\fP (\fBlocale_ref\fP, bool)"
.br
.ti -1c
.RI "constexpr Char \fBseparator\fP () const"
.br
.ti -1c
.RI "constexpr int \fBcount_separators\fP (int) const"
.br
.ti -1c
.RI "template<typename Out , typename C > constexpr Out \fBapply\fP (Out out, \fBbasic_string_view\fP< C >) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
