.TH "fcurl_data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fcurl_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum fcurl_type_e \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   CURL * \fBcurl\fP"
.br
.ti -1c
.RI "   FILE * \fBfile\fP"
.br
.ti -1c
.RI "} \fBhandle\fP"
.br
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.ti -1c
.RI "size_t \fBbuffer_len\fP"
.br
.ti -1c
.RI "size_t \fBbuffer_pos\fP"
.br
.ti -1c
.RI "int \fBstill_running\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
