.TH "file_header" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_header
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ssize_t \fBbytes_remaining\fP"
.br
.ti -1c
.RI "ssize_t \fBunpacked_size\fP"
.br
.ti -1c
.RI "int64_t \fBlast_offset\fP"
.br
.ti -1c
.RI "int64_t \fBlast_size\fP"
.br
.ti -1c
.RI "uint8_t \fBsolid\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBservice\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBeof\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBdir\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBe_mtime\fP"
.br
.ti -1c
.RI "uint64_t \fBe_ctime\fP"
.br
.ti -1c
.RI "uint64_t \fBe_atime\fP"
.br
.ti -1c
.RI "uint32_t \fBe_unix_ns\fP"
.br
.ti -1c
.RI "uint32_t \fBstored_crc32\fP"
.br
.ti -1c
.RI "uint32_t \fBcalculated_crc32\fP"
.br
.ti -1c
.RI "uint8_t \fBblake2sp\fP [32]"
.br
.ti -1c
.RI "\fBblake2sp_state\fP \fBb2state\fP"
.br
.ti -1c
.RI "char \fBhas_blake2\fP"
.br
.ti -1c
.RI "uint64_t \fBredir_type\fP"
.br
.ti -1c
.RI "uint64_t \fBredir_flags\fP"
.br
.ti -1c
.RI "ssize_t \fBsolid_window_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
