.TH "file" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive_rb_node\fP \fBrbnode\fP"
.br
.ti -1c
.RI "struct \fBfile\fP * \fBnext\fP"
.br
.ti -1c
.RI "unsigned \fBname_len\fP"
.br
.ti -1c
.RI "uint8_t * \fButf16name\fP"
.br
.ti -1c
.RI "uint64_t \fBsize\fP"
.br
.ti -1c
.RI "unsigned \fBflg\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   time_t \fBtime\fP"
.br
.ti -1c
.RI "   long \fBtime_ns\fP"
.br
.ti -1c
.RI "} \fBtimes\fP [3]"
.br
.ti -1c
.RI "mode_t \fBmode\fP"
.br
.ti -1c
.RI "uint32_t \fBcrc32\fP"
.br
.ti -1c
.RI "signed int \fBdir\fP:1"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "unsigned \fBleft\fP"
.br
.ti -1c
.RI "unsigned char * \fBbuf\fP"
.br
.ti -1c
.RI "z_const unsigned char * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
