.TH "filesystem" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filesystem
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBdev\fP"
.br
.ti -1c
.RI "int \fBsynthetic\fP"
.br
.ti -1c
.RI "int \fBremote\fP"
.br
.ti -1c
.RI "int \fBnoatime\fP"
.br
.ti -1c
.RI "long \fBincr_xfer_size\fP"
.br
.ti -1c
.RI "long \fBmax_xfer_size\fP"
.br
.ti -1c
.RI "long \fBmin_xfer_size\fP"
.br
.ti -1c
.RI "long \fBxfer_align\fP"
.br
.ti -1c
.RI "unsigned char * \fBallocation_ptr\fP"
.br
.ti -1c
.RI "unsigned char * \fBbuff\fP"
.br
.ti -1c
.RI "size_t \fBbuff_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
