.TH "file_in_zip64_read_info_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_in_zip64_read_info_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBread_buffer\fP"
.br
.ti -1c
.RI "\fBz_stream\fP \fBstream\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBpos_in_zipfile\fP"
.br
.ti -1c
.RI "uLong \fBstream_initialised\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBoffset_local_extrafield\fP"
.br
.ti -1c
.RI "uInt \fBsize_local_extrafield\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBpos_local_extrafield\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBtotal_out_64\fP"
.br
.ti -1c
.RI "uLong \fBcrc32\fP"
.br
.ti -1c
.RI "uLong \fBcrc32_wait\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBrest_read_compressed\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBrest_read_uncompressed\fP"
.br
.ti -1c
.RI "\fBzlib_filefunc64_32_def\fP \fBz_filefunc\fP"
.br
.ti -1c
.RI "voidpf \fBfilestream\fP"
.br
.ti -1c
.RI "uLong \fBcompression_method\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBbyte_before_the_zipfile\fP"
.br
.ti -1c
.RI "int \fBraw\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
