.TH "file_info" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBfile_info\fP * \fBuse_next\fP"
.br
.ti -1c
.RI "struct \fBfile_info\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct \fBfile_info\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBfile_info\fP * \fBre_next\fP"
.br
.ti -1c
.RI "int \fBsubdirs\fP"
.br
.ti -1c
.RI "uint64_t \fBkey\fP"
.br
.ti -1c
.RI "uint64_t \fBoffset\fP"
.br
.ti -1c
.RI "uint64_t \fBsize\fP"
.br
.ti -1c
.RI "uint32_t \fBce_offset\fP"
.br
.ti -1c
.RI "uint32_t \fBce_size\fP"
.br
.ti -1c
.RI "char \fBrr_moved\fP"
.br
.ti -1c
.RI "char \fBrr_moved_has_re_only\fP"
.br
.ti -1c
.RI "char \fBre\fP"
.br
.ti -1c
.RI "char \fBre_descendant\fP"
.br
.ti -1c
.RI "uint64_t \fBcl_offset\fP"
.br
.ti -1c
.RI "int \fBbirthtime_is_set\fP"
.br
.ti -1c
.RI "time_t \fBbirthtime\fP"
.br
.ti -1c
.RI "time_t \fBmtime\fP"
.br
.ti -1c
.RI "time_t \fBatime\fP"
.br
.ti -1c
.RI "time_t \fBctime\fP"
.br
.ti -1c
.RI "uint64_t \fBrdev\fP"
.br
.ti -1c
.RI "mode_t \fBmode\fP"
.br
.ti -1c
.RI "uid_t \fBuid\fP"
.br
.ti -1c
.RI "gid_t \fBgid\fP"
.br
.ti -1c
.RI "int64_t \fBnumber\fP"
.br
.ti -1c
.RI "int \fBnlinks\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBname\fP"
.br
.ti -1c
.RI "unsigned char * \fButf16be_name\fP"
.br
.ti -1c
.RI "size_t \fButf16be_bytes\fP"
.br
.ti -1c
.RI "char \fBname_continues\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBsymlink\fP"
.br
.ti -1c
.RI "char \fBsymlink_continues\fP"
.br
.ti -1c
.RI "int \fBpz\fP"
.br
.ti -1c
.RI "int \fBpz_log2_bs\fP"
.br
.ti -1c
.RI "uint64_t \fBpz_uncompressed_size\fP"
.br
.ti -1c
.RI "int \fBmulti_extent\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBcontent\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBcontent\fP ** \fBlast\fP"
.br
.ti -1c
.RI "} \fBcontents\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBfile_info\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBfile_info\fP ** \fBlast\fP"
.br
.ti -1c
.RI "} \fBrede_files\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
