.TH "fileblocks" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fileblocks
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBfilesize\fP"
.br
.ti -1c
.RI "int64_t \fBfileposition\fP"
.br
.ti -1c
.RI "int64_t \fBgap_remaining\fP"
.br
.ti -1c
.RI "void * \fBbuff\fP"
.br
.ti -1c
.RI "struct \fBfileblock\fP * \fBfirst\fP"
.br
.ti -1c
.RI "struct \fBfileblock\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "struct \fBfileblock\fP * \fBlast\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
