.TH "filter_info_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filter_info_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pixman_kernel_t \fBkernel\fP"
.br
.ti -1c
.RI "kernel_func_t \fBfunc\fP"
.br
.ti -1c
.RI "double \fBwidth\fP"
.br
.ti -1c
.RI "pixman_filter_t \fBvalue\fP"
.br
.ti -1c
.RI "char \fBname\fP [28]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
