.TH "filter_info" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filter_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBchannels\fP"
.br
.ti -1c
.RI "int \fBpos_r\fP"
.br
.ti -1c
.RI "int64_t \fBblock_start\fP"
.br
.ti -1c
.RI "ssize_t \fBblock_length\fP"
.br
.ti -1c
.RI "uint16_t \fBwidth\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
