.TH "finalize_closure_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
finalize_closure_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBcallback\fP )(\fBfinalize_closure_t\fP *)"
.br
.ti -1c
.RI "cairo_surface_t * \fBsurface\fP"
.br
.ti -1c
.RI "cairo_write_func_t \fBwrite_func\fP"
.br
.ti -1c
.RI "void * \fBclosure\fP"
.br
.ti -1c
.RI "image_protocol_t \fBprotocol\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
