.TH "fixup_entry" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fixup_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBfixup_entry\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBarchive_acl\fP \fBacl\fP"
.br
.ti -1c
.RI "mode_t \fBmode\fP"
.br
.ti -1c
.RI "__LA_MODE_T \fBfiletype\fP"
.br
.ti -1c
.RI "int64_t \fBatime\fP"
.br
.ti -1c
.RI "int64_t \fBbirthtime\fP"
.br
.ti -1c
.RI "int64_t \fBmtime\fP"
.br
.ti -1c
.RI "int64_t \fBctime\fP"
.br
.ti -1c
.RI "unsigned long \fBatime_nanos\fP"
.br
.ti -1c
.RI "unsigned long \fBbirthtime_nanos\fP"
.br
.ti -1c
.RI "unsigned long \fBmtime_nanos\fP"
.br
.ti -1c
.RI "unsigned long \fBctime_nanos\fP"
.br
.ti -1c
.RI "unsigned long \fBfflags_set\fP"
.br
.ti -1c
.RI "size_t \fBmac_metadata_size\fP"
.br
.ti -1c
.RI "void * \fBmac_metadata\fP"
.br
.ti -1c
.RI "int \fBfixup\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
