.TH "FloatingWindow" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FloatingWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCustomWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrecreate\fP (\fBos::Window\fP *parent)"
.br
.ti -1c
.RI "bool \fBisFloating\fP () const override"
.br
.in -1c

Public Member Functions inherited from \fBCustomWindow\fP
.in +1c
.ti -1c
.RI "void \fBcreate\fP (const std::string &title, int w, int h, \fBos::Window\fP *parent=nullptr)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "void \fBfocus\fP ()"
.br
.ti -1c
.RI "bool \fBisVisible\fP () const"
.br
.ti -1c
.RI "void \fBredraw\fP ()"
.br
.ti -1c
.RI "virtual bool \fBisFloating\fP () const"
.br
.ti -1c
.RI "virtual bool \fBhandleEvent\fP (\fBos::Event\fP &ev)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBCustomWindow\fP
.in +1c
.ti -1c
.RI "virtual void \fBonRedraw\fP (\fBos::Surface\fP *surface, const \fBgfx::Rect\fP &rc)"
.br
.ti -1c
.RI "virtual void \fBonEnterKey\fP ()"
.br
.ti -1c
.RI "os::WindowRef \fBnativeWindow\fP () const"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool FloatingWindow::isFloating () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBCustomWindow\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
