.TH "float_specs" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
float_specs
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBprecision\fP"
.br
.ti -1c
.RI "float_format \fBformat\fP: 8"
.br
.ti -1c
.RI "sign_t \fBsign\fP: 8"
.br
.ti -1c
.RI "bool \fBupper\fP: 1"
.br
.ti -1c
.RI "bool \fBlocale\fP: 1"
.br
.ti -1c
.RI "bool \fBbinary32\fP: 1"
.br
.ti -1c
.RI "bool \fBshowpoint\fP: 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
