.TH "fmt_ref_view< R >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fmt_ref_view< R >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBbegin\fP () const \-> decltype(r\->begin())"
.br
.ti -1c
.RI "auto \fBend\fP () const \-> decltype(r\->end())"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "R * \fBr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
