.TH "fns" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fns
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBmaxlen\fP"
.br
.ti -1c
.RI "size_t \fBlongest_len\fP"
.br
.ti -1c
.RI "size_t \fBmaxflen\fP"
.br
.ti -1c
.RI "size_t \fBmaxelen\fP"
.br
.ti -1c
.RI "size_t \fBalloc\fP"
.br
.ti -1c
.RI "int \fBcnt\fP"
.br
.ti -1c
.RI "char ** \fBnames\fP"
.br
.ti -1c
.RI "int \fBopt\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
