.TH "font_options_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
font_options_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBface_options_t\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_options\fP (\fBoption_parser_t\fP *parser)"
.br
.ti -1c
.RI "void \fBpost_parse\fP (GError **error)"
.br
.in -1c

Public Member Functions inherited from \fBface_options_t\fP
.in +1c
.ti -1c
.RI "void \fBset_face\fP (\fBhb_face_t\fP *face_)"
.br
.ti -1c
.RI "void \fBadd_options\fP (\fBoption_parser_t\fP *parser)"
.br
.ti -1c
.RI "void \fBpost_parse\fP (GError **error)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_bool_t \fBsub_font\fP = false"
.br
.ti -1c
.RI "\fBhb_variation_t\fP * \fBvariations\fP = nullptr"
.br
.ti -1c
.RI "unsigned int \fBnum_variations\fP = 0"
.br
.ti -1c
.RI "int \fBx_ppem\fP = 0"
.br
.ti -1c
.RI "int \fBy_ppem\fP = 0"
.br
.ti -1c
.RI "double \fBptem\fP = 0\&."
.br
.ti -1c
.RI "double \fBslant\fP = 0\&."
.br
.ti -1c
.RI "unsigned int \fBsubpixel_bits\fP = SUBPIXEL_BITS"
.br
.ti -1c
.RI "double \fBfont_size_x\fP = DEFAULT_FONT_SIZE"
.br
.ti -1c
.RI "double \fBfont_size_y\fP = DEFAULT_FONT_SIZE"
.br
.ti -1c
.RI "char * \fBfont_funcs\fP = nullptr"
.br
.ti -1c
.RI "int \fBft_load_flags\fP = 2"
.br
.ti -1c
.RI "\fBhb_font_t\fP * \fBfont\fP = nullptr"
.br
.in -1c

Public Attributes inherited from \fBface_options_t\fP
.in +1c
.ti -1c
.RI "char * \fBfont_file\fP = nullptr"
.br
.ti -1c
.RI "unsigned \fBface_index\fP = 0"
.br
.ti -1c
.RI "\fBhb_blob_t\fP * \fBblob\fP = nullptr"
.br
.ti -1c
.RI "\fBhb_face_t\fP * \fBface\fP = nullptr"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBface_options_t\fP
.in +1c
.ti -1c
.RI "static struct face_options_t::cache_t \fBcache\fP {}"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
