.TH "FormInfo" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "size_t \fBnamelength\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.ti -1c
.RI "curl_off_t \fBcontentslength\fP"
.br
.ti -1c
.RI "char * \fBcontenttype\fP"
.br
.ti -1c
.RI "long \fBflags\fP"
.br
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.ti -1c
.RI "size_t \fBbufferlength\fP"
.br
.ti -1c
.RI "char * \fBshowfilename\fP"
.br
.ti -1c
.RI "char * \fBuserp\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBcontentheader\fP"
.br
.ti -1c
.RI "struct \fBFormInfo\fP * \fBmore\fP"
.br
.ti -1c
.RI "bool \fBname_alloc\fP"
.br
.ti -1c
.RI "bool \fBvalue_alloc\fP"
.br
.ti -1c
.RI "bool \fBcontenttype_alloc\fP"
.br
.ti -1c
.RI "bool \fBshowfilename_alloc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
