.TH "format_error" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
format_error
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <format\&.h>\fP
.PP
Inherits std::runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformat_error\fP (const char *message)"
.br
.ti -1c
.RI "\fBformat_error\fP (const std::string &message)"
.br
.ti -1c
.RI "\fBformat_error\fP (const \fBformat_error\fP &)=default"
.br
.ti -1c
.RI "\fBformat_error\fP & \fBoperator=\fP (const \fBformat_error\fP &)=default"
.br
.ti -1c
.RI "\fBformat_error\fP (\fBformat_error\fP &&)=default"
.br
.ti -1c
.RI "\fBformat_error\fP & \fBoperator=\fP (\fBformat_error\fP &&)=default"
.br
.ti -1c
.RI "\fBformat_error\fP (const char *message)"
.br
.ti -1c
.RI "\fBformat_error\fP (const std::string &message)"
.br
.ti -1c
.RI "\fBformat_error\fP (const \fBformat_error\fP &)=default"
.br
.ti -1c
.RI "\fBformat_error\fP & \fBoperator=\fP (const \fBformat_error\fP &)=default"
.br
.ti -1c
.RI "\fBformat_error\fP (\fBformat_error\fP &&)=default"
.br
.ti -1c
.RI "\fBformat_error\fP & \fBoperator=\fP (\fBformat_error\fP &&)=default"
.br
.ti -1c
.RI "\fBformat_error\fP (const char *message)"
.br
.ti -1c
.RI "\fBformat_error\fP (const std::string &message)"
.br
.ti -1c
.RI "\fBformat_error\fP (const \fBformat_error\fP &)=default"
.br
.ti -1c
.RI "\fBformat_error\fP & \fBoperator=\fP (const \fBformat_error\fP &)=default"
.br
.ti -1c
.RI "\fBformat_error\fP (\fBformat_error\fP &&)=default"
.br
.ti -1c
.RI "\fBformat_error\fP & \fBoperator=\fP (\fBformat_error\fP &&)=default"
.br
.ti -1c
.RI "\fBformat_error\fP (const char *message)"
.br
.ti -1c
.RI "\fBformat_error\fP (const std::string &message)"
.br
.ti -1c
.RI "\fBformat_error\fP (const \fBformat_error\fP &)=default"
.br
.ti -1c
.RI "\fBformat_error\fP & \fBoperator=\fP (const \fBformat_error\fP &)=default"
.br
.ti -1c
.RI "\fBformat_error\fP (\fBformat_error\fP &&)=default"
.br
.ti -1c
.RI "\fBformat_error\fP & \fBoperator=\fP (\fBformat_error\fP &&)=default"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP formatting error such as invalid format string\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
