.TH "formatter< weekday, Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatter< weekday, Char >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR auto \fBparse\fP (\fBbasic_format_parse_context\fP< Char > &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (\fBweekday\fP wd, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBparse\fP (\fBbasic_format_parse_context\fP< Char > &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (\fBweekday\fP wd, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBparse\fP (\fBbasic_format_parse_context\fP< Char > &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (\fBweekday\fP wd, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBparse\fP (\fBbasic_format_parse_context\fP< Char > &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (\fBweekday\fP wd, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
