.TH "format_string_checker< Char, ErrorHandler, Args >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
format_string_checker< Char, ErrorHandler, Args >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBformat_string_checker\fP (\fBbasic_string_view\fP< Char > format_str, ErrorHandler eh)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_text\fP (const Char *, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_arg_id\fP () \-> int"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_arg_id\fP (int id) \-> int"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_arg_id\fP (\fBbasic_string_view\fP< Char > id) \-> int"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_replacement_field\fP (int, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_format_specs\fP (int id, const Char *begin, const Char *) \-> const Char *"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_error\fP (const char *message)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBformat_string_checker\fP (\fBbasic_string_view\fP< Char > format_str, ErrorHandler eh)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_text\fP (const Char *, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_arg_id\fP () \-> int"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_arg_id\fP (int id) \-> int"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_arg_id\fP (\fBbasic_string_view\fP< Char > id) \-> int"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_replacement_field\fP (int, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_format_specs\fP (int id, const Char *begin, const Char *) \-> const Char *"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_error\fP (const char *message)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBformat_string_checker\fP (\fBbasic_string_view\fP< Char > format_str, ErrorHandler eh)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_text\fP (const Char *, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_arg_id\fP () \-> int"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_arg_id\fP (int id) \-> int"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_arg_id\fP (\fBbasic_string_view\fP< Char > id) \-> int"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_replacement_field\fP (int, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_format_specs\fP (int id, const Char *begin, const Char *) \-> const Char *"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_error\fP (const char *message)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBformat_string_checker\fP (\fBbasic_string_view\fP< Char > format_str, ErrorHandler eh)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_text\fP (const Char *, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_arg_id\fP () \-> int"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_arg_id\fP (int id) \-> int"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_arg_id\fP (\fBbasic_string_view\fP< Char > id) \-> int"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_replacement_field\fP (int, const Char *)"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBon_format_specs\fP (int id, const Char *begin, const Char *) \-> const Char *"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_error\fP (const char *message)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
