.TH "formatter< std::complex< double >, charT >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatter< std::complex< double >, charT >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBbasic_format_parse_context\fP< charT >::iterator \fBparse\fP (\fBbasic_format_parse_context\fP< charT > &ctx)"
.br
.ti -1c
.RI "template<class FormatContext > FormatContext::iterator \fBformat\fP (const std::complex< double > &c, FormatContext &ctx)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
