.TH "formatter< std::thread::id, Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatter< std::thread::id, Char >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbasic_ostream_formatter< Char >\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBbasic_ostream_formatter< Char >\fP
.in +1c
.ti -1c
.RI "void \fBset_debug_format\fP ()=delete"
.br
.ti -1c
.RI "template<typename T , typename OutputIt > auto \fBformat\fP (const T &\fBvalue\fP, \fBbasic_format_context\fP< OutputIt, Char > &ctx) const \-> OutputIt"
.br
.ti -1c
.RI "void \fBset_debug_format\fP ()=delete"
.br
.ti -1c
.RI "template<typename T , typename OutputIt > auto \fBformat\fP (const T &\fBvalue\fP, \fBbasic_format_context\fP< OutputIt, Char > &ctx) const \-> OutputIt"
.br
.ti -1c
.RI "void \fBset_debug_format\fP ()=delete"
.br
.ti -1c
.RI "template<typename T , typename OutputIt > auto \fBformat\fP (const T &\fBvalue\fP, \fBbasic_format_context\fP< OutputIt, Char > &ctx) const \-> OutputIt"
.br
.ti -1c
.RI "void \fBset_debug_format\fP ()=delete"
.br
.ti -1c
.RI "template<typename T , typename OutputIt > auto \fBformat\fP (const T &\fBvalue\fP, \fBbasic_format_context\fP< OutputIt, Char > &ctx) const \-> OutputIt"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
