.TH "format_facet< Locale >::int_formatter" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
format_facet< Locale >::int_formatter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(fmt::detail::is_integer< T >\fB::value\fP) > auto \fBoperator()\fP (T \fBvalue\fP) \-> bool"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(!fmt::detail::is_integer< T >\fB::value\fP) > auto \fBoperator()\fP (T) \-> bool"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "fmt::appender \fBout\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
