.TH "formatter< bytes >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatter< bytes >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (\fBbytes\fP b, FormatContext &ctx) \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (\fBbytes\fP b, FormatContext &ctx) \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (\fBbytes\fP b, FormatContext &ctx) \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (\fBbytes\fP b, FormatContext &ctx) \-> decltype(ctx\&.out())"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
