.TH "formatter< detail::bigint >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatter< detail::bigint >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR auto \fBparse\fP (\fBformat_parse_context\fP &ctx) \-> format_parse_context::iterator"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (const detail::bigint &n, FormatContext &ctx) const \-> typename FormatContext::iterator"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBparse\fP (\fBformat_parse_context\fP &ctx) \-> format_parse_context::iterator"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (const detail::bigint &n, FormatContext &ctx) const \-> typename FormatContext::iterator"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBparse\fP (\fBformat_parse_context\fP &ctx) \-> format_parse_context::iterator"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (const detail::bigint &n, FormatContext &ctx) const \-> typename FormatContext::iterator"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBparse\fP (\fBformat_parse_context\fP &ctx) \-> format_parse_context::iterator"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (const detail::bigint &n, FormatContext &ctx) const \-> typename FormatContext::iterator"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
