.TH "format_int" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
format_int
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <format\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformat_int\fP (int \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (long \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (long long \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (unsigned \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (unsigned long \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (unsigned long long \fBvalue\fP)"
.br
.ti -1c
.RI "auto \fBsize\fP () const \-> size_t"
.br
.ti -1c
.RI "auto \fBdata\fP () const \-> const char *"
.br
.ti -1c
.RI "auto \fBc_str\fP () const \-> const char *"
.br
.ti -1c
.RI "auto \fBstr\fP () const \-> std::string"
.br
.ti -1c
.RI "\fBformat_int\fP (int \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (long \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (long long \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (unsigned \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (unsigned long \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (unsigned long long \fBvalue\fP)"
.br
.ti -1c
.RI "auto \fBsize\fP () const \-> size_t"
.br
.ti -1c
.RI "auto \fBdata\fP () const \-> const char *"
.br
.ti -1c
.RI "auto \fBc_str\fP () const \-> const char *"
.br
.ti -1c
.RI "auto \fBstr\fP () const \-> std::string"
.br
.ti -1c
.RI "\fBformat_int\fP (int \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (long \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (long long \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (unsigned \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (unsigned long \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (unsigned long long \fBvalue\fP)"
.br
.ti -1c
.RI "auto \fBsize\fP () const \-> size_t"
.br
.ti -1c
.RI "auto \fBdata\fP () const \-> const char *"
.br
.ti -1c
.RI "auto \fBc_str\fP () const \-> const char *"
.br
.ti -1c
.RI "auto \fBstr\fP () const \-> std::string"
.br
.ti -1c
.RI "\fBformat_int\fP (int \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (long \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (long long \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (unsigned \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (unsigned long \fBvalue\fP)"
.br
.ti -1c
.RI "\fBformat_int\fP (unsigned long long \fBvalue\fP)"
.br
.ti -1c
.RI "auto \fBsize\fP () const \-> size_t"
.br
.ti -1c
.RI "auto \fBdata\fP () const \-> const char *"
.br
.ti -1c
.RI "auto \fBc_str\fP () const \-> const char *"
.br
.ti -1c
.RI "auto \fBstr\fP () const \-> std::string"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fast integer formatter\&. 
.SH "Member Function Documentation"
.PP 
.SS "auto format_int::c_str () const \-> const char* \fC [inline]\fP"
Returns a pointer to the output buffer content with terminating null character appended\&. 
.SS "auto format_int::c_str () const \-> const char* \fC [inline]\fP"
Returns a pointer to the output buffer content with terminating null character appended\&. 
.SS "auto format_int::c_str () const \-> const char* \fC [inline]\fP"
Returns a pointer to the output buffer content with terminating null character appended\&. 
.SS "auto format_int::c_str () const \-> const char* \fC [inline]\fP"
Returns a pointer to the output buffer content with terminating null character appended\&. 
.SS "auto format_int::data () const \-> const char* \fC [inline]\fP"
Returns a pointer to the output buffer content\&. No terminating null character is appended\&. 
.SS "auto format_int::data () const \-> const char* \fC [inline]\fP"
Returns a pointer to the output buffer content\&. No terminating null character is appended\&. 
.SS "auto format_int::data () const \-> const char* \fC [inline]\fP"
Returns a pointer to the output buffer content\&. No terminating null character is appended\&. 
.SS "auto format_int::data () const \-> const char* \fC [inline]\fP"
Returns a pointer to the output buffer content\&. No terminating null character is appended\&. 
.SS "auto format_int::size () const \-> size_t \fC [inline]\fP"
Returns the number of characters written to the output buffer\&. 
.SS "auto format_int::size () const \-> size_t \fC [inline]\fP"
Returns the number of characters written to the output buffer\&. 
.SS "auto format_int::size () const \-> size_t \fC [inline]\fP"
Returns the number of characters written to the output buffer\&. 
.SS "auto format_int::size () const \-> size_t \fC [inline]\fP"
Returns the number of characters written to the output buffer\&. 
.SS "auto format_int::str () const \-> std::string \fC [inline]\fP"
\\rst Returns the content of the output buffer as an \fCstd::string\fP\&. \\endrst 
.SS "auto format_int::str () const \-> std::string \fC [inline]\fP"
\\rst Returns the content of the output buffer as an \fCstd::string\fP\&. \\endrst 
.SS "auto format_int::str () const \-> std::string \fC [inline]\fP"
\\rst Returns the content of the output buffer as an \fCstd::string\fP\&. \\endrst 
.SS "auto format_int::str () const \-> std::string \fC [inline]\fP"
\\rst Returns the content of the output buffer as an \fCstd::string\fP\&. \\endrst 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
