.TH "formatter< TupleT, Char, enable_if_t< fmt::is_tuple_like< TupleT >::value &&fmt::is_tuple_formattable< TupleT, Char >::value > >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatter< TupleT, Char, enable_if_t< fmt::is_tuple_like< TupleT >::value &&fmt::is_tuple_formattable< TupleT, Char >::value > >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_separator\fP (\fBbasic_string_view\fP< Char > sep)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_brackets\fP (\fBbasic_string_view\fP< Char > open, \fBbasic_string_view\fP< Char > close)"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext  = format_context> auto \fBformat\fP (const TupleT &values, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_separator\fP (\fBbasic_string_view\fP< Char > sep)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_brackets\fP (\fBbasic_string_view\fP< Char > open, \fBbasic_string_view\fP< Char > close)"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext  = format_context> auto \fBformat\fP (const TupleT &values, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_separator\fP (\fBbasic_string_view\fP< Char > sep)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_brackets\fP (\fBbasic_string_view\fP< Char > open, \fBbasic_string_view\fP< Char > close)"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext  = format_context> auto \fBformat\fP (const TupleT &values, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_separator\fP (\fBbasic_string_view\fP< Char > sep)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_brackets\fP (\fBbasic_string_view\fP< Char > open, \fBbasic_string_view\fP< Char > close)"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext  = format_context> auto \fBformat\fP (const TupleT &values, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
