.TH "format_facet< Locale >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
format_facet< Locale >
.SH SYNOPSIS
.br
.PP
.PP
Inherits Locale::facet, and fmt::format_facet< std::locale >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBint_formatter\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformat_facet\fP (Locale &loc)"
.br
.ti -1c
.RI "\fBformat_facet\fP (\fBstring_view\fP sep='', std::initializer_list< unsigned char > g={3}, std::string decimal_point='\&.')"
.br
.ti -1c
.RI "auto \fBput\fP (\fBappender\fP out, \fBloc_value\fP val, const \fBformat_specs\fP &specs) const \-> bool"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static FMT_API Locale::id \fBid\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual auto \fBdo_put\fP (\fBappender\fP out, \fBloc_value\fP val, const \fBformat_specs\fP &specs) const \-> bool"
.br
.ti -1c
.RI "auto \fBdo_put\fP (fmt::appender out, fmt::loc_value val, const fmt::format_specs &) const \-> bool override"
.br
.ti -1c
.RI "FMT_API FMT_FUNC auto \fBdo_put\fP (\fBappender\fP out, \fBloc_value\fP val, const \fBformat_specs\fP &specs) const \-> bool"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
