.TH "formatter< test_struct, Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatter< test_struct, Char >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBparse\fP (\fBformat_parse_context\fP &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "auto \fBformat\fP (\fBtest_struct\fP, \fBformat_context\fP &ctx) \-> decltype(ctx\&.out())"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
