.TH "format_info_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
format_info_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pixman_format_code_t \fBformat\fP"
.br
.ti -1c
.RI "fetch_scanline_t \fBfetch_scanline_32\fP"
.br
.ti -1c
.RI "fetch_scanline_t \fBfetch_scanline_float\fP"
.br
.ti -1c
.RI "fetch_pixel_32_t \fBfetch_pixel_32\fP"
.br
.ti -1c
.RI "fetch_pixel_float_t \fBfetch_pixel_float\fP"
.br
.ti -1c
.RI "store_scanline_t \fBstore_scanline_32\fP"
.br
.ti -1c
.RI "store_scanline_t \fBstore_scanline_float\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
