.TH "formatter< variant >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatter< variant >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdynamic_formatter< Char >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBformat\fP (\fBvariant\fP \fBvalue\fP, \fBformat_context\fP &ctx) \-> decltype(ctx\&.out())"
.br
.in -1c

Public Member Functions inherited from \fBdynamic_formatter< Char >\fP
.in +1c
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename T , typename FormatContext > auto \fBformat\fP (const T &val, FormatContext &ctx) \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename T , typename FormatContext > auto \fBformat\fP (const T &val, FormatContext &ctx) \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename T , typename FormatContext > auto \fBformat\fP (const T &val, FormatContext &ctx) \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename T , typename FormatContext > auto \fBformat\fP (const T &val, FormatContext &ctx) \-> decltype(ctx\&.out())"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
