.TH "formatter< std::chrono::time_point< std::chrono::system_clock, Duration >, Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatter< std::chrono::time_point< std::chrono::system_clock, Duration >, Char >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBformatter< std::tm, Char >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (std::chrono::time_point< std::chrono::system_clock > val, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (std::chrono::time_point< std::chrono::system_clock > val, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (std::chrono::time_point< std::chrono::system_clock > val, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (std::chrono::time_point< std::chrono::system_clock > val, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.in -1c

Public Member Functions inherited from \fBformatter< std::tm, Char >\fP
.in +1c
.ti -1c
.RI "FMT_CONSTEXPR auto \fBparse\fP (\fBbasic_format_parse_context\fP< Char > &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (const std::tm &tm, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBparse\fP (\fBbasic_format_parse_context\fP< Char > &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (const std::tm &tm, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBparse\fP (\fBbasic_format_parse_context\fP< Char > &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (const std::tm &tm, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBparse\fP (\fBbasic_format_parse_context\fP< Char > &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (const std::tm &tm, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBformatter< std::tm, Char >\fP
.in +1c
.ti -1c
.RI "template<typename It > FMT_CONSTEXPR auto \fBdo_parse\fP (It begin, It end) \-> It"
.br
.ti -1c
.RI "template<typename It > FMT_CONSTEXPR auto \fBdo_parse\fP (It begin, It end) \-> It"
.br
.ti -1c
.RI "template<typename It > FMT_CONSTEXPR auto \fBdo_parse\fP (It begin, It end) \-> It"
.br
.ti -1c
.RI "template<typename It > FMT_CONSTEXPR auto \fBdo_parse\fP (It begin, It end) \-> It"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
