.TH "format_arg_store< Context, Args >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
format_arg_store< Context, Args >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. T> FMT_CONSTEXPR FMT_INLINE \fBformat_arg_store\fP (T &&\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> FMT_CONSTEXPR FMT_INLINE \fBformat_arg_store\fP (T &&\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> FMT_CONSTEXPR FMT_INLINE \fBformat_arg_store\fP (T &&\&.\&.\&. args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. T> FMT_CONSTEXPR FMT_INLINE \fBformat_arg_store\fP (T &&\&.\&.\&. args)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBbasic_format_args< Context >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename \fBContext\fP, typename\&.\&.\&. Args>
.br
class format_arg_store< Context, Args >"\\rst An array of references to arguments\&. It can be implicitly converted into \fC~fmt\fBbasic_format_args\fP\fP for passing into type-erased formatting functions such as \fC~fmtvformat\fP\&. \\endrst 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
