.TH "formatter< convertible_to_pointer_formattable >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatter< convertible_to_pointer_formattable >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBparse\fP (\fBformat_parse_context\fP &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "auto \fBformat\fP (\fBconvertible_to_pointer_formattable\fP, \fBformat_context\fP &ctx) const \-> decltype(ctx\&.out())"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
