.TH "formatter< void *, Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
formatter< void *, Char >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBformatter< const void *, Char >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (void *val, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (void *val, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (void *val, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "template<typename FormatContext > auto \fBformat\fP (void *val, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
