.TH "FrameRectangle" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FrameRectangle
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx_offset_\fP"
.br
.ti -1c
.RI "int \fBy_offset_\fP"
.br
.ti -1c
.RI "int \fBwidth_\fP"
.br
.ti -1c
.RI "int \fBheight_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
