.TH "Frame" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Frame
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx_offset_\fP"
.br
.ti -1c
.RI "int \fBy_offset_\fP"
.br
.ti -1c
.RI "int \fBwidth_\fP"
.br
.ti -1c
.RI "int \fBheight_\fP"
.br
.ti -1c
.RI "int \fBhas_alpha_\fP"
.br
.ti -1c
.RI "int \fBduration_\fP"
.br
.ti -1c
.RI "WebPMuxAnimDispose \fBdispose_method_\fP"
.br
.ti -1c
.RI "WebPMuxAnimBlend \fBblend_method_\fP"
.br
.ti -1c
.RI "int \fBframe_num_\fP"
.br
.ti -1c
.RI "int \fBcomplete_\fP"
.br
.ti -1c
.RI "\fBChunkData\fP \fBimg_components_\fP [2]"
.br
.ti -1c
.RI "struct \fBFrame\fP * \fBnext_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
