.TH "FT_AutoHinter_InterfaceRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_AutoHinter_InterfaceRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_AutoHinter_GlobalResetFunc \fBreset_face\fP"
.br
.ti -1c
.RI "FT_AutoHinter_GlobalGetFunc \fBget_global_hints\fP"
.br
.ti -1c
.RI "FT_AutoHinter_GlobalDoneFunc \fBdone_global_hints\fP"
.br
.ti -1c
.RI "FT_AutoHinter_GlyphLoadFunc \fBload_glyph\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
