.TH "FT_COLR_Paint_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_COLR_Paint_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_PaintFormat \fBformat\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBFT_PaintColrLayers\fP \fBcolr_layers\fP"
.br
.ti -1c
.RI "   \fBFT_PaintGlyph\fP \fBglyph\fP"
.br
.ti -1c
.RI "   \fBFT_PaintSolid\fP \fBsolid\fP"
.br
.ti -1c
.RI "   \fBFT_PaintLinearGradient\fP \fBlinear_gradient\fP"
.br
.ti -1c
.RI "   \fBFT_PaintRadialGradient\fP \fBradial_gradient\fP"
.br
.ti -1c
.RI "   \fBFT_PaintSweepGradient\fP \fBsweep_gradient\fP"
.br
.ti -1c
.RI "   \fBFT_PaintTransform\fP \fBtransform\fP"
.br
.ti -1c
.RI "   \fBFT_PaintTranslate\fP \fBtranslate\fP"
.br
.ti -1c
.RI "   \fBFT_PaintScale\fP \fBscale\fP"
.br
.ti -1c
.RI "   \fBFT_PaintRotate\fP \fBrotate\fP"
.br
.ti -1c
.RI "   \fBFT_PaintSkew\fP \fBskew\fP"
.br
.ti -1c
.RI "   \fBFT_PaintComposite\fP \fBcomposite\fP"
.br
.ti -1c
.RI "   \fBFT_PaintColrGlyph\fP \fBcolr_glyph\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
