.TH "FT_Face_InternalRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_Face_InternalRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Matrix\fP \fBtransform_matrix\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBtransform_delta\fP"
.br
.ti -1c
.RI "FT_Int \fBtransform_flags\fP"
.br
.ti -1c
.RI "\fBFT_ServiceCacheRec\fP \fBservices\fP"
.br
.ti -1c
.RI "FT_Char \fBno_stem_darkening\fP"
.br
.ti -1c
.RI "FT_Int32 \fBrandom_seed\fP"
.br
.ti -1c
.RI "FT_Int \fBrefcount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
