.TH "FT_GlyphLoaderRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_GlyphLoaderRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_points\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_contours\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_subglyphs\fP"
.br
.ti -1c
.RI "FT_Bool \fBuse_extra\fP"
.br
.ti -1c
.RI "\fBFT_GlyphLoadRec\fP \fBbase\fP"
.br
.ti -1c
.RI "\fBFT_GlyphLoadRec\fP \fBcurrent\fP"
.br
.ti -1c
.RI "void * \fBother\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
