.TH "FT_GlyphRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_GlyphRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_Library\fP \fBlibrary\fP"
.br
.ti -1c
.RI "const FT_Glyph_Class * \fBclazz\fP"
.br
.ti -1c
.RI "FT_Glyph_Format \fBformat\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBadvance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
