.TH "FT_PaintRadialGradient_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_PaintRadialGradient_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_ColorLine\fP \fBcolorline\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBc0\fP"
.br
.ti -1c
.RI "FT_Pos \fBr0\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBc1\fP"
.br
.ti -1c
.RI "FT_Pos \fBr1\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
