.TH "FT_PaintScale_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_PaintScale_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_OpaquePaint\fP \fBpaint\fP"
.br
.ti -1c
.RI "FT_Fixed \fBscale_x\fP"
.br
.ti -1c
.RI "FT_Fixed \fBscale_y\fP"
.br
.ti -1c
.RI "FT_Fixed \fBcenter_x\fP"
.br
.ti -1c
.RI "FT_Fixed \fBcenter_y\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
