.TH "FT_SvgGlyphRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_SvgGlyphRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_GlyphRec\fP \fBroot\fP"
.br
.ti -1c
.RI "FT_Byte * \fBsvg_document\fP"
.br
.ti -1c
.RI "FT_ULong \fBsvg_document_length\fP"
.br
.ti -1c
.RI "FT_UInt \fBglyph_index\fP"
.br
.ti -1c
.RI "\fBFT_Size_Metrics\fP \fBmetrics\fP"
.br
.ti -1c
.RI "FT_UShort \fBunits_per_EM\fP"
.br
.ti -1c
.RI "FT_UShort \fBstart_glyph_id\fP"
.br
.ti -1c
.RI "FT_UShort \fBend_glyph_id\fP"
.br
.ti -1c
.RI "\fBFT_Matrix\fP \fBtransform\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBdelta\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
