.TH "FT_SubGlyphRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FT_SubGlyphRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Int \fBindex\fP"
.br
.ti -1c
.RI "FT_UShort \fBflags\fP"
.br
.ti -1c
.RI "FT_Int \fBarg1\fP"
.br
.ti -1c
.RI "FT_Int \fBarg2\fP"
.br
.ti -1c
.RI "\fBFT_Matrix\fP \fBtransform\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
