.TH "FTC_MruListClassRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTC_MruListClassRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Offset \fBnode_size\fP"
.br
.ti -1c
.RI "FTC_MruNode_CompareFunc \fBnode_compare\fP"
.br
.ti -1c
.RI "FTC_MruNode_InitFunc \fBnode_init\fP"
.br
.ti -1c
.RI "FTC_MruNode_ResetFunc \fBnode_reset\fP"
.br
.ti -1c
.RI "FTC_MruNode_DoneFunc \fBnode_done\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
