.TH "ftp_conn" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ftp_conn
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBpingpong\fP \fBpp\fP"
.br
.ti -1c
.RI "char * \fBentrypath\fP"
.br
.ti -1c
.RI "char * \fBfile\fP"
.br
.ti -1c
.RI "char ** \fBdirs\fP"
.br
.ti -1c
.RI "int \fBdirdepth\fP"
.br
.ti -1c
.RI "bool \fBdont_check\fP"
.br
.ti -1c
.RI "bool \fBctl_valid\fP"
.br
.ti -1c
.RI "bool \fBcwddone\fP"
.br
.ti -1c
.RI "int \fBcwdcount\fP"
.br
.ti -1c
.RI "bool \fBcwdfail\fP"
.br
.ti -1c
.RI "bool \fBwait_data_conn\fP"
.br
.ti -1c
.RI "unsigned short \fBnewport\fP"
.br
.ti -1c
.RI "char * \fBnewhost\fP"
.br
.ti -1c
.RI "char * \fBprevpath\fP"
.br
.ti -1c
.RI "char \fBtransfertype\fP"
.br
.ti -1c
.RI "int \fBcount1\fP"
.br
.ti -1c
.RI "int \fBcount2\fP"
.br
.ti -1c
.RI "int \fBcount3\fP"
.br
.ti -1c
.RI "ftpstate \fBstate\fP"
.br
.ti -1c
.RI "ftpstate \fBstate_saved\fP"
.br
.ti -1c
.RI "curl_off_t \fBretr_size_saved\fP"
.br
.ti -1c
.RI "char * \fBserver_os\fP"
.br
.ti -1c
.RI "curl_off_t \fBknown_filesize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
