.TH "ftp_wc" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ftp_wc
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBftp_parselist_data\fP * \fBparser\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   curl_write_callback \fBwrite_function\fP"
.br
.ti -1c
.RI "   FILE * \fBfile_descriptor\fP"
.br
.ti -1c
.RI "} \fBbackup\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
