.TH "ftp_parselist_data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ftp_parselist_data
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBOS_TYPE_UNKNOWN\fP = 0, \fBOS_TYPE_UNIX\fP, \fBOS_TYPE_WIN_NT\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum ftp_parselist_data:: { \&.\&.\&. }  \fBos_type\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      pl_unix_mainstate \fBmain\fP"
.br
.ti -1c
.RI "      \fBpl_unix_substate\fP \fBsub\fP"
.br
.ti -1c
.RI "   } \fBUNIX\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      pl_winNT_mainstate \fBmain\fP"
.br
.ti -1c
.RI "      \fBpl_winNT_substate\fP \fBsub\fP"
.br
.ti -1c
.RI "   } \fBNT\fP"
.br
.ti -1c
.RI "} \fBstate\fP"
.br
.ti -1c
.RI "CURLcode \fBerror\fP"
.br
.ti -1c
.RI "struct \fBfileinfo\fP * \fBfile_data\fP"
.br
.ti -1c
.RI "unsigned int \fBitem_length\fP"
.br
.ti -1c
.RI "size_t \fBitem_offset\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   size_t \fBfilename\fP"
.br
.ti -1c
.RI "   size_t \fBuser\fP"
.br
.ti -1c
.RI "   size_t \fBgroup\fP"
.br
.ti -1c
.RI "   size_t \fBtime\fP"
.br
.ti -1c
.RI "   size_t \fBperm\fP"
.br
.ti -1c
.RI "   size_t \fBsymlink_target\fP"
.br
.ti -1c
.RI "} \fBoffsets\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
