.TH "FuncState" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FuncState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBProto\fP * \fBf\fP"
.br
.ti -1c
.RI "struct \fBFuncState\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBLexState\fP * \fBls\fP"
.br
.ti -1c
.RI "struct \fBBlockCnt\fP * \fBbl\fP"
.br
.ti -1c
.RI "int \fBpc\fP"
.br
.ti -1c
.RI "int \fBlasttarget\fP"
.br
.ti -1c
.RI "int \fBpreviousline\fP"
.br
.ti -1c
.RI "int \fBnk\fP"
.br
.ti -1c
.RI "int \fBnp\fP"
.br
.ti -1c
.RI "int \fBnabslineinfo\fP"
.br
.ti -1c
.RI "int \fBfirstlocal\fP"
.br
.ti -1c
.RI "int \fBfirstlabel\fP"
.br
.ti -1c
.RI "short \fBndebugvars\fP"
.br
.ti -1c
.RI "lu_byte \fBnactvar\fP"
.br
.ti -1c
.RI "lu_byte \fBnups\fP"
.br
.ti -1c
.RI "lu_byte \fBfreereg\fP"
.br
.ti -1c
.RI "lu_byte \fBiwthabs\fP"
.br
.ti -1c
.RI "lu_byte \fBneedclose\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
