.TH "gdstate" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdstate
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBtoken\fP * \fBtokenp\fP"
.br
.ti -1c
.RI "int \fBHaveYear\fP"
.br
.ti -1c
.RI "int \fBHaveMonth\fP"
.br
.ti -1c
.RI "int \fBHaveDay\fP"
.br
.ti -1c
.RI "int \fBHaveWeekDay\fP"
.br
.ti -1c
.RI "int \fBHaveTime\fP"
.br
.ti -1c
.RI "int \fBHaveZone\fP"
.br
.ti -1c
.RI "int \fBHaveRel\fP"
.br
.ti -1c
.RI "time_t \fBTimezone\fP"
.br
.ti -1c
.RI "time_t \fBDay\fP"
.br
.ti -1c
.RI "time_t \fBHour\fP"
.br
.ti -1c
.RI "time_t \fBMinutes\fP"
.br
.ti -1c
.RI "time_t \fBMonth\fP"
.br
.ti -1c
.RI "time_t \fBSeconds\fP"
.br
.ti -1c
.RI "time_t \fBYear\fP"
.br
.ti -1c
.RI "enum DSTMODE \fBDSTmode\fP"
.br
.ti -1c
.RI "time_t \fBDayOrdinal\fP"
.br
.ti -1c
.RI "time_t \fBDayNumber\fP"
.br
.ti -1c
.RI "time_t \fBRelMonth\fP"
.br
.ti -1c
.RI "time_t \fBRelSeconds\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
