.TH "gen_digits_handler" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gen_digits_handler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR digits::result \fBon_digit\fP (char digit, uint64_t divisor, uint64_t remainder, uint64_t error, bool integral)"
.br
.ti -1c
.RI "FMT_CONSTEXPR digits::result \fBon_digit\fP (char digit, uint64_t divisor, uint64_t remainder, uint64_t error, bool integral)"
.br
.ti -1c
.RI "FMT_CONSTEXPR digits::result \fBon_digit\fP (char digit, uint64_t divisor, uint64_t remainder, uint64_t error, bool integral)"
.br
.ti -1c
.RI "FMT_CONSTEXPR digits::result \fBon_digit\fP (char digit, uint64_t divisor, uint64_t remainder, uint64_t error, bool integral)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBbuf\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBprecision\fP"
.br
.ti -1c
.RI "int \fBexp10\fP"
.br
.ti -1c
.RI "bool \fBfixed\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
