.TH "get_seac_param_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_seac_param_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (const \fBOT::cff1::accelerator_t\fP *_cff)"
.br
.ti -1c
.RI "bool \fBhas_seac\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBOT::cff1::accelerator_t\fP * \fBcff\fP"
.br
.ti -1c
.RI "hb_codepoint_t \fBbase\fP"
.br
.ti -1c
.RI "hb_codepoint_t \fBaccent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
