.TH "get_locale" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
get_locale
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBget_locale\fP (bool localized, \fBlocale_ref\fP loc)"
.br
.ti -1c
.RI "\fBoperator const std::locale &\fP () const"
.br
.ti -1c
.RI "\fBget_locale\fP (bool localized, \fBlocale_ref\fP loc)"
.br
.ti -1c
.RI "\fBoperator const std::locale &\fP () const"
.br
.ti -1c
.RI "\fBget_locale\fP (bool localized, \fBlocale_ref\fP loc)"
.br
.ti -1c
.RI "\fBoperator const std::locale &\fP () const"
.br
.ti -1c
.RI "\fBget_locale\fP (bool localized, \fBlocale_ref\fP loc)"
.br
.ti -1c
.RI "\fBoperator const std::locale &\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
