.TH "gif_dest_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gif_dest_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBdjpeg_dest_struct\fP \fBpub\fP"
.br
.ti -1c
.RI "\fBj_decompress_ptr\fP \fBcinfo\fP"
.br
.ti -1c
.RI "int \fBn_bits\fP"
.br
.ti -1c
.RI "int \fBmaxcode\fP"
.br
.ti -1c
.RI "INT32 \fBcur_accum\fP"
.br
.ti -1c
.RI "int \fBcur_bits\fP"
.br
.ti -1c
.RI "int \fBClearCode\fP"
.br
.ti -1c
.RI "int \fBEOFCode\fP"
.br
.ti -1c
.RI "int \fBcode_counter\fP"
.br
.ti -1c
.RI "int \fBbytesinpkt\fP"
.br
.ti -1c
.RI "char \fBpacketbuf\fP [256]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
