.TH "GifFileType" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GifFileType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GifWord \fBSWidth\fP"
.br
.ti -1c
.RI "GifWord \fBSHeight\fP"
.br
.ti -1c
.RI "GifWord \fBSColorResolution\fP"
.br
.ti -1c
.RI "GifWord \fBSBackGroundColor\fP"
.br
.ti -1c
.RI "GifByteType \fBAspectByte\fP"
.br
.ti -1c
.RI "\fBColorMapObject\fP * \fBSColorMap\fP"
.br
.ti -1c
.RI "int \fBImageCount\fP"
.br
.ti -1c
.RI "\fBGifImageDesc\fP \fBImage\fP"
.br
.ti -1c
.RI "\fBSavedImage\fP * \fBSavedImages\fP"
.br
.ti -1c
.RI "int \fBExtensionBlockCount\fP"
.br
.ti -1c
.RI "\fBExtensionBlock\fP * \fBExtensionBlocks\fP"
.br
.ti -1c
.RI "int \fBError\fP"
.br
.ti -1c
.RI "void * \fBUserData\fP"
.br
.ti -1c
.RI "void * \fBPrivate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
