.TH "GifFilePrivateType" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GifFilePrivateType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GifWord \fBFileState\fP"
.br
.ti -1c
.RI "GifWord \fBFileHandle\fP"
.br
.ti -1c
.RI "GifWord \fBBitsPerPixel\fP"
.br
.ti -1c
.RI "GifWord \fBClearCode\fP"
.br
.ti -1c
.RI "GifWord \fBEOFCode\fP"
.br
.ti -1c
.RI "GifWord \fBRunningCode\fP"
.br
.ti -1c
.RI "GifWord \fBRunningBits\fP"
.br
.ti -1c
.RI "GifWord \fBMaxCode1\fP"
.br
.ti -1c
.RI "GifWord \fBLastCode\fP"
.br
.ti -1c
.RI "GifWord \fBCrntCode\fP"
.br
.ti -1c
.RI "GifWord \fBStackPtr\fP"
.br
.ti -1c
.RI "GifWord \fBCrntShiftState\fP"
.br
.ti -1c
.RI "unsigned long \fBCrntShiftDWord\fP"
.br
.ti -1c
.RI "unsigned long \fBPixelCount\fP"
.br
.ti -1c
.RI "FILE * \fBFile\fP"
.br
.ti -1c
.RI "InputFunc \fBRead\fP"
.br
.ti -1c
.RI "OutputFunc \fBWrite\fP"
.br
.ti -1c
.RI "GifByteType \fBBuf\fP [256]"
.br
.ti -1c
.RI "GifByteType \fBStack\fP [LZ_MAX_CODE]"
.br
.ti -1c
.RI "GifByteType \fBSuffix\fP [LZ_MAX_CODE+1]"
.br
.ti -1c
.RI "GifPrefixType \fBPrefix\fP [LZ_MAX_CODE+1]"
.br
.ti -1c
.RI "\fBGifHashTableType\fP * \fBHashTable\fP"
.br
.ti -1c
.RI "bool \fBgif89\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
