.TH "GifImageDesc" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GifImageDesc
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GifWord \fBLeft\fP"
.br
.ti -1c
.RI "GifWord \fBTop\fP"
.br
.ti -1c
.RI "GifWord \fBWidth\fP"
.br
.ti -1c
.RI "GifWord \fBHeight\fP"
.br
.ti -1c
.RI "bool \fBInterlace\fP"
.br
.ti -1c
.RI "\fBColorMapObject\fP * \fBColorMap\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
