.TH "GL3WProcs" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL3WProcs
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GL3WglProc \fBptr\fP [53]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   PFNGLACTIVETEXTUREPROC \fBActiveTexture\fP"
.br
.ti -1c
.RI "   PFNGLATTACHSHADERPROC \fBAttachShader\fP"
.br
.ti -1c
.RI "   PFNGLBINDBUFFERPROC \fBBindBuffer\fP"
.br
.ti -1c
.RI "   PFNGLBINDSAMPLERPROC \fBBindSampler\fP"
.br
.ti -1c
.RI "   PFNGLBINDTEXTUREPROC \fBBindTexture\fP"
.br
.ti -1c
.RI "   PFNGLBINDVERTEXARRAYPROC \fBBindVertexArray\fP"
.br
.ti -1c
.RI "   PFNGLBLENDEQUATIONPROC \fBBlendEquation\fP"
.br
.ti -1c
.RI "   PFNGLBLENDEQUATIONSEPARATEPROC \fBBlendEquationSeparate\fP"
.br
.ti -1c
.RI "   PFNGLBLENDFUNCSEPARATEPROC \fBBlendFuncSeparate\fP"
.br
.ti -1c
.RI "   PFNGLBUFFERDATAPROC \fBBufferData\fP"
.br
.ti -1c
.RI "   PFNGLCLEARPROC \fBClear\fP"
.br
.ti -1c
.RI "   PFNGLCLEARCOLORPROC \fBClearColor\fP"
.br
.ti -1c
.RI "   PFNGLCOMPILESHADERPROC \fBCompileShader\fP"
.br
.ti -1c
.RI "   PFNGLCREATEPROGRAMPROC \fBCreateProgram\fP"
.br
.ti -1c
.RI "   PFNGLCREATESHADERPROC \fBCreateShader\fP"
.br
.ti -1c
.RI "   PFNGLDELETEBUFFERSPROC \fBDeleteBuffers\fP"
.br
.ti -1c
.RI "   PFNGLDELETEPROGRAMPROC \fBDeleteProgram\fP"
.br
.ti -1c
.RI "   PFNGLDELETESHADERPROC \fBDeleteShader\fP"
.br
.ti -1c
.RI "   PFNGLDELETETEXTURESPROC \fBDeleteTextures\fP"
.br
.ti -1c
.RI "   PFNGLDELETEVERTEXARRAYSPROC \fBDeleteVertexArrays\fP"
.br
.ti -1c
.RI "   PFNGLDETACHSHADERPROC \fBDetachShader\fP"
.br
.ti -1c
.RI "   PFNGLDISABLEPROC \fBDisable\fP"
.br
.ti -1c
.RI "   PFNGLDRAWELEMENTSPROC \fBDrawElements\fP"
.br
.ti -1c
.RI "   PFNGLDRAWELEMENTSBASEVERTEXPROC \fBDrawElementsBaseVertex\fP"
.br
.ti -1c
.RI "   PFNGLENABLEPROC \fBEnable\fP"
.br
.ti -1c
.RI "   PFNGLENABLEVERTEXATTRIBARRAYPROC \fBEnableVertexAttribArray\fP"
.br
.ti -1c
.RI "   PFNGLGENBUFFERSPROC \fBGenBuffers\fP"
.br
.ti -1c
.RI "   PFNGLGENTEXTURESPROC \fBGenTextures\fP"
.br
.ti -1c
.RI "   PFNGLGENVERTEXARRAYSPROC \fBGenVertexArrays\fP"
.br
.ti -1c
.RI "   PFNGLGETATTRIBLOCATIONPROC \fBGetAttribLocation\fP"
.br
.ti -1c
.RI "   PFNGLGETERRORPROC \fBGetError\fP"
.br
.ti -1c
.RI "   PFNGLGETINTEGERVPROC \fBGetIntegerv\fP"
.br
.ti -1c
.RI "   PFNGLGETPROGRAMINFOLOGPROC \fBGetProgramInfoLog\fP"
.br
.ti -1c
.RI "   PFNGLGETPROGRAMIVPROC \fBGetProgramiv\fP"
.br
.ti -1c
.RI "   PFNGLGETSHADERINFOLOGPROC \fBGetShaderInfoLog\fP"
.br
.ti -1c
.RI "   PFNGLGETSHADERIVPROC \fBGetShaderiv\fP"
.br
.ti -1c
.RI "   PFNGLGETSTRINGPROC \fBGetString\fP"
.br
.ti -1c
.RI "   PFNGLGETSTRINGIPROC \fBGetStringi\fP"
.br
.ti -1c
.RI "   PFNGLGETUNIFORMLOCATIONPROC \fBGetUniformLocation\fP"
.br
.ti -1c
.RI "   PFNGLISENABLEDPROC \fBIsEnabled\fP"
.br
.ti -1c
.RI "   PFNGLLINKPROGRAMPROC \fBLinkProgram\fP"
.br
.ti -1c
.RI "   PFNGLPIXELSTOREIPROC \fBPixelStorei\fP"
.br
.ti -1c
.RI "   PFNGLPOLYGONMODEPROC \fBPolygonMode\fP"
.br
.ti -1c
.RI "   PFNGLREADPIXELSPROC \fBReadPixels\fP"
.br
.ti -1c
.RI "   PFNGLSCISSORPROC \fBScissor\fP"
.br
.ti -1c
.RI "   PFNGLSHADERSOURCEPROC \fBShaderSource\fP"
.br
.ti -1c
.RI "   PFNGLTEXIMAGE2DPROC \fBTexImage2D\fP"
.br
.ti -1c
.RI "   PFNGLTEXPARAMETERIPROC \fBTexParameteri\fP"
.br
.ti -1c
.RI "   PFNGLUNIFORM1IPROC \fBUniform1i\fP"
.br
.ti -1c
.RI "   PFNGLUNIFORMMATRIX4FVPROC \fBUniformMatrix4fv\fP"
.br
.ti -1c
.RI "   PFNGLUSEPROGRAMPROC \fBUseProgram\fP"
.br
.ti -1c
.RI "   PFNGLVERTEXATTRIBPOINTERPROC \fBVertexAttribPointer\fP"
.br
.ti -1c
.RI "   PFNGLVIEWPORTPROC \fBViewport\fP"
.br
.ti -1c
.RI "} \fBgl\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
