.TH "GLApp" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLApp
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGLApp\fP (const char *title='OpenGL App', int desired_width=800, int desired_height=600)"
.br
.ti -1c
.RI "\fBGLApp\fP (const \fBGLApp\fP &)=delete"
.br
.ti -1c
.RI "\fBGLApp\fP & \fBoperator=\fP (const \fBGLApp\fP &)=delete"
.br
.ti -1c
.RI "\fBGLApp\fP (\fBGLApp\fP &&) noexcept=delete"
.br
.ti -1c
.RI "\fBGLApp\fP & \fBoperator=\fP (\fBGLApp\fP &&) noexcept=delete"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "bool \fBIsDone\fP () const noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
