.TH "GLAttributeLayout" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLAttributeLayout
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBComponentType\fP : GLenum { \fBFloat\fP = GL_FLOAT, \fBInt\fP = GL_INT, \fBBool\fP = GL_BOOL, \fBFloat\fP = GL_FLOAT, \fBInt\fP = GL_INT, \fBBool\fP = GL_BOOL }"
.br
.ti -1c
.RI "enum \fBNumComponents\fP : GLint { \fB_1\fP = 1, \fB_2\fP = 2, \fB_3\fP = 3, \fB_4\fP = 4, \fB_1\fP = 1, \fB_2\fP = 2, \fB_3\fP = 3, \fB_4\fP = 4 }"
.br
.ti -1c
.RI "enum \fBComponentType\fP : GLenum { \fBFloat\fP = GL_FLOAT, \fBInt\fP = GL_INT, \fBBool\fP = GL_BOOL, \fBFloat\fP = GL_FLOAT, \fBInt\fP = GL_INT, \fBBool\fP = GL_BOOL }"
.br
.ti -1c
.RI "enum \fBNumComponents\fP : GLint { \fB_1\fP = 1, \fB_2\fP = 2, \fB_3\fP = 3, \fB_4\fP = 4, \fB_1\fP = 1, \fB_2\fP = 2, \fB_3\fP = 3, \fB_4\fP = 4 }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ComponentType \fBcomponent_type\fP = ComponentType::Float"
.br
.ti -1c
.RI "NumComponents \fBcomponent_dimension\fP = NumComponents::_1"
.br
.ti -1c
.RI "GLuint \fBvertex_layout_location\fP = 0"
.br
.ti -1c
.RI "GLboolean \fBnormalized\fP = GL_FALSE"
.br
.ti -1c
.RI "GLuint \fBrelative_offset\fP = 0"
.br
.ti -1c
.RI "GLintptr \fBoffset\fP = 0"
.br
.ti -1c
.RI "GLsizei \fBstride\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
