.TH "GLFWgamepadstate" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLFWgamepadstate \- Gamepad input state\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glfw3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBbuttons\fP [15]"
.br
.ti -1c
.RI "float \fBaxes\fP [6]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gamepad input state\&. 

This describes the input state of a gamepad\&.
.PP
\fBSee also\fP
.RS 4
\fBgamepad\fP 
.PP
\fBglfwGetGamepadState\fP
.RE
.PP
\fBSince\fP
.RS 4
Added in version 3\&.3\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "float GLFWgamepadstate::axes"
The states of each \fBgamepad axis\fP, in the range -1\&.0 to 1\&.0 inclusive\&. 
.SS "unsigned char GLFWgamepadstate::buttons"
The states of each \fBgamepad button\fP, \fCGLFW_PRESS\fP or \fCGLFW_RELEASE\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
