.TH "GLIndexElement" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLIndexElement
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP : unsigned { \fBUInt\fP = GL_UNSIGNED_INT, \fBUShort\fP = GL_UNSIGNED_SHORT, \fBUByte\fP = GL_UNSIGNED_BYTE, \fBNone\fP = 0, \fBUInt\fP = GL_UNSIGNED_INT, \fBUShort\fP = GL_UNSIGNED_SHORT, \fBUByte\fP = GL_UNSIGNED_BYTE, \fBNone\fP = 0 }"
.br
.ti -1c
.RI "enum \fBType\fP : unsigned { \fBUInt\fP = GL_UNSIGNED_INT, \fBUShort\fP = GL_UNSIGNED_SHORT, \fBUByte\fP = GL_UNSIGNED_BYTE, \fBNone\fP = 0, \fBUInt\fP = GL_UNSIGNED_INT, \fBUShort\fP = GL_UNSIGNED_SHORT, \fBUByte\fP = GL_UNSIGNED_BYTE, \fBNone\fP = 0 }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
