.TH "GLIndexBuffer" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLIndexBuffer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGLIndexBuffer\fP (std::span< const unsigned int > indices)"
.br
.ti -1c
.RI "\fBGLIndexBuffer\fP (std::span< const unsigned short > indices)"
.br
.ti -1c
.RI "\fBGLIndexBuffer\fP (std::span< const unsigned char > indices)"
.br
.ti -1c
.RI "\fBGLIndexBuffer\fP (const \fBGLIndexBuffer\fP &)=delete"
.br
.ti -1c
.RI "\fBGLIndexBuffer\fP & \fBoperator=\fP (const \fBGLIndexBuffer\fP &)=delete"
.br
.ti -1c
.RI "\fBGLIndexBuffer\fP (\fBGLIndexBuffer\fP &&temp) noexcept"
.br
.ti -1c
.RI "\fBGLIndexBuffer\fP & \fBoperator=\fP (\fBGLIndexBuffer\fP &&temp) noexcept"
.br
.ti -1c
.RI "void \fBUse\fP (bool bind=true) const"
.br
.ti -1c
.RI "template<typename T > void \fBcreate_indices_buffer\fP (std::span< T >indices)"
.br
.ti -1c
.RI "GLHandle \fBGetHandle\fP () const noexcept"
.br
.ti -1c
.RI "GLsizei \fBGetCount\fP () const noexcept"
.br
.ti -1c
.RI "GLIndexElement::Type \fBGetElementType\fP () const noexcept"
.br
.ti -1c
.RI "\fBGLIndexBuffer\fP (std::span< const unsigned int > indices)"
.br
.ti -1c
.RI "\fBGLIndexBuffer\fP (std::span< const unsigned short > indices)"
.br
.ti -1c
.RI "\fBGLIndexBuffer\fP (std::span< const unsigned char > indices)"
.br
.ti -1c
.RI "\fBGLIndexBuffer\fP (const \fBGLIndexBuffer\fP &)=delete"
.br
.ti -1c
.RI "\fBGLIndexBuffer\fP & \fBoperator=\fP (const \fBGLIndexBuffer\fP &)=delete"
.br
.ti -1c
.RI "\fBGLIndexBuffer\fP (\fBGLIndexBuffer\fP &&temp) noexcept"
.br
.ti -1c
.RI "\fBGLIndexBuffer\fP & \fBoperator=\fP (\fBGLIndexBuffer\fP &&temp) noexcept"
.br
.ti -1c
.RI "void \fBUse\fP (bool bind=true) const"
.br
.ti -1c
.RI "template<typename T > void \fBcreate_indices_buffer\fP (std::span< T >indices)"
.br
.ti -1c
.RI "GLHandle \fBGetHandle\fP () const noexcept"
.br
.ti -1c
.RI "GLsizei \fBGetCount\fP () const noexcept"
.br
.ti -1c
.RI "GLIndexElement::Type \fBGetElementType\fP () const noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
