.TH "GLPrimitive" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLPrimitive
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP : GLenum { \fBPoints\fP = GL_POINTS, \fBLines\fP = GL_LINES, \fBLineLoop\fP = GL_LINE_LOOP, \fBLineStrip\fP = GL_LINE_STRIP, \fBTriangles\fP = GL_TRIANGLES, \fBTriangleStrip\fP = GL_TRIANGLE_STRIP, \fBTriangleFan\fP = GL_TRIANGLE_FAN, \fBPoints\fP = GL_POINTS, \fBLines\fP = GL_LINES, \fBLineLoop\fP = GL_LINE_LOOP, \fBLineStrip\fP = GL_LINE_STRIP, \fBTriangles\fP = GL_TRIANGLES, \fBTriangleStrip\fP = GL_TRIANGLE_STRIP, \fBTriangleFan\fP = GL_TRIANGLE_FAN }"
.br
.ti -1c
.RI "enum \fBType\fP : GLenum { \fBPoints\fP = GL_POINTS, \fBLines\fP = GL_LINES, \fBLineLoop\fP = GL_LINE_LOOP, \fBLineStrip\fP = GL_LINE_STRIP, \fBTriangles\fP = GL_TRIANGLES, \fBTriangleStrip\fP = GL_TRIANGLE_STRIP, \fBTriangleFan\fP = GL_TRIANGLE_FAN, \fBPoints\fP = GL_POINTS, \fBLines\fP = GL_LINES, \fBLineLoop\fP = GL_LINE_LOOP, \fBLineStrip\fP = GL_LINE_STRIP, \fBTriangles\fP = GL_TRIANGLES, \fBTriangleStrip\fP = GL_TRIANGLE_STRIP, \fBTriangleFan\fP = GL_TRIANGLE_FAN }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
