.TH "GLTexture" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLTexture
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFiltering\fP : GLint { \fBNearestPixel\fP = GL_NEAREST, \fBLinear\fP = GL_LINEAR }"
.br
.ti -1c
.RI "enum \fBCoordinate\fP { \fBS\fP, \fBT\fP, \fBBoth\fP }"
.br
.ti -1c
.RI "enum \fBWrapping\fP : GLint { \fBRepeat\fP = GL_REPEAT, \fBClampToEdge\fP = GL_CLAMP_TO_EDGE, \fBClampToBorder\fP = GL_CLAMP_TO_BORDER, \fBMirroredRepeat\fP = GL_MIRRORED_REPEAT, \fBMirrorClampToEdge\fP = GL_MIRROR_CLAMP_TO_EDGE }"
.br
.ti -1c
.RI "using \fBRGBA\fP = unsigned int"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGLTexture\fP (const \fBGLTexture\fP &other)=delete"
.br
.ti -1c
.RI "\fBGLTexture\fP (\fBGLTexture\fP &&other) noexcept"
.br
.ti -1c
.RI "\fBGLTexture\fP & \fBoperator=\fP (const \fBGLTexture\fP &other)=delete"
.br
.ti -1c
.RI "\fBGLTexture\fP & \fBoperator=\fP (\fBGLTexture\fP &&other) noexcept"
.br
.ti -1c
.RI "bool \fBLoadFromFileImage\fP (const std::filesystem::path &image_filepath, bool flip_vertical=true) noexcept"
.br
.ti -1c
.RI "bool \fBLoadFromMemory\fP (int image_width, int image_height, const RGBA *colors) noexcept"
.br
.ti -1c
.RI "void \fBUseForSlot\fP (unsigned int texture_unit) const noexcept"
.br
.ti -1c
.RI "unsigned int \fBGetHandle\fP () const noexcept"
.br
.ti -1c
.RI "int \fBGetWidth\fP () const noexcept"
.br
.ti -1c
.RI "int \fBGetHeight\fP () const noexcept"
.br
.ti -1c
.RI "void \fBSetFiltering\fP (Filtering how_to_filter) noexcept"
.br
.ti -1c
.RI "Filtering \fBGetFiltering\fP () const noexcept"
.br
.ti -1c
.RI "void \fBSetWrapping\fP (Wrapping how_to_wrap, Coordinate coord=Coordinate::Both) noexcept"
.br
.ti -1c
.RI "std::array< Wrapping, 2 > \fBGetWrapping\fP () const noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
