.TH "GLVertexBuffer" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLVertexBuffer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGLVertexBuffer\fP (GLsizei size_in_bytes)"
.br
.ti -1c
.RI "template<typename T , auto N = std::dynamic_extent> \fBGLVertexBuffer\fP (std::span< T, N > buffer_data)"
.br
.ti -1c
.RI "\fBGLVertexBuffer\fP (const \fBGLVertexBuffer\fP &)=delete"
.br
.ti -1c
.RI "\fBGLVertexBuffer\fP & \fBoperator=\fP (const \fBGLVertexBuffer\fP &)=delete"
.br
.ti -1c
.RI "\fBGLVertexBuffer\fP (\fBGLVertexBuffer\fP &&temp) noexcept"
.br
.ti -1c
.RI "\fBGLVertexBuffer\fP & \fBoperator=\fP (\fBGLVertexBuffer\fP &&temp) noexcept"
.br
.ti -1c
.RI "void \fBUse\fP (bool bind=true) const"
.br
.ti -1c
.RI "template<typename T , auto N = std::dynamic_extent> void \fBSetData\fP (std::span< T, N > buffer_data, GLsizei starting_offset=0) const"
.br
.ti -1c
.RI "GLHandle \fBGetHandle\fP () const noexcept"
.br
.ti -1c
.RI "GLsizei \fBGetSizeBytes\fP () const noexcept"
.br
.ti -1c
.RI "\fBGLVertexBuffer\fP (GLsizei size_in_bytes)"
.br
.ti -1c
.RI "template<typename T , auto N = std::dynamic_extent> \fBGLVertexBuffer\fP (std::span< T, N > buffer_data)"
.br
.ti -1c
.RI "\fBGLVertexBuffer\fP (const \fBGLVertexBuffer\fP &)=delete"
.br
.ti -1c
.RI "\fBGLVertexBuffer\fP & \fBoperator=\fP (const \fBGLVertexBuffer\fP &)=delete"
.br
.ti -1c
.RI "\fBGLVertexBuffer\fP (\fBGLVertexBuffer\fP &&temp) noexcept"
.br
.ti -1c
.RI "\fBGLVertexBuffer\fP & \fBoperator=\fP (\fBGLVertexBuffer\fP &&temp) noexcept"
.br
.ti -1c
.RI "void \fBUse\fP (bool bind=true) const"
.br
.ti -1c
.RI "template<typename T , auto N = std::dynamic_extent> void \fBSetData\fP (std::span< T, N > buffer_data, GLsizei starting_offset=0) const"
.br
.ti -1c
.RI "GLHandle \fBGetHandle\fP () const noexcept"
.br
.ti -1c
.RI "GLsizei \fBGetSizeBytes\fP () const noexcept"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
