.TH "GLVertexArray" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLVertexArray
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGLVertexArray\fP (GLPrimitive::Type the_primitive_pattern=GLPrimitive::Triangles)"
.br
.ti -1c
.RI "\fBGLVertexArray\fP (const \fBGLVertexArray\fP &)=delete"
.br
.ti -1c
.RI "\fBGLVertexArray\fP & \fBoperator=\fP (const \fBGLVertexArray\fP &)=delete"
.br
.ti -1c
.RI "\fBGLVertexArray\fP (\fBGLVertexArray\fP &&temp) noexcept"
.br
.ti -1c
.RI "\fBGLVertexArray\fP & \fBoperator=\fP (\fBGLVertexArray\fP &&temp) noexcept"
.br
.ti -1c
.RI "void \fBUse\fP (bool bind=true) const"
.br
.ti -1c
.RI "void \fBAddVertexBuffer\fP (\fBGLVertexBuffer\fP &&vertex_buffer, std::initializer_list< \fBGLAttributeLayout\fP > buffer_layout)"
.br
.ti -1c
.RI "void \fBSetIndexBuffer\fP (\fBGLIndexBuffer\fP &&the_indices)"
.br
.ti -1c
.RI "GLHandle \fBGetHandle\fP () const noexcept"
.br
.ti -1c
.RI "const auto & \fBGetVertexBuffers\fP () const"
.br
.ti -1c
.RI "const auto & \fBGetIndexBuffer\fP () const"
.br
.ti -1c
.RI "GLsizei \fBGetIndicesCount\fP () const noexcept"
.br
.ti -1c
.RI "GLIndexElement::Type \fBGetIndicesType\fP () const noexcept"
.br
.ti -1c
.RI "GLPrimitive::Type \fBGetPrimitivePattern\fP () const"
.br
.ti -1c
.RI "void \fBSetPrimitivePattern\fP (GLPrimitive::Type the_primitive_pattern)"
.br
.ti -1c
.RI "GLsizei \fBGetVertexCount\fP () const"
.br
.ti -1c
.RI "void \fBSetVertexCount\fP (int vertex_count)"
.br
.ti -1c
.RI "\fBGLVertexArray\fP (GLPrimitive::Type the_primitive_pattern=GLPrimitive::Triangles)"
.br
.ti -1c
.RI "\fBGLVertexArray\fP (const \fBGLVertexArray\fP &)=delete"
.br
.ti -1c
.RI "\fBGLVertexArray\fP & \fBoperator=\fP (const \fBGLVertexArray\fP &)=delete"
.br
.ti -1c
.RI "\fBGLVertexArray\fP (\fBGLVertexArray\fP &&temp) noexcept"
.br
.ti -1c
.RI "\fBGLVertexArray\fP & \fBoperator=\fP (\fBGLVertexArray\fP &&temp) noexcept"
.br
.ti -1c
.RI "void \fBUse\fP (bool bind=true) const"
.br
.ti -1c
.RI "void \fBAddVertexBuffer\fP (\fBGLVertexBuffer\fP &&vertex_buffer, std::initializer_list< \fBGLAttributeLayout\fP > buffer_layout)"
.br
.ti -1c
.RI "void \fBSetIndexBuffer\fP (\fBGLIndexBuffer\fP &&the_indices)"
.br
.ti -1c
.RI "GLint \fBGetHandle\fP () const noexcept"
.br
.ti -1c
.RI "const auto & \fBGetVertexBuffers\fP () const"
.br
.ti -1c
.RI "const auto & \fBGetIndexBuffer\fP () const"
.br
.ti -1c
.RI "GLsizei \fBGetIndicesCount\fP () const noexcept"
.br
.ti -1c
.RI "GLIndexElement::Type \fBGetIndicesType\fP () const noexcept"
.br
.ti -1c
.RI "GLPrimitive::Type \fBGetPrimitivePattern\fP () const"
.br
.ti -1c
.RI "void \fBSetPrimitivePattern\fP (GLPrimitive::Type the_primitive_pattern)"
.br
.ti -1c
.RI "GLsizei \fBGetVertexCount\fP () const"
.br
.ti -1c
.RI "void \fBSetVertexCount\fP (int vertex_count)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
