.TH "glyph_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glyph_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBfont_key\fP"
.br
.ti -1c
.RI "void * \fBglyph_key\fP"
.br
.ti -1c
.RI "int \fBorigin_x\fP"
.br
.ti -1c
.RI "int \fBorigin_y\fP"
.br
.ti -1c
.RI "\fBpixman_image_t\fP * \fBimage\fP"
.br
.ti -1c
.RI "\fBpixman_link_t\fP \fBmru_link\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
