.TH "GMatchState" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GMatchState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBsrc\fP"
.br
.ti -1c
.RI "const char * \fBp\fP"
.br
.ti -1c
.RI "const char * \fBlastmatch\fP"
.br
.ti -1c
.RI "\fBMatchState\fP \fBms\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
