.TH "gradient" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gradient
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBimage_common_t\fP \fBcommon\fP"
.br
.ti -1c
.RI "int \fBn_stops\fP"
.br
.ti -1c
.RI "\fBpixman_gradient_stop_t\fP * \fBstops\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
