.TH "graph_t::vertex_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph_t::vertex_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBis_shared\fP () const"
.br
.ti -1c
.RI "unsigned \fBincoming_edges\fP () const"
.br
.ti -1c
.RI "void \fBremove_parent\fP (unsigned parent_index)"
.br
.ti -1c
.RI "void \fBremap_parents\fP (const \fBhb_vector_t\fP< unsigned > &id_map)"
.br
.ti -1c
.RI "void \fBremap_parent\fP (unsigned old_index, unsigned new_index)"
.br
.ti -1c
.RI "bool \fBis_leaf\fP () const"
.br
.ti -1c
.RI "bool \fBraise_priority\fP ()"
.br
.ti -1c
.RI "bool \fBhas_max_priority\fP () const"
.br
.ti -1c
.RI "int64_t \fBmodified_distance\fP (unsigned order) const"
.br
.ti -1c
.RI "int64_t \fBdistance_modifier\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_serialize_context_t::object_t\fP \fBobj\fP"
.br
.ti -1c
.RI "int64_t \fBdistance\fP = 0"
.br
.ti -1c
.RI "int64_t \fBspace\fP = 0"
.br
.ti -1c
.RI "\fBhb_vector_t\fP< unsigned > \fBparents\fP"
.br
.ti -1c
.RI "unsigned \fBstart\fP = 0"
.br
.ti -1c
.RI "unsigned \fBend\fP = 0"
.br
.ti -1c
.RI "unsigned \fBpriority\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
