.TH "GraphicsControlBlock" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsControlBlock
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBDisposalMode\fP"
.br
.ti -1c
.RI "bool \fBUserInputFlag\fP"
.br
.ti -1c
.RI "int \fBDelayTime\fP"
.br
.ti -1c
.RI "int \fBTransparentColor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
