.TH "graph_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graph_t
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBoverflow_record_t\fP"
.br
.ti -1c
.RI "struct \fBvertex_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgraph_t\fP (const \fBhb_vector_t\fP< \fBhb_serialize_context_t::object_t\fP * > &objects)"
.br
.ti -1c
.RI "bool \fBin_error\fP () const"
.br
.ti -1c
.RI "const \fBvertex_t\fP & \fBroot\fP () const"
.br
.ti -1c
.RI "unsigned \fBroot_idx\fP () const"
.br
.ti -1c
.RI "const \fBhb_serialize_context_t::object_t\fP & \fBobject\fP (unsigned i) const"
.br
.ti -1c
.RI "\fBhb_blob_t\fP * \fBserialize\fP () const"
.br
.ti -1c
.RI "void \fBsort_kahn\fP ()"
.br
.ti -1c
.RI "void \fBsort_shortest_distance\fP ()"
.br
.ti -1c
.RI "bool \fBassign_32bit_spaces\fP ()"
.br
.ti -1c
.RI "bool \fBisolate_subgraph\fP (\fBhb_set_t\fP &roots)"
.br
.ti -1c
.RI "void \fBfind_subgraph\fP (unsigned node_idx, \fBhb_hashmap_t\fP< unsigned, unsigned > &subgraph)"
.br
.ti -1c
.RI "void \fBfind_subgraph\fP (unsigned node_idx, \fBhb_set_t\fP &subgraph)"
.br
.ti -1c
.RI "void \fBduplicate_subgraph\fP (unsigned node_idx, \fBhb_hashmap_t\fP< unsigned, unsigned > &index_map)"
.br
.ti -1c
.RI "unsigned \fBduplicate\fP (unsigned node_idx)"
.br
.ti -1c
.RI "bool \fBduplicate\fP (unsigned parent_idx, unsigned child_idx)"
.br
.ti -1c
.RI "bool \fBraise_childrens_priority\fP (unsigned parent_idx)"
.br
.ti -1c
.RI "bool \fBwill_overflow\fP (\fBhb_vector_t\fP< \fBoverflow_record_t\fP > *overflows=nullptr)"
.br
.ti -1c
.RI "void \fBprint_orphaned_nodes\fP ()"
.br
.ti -1c
.RI "void \fBprint_overflows\fP (const \fBhb_vector_t\fP< \fBoverflow_record_t\fP > &overflows)"
.br
.ti -1c
.RI "unsigned \fBnum_roots_for_space\fP (unsigned space) const"
.br
.ti -1c
.RI "unsigned \fBnext_space\fP () const"
.br
.ti -1c
.RI "void \fBmove_to_new_space\fP (const \fBhb_set_t\fP &indices)"
.br
.ti -1c
.RI "unsigned \fBspace_for\fP (unsigned index, unsigned *root=nullptr) const"
.br
.ti -1c
.RI "void \fBerr_other_error\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_vector_t\fP< \fBvertex_t\fP > \fBvertices_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
