.TH "gray_TWorker_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gray_TWorker_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ft_jmp_buf \fBjump_buffer\fP"
.br
.ti -1c
.RI "TCoord \fBmin_ex\fP"
.br
.ti -1c
.RI "TCoord \fBmax_ex\fP"
.br
.ti -1c
.RI "TCoord \fBmin_ey\fP"
.br
.ti -1c
.RI "TCoord \fBmax_ey\fP"
.br
.ti -1c
.RI "TCoord \fBcount_ey\fP"
.br
.ti -1c
.RI "\fBPCell\fP \fBcell\fP"
.br
.ti -1c
.RI "\fBPCell\fP \fBcell_free\fP"
.br
.ti -1c
.RI "\fBPCell\fP \fBcell_null\fP"
.br
.ti -1c
.RI "\fBPCell\fP * \fBycells\fP"
.br
.ti -1c
.RI "TPos \fBx\fP"
.br
.ti -1c
.RI "TPos \fBy\fP"
.br
.ti -1c
.RI "\fBFT_Outline\fP \fBoutline\fP"
.br
.ti -1c
.RI "\fBTPixmap\fP \fBtarget\fP"
.br
.ti -1c
.RI "FT_Raster_Span_Func \fBrender_span\fP"
.br
.ti -1c
.RI "void * \fBrender_span_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
