.TH "gss_ctx_id_t_desc_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gss_ctx_id_t_desc_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBNONE\fP, \fBKRB5\fP, \fBNTLM1\fP, \fBNTLM3\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum gss_ctx_id_t_desc_struct:: { \&.\&.\&. }  \fBsent\fP"
.br
.ti -1c
.RI "int \fBhave_krb5\fP"
.br
.ti -1c
.RI "int \fBhave_ntlm\fP"
.br
.ti -1c
.RI "OM_uint32 \fBflags\fP"
.br
.ti -1c
.RI "char \fBcreds\fP [MAX_CREDS_LENGTH]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
