.TH "GXV_mort_featureRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_mort_featureRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBfeatureType\fP"
.br
.ti -1c
.RI "FT_UShort \fBfeatureSetting\fP"
.br
.ti -1c
.RI "FT_ULong \fBenableFlags\fP"
.br
.ti -1c
.RI "FT_ULong \fBdisableFlags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
