.TH "GXV_mort_subtable_type5_StateOptRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_mort_subtable_type5_StateOptRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBclassTable\fP"
.br
.ti -1c
.RI "FT_UShort \fBstateArray\fP"
.br
.ti -1c
.RI "FT_UShort \fBentryTable\fP"
.br
.ti -1c
.RI "FT_UShort * \fBclassTable_length_p\fP"
.br
.ti -1c
.RI "FT_UShort * \fBstateArray_length_p\fP"
.br
.ti -1c
.RI "FT_UShort * \fBentryTable_length_p\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
