.TH "GXV_mort_subtable_type2_StateOptRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_mort_subtable_type2_StateOptRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBligActionTable\fP"
.br
.ti -1c
.RI "FT_UShort \fBcomponentTable\fP"
.br
.ti -1c
.RI "FT_UShort \fBligatureTable\fP"
.br
.ti -1c
.RI "FT_UShort \fBligActionTable_length\fP"
.br
.ti -1c
.RI "FT_UShort \fBcomponentTable_length\fP"
.br
.ti -1c
.RI "FT_UShort \fBligatureTable_length\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
