.TH "GXV_just_DataRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GXV_just_DataRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBwdc_offset_max\fP"
.br
.ti -1c
.RI "FT_UShort \fBwdc_offset_min\fP"
.br
.ti -1c
.RI "FT_UShort \fBpc_offset_max\fP"
.br
.ti -1c
.RI "FT_UShort \fBpc_offset_min\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
