.TH "gz_header_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gz_header_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtext\fP"
.br
.ti -1c
.RI "uLong \fBtime\fP"
.br
.ti -1c
.RI "int \fBxflags\fP"
.br
.ti -1c
.RI "int \fBos\fP"
.br
.ti -1c
.RI "Bytef * \fBextra\fP"
.br
.ti -1c
.RI "uInt \fBextra_len\fP"
.br
.ti -1c
.RI "uInt \fBextra_max\fP"
.br
.ti -1c
.RI "Bytef * \fBname\fP"
.br
.ti -1c
.RI "uInt \fBname_max\fP"
.br
.ti -1c
.RI "Bytef * \fBcomment\fP"
.br
.ti -1c
.RI "uInt \fBcomm_max\fP"
.br
.ti -1c
.RI "int \fBhcrc\fP"
.br
.ti -1c
.RI "int \fBdone\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
