.TH "gz_state" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gz_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBgzFile_s\fP \fBx\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "unsigned \fBsize\fP"
.br
.ti -1c
.RI "unsigned \fBwant\fP"
.br
.ti -1c
.RI "unsigned char * \fBin\fP"
.br
.ti -1c
.RI "unsigned char * \fBout\fP"
.br
.ti -1c
.RI "int \fBdirect\fP"
.br
.ti -1c
.RI "int \fBhow\fP"
.br
.ti -1c
.RI "z_off64_t \fBstart\fP"
.br
.ti -1c
.RI "int \fBeof\fP"
.br
.ti -1c
.RI "int \fBpast\fP"
.br
.ti -1c
.RI "int \fBlevel\fP"
.br
.ti -1c
.RI "int \fBstrategy\fP"
.br
.ti -1c
.RI "int \fBreset\fP"
.br
.ti -1c
.RI "z_off64_t \fBskip\fP"
.br
.ti -1c
.RI "int \fBseek\fP"
.br
.ti -1c
.RI "int \fBerr\fP"
.br
.ti -1c
.RI "char * \fBmsg\fP"
.br
.ti -1c
.RI "\fBz_stream\fP \fBstrm\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
