.TH "gzfilestream_common" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gzfilestream_common
.SH SYNOPSIS
.br
.PP
.PP
Inherits ios\&.
.PP
Inherited by \fBgzifstream\fP, and \fBgzofstream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBattach\fP (int fd, int io_mode)"
.br
.ti -1c
.RI "void \fBopen\fP (const char *name, int io_mode)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBgzifstream\fP"
.br
.ti -1c
.RI "class \fBgzofstream\fP"
.br
.ti -1c
.RI "\fBgzofstream\fP & \fBsetcompressionlevel\fP (\fBgzofstream\fP &, int)"
.br
.ti -1c
.RI "\fBgzofstream\fP & \fBsetcompressionstrategy\fP (\fBgzofstream\fP &, int)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
