.TH "gzomanip2< T1, T2 >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gzomanip2< T1, T2 > \- Gzipped file output stream manipulator class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <zfstream\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgzomanip2\fP (\fBgzofstream\fP &(*f)(\fBgzofstream\fP &, T1, T2), T1 v1, T2 v2)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename Ta , typename Tb > \fBgzofstream\fP & \fBoperator<<\fP (\fBgzofstream\fP &, const \fBgzomanip2\fP< Ta, Tb > &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T1, typename T2>
.br
class gzomanip2< T1, T2 >"Gzipped file output stream manipulator class\&. 

This class defines a two-argument manipulator for gzofstream\&. It is used as base for the setcompression(int,int) manipulator\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
