.TH "hardlink" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hardlink
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive_rb_node\fP \fBrbnode\fP"
.br
.ti -1c
.RI "int \fBnlink\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBisofile\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBisofile\fP ** \fBlast\fP"
.br
.ti -1c
.RI "} \fBfile_list\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
