.TH "has_member_data_tm_gmtoff< T, typename >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
has_member_data_tm_gmtoff< T, typename >
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::false_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
