.TH "hb_aat_map_builder_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_aat_map_builder_t
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBfeature_info_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "HB_INTERNAL \fBhb_aat_map_builder_t\fP (\fBhb_face_t\fP *face_, const \fBhb_segment_properties_t\fP *props_ HB_UNUSED)"
.br
.ti -1c
.RI "HB_INTERNAL void \fBadd_feature\fP (hb_tag_t tag, unsigned int \fBvalue\fP=1)"
.br
.ti -1c
.RI "HB_INTERNAL void \fBcompile\fP (\fBhb_aat_map_t\fP &m)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_face_t\fP * \fBface\fP"
.br
.ti -1c
.RI "\fBhb_sorted_vector_t\fP< \fBfeature_info_t\fP > \fBfeatures\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
