.TH "hb_atomic_int_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_atomic_int_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBhb_atomic_int_t\fP (int v)"
.br
.ti -1c
.RI "void \fBset_relaxed\fP (int v_)"
.br
.ti -1c
.RI "void \fBset\fP (int v_)"
.br
.ti -1c
.RI "int \fBget_relaxed\fP () const"
.br
.ti -1c
.RI "int \fBget\fP () const"
.br
.ti -1c
.RI "int \fBinc\fP ()"
.br
.ti -1c
.RI "int \fBdec\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBv\fP = 0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
