.TH "hb_aat_layout_feature_selector_info_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_aat_layout_feature_selector_info_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hb\-aat\-layout\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_ot_name_id_t \fBname_id\fP"
.br
.ti -1c
.RI "hb_aat_layout_feature_selector_t \fBenable\fP"
.br
.ti -1c
.RI "hb_aat_layout_feature_selector_t \fBdisable\fP"
.br
.ti -1c
.RI "unsigned int \fBreserved\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBhb_aat_layout_feature_selector_info_t\fP: @name_id: The selector's name identifier @enable: The value to turn the selector on @disable: The value to turn the selector off
.PP
Structure representing a setting for an hb_aat_layout_feature_type_t\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
