.TH "hb_aat_map_builder_t::feature_info_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_aat_map_builder_t::feature_info_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcmp\fP (const \fBfeature_info_t\fP &f) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static HB_INTERNAL int \fBcmp\fP (const void *pa, const void *pb)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_aat_layout_feature_type_t \fBtype\fP"
.br
.ti -1c
.RI "hb_aat_layout_feature_selector_t \fBsetting\fP"
.br
.ti -1c
.RI "bool \fBis_exclusive\fP"
.br
.ti -1c
.RI "unsigned \fBseq\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
