.TH "hb_auto_trace_t< 0, ret_t >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_auto_trace_t< 0, ret_t >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhb_auto_trace_t\fP (unsigned int *plevel_, const char *what_, const void *obj_, const char *func, const char *message,\&.\&.\&.) HB_PRINTF_FUNC(6"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
