.TH "hb_bit_set_t::page_map_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_bit_set_t::page_map_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcmp\fP (const \fBpage_map_t\fP &o) const"
.br
.ti -1c
.RI "int \fBcmp\fP (uint32_t o_major) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBmajor\fP"
.br
.ti -1c
.RI "uint32_t \fBindex\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
