.TH "hb_blob_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_blob_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBfini_shallow\fP ()"
.br
.ti -1c
.RI "void \fBdestroy_user_data\fP ()"
.br
.ti -1c
.RI "HB_INTERNAL bool \fBtry_make_writable\fP ()"
.br
.ti -1c
.RI "HB_INTERNAL bool \fBtry_make_writable_inplace\fP ()"
.br
.ti -1c
.RI "HB_INTERNAL bool \fBtry_make_writable_inplace_unix\fP ()"
.br
.ti -1c
.RI "\fBhb_bytes_t\fP \fBas_bytes\fP () const"
.br
.ti -1c
.RI "template<typename Type > const Type * \fBas\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_object_header_t\fP \fBheader\fP"
.br
.ti -1c
.RI "const char * \fBdata\fP"
.br
.ti -1c
.RI "unsigned int \fBlength\fP"
.br
.ti -1c
.RI "hb_memory_mode_t \fBmode\fP"
.br
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.ti -1c
.RI "hb_destroy_func_t \fBdestroy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
