.TH "hb_bit_page_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_bit_page_t
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef unsigned long long \fBelt_t\fP"
.br
.ti -1c
.RI "typedef \fBhb_vector_size_t\fP< elt_t, PAGE_BITS/8 > \fBvector_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit0\fP ()"
.br
.ti -1c
.RI "void \fBinit1\fP ()"
.br
.ti -1c
.RI "constexpr unsigned \fBlen\fP () const"
.br
.ti -1c
.RI "bool \fBis_empty\fP () const"
.br
.ti -1c
.RI "void \fBadd\fP (hb_codepoint_t g)"
.br
.ti -1c
.RI "void \fBdel\fP (hb_codepoint_t g)"
.br
.ti -1c
.RI "void \fBset\fP (hb_codepoint_t g, bool v)"
.br
.ti -1c
.RI "bool \fBget\fP (hb_codepoint_t g) const"
.br
.ti -1c
.RI "void \fBadd_range\fP (hb_codepoint_t \fBa\fP, hb_codepoint_t b)"
.br
.ti -1c
.RI "void \fBdel_range\fP (hb_codepoint_t \fBa\fP, hb_codepoint_t b)"
.br
.ti -1c
.RI "void \fBset_range\fP (hb_codepoint_t \fBa\fP, hb_codepoint_t b, bool v)"
.br
.ti -1c
.RI "bool \fBis_equal\fP (const \fBhb_bit_page_t\fP &other) const"
.br
.ti -1c
.RI "bool \fBis_subset\fP (const \fBhb_bit_page_t\fP &larger_page) const"
.br
.ti -1c
.RI "unsigned int \fBget_population\fP () const"
.br
.ti -1c
.RI "bool \fBnext\fP (hb_codepoint_t *codepoint) const"
.br
.ti -1c
.RI "bool \fBprevious\fP (hb_codepoint_t *codepoint) const"
.br
.ti -1c
.RI "hb_codepoint_t \fBget_min\fP () const"
.br
.ti -1c
.RI "hb_codepoint_t \fBget_max\fP () const"
.br
.ti -1c
.RI "elt_t & \fBelt\fP (hb_codepoint_t g)"
.br
.ti -1c
.RI "const elt_t & \fBelt\fP (hb_codepoint_t g) const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned int \fBelt_get_min\fP (const elt_t &elt)"
.br
.ti -1c
.RI "static unsigned int \fBelt_get_max\fP (const elt_t &elt)"
.br
.ti -1c
.RI "static constexpr elt_t \fBmask\fP (hb_codepoint_t g)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvector_t\fP \fBv\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr hb_codepoint_t \fBINVALID\fP = HB_SET_VALUE_INVALID"
.br
.ti -1c
.RI "static constexpr unsigned \fBPAGE_BITS\fP = 512"
.br
.ti -1c
.RI "static constexpr unsigned \fBELT_BITS\fP = sizeof (elt_t) * 8"
.br
.ti -1c
.RI "static constexpr unsigned \fBELT_MASK\fP = ELT_BITS \- 1"
.br
.ti -1c
.RI "static constexpr unsigned \fBBITS\fP = sizeof (\fBvector_t\fP) * 8"
.br
.ti -1c
.RI "static constexpr unsigned \fBMASK\fP = BITS \- 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
