.TH "hb_collect_features_context_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_collect_features_context_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhb_collect_features_context_t\fP (\fBhb_face_t\fP *face, hb_tag_t table_tag, \fBhb_set_t\fP *feature_indices_, const hb_tag_t *features)"
.br
.ti -1c
.RI "void \fBcompute_feature_filter\fP (const hb_tag_t *features)"
.br
.ti -1c
.RI "bool \fBvisited\fP (const \fBOT::Script\fP &s)"
.br
.ti -1c
.RI "bool \fBvisited\fP (const \fBOT::LangSys\fP &l)"
.br
.ti -1c
.RI "bool \fBvisited_feature_indices\fP (unsigned count)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBOT::GSUBGPOS\fP & \fBg\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBfeature_indices\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP \fBfeature_indices_filter\fP"
.br
.ti -1c
.RI "bool \fBhas_feature_filter\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
