.TH "hb_cache_t< key_bits, value_bits, cache_bits >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_cache_t< key_bits, value_bits, cache_bits >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "bool \fBget\fP (unsigned int key, unsigned int *\fBvalue\fP) const"
.br
.ti -1c
.RI "bool \fBset\fP (unsigned int key, unsigned int \fBvalue\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
