.TH "hb_draw_state_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_draw_state_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hb\-draw\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_bool_t \fBpath_open\fP"
.br
.ti -1c
.RI "float \fBpath_start_x\fP"
.br
.ti -1c
.RI "float \fBpath_start_y\fP"
.br
.ti -1c
.RI "float \fBcurrent_x\fP"
.br
.ti -1c
.RI "float \fBcurrent_y\fP"
.br
.ti -1c
.RI "\fBhb_var_num_t\fP \fBreserved1\fP"
.br
.ti -1c
.RI "\fBhb_var_num_t\fP \fBreserved2\fP"
.br
.ti -1c
.RI "\fBhb_var_num_t\fP \fBreserved3\fP"
.br
.ti -1c
.RI "\fBhb_var_num_t\fP \fBreserved4\fP"
.br
.ti -1c
.RI "\fBhb_var_num_t\fP \fBreserved5\fP"
.br
.ti -1c
.RI "\fBhb_var_num_t\fP \fBreserved6\fP"
.br
.ti -1c
.RI "\fBhb_var_num_t\fP \fBreserved7\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBhb_draw_state_t\fP @path_open: Whether there is an open path @path_start_x: X component of the start of current path @path_start_y: Y component of the start of current path @current_x: X component of current point @current_y: Y component of current point
.PP
Current drawing state\&.
.PP
Since: 4\&.0\&.0 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
