.TH "hb_data_wrapper_t< Data, WheresData >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_data_wrapper_t< Data, WheresData >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhb_lazy_loader_t< T, hb_face_lazy_loader_t< T, WheresFace >, hb_face_t, WheresFace >\fP, \fBhb_lazy_loader_t< hb_font_funcs_t, Subclass >\fP, \fBhb_lazy_loader_t< int, hb_intp_lazy_loader_t >\fP, \fBhb_lazy_loader_t< hb_font_funcs_t, hb_ot_font_funcs_lazy_loader_t >\fP, \fBhb_lazy_loader_t< const char *, hb_shaper_list_lazy_loader_t >\fP, \fBhb_lazy_loader_t< const hb_shaper_entry_t, hb_shapers_lazy_loader_t >\fP, \fBhb_lazy_loader_t< T, hb_table_lazy_loader_t< T, WheresFace, false >, hb_face_t, WheresFace, hb_blob_t >\fP, \fBhb_lazy_loader_t< hb_unicode_funcs_t, hb_ucd_unicode_funcs_lazy_loader_t >\fP, \fBhb_lazy_loader_t< hb_unicode_funcs_t, Subclass >\fP, \fBhb_lazy_loader_t< void, hb_void_lazy_loader_t >\fP, and \fBhb_lazy_loader_t< Returned, Subclass, Data, WheresData, Stored >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Data * \fBget_data\fP () const"
.br
.ti -1c
.RI "bool \fBis_inert\fP () const"
.br
.ti -1c
.RI "template<typename Stored , typename Subclass > Stored * \fBcall_create\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
