.TH "hb_font_extents_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_font_extents_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hb\-font\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_position_t \fBascender\fP"
.br
.ti -1c
.RI "hb_position_t \fBdescender\fP"
.br
.ti -1c
.RI "hb_position_t \fBline_gap\fP"
.br
.ti -1c
.RI "hb_position_t \fBreserved9\fP"
.br
.ti -1c
.RI "hb_position_t \fBreserved8\fP"
.br
.ti -1c
.RI "hb_position_t \fBreserved7\fP"
.br
.ti -1c
.RI "hb_position_t \fBreserved6\fP"
.br
.ti -1c
.RI "hb_position_t \fBreserved5\fP"
.br
.ti -1c
.RI "hb_position_t \fBreserved4\fP"
.br
.ti -1c
.RI "hb_position_t \fBreserved3\fP"
.br
.ti -1c
.RI "hb_position_t \fBreserved2\fP"
.br
.ti -1c
.RI "hb_position_t \fBreserved1\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBhb_font_extents_t\fP: @ascender: The height of typographic ascenders\&. @descender: The depth of typographic descenders\&. @line_gap: The suggested line-spacing gap\&.
.PP
Font-wide extent values, measured in font units\&.
.PP
Note that typically @ascender is positive and @descender negative, in coordinate systems that grow up\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
