.TH "hb_feature_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_feature_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hb\-common\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_tag_t \fBtag\fP"
.br
.ti -1c
.RI "uint32_t \fBvalue\fP"
.br
.ti -1c
.RI "unsigned int \fBstart\fP"
.br
.ti -1c
.RI "unsigned int \fBend\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBhb_feature_t\fP: @tag: The hb_tag_t tag of the feature @value: The value of the feature\&. 0 disables the feature, non-zero (usually 1) enables the feature\&. For features implemented as lookup type 3 (like 'salt') the @value is a one based index into the alternates\&. @start: the cluster to start applying this feature setting (inclusive)\&. @end: the cluster to end applying this feature setting (exclusive)\&.
.PP
The \fBhb_feature_t\fP is the structure that holds information about requested feature application\&. The feature will be applied with the given value to all glyphs which are in clusters between @start (inclusive) and @end (exclusive)\&. Setting start to HB_FEATURE_GLOBAL_START and end to HB_FEATURE_GLOBAL_END specifies that the feature always applies to the entire buffer\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
