.TH "hb_face_lazy_loader_t< T, WheresFace >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_face_lazy_loader_t< T, WheresFace >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhb_lazy_loader_t< T, hb_face_lazy_loader_t< T, WheresFace >, hb_face_t, WheresFace >\fP\&.
.SS "Additional Inherited Members"


Public Types inherited from \fBhb_lazy_loader_t< T, hb_face_lazy_loader_t< T, WheresFace >, hb_face_t, WheresFace >\fP
.in +1c
.ti -1c
.RI "typedef \fBhb_non_void_t\fP< \fBhb_face_lazy_loader_t\fP< T, WheresFace >, \fBhb_lazy_loader_t\fP< T, \fBhb_face_lazy_loader_t\fP< T, WheresFace >, \fBhb_face_t\fP, WheresData, T > >\fB::value\fP \fBFuncs\fP"
.br
.in -1c

Public Member Functions inherited from \fBhb_lazy_loader_t< T, hb_face_lazy_loader_t< T, WheresFace >, hb_face_t, WheresFace >\fP
.in +1c
.ti -1c
.RI "void \fBinit0\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.ti -1c
.RI "void \fBfree_instance\fP ()"
.br
.ti -1c
.RI "const T * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "const U & \fBoperator*\fP () const"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "\fBoperator const C *\fP () const"
.br
.ti -1c
.RI "T * \fBget_stored\fP () const"
.br
.ti -1c
.RI "T * \fBget_stored_relaxed\fP () const"
.br
.ti -1c
.RI "bool \fBcmpexch\fP (T *current, T *\fBvalue\fP) const"
.br
.ti -1c
.RI "const T * \fBget\fP () const"
.br
.ti -1c
.RI "const T * \fBget_relaxed\fP () const"
.br
.ti -1c
.RI "T * \fBget_unconst\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBhb_data_wrapper_t< Data, WheresData >\fP
.in +1c
.ti -1c
.RI "Data * \fBget_data\fP () const"
.br
.ti -1c
.RI "bool \fBis_inert\fP () const"
.br
.ti -1c
.RI "template<typename Stored , typename Subclass > Stored * \fBcall_create\fP () const"
.br
.in -1c

Static Public Member Functions inherited from \fBhb_lazy_loader_t< T, hb_face_lazy_loader_t< T, WheresFace >, hb_face_t, WheresFace >\fP
.in +1c
.ti -1c
.RI "static void \fBdo_destroy\fP (T *p)"
.br
.ti -1c
.RI "static T * \fBconvert\fP (T *p)"
.br
.ti -1c
.RI "static const T * \fBget_null\fP ()"
.br
.ti -1c
.RI "static T * \fBcreate\fP (\fBhb_face_t\fP *\fBdata\fP)"
.br
.ti -1c
.RI "static T * \fBcreate\fP ()"
.br
.ti -1c
.RI "static void \fBdestroy\fP (T *p)"
.br
.in -1c

Public Attributes inherited from \fBhb_lazy_loader_t< T, hb_face_lazy_loader_t< T, WheresFace >, hb_face_t, WheresFace >\fP
.in +1c
.ti -1c
.RI "\fBhb_atomic_ptr_t\fP< T * > \fBinstance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
