.TH "hb_font_funcs_lazy_loader_t< Subclass >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_font_funcs_lazy_loader_t< Subclass >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhb_lazy_loader_t< hb_font_funcs_t, Subclass >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdestroy\fP (\fBhb_font_funcs_t\fP *p)"
.br
.ti -1c
.RI "static const \fBhb_font_funcs_t\fP * \fBget_null\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBhb_lazy_loader_t< hb_font_funcs_t, Subclass >\fP
.in +1c
.ti -1c
.RI "static void \fBdo_destroy\fP (\fBhb_font_funcs_t\fP *p)"
.br
.ti -1c
.RI "static \fBhb_font_funcs_t\fP * \fBconvert\fP (\fBhb_font_funcs_t\fP *p)"
.br
.ti -1c
.RI "static const \fBhb_font_funcs_t\fP * \fBget_null\fP ()"
.br
.ti -1c
.RI "static \fBhb_font_funcs_t\fP * \fBcreate\fP (void *\fBdata\fP)"
.br
.ti -1c
.RI "static \fBhb_font_funcs_t\fP * \fBcreate\fP ()"
.br
.ti -1c
.RI "static void \fBdestroy\fP (\fBhb_font_funcs_t\fP *p)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBhb_lazy_loader_t< hb_font_funcs_t, Subclass >\fP
.in +1c
.ti -1c
.RI "typedef \fBhb_non_void_t\fP< Subclass, \fBhb_lazy_loader_t\fP< \fBhb_font_funcs_t\fP, Subclass, void, 0, \fBhb_font_funcs_t\fP > >\fB::value\fP \fBFuncs\fP"
.br
.in -1c

Public Member Functions inherited from \fBhb_lazy_loader_t< hb_font_funcs_t, Subclass >\fP
.in +1c
.ti -1c
.RI "void \fBinit0\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.ti -1c
.RI "void \fBfree_instance\fP ()"
.br
.ti -1c
.RI "const \fBhb_font_funcs_t\fP * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "const U & \fBoperator*\fP () const"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "\fBoperator const C *\fP () const"
.br
.ti -1c
.RI "\fBhb_font_funcs_t\fP * \fBget_stored\fP () const"
.br
.ti -1c
.RI "\fBhb_font_funcs_t\fP * \fBget_stored_relaxed\fP () const"
.br
.ti -1c
.RI "bool \fBcmpexch\fP (\fBhb_font_funcs_t\fP *current, \fBhb_font_funcs_t\fP *\fBvalue\fP) const"
.br
.ti -1c
.RI "const \fBhb_font_funcs_t\fP * \fBget\fP () const"
.br
.ti -1c
.RI "const \fBhb_font_funcs_t\fP * \fBget_relaxed\fP () const"
.br
.ti -1c
.RI "\fBhb_font_funcs_t\fP * \fBget_unconst\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBhb_data_wrapper_t< Data, WheresData >\fP
.in +1c
.ti -1c
.RI "Data * \fBget_data\fP () const"
.br
.ti -1c
.RI "bool \fBis_inert\fP () const"
.br
.ti -1c
.RI "template<typename Stored , typename Subclass > Stored * \fBcall_create\fP () const"
.br
.in -1c

Public Attributes inherited from \fBhb_lazy_loader_t< hb_font_funcs_t, Subclass >\fP
.in +1c
.ti -1c
.RI "\fBhb_atomic_ptr_t\fP< \fBhb_font_funcs_t\fP * > \fBinstance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
