.TH "hb_font_funcs_t::get_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_font_funcs_t::get_t
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBget_funcs_t\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBhb_font_funcs_t::get_t::get_funcs_t\fP \fBf\fP"
.br
.ti -1c
.RI "void(* \fBarray\fP )()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
