.TH "hb_face_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_face_t
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBplan_node_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhb_blob_t\fP * \fBreference_table\fP (hb_tag_t tag) const"
.br
.ti -1c
.RI "unsigned int \fBget_upem\fP () const"
.br
.ti -1c
.RI "unsigned int \fBget_num_glyphs\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_object_header_t\fP \fBheader\fP"
.br
.ti -1c
.RI "hb_reference_table_func_t \fBreference_table_func\fP"
.br
.ti -1c
.RI "void * \fBuser_data\fP"
.br
.ti -1c
.RI "hb_destroy_func_t \fBdestroy\fP"
.br
.ti -1c
.RI "unsigned int \fBindex\fP"
.br
.ti -1c
.RI "\fBhb_atomic_int_t\fP \fBupem\fP"
.br
.ti -1c
.RI "\fBhb_atomic_int_t\fP \fBnum_glyphs\fP"
.br
.ti -1c
.RI "\fBhb_shaper_object_dataset_t\fP< \fBhb_face_t\fP > \fBdata\fP"
.br
.ti -1c
.RI "\fBhb_ot_face_t\fP \fBtable\fP"
.br
.ti -1c
.RI "\fBhb_atomic_ptr_t\fP< \fBplan_node_t\fP > \fBshape_plans\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
