.TH "hb_glyph_extents_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_glyph_extents_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hb\-font\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_position_t \fBx_bearing\fP"
.br
.ti -1c
.RI "hb_position_t \fBy_bearing\fP"
.br
.ti -1c
.RI "hb_position_t \fBwidth\fP"
.br
.ti -1c
.RI "hb_position_t \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBhb_glyph_extents_t\fP: @x_bearing: Distance from the x-origin to the left extremum of the glyph\&. @y_bearing: Distance from the top extremum of the glyph to the y-origin\&. @width: Distance from the left extremum of the glyph to the right extremum\&. @height: Distance from the top extremum of the glyph to the bottom extremum\&.
.PP
Glyph extent values, measured in font units\&.
.PP
Note that @height is negative, in coordinate systems that grow up\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
