.TH "hb_glyph_position_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_glyph_position_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hb\-buffer\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_position_t \fBx_advance\fP"
.br
.ti -1c
.RI "hb_position_t \fBy_advance\fP"
.br
.ti -1c
.RI "hb_position_t \fBx_offset\fP"
.br
.ti -1c
.RI "hb_position_t \fBy_offset\fP"
.br
.ti -1c
.RI "\fBhb_var_int_t\fP \fBvar\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBhb_glyph_position_t\fP: @x_advance: how much the line advances after drawing this glyph when setting text in horizontal direction\&. @y_advance: how much the line advances after drawing this glyph when setting text in vertical direction\&. @x_offset: how much the glyph moves on the X-axis before drawing it, this should not affect how much the line advances\&. @y_offset: how much the glyph moves on the Y-axis before drawing it, this should not affect how much the line advances\&.
.PP
The \fBhb_glyph_position_t\fP is the structure that holds the positions of the glyph in both horizontal and vertical directions\&. All positions in \fBhb_glyph_position_t\fP are relative to the current point\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
