.TH "hb_hashmap_t< K, V, k_invalid_t, v_invalid_t, kINVALID, vINVALID >::item_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_hashmap_t< K, V, k_invalid_t, v_invalid_t, kINVALID, vINVALID >::item_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const K &o)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBitem_t\fP &o)"
.br
.ti -1c
.RI "bool \fBis_unused\fP () const"
.br
.ti -1c
.RI "bool \fBis_tombstone\fP () const"
.br
.ti -1c
.RI "bool \fBis_real\fP () const"
.br
.ti -1c
.RI "\fBhb_pair_t\fP< K, V > \fBget_pair\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "K \fBkey\fP"
.br
.ti -1c
.RI "V \fBvalue\fP"
.br
.ti -1c
.RI "uint32_t \fBhash\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
