.TH "hb_int_max< unsigned long long >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_int_max< unsigned long long >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhb_integral_constant< unsigned long long, ULLONG_MAX >\fP\&.
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBhb_integral_constant< unsigned long long, ULLONG_MAX >\fP
.in +1c
.ti -1c
.RI "static constexpr unsigned long long \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
