.TH "hb_iter_fallback_mixin_t< iter_t, item_t >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_iter_fallback_mixin_t< iter_t, item_t >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhb_iter_with_fallback_t< iter_t, hb_codepoint_t >\fP, \fBhb_iter_with_fallback_t< composite_iter_t, const CompositeGlyphChain & >\fP, \fBhb_iter_with_fallback_t< array_iter_t< T >, T & >\fP, \fBhb_iter_with_fallback_t< hb_array_t< Type >, Type & >\fP, \fBhb_iter_with_fallback_t< hb_filter_iter_t< Iter, Pred, Proj >, Iter::item_t >\fP, \fBhb_iter_with_fallback_t< hb_iota_iter_t< T, S >, T >\fP, \fBhb_iter_with_fallback_t< machine_index_t< Iter >, Iter::item_t >\fP, \fBhb_iter_with_fallback_t< hb_array_t< const char >, const char & >\fP, \fBhb_iter_with_fallback_t< hb_array_t< T >, T & >\fP, and \fBhb_iter_with_fallback_t< iter_t, item_t >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "item_t \fB__item__\fP () const"
.br
.ti -1c
.RI "item_t \fB__item_at__\fP (unsigned i) const"
.br
.ti -1c
.RI "bool \fB__more__\fP () const"
.br
.ti -1c
.RI "unsigned \fB__len__\fP () const"
.br
.ti -1c
.RI "void \fB__next__\fP ()"
.br
.ti -1c
.RI "void \fB__forward__\fP (unsigned n)"
.br
.ti -1c
.RI "void \fB__prev__\fP ()"
.br
.ti -1c
.RI "void \fB__rewind__\fP (unsigned n)"
.br
.ti -1c
.RI "iter_t \fB__end__\fP () const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBhb_iter_fallback_mixin_t\fP (const \fBhb_iter_fallback_mixin_t\fP &o HB_UNUSED)=default"
.br
.ti -1c
.RI "\fBhb_iter_fallback_mixin_t\fP (\fBhb_iter_fallback_mixin_t\fP &&o HB_UNUSED)=default"
.br
.ti -1c
.RI "\fBhb_iter_fallback_mixin_t\fP & \fBoperator=\fP (const \fBhb_iter_fallback_mixin_t\fP &o HB_UNUSED)=default"
.br
.ti -1c
.RI "\fBhb_iter_fallback_mixin_t\fP & \fBoperator=\fP (\fBhb_iter_fallback_mixin_t\fP &&o HB_UNUSED)=default"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
