.TH "hb_is_same< T, T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_is_same< T, T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhb_integral_constant< T, v >\fP\&.
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBhb_integral_constant< T, v >\fP
.in +1c
.ti -1c
.RI "static constexpr T \fBvalue\fP = v"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
