.TH "hb_integral_constant< T, v >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_integral_constant< T, v >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhb_is_same< T, T2 >\fP, \fBhb_is_same< T, T >\fP, \fBhb_match_const< T >\fP, \fBhb_match_const< const T >\fP, \fBhb_match_pointer< T >\fP, \fBhb_match_pointer< T * >\fP, \fBhb_match_reference< T >\fP, \fBhb_match_reference< T & >\fP, \fBhb_match_reference< T && >\fP, and \fBstatic_assert_expr< true >\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr T \fBvalue\fP = v"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
