.TH "hb_is_iterator_of< Iter, Item >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_is_iterator_of< Iter, Item >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Item2  = Item> static \fBhb_true_type\fP \fBimpl\fP (\fBhb_priority\fP< 2 >, \fBhb_iter_t\fP< Iter, hb_type_identity< Item2 > > *)"
.br
.ti -1c
.RI "static \fBhb_false_type\fP \fBimpl\fP (\fBhb_priority\fP< 0 >, const void *)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr bool \fBvalue\fP = decltype (impl (hb_prioritize, hb_declval (Iter*)))\fB::value\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
