.TH "hb_indic_would_substitute_feature_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_indic_would_substitute_feature_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (const \fBhb_ot_map_t\fP *map, hb_tag_t feature_tag, bool zero_context_)"
.br
.ti -1c
.RI "bool \fBwould_substitute\fP (const hb_codepoint_t *glyphs, unsigned int glyphs_count, \fBhb_face_t\fP *face) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
