.TH "hb_map_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_map_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhb_hashmap_t< hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, HB_MAP_VALUE_INVALID, HB_MAP_VALUE_INVALID >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBhashmap\fP = \fBhb_hashmap_t\fP< hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, HB_MAP_VALUE_INVALID, HB_MAP_VALUE_INVALID >"
.br
.in -1c

Public Types inherited from \fBhb_hashmap_t< hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, HB_MAP_VALUE_INVALID, HB_MAP_VALUE_INVALID >\fP
.in +1c
.ti -1c
.RI "typedef hb_codepoint_t \fBvalue_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhb_map_t\fP (\fBhb_map_t\fP &)=default"
.br
.ti -1c
.RI "\fBhb_map_t\fP & \fBoperator=\fP (const \fBhb_map_t\fP &)=default"
.br
.ti -1c
.RI "\fBhb_map_t\fP & \fBoperator=\fP (\fBhb_map_t\fP &&)=default"
.br
.ti -1c
.RI "\fBhb_map_t\fP (std::initializer_list< \fBhb_pair_t\fP< hb_codepoint_t, hb_codepoint_t > > lst)"
.br
.ti -1c
.RI "template<typename Iterable , hb_requires(\fBhb_is_iterable\fP(Iterable)) > \fBhb_map_t\fP (const Iterable &o)"
.br
.in -1c

Public Member Functions inherited from \fBhb_hashmap_t< hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, HB_MAP_VALUE_INVALID, HB_MAP_VALUE_INVALID >\fP
.in +1c
.ti -1c
.RI "\fBhb_hashmap_t\fP (const \fBhb_hashmap_t\fP &o)"
.br
.ti -1c
.RI "\fBhb_hashmap_t\fP (\fBhb_hashmap_t\fP &&o)"
.br
.ti -1c
.RI "\fBhb_hashmap_t\fP (std::initializer_list< \fBhb_pair_t\fP< hb_codepoint_t, hb_codepoint_t > > lst)"
.br
.ti -1c
.RI "\fBhb_hashmap_t\fP (const Iterable &o)"
.br
.ti -1c
.RI "\fBhb_hashmap_t\fP & \fBoperator=\fP (const \fBhb_hashmap_t\fP &o)"
.br
.ti -1c
.RI "\fBhb_hashmap_t\fP & \fBoperator=\fP (\fBhb_hashmap_t\fP &&o)"
.br
.ti -1c
.RI "void \fBinit_shallow\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBfini_shallow\fP ()"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "bool \fBin_error\fP () const"
.br
.ti -1c
.RI "bool \fBresize\fP ()"
.br
.ti -1c
.RI "bool \fBset\fP (hb_codepoint_t key, const hb_codepoint_t &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBset\fP (hb_codepoint_t key, hb_codepoint_t &&\fBvalue\fP)"
.br
.ti -1c
.RI "hb_codepoint_t \fBget\fP (hb_codepoint_t key) const"
.br
.ti -1c
.RI "void \fBdel\fP (hb_codepoint_t key)"
.br
.ti -1c
.RI "value_t \fBoperator[]\fP (hb_codepoint_t k) const"
.br
.ti -1c
.RI "bool \fBhas\fP (hb_codepoint_t k, hb_codepoint_t *vp=nullptr) const"
.br
.ti -1c
.RI "hb_codepoint_t \fBoperator()\fP (hb_codepoint_t k) const"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "bool \fBis_empty\fP () const"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "unsigned int \fBget_population\fP () const"
.br
.ti -1c
.RI "auto \fBiter\fP () const HB_AUTO_RETURN(+hb_array(items"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBhb_hashmap_t< hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, HB_MAP_VALUE_INVALID, HB_MAP_VALUE_INVALID >\fP
.in +1c
.ti -1c
.RI "\fBhb_object_header_t\fP \fBheader\fP"
.br
.ti -1c
.RI "bool \fBsuccessful\fP"
.br
.ti -1c
.RI "unsigned int \fBpopulation\fP"
.br
.ti -1c
.RI "unsigned int \fBoccupancy\fP"
.br
.ti -1c
.RI "unsigned int \fBmask\fP"
.br
.ti -1c
.RI "auto mask \fBmask\fP"
.br
.ti -1c
.RI "auto mask mask \fBmask\fP"
.br
.ti -1c
.RI "auto mask mask mask \fBmask\fP"
.br
.ti -1c
.RI "unsigned int \fBprime\fP"
.br
.ti -1c
.RI "item_t * \fBitems\fP"
.br
.ti -1c
.RI "auto mask mask mask hb_codepoint_t & \fBv\fP"
.br
.ti -1c
.RI "return * \fBthis\fP"
.br
.in -1c

Protected Member Functions inherited from \fBhb_hashmap_t< hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, HB_MAP_VALUE_INVALID, HB_MAP_VALUE_INVALID >\fP
.in +1c
.ti -1c
.RI "bool \fBset_with_hash\fP (hb_codepoint_t key, uint32_t hash, VV &&\fBvalue\fP)"
.br
.ti -1c
.RI "unsigned int \fBbucket_for\fP (hb_codepoint_t key) const"
.br
.ti -1c
.RI "unsigned int \fBbucket_for_hash\fP (hb_codepoint_t key, uint32_t hash) const"
.br
.in -1c

Static Protected Member Functions inherited from \fBhb_hashmap_t< hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, hb_codepoint_t, HB_MAP_VALUE_INVALID, HB_MAP_VALUE_INVALID >\fP
.in +1c
.ti -1c
.RI "static unsigned int \fBprime_for\fP (unsigned int shift)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
