.TH "hb_map_iter_factory_t< Proj, Sorted >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_map_iter_factory_t< Proj, Sorted >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhb_map_iter_factory_t\fP (Proj f)"
.br
.ti -1c
.RI "template<typename Iter , hb_requires(hb_is_iterator(Iter)) > hb_map_iter_t< Iter, Proj, Sorted > \fBoperator()\fP (Iter it)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
