.TH "hb_match_const< T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_match_const< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhb_type_identity_t< T >\fP, and \fBhb_integral_constant< T, v >\fP\&.
.SS "Additional Inherited Members"


Public Types inherited from \fBhb_type_identity_t< T >\fP
.in +1c
.ti -1c
.RI "typedef T \fBtype\fP"
.br
.in -1c

Static Public Attributes inherited from \fBhb_integral_constant< T, v >\fP
.in +1c
.ti -1c
.RI "static constexpr T \fBvalue\fP = v"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
