.TH "hb_ot_shape_plan_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_shape_plan_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcollect_lookups\fP (hb_tag_t table_tag, \fBhb_set_t\fP *lookups) const"
.br
.ti -1c
.RI "HB_INTERNAL bool \fBinit0\fP (\fBhb_face_t\fP *face, const \fBhb_shape_plan_key_t\fP *key)"
.br
.ti -1c
.RI "HB_INTERNAL void \fBfini\fP ()"
.br
.ti -1c
.RI "HB_INTERNAL void \fBsubstitute\fP (\fBhb_font_t\fP *font, \fBhb_buffer_t\fP *\fBbuffer\fP) const"
.br
.ti -1c
.RI "HB_INTERNAL void \fBposition\fP (\fBhb_font_t\fP *font, \fBhb_buffer_t\fP *\fBbuffer\fP) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_segment_properties_t\fP \fBprops\fP"
.br
.ti -1c
.RI "const struct \fBhb_ot_complex_shaper_t\fP * \fBshaper\fP"
.br
.ti -1c
.RI "\fBhb_ot_map_t\fP \fBmap\fP"
.br
.ti -1c
.RI "\fBhb_aat_map_t\fP \fBaat_map\fP"
.br
.ti -1c
.RI "const void * \fBdata\fP"
.br
.ti -1c
.RI "hb_mask_t \fBfrac_mask\fP"
.br
.ti -1c
.RI "hb_mask_t \fBnumr_mask\fP"
.br
.ti -1c
.RI "hb_mask_t \fBdnom_mask\fP"
.br
.ti -1c
.RI "hb_mask_t \fBrtlm_mask\fP"
.br
.ti -1c
.RI "hb_mask_t \fBkern_mask\fP"
.br
.ti -1c
.RI "hb_mask_t \fBtrak_mask\fP"
.br
.ti -1c
.RI "bool \fBrequested_kerning\fP: 1"
.br
.ti -1c
.RI "bool \fBrequested_tracking\fP: 1"
.br
.ti -1c
.RI "bool \fBhas_frac\fP: 1"
.br
.ti -1c
.RI "bool \fBhas_vert\fP: 1"
.br
.ti -1c
.RI "bool \fBhas_gpos_mark\fP: 1"
.br
.ti -1c
.RI "bool \fBzero_marks\fP: 1"
.br
.ti -1c
.RI "bool \fBfallback_glyph_classes\fP: 1"
.br
.ti -1c
.RI "bool \fBfallback_mark_positioning\fP: 1"
.br
.ti -1c
.RI "bool \fBadjust_mark_positioning_when_zeroing\fP: 1"
.br
.ti -1c
.RI "bool \fBapply_gpos\fP: 1"
.br
.ti -1c
.RI "bool \fBapply_kern\fP: 1"
.br
.ti -1c
.RI "bool \fBapply_fallback_kern\fP: 1"
.br
.ti -1c
.RI "bool \fBapply_kerx\fP: 1"
.br
.ti -1c
.RI "bool \fBapply_morx\fP: 1"
.br
.ti -1c
.RI "bool \fBapply_trak\fP: 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
