.TH "hb_ot_map_t::lookup_map_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_map_t::lookup_map_t
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static HB_INTERNAL int \fBcmp\fP (const void *pa, const void *pb)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBindex\fP"
.br
.ti -1c
.RI "unsigned short \fBauto_zwnj\fP: 1"
.br
.ti -1c
.RI "unsigned short \fBauto_zwj\fP: 1"
.br
.ti -1c
.RI "unsigned short \fBrandom\fP: 1"
.br
.ti -1c
.RI "hb_mask_t \fBmask\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
