.TH "hb_ot_name_entry_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_name_entry_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hb\-ot\-name\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_ot_name_id_t \fBname_id\fP"
.br
.ti -1c
.RI "\fBhb_var_int_t\fP \fBvar\fP"
.br
.ti -1c
.RI "\fBhb_language_t\fP \fBlanguage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBhb_ot_name_entry_t\fP: @name_id: name ID @language: language
.PP
Structure representing a name ID in a particular language\&.
.PP
Since: 2\&.1\&.0 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
