.TH "hb_ot_map_t::feature_map_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_map_t::feature_map_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcmp\fP (const hb_tag_t tag_) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_tag_t \fBtag\fP"
.br
.ti -1c
.RI "unsigned int \fBindex\fP [2]"
.br
.ti -1c
.RI "unsigned int \fBstage\fP [2]"
.br
.ti -1c
.RI "unsigned int \fBshift\fP"
.br
.ti -1c
.RI "hb_mask_t \fBmask\fP"
.br
.ti -1c
.RI "hb_mask_t \fB_1_mask\fP"
.br
.ti -1c
.RI "unsigned int \fBneeds_fallback\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBauto_zwnj\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBauto_zwj\fP: 1"
.br
.ti -1c
.RI "unsigned int \fBrandom\fP: 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
