.TH "hb_object_header_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_object_header_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBis_inert\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_reference_count_t\fP \fBref_count\fP"
.br
.ti -1c
.RI "\fBhb_atomic_int_t\fP \fBwritable\fP = 0"
.br
.ti -1c
.RI "\fBhb_atomic_ptr_t\fP< \fBhb_user_data_array_t\fP > \fBuser_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
