.TH "hb_ot_math_glyph_part_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_math_glyph_part_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hb\-ot\-math\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_codepoint_t \fBglyph\fP"
.br
.ti -1c
.RI "hb_position_t \fBstart_connector_length\fP"
.br
.ti -1c
.RI "hb_position_t \fBend_connector_length\fP"
.br
.ti -1c
.RI "hb_position_t \fBfull_advance\fP"
.br
.ti -1c
.RI "hb_ot_math_glyph_part_flags_t \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBhb_ot_math_glyph_part_t\fP: @glyph: The glyph index of the variant part @start_connector_length: The length of the connector on the starting side of the variant part @end_connector_length: The length of the connector on the ending side of the variant part @full_advance: The total advance of the part @flags: hb_ot_math_glyph_part_flags_t flags for the part
.PP
Data type to hold information for a 'part' component of a math-variant glyph\&. \fBLarge\fP variants for stretchable math glyphs (such as parentheses) can be constructed on the fly from parts\&.
.PP
Since: 1\&.3\&.3 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
