.TH "hb_ot_var_axis_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_var_axis_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hb\-ot\-deprecated\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_tag_t \fBtag\fP"
.br
.ti -1c
.RI "hb_ot_name_id_t \fBname_id\fP"
.br
.ti -1c
.RI "float \fBmin_value\fP"
.br
.ti -1c
.RI "float \fBdefault_value\fP"
.br
.ti -1c
.RI "float \fBmax_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBhb_ot_var_axis_t\fP: @tag: axis tag @name_id: axis name identifier @min_value: minimum value of the axis @default_value: default value of the axis @max_value: maximum value of the axis
.PP
Use \fBhb_ot_var_axis_info_t\fP instead\&.
.PP
Since: 1\&.4\&.2 Deprecated: 2\&.2\&.0 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
