.TH "hb_ot_shape_plan_key_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_shape_plan_key_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (\fBhb_face_t\fP *face, const int *coords, unsigned num_coords)"
.br
.ti -1c
.RI "bool \fBequal\fP (const \fBhb_ot_shape_plan_key_t\fP *other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBvariations_index\fP [2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
