.TH "hb_ot_shape_fallback_kern_driver_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_shape_fallback_kern_driver_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhb_ot_shape_fallback_kern_driver_t\fP (\fBhb_font_t\fP *font_, \fBhb_buffer_t\fP *\fBbuffer\fP)"
.br
.ti -1c
.RI "hb_position_t \fBget_kerning\fP (hb_codepoint_t first, hb_codepoint_t second) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_font_t\fP * \fBfont\fP"
.br
.ti -1c
.RI "hb_direction_t \fBdirection\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
