.TH "hb_ot_complex_shaper_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_complex_shaper_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBcollect_features\fP )(\fBhb_ot_shape_planner_t\fP *plan)"
.br
.ti -1c
.RI "void(* \fBoverride_features\fP )(\fBhb_ot_shape_planner_t\fP *plan)"
.br
.ti -1c
.RI "void *(* \fBdata_create\fP )(const \fBhb_ot_shape_plan_t\fP *plan)"
.br
.ti -1c
.RI "void(* \fBdata_destroy\fP )(void *\fBdata\fP)"
.br
.ti -1c
.RI "void(* \fBpreprocess_text\fP )(const \fBhb_ot_shape_plan_t\fP *plan, \fBhb_buffer_t\fP *\fBbuffer\fP, \fBhb_font_t\fP *font)"
.br
.ti -1c
.RI "void(* \fBpostprocess_glyphs\fP )(const \fBhb_ot_shape_plan_t\fP *plan, \fBhb_buffer_t\fP *\fBbuffer\fP, \fBhb_font_t\fP *font)"
.br
.ti -1c
.RI "hb_ot_shape_normalization_mode_t \fBnormalization_preference\fP"
.br
.ti -1c
.RI "bool(* \fBdecompose\fP )(const \fBhb_ot_shape_normalize_context_t\fP *c, hb_codepoint_t ab, hb_codepoint_t *\fBa\fP, hb_codepoint_t *b)"
.br
.ti -1c
.RI "bool(* \fBcompose\fP )(const \fBhb_ot_shape_normalize_context_t\fP *c, hb_codepoint_t \fBa\fP, hb_codepoint_t b, hb_codepoint_t *ab)"
.br
.ti -1c
.RI "void(* \fBsetup_masks\fP )(const \fBhb_ot_shape_plan_t\fP *plan, \fBhb_buffer_t\fP *\fBbuffer\fP, \fBhb_font_t\fP *font)"
.br
.ti -1c
.RI "hb_tag_t \fBgpos_tag\fP"
.br
.ti -1c
.RI "void(* \fBreorder_marks\fP )(const \fBhb_ot_shape_plan_t\fP *plan, \fBhb_buffer_t\fP *\fBbuffer\fP, unsigned int start, unsigned int end)"
.br
.ti -1c
.RI "hb_ot_shape_zero_width_marks_type_t \fBzero_width_marks\fP"
.br
.ti -1c
.RI "bool \fBfallback_position\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
