.TH "hb_ot_map_builder_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_map_builder_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "HB_INTERNAL \fBhb_ot_map_builder_t\fP (\fBhb_face_t\fP *face_, const \fBhb_segment_properties_t\fP *props_)"
.br
.ti -1c
.RI "HB_INTERNAL void \fBadd_feature\fP (hb_tag_t tag, hb_ot_map_feature_flags_t flags=F_NONE, unsigned int \fBvalue\fP=1)"
.br
.ti -1c
.RI "void \fBadd_feature\fP (const \fBhb_ot_map_feature_t\fP &\fBfeat\fP)"
.br
.ti -1c
.RI "void \fBenable_feature\fP (hb_tag_t tag, hb_ot_map_feature_flags_t flags=F_NONE, unsigned int \fBvalue\fP=1)"
.br
.ti -1c
.RI "void \fBdisable_feature\fP (hb_tag_t tag)"
.br
.ti -1c
.RI "void \fBadd_gsub_pause\fP (hb_ot_map_t::pause_func_t pause_func)"
.br
.ti -1c
.RI "void \fBadd_gpos_pause\fP (hb_ot_map_t::pause_func_t pause_func)"
.br
.ti -1c
.RI "HB_INTERNAL void \fBcompile\fP (\fBhb_ot_map_t\fP &m, const \fBhb_ot_shape_plan_key_t\fP &key)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_face_t\fP * \fBface\fP"
.br
.ti -1c
.RI "\fBhb_segment_properties_t\fP \fBprops\fP"
.br
.ti -1c
.RI "hb_tag_t \fBchosen_script\fP [2]"
.br
.ti -1c
.RI "bool \fBfound_script\fP [2]"
.br
.ti -1c
.RI "unsigned int \fBscript_index\fP [2]"
.br
.ti -1c
.RI "unsigned int \fBlanguage_index\fP [2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
