.TH "hb_ot_color_layer_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_color_layer_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hb\-ot\-color\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_codepoint_t \fBglyph\fP"
.br
.ti -1c
.RI "unsigned int \fBcolor_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBhb_ot_color_layer_t\fP: @glyph: the glyph ID of the layer @color_index: the palette color index of the layer
.PP
Pairs of glyph and color index\&.
.PP
Since: 2\&.1\&.0 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
