.TH "hb_ot_shape_context_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_shape_context_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_ot_shape_plan_t\fP * \fBplan\fP"
.br
.ti -1c
.RI "\fBhb_font_t\fP * \fBfont\fP"
.br
.ti -1c
.RI "\fBhb_face_t\fP * \fBface\fP"
.br
.ti -1c
.RI "\fBhb_buffer_t\fP * \fBbuffer\fP"
.br
.ti -1c
.RI "const \fBhb_feature_t\fP * \fBuser_features\fP"
.br
.ti -1c
.RI "unsigned int \fBnum_user_features\fP"
.br
.ti -1c
.RI "hb_direction_t \fBtarget_direction\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
