.TH "hb_ot_var_axis_info_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_var_axis_info_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hb\-ot\-var\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBaxis_index\fP"
.br
.ti -1c
.RI "hb_tag_t \fBtag\fP"
.br
.ti -1c
.RI "hb_ot_name_id_t \fBname_id\fP"
.br
.ti -1c
.RI "hb_ot_var_axis_flags_t \fBflags\fP"
.br
.ti -1c
.RI "float \fBmin_value\fP"
.br
.ti -1c
.RI "float \fBdefault_value\fP"
.br
.ti -1c
.RI "float \fBmax_value\fP"
.br
.ti -1c
.RI "unsigned int \fBreserved\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBhb_ot_var_axis_info_t\fP: @axis_index: Index of the axis in the variation-axis array @tag: The hb_tag_t tag identifying the design variation of the axis @name_id: The \fCname\fP table Name ID that provides display names for the axis @flags: The hb_ot_var_axis_flags_t flags for the axis @min_value: The minimum value on the variation axis that the font covers @default_value: The position on the variation axis corresponding to the font's defaults @max_value: The maximum value on the variation axis that the font covers
.PP
Data type for holding variation-axis values\&.
.PP
The minimum, default, and maximum values are in un-normalized, user scales\&.
.PP
<note>Note: at present, the only flag defined for @flags is HB_OT_VAR_AXIS_FLAG_HIDDEN\&.</note>
.PP
Since: 2\&.2\&.0 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
