.TH "hb_ot_map_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_ot_map_t
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBfeature_map_t\fP"
.br
.ti -1c
.RI "struct \fBlookup_map_t\fP"
.br
.ti -1c
.RI "struct \fBstage_map_t\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void(* \fBpause_func_t\fP) (const struct \fBhb_ot_shape_plan_t\fP *plan, \fBhb_font_t\fP *font, \fBhb_buffer_t\fP *\fBbuffer\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.ti -1c
.RI "hb_mask_t \fBget_global_mask\fP () const"
.br
.ti -1c
.RI "hb_mask_t \fBget_mask\fP (hb_tag_t feature_tag, unsigned int *shift=nullptr) const"
.br
.ti -1c
.RI "bool \fBneeds_fallback\fP (hb_tag_t feature_tag) const"
.br
.ti -1c
.RI "hb_mask_t \fBget_1_mask\fP (hb_tag_t feature_tag) const"
.br
.ti -1c
.RI "unsigned int \fBget_feature_index\fP (unsigned int table_index, hb_tag_t feature_tag) const"
.br
.ti -1c
.RI "unsigned int \fBget_feature_stage\fP (unsigned int table_index, hb_tag_t feature_tag) const"
.br
.ti -1c
.RI "void \fBget_stage_lookups\fP (unsigned int table_index, unsigned int stage, const struct \fBlookup_map_t\fP **plookups, unsigned int *lookup_count) const"
.br
.ti -1c
.RI "HB_INTERNAL void \fBcollect_lookups\fP (unsigned int table_index, \fBhb_set_t\fP *lookups) const"
.br
.ti -1c
.RI "template<typename Proxy > HB_INTERNAL void \fBapply\fP (const Proxy &proxy, const struct \fBhb_ot_shape_plan_t\fP *plan, \fBhb_font_t\fP *font, \fBhb_buffer_t\fP *\fBbuffer\fP) const"
.br
.ti -1c
.RI "HB_INTERNAL void \fBsubstitute\fP (const struct \fBhb_ot_shape_plan_t\fP *plan, \fBhb_font_t\fP *font, \fBhb_buffer_t\fP *\fBbuffer\fP) const"
.br
.ti -1c
.RI "HB_INTERNAL void \fBposition\fP (const struct \fBhb_ot_shape_plan_t\fP *plan, \fBhb_font_t\fP *font, \fBhb_buffer_t\fP *\fBbuffer\fP) const"
.br
.ti -1c
.RI "template<typename Proxy > void \fBapply\fP (const Proxy &proxy, const \fBhb_ot_shape_plan_t\fP *plan, \fBhb_font_t\fP *font, \fBhb_buffer_t\fP *\fBbuffer\fP) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_tag_t \fBchosen_script\fP [2]"
.br
.ti -1c
.RI "bool \fBfound_script\fP [2]"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "struct \fBhb_ot_map_builder_t\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
