.TH "hb_pair_t< T1, T2 >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_pair_t< T1, T2 >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T1 \fBfirst_t\fP"
.br
.ti -1c
.RI "typedef T2 \fBsecond_t\fP"
.br
.ti -1c
.RI "typedef \fBhb_pair_t\fP< T1, T2 > \fBpair_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhb_pair_t\fP (T1 \fBa\fP, T2 b)"
.br
.ti -1c
.RI "template<typename Q1 , typename Q2 , \fBhb_enable_if\fP(hb_is_convertible(T1, Q1) && hb_is_convertible(T2, Q2)) > \fBoperator hb_pair_t< Q1, Q2 >\fP ()"
.br
.ti -1c
.RI "\fBhb_pair_t\fP< T1, T2 > \fBreverse\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBpair_t\fP &o) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBpair_t\fP &o) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBpair_t\fP &o) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBpair_t\fP &o) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBpair_t\fP &o) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBpair_t\fP &o) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T1 \fBfirst\fP"
.br
.ti -1c
.RI "T2 \fBsecond\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
