.TH "hb_partial_t< Pos, Appl, V >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_partial_t< Pos, Appl, V >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhb_partial_t\fP (Appl \fBa\fP, V v)"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Ts, unsigned P = Pos, \fBhb_enable_if\fP(P==1) > auto \fBoperator()\fP (Ts &&\&.\&.\&.ds) \-> decltype(hb_invoke(hb_declval(Appl), hb_declval(V), hb_declval(Ts)\&.\&.\&.))"
.br
.ti -1c
.RI "template<typename T0 , typename \&.\&.\&. Ts, unsigned P = Pos, \fBhb_enable_if\fP(P==2) > auto \fBoperator()\fP (T0 &&d0, Ts &&\&.\&.\&.ds) \-> decltype(hb_invoke(hb_declval(Appl), hb_declval(T0), hb_declval(V), hb_declval(Ts)\&.\&.\&.))"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
