.TH "hb_reference_count_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_reference_count_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP (int v=1)"
.br
.ti -1c
.RI "int \fBget_relaxed\fP () const"
.br
.ti -1c
.RI "int \fBinc\fP () const"
.br
.ti -1c
.RI "int \fBdec\fP () const"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.ti -1c
.RI "bool \fBis_inert\fP () const"
.br
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_atomic_int_t\fP \fBref_count\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
