.TH "hb_serialize_context_t::object_t::link_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_serialize_context_t::object_t::link_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBwidth\fP: 3"
.br
.ti -1c
.RI "bool \fBis_signed\fP: 1"
.br
.ti -1c
.RI "unsigned \fBwhence\fP: 2"
.br
.ti -1c
.RI "unsigned \fBposition\fP: 28"
.br
.ti -1c
.RI "unsigned \fBbias\fP"
.br
.ti -1c
.RI "objidx_t \fBobjidx\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
