.TH "hb_subset_input_t::sets_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_subset_input_t::sets_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_set_t\fP * \fBglyphs\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBunicodes\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBno_subset_tables\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBdrop_tables\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBname_ids\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBname_languages\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBlayout_features\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
