.TH "hb_serialize_context_t::object_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_serialize_context_t::object_t
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlink_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBfini\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBobject_t\fP &o) const"
.br
.ti -1c
.RI "uint32_t \fBhash\fP () const"
.br
.ti -1c
.RI "auto \fBall_links\fP () const HB_AUTO_RETURN((hb_concat(this \-> real_links, this\->virtual_links)))"
.br
.ti -1c
.RI "auto \fBall_links_writer\fP () HB_AUTO_RETURN((hb_concat(this \-> real_links\&.writer(), this\->virtual_links\&.writer())))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBhead\fP"
.br
.ti -1c
.RI "char * \fBtail\fP"
.br
.ti -1c
.RI "\fBhb_vector_t\fP< \fBlink_t\fP > \fBreal_links\fP"
.br
.ti -1c
.RI "\fBhb_vector_t\fP< \fBlink_t\fP > \fBvirtual_links\fP"
.br
.ti -1c
.RI "\fBobject_t\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
