.TH "hb_shape_plan_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_shape_plan_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_object_header_t\fP \fBheader\fP"
.br
.ti -1c
.RI "\fBhb_face_t\fP * \fBface_unsafe\fP"
.br
.ti -1c
.RI "\fBhb_shape_plan_key_t\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBhb_ot_shape_plan_t\fP \fBot\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
