.TH "hb_subset_input_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_subset_input_t
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsets_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "unsigned \fBnum_sets\fP () const"
.br
.ti -1c
.RI "\fBhb_array_t\fP< \fBhb_set_t\fP * > \fBsets_iter\fP ()"
.br
.ti -1c
.RI "bool \fBin_error\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_object_header_t\fP \fBheader\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBsets_t\fP \fBsets\fP"
.br
.ti -1c
.RI "   \fBhb_set_t\fP * \fBset_ptrs\fP [sizeof(\fBsets_t\fP)/sizeof(\fBhb_set_t\fP *)]"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "unsigned \fBflags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
