.TH "hb_subset_plan_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_subset_plan_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBin_error\fP () const"
.br
.ti -1c
.RI "bool \fBcheck_success\fP (bool success)"
.br
.ti -1c
.RI "const \fBhb_set_t\fP * \fBglyphset\fP () const"
.br
.ti -1c
.RI "const \fBhb_set_t\fP * \fBglyphset_gsub\fP () const"
.br
.ti -1c
.RI "unsigned int \fBnum_output_glyphs\fP () const"
.br
.ti -1c
.RI "bool \fBis_empty_glyph\fP (hb_codepoint_t gid) const"
.br
.ti -1c
.RI "bool \fBnew_gid_for_codepoint\fP (hb_codepoint_t codepoint, hb_codepoint_t *new_gid) const"
.br
.ti -1c
.RI "bool \fBnew_gid_for_old_gid\fP (hb_codepoint_t old_gid, hb_codepoint_t *new_gid) const"
.br
.ti -1c
.RI "bool \fBold_gid_for_new_gid\fP (hb_codepoint_t new_gid, hb_codepoint_t *old_gid) const"
.br
.ti -1c
.RI "bool \fBadd_table\fP (hb_tag_t tag, \fBhb_blob_t\fP *\fBcontents\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_object_header_t\fP \fBheader\fP"
.br
.ti -1c
.RI "bool \fBsuccessful\fP"
.br
.ti -1c
.RI "unsigned \fBflags\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBunicodes\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBname_ids\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBname_languages\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBlayout_features\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBglyphs_requested\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBno_subset_tables\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBdrop_tables\fP"
.br
.ti -1c
.RI "\fBhb_map_t\fP * \fBcodepoint_to_glyph\fP"
.br
.ti -1c
.RI "\fBhb_map_t\fP * \fBglyph_map\fP"
.br
.ti -1c
.RI "\fBhb_map_t\fP * \fBreverse_glyph_map\fP"
.br
.ti -1c
.RI "\fBhb_face_t\fP * \fBsource\fP"
.br
.ti -1c
.RI "\fBhb_face_t\fP * \fBdest\fP"
.br
.ti -1c
.RI "unsigned int \fB_num_output_glyphs\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fB_glyphset\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fB_glyphset_gsub\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fB_glyphset_mathed\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fB_glyphset_colred\fP"
.br
.ti -1c
.RI "\fBhb_map_t\fP * \fBgsub_lookups\fP"
.br
.ti -1c
.RI "\fBhb_map_t\fP * \fBgpos_lookups\fP"
.br
.ti -1c
.RI "\fBhb_hashmap_t\fP< unsigned, \fBhb_set_t\fP * > * \fBgsub_langsys\fP"
.br
.ti -1c
.RI "\fBhb_hashmap_t\fP< unsigned, \fBhb_set_t\fP * > * \fBgpos_langsys\fP"
.br
.ti -1c
.RI "\fBhb_map_t\fP * \fBgsub_features\fP"
.br
.ti -1c
.RI "\fBhb_map_t\fP * \fBgpos_features\fP"
.br
.ti -1c
.RI "\fBhb_map_t\fP * \fBcolrv1_layers\fP"
.br
.ti -1c
.RI "\fBhb_map_t\fP * \fBcolr_palettes\fP"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBlayout_variation_indices\fP"
.br
.ti -1c
.RI "\fBhb_map_t\fP * \fBlayout_variation_idx_map\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
