.TH "hb_subset_context_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_subset_context_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhb_dispatch_context_t< hb_subset_context_t, bool, HB_DEBUG_SUBSET >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const char * \fBget_name\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBhb_dispatch_context_t< hb_subset_context_t, bool, HB_DEBUG_SUBSET >\fP
.in +1c
.ti -1c
.RI "const char * \fBget_name\fP ()"
.br
.ti -1c
.RI "bool \fBmay_dispatch\fP (const T *obj HB_UNUSED, const F *format HB_UNUSED)"
.br
.ti -1c
.RI "return_t \fBdispatch\fP (const T &obj, Ts &&\&.\&.\&. ds)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static return_t \fBdefault_return_value\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBhb_dispatch_context_t< hb_subset_context_t, bool, HB_DEBUG_SUBSET >\fP
.in +1c
.ti -1c
.RI "static return_t \fBno_dispatch_return_value\fP ()"
.br
.ti -1c
.RI "static bool \fBstop_sublookup_iteration\fP (const return_t r HB_UNUSED)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBhb_dispatch_context_t< hb_subset_context_t, bool, HB_DEBUG_SUBSET >\fP
.in +1c
.ti -1c
.RI "typedef bool \fBreturn_t\fP"
.br
.in -1c

Public Attributes inherited from \fBhb_dispatch_context_t< hb_subset_context_t, bool, HB_DEBUG_SUBSET >\fP
.in +1c
.ti -1c
.RI "unsigned \fBdebug_depth\fP"
.br
.in -1c

Static Public Attributes inherited from \fBhb_dispatch_context_t< hb_subset_context_t, bool, HB_DEBUG_SUBSET >\fP
.in +1c
.ti -1c
.RI "static constexpr unsigned \fBmax_debug_depth\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
