.TH "hb_type_identity_t< T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_type_identity_t< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fB_hb_unwrap_type< T::type, void >\fP, \fB_hb_unwrap_type< T, typename >\fP, \fBhb_match_const< T >\fP, \fBhb_match_const< const T >\fP, \fBhb_match_pointer< T >\fP, \fBhb_match_pointer< T * >\fP, \fBhb_match_reference< T >\fP, \fBhb_match_reference< T & >\fP, and \fBhb_match_reference< T && >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
