.TH "hb_trampoline_t< FuncType >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_trampoline_t< FuncType >
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_trampoline_closure_t\fP \fBclosure\fP"
.br
.ti -1c
.RI "FuncType \fBfunc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
