.TH "hb_table_lazy_loader_t< T, WheresFace, core >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_table_lazy_loader_t< T, WheresFace, core >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBhb_lazy_loader_t< Returned, Subclass, Data, WheresData, Stored >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhb_blob_t\fP * \fBget_blob\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBhb_lazy_loader_t< Returned, Subclass, Data, WheresData, Stored >\fP
.in +1c
.ti -1c
.RI "void \fBinit0\fP ()"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.ti -1c
.RI "void \fBfree_instance\fP ()"
.br
.ti -1c
.RI "const Returned * \fBoperator\->\fP () const"
.br
.ti -1c
.RI "template<typename U  = Returned, \fBhb_enable_if\fP(!\fBhb_is_same\fP(U, void)) > const U & \fBoperator*\fP () const"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "template<typename C > \fBoperator const C *\fP () const"
.br
.ti -1c
.RI "Stored * \fBget_stored\fP () const"
.br
.ti -1c
.RI "Stored * \fBget_stored_relaxed\fP () const"
.br
.ti -1c
.RI "bool \fBcmpexch\fP (Stored *current, Stored *\fBvalue\fP) const"
.br
.ti -1c
.RI "const Returned * \fBget\fP () const"
.br
.ti -1c
.RI "const Returned * \fBget_relaxed\fP () const"
.br
.ti -1c
.RI "Returned * \fBget_unconst\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBhb_data_wrapper_t< Data, WheresData >\fP
.in +1c
.ti -1c
.RI "Data * \fBget_data\fP () const"
.br
.ti -1c
.RI "bool \fBis_inert\fP () const"
.br
.ti -1c
.RI "template<typename Stored , typename Subclass > Stored * \fBcall_create\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBhb_blob_t\fP * \fBcreate\fP (\fBhb_face_t\fP *face)"
.br
.ti -1c
.RI "static void \fBdestroy\fP (\fBhb_blob_t\fP *p)"
.br
.ti -1c
.RI "static const \fBhb_blob_t\fP * \fBget_null\fP ()"
.br
.ti -1c
.RI "static const T * \fBconvert\fP (const \fBhb_blob_t\fP *blob)"
.br
.in -1c

Static Public Member Functions inherited from \fBhb_lazy_loader_t< Returned, Subclass, Data, WheresData, Stored >\fP
.in +1c
.ti -1c
.RI "static void \fBdo_destroy\fP (Stored *p)"
.br
.ti -1c
.RI "static Returned * \fBconvert\fP (Stored *p)"
.br
.ti -1c
.RI "static const Stored * \fBget_null\fP ()"
.br
.ti -1c
.RI "static Stored * \fBcreate\fP (Data *\fBdata\fP)"
.br
.ti -1c
.RI "static Stored * \fBcreate\fP ()"
.br
.ti -1c
.RI "static void \fBdestroy\fP (Stored *p)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBhb_lazy_loader_t< Returned, Subclass, Data, WheresData, Stored >\fP
.in +1c
.ti -1c
.RI "typedef \fBhb_non_void_t\fP< Subclass, \fBhb_lazy_loader_t\fP< Returned, Subclass, Data, WheresData, Stored > >\fB::value\fP \fBFuncs\fP"
.br
.in -1c

Public Attributes inherited from \fBhb_lazy_loader_t< Returned, Subclass, Data, WheresData, Stored >\fP
.in +1c
.ti -1c
.RI "\fBhb_atomic_ptr_t\fP< Stored * > \fBinstance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
