.TH "hb_utf8_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_utf8_t
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef uint8_t \fBcodepoint_t\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const codepoint_t * \fBnext\fP (const codepoint_t *text, const codepoint_t *end, hb_codepoint_t *unicode, hb_codepoint_t replacement)"
.br
.ti -1c
.RI "static const codepoint_t * \fBprev\fP (const codepoint_t *text, const codepoint_t *start, hb_codepoint_t *unicode, hb_codepoint_t replacement)"
.br
.ti -1c
.RI "static unsigned int \fBstrlen\fP (const codepoint_t *text)"
.br
.ti -1c
.RI "static unsigned int \fBencode_len\fP (hb_codepoint_t unicode)"
.br
.ti -1c
.RI "static codepoint_t * \fBencode\fP (codepoint_t *text, const codepoint_t *end, hb_codepoint_t unicode)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
