.TH "hb_user_data_array_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_user_data_array_t
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBhb_user_data_item_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "HB_INTERNAL bool \fBset\fP (\fBhb_user_data_key_t\fP *key, void *\fBdata\fP, hb_destroy_func_t destroy, hb_bool_t replace)"
.br
.ti -1c
.RI "HB_INTERNAL void * \fBget\fP (\fBhb_user_data_key_t\fP *key)"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_mutex_t\fP \fBlock\fP"
.br
.ti -1c
.RI "\fBhb_lockable_set_t\fP< \fBhb_user_data_item_t\fP, \fBhb_mutex_t\fP > \fBitems\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
