.TH "hb_unicode_funcs_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_unicode_funcs_t
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBspace_t\fP { \fBNOT_SPACE\fP = 0, \fBSPACE_EM\fP = 1, \fBSPACE_EM_2\fP = 2, \fBSPACE_EM_3\fP = 3, \fBSPACE_EM_4\fP = 4, \fBSPACE_EM_5\fP = 5, \fBSPACE_EM_6\fP = 6, \fBSPACE_EM_16\fP = 16, \fBSPACE_4_EM_18\fP, \fBSPACE\fP, \fBSPACE_FIGURE\fP, \fBSPACE_PUNCTUATION\fP, \fBSPACE_NARROW\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "HB_UNICODE_FUNCS_IMPLEMENT_CALLBACKS_SIMPLE hb_bool_t \fBcompose\fP (hb_codepoint_t \fBa\fP, hb_codepoint_t b, hb_codepoint_t *ab)"
.br
.ti -1c
.RI "hb_bool_t \fBdecompose\fP (hb_codepoint_t ab, hb_codepoint_t *\fBa\fP, hb_codepoint_t *b)"
.br
.ti -1c
.RI "unsigned int \fBdecompose_compatibility\fP (hb_codepoint_t u, hb_codepoint_t *decomposed)"
.br
.ti -1c
.RI "unsigned int \fBmodified_combining_class\fP (hb_codepoint_t u)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static hb_bool_t \fBis_variation_selector\fP (hb_codepoint_t unicode)"
.br
.ti -1c
.RI "static hb_bool_t \fBis_default_ignorable\fP (hb_codepoint_t ch)"
.br
.ti -1c
.RI "static space_t \fBspace_fallback_type\fP (hb_codepoint_t u)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_object_header_t\fP \fBheader\fP"
.br
.ti -1c
.RI "\fBhb_unicode_funcs_t\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBfunc\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBuser_data\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBdestroy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
