.TH "hb_user_data_array_t::hb_user_data_item_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_user_data_array_t::hb_user_data_item_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBhb_user_data_key_t\fP *other_key) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBhb_user_data_item_t\fP &other) const"
.br
.ti -1c
.RI "void \fBfini\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_user_data_key_t\fP * \fBkey\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "hb_destroy_func_t \fBdestroy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
