.TH "hb_utf32_xe_t< TCodepoint, validate >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_utf32_xe_t< TCodepoint, validate >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef TCodepoint \fBcodepoint_t\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const TCodepoint * \fBnext\fP (const TCodepoint *text, const TCodepoint *end HB_UNUSED, hb_codepoint_t *unicode, hb_codepoint_t replacement)"
.br
.ti -1c
.RI "static const TCodepoint * \fBprev\fP (const TCodepoint *text, const TCodepoint *start HB_UNUSED, hb_codepoint_t *unicode, hb_codepoint_t replacement)"
.br
.ti -1c
.RI "static unsigned int \fBstrlen\fP (const TCodepoint *text)"
.br
.ti -1c
.RI "static unsigned int \fBencode_len\fP (hb_codepoint_t unicode HB_UNUSED)"
.br
.ti -1c
.RI "static codepoint_t * \fBencode\fP (codepoint_t *text, const codepoint_t *end HB_UNUSED, hb_codepoint_t unicode)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
