.TH "hb_variation_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hb_variation_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hb\-common\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_tag_t \fBtag\fP"
.br
.ti -1c
.RI "float \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBhb_variation_t\fP: @tag: The hb_tag_t tag of the variation-axis name @value: The value of the variation axis
.PP
Data type for holding variation data\&. Registered OpenType variation-axis tags are listed in \fCOpenType Axis Tag Registry\fP\&.
.PP
Since: 1\&.4\&.2 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
