.TH "helper_cairo_line_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
helper_cairo_line_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBfinish\fP ()"
.br
.ti -1c
.RI "void \fBget_advance\fP (double *x_advance, double *y_advance)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "cairo_glyph_t * \fBglyphs\fP"
.br
.ti -1c
.RI "unsigned int \fBnum_glyphs\fP"
.br
.ti -1c
.RI "char * \fButf8\fP"
.br
.ti -1c
.RI "unsigned int \fButf8_len\fP"
.br
.ti -1c
.RI "cairo_text_cluster_t * \fBclusters\fP"
.br
.ti -1c
.RI "unsigned int \fBnum_clusters\fP"
.br
.ti -1c
.RI "cairo_text_cluster_flags_t \fBcluster_flags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
