.TH "HTreeGroup" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HTreeGroup
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHuffmanCode\fP * \fBhtrees\fP [HUFFMAN_CODES_PER_META_CODE]"
.br
.ti -1c
.RI "int \fBis_trivial_literal\fP"
.br
.ti -1c
.RI "uint32_t \fBliteral_arb\fP"
.br
.ti -1c
.RI "int \fBis_trivial_code\fP"
.br
.ti -1c
.RI "int \fBuse_packed_table\fP"
.br
.ti -1c
.RI "\fBHuffmanCode32\fP \fBpacked_table\fP [HUFFMAN_PACKED_TABLE_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
