.TH "HTTP" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HTTP
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBback\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBHTTPSEND_NADA\fP, \fBHTTPSEND_REQUEST\fP, \fBHTTPSEND_BODY\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcurl_mimepart\fP * \fBsendit\fP"
.br
.ti -1c
.RI "curl_off_t \fBpostsize\fP"
.br
.ti -1c
.RI "const char * \fBpostdata\fP"
.br
.ti -1c
.RI "const char * \fBp_pragma\fP"
.br
.ti -1c
.RI "\fBcurl_mimepart\fP \fBform\fP"
.br
.ti -1c
.RI "struct \fBHTTP::back\fP \fBbackup\fP"
.br
.ti -1c
.RI "enum HTTP:: { \&.\&.\&. }  \fBsending\fP"
.br
.ti -1c
.RI "struct \fBdynbuf\fP \fBsend_buffer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
