.TH "httprequest" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httprequest
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBreqbuf\fP [REQBUFSIZ]"
.br
.ti -1c
.RI "size_t \fBcheckindex\fP"
.br
.ti -1c
.RI "size_t \fBoffset\fP"
.br
.ti -1c
.RI "long \fBtestno\fP"
.br
.ti -1c
.RI "long \fBpartno\fP"
.br
.ti -1c
.RI "bool \fBopen\fP"
.br
.ti -1c
.RI "bool \fBauth_req\fP"
.br
.ti -1c
.RI "bool \fBauth\fP"
.br
.ti -1c
.RI "size_t \fBcl\fP"
.br
.ti -1c
.RI "bool \fBdigest\fP"
.br
.ti -1c
.RI "bool \fBntlm\fP"
.br
.ti -1c
.RI "int \fBpipe\fP"
.br
.ti -1c
.RI "int \fBskip\fP"
.br
.ti -1c
.RI "int \fBrcmd\fP"
.br
.ti -1c
.RI "reqprot_t \fBprotocol\fP"
.br
.ti -1c
.RI "int \fBprot_version\fP"
.br
.ti -1c
.RI "bool \fBpipelining\fP"
.br
.ti -1c
.RI "char * \fBrtp_buffer\fP"
.br
.ti -1c
.RI "size_t \fBrtp_buffersize\fP"
.br
.ti -1c
.RI "bool \fBconnect_request\fP"
.br
.ti -1c
.RI "unsigned short \fBconnect_port\fP"
.br
.ti -1c
.RI "int \fBwritedelay\fP"
.br
.ti -1c
.RI "int \fBcallcount\fP"
.br
.ti -1c
.RI "bool \fBskipall\fP"
.br
.ti -1c
.RI "bool \fBnoexpect\fP"
.br
.ti -1c
.RI "bool \fBconnmon\fP"
.br
.ti -1c
.RI "bool \fBupgrade\fP"
.br
.ti -1c
.RI "bool \fBupgrade_request\fP"
.br
.ti -1c
.RI "bool \fBclose\fP"
.br
.ti -1c
.RI "int \fBdone_processing\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
