.TH "http_connect_state" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
http_connect_state
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBkeeponval\fP { \fBKEEPON_DONE\fP, \fBKEEPON_CONNECT\fP, \fBKEEPON_IGNORE\fP }"
.br
.ti -1c
.RI "enum { \fBTUNNEL_INIT\fP, \fBTUNNEL_CONNECT\fP, \fBTUNNEL_COMPLETE\fP, \fBTUNNEL_EXIT\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBIT\fP (chunked_encoding)"
.br
.ti -1c
.RI "\fBBIT\fP (close_connection)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBHTTP\fP \fBhttp_proxy\fP"
.br
.ti -1c
.RI "struct \fBHTTP\fP * \fBprot_save\fP"
.br
.ti -1c
.RI "struct \fBdynbuf\fP \fBrcvbuf\fP"
.br
.ti -1c
.RI "struct \fBdynbuf\fP \fBreq\fP"
.br
.ti -1c
.RI "size_t \fBnsend\fP"
.br
.ti -1c
.RI "enum http_connect_state::keeponval \fBkeepon\fP"
.br
.ti -1c
.RI "curl_off_t \fBcl\fP"
.br
.ti -1c
.RI "enum http_connect_state:: { \&.\&.\&. }  \fBtunnel_state\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
