.TH "HTTP::back" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HTTP::back
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "curl_read_callback \fBfread_func\fP"
.br
.ti -1c
.RI "void * \fBfread_in\fP"
.br
.ti -1c
.RI "const char * \fBpostdata\fP"
.br
.ti -1c
.RI "curl_off_t \fBpostsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
