.TH "huffman_code" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
huffman_code
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBhuffman_tree_node\fP * \fBtree\fP"
.br
.ti -1c
.RI "int \fBnumentries\fP"
.br
.ti -1c
.RI "int \fBnumallocatedentries\fP"
.br
.ti -1c
.RI "int \fBminlength\fP"
.br
.ti -1c
.RI "int \fBmaxlength\fP"
.br
.ti -1c
.RI "int \fBtablesize\fP"
.br
.ti -1c
.RI "struct \fBhuffman_table_entry\fP * \fBtable\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
