.TH "idr" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
idr
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBidrent\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBidr::idrent\fP * \fBidrent_pool\fP"
.br
.ti -1c
.RI "struct \fBarchive_rb_tree\fP \fBrbtree\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBidrent\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBidrent\fP ** \fBlast\fP"
.br
.ti -1c
.RI "} \fBwait_list\fP"
.br
.ti -1c
.RI "int \fBpool_size\fP"
.br
.ti -1c
.RI "int \fBpool_idx\fP"
.br
.ti -1c
.RI "int \fBnum_size\fP"
.br
.ti -1c
.RI "int \fBnull_size\fP"
.br
.ti -1c
.RI "char \fBchar_map\fP [0x80]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
