.TH "image_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
image_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBimage_t\fP (unsigned int width_, unsigned int height_, const uint32_t *data_, unsigned int stride_)"
.br
.ti -1c
.RI "\fBimage_t\fP (unsigned int width_, unsigned int height_)"
.br
.ti -1c
.RI "\fBcolor_t\fP & \fBoperator()\fP (unsigned int x, unsigned int y)"
.br
.ti -1c
.RI "\fBcolor_t\fP \fBoperator()\fP (unsigned int x, unsigned int y) const"
.br
.ti -1c
.RI "void \fBcopy_sub_image\fP (const \fBimage_t\fP &s, unsigned int x, unsigned int y, unsigned int w, unsigned int h)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "const unsigned int \fBheight\fP"
.br
.ti -1c
.RI "\fBpixman_image_t\fP * \fBimage\fP"
.br
.ti -1c
.RI "pixman_format_code_t \fBformat\fP"
.br
.ti -1c
.RI "const \fBcolor_t\fP * \fBcolor\fP"
.br
.ti -1c
.RI "pixman_repeat_t \fBrepeat\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
