.TH "image_common" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
image_common
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "image_type_t \fBtype\fP"
.br
.ti -1c
.RI "int32_t \fBref_count\fP"
.br
.ti -1c
.RI "\fBpixman_region32_t\fP \fBclip_region\fP"
.br
.ti -1c
.RI "int32_t \fBalpha_count\fP"
.br
.ti -1c
.RI "pixman_bool_t \fBhave_clip_region\fP"
.br
.ti -1c
.RI "pixman_bool_t \fBclient_clip\fP"
.br
.ti -1c
.RI "pixman_bool_t \fBclip_sources\fP"
.br
.ti -1c
.RI "pixman_bool_t \fBdirty\fP"
.br
.ti -1c
.RI "\fBpixman_transform_t\fP * \fBtransform\fP"
.br
.ti -1c
.RI "pixman_repeat_t \fBrepeat\fP"
.br
.ti -1c
.RI "pixman_filter_t \fBfilter\fP"
.br
.ti -1c
.RI "pixman_fixed_t * \fBfilter_params\fP"
.br
.ti -1c
.RI "int \fBn_filter_params\fP"
.br
.ti -1c
.RI "\fBbits_image_t\fP * \fBalpha_map\fP"
.br
.ti -1c
.RI "int \fBalpha_origin_x\fP"
.br
.ti -1c
.RI "int \fBalpha_origin_y\fP"
.br
.ti -1c
.RI "pixman_bool_t \fBcomponent_alpha\fP"
.br
.ti -1c
.RI "property_changed_func_t \fBproperty_changed\fP"
.br
.ti -1c
.RI "pixman_image_destroy_func_t \fBdestroy_func\fP"
.br
.ti -1c
.RI "void * \fBdestroy_data\fP"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.ti -1c
.RI "pixman_format_code_t \fBextended_format_code\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
