.TH "IMAP" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IMAP
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "curl_pp_transfer \fBtransfer\fP"
.br
.ti -1c
.RI "char * \fBmailbox\fP"
.br
.ti -1c
.RI "char * \fBuidvalidity\fP"
.br
.ti -1c
.RI "char * \fBuid\fP"
.br
.ti -1c
.RI "char * \fBmindex\fP"
.br
.ti -1c
.RI "char * \fBsection\fP"
.br
.ti -1c
.RI "char * \fBpartial\fP"
.br
.ti -1c
.RI "char * \fBquery\fP"
.br
.ti -1c
.RI "char * \fBcustom\fP"
.br
.ti -1c
.RI "char * \fBcustom_params\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
