.TH "imap_conn" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imap_conn
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBpingpong\fP \fBpp\fP"
.br
.ti -1c
.RI "imapstate \fBstate\fP"
.br
.ti -1c
.RI "bool \fBssldone\fP"
.br
.ti -1c
.RI "bool \fBpreauth\fP"
.br
.ti -1c
.RI "struct \fBSASL\fP \fBsasl\fP"
.br
.ti -1c
.RI "unsigned int \fBpreftype\fP"
.br
.ti -1c
.RI "unsigned int \fBcmdid\fP"
.br
.ti -1c
.RI "char \fBresptag\fP [5]"
.br
.ti -1c
.RI "bool \fBtls_supported\fP"
.br
.ti -1c
.RI "bool \fBlogin_disabled\fP"
.br
.ti -1c
.RI "bool \fBir_supported\fP"
.br
.ti -1c
.RI "char * \fBmailbox\fP"
.br
.ti -1c
.RI "char * \fBmailbox_uidvalidity\fP"
.br
.ti -1c
.RI "struct \fBdynbuf\fP \fBdyn\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
