.TH "ImDrawListSharedData" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImDrawListSharedData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetCircleTessellationMaxError\fP (float max_error)"
.br
.ti -1c
.RI "void \fBSetCircleTessellationMaxError\fP (float max_error)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVec2\fP \fBTexUvWhitePixel\fP"
.br
.ti -1c
.RI "\fBImFont\fP * \fBFont\fP"
.br
.ti -1c
.RI "float \fBFontSize\fP"
.br
.ti -1c
.RI "float \fBCurveTessellationTol\fP"
.br
.ti -1c
.RI "float \fBCircleSegmentMaxError\fP"
.br
.ti -1c
.RI "\fBImVec4\fP \fBClipRectFullscreen\fP"
.br
.ti -1c
.RI "ImDrawListFlags \fBInitialFlags\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBArcFastVtx\fP [IM_DRAWLIST_ARCFAST_TABLE_SIZE]"
.br
.ti -1c
.RI "float \fBArcFastRadiusCutoff\fP"
.br
.ti -1c
.RI "ImU8 \fBCircleSegmentCounts\fP [64]"
.br
.ti -1c
.RI "const \fBImVec4\fP * \fBTexUvLines\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
