.TH "ImDrawCmd" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImDrawCmd
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ImTextureID \fBGetTexID\fP () const"
.br
.ti -1c
.RI "ImTextureID \fBGetTexID\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVec4\fP \fBClipRect\fP"
.br
.ti -1c
.RI "ImTextureID \fBTextureId\fP"
.br
.ti -1c
.RI "unsigned int \fBVtxOffset\fP"
.br
.ti -1c
.RI "unsigned int \fBIdxOffset\fP"
.br
.ti -1c
.RI "unsigned int \fBElemCount\fP"
.br
.ti -1c
.RI "ImDrawCallback \fBUserCallback\fP"
.br
.ti -1c
.RI "void * \fBUserCallbackData\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
