.TH "ImFontAtlasCustomRect" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImFontAtlasCustomRect
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsPacked\fP () const"
.br
.ti -1c
.RI "bool \fBIsPacked\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBWidth\fP"
.br
.ti -1c
.RI "unsigned short \fBHeight\fP"
.br
.ti -1c
.RI "unsigned short \fBX\fP"
.br
.ti -1c
.RI "unsigned short \fBY\fP"
.br
.ti -1c
.RI "unsigned int \fBGlyphID\fP"
.br
.ti -1c
.RI "float \fBGlyphAdvanceX\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGlyphOffset\fP"
.br
.ti -1c
.RI "\fBImFont\fP * \fBFont\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
