.TH "ImGuiViewportP" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiViewportP
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBImGuiViewport\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClearRequestFlags\fP ()"
.br
.ti -1c
.RI "\fBImVec2\fP \fBCalcWorkRectPos\fP (const \fBImVec2\fP &off_min) const"
.br
.ti -1c
.RI "\fBImVec2\fP \fBCalcWorkRectSize\fP (const \fBImVec2\fP &off_min, const \fBImVec2\fP &off_max) const"
.br
.ti -1c
.RI "void \fBUpdateWorkRect\fP ()"
.br
.ti -1c
.RI "\fBImRect\fP \fBGetMainRect\fP () const"
.br
.ti -1c
.RI "\fBImRect\fP \fBGetWorkRect\fP () const"
.br
.ti -1c
.RI "\fBImRect\fP \fBGetBuildWorkRect\fP () const"
.br
.ti -1c
.RI "void \fBClearRequestFlags\fP ()"
.br
.ti -1c
.RI "\fBImVec2\fP \fBCalcWorkRectPos\fP (const \fBImVec2\fP &off_min) const"
.br
.ti -1c
.RI "\fBImVec2\fP \fBCalcWorkRectSize\fP (const \fBImVec2\fP &off_min, const \fBImVec2\fP &off_max) const"
.br
.ti -1c
.RI "void \fBUpdateWorkRect\fP ()"
.br
.ti -1c
.RI "\fBImRect\fP \fBGetMainRect\fP () const"
.br
.ti -1c
.RI "\fBImRect\fP \fBGetWorkRect\fP () const"
.br
.ti -1c
.RI "\fBImRect\fP \fBGetBuildWorkRect\fP () const"
.br
.in -1c

Public Member Functions inherited from \fBImGuiViewport\fP
.in +1c
.ti -1c
.RI "\fBImVec2\fP \fBGetCenter\fP () const"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGetWorkCenter\fP () const"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGetCenter\fP () const"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGetWorkCenter\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBIdx\fP"
.br
.ti -1c
.RI "int \fBLastFrameActive\fP"
.br
.ti -1c
.RI "int \fBLastFrontMostStampCount\fP"
.br
.ti -1c
.RI "ImGuiID \fBLastNameHash\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLastPos\fP"
.br
.ti -1c
.RI "float \fBAlpha\fP"
.br
.ti -1c
.RI "float \fBLastAlpha\fP"
.br
.ti -1c
.RI "short \fBPlatformMonitor\fP"
.br
.ti -1c
.RI "bool \fBPlatformWindowCreated\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "int \fBDrawListsLastFrame\fP [2]"
.br
.ti -1c
.RI "\fBImDrawList\fP * \fBDrawLists\fP [2]"
.br
.ti -1c
.RI "\fBImDrawData\fP \fBDrawDataP\fP"
.br
.ti -1c
.RI "\fBImDrawDataBuilder\fP \fBDrawDataBuilder\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLastPlatformPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLastPlatformSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBLastRendererSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkOffsetMin\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkOffsetMax\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBuildWorkOffsetMin\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBuildWorkOffsetMax\fP"
.br
.in -1c

Public Attributes inherited from \fBImGuiViewport\fP
.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiViewportFlags \fBFlags\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkSize\fP"
.br
.ti -1c
.RI "float \fBDpiScale\fP"
.br
.ti -1c
.RI "ImGuiID \fBParentViewportId\fP"
.br
.ti -1c
.RI "\fBImDrawData\fP * \fBDrawData\fP"
.br
.ti -1c
.RI "void * \fBRendererUserData\fP"
.br
.ti -1c
.RI "void * \fBPlatformUserData\fP"
.br
.ti -1c
.RI "void * \fBPlatformHandle\fP"
.br
.ti -1c
.RI "void * \fBPlatformHandleRaw\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestMove\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestResize\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestClose\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
