.TH "ImGuiSettingsHandler" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiSettingsHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBTypeName\fP"
.br
.ti -1c
.RI "ImGuiID \fBTypeHash\fP"
.br
.ti -1c
.RI "void(* \fBClearAllFn\fP )(\fBImGuiContext\fP *ctx, \fBImGuiSettingsHandler\fP *handler)"
.br
.ti -1c
.RI "void(* \fBReadInitFn\fP )(\fBImGuiContext\fP *ctx, \fBImGuiSettingsHandler\fP *handler)"
.br
.ti -1c
.RI "void *(* \fBReadOpenFn\fP )(\fBImGuiContext\fP *ctx, \fBImGuiSettingsHandler\fP *handler, const char *name)"
.br
.ti -1c
.RI "void(* \fBReadLineFn\fP )(\fBImGuiContext\fP *ctx, \fBImGuiSettingsHandler\fP *handler, void *\fBentry\fP, const char *line)"
.br
.ti -1c
.RI "void(* \fBApplyAllFn\fP )(\fBImGuiContext\fP *ctx, \fBImGuiSettingsHandler\fP *handler)"
.br
.ti -1c
.RI "void(* \fBWriteAllFn\fP )(\fBImGuiContext\fP *ctx, \fBImGuiSettingsHandler\fP *handler, \fBImGuiTextBuffer\fP *out_buf)"
.br
.ti -1c
.RI "void * \fBUserData\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
