.TH "ImGuiOldColumnData" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiOldColumnData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBOffsetNorm\fP"
.br
.ti -1c
.RI "float \fBOffsetNormBeforeResize\fP"
.br
.ti -1c
.RI "ImGuiOldColumnFlags \fBFlags\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBClipRect\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
