.TH "ImGuiWindowSettings" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiWindowSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetName\fP ()"
.br
.ti -1c
.RI "char * \fBGetName\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBSize\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBViewportPos\fP"
.br
.ti -1c
.RI "ImGuiID \fBViewportId\fP"
.br
.ti -1c
.RI "ImGuiID \fBDockId\fP"
.br
.ti -1c
.RI "ImGuiID \fBClassId\fP"
.br
.ti -1c
.RI "short \fBDockOrder\fP"
.br
.ti -1c
.RI "bool \fBCollapsed\fP"
.br
.ti -1c
.RI "bool \fBWantApply\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
