.TH "ImGuiListClipperRange" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiListClipperRange
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBImGuiListClipperRange\fP \fBFromIndices\fP (int min, int max)"
.br
.ti -1c
.RI "static \fBImGuiListClipperRange\fP \fBFromPositions\fP (float y1, float y2, int off_min, int off_max)"
.br
.ti -1c
.RI "static \fBImGuiListClipperRange\fP \fBFromIndices\fP (int min, int max)"
.br
.ti -1c
.RI "static \fBImGuiListClipperRange\fP \fBFromPositions\fP (float y1, float y2, int off_min, int off_max)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBMin\fP"
.br
.ti -1c
.RI "int \fBMax\fP"
.br
.ti -1c
.RI "bool \fBPosToIndexConvert\fP"
.br
.ti -1c
.RI "ImS8 \fBPosToIndexOffsetMin\fP"
.br
.ti -1c
.RI "ImS8 \fBPosToIndexOffsetMax\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
