.TH "ImGui_ImplOpenGL3_Data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGui_ImplOpenGL3_Data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLuint \fBGlVersion\fP"
.br
.ti -1c
.RI "char \fBGlslVersionString\fP [32]"
.br
.ti -1c
.RI "GLuint \fBFontTexture\fP"
.br
.ti -1c
.RI "GLuint \fBShaderHandle\fP"
.br
.ti -1c
.RI "GLint \fBAttribLocationTex\fP"
.br
.ti -1c
.RI "GLint \fBAttribLocationProjMtx\fP"
.br
.ti -1c
.RI "GLuint \fBAttribLocationVtxPos\fP"
.br
.ti -1c
.RI "GLuint \fBAttribLocationVtxUV\fP"
.br
.ti -1c
.RI "GLuint \fBAttribLocationVtxColor\fP"
.br
.ti -1c
.RI "unsigned int \fBVboHandle\fP"
.br
.ti -1c
.RI "unsigned int \fBElementsHandle\fP"
.br
.ti -1c
.RI "bool \fBHasClipOrigin\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
