.TH "ImGuiWindowClass" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiWindowClass
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBClassId\fP"
.br
.ti -1c
.RI "ImGuiID \fBParentViewportId\fP"
.br
.ti -1c
.RI "ImGuiViewportFlags \fBViewportFlagsOverrideSet\fP"
.br
.ti -1c
.RI "ImGuiViewportFlags \fBViewportFlagsOverrideClear\fP"
.br
.ti -1c
.RI "ImGuiTabItemFlags \fBTabItemFlagsOverrideSet\fP"
.br
.ti -1c
.RI "ImGuiDockNodeFlags \fBDockNodeFlagsOverrideSet\fP"
.br
.ti -1c
.RI "bool \fBDockingAlwaysTabBar\fP"
.br
.ti -1c
.RI "bool \fBDockingAllowUnclassed\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
