.TH "ImGuiTableTempData" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTableTempData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBTableIndex\fP"
.br
.ti -1c
.RI "float \fBLastTimeActive\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBUserOuterSize\fP"
.br
.ti -1c
.RI "\fBImDrawListSplitter\fP \fBDrawSplitter\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBHostBackupWorkRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBHostBackupParentWorkRect\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBHostBackupPrevLineSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBHostBackupCurrLineSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBHostBackupCursorMaxPos\fP"
.br
.ti -1c
.RI "\fBImVec1\fP \fBHostBackupColumnsOffset\fP"
.br
.ti -1c
.RI "float \fBHostBackupItemWidth\fP"
.br
.ti -1c
.RI "int \fBHostBackupItemWidthStackSize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
