.TH "ImGuiPayload" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiPayload
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "bool \fBIsDataType\fP (const char *type) const"
.br
.ti -1c
.RI "bool \fBIsPreview\fP () const"
.br
.ti -1c
.RI "bool \fBIsDelivery\fP () const"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "bool \fBIsDataType\fP (const char *type) const"
.br
.ti -1c
.RI "bool \fBIsPreview\fP () const"
.br
.ti -1c
.RI "bool \fBIsDelivery\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBData\fP"
.br
.ti -1c
.RI "int \fBDataSize\fP"
.br
.ti -1c
.RI "ImGuiID \fBSourceId\fP"
.br
.ti -1c
.RI "ImGuiID \fBSourceParentId\fP"
.br
.ti -1c
.RI "int \fBDataFrameCount\fP"
.br
.ti -1c
.RI "char \fBDataType\fP [32+1]"
.br
.ti -1c
.RI "bool \fBPreview\fP"
.br
.ti -1c
.RI "bool \fBDelivery\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
