.TH "ImGuiStackLevelInfo" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiStackLevelInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImS8 \fBQueryFrameCount\fP"
.br
.ti -1c
.RI "bool \fBQuerySuccess\fP"
.br
.ti -1c
.RI "ImGuiDataType \fBDataType\fP: 8"
.br
.ti -1c
.RI "char \fBDesc\fP [57]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
