.TH "ImGuiContextHook" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiContextHook
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBHookId\fP"
.br
.ti -1c
.RI "ImGuiContextHookType \fBType\fP"
.br
.ti -1c
.RI "ImGuiID \fBOwner\fP"
.br
.ti -1c
.RI "ImGuiContextHookCallback \fBCallback\fP"
.br
.ti -1c
.RI "void * \fBUserData\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
