.TH "ImGuiTextFilter::ImGuiTextRange" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTextFilter::ImGuiTextRange
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTextRange\fP (const char *_b, const char *_e)"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "IMGUI_API void \fBsplit\fP (char separator, \fBImVector\fP< \fBImGuiTextRange\fP > *out) const"
.br
.ti -1c
.RI "\fBImGuiTextRange\fP (const char *_b, const char *_e)"
.br
.ti -1c
.RI "bool \fBempty\fP () const"
.br
.ti -1c
.RI "IMGUI_API void \fBsplit\fP (char separator, \fBImVector\fP< \fBImGuiTextRange\fP > *out) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBb\fP"
.br
.ti -1c
.RI "const char * \fBe\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
