.TH "ImGuiDockRequest" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDockRequest
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiDockRequestType \fBType\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBDockTargetWindow\fP"
.br
.ti -1c
.RI "\fBImGuiDockNode\fP * \fBDockTargetNode\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBDockPayload\fP"
.br
.ti -1c
.RI "ImGuiDir \fBDockSplitDir\fP"
.br
.ti -1c
.RI "float \fBDockSplitRatio\fP"
.br
.ti -1c
.RI "bool \fBDockSplitOuter\fP"
.br
.ti -1c
.RI "\fBImGuiWindow\fP * \fBUndockTargetWindow\fP"
.br
.ti -1c
.RI "\fBImGuiDockNode\fP * \fBUndockTargetNode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
