.TH "ImGuiNextItemData" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiNextItemData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClearFlags\fP ()"
.br
.ti -1c
.RI "void \fBClearFlags\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiNextItemDataFlags \fBFlags\fP"
.br
.ti -1c
.RI "float \fBWidth\fP"
.br
.ti -1c
.RI "ImGuiID \fBFocusScopeId\fP"
.br
.ti -1c
.RI "ImGuiCond \fBOpenCond\fP"
.br
.ti -1c
.RI "bool \fBOpenVal\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
