.TH "ImGui_ImplGlfw_ViewportData" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGui_ImplGlfw_ViewportData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGLFWwindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "bool \fBWindowOwned\fP"
.br
.ti -1c
.RI "int \fBIgnoreWindowPosEventFrame\fP"
.br
.ti -1c
.RI "int \fBIgnoreWindowSizeEventFrame\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
