.TH "ImGuiLastItemData" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiLastItemData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiItemFlags \fBInFlags\fP"
.br
.ti -1c
.RI "ImGuiItemStatusFlags \fBStatusFlags\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBNavRect\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBDisplayRect\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
