.TH "ImGuiStackSizes" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiStackSizes
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetToCurrentState\fP ()"
.br
.ti -1c
.RI "void \fBCompareWithCurrentState\fP ()"
.br
.ti -1c
.RI "void \fBSetToCurrentState\fP ()"
.br
.ti -1c
.RI "void \fBCompareWithCurrentState\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBSizeOfIDStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfColorStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfStyleVarStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfFontStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfFocusScopeStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfGroupStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfItemFlagsStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfBeginPopupStack\fP"
.br
.ti -1c
.RI "short \fBSizeOfDisabledStack\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
