.TH "ImGuiTableSettings" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTableSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImGuiTableColumnSettings\fP * \fBGetColumnSettings\fP ()"
.br
.ti -1c
.RI "\fBImGuiTableColumnSettings\fP * \fBGetColumnSettings\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiTableFlags \fBSaveFlags\fP"
.br
.ti -1c
.RI "float \fBRefScale\fP"
.br
.ti -1c
.RI "ImGuiTableColumnIdx \fBColumnsCount\fP"
.br
.ti -1c
.RI "ImGuiTableColumnIdx \fBColumnsCountMax\fP"
.br
.ti -1c
.RI "bool \fBWantApply\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
