.TH "ImGuiTableColumnSettings" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTableColumnSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBWidthOrWeight\fP"
.br
.ti -1c
.RI "ImGuiID \fBUserID\fP"
.br
.ti -1c
.RI "ImGuiTableColumnIdx \fBIndex\fP"
.br
.ti -1c
.RI "ImGuiTableColumnIdx \fBDisplayOrder\fP"
.br
.ti -1c
.RI "ImGuiTableColumnIdx \fBSortOrder\fP"
.br
.ti -1c
.RI "ImU8 \fBSortDirection\fP: 2"
.br
.ti -1c
.RI "ImU8 \fBIsEnabled\fP: 1"
.br
.ti -1c
.RI "ImU8 \fBIsStretch\fP: 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
