.TH "ImGuiTabBar" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTabBar
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBGetTabOrder\fP (const \fBImGuiTabItem\fP *\fBtab\fP) const"
.br
.ti -1c
.RI "const char * \fBGetTabName\fP (const \fBImGuiTabItem\fP *\fBtab\fP) const"
.br
.ti -1c
.RI "int \fBGetTabOrder\fP (const \fBImGuiTabItem\fP *\fBtab\fP) const"
.br
.ti -1c
.RI "const char * \fBGetTabName\fP (const \fBImGuiTabItem\fP *\fBtab\fP) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImVector\fP< \fBImGuiTabItem\fP > \fBTabs\fP"
.br
.ti -1c
.RI "ImGuiTabBarFlags \fBFlags\fP"
.br
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiID \fBSelectedTabId\fP"
.br
.ti -1c
.RI "ImGuiID \fBNextSelectedTabId\fP"
.br
.ti -1c
.RI "ImGuiID \fBVisibleTabId\fP"
.br
.ti -1c
.RI "int \fBCurrFrameVisible\fP"
.br
.ti -1c
.RI "int \fBPrevFrameVisible\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBBarRect\fP"
.br
.ti -1c
.RI "float \fBCurrTabsContentsHeight\fP"
.br
.ti -1c
.RI "float \fBPrevTabsContentsHeight\fP"
.br
.ti -1c
.RI "float \fBWidthAllTabs\fP"
.br
.ti -1c
.RI "float \fBWidthAllTabsIdeal\fP"
.br
.ti -1c
.RI "float \fBScrollingAnim\fP"
.br
.ti -1c
.RI "float \fBScrollingTarget\fP"
.br
.ti -1c
.RI "float \fBScrollingTargetDistToVisibility\fP"
.br
.ti -1c
.RI "float \fBScrollingSpeed\fP"
.br
.ti -1c
.RI "float \fBScrollingRectMinX\fP"
.br
.ti -1c
.RI "float \fBScrollingRectMaxX\fP"
.br
.ti -1c
.RI "ImGuiID \fBReorderRequestTabId\fP"
.br
.ti -1c
.RI "ImS16 \fBReorderRequestOffset\fP"
.br
.ti -1c
.RI "ImS8 \fBBeginCount\fP"
.br
.ti -1c
.RI "bool \fBWantLayout\fP"
.br
.ti -1c
.RI "bool \fBVisibleTabWasSubmitted\fP"
.br
.ti -1c
.RI "bool \fBTabsAddedNew\fP"
.br
.ti -1c
.RI "ImS16 \fBTabsActiveCount\fP"
.br
.ti -1c
.RI "ImS16 \fBLastTabItemIdx\fP"
.br
.ti -1c
.RI "float \fBItemSpacingY\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBFramePadding\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCursorPos\fP"
.br
.ti -1c
.RI "\fBImGuiTextBuffer\fP \fBTabsNames\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
