.TH "ImGuiMetricsConfig" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiMetricsConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBShowDebugLog\fP"
.br
.ti -1c
.RI "bool \fBShowStackTool\fP"
.br
.ti -1c
.RI "bool \fBShowWindowsRects\fP"
.br
.ti -1c
.RI "bool \fBShowWindowsBeginOrder\fP"
.br
.ti -1c
.RI "bool \fBShowTablesRects\fP"
.br
.ti -1c
.RI "bool \fBShowDrawCmdMesh\fP"
.br
.ti -1c
.RI "bool \fBShowDrawCmdBoundingBoxes\fP"
.br
.ti -1c
.RI "bool \fBShowDockingNodes\fP"
.br
.ti -1c
.RI "int \fBShowWindowsRectsType\fP"
.br
.ti -1c
.RI "int \fBShowTablesRectsType\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
