.TH "ImGuiTableColumnSortSpecs" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiTableColumnSortSpecs
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBColumnUserID\fP"
.br
.ti -1c
.RI "ImS16 \fBColumnIndex\fP"
.br
.ti -1c
.RI "ImS16 \fBSortOrder\fP"
.br
.ti -1c
.RI "ImGuiSortDirection \fBSortDirection\fP: 8"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
