.TH "ImGuiViewport" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiViewport
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBImGuiViewportP\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImVec2\fP \fBGetCenter\fP () const"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGetWorkCenter\fP () const"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGetCenter\fP () const"
.br
.ti -1c
.RI "\fBImVec2\fP \fBGetWorkCenter\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiViewportFlags \fBFlags\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBSize\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBWorkSize\fP"
.br
.ti -1c
.RI "float \fBDpiScale\fP"
.br
.ti -1c
.RI "ImGuiID \fBParentViewportId\fP"
.br
.ti -1c
.RI "\fBImDrawData\fP * \fBDrawData\fP"
.br
.ti -1c
.RI "void * \fBRendererUserData\fP"
.br
.ti -1c
.RI "void * \fBPlatformUserData\fP"
.br
.ti -1c
.RI "void * \fBPlatformHandle\fP"
.br
.ti -1c
.RI "void * \fBPlatformHandleRaw\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestMove\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestResize\fP"
.br
.ti -1c
.RI "bool \fBPlatformRequestClose\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
