.TH "ImGui_ImplGlfw_Data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGui_ImplGlfw_Data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGLFWwindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "GlfwClientApi \fBClientApi\fP"
.br
.ti -1c
.RI "double \fBTime\fP"
.br
.ti -1c
.RI "\fBGLFWwindow\fP * \fBMouseWindow\fP"
.br
.ti -1c
.RI "bool \fBMouseJustPressed\fP [ImGuiMouseButton_COUNT]"
.br
.ti -1c
.RI "\fBGLFWcursor\fP * \fBMouseCursors\fP [ImGuiMouseCursor_COUNT]"
.br
.ti -1c
.RI "\fBGLFWwindow\fP * \fBKeyOwnerWindows\fP [512]"
.br
.ti -1c
.RI "bool \fBInstalledCallbacks\fP"
.br
.ti -1c
.RI "bool \fBWantUpdateMonitors\fP"
.br
.ti -1c
.RI "\fBGLFWwindowfocusfun\fP \fBPrevUserCallbackWindowFocus\fP"
.br
.ti -1c
.RI "\fBGLFWcursorenterfun\fP \fBPrevUserCallbackCursorEnter\fP"
.br
.ti -1c
.RI "\fBGLFWmousebuttonfun\fP \fBPrevUserCallbackMousebutton\fP"
.br
.ti -1c
.RI "\fBGLFWscrollfun\fP \fBPrevUserCallbackScroll\fP"
.br
.ti -1c
.RI "\fBGLFWkeyfun\fP \fBPrevUserCallbackKey\fP"
.br
.ti -1c
.RI "\fBGLFWcharfun\fP \fBPrevUserCallbackChar\fP"
.br
.ti -1c
.RI "\fBGLFWmonitorfun\fP \fBPrevUserCallbackMonitor\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
