.TH "ImGuiNavItemData" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiNavItemData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiWindow\fP * \fBWindow\fP"
.br
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiID \fBFocusScopeId\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBRectRel\fP"
.br
.ti -1c
.RI "ImGuiItemFlags \fBInFlags\fP"
.br
.ti -1c
.RI "float \fBDistBox\fP"
.br
.ti -1c
.RI "float \fBDistCenter\fP"
.br
.ti -1c
.RI "float \fBDistAxial\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
