.TH "ImGuiGroupData" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiGroupData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBWindowID\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCursorPos\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCursorMaxPos\fP"
.br
.ti -1c
.RI "\fBImVec1\fP \fBBackupIndent\fP"
.br
.ti -1c
.RI "\fBImVec1\fP \fBBackupGroupOffset\fP"
.br
.ti -1c
.RI "\fBImVec2\fP \fBBackupCurrLineSize\fP"
.br
.ti -1c
.RI "float \fBBackupCurrLineTextBaseOffset\fP"
.br
.ti -1c
.RI "ImGuiID \fBBackupActiveIdIsAlive\fP"
.br
.ti -1c
.RI "bool \fBBackupActiveIdPreviousFrameIsAlive\fP"
.br
.ti -1c
.RI "bool \fBBackupHoveredIdIsAlive\fP"
.br
.ti -1c
.RI "bool \fBEmitItem\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
