.TH "ImGuiDockNodeSettings" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDockNodeSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImGuiID \fBID\fP"
.br
.ti -1c
.RI "ImGuiID \fBParentNodeId\fP"
.br
.ti -1c
.RI "ImGuiID \fBParentWindowId\fP"
.br
.ti -1c
.RI "ImGuiID \fBSelectedTabId\fP"
.br
.ti -1c
.RI "signed char \fBSplitAxis\fP"
.br
.ti -1c
.RI "char \fBDepth\fP"
.br
.ti -1c
.RI "ImGuiDockNodeFlags \fBFlags\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBPos\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBSize\fP"
.br
.ti -1c
.RI "\fBImVec2ih\fP \fBSizeRef\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
