.TH "ImGuiDockPreviewData" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiDockPreviewData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBImGuiDockNode\fP \fBFutureNode\fP"
.br
.ti -1c
.RI "bool \fBIsDropAllowed\fP"
.br
.ti -1c
.RI "bool \fBIsCenterAvailable\fP"
.br
.ti -1c
.RI "bool \fBIsSidesAvailable\fP"
.br
.ti -1c
.RI "bool \fBIsSplitDirExplicit\fP"
.br
.ti -1c
.RI "\fBImGuiDockNode\fP * \fBSplitNode\fP"
.br
.ti -1c
.RI "ImGuiDir \fBSplitDir\fP"
.br
.ti -1c
.RI "float \fBSplitRatio\fP"
.br
.ti -1c
.RI "\fBImRect\fP \fBDropRectsDraw\fP [ImGuiDir_COUNT+1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
