.TH "ImGuiMenuColumns" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImGuiMenuColumns
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP (float spacing, bool window_reappearing)"
.br
.ti -1c
.RI "float \fBDeclColumns\fP (float w_icon, float w_label, float w_shortcut, float w_mark)"
.br
.ti -1c
.RI "void \fBCalcNextTotalWidth\fP (bool update_offsets)"
.br
.ti -1c
.RI "void \fBUpdate\fP (float spacing, bool window_reappearing)"
.br
.ti -1c
.RI "float \fBDeclColumns\fP (float w_icon, float w_label, float w_shortcut, float w_mark)"
.br
.ti -1c
.RI "void \fBCalcNextTotalWidth\fP (bool update_offsets)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ImU32 \fBTotalWidth\fP"
.br
.ti -1c
.RI "ImU32 \fBNextTotalWidth\fP"
.br
.ti -1c
.RI "ImU16 \fBSpacing\fP"
.br
.ti -1c
.RI "ImU16 \fBOffsetIcon\fP"
.br
.ti -1c
.RI "ImU16 \fBOffsetLabel\fP"
.br
.ti -1c
.RI "ImU16 \fBOffsetShortcut\fP"
.br
.ti -1c
.RI "ImU16 \fBOffsetMark\fP"
.br
.ti -1c
.RI "ImU16 \fBWidths\fP [4]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
