.TH "ImSpan< T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImSpan< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImSpan\fP (T *\fBdata\fP, int size)"
.br
.ti -1c
.RI "\fBImSpan\fP (T *\fBdata\fP, T *data_end)"
.br
.ti -1c
.RI "void \fBset\fP (T *\fBdata\fP, int size)"
.br
.ti -1c
.RI "void \fBset\fP (T *\fBdata\fP, T *data_end)"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.ti -1c
.RI "int \fBsize_in_bytes\fP () const"
.br
.ti -1c
.RI "T & \fBoperator[]\fP (int i)"
.br
.ti -1c
.RI "const T & \fBoperator[]\fP (int i) const"
.br
.ti -1c
.RI "T * \fBbegin\fP ()"
.br
.ti -1c
.RI "const T * \fBbegin\fP () const"
.br
.ti -1c
.RI "T * \fBend\fP ()"
.br
.ti -1c
.RI "const T * \fBend\fP () const"
.br
.ti -1c
.RI "int \fBindex_from_ptr\fP (const T *it) const"
.br
.ti -1c
.RI "\fBImSpan\fP (T *\fBdata\fP, int size)"
.br
.ti -1c
.RI "\fBImSpan\fP (T *\fBdata\fP, T *data_end)"
.br
.ti -1c
.RI "void \fBset\fP (T *\fBdata\fP, int size)"
.br
.ti -1c
.RI "void \fBset\fP (T *\fBdata\fP, T *data_end)"
.br
.ti -1c
.RI "int \fBsize\fP () const"
.br
.ti -1c
.RI "int \fBsize_in_bytes\fP () const"
.br
.ti -1c
.RI "T & \fBoperator[]\fP (int i)"
.br
.ti -1c
.RI "const T & \fBoperator[]\fP (int i) const"
.br
.ti -1c
.RI "T * \fBbegin\fP ()"
.br
.ti -1c
.RI "const T * \fBbegin\fP () const"
.br
.ti -1c
.RI "T * \fBend\fP ()"
.br
.ti -1c
.RI "const T * \fBend\fP () const"
.br
.ti -1c
.RI "int \fBindex_from_ptr\fP (const T *it) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T * \fBData\fP"
.br
.ti -1c
.RI "T * \fBDataEnd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
