.TH "indic_shape_plan_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
indic_shape_plan_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBload_virama_glyph\fP (\fBhb_font_t\fP *font, hb_codepoint_t *pglyph) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBindic_config_t\fP * \fBconfig\fP"
.br
.ti -1c
.RI "bool \fBis_old_spec\fP"
.br
.ti -1c
.RI "bool \fBuniscribe_bug_compatible\fP"
.br
.ti -1c
.RI "\fBhb_atomic_int_t\fP \fBvirama_glyph\fP"
.br
.ti -1c
.RI "\fBhb_indic_would_substitute_feature_t\fP \fBrphf\fP"
.br
.ti -1c
.RI "\fBhb_indic_would_substitute_feature_t\fP \fBpref\fP"
.br
.ti -1c
.RI "\fBhb_indic_would_substitute_feature_t\fP \fBblwf\fP"
.br
.ti -1c
.RI "\fBhb_indic_would_substitute_feature_t\fP \fBpstf\fP"
.br
.ti -1c
.RI "\fBhb_indic_would_substitute_feature_t\fP \fBvatu\fP"
.br
.ti -1c
.RI "hb_mask_t \fBmask_array\fP [INDIC_NUM_FEATURES]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
