.TH "inffast_ar" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inffast_ar
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBesp\fP"
.br
.ti -1c
.RI "void * \fBebp\fP"
.br
.ti -1c
.RI "unsigned char FAR * \fBin\fP"
.br
.ti -1c
.RI "unsigned char FAR * \fBlast\fP"
.br
.ti -1c
.RI "unsigned char FAR * \fBout\fP"
.br
.ti -1c
.RI "unsigned char FAR * \fBbeg\fP"
.br
.ti -1c
.RI "unsigned char FAR * \fBend\fP"
.br
.ti -1c
.RI "unsigned char FAR * \fBwindow\fP"
.br
.ti -1c
.RI "\fBcode\fP const FAR * \fBlcode\fP"
.br
.ti -1c
.RI "\fBcode\fP const FAR * \fBdcode\fP"
.br
.ti -1c
.RI "size_t \fBhold\fP"
.br
.ti -1c
.RI "unsigned \fBbits\fP"
.br
.ti -1c
.RI "unsigned \fBwsize\fP"
.br
.ti -1c
.RI "unsigned \fBwrite\fP"
.br
.ti -1c
.RI "unsigned \fBlmask\fP"
.br
.ti -1c
.RI "unsigned \fBdmask\fP"
.br
.ti -1c
.RI "unsigned \fBlen\fP"
.br
.ti -1c
.RI "unsigned \fBdist\fP"
.br
.ti -1c
.RI "unsigned \fBstatus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
