.TH "inflate_state" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inflate_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "z_streamp \fBstrm\fP"
.br
.ti -1c
.RI "inflate_mode \fBmode\fP"
.br
.ti -1c
.RI "int \fBlast\fP"
.br
.ti -1c
.RI "int \fBwrap\fP"
.br
.ti -1c
.RI "int \fBhavedict\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "unsigned \fBdmax\fP"
.br
.ti -1c
.RI "unsigned long \fBcheck\fP"
.br
.ti -1c
.RI "unsigned long \fBtotal\fP"
.br
.ti -1c
.RI "gz_headerp \fBhead\fP"
.br
.ti -1c
.RI "unsigned \fBwbits\fP"
.br
.ti -1c
.RI "unsigned \fBwsize\fP"
.br
.ti -1c
.RI "unsigned \fBwhave\fP"
.br
.ti -1c
.RI "unsigned \fBwnext\fP"
.br
.ti -1c
.RI "unsigned char FAR * \fBwindow\fP"
.br
.ti -1c
.RI "unsigned long \fBhold\fP"
.br
.ti -1c
.RI "unsigned \fBbits\fP"
.br
.ti -1c
.RI "unsigned \fBlength\fP"
.br
.ti -1c
.RI "unsigned \fBoffset\fP"
.br
.ti -1c
.RI "unsigned \fBextra\fP"
.br
.ti -1c
.RI "\fBcode\fP const FAR * \fBlencode\fP"
.br
.ti -1c
.RI "\fBcode\fP const FAR * \fBdistcode\fP"
.br
.ti -1c
.RI "unsigned \fBlenbits\fP"
.br
.ti -1c
.RI "unsigned \fBdistbits\fP"
.br
.ti -1c
.RI "unsigned \fBncode\fP"
.br
.ti -1c
.RI "unsigned \fBnlen\fP"
.br
.ti -1c
.RI "unsigned \fBndist\fP"
.br
.ti -1c
.RI "unsigned \fBhave\fP"
.br
.ti -1c
.RI "\fBcode\fP FAR * \fBnext\fP"
.br
.ti -1c
.RI "unsigned short \fBlens\fP [320]"
.br
.ti -1c
.RI "unsigned short \fBwork\fP [288]"
.br
.ti -1c
.RI "\fBcode\fP \fBcodes\fP [ENOUGH]"
.br
.ti -1c
.RI "int \fBsane\fP"
.br
.ti -1c
.RI "int \fBback\fP"
.br
.ti -1c
.RI "unsigned \fBwas\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
