.TH "info_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
info_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBaddr\fP"
.br
.ti -1c
.RI "uint32_t \fBlen\fP"
.br
.ti -1c
.RI "uint8_t * \fBtrailing\fP"
.br
.ti -1c
.RI "int \fBn_bytes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
