.TH "InheritsDebugStringMethods" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InheritsDebugStringMethods
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHasDebugStringMethods\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBHasDebugStringMethods\fP
.in +1c
.ti -1c
.RI "std::string \fBDebugString\fP () const"
.br
.ti -1c
.RI "std::string \fBShortDebugString\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
