.TH "input" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
input
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBin\fP"
.br
.ti -1c
.RI "size_t \fBbytes_read\fP"
.br
.ti -1c
.RI "CURL * \fBhnd\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
