.TH "int_checker< true >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
int_checker< true >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > static bool \fBfits_in_int\fP (T \fBvalue\fP)"
.br
.ti -1c
.RI "static bool \fBfits_in_int\fP (int)"
.br
.ti -1c
.RI "template<typename T > static bool \fBfits_in_int\fP (T \fBvalue\fP)"
.br
.ti -1c
.RI "static bool \fBfits_in_int\fP (int)"
.br
.ti -1c
.RI "template<typename T > static bool \fBfits_in_int\fP (T \fBvalue\fP)"
.br
.ti -1c
.RI "static bool \fBfits_in_int\fP (int)"
.br
.ti -1c
.RI "template<typename T > static bool \fBfits_in_int\fP (T \fBvalue\fP)"
.br
.ti -1c
.RI "static bool \fBfits_in_int\fP (int)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
