.TH "Interface" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interface
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMock\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBVoidFromString\fP (char *str)=0"
.br
.ti -1c
.RI "virtual char * \fBStringFromString\fP (char *str)=0"
.br
.ti -1c
.RI "virtual int \fBIntFromString\fP (char *str)=0"
.br
.ti -1c
.RI "virtual int & \fBIntRefFromString\fP (char *str)=0"
.br
.ti -1c
.RI "virtual void \fBVoidFromFunc\fP (void(*func)(char *str))=0"
.br
.ti -1c
.RI "virtual void \fBVoidFromIntRef\fP (int &n)=0"
.br
.ti -1c
.RI "virtual void \fBVoidFromFloat\fP (float n)=0"
.br
.ti -1c
.RI "virtual void \fBVoidFromDouble\fP (double n)=0"
.br
.ti -1c
.RI "virtual void \fBVoidFromVector\fP (const std::vector< int > &v)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
