.TH "internal_state" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "z_streamp \fBstrm\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.ti -1c
.RI "Bytef * \fBpending_buf\fP"
.br
.ti -1c
.RI "ulg \fBpending_buf_size\fP"
.br
.ti -1c
.RI "Bytef * \fBpending_out\fP"
.br
.ti -1c
.RI "ulg \fBpending\fP"
.br
.ti -1c
.RI "int \fBwrap\fP"
.br
.ti -1c
.RI "gz_headerp \fBgzhead\fP"
.br
.ti -1c
.RI "ulg \fBgzindex\fP"
.br
.ti -1c
.RI "Byte \fBmethod\fP"
.br
.ti -1c
.RI "int \fBlast_flush\fP"
.br
.ti -1c
.RI "uInt \fBw_size\fP"
.br
.ti -1c
.RI "uInt \fBw_bits\fP"
.br
.ti -1c
.RI "uInt \fBw_mask\fP"
.br
.ti -1c
.RI "Bytef * \fBwindow\fP"
.br
.ti -1c
.RI "ulg \fBwindow_size\fP"
.br
.ti -1c
.RI "Posf * \fBprev\fP"
.br
.ti -1c
.RI "Posf * \fBhead\fP"
.br
.ti -1c
.RI "uInt \fBins_h\fP"
.br
.ti -1c
.RI "uInt \fBhash_size\fP"
.br
.ti -1c
.RI "uInt \fBhash_bits\fP"
.br
.ti -1c
.RI "uInt \fBhash_mask\fP"
.br
.ti -1c
.RI "uInt \fBhash_shift\fP"
.br
.ti -1c
.RI "long \fBblock_start\fP"
.br
.ti -1c
.RI "uInt \fBmatch_length\fP"
.br
.ti -1c
.RI "IPos \fBprev_match\fP"
.br
.ti -1c
.RI "int \fBmatch_available\fP"
.br
.ti -1c
.RI "uInt \fBstrstart\fP"
.br
.ti -1c
.RI "uInt \fBmatch_start\fP"
.br
.ti -1c
.RI "uInt \fBlookahead\fP"
.br
.ti -1c
.RI "uInt \fBprev_length\fP"
.br
.ti -1c
.RI "uInt \fBmax_chain_length\fP"
.br
.ti -1c
.RI "uInt \fBmax_lazy_match\fP"
.br
.ti -1c
.RI "int \fBlevel\fP"
.br
.ti -1c
.RI "int \fBstrategy\fP"
.br
.ti -1c
.RI "uInt \fBgood_match\fP"
.br
.ti -1c
.RI "int \fBnice_match\fP"
.br
.ti -1c
.RI "struct \fBct_data_s\fP \fBdyn_ltree\fP [HEAP_SIZE]"
.br
.ti -1c
.RI "struct \fBct_data_s\fP \fBdyn_dtree\fP [2 *D_CODES+1]"
.br
.ti -1c
.RI "struct \fBct_data_s\fP \fBbl_tree\fP [2 *BL_CODES+1]"
.br
.ti -1c
.RI "struct \fBtree_desc_s\fP \fBl_desc\fP"
.br
.ti -1c
.RI "struct \fBtree_desc_s\fP \fBd_desc\fP"
.br
.ti -1c
.RI "struct \fBtree_desc_s\fP \fBbl_desc\fP"
.br
.ti -1c
.RI "ush \fBbl_count\fP [MAX_BITS+1]"
.br
.ti -1c
.RI "int \fBheap\fP [2 *L_CODES+1]"
.br
.ti -1c
.RI "int \fBheap_len\fP"
.br
.ti -1c
.RI "int \fBheap_max\fP"
.br
.ti -1c
.RI "uch \fBdepth\fP [2 *L_CODES+1]"
.br
.ti -1c
.RI "uchf * \fBl_buf\fP"
.br
.ti -1c
.RI "uInt \fBlit_bufsize\fP"
.br
.ti -1c
.RI "uInt \fBlast_lit\fP"
.br
.ti -1c
.RI "ushf * \fBd_buf\fP"
.br
.ti -1c
.RI "ulg \fBopt_len\fP"
.br
.ti -1c
.RI "ulg \fBstatic_len\fP"
.br
.ti -1c
.RI "uInt \fBmatches\fP"
.br
.ti -1c
.RI "uInt \fBinsert\fP"
.br
.ti -1c
.RI "ush \fBbi_buf\fP"
.br
.ti -1c
.RI "int \fBbi_valid\fP"
.br
.ti -1c
.RI "ulg \fBhigh_water\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
