.TH "IntWrapper" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntWrapper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntWrapper\fP (int a_value)"
.br
.ti -1c
.RI "\fBIntWrapper\fP (const \fBIntWrapper\fP &other)"
.br
.ti -1c
.RI "\fBIntWrapper\fP \fBoperator=\fP (const \fBIntWrapper\fP &other)"
.br
.ti -1c
.RI "\fBIntWrapper\fP \fBoperator+\fP (int other) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBIntWrapper\fP &other) const"
.br
.ti -1c
.RI "int \fBvalue\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
