.TH "InvokeHelper" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvokeHelper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVoidFromVoid\fP ()"
.br
.ti -1c
.RI "void \fBVoidFromString\fP (char *)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBStaticVoidFromVoid\fP ()"
.br
.ti -1c
.RI "static void \fBStaticVoidFromString\fP (char *)"
.br
.ti -1c
.RI "static int \fBStaticIntFromString\fP (char *)"
.br
.ti -1c
.RI "static bool \fBStaticBoolFromString\fP (const char *)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
