.TH "IPpmd7" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPpmd7
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBPpmd7_Construct\fP )(\fBCPpmd7\fP *p)"
.br
.ti -1c
.RI "\fBBool\fP(* \fBPpmd7_Alloc\fP )(\fBCPpmd7\fP *p, UInt32 size)"
.br
.ti -1c
.RI "void(* \fBPpmd7_Free\fP )(\fBCPpmd7\fP *p)"
.br
.ti -1c
.RI "void(* \fBPpmd7_Init\fP )(\fBCPpmd7\fP *p, unsigned maxOrder)"
.br
.ti -1c
.RI "void(* \fBPpmd7z_RangeDec_CreateVTable\fP )(\fBCPpmd7z_RangeDec\fP *p)"
.br
.ti -1c
.RI "void(* \fBPpmdRAR_RangeDec_CreateVTable\fP )(\fBCPpmd7z_RangeDec\fP *p)"
.br
.ti -1c
.RI "\fBBool\fP(* \fBPpmd7z_RangeDec_Init\fP )(\fBCPpmd7z_RangeDec\fP *p)"
.br
.ti -1c
.RI "\fBBool\fP(* \fBPpmdRAR_RangeDec_Init\fP )(\fBCPpmd7z_RangeDec\fP *p)"
.br
.ti -1c
.RI "int(* \fBPpmd7_DecodeSymbol\fP )(\fBCPpmd7\fP *p, \fBIPpmd7_RangeDec\fP *rc)"
.br
.ti -1c
.RI "void(* \fBPpmd7z_RangeEnc_Init\fP )(\fBCPpmd7z_RangeEnc\fP *p)"
.br
.ti -1c
.RI "void(* \fBPpmd7z_RangeEnc_FlushData\fP )(\fBCPpmd7z_RangeEnc\fP *p)"
.br
.ti -1c
.RI "void(* \fBPpmd7_EncodeSymbol\fP )(\fBCPpmd7\fP *p, \fBCPpmd7z_RangeEnc\fP *rc, int symbol)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
