.TH "IPpmd8" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPpmd8
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBPpmd8_Construct\fP )(\fBCPpmd8\fP *p)"
.br
.ti -1c
.RI "\fBBool\fP(* \fBPpmd8_Alloc\fP )(\fBCPpmd8\fP *p, UInt32 size)"
.br
.ti -1c
.RI "void(* \fBPpmd8_Free\fP )(\fBCPpmd8\fP *p)"
.br
.ti -1c
.RI "void(* \fBPpmd8_Init\fP )(\fBCPpmd8\fP *p, unsigned max_order, unsigned restore_method)"
.br
.ti -1c
.RI "int(* \fBPpmd8_RangeDec_Init\fP )(\fBCPpmd8\fP *p)"
.br
.ti -1c
.RI "int(* \fBPpmd8_DecodeSymbol\fP )(\fBCPpmd8\fP *p)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
