.TH "IPpmd7_RangeDec" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPpmd7_RangeDec
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UInt32(* \fBGetThreshold\fP )(void *p, UInt32 total)"
.br
.ti -1c
.RI "void(* \fBDecode\fP )(void *p, UInt32 start, UInt32 size)"
.br
.ti -1c
.RI "UInt32(* \fBDecodeBit\fP )(void *p, UInt32 size0)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
