.TH "IProgram" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IProgram
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTutorial_0\fP, \fBTutorial_1\fP, \fBTutorial_2\fP, \fBTutorial_3\fP, \fBTutorial_4\fP, and \fBTutorial_5\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBIProgram\fP (const \fBIProgram\fP &) noexcept=default"
.br
.ti -1c
.RI "constexpr \fBIProgram\fP (\fBIProgram\fP &&) noexcept=default"
.br
.ti -1c
.RI "\fBIProgram\fP & \fBoperator=\fP (const \fBIProgram\fP &) noexcept=default"
.br
.ti -1c
.RI "\fBIProgram\fP & \fBoperator=\fP (\fBIProgram\fP &&) noexcept=default"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBDraw\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBImGuiDraw\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBHandleEvent\fP (SDL_Window &sdl_window, const \fBSDL_Event\fP &event)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
