.TH "is_char< T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_char< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core\&.h>\fP
.PP
Inherits std::false_type\&.
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
struct is_char< T >"Specifies if \fCT\fP is a character type\&. Can be specialized by users\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
