.TH "is_char< detail::char8_type >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_char< detail::char8_type >
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::true_type\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
