.TH "is_range< T, Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_range< T, Char >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr const bool \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename T , typename Char > static constexpr const bool \fBis_range\fP< T, Char >\fB::value\fP\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
      detail::is_range_<T>::value && !detail::is_std_string_like<T>::value &&
      !std::is_convertible<T, std::basic_string<Char>>::value &&
      !std::is_convertible<T, detail::std_string_view<Char>>::value
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
