.TH "is_tuple_formattable< T, C >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
is_tuple_formattable< T, C >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr const bool \fBvalue\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<typename T , typename C > static constexpr const bool \fBis_tuple_formattable\fP< T, C >\fB::value\fP\fC [static]\fP, \fC [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
=
      detail::is_tuple_formattable_<T, C>::value
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
