.TH "iso9660::vdd" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iso9660::vdd
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBpath_table\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBvdd_type\fP { \fBVDD_PRIMARY\fP, \fBVDD_JOLIET\fP, \fBVDD_ENHANCED\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisoent\fP * \fBrootent\fP"
.br
.ti -1c
.RI "enum iso9660::vdd::vdd_type \fBvdd_type\fP"
.br
.ti -1c
.RI "struct \fBiso9660::vdd::path_table\fP * \fBpathtbl\fP"
.br
.ti -1c
.RI "int \fBmax_depth\fP"
.br
.ti -1c
.RI "int \fBpath_table_block\fP"
.br
.ti -1c
.RI "int \fBpath_table_size\fP"
.br
.ti -1c
.RI "int \fBlocation_type_L_path_table\fP"
.br
.ti -1c
.RI "int \fBlocation_type_M_path_table\fP"
.br
.ti -1c
.RI "int \fBtotal_dir_block\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
