.TH "iso9660::vdd::path_table" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iso9660::vdd::path_table
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisoent\fP * \fBfirst\fP"
.br
.ti -1c
.RI "struct \fBisoent\fP ** \fBlast\fP"
.br
.ti -1c
.RI "struct \fBisoent\fP ** \fBsorted\fP"
.br
.ti -1c
.RI "int \fBcnt\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
