.TH "iso9660" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iso9660
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBread_ce_queue\fP"
.br
.ti -1c
.RI "struct \fBvd\fP"
.br
.ti -1c
.RI "struct \fBvdd\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBWB_TO_STREAM\fP, \fBWB_TO_TEMP\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmagic\fP"
.br
.ti -1c
.RI "int \fBopt_support_joliet\fP"
.br
.ti -1c
.RI "int \fBopt_support_rockridge\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBpathname\fP"
.br
.ti -1c
.RI "char \fBseenRockridge\fP"
.br
.ti -1c
.RI "char \fBseenSUSP\fP"
.br
.ti -1c
.RI "char \fBseenJoliet\fP"
.br
.ti -1c
.RI "unsigned char \fBsuspOffset\fP"
.br
.ti -1c
.RI "struct \fBfile_info\fP * \fBrr_moved\fP"
.br
.ti -1c
.RI "struct \fBiso9660::read_ce_queue\fP \fBread_ce_req\fP"
.br
.ti -1c
.RI "int64_t \fBprevious_number\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBprevious_pathname\fP"
.br
.ti -1c
.RI "struct \fBfile_info\fP * \fBuse_files\fP"
.br
.ti -1c
.RI "struct \fBheap_queue\fP \fBpending_files\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBfile_info\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBfile_info\fP ** \fBlast\fP"
.br
.ti -1c
.RI "} \fBcache_files\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBfile_info\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBfile_info\fP ** \fBlast\fP"
.br
.ti -1c
.RI "} \fBre_files\fP"
.br
.ti -1c
.RI "uint64_t \fBcurrent_position\fP"
.br
.ti -1c
.RI "ssize_t \fBlogical_block_size\fP"
.br
.ti -1c
.RI "uint64_t \fBvolume_size\fP"
.br
.ti -1c
.RI "int32_t \fBvolume_block\fP"
.br
.ti -1c
.RI "struct \fBiso9660::vd\fP \fBprimary\fP"
.br
.ti -1c
.RI "struct \fBiso9660::vd\fP \fBjoliet\fP"
.br
.ti -1c
.RI "int64_t \fBentry_sparse_offset\fP"
.br
.ti -1c
.RI "int64_t \fBentry_bytes_remaining\fP"
.br
.ti -1c
.RI "size_t \fBentry_bytes_unconsumed\fP"
.br
.ti -1c
.RI "struct \fBzisofs\fP \fBentry_zisofs\fP"
.br
.ti -1c
.RI "struct \fBcontent\fP * \fBentry_content\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_utf16be\fP"
.br
.ti -1c
.RI "unsigned char * \fButf16be_path\fP"
.br
.ti -1c
.RI "size_t \fButf16be_path_len\fP"
.br
.ti -1c
.RI "unsigned char * \fButf16be_previous_path\fP"
.br
.ti -1c
.RI "size_t \fButf16be_previous_path_len\fP"
.br
.ti -1c
.RI "unsigned char \fBnull\fP [2048]"
.br
.ti -1c
.RI "time_t \fBbirth_time\fP"
.br
.ti -1c
.RI "int \fBtemp_fd\fP"
.br
.ti -1c
.RI "struct \fBisofile\fP * \fBcur_file\fP"
.br
.ti -1c
.RI "struct \fBisoent\fP * \fBcur_dirent\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBcur_dirstr\fP"
.br
.ti -1c
.RI "uint64_t \fBbytes_remaining\fP"
.br
.ti -1c
.RI "int \fBneed_multi_extent\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fButf16be\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBmbs\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_to_utf16be\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_from_utf16be\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBisofile\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBisofile\fP ** \fBlast\fP"
.br
.ti -1c
.RI "} \fBall_file_list\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBisofile\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBisofile\fP ** \fBlast\fP"
.br
.ti -1c
.RI "} \fBdata_file_list\fP"
.br
.ti -1c
.RI "struct \fBarchive_rb_tree\fP \fBhardlink_rbtree\fP"
.br
.ti -1c
.RI "struct \fBiso9660::vdd\fP \fBprimary\fP"
.br
.ti -1c
.RI "struct \fBiso9660::vdd\fP \fBjoliet\fP"
.br
.ti -1c
.RI "int \fBvolume_space_size\fP"
.br
.ti -1c
.RI "int \fBvolume_sequence_number\fP"
.br
.ti -1c
.RI "int \fBtotal_file_block\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBvolume_identifier\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBpublisher_identifier\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBdata_preparer_identifier\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBapplication_identifier\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBcopyright_file_identifier\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBabstract_file_identifier\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBbibliographic_file_identifier\fP"
.br
.ti -1c
.RI "int \fBlocation_rrip_er\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   signed int \fBdetect_magic\fP:1"
.br
.ti -1c
.RI "   signed int \fBmaking\fP:1"
.br
.ti -1c
.RI "   signed int \fBallzero\fP:1"
.br
.ti -1c
.RI "   unsigned char \fBmagic_buffer\fP [64]"
.br
.ti -1c
.RI "   int \fBmagic_cnt\fP"
.br
.ti -1c
.RI "} \fBzisofs\fP"
.br
.ti -1c
.RI "struct \fBisoent\fP * \fBdirectories_too_deep\fP"
.br
.ti -1c
.RI "int \fBdircnt_max\fP"
.br
.ti -1c
.RI "unsigned char \fBwbuff\fP [LOGICAL_BLOCK_SIZE *32]"
.br
.ti -1c
.RI "size_t \fBwbuff_remaining\fP"
.br
.ti -1c
.RI "enum iso9660:: { \&.\&.\&. }  \fBwbuff_type\fP"
.br
.ti -1c
.RI "int64_t \fBwbuff_offset\fP"
.br
.ti -1c
.RI "int64_t \fBwbuff_written\fP"
.br
.ti -1c
.RI "int64_t \fBwbuff_tail\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBarchive_string\fP \fBcatalog_filename\fP"
.br
.ti -1c
.RI "   struct \fBisoent\fP * \fBcatalog\fP"
.br
.ti -1c
.RI "   struct \fBarchive_string\fP \fBboot_filename\fP"
.br
.ti -1c
.RI "   struct \fBisoent\fP * \fBboot\fP"
.br
.ti -1c
.RI "   unsigned char \fBplatform_id\fP"
.br
.ti -1c
.RI "   struct \fBarchive_string\fP \fBid\fP"
.br
.ti -1c
.RI "   unsigned char \fBmedia_type\fP"
.br
.ti -1c
.RI "   unsigned char \fBsystem_type\fP"
.br
.ti -1c
.RI "   uint16_t \fBboot_load_seg\fP"
.br
.ti -1c
.RI "   uint16_t \fBboot_load_size\fP"
.br
.ti -1c
.RI "} \fBel_torito\fP"
.br
.ti -1c
.RI "struct \fBiso_option\fP \fBopt\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
