.TH "iso_option" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iso_option
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBabstract_file\fP:1"
.br
.ti -1c
.RI "unsigned int \fBapplication_id\fP:1"
.br
.ti -1c
.RI "unsigned int \fBallow_vernum\fP:1"
.br
.ti -1c
.RI "unsigned int \fBbiblio_file\fP:1"
.br
.ti -1c
.RI "unsigned int \fBboot\fP:1"
.br
.ti -1c
.RI "unsigned int \fBboot_catalog\fP:1"
.br
.ti -1c
.RI "unsigned int \fBboot_info_table\fP:1"
.br
.ti -1c
.RI "unsigned int \fBboot_load_seg\fP:1"
.br
.ti -1c
.RI "unsigned int \fBboot_load_size\fP:1"
.br
.ti -1c
.RI "unsigned int \fBboot_type\fP:2"
.br
.ti -1c
.RI "unsigned int \fBcompression_level\fP:1"
.br
.ti -1c
.RI "unsigned int \fBcopyright_file\fP:1"
.br
.ti -1c
.RI "unsigned int \fBgid\fP:1"
.br
.ti -1c
.RI "unsigned int \fBiso_level\fP:3"
.br
.ti -1c
.RI "unsigned int \fBjoliet\fP:2"
.br
.ti -1c
.RI "unsigned int \fBlimit_depth\fP:1"
.br
.ti -1c
.RI "unsigned int \fBlimit_dirs\fP:1"
.br
.ti -1c
.RI "unsigned int \fBpad\fP:1"
.br
.ti -1c
.RI "unsigned int \fBpublisher\fP:1"
.br
.ti -1c
.RI "unsigned int \fBrr\fP:2"
.br
.ti -1c
.RI "unsigned int \fBvolume_id\fP:1"
.br
.ti -1c
.RI "unsigned int \fBzisofs\fP:1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
