.TH "isoent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isoent
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive_rb_node\fP \fBrbnode\fP"
.br
.ti -1c
.RI "struct \fBisofile\fP * \fBfile\fP"
.br
.ti -1c
.RI "struct \fBisoent\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBisoent\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBisoent\fP ** \fBlast\fP"
.br
.ti -1c
.RI "   int \fBcnt\fP"
.br
.ti -1c
.RI "} \fBchildren\fP"
.br
.ti -1c
.RI "struct \fBarchive_rb_tree\fP \fBrbtree\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBisoent\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBisoent\fP ** \fBlast\fP"
.br
.ti -1c
.RI "   int \fBcnt\fP"
.br
.ti -1c
.RI "} \fBsubdirs\fP"
.br
.ti -1c
.RI "struct \fBisoent\fP ** \fBchildren_sorted\fP"
.br
.ti -1c
.RI "struct \fBisoent\fP * \fBchnext\fP"
.br
.ti -1c
.RI "struct \fBisoent\fP * \fBdrnext\fP"
.br
.ti -1c
.RI "struct \fBisoent\fP * \fBptnext\fP"
.br
.ti -1c
.RI "int \fBdir_number\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBvd\fP"
.br
.ti -1c
.RI "   int \fBself\fP"
.br
.ti -1c
.RI "   int \fBparent\fP"
.br
.ti -1c
.RI "   int \fBnormal\fP"
.br
.ti -1c
.RI "} \fBdr_len\fP"
.br
.ti -1c
.RI "uint32_t \fBdir_location\fP"
.br
.ti -1c
.RI "int \fBdir_block\fP"
.br
.ti -1c
.RI "char * \fBidentifier\fP"
.br
.ti -1c
.RI "int \fBext_off\fP"
.br
.ti -1c
.RI "int \fBext_len\fP"
.br
.ti -1c
.RI "int \fBid_len\fP"
.br
.ti -1c
.RI "int \fBmb_len\fP"
.br
.ti -1c
.RI "struct \fBisoent\fP * \fBrr_parent\fP"
.br
.ti -1c
.RI "struct \fBisoent\fP * \fBrr_child\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   struct \fBextr_rec\fP * \fBfirst\fP"
.br
.ti -1c
.RI "   struct \fBextr_rec\fP ** \fBlast\fP"
.br
.ti -1c
.RI "   struct \fBextr_rec\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "} \fBextr_rec_list\fP"
.br
.ti -1c
.RI "signed int \fBvirtual\fP:1"
.br
.ti -1c
.RI "signed int \fBdir\fP:1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
