.TH "isofile" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
isofile
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcontent\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBNO\fP = 0, \fBBOOT_CATALOG\fP, \fBBOOT_IMAGE\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBisofile\fP * \fBallnext\fP"
.br
.ti -1c
.RI "struct \fBisofile\fP * \fBdatanext\fP"
.br
.ti -1c
.RI "struct \fBisofile\fP * \fBhlnext\fP"
.br
.ti -1c
.RI "struct \fBisofile\fP * \fBhardlink_target\fP"
.br
.ti -1c
.RI "struct \fBarchive_entry\fP * \fBentry\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBparentdir\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBbasename\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBbasename_utf16\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBsymlink\fP"
.br
.ti -1c
.RI "int \fBdircnt\fP"
.br
.ti -1c
.RI "struct \fBisofile::content\fP \fBcontent\fP"
.br
.ti -1c
.RI "struct \fBisofile::content\fP * \fBcur_content\fP"
.br
.ti -1c
.RI "int \fBwrite_content\fP"
.br
.ti -1c
.RI "enum isofile:: { \&.\&.\&. }  \fBboot\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   unsigned char \fBheader_size\fP"
.br
.ti -1c
.RI "   unsigned char \fBlog2_bs\fP"
.br
.ti -1c
.RI "   uint32_t \fBuncompressed_size\fP"
.br
.ti -1c
.RI "} \fBzisofs\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
