.TH "izstream" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
izstream
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBizstream\fP (FILE *\fBfp\fP)"
.br
.ti -1c
.RI "\fBizstream\fP (const char *name)"
.br
.ti -1c
.RI "void \fBopen\fP (const char *name)"
.br
.ti -1c
.RI "void \fBopen\fP (FILE *\fBfp\fP)"
.br
.ti -1c
.RI "int \fBclose\fP ()"
.br
.ti -1c
.RI "int \fBread\fP (void *\fBbuf\fP, size_t len)"
.br
.ti -1c
.RI "const char * \fBerror\fP (int *errnum)"
.br
.ti -1c
.RI "\fBgzFile\fP \fBfp\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
