.TH "jpeg_marker_writer" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_marker_writer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, write_file_header,(\fBj_compress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, write_frame_header,(\fBj_compress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, write_scan_header,(\fBj_compress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, write_file_trailer,(\fBj_compress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, write_tables_only,(\fBj_compress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, write_marker_header,(\fBj_compress_ptr\fP cinfo, int marker, unsigned int datalen))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, write_marker_byte,(\fBj_compress_ptr\fP cinfo, int val))"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
