.TH "jpeg_entropy_encoder" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_entropy_encoder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, start_pass,(\fBj_compress_ptr\fP cinfo, boolean gather_statistics))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (boolean, encode_mcu,(\fBj_compress_ptr\fP cinfo, JBLOCKROW *MCU_data))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, finish_pass,(\fBj_compress_ptr\fP cinfo))"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
