.TH "jpeg_compress_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_compress_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBjpeg_common_fields\fP"
.br
.ti -1c
.RI "struct \fBjpeg_destination_mgr\fP * \fBdest\fP"
.br
.ti -1c
.RI "JDIMENSION \fBimage_width\fP"
.br
.ti -1c
.RI "JDIMENSION \fBimage_height\fP"
.br
.ti -1c
.RI "int \fBinput_components\fP"
.br
.ti -1c
.RI "J_COLOR_SPACE \fBin_color_space\fP"
.br
.ti -1c
.RI "double \fBinput_gamma\fP"
.br
.ti -1c
.RI "int \fBdata_precision\fP"
.br
.ti -1c
.RI "int \fBnum_components\fP"
.br
.ti -1c
.RI "J_COLOR_SPACE \fBjpeg_color_space\fP"
.br
.ti -1c
.RI "\fBjpeg_component_info\fP * \fBcomp_info\fP"
.br
.ti -1c
.RI "\fBJQUANT_TBL\fP * \fBquant_tbl_ptrs\fP [NUM_QUANT_TBLS]"
.br
.ti -1c
.RI "\fBJHUFF_TBL\fP * \fBdc_huff_tbl_ptrs\fP [NUM_HUFF_TBLS]"
.br
.ti -1c
.RI "\fBJHUFF_TBL\fP * \fBac_huff_tbl_ptrs\fP [NUM_HUFF_TBLS]"
.br
.ti -1c
.RI "UINT8 \fBarith_dc_L\fP [NUM_ARITH_TBLS]"
.br
.ti -1c
.RI "UINT8 \fBarith_dc_U\fP [NUM_ARITH_TBLS]"
.br
.ti -1c
.RI "UINT8 \fBarith_ac_K\fP [NUM_ARITH_TBLS]"
.br
.ti -1c
.RI "int \fBnum_scans\fP"
.br
.ti -1c
.RI "const \fBjpeg_scan_info\fP * \fBscan_info\fP"
.br
.ti -1c
.RI "boolean \fBraw_data_in\fP"
.br
.ti -1c
.RI "boolean \fBarith_code\fP"
.br
.ti -1c
.RI "boolean \fBoptimize_coding\fP"
.br
.ti -1c
.RI "boolean \fBCCIR601_sampling\fP"
.br
.ti -1c
.RI "int \fBsmoothing_factor\fP"
.br
.ti -1c
.RI "J_DCT_METHOD \fBdct_method\fP"
.br
.ti -1c
.RI "unsigned int \fBrestart_interval\fP"
.br
.ti -1c
.RI "int \fBrestart_in_rows\fP"
.br
.ti -1c
.RI "boolean \fBwrite_JFIF_header\fP"
.br
.ti -1c
.RI "UINT8 \fBJFIF_major_version\fP"
.br
.ti -1c
.RI "UINT8 \fBJFIF_minor_version\fP"
.br
.ti -1c
.RI "UINT8 \fBdensity_unit\fP"
.br
.ti -1c
.RI "UINT16 \fBX_density\fP"
.br
.ti -1c
.RI "UINT16 \fBY_density\fP"
.br
.ti -1c
.RI "boolean \fBwrite_Adobe_marker\fP"
.br
.ti -1c
.RI "JDIMENSION \fBnext_scanline\fP"
.br
.ti -1c
.RI "boolean \fBprogressive_mode\fP"
.br
.ti -1c
.RI "int \fBmax_h_samp_factor\fP"
.br
.ti -1c
.RI "int \fBmax_v_samp_factor\fP"
.br
.ti -1c
.RI "JDIMENSION \fBtotal_iMCU_rows\fP"
.br
.ti -1c
.RI "int \fBcomps_in_scan\fP"
.br
.ti -1c
.RI "\fBjpeg_component_info\fP * \fBcur_comp_info\fP [MAX_COMPS_IN_SCAN]"
.br
.ti -1c
.RI "JDIMENSION \fBMCUs_per_row\fP"
.br
.ti -1c
.RI "JDIMENSION \fBMCU_rows_in_scan\fP"
.br
.ti -1c
.RI "int \fBblocks_in_MCU\fP"
.br
.ti -1c
.RI "int \fBMCU_membership\fP [C_MAX_BLOCKS_IN_MCU]"
.br
.ti -1c
.RI "int \fBSs\fP"
.br
.ti -1c
.RI "int \fBSe\fP"
.br
.ti -1c
.RI "int \fBAh\fP"
.br
.ti -1c
.RI "int \fBAl\fP"
.br
.ti -1c
.RI "struct \fBjpeg_comp_master\fP * \fBmaster\fP"
.br
.ti -1c
.RI "struct \fBjpeg_c_main_controller\fP * \fBmain\fP"
.br
.ti -1c
.RI "struct \fBjpeg_c_prep_controller\fP * \fBprep\fP"
.br
.ti -1c
.RI "struct \fBjpeg_c_coef_controller\fP * \fBcoef\fP"
.br
.ti -1c
.RI "struct \fBjpeg_marker_writer\fP * \fBmarker\fP"
.br
.ti -1c
.RI "struct \fBjpeg_color_converter\fP * \fBcconvert\fP"
.br
.ti -1c
.RI "struct \fBjpeg_downsampler\fP * \fBdownsample\fP"
.br
.ti -1c
.RI "struct \fBjpeg_forward_dct\fP * \fBfdct\fP"
.br
.ti -1c
.RI "struct \fBjpeg_entropy_encoder\fP * \fBentropy\fP"
.br
.ti -1c
.RI "\fBjpeg_scan_info\fP * \fBscript_space\fP"
.br
.ti -1c
.RI "int \fBscript_space_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
