.TH "jpeg_comp_master" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_comp_master
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, prepare_for_pass,(\fBj_compress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, pass_startup,(\fBj_compress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, finish_pass,(\fBj_compress_ptr\fP cinfo))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boolean \fBcall_pass_startup\fP"
.br
.ti -1c
.RI "boolean \fBis_last_pass\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
