.TH "jpeg_decompress_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_decompress_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBjpeg_common_fields\fP"
.br
.ti -1c
.RI "struct \fBjpeg_source_mgr\fP * \fBsrc\fP"
.br
.ti -1c
.RI "JDIMENSION \fBimage_width\fP"
.br
.ti -1c
.RI "JDIMENSION \fBimage_height\fP"
.br
.ti -1c
.RI "int \fBnum_components\fP"
.br
.ti -1c
.RI "J_COLOR_SPACE \fBjpeg_color_space\fP"
.br
.ti -1c
.RI "J_COLOR_SPACE \fBout_color_space\fP"
.br
.ti -1c
.RI "unsigned int \fBscale_num\fP"
.br
.ti -1c
.RI "unsigned int \fBscale_denom\fP"
.br
.ti -1c
.RI "double \fBoutput_gamma\fP"
.br
.ti -1c
.RI "boolean \fBbuffered_image\fP"
.br
.ti -1c
.RI "boolean \fBraw_data_out\fP"
.br
.ti -1c
.RI "J_DCT_METHOD \fBdct_method\fP"
.br
.ti -1c
.RI "boolean \fBdo_fancy_upsampling\fP"
.br
.ti -1c
.RI "boolean \fBdo_block_smoothing\fP"
.br
.ti -1c
.RI "boolean \fBquantize_colors\fP"
.br
.ti -1c
.RI "J_DITHER_MODE \fBdither_mode\fP"
.br
.ti -1c
.RI "boolean \fBtwo_pass_quantize\fP"
.br
.ti -1c
.RI "int \fBdesired_number_of_colors\fP"
.br
.ti -1c
.RI "boolean \fBenable_1pass_quant\fP"
.br
.ti -1c
.RI "boolean \fBenable_external_quant\fP"
.br
.ti -1c
.RI "boolean \fBenable_2pass_quant\fP"
.br
.ti -1c
.RI "JDIMENSION \fBoutput_width\fP"
.br
.ti -1c
.RI "JDIMENSION \fBoutput_height\fP"
.br
.ti -1c
.RI "int \fBout_color_components\fP"
.br
.ti -1c
.RI "int \fBoutput_components\fP"
.br
.ti -1c
.RI "int \fBrec_outbuf_height\fP"
.br
.ti -1c
.RI "int \fBactual_number_of_colors\fP"
.br
.ti -1c
.RI "JSAMPARRAY \fBcolormap\fP"
.br
.ti -1c
.RI "JDIMENSION \fBoutput_scanline\fP"
.br
.ti -1c
.RI "int \fBinput_scan_number\fP"
.br
.ti -1c
.RI "JDIMENSION \fBinput_iMCU_row\fP"
.br
.ti -1c
.RI "int \fBoutput_scan_number\fP"
.br
.ti -1c
.RI "JDIMENSION \fBoutput_iMCU_row\fP"
.br
.ti -1c
.RI "int(* \fBcoef_bits\fP )[DCTSIZE2]"
.br
.ti -1c
.RI "\fBJQUANT_TBL\fP * \fBquant_tbl_ptrs\fP [NUM_QUANT_TBLS]"
.br
.ti -1c
.RI "\fBJHUFF_TBL\fP * \fBdc_huff_tbl_ptrs\fP [NUM_HUFF_TBLS]"
.br
.ti -1c
.RI "\fBJHUFF_TBL\fP * \fBac_huff_tbl_ptrs\fP [NUM_HUFF_TBLS]"
.br
.ti -1c
.RI "int \fBdata_precision\fP"
.br
.ti -1c
.RI "\fBjpeg_component_info\fP * \fBcomp_info\fP"
.br
.ti -1c
.RI "boolean \fBprogressive_mode\fP"
.br
.ti -1c
.RI "boolean \fBarith_code\fP"
.br
.ti -1c
.RI "UINT8 \fBarith_dc_L\fP [NUM_ARITH_TBLS]"
.br
.ti -1c
.RI "UINT8 \fBarith_dc_U\fP [NUM_ARITH_TBLS]"
.br
.ti -1c
.RI "UINT8 \fBarith_ac_K\fP [NUM_ARITH_TBLS]"
.br
.ti -1c
.RI "unsigned int \fBrestart_interval\fP"
.br
.ti -1c
.RI "boolean \fBsaw_JFIF_marker\fP"
.br
.ti -1c
.RI "UINT8 \fBJFIF_major_version\fP"
.br
.ti -1c
.RI "UINT8 \fBJFIF_minor_version\fP"
.br
.ti -1c
.RI "UINT8 \fBdensity_unit\fP"
.br
.ti -1c
.RI "UINT16 \fBX_density\fP"
.br
.ti -1c
.RI "UINT16 \fBY_density\fP"
.br
.ti -1c
.RI "boolean \fBsaw_Adobe_marker\fP"
.br
.ti -1c
.RI "UINT8 \fBAdobe_transform\fP"
.br
.ti -1c
.RI "boolean \fBCCIR601_sampling\fP"
.br
.ti -1c
.RI "jpeg_saved_marker_ptr \fBmarker_list\fP"
.br
.ti -1c
.RI "int \fBmax_h_samp_factor\fP"
.br
.ti -1c
.RI "int \fBmax_v_samp_factor\fP"
.br
.ti -1c
.RI "int \fBmin_DCT_scaled_size\fP"
.br
.ti -1c
.RI "JDIMENSION \fBtotal_iMCU_rows\fP"
.br
.ti -1c
.RI "JSAMPLE * \fBsample_range_limit\fP"
.br
.ti -1c
.RI "int \fBcomps_in_scan\fP"
.br
.ti -1c
.RI "\fBjpeg_component_info\fP * \fBcur_comp_info\fP [MAX_COMPS_IN_SCAN]"
.br
.ti -1c
.RI "JDIMENSION \fBMCUs_per_row\fP"
.br
.ti -1c
.RI "JDIMENSION \fBMCU_rows_in_scan\fP"
.br
.ti -1c
.RI "int \fBblocks_in_MCU\fP"
.br
.ti -1c
.RI "int \fBMCU_membership\fP [D_MAX_BLOCKS_IN_MCU]"
.br
.ti -1c
.RI "int \fBSs\fP"
.br
.ti -1c
.RI "int \fBSe\fP"
.br
.ti -1c
.RI "int \fBAh\fP"
.br
.ti -1c
.RI "int \fBAl\fP"
.br
.ti -1c
.RI "int \fBunread_marker\fP"
.br
.ti -1c
.RI "struct \fBjpeg_decomp_master\fP * \fBmaster\fP"
.br
.ti -1c
.RI "struct \fBjpeg_d_main_controller\fP * \fBmain\fP"
.br
.ti -1c
.RI "struct \fBjpeg_d_coef_controller\fP * \fBcoef\fP"
.br
.ti -1c
.RI "struct \fBjpeg_d_post_controller\fP * \fBpost\fP"
.br
.ti -1c
.RI "struct \fBjpeg_input_controller\fP * \fBinputctl\fP"
.br
.ti -1c
.RI "struct \fBjpeg_marker_reader\fP * \fBmarker\fP"
.br
.ti -1c
.RI "struct \fBjpeg_entropy_decoder\fP * \fBentropy\fP"
.br
.ti -1c
.RI "struct \fBjpeg_inverse_dct\fP * \fBidct\fP"
.br
.ti -1c
.RI "struct \fBjpeg_upsampler\fP * \fBupsample\fP"
.br
.ti -1c
.RI "struct \fBjpeg_color_deconverter\fP * \fBcconvert\fP"
.br
.ti -1c
.RI "struct \fBjpeg_color_quantizer\fP * \fBcquantize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
