.TH "jpeg_memory_mgr" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_memory_mgr
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void *, alloc_small,(\fBj_common_ptr\fP cinfo, int pool_id, size_t sizeofobject))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void FAR *, alloc_large,(\fBj_common_ptr\fP cinfo, int pool_id, size_t sizeofobject))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (JSAMPARRAY, alloc_sarray,(\fBj_common_ptr\fP cinfo, int pool_id, JDIMENSION samplesperrow, JDIMENSION numrows))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (JBLOCKARRAY, alloc_barray,(\fBj_common_ptr\fP cinfo, int pool_id, JDIMENSION blocksperrow, JDIMENSION numrows))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (\fBjvirt_sarray_ptr\fP, request_virt_sarray,(\fBj_common_ptr\fP cinfo, int pool_id, boolean pre_zero, JDIMENSION samplesperrow, JDIMENSION numrows, JDIMENSION maxaccess))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (\fBjvirt_barray_ptr\fP, request_virt_barray,(\fBj_common_ptr\fP cinfo, int pool_id, boolean pre_zero, JDIMENSION blocksperrow, JDIMENSION numrows, JDIMENSION maxaccess))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, realize_virt_arrays,(\fBj_common_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (JSAMPARRAY, access_virt_sarray,(\fBj_common_ptr\fP cinfo, \fBjvirt_sarray_ptr\fP ptr, JDIMENSION start_row, JDIMENSION num_rows, boolean writable))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (JBLOCKARRAY, access_virt_barray,(\fBj_common_ptr\fP cinfo, \fBjvirt_barray_ptr\fP ptr, JDIMENSION start_row, JDIMENSION num_rows, boolean writable))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, free_pool,(\fBj_common_ptr\fP cinfo, int pool_id))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, self_destruct,(\fBj_common_ptr\fP cinfo))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBmax_memory_to_use\fP"
.br
.ti -1c
.RI "long \fBmax_alloc_chunk\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
