.TH "jpeg_d_coef_controller" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_d_coef_controller
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, start_input_pass,(\fBj_decompress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (int, consume_data,(\fBj_decompress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, start_output_pass,(\fBj_decompress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (int, decompress_data,(\fBj_decompress_ptr\fP cinfo, JSAMPIMAGE output_buf))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBjvirt_barray_ptr\fP * \fBcoef_arrays\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
