.TH "jpeg_error_mgr" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_error_mgr
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, error_exit,(\fBj_common_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, emit_message,(\fBj_common_ptr\fP cinfo, int msg_level))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, output_message,(\fBj_common_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, format_message,(\fBj_common_ptr\fP cinfo, char *\fBbuffer\fP))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, reset_error_mgr,(\fBj_common_ptr\fP cinfo))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmsg_code\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   int \fBi\fP [8]"
.br
.ti -1c
.RI "   char \fBs\fP [JMSG_STR_PARM_MAX]"
.br
.ti -1c
.RI "} \fBmsg_parm\fP"
.br
.ti -1c
.RI "int \fBtrace_level\fP"
.br
.ti -1c
.RI "long \fBnum_warnings\fP"
.br
.ti -1c
.RI "const char *const  * \fBjpeg_message_table\fP"
.br
.ti -1c
.RI "int \fBlast_jpeg_message\fP"
.br
.ti -1c
.RI "const char *const  * \fBaddon_message_table\fP"
.br
.ti -1c
.RI "int \fBfirst_addon_message\fP"
.br
.ti -1c
.RI "int \fBlast_addon_message\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
