.TH "jpeg_d_main_controller" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_d_main_controller
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, start_pass,(\fBj_decompress_ptr\fP cinfo, J_BUF_MODE pass_mode))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, process_data,(\fBj_decompress_ptr\fP cinfo, JSAMPARRAY output_buf, JDIMENSION *out_row_ctr, JDIMENSION out_rows_avail))"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
