.TH "jpeg_destination_mgr" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_destination_mgr
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, init_destination,(\fBj_compress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (boolean, empty_output_buffer,(\fBj_compress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, term_destination,(\fBj_compress_ptr\fP cinfo))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "JOCTET * \fBnext_output_byte\fP"
.br
.ti -1c
.RI "size_t \fBfree_in_buffer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
