.TH "jpeg_scan_info" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_scan_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcomps_in_scan\fP"
.br
.ti -1c
.RI "int \fBcomponent_index\fP [MAX_COMPS_IN_SCAN]"
.br
.ti -1c
.RI "int \fBSs\fP"
.br
.ti -1c
.RI "int \fBSe\fP"
.br
.ti -1c
.RI "int \fBAh\fP"
.br
.ti -1c
.RI "int \fBAl\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
