.TH "jpeg_marker_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_marker_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "jpeg_saved_marker_ptr \fBnext\fP"
.br
.ti -1c
.RI "UINT8 \fBmarker\fP"
.br
.ti -1c
.RI "unsigned int \fBoriginal_length\fP"
.br
.ti -1c
.RI "unsigned int \fBdata_length\fP"
.br
.ti -1c
.RI "JOCTET FAR * \fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
