.TH "jpeg_decomp_master" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_decomp_master
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, prepare_for_output_pass,(\fBj_decompress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, finish_output_pass,(\fBj_decompress_ptr\fP cinfo))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boolean \fBis_dummy_pass\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
