.TH "jpeg_component_info" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_component_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcomponent_id\fP"
.br
.ti -1c
.RI "int \fBcomponent_index\fP"
.br
.ti -1c
.RI "int \fBh_samp_factor\fP"
.br
.ti -1c
.RI "int \fBv_samp_factor\fP"
.br
.ti -1c
.RI "int \fBquant_tbl_no\fP"
.br
.ti -1c
.RI "int \fBdc_tbl_no\fP"
.br
.ti -1c
.RI "int \fBac_tbl_no\fP"
.br
.ti -1c
.RI "JDIMENSION \fBwidth_in_blocks\fP"
.br
.ti -1c
.RI "JDIMENSION \fBheight_in_blocks\fP"
.br
.ti -1c
.RI "int \fBDCT_scaled_size\fP"
.br
.ti -1c
.RI "JDIMENSION \fBdownsampled_width\fP"
.br
.ti -1c
.RI "JDIMENSION \fBdownsampled_height\fP"
.br
.ti -1c
.RI "boolean \fBcomponent_needed\fP"
.br
.ti -1c
.RI "int \fBMCU_width\fP"
.br
.ti -1c
.RI "int \fBMCU_height\fP"
.br
.ti -1c
.RI "int \fBMCU_blocks\fP"
.br
.ti -1c
.RI "int \fBMCU_sample_width\fP"
.br
.ti -1c
.RI "int \fBlast_col_width\fP"
.br
.ti -1c
.RI "int \fBlast_row_height\fP"
.br
.ti -1c
.RI "\fBJQUANT_TBL\fP * \fBquant_table\fP"
.br
.ti -1c
.RI "void * \fBdct_table\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
