.TH "jpeg_source_mgr" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_source_mgr
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, init_source,(\fBj_decompress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (boolean, fill_input_buffer,(\fBj_decompress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, skip_input_data,(\fBj_decompress_ptr\fP cinfo, long num_bytes))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (boolean, resync_to_restart,(\fBj_decompress_ptr\fP cinfo, int desired))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, term_source,(\fBj_decompress_ptr\fP cinfo))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const JOCTET * \fBnext_input_byte\fP"
.br
.ti -1c
.RI "size_t \fBbytes_in_buffer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
