.TH "jpeg_marker_reader" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_marker_reader
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, reset_marker_reader,(\fBj_decompress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (int, read_markers,(\fBj_decompress_ptr\fP cinfo))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "jpeg_marker_parser_method \fBread_restart_marker\fP"
.br
.ti -1c
.RI "boolean \fBsaw_SOI\fP"
.br
.ti -1c
.RI "boolean \fBsaw_SOF\fP"
.br
.ti -1c
.RI "int \fBnext_restart_num\fP"
.br
.ti -1c
.RI "unsigned int \fBdiscarded_bytes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
