.TH "jpeg_color_quantizer" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_color_quantizer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, start_pass,(\fBj_decompress_ptr\fP cinfo, boolean is_pre_scan))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, color_quantize,(\fBj_decompress_ptr\fP cinfo, JSAMPARRAY input_buf, JSAMPARRAY output_buf, int num_rows))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, finish_pass,(\fBj_decompress_ptr\fP cinfo))"
.br
.ti -1c
.RI "\fBJMETHOD\fP (void, new_color_map,(\fBj_decompress_ptr\fP cinfo))"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
