.TH "jpeg_progress_mgr" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg_progress_mgr
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, progress_monitor,(\fBj_common_ptr\fP cinfo))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBpass_counter\fP"
.br
.ti -1c
.RI "long \fBpass_limit\fP"
.br
.ti -1c
.RI "int \fBcompleted_passes\fP"
.br
.ti -1c
.RI "int \fBtotal_passes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
