.TH "jvirt_barray_control" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jvirt_barray_control
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "JBLOCKARRAY \fBmem_buffer\fP"
.br
.ti -1c
.RI "JDIMENSION \fBrows_in_array\fP"
.br
.ti -1c
.RI "JDIMENSION \fBblocksperrow\fP"
.br
.ti -1c
.RI "JDIMENSION \fBmaxaccess\fP"
.br
.ti -1c
.RI "JDIMENSION \fBrows_in_mem\fP"
.br
.ti -1c
.RI "JDIMENSION \fBrowsperchunk\fP"
.br
.ti -1c
.RI "JDIMENSION \fBcur_start_row\fP"
.br
.ti -1c
.RI "JDIMENSION \fBfirst_undef_row\fP"
.br
.ti -1c
.RI "boolean \fBpre_zero\fP"
.br
.ti -1c
.RI "boolean \fBdirty\fP"
.br
.ti -1c
.RI "boolean \fBb_s_open\fP"
.br
.ti -1c
.RI "\fBjvirt_barray_ptr\fP \fBnext\fP"
.br
.ti -1c
.RI "\fBbacking_store_info\fP \fBb_s_info\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
