.TH "la_zstream" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
la_zstream
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const uint8_t * \fBnext_in\fP"
.br
.ti -1c
.RI "size_t \fBavail_in\fP"
.br
.ti -1c
.RI "uint64_t \fBtotal_in\fP"
.br
.ti -1c
.RI "uint8_t * \fBnext_out\fP"
.br
.ti -1c
.RI "size_t \fBavail_out\fP"
.br
.ti -1c
.RI "uint64_t \fBtotal_out\fP"
.br
.ti -1c
.RI "uint32_t \fBprop_size\fP"
.br
.ti -1c
.RI "uint8_t * \fBprops\fP"
.br
.ti -1c
.RI "int \fBvalid\fP"
.br
.ti -1c
.RI "void * \fBreal_stream\fP"
.br
.ti -1c
.RI "int(* \fBcode\fP )(struct \fBarchive\fP *\fBa\fP, struct \fBla_zstream\fP *lastrm, enum la_zaction action)"
.br
.ti -1c
.RI "int(* \fBend\fP )(struct \fBarchive\fP *\fBa\fP, struct \fBla_zstream\fP *lastrm)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
