.TH "Labeldesc" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Labeldesc
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTString\fP * \fBname\fP"
.br
.ti -1c
.RI "int \fBpc\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "lu_byte \fBnactvar\fP"
.br
.ti -1c
.RI "lu_byte \fBclose\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
