.TH "lafe_line_reader" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lafe_line_reader
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBf\fP"
.br
.ti -1c
.RI "char * \fBbuff\fP"
.br
.ti -1c
.RI "char * \fBbuff_end\fP"
.br
.ti -1c
.RI "char * \fBline_start\fP"
.br
.ti -1c
.RI "char * \fBline_end\fP"
.br
.ti -1c
.RI "char * \fBpathname\fP"
.br
.ti -1c
.RI "size_t \fBbuff_length\fP"
.br
.ti -1c
.RI "int \fBnullSeparator\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
