.TH "LangTag" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LangTag
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcmp\fP (const char *\fBa\fP) const"
.br
.ti -1c
.RI "int \fBcmp\fP (const \fBLangTag\fP *that) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBlanguage\fP [4]"
.br
.ti -1c
.RI "hb_tag_t \fBtag\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
