.TH "large_pool_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
large_pool_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   large_pool_ptr \fBnext\fP"
.br
.ti -1c
.RI "   size_t \fBbytes_used\fP"
.br
.ti -1c
.RI "   size_t \fBbytes_left\fP"
.br
.ti -1c
.RI "} \fBhdr\fP"
.br
.ti -1c
.RI "ALIGN_TYPE \fBdummy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
