.TH "ldap_urldesc" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ldap_urldesc
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBlud_host\fP"
.br
.ti -1c
.RI "int \fBlud_port\fP"
.br
.ti -1c
.RI "char * \fBlud_dn\fP"
.br
.ti -1c
.RI "char ** \fBlud_attrs\fP"
.br
.ti -1c
.RI "int \fBlud_scope\fP"
.br
.ti -1c
.RI "char * \fBlud_filter\fP"
.br
.ti -1c
.RI "char ** \fBlud_exts\fP"
.br
.ti -1c
.RI "size_t \fBlud_attrs_dups\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
