.TH "LexState" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LexState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcurrent\fP"
.br
.ti -1c
.RI "int \fBlinenumber\fP"
.br
.ti -1c
.RI "int \fBlastline\fP"
.br
.ti -1c
.RI "\fBToken\fP \fBt\fP"
.br
.ti -1c
.RI "\fBToken\fP \fBlookahead\fP"
.br
.ti -1c
.RI "struct \fBFuncState\fP * \fBfs\fP"
.br
.ti -1c
.RI "struct \fBlua_State\fP * \fBL\fP"
.br
.ti -1c
.RI "\fBZIO\fP * \fBz\fP"
.br
.ti -1c
.RI "\fBMbuffer\fP * \fBbuff\fP"
.br
.ti -1c
.RI "\fBTable\fP * \fBh\fP"
.br
.ti -1c
.RI "struct \fBDyndata\fP * \fBdyd\fP"
.br
.ti -1c
.RI "\fBTString\fP * \fBsource\fP"
.br
.ti -1c
.RI "\fBTString\fP * \fBenvn\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
