.TH "lha" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lha
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBentry_offset\fP"
.br
.ti -1c
.RI "int64_t \fBentry_bytes_remaining\fP"
.br
.ti -1c
.RI "int64_t \fBentry_unconsumed\fP"
.br
.ti -1c
.RI "uint16_t \fBentry_crc_calculated\fP"
.br
.ti -1c
.RI "size_t \fBheader_size\fP"
.br
.ti -1c
.RI "unsigned char \fBlevel\fP"
.br
.ti -1c
.RI "char \fBmethod\fP [3]"
.br
.ti -1c
.RI "int64_t \fBcompsize\fP"
.br
.ti -1c
.RI "int64_t \fBorigsize\fP"
.br
.ti -1c
.RI "int \fBsetflag\fP"
.br
.ti -1c
.RI "time_t \fBbirthtime\fP"
.br
.ti -1c
.RI "long \fBbirthtime_tv_nsec\fP"
.br
.ti -1c
.RI "time_t \fBmtime\fP"
.br
.ti -1c
.RI "long \fBmtime_tv_nsec\fP"
.br
.ti -1c
.RI "time_t \fBatime\fP"
.br
.ti -1c
.RI "long \fBatime_tv_nsec\fP"
.br
.ti -1c
.RI "mode_t \fBmode\fP"
.br
.ti -1c
.RI "int64_t \fBuid\fP"
.br
.ti -1c
.RI "int64_t \fBgid\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBuname\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBgname\fP"
.br
.ti -1c
.RI "uint16_t \fBheader_crc\fP"
.br
.ti -1c
.RI "uint16_t \fBcrc\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_dir\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_fname\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBopt_sconv\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBdirname\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBfilename\fP"
.br
.ti -1c
.RI "struct \fBarchive_wstring\fP \fBws\fP"
.br
.ti -1c
.RI "unsigned char \fBdos_attr\fP"
.br
.ti -1c
.RI "char \fBfound_first_header\fP"
.br
.ti -1c
.RI "char \fBdirectory\fP"
.br
.ti -1c
.RI "char \fBdecompress_init\fP"
.br
.ti -1c
.RI "char \fBend_of_entry\fP"
.br
.ti -1c
.RI "char \fBend_of_entry_cleanup\fP"
.br
.ti -1c
.RI "char \fBentry_is_compressed\fP"
.br
.ti -1c
.RI "char \fBformat_name\fP [64]"
.br
.ti -1c
.RI "struct \fBlzh_stream\fP \fBstrm\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
