.TH "links_entry" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
links_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBlinks_entry\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBlinks_entry\fP * \fBprevious\fP"
.br
.ti -1c
.RI "struct \fBarchive_entry\fP * \fBcanonical\fP"
.br
.ti -1c
.RI "struct \fBarchive_entry\fP * \fBentry\fP"
.br
.ti -1c
.RI "size_t \fBhash\fP"
.br
.ti -1c
.RI "unsigned int \fBlinks\fP"
.br
.ti -1c
.RI "dev_t \fBdev\fP"
.br
.ti -1c
.RI "int64_t \fBino\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
