.TH "linkedlist_datablock_internal_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
linkedlist_datablock_internal_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBlinkedlist_datablock_internal_s\fP * \fBnext_datablock\fP"
.br
.ti -1c
.RI "uLong \fBavail_in_this_block\fP"
.br
.ti -1c
.RI "uLong \fBfilled_in_this_block\fP"
.br
.ti -1c
.RI "uLong \fBunused\fP"
.br
.ti -1c
.RI "unsigned char \fBdata\fP [SIZEDATA_INDATABLOCK]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
