.TH "loc_writer< Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loc_writer< Char >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(is_integer< T >\fB::value\fP) > auto \fBoperator()\fP (T \fBvalue\fP) \-> bool"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(is_floating_point< T >\fB::value\fP) > auto \fBoperator()\fP (T) \-> bool"
.br
.ti -1c
.RI "auto \fBoperator()\fP (\&.\&.\&.) \-> bool"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "buffer_appender< Char > \fBout\fP"
.br
.ti -1c
.RI "const \fBbasic_format_specs\fP< Char > & \fBspecs\fP"
.br
.ti -1c
.RI "std::basic_string< Char > \fBsep\fP"
.br
.ti -1c
.RI "std::string \fBgrouping\fP"
.br
.ti -1c
.RI "std::basic_string< Char > \fBdecimal_point\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
