.TH "loc_value" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loc_value
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(!detail::is_float128< T >\fB::value\fP) > \fBloc_value\fP (T \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(detail::is_float128< T >\fB::value\fP) > \fBloc_value\fP (T)"
.br
.ti -1c
.RI "template<typename Visitor > auto \fBvisit\fP (Visitor &&vis) \-> decltype(vis(0))"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
