.TH "locale_ref" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
locale_ref
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Locale > \fBlocale_ref\fP (const Locale &loc)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const noexcept"
.br
.ti -1c
.RI "template<typename Locale > auto \fBget\fP () const \-> Locale"
.br
.ti -1c
.RI "template<typename Locale > \fBlocale_ref\fP (const Locale &loc)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const noexcept"
.br
.ti -1c
.RI "template<typename Locale > auto \fBget\fP () const \-> Locale"
.br
.ti -1c
.RI "template<typename Locale > \fBlocale_ref\fP (const Locale &loc)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const noexcept"
.br
.ti -1c
.RI "template<typename Locale > auto \fBget\fP () const \-> Locale"
.br
.ti -1c
.RI "template<typename Locale > \fBlocale_ref\fP (const Locale &loc)"
.br
.ti -1c
.RI "\fBoperator bool\fP () const noexcept"
.br
.ti -1c
.RI "template<typename Locale > auto \fBget\fP () const \-> Locale"
.br
.ti -1c
.RI "template<typename Locale > Locale \fBget\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
