.TH "log" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBid\fP [4]"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "char * \fBend\fP"
.br
.ti -1c
.RI "off_t \fBfirst\fP"
.br
.ti -1c
.RI "int \fBback\fP"
.br
.ti -1c
.RI "uint \fBstored\fP"
.br
.ti -1c
.RI "off_t \fBlast\fP"
.br
.ti -1c
.RI "ulong \fBccrc\fP"
.br
.ti -1c
.RI "ulong \fBclen\fP"
.br
.ti -1c
.RI "ulong \fBtcrc\fP"
.br
.ti -1c
.RI "ulong \fBtlen\fP"
.br
.ti -1c
.RI "time_t \fBlock\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
