.TH "LogWindow" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogWindow
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogWindow\fP (\fBos::System\fP *system)"
.br
.ti -1c
.RI "bool \fBprocessEvent\fP (const \fBos::Event\fP &ev)"
.br
.ti -1c
.RI "void \fBflush\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
