.TH "LongShort" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LongShort
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBARG_NONE\fP, \fBARG_BOOL\fP, \fBARG_STRING\fP, \fBARG_FILENAME\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBletter\fP"
.br
.ti -1c
.RI "const char * \fBlname\fP"
.br
.ti -1c
.RI "enum LongShort:: { \&.\&.\&. }  \fBdesc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
