.TH "luaL_Buffer" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
luaL_Buffer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBb\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBn\fP"
.br
.ti -1c
.RI "\fBlua_State\fP * \fBL\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBLUAI_MAXALIGN\fP"
.br
.ti -1c
.RI "   char \fBb\fP [LUAL_BUFFERSIZE]"
.br
.ti -1c
.RI "} \fBinit\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
