.TH "lzh_stream" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lzh_stream
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const unsigned char * \fBnext_in\fP"
.br
.ti -1c
.RI "int \fBavail_in\fP"
.br
.ti -1c
.RI "int64_t \fBtotal_in\fP"
.br
.ti -1c
.RI "const unsigned char * \fBref_ptr\fP"
.br
.ti -1c
.RI "int \fBavail_out\fP"
.br
.ti -1c
.RI "int64_t \fBtotal_out\fP"
.br
.ti -1c
.RI "struct \fBlzh_dec\fP * \fBds\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
