.TH "lzh_dec" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lzh_dec
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBhuffman\fP"
.br
.ti -1c
.RI "struct \fBlzh_br\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "int \fBw_size\fP"
.br
.ti -1c
.RI "int \fBw_mask\fP"
.br
.ti -1c
.RI "unsigned char * \fBw_buff\fP"
.br
.ti -1c
.RI "int \fBw_pos\fP"
.br
.ti -1c
.RI "int \fBcopy_pos\fP"
.br
.ti -1c
.RI "int \fBcopy_len\fP"
.br
.ti -1c
.RI "struct \fBlzh_dec::lzh_br\fP \fBbr\fP"
.br
.ti -1c
.RI "struct \fBlzh_dec::huffman\fP \fBlt\fP"
.br
.ti -1c
.RI "struct \fBlzh_dec::huffman\fP \fBpt\fP"
.br
.ti -1c
.RI "int \fBblocks_avail\fP"
.br
.ti -1c
.RI "int \fBpos_pt_len_size\fP"
.br
.ti -1c
.RI "int \fBpos_pt_len_bits\fP"
.br
.ti -1c
.RI "int \fBliteral_pt_len_size\fP"
.br
.ti -1c
.RI "int \fBliteral_pt_len_bits\fP"
.br
.ti -1c
.RI "int \fBreading_position\fP"
.br
.ti -1c
.RI "int \fBloop\fP"
.br
.ti -1c
.RI "int \fBerror\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
