.TH "lzh_dec::huffman" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lzh_dec::huffman
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBhtree_t\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlen_size\fP"
.br
.ti -1c
.RI "int \fBlen_avail\fP"
.br
.ti -1c
.RI "int \fBlen_bits\fP"
.br
.ti -1c
.RI "int \fBfreq\fP [17]"
.br
.ti -1c
.RI "unsigned char * \fBbitlen\fP"
.br
.ti -1c
.RI "int \fBmax_bits\fP"
.br
.ti -1c
.RI "int \fBshift_bits\fP"
.br
.ti -1c
.RI "int \fBtbl_bits\fP"
.br
.ti -1c
.RI "int \fBtree_used\fP"
.br
.ti -1c
.RI "int \fBtree_avail\fP"
.br
.ti -1c
.RI "uint16_t * \fBtbl\fP"
.br
.ti -1c
.RI "struct \fBlzh_dec::huffman::htree_t\fP * \fBtree\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
