.TH "lzx_dec" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lzx_dec
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBhuffman\fP"
.br
.ti -1c
.RI "struct \fBlzx_br\fP"
.br
.ti -1c
.RI "struct \fBlzx_pos_tbl\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "int \fBw_size\fP"
.br
.ti -1c
.RI "int \fBw_mask\fP"
.br
.ti -1c
.RI "unsigned char * \fBw_buff\fP"
.br
.ti -1c
.RI "int \fBw_pos\fP"
.br
.ti -1c
.RI "int \fBcopy_pos\fP"
.br
.ti -1c
.RI "int \fBcopy_len\fP"
.br
.ti -1c
.RI "uint32_t \fBtranslation_size\fP"
.br
.ti -1c
.RI "char \fBtranslation\fP"
.br
.ti -1c
.RI "char \fBblock_type\fP"
.br
.ti -1c
.RI "size_t \fBblock_size\fP"
.br
.ti -1c
.RI "size_t \fBblock_bytes_avail\fP"
.br
.ti -1c
.RI "int \fBr0\fP"
.br
.ti -1c
.RI "int \fBr1\fP"
.br
.ti -1c
.RI "int \fBr2\fP"
.br
.ti -1c
.RI "unsigned char \fBrbytes\fP [4]"
.br
.ti -1c
.RI "int \fBrbytes_avail\fP"
.br
.ti -1c
.RI "int \fBlength_header\fP"
.br
.ti -1c
.RI "int \fBposition_slot\fP"
.br
.ti -1c
.RI "int \fBoffset_bits\fP"
.br
.ti -1c
.RI "struct \fBlzx_dec::lzx_pos_tbl\fP * \fBpos_tbl\fP"
.br
.ti -1c
.RI "struct \fBlzx_dec::lzx_br\fP \fBbr\fP"
.br
.ti -1c
.RI "struct \fBlzx_dec::huffman\fP \fBat\fP"
.br
.ti -1c
.RI "struct \fBlzx_dec::huffman\fP \fBlt\fP"
.br
.ti -1c
.RI "struct \fBlzx_dec::huffman\fP \fBmt\fP"
.br
.ti -1c
.RI "struct \fBlzx_dec::huffman\fP \fBpt\fP"
.br
.ti -1c
.RI "int \fBloop\fP"
.br
.ti -1c
.RI "int \fBerror\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
