.TH "main_header" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main_header
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBsolid\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBvolume\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBendarc\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBnotused\fP: 5"
.br
.ti -1c
.RI "unsigned int \fBvol_no\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
