.TH "main_font_text_t< consumer_t, font_options_type, text_options_type >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main_font_text_t< consumer_t, font_options_type, text_options_type >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBoption_parser_t\fP, font_options_type, text_options_type, and consumer_t\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBoperator()\fP (int argc, char **argv)"
.br
.in -1c

Public Member Functions inherited from \fBoption_parser_t\fP
.in +1c
.ti -1c
.RI "\fBoption_parser_t\fP (const char *parameter_string=nullptr)"
.br
.ti -1c
.RI "void \fBadd_options\fP ()"
.br
.ti -1c
.RI "template<typename Type > void \fBadd_group\fP (GOptionEntry *entries, const gchar *name, const gchar *description, const gchar *help_description, Type *closure, bool add_parse_hooks=true)"
.br
.ti -1c
.RI "template<typename Type > void \fBadd_main_group\fP (GOptionEntry *entries, Type *closure)"
.br
.ti -1c
.RI "void \fBset_summary\fP (const char *summary)"
.br
.ti -1c
.RI "void \fBset_description\fP (const char *description)"
.br
.ti -1c
.RI "void \fBfree_later\fP (char *p)"
.br
.ti -1c
.RI "bool \fBparse\fP (int *argc, char ***argv, bool ignore_error=false)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_options\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBoption_parser_t\fP
.in +1c
.ti -1c
.RI "static void \fB_g_free_g_func\fP (void *p, void *G_GNUC_UNUSED)"
.br
.ti -1c
.RI "static void \fBpost_parse_\fP (void *thiz, GError **error)"
.br
.ti -1c
.RI "template<typename Type > static auto \fBpost_parse_\fP (Type *thiz, GError **error) \-> decltype(thiz\->post_parse(error))"
.br
.ti -1c
.RI "template<typename Type > static gboolean \fBpost_parse\fP (GOptionContext *context G_GNUC_UNUSED, GOptionGroup *\fBgroup\fP G_GNUC_UNUSED, gpointer \fBdata\fP, GError **error)"
.br
.in -1c

Public Attributes inherited from \fBoption_parser_t\fP
.in +1c
.ti -1c
.RI "GOptionContext * \fBcontext\fP"
.br
.in -1c

Protected Attributes inherited from \fBoption_parser_t\fP
.in +1c
.ti -1c
.RI "GPtrArray * \fBto_free\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
