.TH "MainWindow" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCustomWindow\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBCustomWindow\fP
.in +1c
.ti -1c
.RI "void \fBcreate\fP (const std::string &title, int w, int h, \fBos::Window\fP *parent=nullptr)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "void \fBfocus\fP ()"
.br
.ti -1c
.RI "bool \fBisVisible\fP () const"
.br
.ti -1c
.RI "void \fBredraw\fP ()"
.br
.ti -1c
.RI "virtual bool \fBisFloating\fP () const"
.br
.ti -1c
.RI "virtual bool \fBhandleEvent\fP (\fBos::Event\fP &ev)"
.br
.in -1c

Protected Member Functions inherited from \fBCustomWindow\fP
.in +1c
.ti -1c
.RI "virtual void \fBonRedraw\fP (\fBos::Surface\fP *surface, const \fBgfx::Rect\fP &rc)"
.br
.ti -1c
.RI "virtual void \fBonEnterKey\fP ()"
.br
.ti -1c
.RI "os::WindowRef \fBnativeWindow\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
