.TH "ManifestLookup" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ManifestLookup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDEFINE_SIZE_STATIC\fP (6)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBOT::Tag\fP \fBtag\fP"
.br
.ti -1c
.RI "\fBOT::Offset16To\fP< \fBOT::SubstLookup\fP > \fBlookupOffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
