.TH "mat3" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mat3 \- Column first 3x3 matrix class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mat3\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBmat3\fP (\fBvec3\fP first_column, \fBvec3\fP second_column, \fBvec3\fP third_column) noexcept"
.br
.ti -1c
.RI "constexpr \fBmat3\fP (float column0_row0, float column0_row1, float column0_row2, float column1_row0, float column1_row1, float column1_row2, float column2_row0, float column2_row1, float column2_row2) noexcept"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static constexpr \fBmat3\fP \fBtranspose\fP (const \fBmat3\fP &m) noexcept"
.br
.ti -1c
.RI "static constexpr \fBmat3\fP \fBbuild_scale\fP (float scale) noexcept"
.br
.ti -1c
.RI "static constexpr \fBmat3\fP \fBbuild_scale\fP (float scale_x, float scale_y) noexcept"
.br
.ti -1c
.RI "static constexpr \fBmat3\fP \fBbuild_scale\fP (const \fBvec2\fP &scale) noexcept"
.br
.ti -1c
.RI "static \fBmat3\fP \fBbuild_rotation\fP (float angle_in_radians) noexcept"
.br
.ti -1c
.RI "static constexpr \fBmat3\fP \fBbuild_translation\fP (float translate_x, float translate_y) noexcept"
.br
.ti -1c
.RI "static constexpr \fBmat3\fP \fBbuild_translation\fP (const \fBvec2\fP &translation) noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   float \fBelements\fP [3][3]"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBvec3\fP \fBcolumn0\fP"
.br
.ti -1c
.RI "      \fBvec3\fP \fBcolumn1\fP"
.br
.ti -1c
.RI "      \fBvec3\fP \fBcolumn2\fP"
.br
.ti -1c
.RI "   } "
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Column first 3x3 matrix class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
