.TH "MatchState" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatchState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBsrc_init\fP"
.br
.ti -1c
.RI "const char * \fBsrc_end\fP"
.br
.ti -1c
.RI "const char * \fBp_end\fP"
.br
.ti -1c
.RI "\fBlua_State\fP * \fBL\fP"
.br
.ti -1c
.RI "int \fBmatchdepth\fP"
.br
.ti -1c
.RI "unsigned char \fBlevel\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   const char * \fBinit\fP"
.br
.ti -1c
.RI "   ptrdiff_t \fBlen\fP"
.br
.ti -1c
.RI "} \fBcapture\fP [LUA_MAXCAPTURES]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
