.TH "match_list" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
match_list
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBmatch\fP * \fBfirst\fP"
.br
.ti -1c
.RI "struct \fBmatch\fP ** \fBlast\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int \fBunmatched_count\fP"
.br
.ti -1c
.RI "struct \fBmatch\fP * \fBunmatched_next\fP"
.br
.ti -1c
.RI "int \fBunmatched_eof\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
