.TH "match_file" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
match_file
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive_rb_node\fP \fBnode\fP"
.br
.ti -1c
.RI "struct \fBmatch_file\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBarchive_mstring\fP \fBpathname\fP"
.br
.ti -1c
.RI "int \fBflag\fP"
.br
.ti -1c
.RI "time_t \fBmtime_sec\fP"
.br
.ti -1c
.RI "long \fBmtime_nsec\fP"
.br
.ti -1c
.RI "time_t \fBctime_sec\fP"
.br
.ti -1c
.RI "long \fBctime_nsec\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
