.TH "max_size_allocator< Allocator, MaxSize >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
max_size_allocator< Allocator, MaxSize >
.SH SYNOPSIS
.br
.PP
.PP
Inherits Allocator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBmax_size\fP () const noexcept"
.br
.ti -1c
.RI "value_type * \fBallocate\fP (size_t n)"
.br
.ti -1c
.RI "void \fBdeallocate\fP (value_type *p, size_t n)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
