.TH "md__ase_sprite_aseprite_third_party_harfbuzz__t_e_s_t_i_n_g" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_harfbuzz__t_e_s_t_i_n_g \- Build and \fBTest\fP 
.PP

.PP
.nf
meson build
ninja \-Cbuild
meson test \-Cbuild

.fi
.PP
.SS "Debug with GDB"
.PP
.nf
meson test \-Cbuild \-\-gdb testname
.fi
.PP
.SH "Build and Run"
.PP
Depending on what area you are working in change or add \fCHB_DEBUG_<whatever>\fP\&. Values defined in \fC\fBhb-debug\&.hh\fP\fP\&.
.PP
.PP
.nf
CPPFLAGS='\-DHB_DEBUG_SUBSET=100' meson setup build \-\-reconfigure
meson test \-C build
.fi
.PP
.SS "Run tests with asan"
.PP
.nf
meson setup build \-Db_sanitize=address \-\-reconfigure
meson compile \-C build
meson test \-C build
.fi
.PP
.SS "Enable Debug Logging"
.PP
.nf
CPPFLAGS=\-DHB_DEBUG_SUBSET=100 meson build \-\-reconfigure
ninja \-C build
.fi
.PP
.SH "Test with the Fuzzer"
.PP
.PP
.nf
CXXFLAGS="\-fsanitize=address,fuzzer\-no\-link" meson fuzzbuild \-\-default\-library=static \-Dfuzzer_ldflags="\-fsanitize=address,fuzzer" \-Dexperimental_api=true
ninja \-Cfuzzbuild test/fuzzing/hb\-{shape,draw,subset,set}\-fuzzer
fuzzbuild/test/fuzzing/hb\-subset\-fuzzer test/fuzzing/fonts
.fi
.PP
.SH "Profiling"
.PP
.PP
.nf
meson build \-\-reconfigure
meson compile \-C build
build/perf/perf
.fi
.PP
 
