.TH "md__ase_sprite_aseprite_src_app_modules__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_src_app_modules__r_e_a_d_m_e \- modules/ 
.PP
This directory contains a lot of deprecated C code\&. This should be moved/refactored to better C++ abstractions\&. 
