.TH "md__ase_sprite_aseprite_third_party_curl_docs__b_i_n_d_i_n_g_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl_docs__b_i_n_d_i_n_g_s \- libcurl bindings 
.PP
Creative people have written bindings or interfaces for various environments and programming languages\&. Using one of these allows you to take advantage of curl powers from within your favourite language or system\&.
.PP
This is a list of all known interfaces as of this writing\&.
.PP
The bindings listed below are not part of the curl/libcurl distribution archives, but must be downloaded and installed separately\&.
.PP
\fCAda95\fP Written by Andreas Almroth
.PP
\fCBasic\fP ScriptBasic bindings written by Peter Verhas
.PP
C++: \fCcurlpp\fP Written by Jean-Philippe Barrette-LaPierre, \fCcurlcpp\fP by Giuseppe Persico and \fCC++ Requests\fP by Huu Nguyen
.PP
\fCCh\fP Written by Stephen Nestinger and Jonathan Rogado
.PP
Cocoa: \fCBBHTTP\fP written by Bruno de Carvalho \fCcurlhandle\fP Written by Dan Wood
.PP
Clojure: \fCclj-curl\fP by Lucas Severo
.PP
\fCD\fP Written by Kenneth Bogert
.PP
\fCDelphi\fP Written by Mikhail Merkuryev
.PP
\fCDylan\fP Written by Chris Double
.PP
\fCEiffel\fP Written by Eiffel Software
.PP
\fCEuphoria\fP Written by Ray Smith
.PP
\fCFalcon\fP
.PP
\fCFerite\fP Written by Paul Querna
.PP
\fCGambas\fP
.PP
\fCglib/GTK+\fP Written by Richard Atterer
.PP
Go: \fCgo-curl\fP by ShuYu Wang
.PP
\fCGuile\fP Written by Michael L\&. Gran
.PP
\fCHarbour\fP Written by Viktor Szakats
.PP
\fCHaskell\fP Written by Galois, Inc
.PP
\fCJava\fP
.PP
\fCJulia\fP Written by Paul Howe
.PP
\fCKapito\fP is an Erlang \fBHTTP\fP library around libcurl\&.
.PP
\fCLisp\fP Written by Liam Healy
.PP
Lua: \fCluacurl\fP by Alexander Marinov, \fCLua-cURL\fP by Jürgen Hötzel
.PP
\fCMono\fP Written by Jeffrey Phillips
.PP
\fC\&.NET\fP libcurl-net by Jeffrey Phillips
.PP
\fCNim\fP wrapper for libcurl
.PP
\fCnode\&.js\fP node-libcurl by Jonathan Cardoso Machado
.PP
\fCObject-Pascal\fP Free Pascal, Delphi and Kylix binding written by Christophe Espern\&.
.PP
\fCOCaml\fP Written by Lars Nilsson and ygrek
.PP
\fCPascal\fP Free Pascal, Delphi and Kylix binding written by Jeffrey Pohlmeyer\&.
.PP
Perl: \fCWWW::Curl\fP Maintained by Cris Bailiff and Bálint Szilakszi, \fCperl6-net-curl\fP by Ahmad M\&. Zawawi \fCNET::Curl\fP by Przemyslaw Iskra
.PP
\fCPHP\fP Originally written by Sterling Hughes
.PP
\fCPostgreSQL\fP - \fBHTTP\fP client for PostgreSQL
.PP
\fCPureBasic\fP uses libcurl in its 'native' \fBHTTP\fP subsystem
.PP
\fCPython\fP PycURL by Kjetil Jacobsen
.PP
\fCR\fP
.PP
\fCRexx\fP Written Mark Hessling
.PP
\fCRing\fP RingLibCurl by Mahmoud Fayed
.PP
RPG, support for ILE/RPG on OS/400 is included in source distribution
.PP
Ruby: \fCcurb\fP written by Ross Bamford
.PP
\fCRust\fP curl-rust - by Carl Lerche
.PP
\fCScheme\fP Bigloo binding by Kirill Lisovsky
.PP
\fCScilab\fP binding by Sylvestre Ledru
.PP
\fCS-Lang\fP by John E Davis
.PP
\fCSmalltalk\fP Written by Danil Osipchuk
.PP
\fCSP-Forth\fP Written by Andrey Cherezov
.PP
\fCSPL\fP Written by Clifford Wolf
.PP
\fCTcl\fP Tclcurl by Andrés García
.PP
\fCVisual Basic\fP libcurl-vb by Jeffrey Phillips
.PP
\fCVisual Foxpro\fP by Carlos Alloatti
.PP
\fCQ\fP The libcurl module is part of the default install
.PP
\fCwxWidgets\fP Written by Casey \fBO\fP'Donnell
.PP
\fCXBLite\fP Written by David Szafranski
.PP
\fCXojo\fP Written by Andrew Lambert 
