.TH "md__ase_sprite_aseprite_third_party__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party__r_e_a_d_m_e \- README 
.PP
Here are third party libraries with necessary components for Aseprite\&. Some directories are git submodules, and other are just a copy of its original package\&. 
