.TH "md__ase_sprite_aseprite_third_party_curl_docs__c_u_r_l__d_i_s_a_b_l_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl_docs__c_u_r_l__d_i_s_a_b_l_e \- Code defines to disable features and protocols 
.PP

.SH "CURL_DISABLE_ALTSVC"
.PP
Disable support for Alt-Svc: \fBHTTP\fP headers\&.
.SH "CURL_DISABLE_COOKIES"
.PP
Disable support for \fBHTTP\fP cookies\&.
.SH "CURL_DISABLE_CRYPTO_AUTH"
.PP
Disable support for authentication methods using crypto\&.
.SH "CURL_DISABLE_DICT"
.PP
Disable the DICT protocol
.SH "CURL_DISABLE_DOH"
.PP
Disable DNS-over-HTTPS
.SH "CURL_DISABLE_FILE"
.PP
Disable the FILE protocol
.SH "CURL_DISABLE_FTP"
.PP
Disable the \fBFTP\fP (and FTPS) protocol
.SH "CURL_DISABLE_GETOPTIONS"
.PP
Disable the \fCcurl_easy_options\fP API calls that lets users get information about existing options to \fCcurl_easy_setopt\fP\&.
.SH "CURL_DISABLE_GOPHER"
.PP
Disable the GOPHER protocol\&.
.SH "CURL_DISABLE_HSTS"
.PP
Disable the \fBHTTP\fP Strict Transport Security support\&.
.SH "CURL_DISABLE_HTTP"
.PP
Disable the HTTP(S) protocols\&. Note that this then also disable \fBHTTP\fP proxy support\&.
.SH "CURL_DISABLE_HTTP_AUTH"
.PP
Disable support for all \fBHTTP\fP authentication methods\&.
.SH "CURL_DISABLE_IMAP"
.PP
Disable the \fBIMAP(S)\fP protocols\&.
.SH "CURL_DISABLE_LDAP"
.PP
Disable the LDAP(S) protocols\&.
.SH "CURL_DISABLE_LDAPS"
.PP
Disable the LDAPS protocol\&.
.SH "CURL_DISABLE_LIBCURL_OPTION"
.PP
Disable the --libcurl option from the curl tool\&.
.SH "CURL_DISABLE_MIME"
.PP
Disable MIME support\&.
.SH "CURL_DISABLE_MQTT"
.PP
Disable \fBMQTT\fP support\&.
.SH "CURL_DISABLE_NETRC"
.PP
Disable the netrc parser\&.
.SH "CURL_DISABLE_NTLM"
.PP
Disable support for NTLM\&.
.SH "CURL_DISABLE_OPENSSL_AUTO_LOAD_CONFIG"
.PP
Disable the auto load config support in the OpenSSL backend\&.
.SH "CURL_DISABLE_PARSEDATE"
.PP
Disable date parsing
.SH "CURL_DISABLE_POP3"
.PP
Disable the \fBPOP3\fP protocol
.SH "CURL_DISABLE_PROGRESS_METER"
.PP
Disable the built-in progress meter
.SH "CURL_DISABLE_PROXY"
.PP
Disable support for proxies
.SH "CURL_DISABLE_RTSP"
.PP
Disable the \fBRTSP\fP protocol\&.
.SH "CURL_DISABLE_SHUFFLE_DNS"
.PP
Disable the shuffle DNS feature
.SH "CURL_DISABLE_SMB"
.PP
Disable the SMB(S) protocols
.SH "CURL_DISABLE_SMTP"
.PP
Disable the \fBSMTP(S)\fP protocols
.SH "CURL_DISABLE_SOCKETPAIR"
.PP
Disable the use of socketpair internally to allow waking up and canceling curl_multi_poll()\&.
.SH "CURL_DISABLE_TELNET"
.PP
Disable the \fBTELNET\fP protocol
.SH "CURL_DISABLE_TFTP"
.PP
Disable the TFTP protocol
.SH "CURL_DISABLE_VERBOSE_STRINGS"
.PP
Disable verbose strings and error messages\&. 
