.TH "md__ase_sprite_aseprite_third_party_cmark_bench_samples_block_list_nested" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_cmark_bench_samples_block_list_nested \- block-list-nested 
.PP

.IP "\(bu" 2
this
.IP "  \(bu" 4
is
.IP "    \(bu" 6
a
.IP "      \(bu" 8
deeply
.IP "        \(bu" 10
nested
.IP "          \(bu" 12
bullet
.IP "            \(bu" 14
list
.PP

.PP

.PP

.PP

.PP

.PP

.PP
.IP "1." 4
this
.IP "  2." 6
is
.IP "    3." 8
a
.IP "      4." 10
deeply
.IP "        5." 12
nested
.IP "          6." 14
unordered
.IP "            7." 16
list
.PP

.PP

.PP

.PP

.PP

.PP

.PP
.IP "\(bu" 2
1
.IP "  \(bu" 4
2
.IP "    \(bu" 6
3
.IP "      \(bu" 8
4
.IP "        \(bu" 10
5
.IP "          \(bu" 12
6
.IP "            \(bu" 14
7
.PP

.IP "          \(bu" 12
6
.PP

.IP "        \(bu" 10
5
.PP

.IP "      \(bu" 8
4
.PP

.IP "    \(bu" 6
3
.PP

.IP "  \(bu" 4
2
.PP

.IP "\(bu" 2
1
.IP "\(bu" 2
- - - - - - - - deeply-nested one-element item 
.PP

