.TH "md__ase_sprite_aseprite_third_party_harfbuzz__r_e_l_e_a_s_i_n_g" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_harfbuzz__r_e_l_e_a_s_i_n_g \- HarfBuzz release walk-through checklist: 
.PP

.IP "\(bu" 2
[ ] Open gitk and review changes since last release\&.
.IP "  \(bu" 4
[ ] Print all public API changes: `git diff $(git describe | sed 's/-\&.*//')\&.\&. src/*\&.h`
.IP "  \(bu" 4
[ ] Document them in NEWS\&. All API and API semantic changes should be clearly marked as API additions, API changes, or API deletions\&.
.IP "  \(bu" 4
[ ] Document deprecations\&. Ensure all new API / deprecations are in listed correctly in docs/harfbuzz-sections\&.txt\&. If release added new API, add entry for new API index at the end of docs/harfbuzz-docs\&.xml\&.
.PP
If there's a backward-incompatible API change (including deletions for API used anywhere), that's a release blocker\&. Do NOT release\&.
.PP

.IP "\(bu" 2
[ ] Based on severity of changes, decide whether it's a minor or micro release number bump\&.
.IP "\(bu" 2
[ ] Search for REPLACEME on the repository and replace it with the chosen version for the release\&.
.IP "\(bu" 2
[ ] Make sure you have correct date and new version at the top of NEWS file\&.
.IP "\(bu" 2
[ ] Bump version in line 3 of meson\&.build and configure\&.ac\&.
.IP "\(bu" 2
[ ] Do a \fCmeson test -Cbuild\fP so it both checks the tests and updates \fBhb-version\&.h\fP (use \fCgit diff\fP to see if is really updated)\&.
.IP "\(bu" 2
[ ] Commit NEWS, meson\&.build, configure\&.ac, and \fBsrc/hb-version\&.h\fP, as well as any REPLACEME changes you made\&. The commit message is simply the release number, e\&. g\&. '1\&.4\&.7'
.IP "\(bu" 2
[ ] Do a \fCmeson dist -Cbuild\fP that runs the tests against the latest committed changes\&. If doesn't pass, something fishy is going on, reset the repo and start over\&.
.IP "\(bu" 2
[ ] Tag the release and sign it: e\&.g\&. \fCgit tag -s 1\&.4\&.7 -m 1\&.4\&.7\fP\&. Enter your GPG password\&.
.IP "\(bu" 2
[ ] Push the commit and tag out: \fCgit push --follow-tags\fP\&. 
.PP

