.TH "md__ase_sprite_aseprite_third_party_cmark_bench_samples_block_bq_flat" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_cmark_bench_samples_block_bq_flat \- block-bq-flat 
.PP

.PP
.RS 4
the simple example of a blockquote the simple example of a blockquote the simple example of a blockquote the simple example of a blockquote 
.RE
.PP
\&.\&.\&. continuation \&.\&.\&. continuation \&.\&.\&. continuation \&.\&.\&. continuation
.PP
empty blockquote:
.PP
.RS 4

.PP
.RE
.PP

