.TH "md__ase_sprite_aseprite_third_party_curl_docs__d_e_p_r_e_c_a_t_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl_docs__d_e_p_r_e_c_a_t_e \- Items to be removed from future curl releases 
.PP
If any of these deprecated features is a cause for concern for you, please email the \fCcurl-library mailing list\fP as soon as possible and explain to us why this is a problem for you and how your use case can't be satisfied properly using a workaround\&.
.SH "Past removals"
.PP
.IP "\(bu" 2
Pipelining
.IP "\(bu" 2
axTLS
.IP "\(bu" 2
PolarSSL 
.PP

