.TH "md__ase_sprite_aseprite_src_undo__c_o_n_t_r_i_b_u_t_i_n_g" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_src_undo__c_o_n_t_r_i_b_u_t_i_n_g \- CONTRIBUTING 
.PP
By submitting a pull request, you represent that you have the right to license your contribution to the Undo project owners and the community, agree by submitting the patch that your contributions are licensed under the \fCUndo license\fP, and agree to future changes to the licensing\&. 
