.TH "md__ase_sprite_aseprite_third_party_curl_docs__e_x_p_e_r_i_m_e_n_t_a_l" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl_docs__e_x_p_e_r_i_m_e_n_t_a_l \- Experimental 
.PP
Some features and functionality in curl and libcurl are considered \fBEXPERIMENTAL\fP\&.
.PP
Experimental support in curl means:
.PP
.IP "1." 4
Experimental features are provided to allow users to try them out and provide feedback on functionality and API etc before they ship and get 'carved in stone'\&.
.IP "2." 4
You must enable the feature when invoking configure as otherwise curl will not be built with the feature present\&.
.IP "3." 4
We strongly advice against using this feature in production\&.
.IP "4." 4
\fBWe reserve the right to change behavior\fP of the feature without sticking to our API/ABI rules as we do for regular features, as long as it is marked experimental\&.
.IP "5." 4
Experimental features are clearly marked so in documentation\&. Beware\&.
.PP
.SH "Experimental features right now"
.PP
.IP "\(bu" 2
The Hyper \fBHTTP\fP backend
.IP "\(bu" 2
HTTP/3 support and options
.IP "\(bu" 2
CURLSSLOPT_NATIVE_CA (No configure option, feature built in when supported) 
.PP

