.TH "md__ase_sprite_aseprite_laf_docs_ft__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_laf_docs_ft__r_e_a_d_m_e \- laf-ft 
.PP
\fIlaf-ft\fP is a wrapper of FreeType and HarfBuzz to shape Unicode text correctly\&. This library might be replaced with an alternative way to handle text on \fIlaf-os\fP, mainly integrating Skia, the native APIs to paint text, and a way to create/use sprite sheet-based fonts\&.
.SH "API Reference"
.PP
.IP "\(bu" 2
\fCft::FaceFT\fP: FT_Face wrapper
.IP "\(bu" 2
\fCft::ForEachGlyph\fP: Algorithm to iterate each glyph
.IP "\(bu" 2
\fCft::HBFace\fP: \fBhb_font_t\fP wrapper
.IP "\(bu" 2
\fCft::HBShaper\fP: hb_shape & hb_buffer wrappers
.IP "\(bu" 2
\fCft::Lib\fP: FT_Library wrapper 
.PP

