.TH "md__ase_sprite_aseprite_tests_sprites__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_tests_sprites__r_e_a_d_m_e \- Files 
.PP

.IP "\(bu" 2
\fCabcd\&.aseprite\fP: Indexed, 32x32, four layers ('a', 'b', 'c', 'd')
.IP "\(bu" 2
\fC1empty3\&.aseprite\fP: RGB, 32x32, two layers ('fg', 'bg'), 2nd frame completelly empty, two tags ('a', 'b')
.IP "\(bu" 2
\fCgroups2\&.aseprite\fP: Indexed, 8x8, two groups ('items', 'player'), two layers per group ('items/gun', 'items/sword', 'player/head', 'player/body'), with one layer hidden ('items/gun')\&.
.IP "\(bu" 2
\fCgroups3abc\&.aseprite\fP: RGB, 9x11, three groups ('a', 'b', 'c'), with three layers each one (called 'a', 'b', 'c' too)\&. There is a combination of visibilities ('b/b', 'c', 'c/a', and 'c/b' are hidden)\&.
.IP "\(bu" 2
\fCbg-index-3\&.aseprite\fP: Indexed, 4x4, two layers ('fg' and 'bg') with a special transparent index color (= palette index 3)\&.
.IP "\(bu" 2
\fCtags3\&.aseprite\fP: 3 tags ('forward', 'reverse', 'pingpong') and 3 layers ('a', 'b', 'c'), 4x4, several linked cels + layer 'c' with empty cels\&.
.IP "\(bu" 2
\fCpoint4frames\&.aseprite\fP: Indexed, 4 frames, 2 layers, same cel content but different positions, can be used to test \fC-merge-duplicates\fP to check if all cels go to the same sprite sheet position\&.
.IP "\(bu" 2
\fCpoint2frames\&.aseprite\fP: Indexed, 2 frames, 1 layer, same cel content as in \fCpoint4frames\&.aseprite\fP\&. Useful to test if \fC'sourceSize'\fP is different when two cels from different sprites are merged in the same texture atlas\&.
.IP "\(bu" 2
\fC2f-index-3x3\&.aseprite\fP: Indexed, 2 frames, 1 layer, mask color set to index 21\&.
.IP "\(bu" 2
\fCfile-tests-props\&.aseprite\fP: Indexed, 64x64, 6 frames, 4 layers (one of them is a tilemap), 13 cels, 1 tag\&. 
.PP

