.TH "md__ase_sprite_aseprite_src_dio__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_src_dio__r_e_a_d_m_e \- Aseprite Document IO Library 
.PP

.PP
.RS 4
Distributed under \fCMIT license\fP 
.RE
.PP
Library to decode \fC\fBdoc::Document\fP\fP from \fC\&.aseprite\fP files\&. This library should support encoding of \fC\&.aseprite\fP files in the near future\&. 
