.TH "md__ase_sprite_aseprite_laf_docs_base__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_laf_docs_base__r_e_a_d_m_e \- laf-base 
.PP
Cross-platform core functionality to do basic tasks\&. Ideally this functionaly should be included on C++, so some functions could be replaced with a \fCstd::\fP equivalent in the future\&.
.PP
.IP "\(bu" 2
Data utilities (\fCencode/decode_base64\fP)
.IP "\(bu" 2
File system & filename/path utilities (\fCfs\&.h\fP)
.IP "\(bu" 2
File utilities (\fCserialization\fP, \fCsha1\fP, \fClauncher\fP)
.IP "\(bu" 2
Logging functions (\fCLOG()\fP)
.IP "\(bu" 2
Manage DLLs (\fCload/unload_dll()\fP)
.IP "\(bu" 2
Multi-threading utilities (\fCthread\fP, \fCthread_pool\fP)
.IP "\(bu" 2
Smart pointers (\fCRefCount/Ref\fP)
.IP "\(bu" 2
String/UTF8 utilities (\fCstring\fP, \fCsplit_string\fP, \fCtrim_string\fP)
.IP "\(bu" 2
Timing (\fCtick_t/current_tick()\fP, \fCChrono\fP)
.IP "\(bu" 2
Type conversion (\fCconvert_to\fP)
.IP "\(bu" 2
Unicode filenames (\fCopen_file_raw()\fP, \fCFSTREAM_PATH()\fP)
.IP "\(bu" 2
Version comparison (\fCVersion\fP) 
.PP

