.TH "md__ase_sprite_aseprite_third_party_curl_docs__e_c_h" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl_docs__e_c_h \- TLS: ECH support in curl and libcurl 
.PP

.SH "Summary"
.PP
\fBECH\fP means \fBEncrypted Client Hello\fP, a TLS 1\&.3 extension which is currently the subject of an \fCIETF Draft\fP\&. (ECH was formerly known as ESNI)\&.
.PP
This file is intended to show the latest current state of ECH support in \fBcurl\fP and \fBlibcurl\fP\&.
.PP
At end of August 2019, an \fCexperimental fork of curl\fP, built using an \fCexperimental fork of OpenSSL\fP, which in turn provided an implementation of ECH, was demonstrated interoperating with a server belonging to the \fCDEfO Project\fP\&.
.PP
Further sections here describe
.PP
.IP "\(bu" 2
resources needed for building and demonstrating \fBcurl\fP support for ECH,
.IP "\(bu" 2
progress to date,
.IP "\(bu" 2
TODO items, and
.IP "\(bu" 2
additional details of specific stages of the progress\&.
.PP
.SH "Resources needed"
.PP
To build and demonstrate ECH support in \fBcurl\fP and/or \fBlibcurl\fP, you will need
.PP
.IP "\(bu" 2
a TLS library, supported by \fBlibcurl\fP, which implements ECH;
.IP "\(bu" 2
an edition of \fBcurl\fP and/or \fBlibcurl\fP which supports the ECH implementation of the chosen TLS library;
.IP "\(bu" 2
an environment for building and running \fBcurl\fP, and at least building \fBOpenSSL\fP;
.IP "\(bu" 2
a server, supporting ECH, against which to run a demonstration and perhaps a specific target URL;
.IP "\(bu" 2
some instructions\&.
.PP
.PP
The following set of resources is currently known to be available\&.
.PP
Set   Component   Location   Remarks    DEfO   TLS library   \fCsftcd/openssl\fP   Tag \fIesni-2019-08-30\fP avoids bleeding edge    curl fork   \fCniallor/curl\fP   Tag \fIesni-2019-08-30\fP likewise    instructions   \fCESNI-README\fP   
.SH "Progress"
.PP
.SS "PR 4011 (Jun 2019) expected in curl release 7\&.67\&.0 (Oct 2019)"
.IP "\(bu" 2
Details \fBbelow\fP;
.IP "\(bu" 2
New configuration option: \fC--enable-ech\fP;
.IP "\(bu" 2
Build-time check for availability of resources needed for ECH support;
.IP "\(bu" 2
Pre-processor symbol \fCUSE_ECH\fP for conditional compilation of ECH support code, subject to configuration option and availability of needed resources\&.
.PP
.SH "TODO"
.PP
.IP "\(bu" 2
(next PR) Add libcurl options to set ECH parameters\&.
.IP "\(bu" 2
(next PR) Add curl tool command line options to set ECH parameters\&.
.IP "\(bu" 2
(WIP) Extend DoH functions so that published ECH parameters can be retrieved from DNS instead of being required as options\&.
.IP "\(bu" 2
(WIP) Work with OpenSSL community to finalize ECH API\&.
.IP "\(bu" 2
Track OpenSSL ECH API in libcurl
.IP "\(bu" 2
Identify and implement any changes needed for CMake\&.
.IP "\(bu" 2
Optimize build-time checking of available resources\&.
.IP "\(bu" 2
Encourage ECH support work on other TLS/SSL backends\&.
.PP
.SH "Additional detail"
.PP
.SS "PR 4011"
\fBTLS: Provide ECH support framework for curl and libcurl\fP
.PP
The proposed change provides a framework to facilitate work to implement ECH support in curl and libcurl\&. It is not intended either to provide ECH functionality or to favour any particular TLS-providing backend\&. Specifically, the change reserves a feature bit for ECH support (symbol \fCCURL_VERSION_ECH\fP), implements setting and reporting of this bit, includes dummy book-keeping for the symbol, adds a build-time configuration option (\fC--enable-ech\fP), provides an extensible check for resources available to provide ECH support, and defines a compiler pre-processor symbol (\fCUSE_ECH\fP) accordingly\&.
.PP
Proposed-by: @niallor (Niall \fBO\fP'Reilly)\\ Encouraged-by: @sftcd (Stephen Farrell)\\ See-also: \fCthis message\fP
.PP
Limitations:
.IP "\(bu" 2
Book-keeping (symbols-in-versions) needs real release number, not 'DUMMY'\&.
.IP "\(bu" 2
Framework is incomplete, as it covers autoconf, but not CMake\&.
.IP "\(bu" 2
Check for available resources, although extensible, refers only to specific work in progress (\fCdescribed here\fP) to implement ECH for OpenSSL, as this is the immediate motivation for the proposed change\&.
.PP
.SH "References"
.PP
Cloudflare blog: \fCEncrypting SNI: Fixing One of the Core Internet Bugs\fP
.PP
Cloudflare blog: \fCEncrypt it or lose it: how encrypted SNI works\fP
.PP
IETF Draft: \fCEncrypted Server Name Indication for TLS 1\&.3\fP
.PP
.PP
 
