.TH "md__c_s200__challenge__c_s200__challenge__line__resterization__read_me" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_s200__challenge__c_s200__challenge__line__resterization__read_me \- Build Line Rasterizer 
.PP
Compile the \fCLineRasterizer\&.cpp\fP, \fCdraw_line\&.cpp\fP, and \fCImage\&.cpp\fP files\&.
.PP
Something like :
.PP
.PP
.nf
g++ \-Wall \-Wextra \-pedantic \-O2 \-std=c++17 LineRasterizer\&.cpp draw_line\&.cpp Image\&.cpp \-o LineRasterizer
.fi
.PP
.SH "Build Test Driver"
.PP
Compile the \fCTestDriver\&.cpp\fP and \fCdraw_line\&.cpp\fP files\&.
.PP
Something like :
.PP
.PP
.nf
g++ \-Wall \-Wextra \-pedantic \-O2 \-std=c++17 TestDriver\&.cpp draw_line\&.cpp \-o TestDriver
.fi
.PP
 
