.TH "md__ase_sprite_aseprite_third_party__i_x_web_socket_third_party__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party__i_x_web_socket_third_party__r_e_a_d_m_e \- Note 
.PP
Except \fIzlib\fP and \fImbedtls\fP on Windows, all dependencies here are for the ws command line tools, not for the IXWebSockets library which is standalone\&.
.SH "MbedTLS"
.PP
\fBA\fP small CMakeLists\&.txt fix had to be done so that the library can be included with 'include_directory' in the top level CMakeLists\&.txt file\&. See https://github.com/ARMmbed/mbedtls/issues/2609 
