.TH "md__ase_sprite_aseprite_third_party_harfbuzz__b_u_i_l_d" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_harfbuzz__b_u_i_l_d \- BUILD 
.PP
On Linux, install the development packages for FreeType, Cairo, and GLib\&. For example, on Ubuntu / Debian, you would do: 
.PP
.nf
sudo apt-get install meson pkg-config ragel gtk-doc-tools gcc g++ libfreetype6-dev libglib2\&.0-dev libcairo2-dev

.fi
.PP
 whereas on Fedora, RHEL, CentOS, and other Red Hat based systems you would do: 
.PP
.nf
sudo dnf install meson pkgconfig gtk-doc gcc gcc-c++ freetype-devel glib2-devel cairo-dev

.fi
.PP
 and on ArchLinux and Manjaro: 
.PP
.nf
sudo pacman -Suy meson pkg-config ragel gcc freetype2 glib2 cairo

.fi
.PP
 then use meson to build the project like \fCmeson build && meson test -Cbuild\fP\&.
.PP
On macOS, \fCbrew install pkg-config ragel gtk-doc freetype glib cairo meson\fP then use meson like above\&.
.PP
On Windows, meson can build the project like above if a working MSVC's cl\&.exe (\fCvcvarsall\&.bat\fP) or gcc/clang is already on your path, and if you use something like \fCmeson build --wrap-mode=default\fP it fetches and compiles most of the dependencies also\&. It is recommended to install CMake either manually or via the Visual Studio installer when building with MSVC when building with meson\&.
.PP
Our CI configurations is also a good source of learning how to build HarfBuzz\&.
.PP
There is also amalgam source provided with HarfBuzz which reduces whole process of building HarfBuzz like \fCg++ src/harfbuzz\&.cc -fno-exceptions\fP but there is not guarantee provided with buildability and reliability of features you get\&. 
