.TH "md__ase_sprite_aseprite_third_party_harfbuzz__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_harfbuzz__r_e_a_d_m_e \- README 
.PP
\fC\fP \fC\fP \fC\fP \fC\fP \fC\fP \fC\fP \fC\fP \fC\fP \fCABI Tracker\fP
.PP
This is HarfBuzz, a text shaping library\&.
.PP
For bug reports, mailing list, and other information please visit:
.PP
http://harfbuzz.org/
.PP
For license information, see [COPYING](COPYING)\&.
.PP
For build information, see \fBBUILD\&.md\fP\&.
.PP
For custom configurations, see \fBCONFIG\&.md\fP\&.
.PP
For test execution, see \fBTESTING\&.md\fP\&.
.PP
Documentation: https://harfbuzz.github.io
.PP
\fBPackaging status of HarfBuzz\fP
.PP
.PP
.RS 4

.PP
\fC\fP.PP
.RE
.PP

