.TH "md__ase_sprite_aseprite_third_party_cmark_bench_samples_rawtabs" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_cmark_bench_samples_rawtabs \- rawtabs 
.PP
this is a test for tab expansion, be careful not to replace them with spaces
.PP
1 4444 22 333 333 22 4444 1
.PP
.PP
.nf
tab-indented line
space-indented line
tab-indented line
.fi
.PP
.PP
a lot of spaces in between here
.PP
a lot of tabs in between here 
