.TH "md__ase_sprite_aseprite_third_party_curl_docs__r_o_a_d_m_a_p" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl_docs__r_o_a_d_m_a_p \- curl the next few years - perhaps 
.PP
Roadmap of things Daniel Stenberg wants to work on next\&. It is intended to serve as a guideline for others for information, feedback and possible participation\&.
.SH "'Complete' the HTTP/3 support"
.PP
curl has experimental support for HTTP/3 since a good while back\&. There are some functionality missing and once the final specs are published we want to eventually remove the 'experimental' label from this functionality\&.
.SH "HTTPS DNS records"
.PP
As a DNS version of alt-svc and also a pre-requisite for ECH (see below)\&.
.PP
See: https://tools.ietf.org/html/draft-ietf-dnsop-svcb-https-02
.SH "ECH (Encrypted Client Hello - formerly known as ESNI)"
.PP
See Daniel's post on \fCSupport of Encrypted SNI\fP on the mailing list\&.
.PP
Initial work exists in https://github.com/curl/curl/pull/4011 
