.TH "md__ase_sprite_aseprite_third_party_qoi__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_qoi__r_e_a_d_m_e \- README 
.PP

.SH "QOI - The “Quite OK Image Format” for fast, lossless image compression"
.PP
Single-file MIT licensed library for C/C++
.PP
See \fCqoi\&.h\fP for the documentation and format specification\&.
.PP
More info at https://qoiformat.org
.SS "Why?"
Compared to stb_image and stb_image_write QOI offers 20x-50x faster encoding, 3x-4x faster decoding and 20% better compression\&. It's also stupidly simple and fits in about 300 lines of C\&.
.SS "Example Usage"
.IP "\(bu" 2
\fCqoiconv\&.c\fP converts between png <> qoi
.IP "  \(bu" 4
\fCqoibench\&.c\fP a simple wrapper to benchmark stbi, libpng and qoi
.PP

.PP
.SS "MIME Type, File Extension"
The recommended MIME type for QOI images is \fCimage/qoi\fP\&. While QOI is not yet officially registered with IANA, I believe QOI has found enough adoption to prevent any future image format from choosing the same name, thus making a MIME type collision highly unlikely (\fCsee #167\fP)\&.
.PP
The recommended file extension for QOI images is \fC\&.qoi\fP
.SS "Limitations"
The QOI file format allows for huge images with up to 18 exa-pixels\&. \fBA\fP streaming en-/decoder can handle these with minimal RAM requirements, assuming there is enough storage space\&.
.PP
This particular implementation of QOI however is limited to images with a maximum size of 400 million pixels\&. It will safely refuse to en-/decode anything larger than that\&. This is not a streaming en-/decoder\&. It loads the whole image file into RAM before doing any work and is not extensively optimized for performance (but it's still very fast)\&.
.PP
If this is a limitation for your use case, please look into any of the other implementations listed below\&.
.SS "Improvements, New Versions and Contributing"
The QOI format has been finalized\&. It was a conscious decision to \fBnot\fP have a version number in the file header\&. If you have a working QOI implementation today, you can rest assured that it will be compatible with all QOI files tomorrow\&.
.PP
There are a lot of interesting ideas for a successor of QOI, but none of these will be implemented here\&. That doesn't mean you shouldn't experiment with QOI, but please be aware that pull requests that change the format will not be accepted\&.
.PP
Likewise, pull requests for performance improvements will probably not be accepted either, as this 'reference implementation' tries to be as easy to read as possible\&.
.SS "Tools"
.IP "\(bu" 2
\fCfloooh/qoiview\fP - native QOI viewer
.IP "\(bu" 2
\fCpfusik/qoi-ci\fP - QOI \fBPlugin\fP installer for Windows Explorer, Finder, GNOME, GIMP, Imagine, Paint\&.NET and XnView
.IP "\(bu" 2
\fCiOrange/QoiFileTypeNet\fP - QOI \fBPlugin\fP for Paint\&.NET
.IP "\(bu" 2
\fCiOrange/QOIThumbnailProvider\fP - Add thumbnails for QOI images in Windows Explorer
.IP "\(bu" 2
\fCTom94/tev\fP - another native QOI viewer (allows pixel peeping and comparison with other image formats)
.IP "\(bu" 2
\fCqoiconverterx\fP QOI <=> PNG converter available on the Mac App Store
.IP "\(bu" 2
\fCkaetemi/qoi-ma\fP - QOI Bitmap I/O \fBPlugin\fP for 3ds Max
.IP "\(bu" 2
\fCrtexviewer\fP - texture viewer, supports QOI
.IP "\(bu" 2
\fCrtexpacker\fP - texture packer, supports QOI
.IP "\(bu" 2
\fCDmitriySalnikov/godot_qoi\fP - QOI GDNative Addon for Godot Engine
.IP "\(bu" 2
\fCdan9er/farbfeld-convert-qoi\fP - QOI <=> farbfeld converter
.IP "\(bu" 2
\fCBen1138/unity-qo\fP - QOI support for the Unity3D Game Engine
.IP "\(bu" 2
\fCxiaozhuai/jetbrains-qo\fP - \fCQOI Support\fP for Jetbrains' IDE\&.
.IP "\(bu" 2
\fCserge-ivamov/QOIql\fP - MacOS QuickLook plugin for QOI
.IP "\(bu" 2
\fCtobozo/kde-thumbnailer-qoi\fP - QOI Thumbnailer for KDE
.IP "\(bu" 2
\fCwalksanatora/qoi-thumbnailer-nemo\fP - QOI Thumbnailer for Nemo
.IP "\(bu" 2
\fChzeller/timg\fP - a terminal image viewer with QOI support
.IP "\(bu" 2
\fCLuisAlfredo92/Super-QOI-converter\fP - \fBA\fP program to convert JPG, JPEG, BMP, and PNG to QOI
.IP "  \(bu" 4
\fCConsole version\fP: Available for Linux, OSX and Windows
.IP "  \(bu" 4
\fCGUI version\fP: Available only for windows
.PP

.PP
.SS "Implementations & Bindings of QOI"
.IP "\(bu" 2
\fCpfusik/qoi-ci\fP - Ć, transpiled to C, C++, C#, Java, JavaScript, Python and Swift
.IP "\(bu" 2
\fCkodonnell/qoi\fP - Python
.IP "\(bu" 2
\fCJaffaKetchup/dqoi\fP - Dart, with Flutter support
.IP "\(bu" 2
\fCCr4xy/lua-qoi\fP - Lua
.IP "\(bu" 2
\fCsuperzazu/SDL_QOI\fP - C, SDL2 bindings
.IP "\(bu" 2
\fCsaharNooby/qoi-java\fP - Java
.IP "\(bu" 2
\fCMasterQ32/zig-qoi\fP - Zig
.IP "\(bu" 2
\fCrbino/qoix\fP - Elixir
.IP "\(bu" 2
\fCNUlliiON/QoiSharp\fP - C#
.IP "\(bu" 2
\fCaldanor/qoi-rust\fP - Rust
.IP "\(bu" 2
\fCzakarumych/rapid-qoi\fP - Rust
.IP "\(bu" 2
\fCtakeyourhatoff/qoi\fP - Go
.IP "\(bu" 2
\fCDosWorld/pasqoi\fP - Pascal
.IP "\(bu" 2
\fCelihwyma/Swift-QOI\fP - Swift
.IP "\(bu" 2
\fCxfmoulet/qoi\fP - Go
.IP "\(bu" 2
\fCerratique\&.ch/qoic\fP - OCaml
.IP "\(bu" 2
\fCarian/go-qoi\fP - Go
.IP "\(bu" 2
\fCkchapelier/qoijs\fP - JavaScript
.IP "\(bu" 2
\fCKristofferC/QOI\&.jl\fP - Julia
.IP "\(bu" 2
\fCshadowMitia/libqoi\fP - C++
.IP "\(bu" 2
\fCMKCG/php-qoi\fP - PHP
.IP "\(bu" 2
\fCLightHouseSoftware/qoiformats\fP - D
.IP "\(bu" 2
\fCmhoward540/qoi-nim\fP - Nim
.IP "\(bu" 2
\fCwx257osn2/qoixx\fP - C++
.IP "\(bu" 2
\fCTiefseetauchner/lr-paint\fP - Processing
.IP "\(bu" 2
\fCamstan/qoi-fpga\fP - FPGA: verilog
.IP "\(bu" 2
\fCmusabkilic/qoi-decoder\fP - Python
.IP "\(bu" 2
\fCmathpn/py-qoi\fP - Python
.IP "\(bu" 2
\fCJohannesFriedrich/qoi4R\fP - R
.IP "\(bu" 2
\fCshraiwi/mini-qoi\fP - C, streaming decoder
.IP "\(bu" 2
\fC10maurycy10/libqoi/\fP - Rust
.IP "\(bu" 2
\fC0xd34df00d/hsqoi\fP - Haskell
.IP "\(bu" 2
\fC418Coffee/qoi-v\fP - V
.IP "\(bu" 2
\fCImagine-Programming/QoiImagePlugin\fP - PureBasic
.IP "\(bu" 2
\fCFabien-Chouteau/qoi-spark\fP - Ada/SPARK formally proven
.IP "\(bu" 2
\fCmzgreen/qoi-kotlin\fP - Kotlin Multiplatform
.IP "\(bu" 2
\fCAftersol/Simplified-QOI-Codec\fP - C99, streaming encoder and decoder, freestanding
.IP "\(bu" 2
\fCAuburnSounds/gamut\fP - D
.IP "\(bu" 2
\fCAngusJohnson/TQoiImage\fP - Delphi
.IP "\(bu" 2
\fCMarkJeronimus/qoi-java-spi\fP - Java SPI
.IP "\(bu" 2
\fCaumouvantsillage/qoi-racket\fP - Racket
.IP "\(bu" 2
\fCrubikscraft/qoi-stream\fP - C99, one byte at a time streaming encoder and decoder
.IP "\(bu" 2
\fCrubikscraft/qoi-img\fP - NodeJS typescript, bindings to both \fCQOIxx\fP and \fCqoi-stream\fP
.PP
.SS "QOI Support in Other Software"
.IP "\(bu" 2
\fCAmiga OS QOI datatype\fP - adds support for decoding QOI images to the Amiga operating system\&.
.IP "\(bu" 2
\fCSerenityOS\fP - supports decoding QOI system wide through a custom \fCcpp implementation in LibGfx\fP
.IP "\(bu" 2
\fCRaylib\fP - supports decoding and encoding QOI textures through its \fCrtextures module\fP
.IP "\(bu" 2
\fCRebol3\fP - supports decoding and encoding QOI using a native codec
.IP "\(bu" 2
\fCc-ray\fP - supports QOI natively
.IP "\(bu" 2
\fCSAIL\fP - image decoding library, supports decoding and encoding QOI images
.IP "\(bu" 2
\fCOrx\fP - 2D game engine, supports QOI natively
.IP "\(bu" 2
\fCIrfanView\fP - supports decoding and encoding QOI through its Formats plugin
.IP "\(bu" 2
\fCImageMagick\fP - supports decoding and encoding QOI, since 7\&.1\&.0-20
.IP "\(bu" 2
\fCbarebox\fP - bootloader, supports decoding QOI images for splash logo, since v2022\&.03\&.0
.IP "\(bu" 2
\fCKorGE\fP - & KorIM Kotlin 2D game engine and imaging library, supports decoding and encoding QOI natively since 2\&.7\&.0
.IP "\(bu" 2
\fCDOjS\fP - DOS JavaScript Canvas implementation supports loading QOI files
.IP "\(bu" 2
\fCXnView MP\fP - supports decoding QOI since 1\&.00
.PP
.SS "Packages"
.IP "\(bu" 2
\fCAUR\fP - system-wide \fBqoi\&.h\fP, qoiconv and qoibench install as split packages\&.
.IP "\(bu" 2
\fCDebian\fP - packages for binaries and \fBqoi\&.h\fP
.IP "\(bu" 2
\fCUbuntu\fP - packages for binaries and \fBqoi\&.h\fP
.PP
.PP
Packages for other systems \fCtracked at Repology\fP\&. 
