.TH "md__ase_sprite_aseprite_tests__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_tests__r_e_a_d_m_e \- Aseprite Tests 
.PP
\fBTest\fP suite for \fCAseprite\fP to avoid breaking backward compatibility\&.
.PP
This directory is cloned by the \fCbuild\&.yml\fP action to run several automated tests after Aseprite is compiled:
.PP
.IP "\(bu" 2
Save/load file formats correctly\&. For this we have \fC\&.aseprite\fP, \fC\&.png\fP, \fC\&.gif\fP, etc\&. files \fCsprites\fP folder\&.
.IP "\(bu" 2
\fBTest\fP backward compatibility with \fCAseprite CLI\fP options
.IP "\(bu" 2
Future \fCscripting API\fP using \fCscripts\fP
.PP
.SH "How to run tests?"
.PP
You have to set the \fCASEPRITE\fP environment variable pointing to the Aseprite executable and then run \fCrun-tests\&.sh\fP from Bash: 
.PP
.nf
export ASEPRITE=$HOME/your-aseprite-build/bin/aseprite
cd tests
bash run-tests\&.sh

.fi
.PP
 You can filter some tests with a regex giving a parameter to \fCrun-tests\&.sh\fP, for example: 
.PP
.nf
run-tests\&.sh color

.fi
.PP
 Should run all tests which have the \fCcolor\fP word in their name\&. 
