.TH "md__ase_sprite_aseprite__c_o_d_e__o_f__c_o_n_d_u_c_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite__c_o_d_e__o_f__c_o_n_d_u_c_t \- Contributor Code of Conduct 
.PP
As contributors and maintainers of this project, and in the interest of fostering an open and welcoming community, we pledge to respect all people who contribute through reporting issues, posting feature requests, updating documentation, submitting pull requests or patches, and other activities\&.
.PP
We are committed to making participation in this project a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, or nationality\&.
.PP
Examples of unacceptable behavior by participants include:
.PP
.IP "\(bu" 2
The use of sexualized language or imagery
.IP "\(bu" 2
Personal attacks
.IP "\(bu" 2
Trolling or insulting/derogatory comments
.IP "\(bu" 2
Public or private harassment
.IP "\(bu" 2
Publishing other's private information, such as physical or electronic addresses, without explicit permission
.IP "\(bu" 2
Other unethical or unprofessional conduct\&.
.PP
.PP
Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct\&. By adopting this Code of Conduct, project maintainers commit themselves to fairly and consistently applying these principles to every aspect of managing this project\&. Project maintainers who do not follow or enforce the Code of Conduct may be permanently removed from the project team\&.
.PP
This code of conduct applies both within project spaces and in public spaces when an individual is representing the project or its community\&.
.PP
Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by opening an issue or contacting one or more of the project maintainers\&.
.PP
This Code of Conduct is adapted from the \fCContributor Covenant\fP, version 1\&.2\&.0, available at \fChttp://contributor-covenant\&.org/version/1/2/0/\fP 
