.TH "md__ase_sprite_aseprite_third_party_lua__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_lua__r_e_a_d_m_e \- Lua 
.PP
This is the repository of Lua development code, as seen by the Lua team\&. It contains the full history of all commits but is mirrored irregularly\&. For complete information about Lua, visit \fCLua\&.org\fP\&.
.PP
Please \fBdo not\fP send pull requests\&. To report issues, post a message to the \fCLua mailing list\fP\&.
.PP
Download official Lua releases from \fCLua\&.org\fP\&. 
