.TH "md__o_p_e_n_g_l_study_resource__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__o_p_e_n_g_l_study_resource__r_e_a_d_m_e \- README 
.PP
Good OpenGL Study Resource
.SS "Homogeneous Cordinate"
http://www.songho.ca/math/homogeneous/homogeneous.html 
