.TH "md__ase_sprite_aseprite_third_party_curl_include__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl_include__r_e_a_d_m_e \- include 
.PP
Public include files for libcurl, external users\&.
.PP
They're all placed in the curl subdirectory here for better fit in any kind of environment\&. You must include files from here using\&.\&.\&. 
.PP
.nf
#include <curl/curl\&.h>

.fi
.PP
 \&.\&.\&. style and point the compiler's include path to the directory holding the curl subdirectory\&. It makes it more likely to survive future modifications\&.
.PP
The public curl include files can be shared freely between different platforms and different architectures\&. 
