.TH "md__ase_sprite_aseprite_third_party_cmark_bench_samples_inline_html" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_cmark_bench_samples_inline_html \- inline-html 
.PP
Taking commonmark tests from the spec for benchmarking here:
.PP
<bab><c2c>
.PP
<b2>
.PP
<b2
data='foo' >
.PP
<33> <__>
.PP
<a h*ref='hi'>
.PP
<a href='hi'> <a href=hi'>

< a><
foo><bar/ >

<a href='bar'title=title>

</a>
</foo >

</a href='foo'>

foo 


foo 

foo <?php echo $a; ?>

foo <!ELEMENT br EMPTY>

foo \\>\\&\\<

<a href='o\*(4'>

<a href='\\*'>

<a href='""> 
