.TH "md__ase_sprite_aseprite_laf_docs_backend" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_laf_docs_backend \- laf backend 
.PP
\fIlaf\fP can be compiled with different backends\&. \fBA\fP backend is another library or platform used to implement \fIlaf\fP functionality/API\&.
.PP
.IP "\(bu" 2
\fCLAF_BACKEND=skia\fP: \fClaf-os\fP will use Skia for drawing on the native window
.IP "\(bu" 2
\fCLAF_BACKEND=none\fP: Mainly for CLI apps (when no UI is required) 
.PP

