.TH "md__ase_sprite_aseprite_laf_docs_gfx__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_laf_docs_gfx__r_e_a_d_m_e \- laf-gfx 
.PP
\fIlaf-gfx\fP provides some common structures to handle graphics (in UI level or at the logic
.SH "API Reference"
.PP
.IP "\(bu" 2
\fCgfx::Border\fP
.IP "\(bu" 2
\fCgfx::Clip\fP
.IP "\(bu" 2
\fCgfx::Color\fP
.IP "\(bu" 2
\fCgfx::ColorSpace\fP
.IP "\(bu" 2
\fCgfx::Hsl\fP
.IP "\(bu" 2
\fCgfx::Hsv\fP
.IP "\(bu" 2
\fCgfx::Matrix\fP
.IP "\(bu" 2
\fCgfx::PackingRects\fP
.IP "\(bu" 2
\fCgfx::Path\fP
.IP "\(bu" 2
\fCgfx::Point\fP
.IP "\(bu" 2
\fCgfx::Rect\fP
.IP "\(bu" 2
\fCgfx::Region\fP
.IP "\(bu" 2
\fCgfx::Rgb\fP
.IP "\(bu" 2
\fCgfx::Size\fP 
.PP

