.TH "md__ase_sprite_aseprite_third_party__i_x_web_socket_test_compatibility_ruby__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party__i_x_web_socket_test_compatibility_ruby__r_e_a_d_m_e \- README 
.PP

.PP
.nf
export GEM_HOME=$HOME/local/gems
bundle install faye\-websocket

.fi
.PP
.PP
https://stackoverflow.com/questions/486995/ruby-equivalent-of-virtualenv 
