.TH "md__ase_sprite_aseprite_src_psd__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_src_psd__r_e_a_d_m_e \- Aseprite PSD Library 
.PP
\fC\fP \fC\fP
.PP
Experimental and \fIWork-In-Progress\fP C++ library to read/write PSD files\&.
.PP
Based on \fCspecs published by Adobe\fP
.SH "Roadmap"
.PP
.IP "\(bu" 2
[ ] Read PSD files
.IP "\(bu" 2
[ ] Write PSD files 
.PP

