.TH "md__ase_sprite_aseprite_third_party_libwebp__c_o_n_t_r_i_b_u_t_i_n_g" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_libwebp__c_o_n_t_r_i_b_u_t_i_n_g \- How to Contribute 
.PP
We'd love to accept your patches and contributions to this project\&. There are just a few small guidelines you need to follow\&.
.SH "Contributor License Agreement"
.PP
Contributions to this project must be accompanied by a Contributor License Agreement\&. You (or your employer) retain the copyright to your contribution; this simply gives us permission to use and redistribute your contributions as part of the project\&. Head over to https://cla.developers.google.com/ to see your current agreements on file or to sign a new one\&.
.PP
You generally only need to submit a CLA once, so if you've already submitted one (even if it was for a different project), you probably don't need to do it again\&.
.SH "Code reviews"
.PP
All submissions, including submissions by project members, require review\&. We use a \fCGerrit\fP instance hosted at https://chromium-review.googlesource.com for this purpose\&. See the \fCWebM Project page\fP for additional details\&.
.SH "Community Guidelines"
.PP
This project follows \fCGoogle's Open Source Community Guidelines\fP\&. 
