.TH "md__ase_sprite_aseprite__c_o_n_t_r_i_b_u_t_i_n_g" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite__c_o_n_t_r_i_b_u_t_i_n_g \- Code of Conduct 
.PP
We have a \fBcode of conduct\fP that we all must read\&. Be polite to everyone\&. If you are not in your best day, take a deep breath and try again\&. Smile :smile:
.SH "New Issues"
.PP
Before you submit an issue:
.PP
.IP "\(bu" 2
Search in the current \fClist of issues\fP, \fCbug reports\fP, or \fCfeature requests\fP\&.
.IP "\(bu" 2
If the issue already exists, add a :+1: or a :heart:, and you can click the \fCSubscribe\fP or \fCWatching\fP button to get notifications via email\&.
.PP
.SH "Compilation problem"
.PP
Before you submit an issue or a post about a \fBcompilation problem\fP, check the following items:
.PP
.IP "\(bu" 2
See how to get the source code correctly in the \fBINSTALL\fP guide\&.
.IP "\(bu" 2
Check if you are using the latest repository clone\&.
.IP "\(bu" 2
Remember that we use submodules, so you need to initialize and update them\&.
.IP "\(bu" 2
Remember that might be some \fCpull requests\fP being reviewed to fix your same problem\&.
.PP
.PP
If you have a compilation problem, you can ask in the \fCDevelopment category\fP in the \fCCommunity site\fP for help or creating a \fCGitHub issue\fP\&.
.SH "Contributing"
.PP
One of the easiest ways to contribute is writing articles, \fCSteam reviews\fP, blog posts, recording video tutorials, \fCcreating pixel art\fP, or showing your love to Aseprite e\&.g\&. naming Aseprite in your website and linking it to https://www.aseprite.org/, following \fC@aseprite\fP twitter account, or \fCbuying an extra Aseprite copy to your friend\fP\&.
.PP
Other ways to contribute require direct contact with us\&. For example:
.PP
.IP "\(bu" 2
\fCWriting documentation\fP\&.
.IP "\(bu" 2
Making art with Aseprite and for Aseprite (logos, skins, mockups)\&.
.IP "\(bu" 2
Sending patches for features or bug fixes\&.
.IP "\(bu" 2
Reviewing issues in the \fCissue tracker\fP and making comments\&.
.IP "\(bu" 2
Helping other users in the \fCCommunity\fP site\&.
.PP
.SS "Documentation"
You can start seeing the \fCdocumentation\fP, and \fCcontact us\fP if you want to help writting documentation or recording \fCtutorials\fP\&.
.PP
If you are going to write documentation, we recommend you to take screenshots or record a GIF animations to show steps:
.PP
.IP "\(bu" 2
As screen recording software, on Windows you can generate GIF files using \fCLICEcap\fP\&.
.IP "\(bu" 2
You can upload the PNG/GIF images to \fCImgur\fP\&.
.PP
.SS "Reviewing Issues"
You can \fCreview issues\fP, make comments, or create new \fCfeatures\fP, \fCbug reports\fP, etc\&. You are encouraged to create mockups for any issue you see and attach them\&.
.SS "Hacking"
The first thing to keep in mind if you want to modify the source code: checkout the \fBmain\fP branch\&. It is the branch that we use to develop new features and fix issues that are planned for the next big release\&. See the \fBINSTALL\fP guide to know how to compile\&.
.PP
To start looking the source code, see how it is organized in \fCsrc/README\&.md\fP file\&.
.SS "Forking & Pull Requests"
You can fork the GitHub repository using the Fork button at \fChttps://github\&.com/aseprite/aseprite\fP\&.
.PP
The Pull Requests (PR) systems works in this way:
.PP
.IP "1." 4
First of all you will need to sign our \fCContributor License Agreement\fP (CLA)\&.
.PP
.IP "1." 4
Then you can start working on Aseprite\&. Create a new branch from \fCmain\fP, e\&.g\&. \fCfix-8\fP to fix the issue 8\&. Check this guide about \fChow to name your branch\fP\&.
.PP
.IP "1." 4
Start working on that new branch, and push your commits to your fork\&.
.PP
.IP "1." 4
Create a new PR to merge your \fCfix-8\fP branch to the official \fCmain\fP\&.
.PP
.IP "1." 4
If the PR is accepted (does not require review/comments/modifications), your branch is merged into \fCmain\fP\&.
.PP
.IP "1." 4
You will need to pull changes from the official \fCmain\fP branch, and merge them in your own \fCmain\fP branch\&. Finally you can discard your own \fCfix-8\fP branch (because those changes should be already merged into \fCmain\fP if the PR was accepted)\&.
.PP
.IP "1." 4
Continue working from the new \fCmain\fP head\&.
.PP
.PP
To keep in mind: \fBalways\fP start working from the \fCmain\fP head, if you want to fix three different issues, create three different branches from \fCmain\fP and then send three different PR\&. Do not chain all the fixes in one single branch\&. E\&.g\&. \fCfix-issues-3-and-8-and-25\fP\&.
.SS "Community"
You can use the \fCDevelopment category\fP to ask question about the code, how to compile, etc\&. If you want to start working in something (\fCissue\fP, \fCbug\fP, or \fCfeature\fP), post a comment asking if somebody is already working on that, in that way you can avoid start programming in something that is already done for the next release or which someone else is working on\&.
.PP
And always remember to take a look at our \fCroadmap\fP\&. 
