.TH "md__ase_sprite_aseprite_third_party_curl_docs__m_q_t_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl_docs__m_q_t_t \- \fBMQTT\fP in curl 
.PP

.SH "Usage"
.PP
\fBA\fP plain 'GET' subscribes to the topic and prints all published messages\&. Doing a 'POST' publishes the post data to the topic and exits\&.
.PP
Example subscribe: 
.PP
.nf
curl mqtt://host/home/bedroom/temp

.fi
.PP
 Example publish: 
.PP
.nf
curl -d 75 mqtt://host/home/bedroom/dimmer

.fi
.PP
 
.SH "What does curl deliver as a response to a subscribe"
.PP
It outputs two bytes topic length (MSB | LSB), the topic followed by the payload\&.
.SH "Caveats"
.PP
Remaining limitations:
.IP "\(bu" 2
Only QoS level 0 is implemented for publish
.IP "\(bu" 2
No way to set retain flag for publish
.IP "\(bu" 2
No TLS (mqtts) support
.IP "\(bu" 2
Naive EAGAIN handling won't handle split messages 
.PP

