.TH "md__ase_sprite_aseprite_laf_third_party_googletest_googlemock_include_gmock_internal_custom__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_laf_third_party_googletest_googlemock_include_gmock_internal_custom__r_e_a_d_m_e \- Customization Points 
.PP
The custom directory is an injection point for custom user configurations\&.
.SH "Header <tt>gmock-port\&.h</tt>"
.PP
The following macros can be defined:
.SS "Flag related macros:"
.IP "\(bu" 2
\fCGMOCK_DECLARE_bool_(name)\fP
.IP "\(bu" 2
\fCGMOCK_DECLARE_int32_(name)\fP
.IP "\(bu" 2
\fCGMOCK_DECLARE_string_(name)\fP
.IP "\(bu" 2
\fCGMOCK_DEFINE_bool_(name, default_val, doc)\fP
.IP "\(bu" 2
\fCGMOCK_DEFINE_int32_(name, default_val, doc)\fP
.IP "\(bu" 2
\fCGMOCK_DEFINE_string_(name, default_val, doc)\fP
.IP "\(bu" 2
\fCGMOCK_FLAG_GET(flag_name)\fP
.IP "\(bu" 2
\fCGMOCK_FLAG_SET(flag_name, value)\fP 
.PP

