.TH "md__ase_sprite_aseprite_third_party_cmark_bench_samples_block_list_flat" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_cmark_bench_samples_block_list_flat \- block-list-flat 
.PP

.IP "\(bu" 2
tidy
.PP
.PP
bullet
.IP "\(bu" 2
list
.IP "\(bu" 2
loose
.IP "\(bu" 2
bullet
.IP "\(bu" 2
list
.PP
.PP
0\&. ordered
.IP "1." 4
list
.IP "2." 4
example
.PP
.IP "\(bu" 2

.IP "\(bu" 2

.IP "\(bu" 2

.IP "\(bu" 2

.PP
.PP
1\&. 2\&. 3\&.
.PP
.IP "\(bu" 2
an example of a list item with a continuation
.PP
this part is inside the list
.PP
this part is just a paragraph 
.br

.PP
.IP "1." 4
test
.PP
.IP "\(bu" 2
test
.PP
.IP "1." 4
test
.PP
.IP "\(bu" 2
test
.PP
.PP
is this a valid bullet?
.PP
.IP "\(bu" 2
_________________________
.IP "\(bu" 2
this
.IP "\(bu" 2
is
.PP
a
.PP
long
.IP "\(bu" 2
loose
.IP "\(bu" 2
list
.IP "\(bu" 2
with
.IP "\(bu" 2
some
.PP
tidy
.IP "\(bu" 2
list
.IP "\(bu" 2
items
.IP "\(bu" 2
in
.IP "\(bu" 2
between
.IP "\(bu" 2
_________________________ 
.PP

