.TH "md__ase_sprite_aseprite_third_party_curl_docs__a_l_t_s_v_c" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl_docs__a_l_t_s_v_c \- Alt-Svc 
.PP
curl features support for the Alt-Svc: \fBHTTP\fP header\&.
.SH "Enable Alt-Svc in build"
.PP
\fC\&./configure --enable-alt-svc\fP
.PP
(enabled by default since 7\&.73\&.0)
.SH "Standard"
.PP
\fCRFC 7838\fP
.SH "Alt-Svc cache file format"
.PP
This a text based file with one line per entry and each line consists of nine space separated fields\&.
.SS "Example"
.PP
.nf
h2 quic\&.tech 8443 h3-22 quic\&.tech 8443 '20190808 06:18:37' 0 0
.fi
.PP
 
.SS "Fields"
.IP "1." 4
The ALPN id for the source origin
.IP "2." 4
The host name for the source origin
.IP "3." 4
The port number for the source origin
.IP "4." 4
The ALPN id for the destination host
.IP "5." 4
The host name for the destination host
.IP "6." 4
The host number for the destination host
.IP "7." 4
The expiration date and time of this entry within double quotes\&. The date format is 'YYYYMMDD HH:MM:SS' and the time zone is GMT\&.
.IP "8." 4
Boolean (1 or 0) if 'persist' was set for this entry
.IP "9." 4
Integer priority value (not currently used)
.PP
.SH "TODO"
.PP
.IP "\(bu" 2
handle multiple response headers, when one of them says \fCclear\fP (should override them all)
.IP "\(bu" 2
using \fCAge:\fP value for caching age as per spec
.IP "\(bu" 2
\fCCURLALTSVC_IMMEDIATELY\fP support 
.PP

