.TH "md__ase_sprite_aseprite_third_party_freetype2_tests__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_freetype2_tests__r_e_a_d_m_e \- Unit and regression tests for the FreeType library 
.PP

.SH "Quick Start"
.PP
.SS "Download test fonts"
Run the \fCtests/scripts/download-fonts\&.py\fP script, which will download test fonts to the \fCtests/data/\fP directory first\&.
.SS "Build the test programs"
The tests are only built with the Meson build system, and are disabled by default, enable the 'tests' option to compile them, as in:
.PP
meson setup out -Dtests=enabled meson compile -C out
.SS "Run the test programs"
meson test -C out 
