.TH "md__ase_sprite_aseprite_laf_docs__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_laf_docs__r_e_a_d_m_e \- laf documentation 
.PP
\fIlaf\fP is a C++ library to create desktop applications for Windows, macOS, and Linux\&. It was mainly developed for \fCAseprite\fP but we want to make it available for other developers in such a way that they can create applications too\&.
.PP
This 'framework' (or library, or set of libraries) is still under development, but we'd like to start stabilizing the main API in a near future\&. The objective is to create a library as small as possible, and leaving parts that are not required to be integrated, to other libraries\&. For example, signal and slots can be used with \fCother libraries\fP, or the clipboard management with \fCdacap/clip\fP, etc\&. Even more, parts of \fIlaf\fP might be separated to other libraries in the future if they are highly valuable on their own\&.
.SH "Modules"
.PP
\fIlaf\fP is a set of libraries:
.PP
.IP "\(bu" 2
[base](base): \fBBase\fP functions for any kind of application (CLI and GUI), generally one function doesn't depend on others, so it has a minimal set of dependencies
.IP "\(bu" 2
[gfx](gfx): Abstract graphics classes (rectangle, point, region, etc\&.)
.IP "\(bu" 2
[ft](ft): FreeType wrapper used by the \fCos\fP module (requires \fCfreetype\fP library as dependency)\&. Might be deleted in the future (replaced with Skia text rendering)
.IP "\(bu" 2
[os](os): Functions to create windows in your Operating System
.PP
.SH "Platform-specific Definitions"
.PP
Compiling in a specific operating system/platforms:
.PP
.IP "\(bu" 2
\fCLAF_WINDOWS\fP
.IP "\(bu" 2
\fCLAF_MACOS\fP
.IP "\(bu" 2
\fCLAF_LINUX\fP
.PP
.PP
\fB*laf* backend\fP:
.PP
.IP "\(bu" 2
\fCLAF_SKIA\fP: When we compile with \fCLAF_BACKEND=skia\fP, Skia library is available
.PP
.PP
CPU \fCendianness\fP (defined in \fCbase/config\&.h\fP):
.PP
.IP "\(bu" 2
\fCLAF_LITTLE_ENDIAN\fP
.IP "\(bu" 2
\fCLAF_BIG_ENDIAN\fP 
.PP

