.TH "md__ase_sprite_aseprite_src_steam__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_src_steam__r_e_a_d_m_e \- Aseprite Steam Wrapper 
.PP
\fICopyright (C) 2016 David Capello\fP
.PP
.RS 4
Distributed under \fCMIT license\fP 
.RE
.PP
This is a way to use the Steam API without linking to the static \fC\&.lib\fP, so we can avoid including the official \fCsteam_api\&.dll\fP in our own packages (e\&.g\&. when we distribute our game outside the Steam store)\&. 
