.TH "md__ase_sprite_aseprite__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite__r_e_a_d_m_e \- Aseprite 
.PP
\fC\fP \fC\fP \fC\fP
.SH "Introduction"
.PP
\fBAseprite\fP is a program to create animated sprites\&. Its main features are:
.PP
.IP "\(bu" 2
Sprites are composed of \fClayers & frames\fP as separated concepts\&.
.IP "\(bu" 2
Support for \fCcolor profiles\fP and different \fCcolor modes\fP: RGBA, Indexed (palettes up to 256 colors), Grayscale\&.
.IP "\(bu" 2
\fCAnimation facilities\fP, with real-time \fCpreview\fP and \fConion skinning\fP\&.
.IP "\(bu" 2
\fCExport/import\fP animations to/from \fCsprite sheets\fP, GIF files, or sequence of PNG files (and FLC, FLI, JPG, BMP, PCX, TGA)\&.
.IP "\(bu" 2
\fCMultiple editors\fP support\&.
.IP "\(bu" 2
\fCLayer groups\fP for organizing your work, and \fCreference layers\fP for rotoscoping\&.
.IP "\(bu" 2
Pixel-art specific tools like \fCPixel Perfect freehand mode\fP, \fCShading ink\fP, \fCCustom Brushes\fP, \fCOutlines\fP, \fCWide Pixels\fP, etc\&.
.IP "\(bu" 2
Other special drawing tools like \fCPressure sensitivity\fP, \fCSymmetry Tool\fP, \fCStroke and Fill\fP selection, \fCGradients\fP\&.
.IP "\(bu" 2
\fCTiled mode\fP useful to draw patterns and textures\&.
.IP "\(bu" 2
\fCTransform multiple frames/layers\fP at the same time\&.
.IP "\(bu" 2
\fCLua scripting capabilities\fP\&.
.IP "\(bu" 2
\fCCLI - Command Line Interface\fP to automatize tasks\&.
.IP "\(bu" 2
\fCQuick Reference / Cheat Sheet\fP keyboard shortcuts (\fCcustomizable keys\fP and \fCmouse wheel\fP)\&.
.IP "\(bu" 2
\fCReopen closed files\fP and \fCrecover data\fP in case of crash\&.
.IP "\(bu" 2
Undo/Redo for every operation and support for \fCnon-linear undo\fP\&.
.IP "\(bu" 2
\fCMore features & tips\fP
.PP
.SH "Issues"
.PP
There is a list of \fCKnown Issues\fP (things to be fixed or that aren't yet implemented)\&.
.PP
If you found a bug or have a new idea/feature for the program, \fCyou can report them\fP\&.
.SH "Support"
.PP
You can ask for help in:
.PP
.IP "\(bu" 2
\fCAseprite Community\fP
.IP "\(bu" 2
\fCAseprite Discord Server\fP
.IP "\(bu" 2
Official support: \fCsupport@aseprite\&.org\fP
.IP "\(bu" 2
Social networks and community-driven places: \fCTwitter\fP, \fCFacebook\fP, \fCYouTube\fP, \fCInstagram\fP\&.
.PP
.SH "Authors"
.PP
Aseprite is being developed by \fCIgara Studio\fP:
.PP
.IP "\(bu" 2
\fCDavid Capello\fP
.IP "\(bu" 2
\fCGaspar Capello\fP
.IP "\(bu" 2
\fCMartín Capello\fP
.PP
.SH "Credits"
.PP
The default Aseprite theme was introduced in v0\&.8, created by:
.PP
.IP "\(bu" 2
\fCIlija Melentijevic\fP
.PP
.PP
\fBA\fP modified dark version of this theme introduced in v1\&.3-beta1 was created by:
.PP
.IP "\(bu" 2
\fCNicolas Desilets\fP
.IP "\(bu" 2
\fCDavid Capello\fP
.PP
.PP
Aseprite includes color palettes created by:
.PP
.IP "\(bu" 2
\fCRichard "DawnBringer" Fhager\fP, \fC16 colors\fP, \fC32 colors\fP\&.
.IP "\(bu" 2
\fCArne Niklas Jansson\fP, \fC16 colors\fP, \fC32 colors\fP\&.
.IP "\(bu" 2
\fCENDESGA Studios\fP, \fCEDG16 and EDG32\fP, and \fCother palettes\fP\&.
.IP "\(bu" 2
\fCHyohnoo Games\fP, \fCmail24\fP palette\&.
.IP "\(bu" 2
\fCDavit Masia\fP, \fCmatriax8c\fP palette\&.
.IP "\(bu" 2
\fCJavier Guerrero\fP, \fCnyx8\fP palette\&.
.IP "\(bu" 2
\fCAdigun A\&. Polack\fP, \fCAAP-64\fP, \fCAAP-Splendor128\fP, \fCSimpleJPC-16\fP, and \fCAAP-Micro12\fP palette\&.
.IP "\(bu" 2
\fCPineTreePizza\fP, \fCRosy-42\fP palette\&.
.PP
.PP
It tries to replicate some pixel-art algorithms:
.PP
.IP "\(bu" 2
\fCRotSprite\fP by Xenowhirl\&.
.IP "\(bu" 2
\fCPixel perfect drawing algorithm\fP by \fCSébastien Bénard\fP and \fCCarduus\fP\&.
.PP
.PP
Thanks to \fBthird-party open source projects\fP, to \fCcontributors\fP, and all the people who have contributed ideas, patches, bugs report, feature requests, donations, and help me to develop Aseprite\&.
.SH "License"
.PP
This program is distributed under three different licenses:
.PP
.IP "1." 4
Source code and official releases/binaries are distributed under our \fCEnd-User License Agreement for Aseprite (EULA)\fP\&. Please check that there are \fBmodules/libraries in the source code\fP that are distributed under the MIT license (e\&.g\&. \fClaf\fP, \fCclip\fP, \fCundo\fP, \fCobservable\fP, \fCui\fP, etc\&.)\&.
.IP "2." 4
You can request a special \fCeducational license\fP in case you are a teacher in an educational institution and want to use Aseprite in your classroom (in-situ)\&.
.IP "3." 4
Steam releases are distributed under the terms of the \fCSteam Subscriber Agreement\fP\&.
.PP
.PP
You can get more information about Aseprite license in the \fCFAQ\fP\&. 
