.TH "md__ase_sprite_aseprite_third_party__i_x_web_socket__s_e_c_u_r_i_t_y" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party__i_x_web_socket__s_e_c_u_r_i_t_y \- Security Policy 
.PP

.SH "Supported Versions"
.PP
Version   Supported    7\&.x\&.x   :white_check_mark:   
.SH "Reporting a Vulnerability"
.PP
Users should send an email to bsergean@gmail.com to report a vulnerability\&. 
