.TH "md__ase_sprite_aseprite_third_party_harfbuzz__r_e_a_d_m_e_python" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_harfbuzz__r_e_a_d_m_e_python \- README\&.python 
.PP
To enable HarfBuzz bindings for Python among other languages, make sure you have latest version of gobject-introspection available\&. On Ubuntu, you can install that this way:
.PP
.PP
.nf
sudo apt\-get install libgirepository1\&.0\-dev
.fi
.PP
.PP
And then run \fCmeson setup\fP and make sure that \fCIntrospection\fP is reported enabled in output\&.
.PP
Compile and install\&.
.PP
Make sure you have the installation lib dir in \fCLD_LIBRARY_PATH\fP, as needed for the linker to find the library\&.
.PP
Then make sure you also have \fCGI_TYPELIB_PATH\fP pointing to the resulting \fC$prefix/lib/girepository-*\fP directory\&.
.PP
Make sure you have pygobject installed\&. Then check that the following import works in your Python interpreter:
.PP
.PP
.nf
from gi\&.repository import HarfBuzz
.fi
.PP
.PP
If it does, you are ready to call HarfBuzz from Python! Congratulations\&. See \fC\fCsrc/sample\&.py\fP\fP\&.
.PP
The Python API will change\&. Let us know on the mailing list if you are using it, and send lots of feedback\&. 
