.TH "md__ase_sprite_aseprite_third_party_curl_docs__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl_docs__r_e_a_d_m_e \- README 
.PP

.SH "Documentation"
.PP
You'll find a mix of various documentation in this directory and subdirectories, using several different formats\&. Some of them are not ideal for reading directly in your browser\&.
.PP
If you'd rather see the rendered version of the documentation, check out the curl website's \fCdocumentation section\fP for general curl stuff or the \fClibcurl section\fP for libcurl related documentation\&. 
