.TH "md__ase_sprite_aseprite_third_party_curl__s_e_c_u_r_i_t_y" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl__s_e_c_u_r_i_t_y \- Security Policy 
.PP
See \fBdocs/SECURITY-PROCESS\&.md\fP for full details\&.
.SH "Reporting a Vulnerability"
.PP
If you have found or just suspect a security problem somewhere in curl or libcurl, report it on \fChttps://hackerone\&.com/curl\fP\&.
.PP
We treat security issues with confidentiality until controlled and disclosed responsibly\&. 
