.TH "md__ase_sprite_aseprite_src_app_cmd__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_src_app_cmd__r_e_a_d_m_e \- Shared pointers 
.PP
Do not keep \fCImageRef\fP or any kind of smart pointer to \fCdoc::\fP entities\&. As several \fCcmd\fP can persist in parallel with other \fCcmd\fP (due the tree structure of the \fCundo history\fP) these smart pointers can generate conflicts in the logic layer\&. E\&.g\&. If we keep an \fCImageRef\fP inside a \fCcmd\fP, the image is not removed from the \fCobjects hash table\fP, so two or more \fCcmd\fP could try to add/remove the same object in the hash table (there are asserts to check this state, were someone is trying to add the same \fCObjectId\fP in the hash table)\&. 
