.TH "md__ase_sprite_aseprite_third_party_fmt__c_o_n_t_r_i_b_u_t_i_n_g" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_fmt__c_o_n_t_r_i_b_u_t_i_n_g \- Contributing to {fmt} 
.PP
By submitting a pull request or a patch, you represent that you have the right to license your contribution to the {fmt} project owners and the community, agree that your contributions are licensed under the {fmt} license, and agree to future changes to the licensing\&.
.PP
All C++ code must adhere to \fCGoogle C++ Style Guide\fP with the following exceptions:
.PP
.IP "\(bu" 2
Exceptions are permitted
.IP "\(bu" 2
snake_case should be used instead of UpperCamelCase for function and type names
.PP
.PP
All documentation must adhere to the \fCGoogle Developer Documentation Style Guide\fP\&.
.PP
Thanks for contributing! 
