.TH "md__ase_sprite_aseprite_third_party_curl_docs_cmdline_opts__m_a_n_p_a_g_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl_docs_cmdline_opts__m_a_n_p_a_g_e \- curl man page generator 
.PP
This is the curl man page generator\&. It generates a single nroff man page output from the set of sources files in this directory\&.
.PP
There is one source file for each supported command line option\&. The output gets \fCpage-header\fP prepended and \fCpage-footer\fP appended\&. The format is described below\&.
.SH "Option files"
.PP
Each command line option is described in a file named \fC<long name>\&.d\fP, where option name is written without any prefixing dashes\&. Like the file name for the -v, --verbose option is named \fCverbose\&.d\fP\&.
.PP
Each file has a set of meta-data and a body of text\&.
.SS "Meta-data"
.PP
.nf
Short: (single letter, without dash)
Long: (long form name, without dashes)
Arg: (the argument the option takes)
Magic: (description of 'magic' options)
Tags: (space separated list)
Protocols: (space separated list for which protocols this option works)
Added: (version number in which this was added)
Mutexed: (space separated list of options this overrides, no dashes)
Requires: (space separated list of features this requires, no dashes)
See-also: (space separated list of related options, no dashes)
Help: (short text for the --help output for this option)
Example: (example command line, without 'curl' and can use `$URL`)
--- (end of meta-data)
.fi
.PP
 
.SS "Body"
The body of the description\&. Only refer to options with their long form option version, like \fC--verbose\fP\&. The output generator will replace such with the correct markup that shows both short and long version\&.
.PP
Text written within \fC*asterisks*\fP will get shown using italics\&. Text within two \fC**asterisks**\fP will get shown using bold\&.
.SH "Header and footer"
.PP
\fCpage-header\fP is the file that will be output before the generated options output for the master man page\&.
.PP
\fCpage-footer\fP is appended after all the individual options\&.
.SH "Generate"
.PP
\fC\&./gen\&.pl mainpage\fP
.PP
This command outputs a single huge nroff file, meant to become \fCcurl\&.1\fP\&. The full curl man page\&.
.PP
\fC\&./gen\&.pl listhelp\fP
.PP
Generates a full \fCcurl --help\fP output for all known command line options\&. 
