.TH "md__ase_sprite_aseprite_third_party_curl_docs__r_u_s_t_l_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl_docs__r_u_s_t_l_s \- Rustls 
.PP
\fCRustls is a TLS backend written in Rust\&.\fP\&. Curl can be built to use it as an alternative to OpenSSL or other TLS backends\&. We use the \fCrustls-ffi C bindings\fP\&. This version of curl depends on version v0\&.7\&.0 of rustls-ffi\&.
.SH "Building with rustls"
.PP
First, \fCinstall Rust\fP\&.
.PP
Next, check out, build, and install the appropriate version of rustls-ffi: 
.PP
.nf
% cargo install cbindgen
% git clone https://github\&.com/rustls/rustls-ffi -b v0\&.7\&.0
% cd rustls-ffi
% make
% make DESTDIR=${HOME}/rustls-ffi-built/ install

.fi
.PP
 Now configure and build curl with rustls: 
.PP
.nf
% git clone https://github\&.com/curl/curl
% cd curl
% \&./buildconf
% \&./configure --with-rustls=${HOME}/rustls-ffi-built
% make

.fi
.PP
 
