.TH "md__ase_sprite_aseprite_src_undo__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_src_undo__r_e_a_d_m_e \- Undo Library 
.PP
\fICopyright (C) 2015-2018 David Capello\fP
.PP
\fC\fP \fC\fP
.PP
\fBA\fP simple library to handle non-linear undo/redo history\&. 
