.TH "md__ase_sprite_aseprite_third_party_curl_docs__h_s_t_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_curl_docs__h_s_t_s \- HSTS support 
.PP
\fBHTTP\fP Strict-Transport-Security\&. Added as experimental in curl 7\&.74\&.0\&. Supported 'for real' since 7\&.77\&.0\&.
.SH "Standard"
.PP
\fCHTTP Strict Transport Security\fP
.SH "Behavior"
.PP
libcurl features an in-memory cache for HSTS hosts, so that subsequent HTTP-only requests to a host name present in the cache will get internally 'redirected' to the HTTPS version\&.
.SH "<tt>curl_easy_setopt()</tt> options:"
.PP
.IP "\(bu" 2
\fCCURLOPT_HSTS_CTRL\fP - enable HSTS for this easy handle
.IP "\(bu" 2
\fCCURLOPT_HSTS\fP - specify file name where to store the HSTS cache on close (and possibly read from at startup)
.PP
.SH "curl cmdline options"
.PP
.IP "\(bu" 2
\fC--hsts [filename]\fP - enable HSTS, use the file as HSTS cache\&. If filename is \fC''\fP (no length) then no file will be used, only in-memory cache\&.
.PP
.SH "HSTS cache file format"
.PP
Lines starting with \fC#\fP are ignored\&.
.PP
For each hsts entry: 
.PP
.nf
[host name] 'YYYYMMDD HH:MM:SS'

.fi
.PP
 The \fC[host name]\fP is dot-prefixed if it is a includeSubDomain\&.
.PP
The time stamp is when the entry expires\&.
.PP
I considered using wget's file format for the HSTS cache\&. However, they store the time stamp as the epoch (number of seconds since 1970) and I strongly disagree with using that format\&. Instead I opted to use a format similar to the curl alt-svc cache file format\&.
.SH "Possible future additions"
.PP
.IP "\(bu" 2
\fCCURLOPT_HSTS_PRELOAD\fP - provide a set of preloaded HSTS host names
.IP "\(bu" 2
ability to save to something else than a file 
.PP

