.TH "md__ase_sprite_aseprite_third_party_cmark_bench_samples_inline_autolink" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_third_party_cmark_bench_samples_inline_autolink \- inline-autolink 
.PP
closed (valid) autolinks:
.PP
ftp://1.2.3.4:21/path/foo http://foo.bar.baz?q=hello&id=22&boolean http://veeeeeeeeeeeeeeeeeeery.loooooooooooooooooooooooooooooooong.autolink/ teeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeest@gmail.com
.PP
these are not autolinks:
.PP
<ftp://1.2.3.4:21/path/foo <http://foo.bar.baz?q=hello&id=22&boolean <http://veeeeeeeeeeeeeeeeeeery.loooooooooooooooooooooooooooooooong.autolink <teeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeest@gmail.com < http://foo.bar.baz?q=hello&id=22&boolean > 
