.TH "md__ase_sprite_aseprite_laf_third_party_googletest__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__ase_sprite_aseprite_laf_third_party_googletest__r_e_a_d_m_e \- GoogleTest 
.PP

.SS "Announcements"
.SS "Live at Head"
GoogleTest now follows the \fCAbseil Live at Head philosophy\fP\&. We recommend \fCupdating to the latest commit in the \fCmain\fP branch as often as possible\fP\&.
.SS "Documentation Updates"
Our documentation is now live on GitHub Pages at https://google.github.io/googletest/\&. We recommend browsing the documentation on GitHub Pages rather than directly in the repository\&.
.SS "Release 1\&.12\&.1"
\fCRelease 1\&.12\&.1\fP is now available\&.
.PP
The 1\&.12\&.x branch will be the last to support C++11\&. Future releases will require at least C++14\&.
.SS "Coming Soon"
.IP "\(bu" 2
We are planning to take a dependency on \fCAbseil\fP\&.
.IP "\(bu" 2
More documentation improvements are planned\&.
.PP
.SH "Welcome to <strong>GoogleTest</strong>, Google's C++ test framework!"
.PP
This repository is a merger of the formerly separate GoogleTest and GoogleMock projects\&. These were so closely related that it makes sense to maintain and release them together\&.
.SS "Getting Started"
See the \fCGoogleTest User's Guide\fP for documentation\&. We recommend starting with the \fCGoogleTest Primer\fP\&.
.PP
More information about building GoogleTest can be found at \fBgoogletest/README\&.md\fP\&.
.SH "Features"
.PP
.IP "\(bu" 2
An \fCxUnit\fP test framework\&.
.IP "\(bu" 2
\fBTest\fP discovery\&.
.IP "\(bu" 2
\fBA\fP rich set of assertions\&.
.IP "\(bu" 2
User-defined assertions\&.
.IP "\(bu" 2
Death tests\&.
.IP "\(bu" 2
Fatal and non-fatal failures\&.
.IP "\(bu" 2
Value-parameterized tests\&.
.IP "\(bu" 2
Type-parameterized tests\&.
.IP "\(bu" 2
Various options for running the tests\&.
.IP "\(bu" 2
XML test report generation\&.
.PP
.SH "Supported Platforms"
.PP
GoogleTest follows Google's \fCFoundational C++ Support Policy\fP\&. See \fCthis table\fP for a list of currently supported versions compilers, platforms, and build tools\&.
.SH "Who Is Using GoogleTest?"
.PP
In addition to many internal projects at Google, GoogleTest is also used by the following notable projects:
.PP
.IP "\(bu" 2
The \fCChromium projects\fP (behind the Chrome browser and Chrome OS)\&.
.IP "\(bu" 2
The \fCLLVM\fP compiler\&.
.IP "\(bu" 2
\fCProtocol Buffers\fP, Google's data interchange format\&.
.IP "\(bu" 2
The \fCOpenCV\fP computer vision library\&.
.PP
.SH "Related Open Source Projects"
.PP
\fCGTest Runner\fP is a Qt5 based automated test-runner and Graphical User \fBInterface\fP with powerful features for Windows and Linux platforms\&.
.PP
\fCGoogleTest UI\fP is a test runner that runs your test binary, allows you to track its progress via a progress bar, and displays a list of test failures\&. Clicking on one shows failure text\&. GoogleTest UI is written in C#\&.
.PP
\fCGTest TAP Listener\fP is an event listener for GoogleTest that implements the \fCTAP protocol\fP for test result output\&. If your test runner understands TAP, you may find it useful\&.
.PP
\fCgtest-parallel\fP is a test runner that runs tests from your binary in parallel to provide significant speed-up\&.
.PP
\fCGoogleTest Adapter\fP is a VS Code extension allowing to view GoogleTest in a tree view and run/debug your tests\&.
.PP
\fCC++ TestMate\fP is a VS Code extension allowing to view GoogleTest in a tree view and run/debug your tests\&.
.PP
\fCCornichon\fP is a small Gherkin DSL parser that generates stub code for GoogleTest\&.
.SH "Contributing Changes"
.PP
Please read \fC\fCCONTRIBUTING\&.md\fP\fP for details on how to contribute to this project\&.
.PP
Happy testing! 
