.TH "MemBuffer" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemBuffer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBstart_\fP"
.br
.ti -1c
.RI "size_t \fBend_\fP"
.br
.ti -1c
.RI "const uint8_t * \fBbuf_\fP"
.br
.ti -1c
.RI "MemBufferMode \fBmode_\fP"
.br
.ti -1c
.RI "size_t \fBbuf_size_\fP"
.br
.ti -1c
.RI "uint8_t * \fBbuf_\fP"
.br
.ti -1c
.RI "size_t \fBpart0_size_\fP"
.br
.ti -1c
.RI "const uint8_t * \fBpart0_buf_\fP"
.br
.ti -1c
.RI "size_t \fBriff_end_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
