.TH "memory_bit_reader" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
memory_bit_reader
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const uint8_t * \fBbytes\fP"
.br
.ti -1c
.RI "size_t \fBlength\fP"
.br
.ti -1c
.RI "size_t \fBoffset\fP"
.br
.ti -1c
.RI "uint64_t \fBbits\fP"
.br
.ti -1c
.RI "int \fBavailable\fP"
.br
.ti -1c
.RI "int \fBat_eof\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
