.TH "mime_encoder_state" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mime_encoder_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBpos\fP"
.br
.ti -1c
.RI "size_t \fBbufbeg\fP"
.br
.ti -1c
.RI "size_t \fBbufend\fP"
.br
.ti -1c
.RI "char \fBbuf\fP [ENCODING_BUFFER_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
