.TH "mime_state" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mime_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum mimestate \fBstate\fP"
.br
.ti -1c
.RI "void * \fBptr\fP"
.br
.ti -1c
.RI "curl_off_t \fBoffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
