.TH "mime_encoder" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mime_encoder
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "size_t(* \fBencodefunc\fP )(char *\fBbuffer\fP, size_t size, bool ateof, \fBcurl_mimepart\fP *\fBpart\fP)"
.br
.ti -1c
.RI "curl_off_t(* \fBsizefunc\fP )(\fBcurl_mimepart\fP *\fBpart\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
