.TH "MockFoo" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MockFoo
.SH SYNOPSIS
.br
.PP
.PP
Inherits FooInterface\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMOCK_METHOD3\fP (Bar, char(const std::string &s, int i, double x))"
.br
.ti -1c
.RI "\fBMOCK_METHOD2\fP (Bar2, bool(int x, int y))"
.br
.ti -1c
.RI "\fBMOCK_METHOD2\fP (Bar3, void(int x, int y))"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
