.TH "mock_allocator< T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mock_allocator< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBvalue_type\fP = T"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmock_allocator\fP (const \fBmock_allocator\fP &)"
.br
.ti -1c
.RI "\fBMOCK_METHOD1_T\fP (allocate, T *(size_t n))"
.br
.ti -1c
.RI "\fBMOCK_METHOD2_T\fP (deallocate, void(T *p, size_t n))"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
