.TH "mock_visitor< T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mock_visitor< T >
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBresult\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMOCK_METHOD1_T\fP (visit, \fBtest_result\fP(T \fBvalue\fP))"
.br
.ti -1c
.RI "\fBMOCK_METHOD0_T\fP (unexpected, void())"
.br
.ti -1c
.RI "\fBtest_result\fP \fBoperator()\fP (T \fBvalue\fP)"
.br
.ti -1c
.RI "template<typename U > \fBtest_result\fP \fBoperator()\fP (U)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
