.TH "mtree_writer" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtree_writer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBmtree_entry\fP * \fBmtree_entry\fP"
.br
.ti -1c
.RI "struct \fBmtree_entry\fP * \fBroot\fP"
.br
.ti -1c
.RI "struct \fBmtree_entry\fP * \fBcur_dirent\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBcur_dirstr\fP"
.br
.ti -1c
.RI "struct \fBmtree_chain\fP \fBfile_list\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBebuf\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBbuf\fP"
.br
.ti -1c
.RI "int \fBfirst\fP"
.br
.ti -1c
.RI "uint64_t \fBentry_bytes_remaining\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBprocessing\fP"
.br
.ti -1c
.RI "   mode_t \fBtype\fP"
.br
.ti -1c
.RI "   int \fBkeys\fP"
.br
.ti -1c
.RI "   int64_t \fBuid\fP"
.br
.ti -1c
.RI "   int64_t \fBgid\fP"
.br
.ti -1c
.RI "   mode_t \fBmode\fP"
.br
.ti -1c
.RI "   unsigned long \fBfflags_set\fP"
.br
.ti -1c
.RI "   unsigned long \fBfflags_clear\fP"
.br
.ti -1c
.RI "} \fBset\fP"
.br
.ti -1c
.RI "struct \fBatt_counter_set\fP \fBacs\fP"
.br
.ti -1c
.RI "int \fBclassic\fP"
.br
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "int \fBcompute_sum\fP"
.br
.ti -1c
.RI "uint32_t \fBcrc\fP"
.br
.ti -1c
.RI "uint64_t \fBcrc_len\fP"
.br
.ti -1c
.RI "int \fBdironly\fP"
.br
.ti -1c
.RI "int \fBindent\fP"
.br
.ti -1c
.RI "int \fBoutput_global_set\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
