.TH "mtree_entry" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtree_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive_rb_node\fP \fBrbnode\fP"
.br
.ti -1c
.RI "struct \fBmtree_entry\fP * \fBnext_dup\fP"
.br
.ti -1c
.RI "struct \fBmtree_entry\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBmtree_option\fP * \fBoptions\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char \fBfull\fP"
.br
.ti -1c
.RI "char \fBused\fP"
.br
.ti -1c
.RI "struct \fBmtree_entry\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct \fBdir_info\fP * \fBdir_info\fP"
.br
.ti -1c
.RI "struct \fBreg_info\fP * \fBreg_info\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBparentdir\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBbasename\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBpathname\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBsymlink\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBuname\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBgname\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBfflags_text\fP"
.br
.ti -1c
.RI "unsigned int \fBnlink\fP"
.br
.ti -1c
.RI "mode_t \fBfiletype\fP"
.br
.ti -1c
.RI "mode_t \fBmode\fP"
.br
.ti -1c
.RI "int64_t \fBsize\fP"
.br
.ti -1c
.RI "int64_t \fBuid\fP"
.br
.ti -1c
.RI "int64_t \fBgid\fP"
.br
.ti -1c
.RI "time_t \fBmtime\fP"
.br
.ti -1c
.RI "long \fBmtime_nsec\fP"
.br
.ti -1c
.RI "unsigned long \fBfflags_set\fP"
.br
.ti -1c
.RI "unsigned long \fBfflags_clear\fP"
.br
.ti -1c
.RI "dev_t \fBrdevmajor\fP"
.br
.ti -1c
.RI "dev_t \fBrdevminor\fP"
.br
.ti -1c
.RI "dev_t \fBdevmajor\fP"
.br
.ti -1c
.RI "dev_t \fBdevminor\fP"
.br
.ti -1c
.RI "int64_t \fBino\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
