.TH "mtree" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mtree
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive_string\fP \fBline\fP"
.br
.ti -1c
.RI "size_t \fBbuffsize\fP"
.br
.ti -1c
.RI "char * \fBbuff\fP"
.br
.ti -1c
.RI "int64_t \fBoffset\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "int \fBarchive_format\fP"
.br
.ti -1c
.RI "const char * \fBarchive_format_name\fP"
.br
.ti -1c
.RI "struct \fBmtree_entry\fP * \fBentries\fP"
.br
.ti -1c
.RI "struct \fBmtree_entry\fP * \fBthis_entry\fP"
.br
.ti -1c
.RI "struct \fBarchive_rb_tree\fP \fBentry_rbtree\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBcurrent_dir\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBcontents_name\fP"
.br
.ti -1c
.RI "struct \fBarchive_entry_linkresolver\fP * \fBresolver\fP"
.br
.ti -1c
.RI "struct \fBarchive_rb_tree\fP \fBrbtree\fP"
.br
.ti -1c
.RI "int64_t \fBcur_size\fP"
.br
.ti -1c
.RI "char \fBcheckfs\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
