.TH "multiplier_table" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiplier_table
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ISLOW_MULT_TYPE \fBislow_array\fP [DCTSIZE2]"
.br
.ti -1c
.RI "IFAST_MULT_TYPE \fBifast_array\fP [DCTSIZE2]"
.br
.ti -1c
.RI "FLOAT_MULT_TYPE \fBfloat_array\fP [DCTSIZE2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
