.TH "my_cquantizer" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_cquantizer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjpeg_color_quantizer\fP \fBpub\fP"
.br
.ti -1c
.RI "JSAMPARRAY \fBsv_colormap\fP"
.br
.ti -1c
.RI "int \fBsv_actual\fP"
.br
.ti -1c
.RI "JSAMPARRAY \fBcolorindex\fP"
.br
.ti -1c
.RI "boolean \fBis_padded\fP"
.br
.ti -1c
.RI "int \fBNcolors\fP [MAX_Q_COMPS]"
.br
.ti -1c
.RI "int \fBrow_index\fP"
.br
.ti -1c
.RI "ODITHER_MATRIX_PTR \fBodither\fP [MAX_Q_COMPS]"
.br
.ti -1c
.RI "FSERRPTR \fBfserrors\fP [MAX_Q_COMPS]"
.br
.ti -1c
.RI "boolean \fBon_odd_row\fP"
.br
.ti -1c
.RI "int \fBdesired\fP"
.br
.ti -1c
.RI "hist3d \fBhistogram\fP"
.br
.ti -1c
.RI "boolean \fBneeds_zeroed\fP"
.br
.ti -1c
.RI "int * \fBerror_limiter\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
