.TH "my_color_deconverter" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_color_deconverter
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjpeg_color_deconverter\fP \fBpub\fP"
.br
.ti -1c
.RI "int * \fBCr_r_tab\fP"
.br
.ti -1c
.RI "int * \fBCb_b_tab\fP"
.br
.ti -1c
.RI "INT32 * \fBCr_g_tab\fP"
.br
.ti -1c
.RI "INT32 * \fBCb_g_tab\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
