.TH "my_coef_controller" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_coef_controller
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjpeg_c_coef_controller\fP \fBpub\fP"
.br
.ti -1c
.RI "JDIMENSION \fBiMCU_row_num\fP"
.br
.ti -1c
.RI "JDIMENSION \fBmcu_ctr\fP"
.br
.ti -1c
.RI "int \fBMCU_vert_offset\fP"
.br
.ti -1c
.RI "int \fBMCU_rows_per_iMCU_row\fP"
.br
.ti -1c
.RI "JBLOCKROW \fBMCU_buffer\fP [C_MAX_BLOCKS_IN_MCU]"
.br
.ti -1c
.RI "\fBjvirt_barray_ptr\fP \fBwhole_image\fP [MAX_COMPONENTS]"
.br
.ti -1c
.RI "\fBjvirt_barray_ptr\fP * \fBwhole_image\fP"
.br
.ti -1c
.RI "JBLOCKROW \fBdummy_buffer\fP [C_MAX_BLOCKS_IN_MCU]"
.br
.ti -1c
.RI "struct \fBjpeg_d_coef_controller\fP \fBpub\fP"
.br
.ti -1c
.RI "JDIMENSION \fBMCU_ctr\fP"
.br
.ti -1c
.RI "int * \fBcoef_bits_latch\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
