.TH "my_decomp_master" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_decomp_master
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjpeg_decomp_master\fP \fBpub\fP"
.br
.ti -1c
.RI "int \fBpass_number\fP"
.br
.ti -1c
.RI "boolean \fBusing_merged_upsample\fP"
.br
.ti -1c
.RI "struct \fBjpeg_color_quantizer\fP * \fBquantizer_1pass\fP"
.br
.ti -1c
.RI "struct \fBjpeg_color_quantizer\fP * \fBquantizer_2pass\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
