.TH "my_data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmagic\fP"
.br
.ti -1c
.RI "int \fBread_return\fP"
.br
.ti -1c
.RI "int \fBread_called\fP"
.br
.ti -1c
.RI "int \fBwrite_return\fP"
.br
.ti -1c
.RI "int \fBwrite_called\fP"
.br
.ti -1c
.RI "int \fBopen_return\fP"
.br
.ti -1c
.RI "int \fBopen_called\fP"
.br
.ti -1c
.RI "int \fBclose_return\fP"
.br
.ti -1c
.RI "int \fBclose_called\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
