.TH "my_fdct_controller" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_fdct_controller
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjpeg_forward_dct\fP \fBpub\fP"
.br
.ti -1c
.RI "forward_DCT_method_ptr \fBdo_dct\fP"
.br
.ti -1c
.RI "DCTELEM * \fBdivisors\fP [NUM_QUANT_TBLS]"
.br
.ti -1c
.RI "float_DCT_method_ptr \fBdo_float_dct\fP"
.br
.ti -1c
.RI "FAST_FLOAT * \fBfloat_divisors\fP [NUM_QUANT_TBLS]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
