.TH "my_main_controller" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_main_controller
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjpeg_c_main_controller\fP \fBpub\fP"
.br
.ti -1c
.RI "JDIMENSION \fBcur_iMCU_row\fP"
.br
.ti -1c
.RI "JDIMENSION \fBrowgroup_ctr\fP"
.br
.ti -1c
.RI "boolean \fBsuspended\fP"
.br
.ti -1c
.RI "J_BUF_MODE \fBpass_mode\fP"
.br
.ti -1c
.RI "JSAMPARRAY \fBbuffer\fP [MAX_COMPONENTS]"
.br
.ti -1c
.RI "struct \fBjpeg_d_main_controller\fP \fBpub\fP"
.br
.ti -1c
.RI "boolean \fBbuffer_full\fP"
.br
.ti -1c
.RI "JSAMPIMAGE \fBxbuffer\fP [2]"
.br
.ti -1c
.RI "int \fBwhichptr\fP"
.br
.ti -1c
.RI "int \fBcontext_state\fP"
.br
.ti -1c
.RI "JDIMENSION \fBrowgroups_avail\fP"
.br
.ti -1c
.RI "JDIMENSION \fBiMCU_row_ctr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
