.TH "my_marker_writer" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_marker_writer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjpeg_marker_writer\fP \fBpub\fP"
.br
.ti -1c
.RI "unsigned int \fBlast_restart_interval\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
