.TH "my_memory_mgr" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_memory_mgr
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjpeg_memory_mgr\fP \fBpub\fP"
.br
.ti -1c
.RI "\fBsmall_pool_ptr\fP \fBsmall_list\fP [JPOOL_NUMPOOLS]"
.br
.ti -1c
.RI "large_pool_ptr \fBlarge_list\fP [JPOOL_NUMPOOLS]"
.br
.ti -1c
.RI "\fBjvirt_sarray_ptr\fP \fBvirt_sarray_list\fP"
.br
.ti -1c
.RI "\fBjvirt_barray_ptr\fP \fBvirt_barray_list\fP"
.br
.ti -1c
.RI "long \fBtotal_space_allocated\fP"
.br
.ti -1c
.RI "JDIMENSION \fBlast_rowsperchunk\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
