.TH "my_marker_reader" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_marker_reader
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjpeg_marker_reader\fP \fBpub\fP"
.br
.ti -1c
.RI "jpeg_marker_parser_method \fBprocess_COM\fP"
.br
.ti -1c
.RI "jpeg_marker_parser_method \fBprocess_APPn\fP [16]"
.br
.ti -1c
.RI "unsigned int \fBlength_limit_COM\fP"
.br
.ti -1c
.RI "unsigned int \fBlength_limit_APPn\fP [16]"
.br
.ti -1c
.RI "jpeg_saved_marker_ptr \fBcur_marker\fP"
.br
.ti -1c
.RI "unsigned int \fBbytes_read\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
