.TH "my_post_controller" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_post_controller
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjpeg_d_post_controller\fP \fBpub\fP"
.br
.ti -1c
.RI "\fBjvirt_sarray_ptr\fP \fBwhole_image\fP"
.br
.ti -1c
.RI "JSAMPARRAY \fBbuffer\fP"
.br
.ti -1c
.RI "JDIMENSION \fBstrip_height\fP"
.br
.ti -1c
.RI "JDIMENSION \fBstarting_row\fP"
.br
.ti -1c
.RI "JDIMENSION \fBnext_row\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
