.TH "my_upsampler" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
my_upsampler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJMETHOD\fP (void, upmethod,(\fBj_decompress_ptr\fP cinfo, JSAMPIMAGE input_buf, JDIMENSION in_row_group_ctr, JSAMPARRAY output_buf))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjpeg_upsampler\fP \fBpub\fP"
.br
.ti -1c
.RI "int * \fBCr_r_tab\fP"
.br
.ti -1c
.RI "int * \fBCb_b_tab\fP"
.br
.ti -1c
.RI "INT32 * \fBCr_g_tab\fP"
.br
.ti -1c
.RI "INT32 * \fBCb_g_tab\fP"
.br
.ti -1c
.RI "JSAMPROW \fBspare_row\fP"
.br
.ti -1c
.RI "boolean \fBspare_full\fP"
.br
.ti -1c
.RI "JDIMENSION \fBout_row_width\fP"
.br
.ti -1c
.RI "JDIMENSION \fBrows_to_go\fP"
.br
.ti -1c
.RI "JSAMPARRAY \fBcolor_buf\fP [MAX_COMPONENTS]"
.br
.ti -1c
.RI "upsample1_ptr \fBmethods\fP [MAX_COMPONENTS]"
.br
.ti -1c
.RI "int \fBnext_row_out\fP"
.br
.ti -1c
.RI "int \fBrowgroup_height\fP [MAX_COMPONENTS]"
.br
.ti -1c
.RI "UINT8 \fBh_expand\fP [MAX_COMPONENTS]"
.br
.ti -1c
.RI "UINT8 \fBv_expand\fP [MAX_COMPONENTS]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
