.TH "MyDrawTextDelegate" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyDrawTextDelegate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBos::DrawTextDelegate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyDrawTextDelegate\fP (const \fBgfx::Point\fP &mousePos)"
.br
.ti -1c
.RI "void \fBpreProcessChar\fP (const int index, const int codepoint, gfx::Color &fg, gfx::Color &bg, const \fBgfx::Rect\fP &charBounds) override"
.br
.in -1c

Public Member Functions inherited from \fBos::DrawTextDelegate\fP
.in +1c
.ti -1c
.RI "virtual void \fBpreProcessChar\fP (const int index, const int codepoint, gfx::Color &fg, gfx::Color &bg, const \fBgfx::Rect\fP &charBounds)"
.br
.ti -1c
.RI "virtual bool \fBpreDrawChar\fP (const \fBgfx::Rect\fP &charBounds)"
.br
.ti -1c
.RI "virtual void \fBpostDrawChar\fP (const \fBgfx::Rect\fP &charBounds)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void MyDrawTextDelegate::preProcessChar (const int index, const int codepoint, gfx::Color & fg, gfx::Color & bg, const \fBgfx::Rect\fP & charBounds)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBos::DrawTextDelegate\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
