.TH "MyString" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyString
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyString\fP (const char *a_c_string)"
.br
.ti -1c
.RI "\fBMyString\fP (const \fBMyString\fP &string)"
.br
.ti -1c
.RI "const char * \fBc_string\fP () const"
.br
.ti -1c
.RI "size_t \fBLength\fP () const"
.br
.ti -1c
.RI "void \fBSet\fP (const char *c_string)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const char * \fBCloneCString\fP (const char *a_c_string)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
