.TH "name_cache" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
name_cache
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBprobes\fP"
.br
.ti -1c
.RI "int \fBhits\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   id_t \fBid\fP"
.br
.ti -1c
.RI "   char * \fBname\fP"
.br
.ti -1c
.RI "} \fBcache\fP [name_cache_size]"
.br
.ti -1c
.RI "struct \fBarchive\fP * \fBarchive\fP"
.br
.ti -1c
.RI "char * \fBbuff\fP"
.br
.ti -1c
.RI "size_t \fBbuff_size\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   id_t \fBid\fP"
.br
.ti -1c
.RI "   const char * \fBname\fP"
.br
.ti -1c
.RI "} \fBcache\fP [name_cache_size]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
