.TH "Names" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Names
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBHCACHE_NONE\fP, \fBHCACHE_MULTI\fP, \fBHCACHE_SHARED\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBCurl_hash\fP * \fBhostcache\fP"
.br
.ti -1c
.RI "enum Names:: { \&.\&.\&. }  \fBhostcachetype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
