.TH "NewColorMapType" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewColorMapType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GifByteType \fBRGBMin\fP [3]"
.br
.ti -1c
.RI "GifByteType \fBRGBWidth\fP [3]"
.br
.ti -1c
.RI "unsigned int \fBNumEntries\fP"
.br
.ti -1c
.RI "unsigned long \fBCount\fP"
.br
.ti -1c
.RI "\fBQuantizedColorType\fP * \fBQuantizedColors\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
