.TH "Node" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNodeKey\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int8_t \fBprev\fP"
.br
.ti -1c
.RI "int8_t \fBsign\fP"
.br
.ti -1c
.RI "int16_t \fBlevel\fP"
.br
.ti -1c
.RI "struct \fBNode::NodeKey\fP \fBu\fP"
.br
.ti -1c
.RI "\fBTValue\fP \fBi_val\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
