.TH "noncopyable_range< T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
noncopyable_range< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBconst_iterator\fP = typename ::std::vector< T >::const_iterator"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBnoncopyable_range\fP (Args &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBnoncopyable_range\fP (\fBnoncopyable_range\fP const &)=delete"
.br
.ti -1c
.RI "\fBnoncopyable_range\fP (\fBnoncopyable_range\fP &)=delete"
.br
.ti -1c
.RI "const_iterator \fBbegin\fP () const"
.br
.ti -1c
.RI "const_iterator \fBend\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
