.TH "NSMenuItemOSX" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSMenuItemOSX
.SH SYNOPSIS
.br
.PP
.PP
Inherits NSMenuItem\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(void) \- \fBdealloc\fP"
.br
.ti -1c
.RI "(void) \- \fBexecuteMenuItem:\fP"
.br
.ti -1c
.RI "(void) \- \fBvalidateLafMenuItem\fP"
.br
.in -1c
.SS "Class Methods"

.in +1c
.ti -1c
.RI "(\fBNSMenuItemOSX\fP *) + \fBalloc:\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBos::Ref\fP< \fBos::MenuItemOSX\fP > \fBoriginal\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
