.TH "O" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
O
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBobs::observable< Observer >\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBobs::observable< Observer >\fP
.in +1c
.ti -1c
.RI "void \fBadd_observer\fP (\fBObserver\fP *observer)"
.br
.ti -1c
.RI "void \fBremove_observer\fP (\fBObserver\fP *observer)"
.br
.ti -1c
.RI "void \fBnotify_observers\fP (void(Observer::*method)())"
.br
.ti -1c
.RI "template<typename \&.\&.\&. Args> void \fBnotify_observers\fP (void(Observer::*method)(Args\&.\&.\&.), Args \&.\&.\&.args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
