.TH "object_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
object_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "create_func_t \fBcreate\fP"
.br
.ti -1c
.RI "create_func_t \fBcreate_from_inert\fP"
.br
.ti -1c
.RI "create_func_t \fBget_empty\fP"
.br
.ti -1c
.RI "reference_func_t \fBreference\fP"
.br
.ti -1c
.RI "destroy_func_t \fBdestroy\fP"
.br
.ti -1c
.RI "set_user_data_func_t \fBset_user_data\fP"
.br
.ti -1c
.RI "get_user_data_func_t \fBget_user_data\fP"
.br
.ti -1c
.RI "make_immutable_func_t \fBmake_immutable\fP"
.br
.ti -1c
.RI "is_immutable_func_t \fBis_immutable\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
