.TH "ObserverA" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObserverA
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObserver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBon_event_a\fP () override"
.br
.in -1c

Public Member Functions inherited from \fBObserver\fP
.in +1c
.ti -1c
.RI "virtual void \fBon_event_a\fP ()"
.br
.ti -1c
.RI "virtual void \fBon_event_b\fP (int \fBa\fP)"
.br
.ti -1c
.RI "virtual void \fBon_event_c\fP (int \fBa\fP, int b)"
.br
.ti -1c
.RI "virtual void \fBon_event\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBa\fP = false"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ObserverA::on_event_a ()\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBObserver\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
