.TH "OpenSaveHelper" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenSaveHelper
.SH SYNOPSIS
.br
.PP
.PP
Inherits NSObject\&.
.SS "Instance Methods"

.in +1c
.ti -1c
.RI "(id) \- \fBinit\fP"
.br
.ti -1c
.RI "(void) \- \fBsetPanel:\fP"
.br
.ti -1c
.RI "(void) \- \fBsetWindow:\fP"
.br
.ti -1c
.RI "(void) \- \fBrunModal\fP"
.br
.ti -1c
.RI "(int) \- \fBresult\fP"
.br
.ti -1c
.RI "(void) \- \fBfileTypeChange\fP"
.br
.ti -1c
.RI "(void) \- \fBsetFileTypeChangeObserver:\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
