.TH "OperationConfig" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBremote_time\fP"
.br
.ti -1c
.RI "char * \fBrandom_file\fP"
.br
.ti -1c
.RI "char * \fBegd_file\fP"
.br
.ti -1c
.RI "char * \fBuseragent\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBcookies\fP"
.br
.ti -1c
.RI "char * \fBcookiejar\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBcookiefiles\fP"
.br
.ti -1c
.RI "char * \fBaltsvc\fP"
.br
.ti -1c
.RI "char * \fBhsts\fP"
.br
.ti -1c
.RI "bool \fBcookiesession\fP"
.br
.ti -1c
.RI "bool \fBencoding\fP"
.br
.ti -1c
.RI "bool \fBtr_encoding\fP"
.br
.ti -1c
.RI "unsigned long \fBauthtype\fP"
.br
.ti -1c
.RI "bool \fBuse_resume\fP"
.br
.ti -1c
.RI "bool \fBresume_from_current\fP"
.br
.ti -1c
.RI "bool \fBdisable_epsv\fP"
.br
.ti -1c
.RI "bool \fBdisable_eprt\fP"
.br
.ti -1c
.RI "bool \fBftp_pret\fP"
.br
.ti -1c
.RI "long \fBproto\fP"
.br
.ti -1c
.RI "bool \fBproto_present\fP"
.br
.ti -1c
.RI "long \fBproto_redir\fP"
.br
.ti -1c
.RI "bool \fBproto_redir_present\fP"
.br
.ti -1c
.RI "char * \fBproto_default\fP"
.br
.ti -1c
.RI "curl_off_t \fBresume_from\fP"
.br
.ti -1c
.RI "char * \fBpostfields\fP"
.br
.ti -1c
.RI "curl_off_t \fBpostfieldsize\fP"
.br
.ti -1c
.RI "char * \fBreferer\fP"
.br
.ti -1c
.RI "double \fBtimeout\fP"
.br
.ti -1c
.RI "double \fBconnecttimeout\fP"
.br
.ti -1c
.RI "long \fBmaxredirs\fP"
.br
.ti -1c
.RI "curl_off_t \fBmax_filesize\fP"
.br
.ti -1c
.RI "char * \fBoutput_dir\fP"
.br
.ti -1c
.RI "char * \fBheaderfile\fP"
.br
.ti -1c
.RI "char * \fBftpport\fP"
.br
.ti -1c
.RI "char * \fBiface\fP"
.br
.ti -1c
.RI "long \fBlocalport\fP"
.br
.ti -1c
.RI "long \fBlocalportrange\fP"
.br
.ti -1c
.RI "unsigned short \fBporttouse\fP"
.br
.ti -1c
.RI "char * \fBrange\fP"
.br
.ti -1c
.RI "long \fBlow_speed_limit\fP"
.br
.ti -1c
.RI "long \fBlow_speed_time\fP"
.br
.ti -1c
.RI "char * \fBdns_servers\fP"
.br
.ti -1c
.RI "char * \fBdns_interface\fP"
.br
.ti -1c
.RI "char * \fBdns_ipv4_addr\fP"
.br
.ti -1c
.RI "char * \fBdns_ipv6_addr\fP"
.br
.ti -1c
.RI "char * \fBuserpwd\fP"
.br
.ti -1c
.RI "char * \fBlogin_options\fP"
.br
.ti -1c
.RI "char * \fBtls_username\fP"
.br
.ti -1c
.RI "char * \fBtls_password\fP"
.br
.ti -1c
.RI "char * \fBtls_authtype\fP"
.br
.ti -1c
.RI "char * \fBproxy_tls_username\fP"
.br
.ti -1c
.RI "char * \fBproxy_tls_password\fP"
.br
.ti -1c
.RI "char * \fBproxy_tls_authtype\fP"
.br
.ti -1c
.RI "char * \fBproxyuserpwd\fP"
.br
.ti -1c
.RI "char * \fBproxy\fP"
.br
.ti -1c
.RI "int \fBproxyver\fP"
.br
.ti -1c
.RI "char * \fBnoproxy\fP"
.br
.ti -1c
.RI "char * \fBmail_from\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBmail_rcpt\fP"
.br
.ti -1c
.RI "char * \fBmail_auth\fP"
.br
.ti -1c
.RI "bool \fBmail_rcpt_allowfails\fP"
.br
.ti -1c
.RI "char * \fBsasl_authzid\fP"
.br
.ti -1c
.RI "bool \fBsasl_ir\fP"
.br
.ti -1c
.RI "bool \fBproxytunnel\fP"
.br
.ti -1c
.RI "bool \fBftp_append\fP"
.br
.ti -1c
.RI "bool \fBuse_ascii\fP"
.br
.ti -1c
.RI "bool \fBautoreferer\fP"
.br
.ti -1c
.RI "bool \fBfailonerror\fP"
.br
.ti -1c
.RI "bool \fBfailwithbody\fP"
.br
.ti -1c
.RI "bool \fBshow_headers\fP"
.br
.ti -1c
.RI "bool \fBno_body\fP"
.br
.ti -1c
.RI "bool \fBdirlistonly\fP"
.br
.ti -1c
.RI "bool \fBfollowlocation\fP"
.br
.ti -1c
.RI "bool \fBunrestricted_auth\fP"
.br
.ti -1c
.RI "bool \fBnetrc_opt\fP"
.br
.ti -1c
.RI "bool \fBnetrc\fP"
.br
.ti -1c
.RI "char * \fBnetrc_file\fP"
.br
.ti -1c
.RI "struct \fBgetout\fP * \fBurl_list\fP"
.br
.ti -1c
.RI "struct \fBgetout\fP * \fBurl_last\fP"
.br
.ti -1c
.RI "struct \fBgetout\fP * \fBurl_get\fP"
.br
.ti -1c
.RI "struct \fBgetout\fP * \fBurl_out\fP"
.br
.ti -1c
.RI "struct \fBgetout\fP * \fBurl_ul\fP"
.br
.ti -1c
.RI "char * \fBdoh_url\fP"
.br
.ti -1c
.RI "char * \fBcipher_list\fP"
.br
.ti -1c
.RI "char * \fBproxy_cipher_list\fP"
.br
.ti -1c
.RI "char * \fBcipher13_list\fP"
.br
.ti -1c
.RI "char * \fBproxy_cipher13_list\fP"
.br
.ti -1c
.RI "char * \fBcert\fP"
.br
.ti -1c
.RI "char * \fBproxy_cert\fP"
.br
.ti -1c
.RI "char * \fBcert_type\fP"
.br
.ti -1c
.RI "char * \fBproxy_cert_type\fP"
.br
.ti -1c
.RI "char * \fBcacert\fP"
.br
.ti -1c
.RI "char * \fBproxy_cacert\fP"
.br
.ti -1c
.RI "char * \fBcapath\fP"
.br
.ti -1c
.RI "char * \fBproxy_capath\fP"
.br
.ti -1c
.RI "char * \fBcrlfile\fP"
.br
.ti -1c
.RI "char * \fBproxy_crlfile\fP"
.br
.ti -1c
.RI "char * \fBpinnedpubkey\fP"
.br
.ti -1c
.RI "char * \fBproxy_pinnedpubkey\fP"
.br
.ti -1c
.RI "char * \fBkey\fP"
.br
.ti -1c
.RI "char * \fBproxy_key\fP"
.br
.ti -1c
.RI "char * \fBkey_type\fP"
.br
.ti -1c
.RI "char * \fBproxy_key_type\fP"
.br
.ti -1c
.RI "char * \fBkey_passwd\fP"
.br
.ti -1c
.RI "char * \fBproxy_key_passwd\fP"
.br
.ti -1c
.RI "char * \fBpubkey\fP"
.br
.ti -1c
.RI "char * \fBhostpubmd5\fP"
.br
.ti -1c
.RI "char * \fBengine\fP"
.br
.ti -1c
.RI "char * \fBetag_save_file\fP"
.br
.ti -1c
.RI "char * \fBetag_compare_file\fP"
.br
.ti -1c
.RI "bool \fBcrlf\fP"
.br
.ti -1c
.RI "char * \fBcustomrequest\fP"
.br
.ti -1c
.RI "char * \fBssl_ec_curves\fP"
.br
.ti -1c
.RI "char * \fBkrblevel\fP"
.br
.ti -1c
.RI "char * \fBrequest_target\fP"
.br
.ti -1c
.RI "long \fBhttpversion\fP"
.br
.ti -1c
.RI "bool \fBhttp09_allowed\fP"
.br
.ti -1c
.RI "bool \fBnobuffer\fP"
.br
.ti -1c
.RI "bool \fBreadbusy\fP"
.br
.ti -1c
.RI "bool \fBgloboff\fP"
.br
.ti -1c
.RI "bool \fBuse_httpget\fP"
.br
.ti -1c
.RI "bool \fBinsecure_ok\fP"
.br
.ti -1c
.RI "bool \fBdoh_insecure_ok\fP"
.br
.ti -1c
.RI "bool \fBproxy_insecure_ok\fP"
.br
.ti -1c
.RI "bool \fBterminal_binary_ok\fP"
.br
.ti -1c
.RI "bool \fBverifystatus\fP"
.br
.ti -1c
.RI "bool \fBdoh_verifystatus\fP"
.br
.ti -1c
.RI "bool \fBcreate_dirs\fP"
.br
.ti -1c
.RI "bool \fBftp_create_dirs\fP"
.br
.ti -1c
.RI "bool \fBftp_skip_ip\fP"
.br
.ti -1c
.RI "bool \fBproxynegotiate\fP"
.br
.ti -1c
.RI "bool \fBproxyntlm\fP"
.br
.ti -1c
.RI "bool \fBproxydigest\fP"
.br
.ti -1c
.RI "bool \fBproxybasic\fP"
.br
.ti -1c
.RI "bool \fBproxyanyauth\fP"
.br
.ti -1c
.RI "char * \fBwriteout\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBquote\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBpostquote\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBprequote\fP"
.br
.ti -1c
.RI "long \fBssl_version\fP"
.br
.ti -1c
.RI "long \fBssl_version_max\fP"
.br
.ti -1c
.RI "long \fBproxy_ssl_version\fP"
.br
.ti -1c
.RI "long \fBip_version\fP"
.br
.ti -1c
.RI "long \fBcreate_file_mode\fP"
.br
.ti -1c
.RI "curl_TimeCond \fBtimecond\fP"
.br
.ti -1c
.RI "curl_off_t \fBcondtime\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBheaders\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBproxyheaders\fP"
.br
.ti -1c
.RI "struct \fBtool_mime\fP * \fBmimeroot\fP"
.br
.ti -1c
.RI "struct \fBtool_mime\fP * \fBmimecurrent\fP"
.br
.ti -1c
.RI "\fBcurl_mime\fP * \fBmimepost\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBtelnet_options\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBresolve\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBconnect_to\fP"
.br
.ti -1c
.RI "HttpReq \fBhttpreq\fP"
.br
.ti -1c
.RI "curl_off_t \fBsendpersecond\fP"
.br
.ti -1c
.RI "curl_off_t \fBrecvpersecond\fP"
.br
.ti -1c
.RI "bool \fBftp_ssl\fP"
.br
.ti -1c
.RI "bool \fBftp_ssl_reqd\fP"
.br
.ti -1c
.RI "bool \fBftp_ssl_control\fP"
.br
.ti -1c
.RI "bool \fBftp_ssl_ccc\fP"
.br
.ti -1c
.RI "int \fBftp_ssl_ccc_mode\fP"
.br
.ti -1c
.RI "char * \fBpreproxy\fP"
.br
.ti -1c
.RI "int \fBsocks5_gssapi_nec\fP"
.br
.ti -1c
.RI "unsigned long \fBsocks5_auth\fP"
.br
.ti -1c
.RI "char * \fBproxy_service_name\fP"
.br
.ti -1c
.RI "char * \fBservice_name\fP"
.br
.ti -1c
.RI "bool \fBtcp_nodelay\fP"
.br
.ti -1c
.RI "bool \fBtcp_fastopen\fP"
.br
.ti -1c
.RI "long \fBreq_retry\fP"
.br
.ti -1c
.RI "bool \fBretry_all_errors\fP"
.br
.ti -1c
.RI "bool \fBretry_connrefused\fP"
.br
.ti -1c
.RI "long \fBretry_delay\fP"
.br
.ti -1c
.RI "long \fBretry_maxtime\fP"
.br
.ti -1c
.RI "char * \fBftp_account\fP"
.br
.ti -1c
.RI "char * \fBftp_alternative_to_user\fP"
.br
.ti -1c
.RI "int \fBftp_filemethod\fP"
.br
.ti -1c
.RI "long \fBtftp_blksize\fP"
.br
.ti -1c
.RI "bool \fBtftp_no_options\fP"
.br
.ti -1c
.RI "bool \fBignorecl\fP"
.br
.ti -1c
.RI "bool \fBdisable_sessionid\fP"
.br
.ti -1c
.RI "bool \fBraw\fP"
.br
.ti -1c
.RI "bool \fBpost301\fP"
.br
.ti -1c
.RI "bool \fBpost302\fP"
.br
.ti -1c
.RI "bool \fBpost303\fP"
.br
.ti -1c
.RI "bool \fBnokeepalive\fP"
.br
.ti -1c
.RI "long \fBalivetime\fP"
.br
.ti -1c
.RI "bool \fBcontent_disposition\fP"
.br
.ti -1c
.RI "int \fBdefault_node_flags\fP"
.br
.ti -1c
.RI "bool \fBxattr\fP"
.br
.ti -1c
.RI "long \fBgssapi_delegation\fP"
.br
.ti -1c
.RI "bool \fBssl_allow_beast\fP"
.br
.ti -1c
.RI "bool \fBproxy_ssl_allow_beast\fP"
.br
.ti -1c
.RI "bool \fBssl_no_revoke\fP"
.br
.ti -1c
.RI "bool \fBssl_revoke_best_effort\fP"
.br
.ti -1c
.RI "bool \fBnative_ca_store\fP"
.br
.ti -1c
.RI "bool \fBssl_auto_client_cert\fP"
.br
.ti -1c
.RI "bool \fBproxy_ssl_auto_client_cert\fP"
.br
.ti -1c
.RI "char * \fBoauth_bearer\fP"
.br
.ti -1c
.RI "bool \fBnonpn\fP"
.br
.ti -1c
.RI "bool \fBnoalpn\fP"
.br
.ti -1c
.RI "char * \fBunix_socket_path\fP"
.br
.ti -1c
.RI "bool \fBabstract_unix_socket\fP"
.br
.ti -1c
.RI "bool \fBfalsestart\fP"
.br
.ti -1c
.RI "bool \fBpath_as_is\fP"
.br
.ti -1c
.RI "double \fBexpect100timeout\fP"
.br
.ti -1c
.RI "bool \fBsuppress_connect_headers\fP"
.br
.ti -1c
.RI "curl_error \fBsynthetic_error\fP"
.br
.ti -1c
.RI "bool \fBssh_compression\fP"
.br
.ti -1c
.RI "long \fBhappy_eyeballs_timeout_ms\fP"
.br
.ti -1c
.RI "bool \fBhaproxy_protocol\fP"
.br
.ti -1c
.RI "bool \fBdisallow_username_in_url\fP"
.br
.ti -1c
.RI "char * \fBaws_sigv4\fP"
.br
.ti -1c
.RI "struct \fBGlobalConfig\fP * \fBglobal\fP"
.br
.ti -1c
.RI "struct \fBOperationConfig\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBOperationConfig\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBState\fP \fBstate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
