.TH "output_buffer_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
output_buffer_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBoutput_options_t< default_stdout >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_options\fP (\fBoption_parser_t\fP *parser)"
.br
.ti -1c
.RI "void \fBinit\fP (\fBhb_buffer_t\fP *\fBbuffer\fP, const \fBfont_options_t\fP *font_opts)"
.br
.ti -1c
.RI "void \fBnew_line\fP ()"
.br
.ti -1c
.RI "void \fBconsume_text\fP (\fBhb_buffer_t\fP *\fBbuffer\fP, const char *text, unsigned int text_len, hb_bool_t utf8_clusters)"
.br
.ti -1c
.RI "void \fBerror\fP (const char *message)"
.br
.ti -1c
.RI "void \fBconsume_glyphs\fP (\fBhb_buffer_t\fP *\fBbuffer\fP, const char *text, unsigned int text_len, hb_bool_t utf8_clusters)"
.br
.ti -1c
.RI "void \fBfinish\fP (\fBhb_buffer_t\fP *\fBbuffer\fP, const \fBfont_options_t\fP *font_opts)"
.br
.ti -1c
.RI "void \fBtrace\fP (\fBhb_buffer_t\fP *\fBbuffer\fP, \fBhb_font_t\fP *font, const char *message)"
.br
.in -1c

Public Member Functions inherited from \fBoutput_options_t< default_stdout >\fP
.in +1c
.ti -1c
.RI "void \fBadd_options\fP (\fBoption_parser_t\fP *parser, const char **supported_formats=nullptr)"
.br
.ti -1c
.RI "void \fBpost_parse\fP (GError **error)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static hb_bool_t \fBmessage_func\fP (\fBhb_buffer_t\fP *\fBbuffer\fP, \fBhb_font_t\fP *font, const char *message, void *user_data)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBshape_format_options_t\fP \fBformat\fP"
.br
.ti -1c
.RI "GString * \fBgs\fP = nullptr"
.br
.ti -1c
.RI "unsigned int \fBline_no\fP = 0"
.br
.ti -1c
.RI "\fBhb_font_t\fP * \fBfont\fP = nullptr"
.br
.ti -1c
.RI "hb_buffer_serialize_format_t \fBserialize_format\fP = HB_BUFFER_SERIALIZE_FORMAT_INVALID"
.br
.ti -1c
.RI "hb_buffer_serialize_flags_t \fBserialize_flags\fP = HB_BUFFER_SERIALIZE_FLAG_DEFAULT"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBoutput_options_t< default_stdout >\fP
.in +1c
.ti -1c
.RI "char * \fBoutput_file\fP = nullptr"
.br
.ti -1c
.RI "char * \fBoutput_format\fP = nullptr"
.br
.ti -1c
.RI "bool \fBexplicit_output_format\fP = false"
.br
.ti -1c
.RI "FILE * \fBout_fp\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
