.TH "output_options_t< default_stdout >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
output_options_t< default_stdout >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBoutput_buffer_t\fP, and \fBview_cairo_t\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_options\fP (\fBoption_parser_t\fP *parser, const char **supported_formats=nullptr)"
.br
.ti -1c
.RI "void \fBpost_parse\fP (GError **error)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBoutput_file\fP = nullptr"
.br
.ti -1c
.RI "char * \fBoutput_format\fP = nullptr"
.br
.ti -1c
.RI "bool \fBexplicit_output_format\fP = false"
.br
.ti -1c
.RI "FILE * \fBout_fp\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
