.TH "PassStats" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PassStats
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBis_first\fP"
.br
.ti -1c
.RI "float \fBdq\fP"
.br
.ti -1c
.RI "float \fBq\fP"
.br
.ti -1c
.RI "float \fBlast_q\fP"
.br
.ti -1c
.RI "float \fBqmin\fP"
.br
.ti -1c
.RI "float \fBqmax\fP"
.br
.ti -1c
.RI "double \fBvalue\fP"
.br
.ti -1c
.RI "double \fBlast_value\fP"
.br
.ti -1c
.RI "double \fBtarget\fP"
.br
.ti -1c
.RI "int \fBdo_size_search\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
