.TH "pax" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pax
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBentry_bytes_remaining\fP"
.br
.ti -1c
.RI "uint64_t \fBentry_padding\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBl_url_encoded_name\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBpax_header\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBsparse_map\fP"
.br
.ti -1c
.RI "size_t \fBsparse_map_padding\fP"
.br
.ti -1c
.RI "struct \fBsparse_block\fP * \fBsparse_list\fP"
.br
.ti -1c
.RI "struct \fBsparse_block\fP * \fBsparse_tail\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_utf8\fP"
.br
.ti -1c
.RI "int \fBopt_binary\fP"
.br
.ti -1c
.RI "unsigned \fBflags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
