.TH "PCF_Compressed_MetricRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PCF_Compressed_MetricRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte \fBleftSideBearing\fP"
.br
.ti -1c
.RI "FT_Byte \fBrightSideBearing\fP"
.br
.ti -1c
.RI "FT_Byte \fBcharacterWidth\fP"
.br
.ti -1c
.RI "FT_Byte \fBascent\fP"
.br
.ti -1c
.RI "FT_Byte \fBdescent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
