.TH "per_transfer" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
per_transfer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBper_transfer\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBper_transfer\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBOperationConfig\fP * \fBconfig\fP"
.br
.ti -1c
.RI "CURL * \fBcurl\fP"
.br
.ti -1c
.RI "long \fBretry_numretries\fP"
.br
.ti -1c
.RI "long \fBretry_sleep_default\fP"
.br
.ti -1c
.RI "long \fBretry_sleep\fP"
.br
.ti -1c
.RI "struct \fBtimeval\fP \fBretrystart\fP"
.br
.ti -1c
.RI "char * \fBthis_url\fP"
.br
.ti -1c
.RI "unsigned int \fBurlnum\fP"
.br
.ti -1c
.RI "char * \fBoutfile\fP"
.br
.ti -1c
.RI "bool \fBinfdopen\fP"
.br
.ti -1c
.RI "int \fBinfd\fP"
.br
.ti -1c
.RI "bool \fBnoprogress\fP"
.br
.ti -1c
.RI "struct \fBProgressData\fP \fBprogressbar\fP"
.br
.ti -1c
.RI "struct \fBOutStruct\fP \fBouts\fP"
.br
.ti -1c
.RI "struct \fBOutStruct\fP \fBheads\fP"
.br
.ti -1c
.RI "struct \fBOutStruct\fP \fBetag_save\fP"
.br
.ti -1c
.RI "struct \fBInStruct\fP \fBinput\fP"
.br
.ti -1c
.RI "struct \fBHdrCbData\fP \fBhdrcbdata\fP"
.br
.ti -1c
.RI "long \fBnum_headers\fP"
.br
.ti -1c
.RI "bool \fBwas_last_header_empty\fP"
.br
.ti -1c
.RI "char \fBerrorbuffer\fP [CURL_ERROR_SIZE]"
.br
.ti -1c
.RI "bool \fBadded\fP"
.br
.ti -1c
.RI "time_t \fBstartat\fP"
.br
.ti -1c
.RI "bool \fBabort\fP"
.br
.ti -1c
.RI "curl_off_t \fBdltotal\fP"
.br
.ti -1c
.RI "curl_off_t \fBdlnow\fP"
.br
.ti -1c
.RI "curl_off_t \fBultotal\fP"
.br
.ti -1c
.RI "curl_off_t \fBulnow\fP"
.br
.ti -1c
.RI "bool \fBdltotal_added\fP"
.br
.ti -1c
.RI "bool \fBultotal_added\fP"
.br
.ti -1c
.RI "char * \fBseparator_err\fP"
.br
.ti -1c
.RI "char * \fBseparator\fP"
.br
.ti -1c
.RI "char * \fBuploadfile\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
