.TH "PFR_LogFontRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_LogFontRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt32 \fBsize\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBoffset\fP"
.br
.ti -1c
.RI "FT_Int32 \fBmatrix\fP [4]"
.br
.ti -1c
.RI "FT_UInt \fBstroke_flags\fP"
.br
.ti -1c
.RI "FT_Int \fBstroke_thickness\fP"
.br
.ti -1c
.RI "FT_Int \fBbold_thickness\fP"
.br
.ti -1c
.RI "FT_Int32 \fBmiter_limit\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBphys_size\fP"
.br
.ti -1c
.RI "FT_UInt32 \fBphys_offset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
