.TH "PFR_GlyphRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_GlyphRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Byte \fBformat\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_xy_control\fP"
.br
.ti -1c
.RI "FT_Pos * \fBx_control\fP"
.br
.ti -1c
.RI "FT_Pos * \fBy_control\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_subs\fP"
.br
.ti -1c
.RI "FT_UInt \fBmax_subs\fP"
.br
.ti -1c
.RI "\fBPFR_SubGlyphRec\fP * \fBsubs\fP"
.br
.ti -1c
.RI "\fBFT_GlyphLoader\fP \fBloader\fP"
.br
.ti -1c
.RI "FT_Bool \fBpath_begun\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
