.TH "PFR_DimensionRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PFR_DimensionRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBstandard\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_stem_snaps\fP"
.br
.ti -1c
.RI "FT_Int * \fBstem_snaps\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
