.TH "phuff_entropy_encoder" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phuff_entropy_encoder
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjpeg_entropy_encoder\fP \fBpub\fP"
.br
.ti -1c
.RI "boolean \fBgather_statistics\fP"
.br
.ti -1c
.RI "JOCTET * \fBnext_output_byte\fP"
.br
.ti -1c
.RI "size_t \fBfree_in_buffer\fP"
.br
.ti -1c
.RI "INT32 \fBput_buffer\fP"
.br
.ti -1c
.RI "int \fBput_bits\fP"
.br
.ti -1c
.RI "\fBj_compress_ptr\fP \fBcinfo\fP"
.br
.ti -1c
.RI "int \fBlast_dc_val\fP [MAX_COMPS_IN_SCAN]"
.br
.ti -1c
.RI "int \fBac_tbl_no\fP"
.br
.ti -1c
.RI "unsigned int \fBEOBRUN\fP"
.br
.ti -1c
.RI "unsigned int \fBBE\fP"
.br
.ti -1c
.RI "char * \fBbit_buffer\fP"
.br
.ti -1c
.RI "unsigned int \fBrestarts_to_go\fP"
.br
.ti -1c
.RI "int \fBnext_restart_num\fP"
.br
.ti -1c
.RI "\fBc_derived_tbl\fP * \fBderived_tbls\fP [NUM_HUFF_TBLS]"
.br
.ti -1c
.RI "long * \fBcount_ptrs\fP [NUM_HUFF_TBLS]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
