.TH "phuff_entropy_decoder" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
phuff_entropy_decoder
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBjpeg_entropy_decoder\fP \fBpub\fP"
.br
.ti -1c
.RI "\fBbitread_perm_state\fP \fBbitstate\fP"
.br
.ti -1c
.RI "\fBsavable_state\fP \fBsaved\fP"
.br
.ti -1c
.RI "unsigned int \fBrestarts_to_go\fP"
.br
.ti -1c
.RI "\fBd_derived_tbl\fP * \fBderived_tbls\fP [NUM_HUFF_TBLS]"
.br
.ti -1c
.RI "\fBd_derived_tbl\fP * \fBac_derived_tbl\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
