.TH "pingpong" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pingpong
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBcache\fP"
.br
.ti -1c
.RI "size_t \fBcache_size\fP"
.br
.ti -1c
.RI "size_t \fBnread_resp\fP"
.br
.ti -1c
.RI "char * \fBlinestart_resp\fP"
.br
.ti -1c
.RI "bool \fBpending_resp\fP"
.br
.ti -1c
.RI "char * \fBsendthis\fP"
.br
.ti -1c
.RI "size_t \fBsendleft\fP"
.br
.ti -1c
.RI "size_t \fBsendsize\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBresponse\fP"
.br
.ti -1c
.RI "timediff_t \fBresponse_time\fP"
.br
.ti -1c
.RI "struct \fBdynbuf\fP \fBsendbuf\fP"
.br
.ti -1c
.RI "CURLcode(* \fBstatemachine\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn)"
.br
.ti -1c
.RI "bool(* \fBendofresp\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, char *ptr, size_t len, int *\fBcode\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
