.TH "pixel_combination_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixel_combination_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pixman_op_t \fBop\fP"
.br
.ti -1c
.RI "pixman_format_code_t \fBsrc_format\fP"
.br
.ti -1c
.RI "uint32_t \fBsrc_pixel\fP"
.br
.ti -1c
.RI "pixman_format_code_t \fBmask_format\fP"
.br
.ti -1c
.RI "uint32_t \fBmask_pixel\fP"
.br
.ti -1c
.RI "pixman_format_code_t \fBdest_format\fP"
.br
.ti -1c
.RI "uint32_t \fBdest_pixel\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
