.TH "pixel_checker_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixel_checker_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pixman_format_code_t \fBformat\fP"
.br
.ti -1c
.RI "uint32_t \fBam\fP"
.br
.ti -1c
.RI "uint32_t \fBrm\fP"
.br
.ti -1c
.RI "uint32_t \fBgm\fP"
.br
.ti -1c
.RI "uint32_t \fBbm\fP"
.br
.ti -1c
.RI "uint32_t \fBas\fP"
.br
.ti -1c
.RI "uint32_t \fBrs\fP"
.br
.ti -1c
.RI "uint32_t \fBgs\fP"
.br
.ti -1c
.RI "uint32_t \fBbs\fP"
.br
.ti -1c
.RI "uint32_t \fBaw\fP"
.br
.ti -1c
.RI "uint32_t \fBrw\fP"
.br
.ti -1c
.RI "uint32_t \fBgw\fP"
.br
.ti -1c
.RI "uint32_t \fBbw\fP"
.br
.ti -1c
.RI "float \fBad\fP"
.br
.ti -1c
.RI "float \fBrd\fP"
.br
.ti -1c
.RI "float \fBgd\fP"
.br
.ti -1c
.RI "float \fBbd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
