.TH "pixman_iter_info_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixman_iter_info_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pixman_format_code_t \fBformat\fP"
.br
.ti -1c
.RI "uint32_t \fBimage_flags\fP"
.br
.ti -1c
.RI "iter_flags_t \fBiter_flags\fP"
.br
.ti -1c
.RI "pixman_iter_initializer_t \fBinitializer\fP"
.br
.ti -1c
.RI "pixman_iter_get_scanline_t \fBget_scanline\fP"
.br
.ti -1c
.RI "pixman_iter_write_back_t \fBwrite_back\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
