.TH "pixman_glyph_cache_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixman_glyph_cache_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBn_glyphs\fP"
.br
.ti -1c
.RI "int \fBn_tombstones\fP"
.br
.ti -1c
.RI "int \fBfreeze_count\fP"
.br
.ti -1c
.RI "\fBpixman_list_t\fP \fBmru\fP"
.br
.ti -1c
.RI "\fBglyph_t\fP * \fBglyphs\fP [HASH_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
