.TH "pixman_indexed" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixman_indexed
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pixman_bool_t \fBcolor\fP"
.br
.ti -1c
.RI "uint32_t \fBrgba\fP [PIXMAN_MAX_INDEXED]"
.br
.ti -1c
.RI "pixman_index_type \fBent\fP [32768]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
