.TH "pixman_implementation_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixman_implementation_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpixman_implementation_t\fP * \fBtoplevel\fP"
.br
.ti -1c
.RI "\fBpixman_implementation_t\fP * \fBfallback\fP"
.br
.ti -1c
.RI "const \fBpixman_fast_path_t\fP * \fBfast_paths\fP"
.br
.ti -1c
.RI "const \fBpixman_iter_info_t\fP * \fBiter_info\fP"
.br
.ti -1c
.RI "pixman_blt_func_t \fBblt\fP"
.br
.ti -1c
.RI "pixman_fill_func_t \fBfill\fP"
.br
.ti -1c
.RI "pixman_combine_32_func_t \fBcombine_32\fP [PIXMAN_N_OPERATORS]"
.br
.ti -1c
.RI "pixman_combine_32_func_t \fBcombine_32_ca\fP [PIXMAN_N_OPERATORS]"
.br
.ti -1c
.RI "pixman_combine_float_func_t \fBcombine_float\fP [PIXMAN_N_OPERATORS]"
.br
.ti -1c
.RI "pixman_combine_float_func_t \fBcombine_float_ca\fP [PIXMAN_N_OPERATORS]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
