.TH "pixman_gradient_walker_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixman_gradient_walker_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBa_s\fP"
.br
.ti -1c
.RI "float \fBa_b\fP"
.br
.ti -1c
.RI "float \fBr_s\fP"
.br
.ti -1c
.RI "float \fBr_b\fP"
.br
.ti -1c
.RI "float \fBg_s\fP"
.br
.ti -1c
.RI "float \fBg_b\fP"
.br
.ti -1c
.RI "float \fBb_s\fP"
.br
.ti -1c
.RI "float \fBb_b\fP"
.br
.ti -1c
.RI "pixman_fixed_48_16_t \fBleft_x\fP"
.br
.ti -1c
.RI "pixman_fixed_48_16_t \fBright_x\fP"
.br
.ti -1c
.RI "\fBpixman_gradient_stop_t\fP * \fBstops\fP"
.br
.ti -1c
.RI "int \fBnum_stops\fP"
.br
.ti -1c
.RI "pixman_repeat_t \fBrepeat\fP"
.br
.ti -1c
.RI "pixman_bool_t \fBneed_reset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
