.TH "pixman_edge" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixman_edge
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pixman_fixed_t \fBx\fP"
.br
.ti -1c
.RI "pixman_fixed_t \fBe\fP"
.br
.ti -1c
.RI "pixman_fixed_t \fBstepx\fP"
.br
.ti -1c
.RI "pixman_fixed_t \fBsigndx\fP"
.br
.ti -1c
.RI "pixman_fixed_t \fBdy\fP"
.br
.ti -1c
.RI "pixman_fixed_t \fBdx\fP"
.br
.ti -1c
.RI "pixman_fixed_t \fBstepx_small\fP"
.br
.ti -1c
.RI "pixman_fixed_t \fBstepx_big\fP"
.br
.ti -1c
.RI "pixman_fixed_t \fBdx_small\fP"
.br
.ti -1c
.RI "pixman_fixed_t \fBdx_big\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
