.TH "pixman_image" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixman_image
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "image_type_t \fBtype\fP"
.br
.ti -1c
.RI "\fBimage_common_t\fP \fBcommon\fP"
.br
.ti -1c
.RI "\fBbits_image_t\fP \fBbits\fP"
.br
.ti -1c
.RI "\fBgradient_t\fP \fBgradient\fP"
.br
.ti -1c
.RI "\fBlinear_gradient_t\fP \fBlinear\fP"
.br
.ti -1c
.RI "\fBconical_gradient_t\fP \fBconical\fP"
.br
.ti -1c
.RI "\fBradial_gradient_t\fP \fBradial\fP"
.br
.ti -1c
.RI "\fBsolid_fill_t\fP \fBsolid\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
