.TH "pixman_triangle" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixman_triangle
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpixman_point_fixed_t\fP \fBp1\fP"
.br
.ti -1c
.RI "\fBpixman_point_fixed_t\fP \fBp2\fP"
.br
.ti -1c
.RI "\fBpixman_point_fixed_t\fP \fBp3\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
