.TH "pixman_rectangle16" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixman_rectangle16
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int16_t \fBx\fP"
.br
.ti -1c
.RI "int16_t \fBy\fP"
.br
.ti -1c
.RI "uint16_t \fBwidth\fP"
.br
.ti -1c
.RI "uint16_t \fBheight\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
