.TH "pixman_color" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixman_color
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBred\fP"
.br
.ti -1c
.RI "uint16_t \fBgreen\fP"
.br
.ti -1c
.RI "uint16_t \fBblue\fP"
.br
.ti -1c
.RI "uint16_t \fBalpha\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
