.TH "PixOrCopyBlock" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PixOrCopyBlock
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPixOrCopyBlock\fP * \fBnext_\fP"
.br
.ti -1c
.RI "\fBPixOrCopy\fP * \fBstart_\fP"
.br
.ti -1c
.RI "int \fBsize_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
