.TH "pl_unix_substate" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pl_unix_substate
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBPL_UNIX_TOTALSIZE_INIT\fP = 0, \fBPL_UNIX_TOTALSIZE_READING\fP }"
.br
.ti -1c
.RI "enum { \fBPL_UNIX_HLINKS_PRESPACE\fP = 0, \fBPL_UNIX_HLINKS_NUMBER\fP }"
.br
.ti -1c
.RI "enum { \fBPL_UNIX_USER_PRESPACE\fP = 0, \fBPL_UNIX_USER_PARSING\fP }"
.br
.ti -1c
.RI "enum { \fBPL_UNIX_GROUP_PRESPACE\fP = 0, \fBPL_UNIX_GROUP_NAME\fP }"
.br
.ti -1c
.RI "enum { \fBPL_UNIX_SIZE_PRESPACE\fP = 0, \fBPL_UNIX_SIZE_NUMBER\fP }"
.br
.ti -1c
.RI "enum { \fBPL_UNIX_TIME_PREPART1\fP = 0, \fBPL_UNIX_TIME_PART1\fP, \fBPL_UNIX_TIME_PREPART2\fP, \fBPL_UNIX_TIME_PART2\fP, \fBPL_UNIX_TIME_PREPART3\fP, \fBPL_UNIX_TIME_PART3\fP }"
.br
.ti -1c
.RI "enum { \fBPL_UNIX_FILENAME_PRESPACE\fP = 0, \fBPL_UNIX_FILENAME_NAME\fP, \fBPL_UNIX_FILENAME_WINDOWSEOL\fP }"
.br
.ti -1c
.RI "enum { \fBPL_UNIX_SYMLINK_PRESPACE\fP = 0, \fBPL_UNIX_SYMLINK_NAME\fP, \fBPL_UNIX_SYMLINK_PRETARGET1\fP, \fBPL_UNIX_SYMLINK_PRETARGET2\fP, \fBPL_UNIX_SYMLINK_PRETARGET3\fP, \fBPL_UNIX_SYMLINK_PRETARGET4\fP, \fBPL_UNIX_SYMLINK_TARGET\fP, \fBPL_UNIX_SYMLINK_WINDOWSEOL\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum pl_unix_substate:: { \&.\&.\&. }  \fBtotal_dirsize\fP"
.br
.ti -1c
.RI "enum pl_unix_substate:: { \&.\&.\&. }  \fBhlinks\fP"
.br
.ti -1c
.RI "enum pl_unix_substate:: { \&.\&.\&. }  \fBuser\fP"
.br
.ti -1c
.RI "enum pl_unix_substate:: { \&.\&.\&. }  \fBgroup\fP"
.br
.ti -1c
.RI "enum pl_unix_substate:: { \&.\&.\&. }  \fBsize\fP"
.br
.ti -1c
.RI "enum pl_unix_substate:: { \&.\&.\&. }  \fBtime\fP"
.br
.ti -1c
.RI "enum pl_unix_substate:: { \&.\&.\&. }  \fBfilename\fP"
.br
.ti -1c
.RI "enum pl_unix_substate:: { \&.\&.\&. }  \fBsymlink\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
