.TH "pl_winNT_substate" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pl_winNT_substate
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBPL_WINNT_TIME_PRESPACE\fP = 0, \fBPL_WINNT_TIME_TIME\fP }"
.br
.ti -1c
.RI "enum { \fBPL_WINNT_DIRORSIZE_PRESPACE\fP = 0, \fBPL_WINNT_DIRORSIZE_CONTENT\fP }"
.br
.ti -1c
.RI "enum { \fBPL_WINNT_FILENAME_PRESPACE\fP = 0, \fBPL_WINNT_FILENAME_CONTENT\fP, \fBPL_WINNT_FILENAME_WINEOL\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum pl_winNT_substate:: { \&.\&.\&. }  \fBtime\fP"
.br
.ti -1c
.RI "enum pl_winNT_substate:: { \&.\&.\&. }  \fBdirorsize\fP"
.br
.ti -1c
.RI "enum pl_winNT_substate:: { \&.\&.\&. }  \fBfilename\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
