.TH "Plugin" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Plugin
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlugin\fP (CFUUIDRef factoryID)"
.br
.ti -1c
.RI "HRESULT \fBQueryInterface\fP (REFIID iid, LPVOID *ppv)"
.br
.ti -1c
.RI "ULONG \fBAddRef\fP ()"
.br
.ti -1c
.RI "ULONG \fBRelease\fP ()"
.br
.ti -1c
.RI "OSStatus \fBGeneratePreviewForURL\fP (QLPreviewRequestRef preview, CFURLRef url, CFStringRef contentTypeUTI, CFDictionaryRef options)"
.br
.ti -1c
.RI "void \fBCancelPreviewGeneration\fP (QLPreviewRequestRef preview)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static OSStatus \fBGenerateThumbnailForURL\fP (QLThumbnailRequestRef thumbnail, CFURLRef url, CFStringRef contentTypeUTI, CFDictionaryRef options, CGSize maxSize)"
.br
.ti -1c
.RI "static void \fBCancelThumbnailGeneration\fP (QLThumbnailRequestRef thumbnail)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QLGeneratorInterfaceStruct * \fBinterface\fP"
.br
.ti -1c
.RI "CFUUIDRef \fBfactoryID\fP"
.br
.ti -1c
.RI "ULONG \fBrefCount\fP = 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
