.TH "png_color_8_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
png_color_8_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "png_byte \fBred\fP"
.br
.ti -1c
.RI "png_byte \fBgreen\fP"
.br
.ti -1c
.RI "png_byte \fBblue\fP"
.br
.ti -1c
.RI "png_byte \fBgray\fP"
.br
.ti -1c
.RI "png_byte \fBalpha\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
