.TH "png_sPLT_entry_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
png_sPLT_entry_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "png_uint_16 \fBred\fP"
.br
.ti -1c
.RI "png_uint_16 \fBgreen\fP"
.br
.ti -1c
.RI "png_uint_16 \fBblue\fP"
.br
.ti -1c
.RI "png_uint_16 \fBalpha\fP"
.br
.ti -1c
.RI "png_uint_16 \fBfrequency\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
