.TH "png_info_def" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
png_info_def
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "png_uint_32 \fBwidth\fP"
.br
.ti -1c
.RI "png_uint_32 \fBheight\fP"
.br
.ti -1c
.RI "png_uint_32 \fBvalid\fP"
.br
.ti -1c
.RI "size_t \fBrowbytes\fP"
.br
.ti -1c
.RI "\fBpng_colorp\fP \fBpalette\fP"
.br
.ti -1c
.RI "png_uint_16 \fBnum_palette\fP"
.br
.ti -1c
.RI "png_uint_16 \fBnum_trans\fP"
.br
.ti -1c
.RI "png_byte \fBbit_depth\fP"
.br
.ti -1c
.RI "png_byte \fBcolor_type\fP"
.br
.ti -1c
.RI "png_byte \fBcompression_type\fP"
.br
.ti -1c
.RI "png_byte \fBfilter_type\fP"
.br
.ti -1c
.RI "png_byte \fBinterlace_type\fP"
.br
.ti -1c
.RI "png_byte \fBchannels\fP"
.br
.ti -1c
.RI "png_byte \fBpixel_depth\fP"
.br
.ti -1c
.RI "png_byte \fBspare_byte\fP"
.br
.ti -1c
.RI "png_uint_32 \fBfree_me\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
