.TH "png_time_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
png_time_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "png_uint_16 \fByear\fP"
.br
.ti -1c
.RI "png_byte \fBmonth\fP"
.br
.ti -1c
.RI "png_byte \fBday\fP"
.br
.ti -1c
.RI "png_byte \fBhour\fP"
.br
.ti -1c
.RI "png_byte \fBminute\fP"
.br
.ti -1c
.RI "png_byte \fBsecond\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
