.TH "png_row_info_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
png_row_info_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "png_uint_32 \fBwidth\fP"
.br
.ti -1c
.RI "size_t \fBrowbytes\fP"
.br
.ti -1c
.RI "png_byte \fBcolor_type\fP"
.br
.ti -1c
.RI "png_byte \fBbit_depth\fP"
.br
.ti -1c
.RI "png_byte \fBchannels\fP"
.br
.ti -1c
.RI "png_byte \fBpixel_depth\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
