.TH "png_struct_def" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
png_struct_def
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "png_error_ptr \fBerror_fn\fP"
.br
.ti -1c
.RI "png_voidp \fBerror_ptr\fP"
.br
.ti -1c
.RI "png_rw_ptr \fBwrite_data_fn\fP"
.br
.ti -1c
.RI "png_rw_ptr \fBread_data_fn\fP"
.br
.ti -1c
.RI "png_voidp \fBio_ptr\fP"
.br
.ti -1c
.RI "png_uint_32 \fBmode\fP"
.br
.ti -1c
.RI "png_uint_32 \fBflags\fP"
.br
.ti -1c
.RI "png_uint_32 \fBtransformations\fP"
.br
.ti -1c
.RI "png_uint_32 \fBzowner\fP"
.br
.ti -1c
.RI "\fBz_stream\fP \fBzstream\fP"
.br
.ti -1c
.RI "png_uint_32 \fBwidth\fP"
.br
.ti -1c
.RI "png_uint_32 \fBheight\fP"
.br
.ti -1c
.RI "png_uint_32 \fBnum_rows\fP"
.br
.ti -1c
.RI "png_uint_32 \fBusr_width\fP"
.br
.ti -1c
.RI "size_t \fBrowbytes\fP"
.br
.ti -1c
.RI "png_uint_32 \fBiwidth\fP"
.br
.ti -1c
.RI "png_uint_32 \fBrow_number\fP"
.br
.ti -1c
.RI "png_uint_32 \fBchunk_name\fP"
.br
.ti -1c
.RI "png_bytep \fBprev_row\fP"
.br
.ti -1c
.RI "png_bytep \fBrow_buf\fP"
.br
.ti -1c
.RI "size_t \fBinfo_rowbytes\fP"
.br
.ti -1c
.RI "png_uint_32 \fBidat_size\fP"
.br
.ti -1c
.RI "png_uint_32 \fBcrc\fP"
.br
.ti -1c
.RI "\fBpng_colorp\fP \fBpalette\fP"
.br
.ti -1c
.RI "png_uint_16 \fBnum_palette\fP"
.br
.ti -1c
.RI "png_uint_16 \fBnum_trans\fP"
.br
.ti -1c
.RI "png_byte \fBcompression\fP"
.br
.ti -1c
.RI "png_byte \fBfilter\fP"
.br
.ti -1c
.RI "png_byte \fBinterlaced\fP"
.br
.ti -1c
.RI "png_byte \fBpass\fP"
.br
.ti -1c
.RI "png_byte \fBdo_filter\fP"
.br
.ti -1c
.RI "png_byte \fBcolor_type\fP"
.br
.ti -1c
.RI "png_byte \fBbit_depth\fP"
.br
.ti -1c
.RI "png_byte \fBusr_bit_depth\fP"
.br
.ti -1c
.RI "png_byte \fBpixel_depth\fP"
.br
.ti -1c
.RI "png_byte \fBchannels\fP"
.br
.ti -1c
.RI "png_byte \fBsig_bytes\fP"
.br
.ti -1c
.RI "png_byte \fBmaximum_pixel_depth\fP"
.br
.ti -1c
.RI "png_byte \fBtransformed_pixel_depth\fP"
.br
.ti -1c
.RI "png_read_status_ptr \fBread_row_fn\fP"
.br
.ti -1c
.RI "png_write_status_ptr \fBwrite_row_fn\fP"
.br
.ti -1c
.RI "png_uint_32 \fBfree_me\fP"
.br
.ti -1c
.RI "png_bytep \fBbig_row_buf\fP"
.br
.ti -1c
.RI "png_byte \fBcompression_type\fP"
.br
.ti -1c
.RI "size_t \fBold_big_row_buf_size\fP"
.br
.ti -1c
.RI "png_bytep \fBbig_prev_row\fP"
.br
.ti -1c
.RI "void(* \fBread_filter\fP [PNG_FILTER_VALUE_LAST\-1])(\fBpng_row_infop\fP row_info, png_bytep row, png_const_bytep prev_row)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
