.TH "png_sPLT_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
png_sPLT_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "png_charp \fBname\fP"
.br
.ti -1c
.RI "png_byte \fBdepth\fP"
.br
.ti -1c
.RI "\fBpng_sPLT_entryp\fP \fBentries\fP"
.br
.ti -1c
.RI "png_int_32 \fBnentries\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
