.TH "PngObjectHandler" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PngObjectHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpng_infop\fP \fBinfo_ptr\fP = nullptr"
.br
.ti -1c
.RI "\fBpng_structp\fP \fBpng_ptr\fP = nullptr"
.br
.ti -1c
.RI "\fBpng_infop\fP \fBend_info_ptr\fP = nullptr"
.br
.ti -1c
.RI "png_voidp \fBrow_ptr\fP = nullptr"
.br
.ti -1c
.RI "\fBBufState\fP * \fBbuf_state\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
