.TH "ppm_source_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ppm_source_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBcjpeg_source_struct\fP \fBpub\fP"
.br
.ti -1c
.RI "U_CHAR * \fBiobuffer\fP"
.br
.ti -1c
.RI "JSAMPROW \fBpixrow\fP"
.br
.ti -1c
.RI "size_t \fBbuffer_width\fP"
.br
.ti -1c
.RI "JSAMPLE * \fBrescale\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
