.TH "ppmd_stream" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ppmd_stream
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstat\fP"
.br
.ti -1c
.RI "\fBCPpmd7\fP \fBppmd7_context\fP"
.br
.ti -1c
.RI "\fBCPpmd7z_RangeEnc\fP \fBrange_enc\fP"
.br
.ti -1c
.RI "\fBIByteOut\fP \fBbyteout\fP"
.br
.ti -1c
.RI "uint8_t * \fBbuff\fP"
.br
.ti -1c
.RI "uint8_t * \fBbuff_ptr\fP"
.br
.ti -1c
.RI "uint8_t * \fBbuff_end\fP"
.br
.ti -1c
.RI "size_t \fBbuff_bytes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
