.TH "PreCalculatedPrimeTable" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PreCalculatedPrimeTable
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPrimeTable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPreCalculatedPrimeTable\fP (int max)"
.br
.ti -1c
.RI "bool \fBIsPrime\fP (int n) const override"
.br
.ti -1c
.RI "int \fBGetNextPrime\fP (int p) const override"
.br
.in -1c
.in +1c
.ti -1c
.RI "virtual bool \fBIsPrime\fP (int n) const =0"
.br
.ti -1c
.RI "virtual int \fBGetNextPrime\fP (int p) const =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int PreCalculatedPrimeTable::GetNextPrime (int p) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrimeTable\fP\&.
.SS "bool PreCalculatedPrimeTable::IsPrime (int n) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBPrimeTable\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
