.TH "precision_checker< ErrorHandler >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
precision_checker< ErrorHandler >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBprecision_checker\fP (ErrorHandler &eh)"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(is_integer< T >\fB::value\fP) > FMT_CONSTEXPR auto \fBoperator()\fP (T \fBvalue\fP) \-> unsigned long long"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(!is_integer< T >\fB::value\fP) > FMT_CONSTEXPR auto \fBoperator()\fP (T) \-> unsigned long long"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBprecision_checker\fP (ErrorHandler &eh)"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(is_integer< T >\fB::value\fP) > FMT_CONSTEXPR auto \fBoperator()\fP (T \fBvalue\fP) \-> unsigned long long"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(!is_integer< T >\fB::value\fP) > FMT_CONSTEXPR auto \fBoperator()\fP (T) \-> unsigned long long"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBprecision_checker\fP (ErrorHandler &eh)"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(is_integer< T >\fB::value\fP) > FMT_CONSTEXPR auto \fBoperator()\fP (T \fBvalue\fP) \-> unsigned long long"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(!is_integer< T >\fB::value\fP) > FMT_CONSTEXPR auto \fBoperator()\fP (T) \-> unsigned long long"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBprecision_checker\fP (ErrorHandler &eh)"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(is_integer< T >\fB::value\fP) > FMT_CONSTEXPR auto \fBoperator()\fP (T \fBvalue\fP) \-> unsigned long long"
.br
.ti -1c
.RI "template<typename T , FMT_ENABLE_IF(!is_integer< T >\fB::value\fP) > FMT_CONSTEXPR auto \fBoperator()\fP (T) \-> unsigned long long"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
