.TH "PredFunctor5" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PredFunctor5
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > bool \fBoperator()\fP (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
