.TH "private_data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
private_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const unsigned char * \fBnext_in\fP"
.br
.ti -1c
.RI "size_t \fBavail_in\fP"
.br
.ti -1c
.RI "size_t \fBconsume_unnotified\fP"
.br
.ti -1c
.RI "int \fBbit_buffer\fP"
.br
.ti -1c
.RI "int \fBbits_avail\fP"
.br
.ti -1c
.RI "size_t \fBbytes_in_section\fP"
.br
.ti -1c
.RI "size_t \fBout_block_size\fP"
.br
.ti -1c
.RI "void * \fBout_block\fP"
.br
.ti -1c
.RI "int \fBuse_reset_code\fP"
.br
.ti -1c
.RI "int \fBend_of_stream\fP"
.br
.ti -1c
.RI "int \fBmaxcode\fP"
.br
.ti -1c
.RI "int \fBmaxcode_bits\fP"
.br
.ti -1c
.RI "int \fBsection_end_code\fP"
.br
.ti -1c
.RI "int \fBbits\fP"
.br
.ti -1c
.RI "int \fBoldcode\fP"
.br
.ti -1c
.RI "int \fBfinbyte\fP"
.br
.ti -1c
.RI "int \fBfree_ent\fP"
.br
.ti -1c
.RI "unsigned char \fBsuffix\fP [65536]"
.br
.ti -1c
.RI "uint16_t \fBprefix\fP [65536]"
.br
.ti -1c
.RI "unsigned char * \fBstackp\fP"
.br
.ti -1c
.RI "unsigned char \fBstack\fP [65300]"
.br
.ti -1c
.RI "int \fBcompression_level\fP"
.br
.ti -1c
.RI "struct \fBarchive_write_program_data\fP * \fBpdata\fP"
.br
.ti -1c
.RI "int64_t \fBin_count\fP"
.br
.ti -1c
.RI "int64_t \fBout_count\fP"
.br
.ti -1c
.RI "int64_t \fBcheckpoint\fP"
.br
.ti -1c
.RI "int \fBcode_len\fP"
.br
.ti -1c
.RI "int \fBcur_maxcode\fP"
.br
.ti -1c
.RI "int \fBmax_maxcode\fP"
.br
.ti -1c
.RI "int \fBhashtab\fP [HSIZE]"
.br
.ti -1c
.RI "unsigned short \fBcodetab\fP [HSIZE]"
.br
.ti -1c
.RI "int \fBfirst_free\fP"
.br
.ti -1c
.RI "int \fBcompress_ratio\fP"
.br
.ti -1c
.RI "int \fBcur_code\fP"
.br
.ti -1c
.RI "int \fBcur_fcode\fP"
.br
.ti -1c
.RI "int \fBbit_offset\fP"
.br
.ti -1c
.RI "unsigned char \fBbit_buf\fP"
.br
.ti -1c
.RI "unsigned char * \fBcompressed\fP"
.br
.ti -1c
.RI "size_t \fBcompressed_buffer_size\fP"
.br
.ti -1c
.RI "size_t \fBcompressed_offset\fP"
.br
.ti -1c
.RI "int \fBtimestamp\fP"
.br
.ti -1c
.RI "unsigned \fBheader_written\fP:1"
.br
.ti -1c
.RI "unsigned \fBversion_number\fP:1"
.br
.ti -1c
.RI "unsigned \fBblock_independence\fP:1"
.br
.ti -1c
.RI "unsigned \fBblock_checksum\fP:1"
.br
.ti -1c
.RI "unsigned \fBstream_size\fP:1"
.br
.ti -1c
.RI "unsigned \fBstream_checksum\fP:1"
.br
.ti -1c
.RI "unsigned \fBpreset_dictionary\fP:1"
.br
.ti -1c
.RI "unsigned \fBblock_maximum_size\fP:3"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBdescription\fP"
.br
.ti -1c
.RI "char * \fBcmd\fP"
.br
.ti -1c
.RI "int \fBthreads\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
