.TH "PrivateCode" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PrivateCode
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFRIEND_TEST\fP (PrivateCodeTest, CanAccessPrivateMembers)"
.br
.ti -1c
.RI "\fBFRIEND_TEST\fP (\fBPrivateCodeFixtureTest\fP, CanAccessPrivateMembers)"
.br
.ti -1c
.RI "int \fBx\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
