.TH "prng_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prng_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsmallprng_t\fP \fBp1\fP"
.br
.ti -1c
.RI "\fBsmallprng_t\fP \fBp2\fP"
.br
.ti -1c
.RI "\fBsmallprng_t\fP \fBp3\fP"
.br
.ti -1c
.RI "\fBsmallprng_t\fP \fBp4\fP"
.br
.ti -1c
.RI "\fBsmallprng_t\fP \fBp0\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
