.TH "Progress" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Progress
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBIT\fP (callback)"
.br
.ti -1c
.RI "\fBBIT\fP (is_t_startransfer_set)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "time_t \fBlastshow\fP"
.br
.ti -1c
.RI "curl_off_t \fBsize_dl\fP"
.br
.ti -1c
.RI "curl_off_t \fBsize_ul\fP"
.br
.ti -1c
.RI "curl_off_t \fBdownloaded\fP"
.br
.ti -1c
.RI "curl_off_t \fBuploaded\fP"
.br
.ti -1c
.RI "curl_off_t \fBcurrent_speed\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "timediff_t \fBtimespent\fP"
.br
.ti -1c
.RI "curl_off_t \fBdlspeed\fP"
.br
.ti -1c
.RI "curl_off_t \fBulspeed\fP"
.br
.ti -1c
.RI "timediff_t \fBt_nslookup\fP"
.br
.ti -1c
.RI "timediff_t \fBt_connect\fP"
.br
.ti -1c
.RI "timediff_t \fBt_appconnect\fP"
.br
.ti -1c
.RI "timediff_t \fBt_pretransfer\fP"
.br
.ti -1c
.RI "timediff_t \fBt_starttransfer\fP"
.br
.ti -1c
.RI "timediff_t \fBt_redirect\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBstart\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBt_startsingle\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBt_startop\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBt_acceptdata\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBul_limit_start\fP"
.br
.ti -1c
.RI "curl_off_t \fBul_limit_size\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBdl_limit_start\fP"
.br
.ti -1c
.RI "curl_off_t \fBdl_limit_size\fP"
.br
.ti -1c
.RI "curl_off_t \fBspeeder\fP [CURR_TIME]"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBspeeder_time\fP [CURR_TIME]"
.br
.ti -1c
.RI "int \fBspeeder_c\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
