.TH "program_filter" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
program_filter
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive_string\fP \fBdescription\fP"
.br
.ti -1c
.RI "pid_t \fBchild\fP"
.br
.ti -1c
.RI "int \fBexit_status\fP"
.br
.ti -1c
.RI "int \fBwaitpid_return\fP"
.br
.ti -1c
.RI "int \fBchild_stdin\fP"
.br
.ti -1c
.RI "int \fBchild_stdout\fP"
.br
.ti -1c
.RI "char * \fBout_buf\fP"
.br
.ti -1c
.RI "size_t \fBout_buf_len\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
