.TH "program_bidder" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
program_bidder
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBdescription\fP"
.br
.ti -1c
.RI "char * \fBcmd\fP"
.br
.ti -1c
.RI "void * \fBsignature\fP"
.br
.ti -1c
.RI "size_t \fBsignature_len\fP"
.br
.ti -1c
.RI "int \fBinhibit\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
