.TH "Proto" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Proto
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCommonHeader\fP"
.br
.ti -1c
.RI "lu_byte \fBnumparams\fP"
.br
.ti -1c
.RI "lu_byte \fBis_vararg\fP"
.br
.ti -1c
.RI "lu_byte \fBmaxstacksize\fP"
.br
.ti -1c
.RI "int \fBsizeupvalues\fP"
.br
.ti -1c
.RI "int \fBsizek\fP"
.br
.ti -1c
.RI "int \fBsizecode\fP"
.br
.ti -1c
.RI "int \fBsizelineinfo\fP"
.br
.ti -1c
.RI "int \fBsizep\fP"
.br
.ti -1c
.RI "int \fBsizelocvars\fP"
.br
.ti -1c
.RI "int \fBsizeabslineinfo\fP"
.br
.ti -1c
.RI "int \fBlinedefined\fP"
.br
.ti -1c
.RI "int \fBlastlinedefined\fP"
.br
.ti -1c
.RI "\fBTValue\fP * \fBk\fP"
.br
.ti -1c
.RI "Instruction * \fBcode\fP"
.br
.ti -1c
.RI "struct \fBProto\fP ** \fBp\fP"
.br
.ti -1c
.RI "\fBUpvaldesc\fP * \fBupvalues\fP"
.br
.ti -1c
.RI "ls_byte * \fBlineinfo\fP"
.br
.ti -1c
.RI "\fBAbsLineInfo\fP * \fBabslineinfo\fP"
.br
.ti -1c
.RI "\fBLocVar\fP * \fBlocvars\fP"
.br
.ti -1c
.RI "\fBTString\fP * \fBsource\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBgclist\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
