.TH "PS_Decoder_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_Decoder_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPS_Builder\fP \fBbuilder\fP"
.br
.ti -1c
.RI "FT_Fixed \fBstack\fP [PS_MAX_OPERANDS+1]"
.br
.ti -1c
.RI "FT_Fixed * \fBtop\fP"
.br
.ti -1c
.RI "\fBPS_Decoder_Zone\fP \fBzones\fP [PS_MAX_SUBRS_CALLS+1]"
.br
.ti -1c
.RI "\fBPS_Decoder_Zone\fP * \fBzone\fP"
.br
.ti -1c
.RI "FT_Int \fBflex_state\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_flex_vectors\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBflex_vectors\fP [7]"
.br
.ti -1c
.RI "\fBCFF_Font\fP \fBcff\fP"
.br
.ti -1c
.RI "\fBCFF_SubFont\fP \fBcurrent_subfont\fP"
.br
.ti -1c
.RI "\fBFT_Generic\fP * \fBcf2_instance\fP"
.br
.ti -1c
.RI "FT_Pos * \fBglyph_width\fP"
.br
.ti -1c
.RI "FT_Bool \fBwidth_only\fP"
.br
.ti -1c
.RI "FT_Int \fBnum_hints\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_locals\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_globals\fP"
.br
.ti -1c
.RI "FT_Int \fBlocals_bias\fP"
.br
.ti -1c
.RI "FT_Int \fBglobals_bias\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBlocals\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBglobals\fP"
.br
.ti -1c
.RI "FT_Byte ** \fBglyph_names\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_glyphs\fP"
.br
.ti -1c
.RI "FT_Render_Mode \fBhint_mode\fP"
.br
.ti -1c
.RI "FT_Bool \fBseac\fP"
.br
.ti -1c
.RI "CFF_Decoder_Get_Glyph_Callback \fBget_glyph_callback\fP"
.br
.ti -1c
.RI "CFF_Decoder_Free_Glyph_Callback \fBfree_glyph_callback\fP"
.br
.ti -1c
.RI "FT_Service_PsCMaps \fBpsnames\fP"
.br
.ti -1c
.RI "FT_Int \fBlenIV\fP"
.br
.ti -1c
.RI "FT_UInt * \fBlocals_len\fP"
.br
.ti -1c
.RI "\fBFT_Hash\fP \fBlocals_hash\fP"
.br
.ti -1c
.RI "\fBFT_Matrix\fP \fBfont_matrix\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP \fBfont_offset\fP"
.br
.ti -1c
.RI "\fBPS_Blend\fP \fBblend\fP"
.br
.ti -1c
.RI "FT_Long * \fBbuildchar\fP"
.br
.ti -1c
.RI "FT_UInt \fBlen_buildchar\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
