.TH "PS_DriverRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_DriverRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_DriverRec\fP \fBroot\fP"
.br
.ti -1c
.RI "FT_UInt \fBhinting_engine\fP"
.br
.ti -1c
.RI "FT_Bool \fBno_stem_darkening\fP"
.br
.ti -1c
.RI "FT_Int \fBdarken_params\fP [8]"
.br
.ti -1c
.RI "FT_Int32 \fBrandom_seed\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
