.TH "PS_Hinter_Module_Rec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_Hinter_Module_Rec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_ModuleRec\fP \fBroot\fP"
.br
.ti -1c
.RI "\fBPS_HintsRec\fP \fBps_hints\fP"
.br
.ti -1c
.RI "\fBPSH_Globals_FuncsRec\fP \fBglobals_funcs\fP"
.br
.ti -1c
.RI "\fBT1_Hints_FuncsRec\fP \fBt1_funcs\fP"
.br
.ti -1c
.RI "\fBT2_Hints_FuncsRec\fP \fBt2_funcs\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
