.TH "PS_Table_FuncsRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_Table_FuncsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Error(* \fBinit\fP )(\fBPS_Table\fP table, FT_Int count, FT_Memory \fBmemory\fP)"
.br
.ti -1c
.RI "void(* \fBdone\fP )(\fBPS_Table\fP table)"
.br
.ti -1c
.RI "FT_Error(* \fBadd\fP )(\fBPS_Table\fP table, FT_Int idx, const void *object, FT_UInt length)"
.br
.ti -1c
.RI "void(* \fBrelease\fP )(\fBPS_Table\fP table)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
