.TH "PS_UnicodesRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PS_UnicodesRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_CMapRec\fP \fBcmap\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_maps\fP"
.br
.ti -1c
.RI "\fBPS_UniMap\fP * \fBmaps\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
