.TH "PSH_WidthsRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSH_WidthsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UInt \fBcount\fP"
.br
.ti -1c
.RI "\fBPSH_WidthRec\fP \fBwidths\fP [PS_GLOBALS_MAX_STD_WIDTHS]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
