.TH "PSH_PointRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSH_PointRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPSH_Point\fP \fBprev\fP"
.br
.ti -1c
.RI "\fBPSH_Point\fP \fBnext\fP"
.br
.ti -1c
.RI "\fBPSH_Contour\fP \fBcontour\fP"
.br
.ti -1c
.RI "FT_UInt \fBflags\fP"
.br
.ti -1c
.RI "FT_UInt \fBflags2\fP"
.br
.ti -1c
.RI "PSH_Dir \fBdir_in\fP"
.br
.ti -1c
.RI "PSH_Dir \fBdir_out\fP"
.br
.ti -1c
.RI "PSH_Hint \fBhint\fP"
.br
.ti -1c
.RI "FT_Pos \fBorg_u\fP"
.br
.ti -1c
.RI "FT_Pos \fBorg_v\fP"
.br
.ti -1c
.RI "FT_Pos \fBcur_u\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
