.TH "PSH_HintRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSH_HintRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Int \fBorg_pos\fP"
.br
.ti -1c
.RI "FT_Int \fBorg_len\fP"
.br
.ti -1c
.RI "FT_Pos \fBcur_pos\fP"
.br
.ti -1c
.RI "FT_Pos \fBcur_len\fP"
.br
.ti -1c
.RI "FT_UInt \fBflags\fP"
.br
.ti -1c
.RI "PSH_Hint \fBparent\fP"
.br
.ti -1c
.RI "FT_Int \fBorder\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
