.TH "PSHinter_Interface_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSHinter_Interface_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPSH_Globals_Funcs\fP(* \fBget_globals_funcs\fP )(\fBFT_Module\fP module)"
.br
.ti -1c
.RI "\fBT1_Hints_Funcs\fP(* \fBget_t1_funcs\fP )(\fBFT_Module\fP module)"
.br
.ti -1c
.RI "\fBT2_Hints_Funcs\fP(* \fBget_t2_funcs\fP )(\fBFT_Module\fP module)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
