.TH "PureInfo" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PureInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBIT\fP (timecond)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBhttpcode\fP"
.br
.ti -1c
.RI "int \fBhttpproxycode\fP"
.br
.ti -1c
.RI "int \fBhttpversion\fP"
.br
.ti -1c
.RI "time_t \fBfiletime\fP"
.br
.ti -1c
.RI "curl_off_t \fBheader_size\fP"
.br
.ti -1c
.RI "curl_off_t \fBrequest_size\fP"
.br
.ti -1c
.RI "unsigned long \fBproxyauthavail\fP"
.br
.ti -1c
.RI "unsigned long \fBhttpauthavail\fP"
.br
.ti -1c
.RI "long \fBnumconnects\fP"
.br
.ti -1c
.RI "char * \fBcontenttype\fP"
.br
.ti -1c
.RI "char * \fBwouldredirect\fP"
.br
.ti -1c
.RI "curl_off_t \fBretry_after\fP"
.br
.ti -1c
.RI "char \fBconn_primary_ip\fP [MAX_IPADR_LEN]"
.br
.ti -1c
.RI "int \fBconn_primary_port\fP"
.br
.ti -1c
.RI "char \fBconn_local_ip\fP [MAX_IPADR_LEN]"
.br
.ti -1c
.RI "int \fBconn_local_port\fP"
.br
.ti -1c
.RI "const char * \fBconn_scheme\fP"
.br
.ti -1c
.RI "unsigned int \fBconn_protocol\fP"
.br
.ti -1c
.RI "struct \fBcurl_certinfo\fP \fBcerts\fP"
.br
.ti -1c
.RI "CURLproxycode \fBpxcode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
