.TH "PyHeapTypeObject" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PyHeapTypeObject
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PyTypeObject \fBtype\fP"
.br
.ti -1c
.RI "PyNumberMethods \fBas_number\fP"
.br
.ti -1c
.RI "PyMappingMethods \fBas_mapping\fP"
.br
.ti -1c
.RI "PySequenceMethods \fBas_sequence\fP"
.br
.ti -1c
.RI "PyBufferProcs \fBas_buffer\fP"
.br
.ti -1c
.RI "PyObject * \fBname\fP"
.br
.ti -1c
.RI "PyObject * \fBslots\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
