.TH "QuantizedColorType" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuantizedColorType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GifByteType \fBRGB\fP [3]"
.br
.ti -1c
.RI "GifByteType \fBNewColorIndex\fP"
.br
.ti -1c
.RI "long \fBCount\fP"
.br
.ti -1c
.RI "struct \fBQuantizedColorType\fP * \fBPnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
