.TH "QueueNode< E >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueueNode< E >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const E & \fBelement\fP () const"
.br
.ti -1c
.RI "\fBQueueNode\fP * \fBnext\fP ()"
.br
.ti -1c
.RI "const \fBQueueNode\fP * \fBnext\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBQueue< E >\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
