.TH "Queue< E >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Queue< E >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "size_t \fBSize\fP () const"
.br
.ti -1c
.RI "\fBQueueNode\fP< E > * \fBHead\fP ()"
.br
.ti -1c
.RI "const \fBQueueNode\fP< E > * \fBHead\fP () const"
.br
.ti -1c
.RI "\fBQueueNode\fP< E > * \fBLast\fP ()"
.br
.ti -1c
.RI "const \fBQueueNode\fP< E > * \fBLast\fP () const"
.br
.ti -1c
.RI "void \fBEnqueue\fP (const E &element)"
.br
.ti -1c
.RI "E * \fBDequeue\fP ()"
.br
.ti -1c
.RI "template<typename F > \fBQueue\fP * \fBMap\fP (F function) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
