.TH "radial_gradient" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
radial_gradient
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBgradient_t\fP \fBcommon\fP"
.br
.ti -1c
.RI "\fBcircle_t\fP \fBc1\fP"
.br
.ti -1c
.RI "\fBcircle_t\fP \fBc2\fP"
.br
.ti -1c
.RI "\fBcircle_t\fP \fBdelta\fP"
.br
.ti -1c
.RI "double \fBa\fP"
.br
.ti -1c
.RI "double \fBinva\fP"
.br
.ti -1c
.RI "double \fBmindr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
