.TH "range_formatter< T, Char, enable_if_t< conjunction< std::is_same< T, remove_cvref_t< T > >, disjunction< is_formattable< T, Char >, detail::has_fallback_formatter< T, Char > > >::value > >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
range_formatter< T, Char, enable_if_t< conjunction< std::is_same< T, remove_cvref_t< T > >, disjunction< is_formattable< T, Char >, detail::has_fallback_formatter< T, Char > > >::value > >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR auto \fBunderlying\fP () \-> detail::range_formatter_type< Char, T > &"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_separator\fP (\fBbasic_string_view\fP< Char > sep)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_brackets\fP (\fBbasic_string_view\fP< Char > open, \fBbasic_string_view\fP< Char > close)"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename R , class FormatContext > auto \fBformat\fP (R &&range, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBunderlying\fP () \-> detail::range_formatter_type< Char, T > &"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_separator\fP (\fBbasic_string_view\fP< Char > sep)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_brackets\fP (\fBbasic_string_view\fP< Char > open, \fBbasic_string_view\fP< Char > close)"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename R , class FormatContext > auto \fBformat\fP (R &&range, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBunderlying\fP () \-> detail::range_formatter_type< Char, T > &"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_separator\fP (\fBbasic_string_view\fP< Char > sep)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_brackets\fP (\fBbasic_string_view\fP< Char > open, \fBbasic_string_view\fP< Char > close)"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename R , class FormatContext > auto \fBformat\fP (R &&range, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.ti -1c
.RI "FMT_CONSTEXPR auto \fBunderlying\fP () \-> detail::range_formatter_type< Char, T > &"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_separator\fP (\fBbasic_string_view\fP< Char > sep)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBset_brackets\fP (\fBbasic_string_view\fP< Char > open, \fBbasic_string_view\fP< Char > close)"
.br
.ti -1c
.RI "template<typename ParseContext > FMT_CONSTEXPR auto \fBparse\fP (ParseContext &ctx) \-> decltype(ctx\&.begin())"
.br
.ti -1c
.RI "template<typename R , class FormatContext > auto \fBformat\fP (R &&range, FormatContext &ctx) const \-> decltype(ctx\&.out())"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
