.TH "rar" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rar
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrar_br\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBmain_flags\fP"
.br
.ti -1c
.RI "unsigned long \fBfile_crc\fP"
.br
.ti -1c
.RI "char \fBreserved1\fP [2]"
.br
.ti -1c
.RI "char \fBreserved2\fP [4]"
.br
.ti -1c
.RI "char \fBencryptver\fP"
.br
.ti -1c
.RI "char \fBcompression_method\fP"
.br
.ti -1c
.RI "unsigned \fBfile_flags\fP"
.br
.ti -1c
.RI "int64_t \fBpacked_size\fP"
.br
.ti -1c
.RI "int64_t \fBunp_size\fP"
.br
.ti -1c
.RI "time_t \fBmtime\fP"
.br
.ti -1c
.RI "long \fBmnsec\fP"
.br
.ti -1c
.RI "mode_t \fBmode\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "char * \fBfilename_save\fP"
.br
.ti -1c
.RI "size_t \fBfilename_save_size\fP"
.br
.ti -1c
.RI "size_t \fBfilename_allocated\fP"
.br
.ti -1c
.RI "char \fBsalt\fP [8]"
.br
.ti -1c
.RI "time_t \fBatime\fP"
.br
.ti -1c
.RI "long \fBansec\fP"
.br
.ti -1c
.RI "time_t \fBctime\fP"
.br
.ti -1c
.RI "long \fBcnsec\fP"
.br
.ti -1c
.RI "time_t \fBarctime\fP"
.br
.ti -1c
.RI "long \fBarcnsec\fP"
.br
.ti -1c
.RI "int64_t \fBbytes_unconsumed\fP"
.br
.ti -1c
.RI "int64_t \fBbytes_remaining\fP"
.br
.ti -1c
.RI "int64_t \fBbytes_uncopied\fP"
.br
.ti -1c
.RI "int64_t \fBoffset\fP"
.br
.ti -1c
.RI "int64_t \fBoffset_outgoing\fP"
.br
.ti -1c
.RI "int64_t \fBoffset_seek\fP"
.br
.ti -1c
.RI "char \fBvalid\fP"
.br
.ti -1c
.RI "unsigned int \fBunp_offset\fP"
.br
.ti -1c
.RI "unsigned int \fBunp_buffer_size\fP"
.br
.ti -1c
.RI "unsigned char * \fBunp_buffer\fP"
.br
.ti -1c
.RI "unsigned int \fBdictionary_size\fP"
.br
.ti -1c
.RI "char \fBstart_new_block\fP"
.br
.ti -1c
.RI "char \fBentry_eof\fP"
.br
.ti -1c
.RI "unsigned long \fBcrc_calculated\fP"
.br
.ti -1c
.RI "int \fBfound_first_header\fP"
.br
.ti -1c
.RI "char \fBhas_endarc_header\fP"
.br
.ti -1c
.RI "struct \fBdata_block_offsets\fP * \fBdbo\fP"
.br
.ti -1c
.RI "unsigned int \fBcursor\fP"
.br
.ti -1c
.RI "unsigned int \fBnodes\fP"
.br
.ti -1c
.RI "char \fBfilename_must_match\fP"
.br
.ti -1c
.RI "struct \fBhuffman_code\fP \fBmaincode\fP"
.br
.ti -1c
.RI "struct \fBhuffman_code\fP \fBoffsetcode\fP"
.br
.ti -1c
.RI "struct \fBhuffman_code\fP \fBlowoffsetcode\fP"
.br
.ti -1c
.RI "struct \fBhuffman_code\fP \fBlengthcode\fP"
.br
.ti -1c
.RI "unsigned char \fBlengthtable\fP [HUFFMAN_TABLE_SIZE]"
.br
.ti -1c
.RI "struct \fBlzss\fP \fBlzss\fP"
.br
.ti -1c
.RI "unsigned int \fBlastlength\fP"
.br
.ti -1c
.RI "unsigned int \fBlastoffset\fP"
.br
.ti -1c
.RI "unsigned int \fBoldoffset\fP [4]"
.br
.ti -1c
.RI "unsigned int \fBlastlowoffset\fP"
.br
.ti -1c
.RI "unsigned int \fBnumlowoffsetrepeats\fP"
.br
.ti -1c
.RI "char \fBstart_new_table\fP"
.br
.ti -1c
.RI "struct \fBrar_filters\fP \fBfilters\fP"
.br
.ti -1c
.RI "char \fBppmd_valid\fP"
.br
.ti -1c
.RI "char \fBppmd_eod\fP"
.br
.ti -1c
.RI "char \fBis_ppmd_block\fP"
.br
.ti -1c
.RI "int \fBppmd_escape\fP"
.br
.ti -1c
.RI "\fBCPpmd7\fP \fBppmd7_context\fP"
.br
.ti -1c
.RI "\fBCPpmd7z_RangeDec\fP \fBrange_dec\fP"
.br
.ti -1c
.RI "\fBIByteIn\fP \fBbytein\fP"
.br
.ti -1c
.RI "int \fBinit_default_conversion\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_default\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBopt_sconv\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_utf8\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_utf16be\fP"
.br
.ti -1c
.RI "struct \fBrar::rar_br\fP \fBbr\fP"
.br
.ti -1c
.RI "int \fBhas_encrypted_entries\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
