.TH "rar5" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rar5
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBheader_initialized\fP"
.br
.ti -1c
.RI "int \fBskipped_magic\fP"
.br
.ti -1c
.RI "int \fBskip_mode\fP"
.br
.ti -1c
.RI "int \fBmerge_mode\fP"
.br
.ti -1c
.RI "uint64_t \fBqlist_offset\fP"
.br
.ti -1c
.RI "uint64_t \fBrr_offset\fP"
.br
.ti -1c
.RI "struct \fBgeneric_header\fP \fBgeneric\fP"
.br
.ti -1c
.RI "struct \fBmain_header\fP \fBmain\fP"
.br
.ti -1c
.RI "struct \fBcomp_state\fP \fBcstate\fP"
.br
.ti -1c
.RI "struct \fBfile_header\fP \fBfile\fP"
.br
.ti -1c
.RI "struct \fBbit_reader\fP \fBbits\fP"
.br
.ti -1c
.RI "struct \fBmultivolume\fP \fBvol\fP"
.br
.ti -1c
.RI "struct \fBcompressed_block_header\fP \fBlast_block_hdr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
