.TH "rar_filters" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rar_filters
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBrar_virtual_machine\fP * \fBvm\fP"
.br
.ti -1c
.RI "struct \fBrar_program_code\fP * \fBprogs\fP"
.br
.ti -1c
.RI "struct \fBrar_filter\fP * \fBstack\fP"
.br
.ti -1c
.RI "int64_t \fBfilterstart\fP"
.br
.ti -1c
.RI "uint32_t \fBlastfilternum\fP"
.br
.ti -1c
.RI "int64_t \fBlastend\fP"
.br
.ti -1c
.RI "uint8_t * \fBbytes\fP"
.br
.ti -1c
.RI "size_t \fBbytes_ready\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
