.TH "rar_program_code" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rar_program_code
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t * \fBstaticdata\fP"
.br
.ti -1c
.RI "uint32_t \fBstaticdatalen\fP"
.br
.ti -1c
.RI "uint8_t * \fBglobalbackup\fP"
.br
.ti -1c
.RI "uint32_t \fBglobalbackuplen\fP"
.br
.ti -1c
.RI "uint64_t \fBfingerprint\fP"
.br
.ti -1c
.RI "uint32_t \fBusagecount\fP"
.br
.ti -1c
.RI "uint32_t \fBoldfilterlength\fP"
.br
.ti -1c
.RI "struct \fBrar_program_code\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
