.TH "rar_header" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rar_header
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBcrc\fP [2]"
.br
.ti -1c
.RI "char \fBtype\fP"
.br
.ti -1c
.RI "char \fBflags\fP [2]"
.br
.ti -1c
.RI "char \fBsize\fP [2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
