.TH "rar_filter" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rar_filter
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBrar_program_code\fP * \fBprog\fP"
.br
.ti -1c
.RI "uint32_t \fBinitialregisters\fP [8]"
.br
.ti -1c
.RI "uint8_t * \fBglobaldata\fP"
.br
.ti -1c
.RI "uint32_t \fBglobaldatalen\fP"
.br
.ti -1c
.RI "size_t \fBblockstartpos\fP"
.br
.ti -1c
.RI "uint32_t \fBblocklength\fP"
.br
.ti -1c
.RI "uint32_t \fBfilteredblockaddress\fP"
.br
.ti -1c
.RI "uint32_t \fBfilteredblocklength\fP"
.br
.ti -1c
.RI "struct \fBrar_filter\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
