.TH "rar_virtual_machine" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rar_virtual_machine
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBregisters\fP [8]"
.br
.ti -1c
.RI "uint8_t \fBmemory\fP [VM_MEMORY_SIZE+sizeof(uint32_t)]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
