.TH "read_memory_data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
read_memory_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const unsigned char * \fBstart\fP"
.br
.ti -1c
.RI "const unsigned char * \fBp\fP"
.br
.ti -1c
.RI "const unsigned char * \fBend\fP"
.br
.ti -1c
.RI "ssize_t \fBread_size\fP"
.br
.ti -1c
.RI "size_t \fBread_size\fP"
.br
.ti -1c
.RI "size_t \fBcopy_buff_size\fP"
.br
.ti -1c
.RI "size_t \fBcopy_buff_offset\fP"
.br
.ti -1c
.RI "char * \fBcopy_buff\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
