.TH "redircase" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
redircase
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBin\fP"
.br
.ti -1c
.RI "const char * \fBset\fP"
.br
.ti -1c
.RI "const char * \fBout\fP"
.br
.ti -1c
.RI "unsigned int \fBurlflags\fP"
.br
.ti -1c
.RI "unsigned int \fBsetflags\fP"
.br
.ti -1c
.RI "CURLUcode \fBucode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
