.TH "render_state" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
render_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcmark_strbuf\fP * \fBhtml\fP"
.br
.ti -1c
.RI "\fBcmark_node\fP * \fBplain\fP"
.br
.ti -1c
.RI "\fBcmark_strbuf\fP * \fBxml\fP"
.br
.ti -1c
.RI "int \fBindent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
