.TH "restore_time" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
restore_time
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "time_t \fBmtime\fP"
.br
.ti -1c
.RI "long \fBmtime_nsec\fP"
.br
.ti -1c
.RI "time_t \fBatime\fP"
.br
.ti -1c
.RI "long \fBatime_nsec\fP"
.br
.ti -1c
.RI "mode_t \fBfiletype\fP"
.br
.ti -1c
.RI "int \fBnoatime\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
