.TH "rpm" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rpm
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBST_LEAD\fP, \fBST_HEADER\fP, \fBST_HEADER_DATA\fP, \fBST_PADDING\fP, \fBST_ARCHIVE\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBtotal_in\fP"
.br
.ti -1c
.RI "size_t \fBhpos\fP"
.br
.ti -1c
.RI "size_t \fBhlen\fP"
.br
.ti -1c
.RI "unsigned char \fBheader\fP [16]"
.br
.ti -1c
.RI "enum rpm:: { \&.\&.\&. }  \fBstate\fP"
.br
.ti -1c
.RI "int \fBfirst_header\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
