.TH "rtsp_conn" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rtsp_conn
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBrtp_buf\fP"
.br
.ti -1c
.RI "ssize_t \fBrtp_bufsize\fP"
.br
.ti -1c
.RI "int \fBrtp_channel\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
