.TH "SASLproto" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SASLproto
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBservice\fP"
.br
.ti -1c
.RI "int \fBcontcode\fP"
.br
.ti -1c
.RI "int \fBfinalcode\fP"
.br
.ti -1c
.RI "size_t \fBmaxirlen\fP"
.br
.ti -1c
.RI "CURLcode(* \fBsendauth\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, const char *mech, const char *ir)"
.br
.ti -1c
.RI "CURLcode(* \fBsendcont\fP )(struct \fBCurl_easy\fP *\fBdata\fP, struct \fBconnectdata\fP *conn, const char *contauth)"
.br
.ti -1c
.RI "void(* \fBgetmessage\fP )(char *\fBbuffer\fP, char **outptr)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
