.TH "SASL" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SASL
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const struct \fBSASLproto\fP * \fBparams\fP"
.br
.ti -1c
.RI "saslstate \fBstate\fP"
.br
.ti -1c
.RI "unsigned short \fBauthmechs\fP"
.br
.ti -1c
.RI "unsigned short \fBprefmech\fP"
.br
.ti -1c
.RI "unsigned short \fBauthused\fP"
.br
.ti -1c
.RI "bool \fBresetprefs\fP"
.br
.ti -1c
.RI "bool \fBmutual_auth\fP"
.br
.ti -1c
.RI "bool \fBforce_ir\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
