.TH "savable_state" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
savable_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "INT32 \fBput_buffer\fP"
.br
.ti -1c
.RI "int \fBput_bits\fP"
.br
.ti -1c
.RI "int \fBlast_dc_val\fP [MAX_COMPS_IN_SCAN]"
.br
.ti -1c
.RI "unsigned int \fBEOBRUN\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
