.TH "scan_parse_context" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scan_parse_context
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBiterator\fP = string_view::iterator"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBscan_parse_context\fP (\fBstring_view\fP format)"
.br
.ti -1c
.RI "FMT_CONSTEXPR iterator \fBbegin\fP () const"
.br
.ti -1c
.RI "FMT_CONSTEXPR iterator \fBend\fP () const"
.br
.ti -1c
.RI "void \fBadvance_to\fP (iterator it)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
