.TH "scoped_mock< Mock >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scoped_mock< Mock >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::StrictMock< Mock >\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBtesting::StrictMock< Mock >\fP
.in +1c
.ti -1c
.RI "\fBStrictMock\fP (\fBA\fP &&arg)"
.br
.ti -1c
.RI "\fBStrictMock\fP (TArg1 &&arg1, TArg2 &&arg2, An &&\&.\&.\&. args)"
.br
.ti -1c
.RI "\fBStrictMock\fP (\fBA\fP &&arg)"
.br
.ti -1c
.RI "\fBStrictMock\fP (TArg1 &&arg1, TArg2 &&arg2, An &&\&.\&.\&. args)"
.br
.in -1c

Public Member Functions inherited from \fBMock\fP
.in +1c
.ti -1c
.RI "\fBMOCK_METHOD0\fP (DoThis, void())"
.br
.ti -1c
.RI "\fBMOCK_METHOD1\fP (VoidFromString, void(char *str))"
.br
.ti -1c
.RI "\fBMOCK_METHOD1\fP (StringFromString, char *(char *str))"
.br
.ti -1c
.RI "\fBMOCK_METHOD1\fP (IntFromString, int(char *str))"
.br
.ti -1c
.RI "\fBMOCK_METHOD1\fP (IntRefFromString, int &(char *str))"
.br
.ti -1c
.RI "\fBMOCK_METHOD1\fP (VoidFromFunc, void(void(*func)(char *str)))"
.br
.ti -1c
.RI "\fBMOCK_METHOD1\fP (VoidFromIntRef, void(int &n))"
.br
.ti -1c
.RI "\fBMOCK_METHOD1\fP (VoidFromFloat, void(float n))"
.br
.ti -1c
.RI "\fBMOCK_METHOD1\fP (VoidFromDouble, void(double n))"
.br
.ti -1c
.RI "\fBMOCK_METHOD1\fP (VoidFromVector, void(const std::vector< int > &v))"
.br
.in -1c

Public Member Functions inherited from \fBInterface\fP
.in +1c
.ti -1c
.RI "virtual void \fBVoidFromString\fP (char *str)=0"
.br
.ti -1c
.RI "virtual char * \fBStringFromString\fP (char *str)=0"
.br
.ti -1c
.RI "virtual int \fBIntFromString\fP (char *str)=0"
.br
.ti -1c
.RI "virtual int & \fBIntRefFromString\fP (char *str)=0"
.br
.ti -1c
.RI "virtual void \fBVoidFromFunc\fP (void(*func)(char *str))=0"
.br
.ti -1c
.RI "virtual void \fBVoidFromIntRef\fP (int &n)=0"
.br
.ti -1c
.RI "virtual void \fBVoidFromFloat\fP (float n)=0"
.br
.ti -1c
.RI "virtual void \fBVoidFromDouble\fP (double n)=0"
.br
.ti -1c
.RI "virtual void \fBVoidFromVector\fP (const std::vector< int > &v)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
