.TH "SDF_Renderer_Module_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDF_Renderer_Module_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_RendererRec\fP \fBroot\fP"
.br
.ti -1c
.RI "FT_UInt \fBspread\fP"
.br
.ti -1c
.RI "FT_Bool \fBflip_sign\fP"
.br
.ti -1c
.RI "FT_Bool \fBflip_y\fP"
.br
.ti -1c
.RI "FT_Bool \fBoverlaps\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
