.TH "SDF_Contour_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDF_Contour_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_26D6_Vec\fP \fBlast_pos\fP"
.br
.ti -1c
.RI "\fBSDF_Edge\fP * \fBedges\fP"
.br
.ti -1c
.RI "struct \fBSDF_Contour_\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
