.TH "SDL_MessageBoxColor" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MessageBoxColor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_messagebox\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint8 \fBr\fP"
.br
.ti -1c
.RI "Uint8 \fBg\fP"
.br
.ti -1c
.RI "Uint8 \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RGB value used in a message box color scheme 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
