.TH "SDL_Keysym" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Keysym \- The SDL keysym structure, used in key events\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_keyboard\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SDL_Scancode \fBscancode\fP"
.br
.ti -1c
.RI "SDL_Keycode \fBsym\fP"
.br
.ti -1c
.RI "Uint16 \fBmod\fP"
.br
.ti -1c
.RI "Uint32 \fBunused\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The SDL keysym structure, used in key events\&. 


.PP
\fBNote\fP
.RS 4
If you are looking for translated character input, see the SDL_TEXTINPUT event\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Uint16 SDL_Keysym::mod"
current key modifiers 
.SS "SDL_Scancode SDL_Keysym::scancode"
SDL physical key code - see SDL_Scancode for details 
.SS "SDL_Keycode SDL_Keysym::sym"
SDL virtual key code - see SDL_Keycode for details 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
