.TH "SDL_DollarGestureEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_DollarGestureEvent \- Dollar Gesture Event (event\&.dgesture\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "SDL_TouchID \fBtouchId\fP"
.br
.ti -1c
.RI "SDL_GestureID \fBgestureId\fP"
.br
.ti -1c
.RI "Uint32 \fBnumFingers\fP"
.br
.ti -1c
.RI "float \fBerror\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dollar Gesture Event (event\&.dgesture\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint32 SDL_DollarGestureEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "SDL_TouchID SDL_DollarGestureEvent::touchId"
The touch device id 
.SS "Uint32 SDL_DollarGestureEvent::type"
SDL_DOLLARGESTURE or SDL_DOLLARRECORD 
.SS "float SDL_DollarGestureEvent::x"
Normalized center of gesture 
.SS "float SDL_DollarGestureEvent::y"
Normalized center of gesture 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
