.TH "SDL_MessageBoxColorScheme" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MessageBoxColorScheme
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_messagebox\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSDL_MessageBoxColor\fP \fBcolors\fP [SDL_MESSAGEBOX_COLOR_MAX]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP set of colors to use for message box dialogs 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
