.TH "SDL_SysWMEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_SysWMEvent \- \fBA\fP video driver dependent system event (event\&.syswm\&.*) This event is disabled by default, you can enable it with SDL_EventState()  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "\fBSDL_SysWMmsg\fP * \fBmsg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP video driver dependent system event (event\&.syswm\&.*) This event is disabled by default, you can enable it with SDL_EventState() 


.PP
\fBNote\fP
.RS 4
If you want to use this event, you should include \fBSDL_syswm\&.h\fP\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBSDL_SysWMmsg\fP* SDL_SysWMEvent::msg"
driver dependent data, defined in \fBSDL_syswm\&.h\fP 
.SS "Uint32 SDL_SysWMEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_SysWMEvent::type"
SDL_SYSWMEVENT 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
