.TH "SDL_MouseMotionEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MouseMotionEvent \- Mouse motion event structure (event\&.motion\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "Uint32 \fBwindowID\fP"
.br
.ti -1c
.RI "Uint32 \fBwhich\fP"
.br
.ti -1c
.RI "Uint32 \fBstate\fP"
.br
.ti -1c
.RI "Sint32 \fBx\fP"
.br
.ti -1c
.RI "Sint32 \fBy\fP"
.br
.ti -1c
.RI "Sint32 \fBxrel\fP"
.br
.ti -1c
.RI "Sint32 \fByrel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Mouse motion event structure (event\&.motion\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint32 SDL_MouseMotionEvent::state"
The current button state 
.SS "Uint32 SDL_MouseMotionEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_MouseMotionEvent::type"
SDL_MOUSEMOTION 
.SS "Uint32 SDL_MouseMotionEvent::which"
The mouse instance id, or SDL_TOUCH_MOUSEID 
.SS "Uint32 SDL_MouseMotionEvent::windowID"
The window with mouse focus, if any 
.SS "Sint32 SDL_MouseMotionEvent::x"
X coordinate, relative to window 
.SS "Sint32 SDL_MouseMotionEvent::xrel"
The relative motion in the X direction 
.SS "Sint32 SDL_MouseMotionEvent::y"
Y coordinate, relative to window 
.SS "Sint32 SDL_MouseMotionEvent::yrel"
The relative motion in the Y direction 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
