.TH "SDL_HapticCustom" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_HapticCustom \- \fBA\fP structure containing a template for the SDL_HAPTIC_CUSTOM effect\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_haptic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint16 \fBtype\fP"
.br
.ti -1c
.RI "\fBSDL_HapticDirection\fP \fBdirection\fP"
.br
.ti -1c
.RI "Uint32 \fBlength\fP"
.br
.ti -1c
.RI "Uint16 \fBdelay\fP"
.br
.ti -1c
.RI "Uint16 \fBbutton\fP"
.br
.ti -1c
.RI "Uint16 \fBinterval\fP"
.br
.ti -1c
.RI "Uint8 \fBchannels\fP"
.br
.ti -1c
.RI "Uint16 \fBperiod\fP"
.br
.ti -1c
.RI "Uint16 \fBsamples\fP"
.br
.ti -1c
.RI "Uint16 * \fBdata\fP"
.br
.ti -1c
.RI "Uint16 \fBattack_length\fP"
.br
.ti -1c
.RI "Uint16 \fBattack_level\fP"
.br
.ti -1c
.RI "Uint16 \fBfade_length\fP"
.br
.ti -1c
.RI "Uint16 \fBfade_level\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP structure containing a template for the SDL_HAPTIC_CUSTOM effect\&. 

This struct is exclusively for the SDL_HAPTIC_CUSTOM effect\&.
.PP
\fBA\fP custom force feedback effect is much like a periodic effect, where the application can define its exact shape\&. You will have to allocate the data yourself\&. Data should consist of channels * samples Uint16 samples\&.
.PP
If channels is one, the effect is rotated using the defined direction\&. Otherwise it uses the samples in data for the different axes\&.
.PP
\fBSee also\fP
.RS 4
SDL_HAPTIC_CUSTOM 
.PP
\fBSDL_HapticEffect\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Uint16 SDL_HapticCustom::attack_length"
Duration of the attack\&. 
.SS "Uint16 SDL_HapticCustom::attack_level"
Level at the start of the attack\&. 
.SS "Uint16 SDL_HapticCustom::button"
Button that triggers the effect\&. 
.SS "Uint8 SDL_HapticCustom::channels"
Axes to use, minimum of one\&. 
.SS "Uint16* SDL_HapticCustom::data"
Should contain channels*samples items\&. 
.SS "Uint16 SDL_HapticCustom::delay"
Delay before starting the effect\&. 
.SS "\fBSDL_HapticDirection\fP SDL_HapticCustom::direction"
Direction of the effect\&. 
.SS "Uint16 SDL_HapticCustom::fade_length"
Duration of the fade\&. 
.SS "Uint16 SDL_HapticCustom::fade_level"
Level at the end of the fade\&. 
.SS "Uint16 SDL_HapticCustom::interval"
How soon it can be triggered again after button\&. 
.SS "Uint32 SDL_HapticCustom::length"
Duration of the effect\&. 
.SS "Uint16 SDL_HapticCustom::period"
Sample periods\&. 
.SS "Uint16 SDL_HapticCustom::samples"
Amount of samples\&. 
.SS "Uint16 SDL_HapticCustom::type"
SDL_HAPTIC_CUSTOM 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
