.TH "SDL_TextEditingExtEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_TextEditingExtEvent \- Extended keyboard text editing event structure (event\&.editExt\&.*) when text would be truncated if stored in the text buffer \fBSDL_TextEditingEvent\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "Uint32 \fBwindowID\fP"
.br
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "Sint32 \fBstart\fP"
.br
.ti -1c
.RI "Sint32 \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Extended keyboard text editing event structure (event\&.editExt\&.*) when text would be truncated if stored in the text buffer \fBSDL_TextEditingEvent\fP\&. 
.SH "Member Data Documentation"
.PP 
.SS "Sint32 SDL_TextEditingExtEvent::length"
The length of selected editing text 
.SS "Sint32 SDL_TextEditingExtEvent::start"
The start cursor of selected editing text 
.SS "char* SDL_TextEditingExtEvent::text"
The editing text, which should be freed with SDL_free(), and will not be NULL 
.SS "Uint32 SDL_TextEditingExtEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_TextEditingExtEvent::type"
SDL_TEXTEDITING_EXT 
.SS "Uint32 SDL_TextEditingExtEvent::windowID"
The window with keyboard focus, if any 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
