.TH "SDL_AudioDeviceEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_AudioDeviceEvent \- Audio device event structure (event\&.adevice\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "Uint32 \fBwhich\fP"
.br
.ti -1c
.RI "Uint8 \fBiscapture\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding1\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding2\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Audio device event structure (event\&.adevice\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint8 SDL_AudioDeviceEvent::iscapture"
zero if an output device, non-zero if a capture device\&. 
.SS "Uint32 SDL_AudioDeviceEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_AudioDeviceEvent::type"
SDL_AUDIODEVICEADDED, or SDL_AUDIODEVICEREMOVED 
.SS "Uint32 SDL_AudioDeviceEvent::which"
The audio device index for the ADDED event (valid until next SDL_GetNumAudioDevices() call), SDL_AudioDeviceID for the REMOVED event 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
