.TH "SDL_JoyBallEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_JoyBallEvent \- Joystick trackball motion event structure (event\&.jball\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "SDL_JoystickID \fBwhich\fP"
.br
.ti -1c
.RI "Uint8 \fBball\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding1\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding2\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding3\fP"
.br
.ti -1c
.RI "Sint16 \fBxrel\fP"
.br
.ti -1c
.RI "Sint16 \fByrel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Joystick trackball motion event structure (event\&.jball\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint8 SDL_JoyBallEvent::ball"
The joystick trackball index 
.SS "Uint32 SDL_JoyBallEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_JoyBallEvent::type"
SDL_JOYBALLMOTION 
.SS "SDL_JoystickID SDL_JoyBallEvent::which"
The joystick instance id 
.SS "Sint16 SDL_JoyBallEvent::xrel"
The relative motion in the X direction 
.SS "Sint16 SDL_JoyBallEvent::yrel"
The relative motion in the Y direction 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
