.TH "SDL_JoyDeviceEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_JoyDeviceEvent \- Joystick device event structure (event\&.jdevice\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "Sint32 \fBwhich\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Joystick device event structure (event\&.jdevice\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint32 SDL_JoyDeviceEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_JoyDeviceEvent::type"
SDL_JOYDEVICEADDED or SDL_JOYDEVICEREMOVED 
.SS "Sint32 SDL_JoyDeviceEvent::which"
The joystick device index for the ADDED event, instance id for the REMOVED event 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
