.TH "SDL_MultiGestureEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MultiGestureEvent \- Multiple Finger Gesture Event (event\&.mgesture\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "SDL_TouchID \fBtouchId\fP"
.br
.ti -1c
.RI "float \fBdTheta\fP"
.br
.ti -1c
.RI "float \fBdDist\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "Uint16 \fBnumFingers\fP"
.br
.ti -1c
.RI "Uint16 \fBpadding\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Multiple Finger Gesture Event (event\&.mgesture\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint32 SDL_MultiGestureEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "SDL_TouchID SDL_MultiGestureEvent::touchId"
The touch device id 
.SS "Uint32 SDL_MultiGestureEvent::type"
SDL_MULTIGESTURE 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
