.TH "SDL_ControllerAxisEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_ControllerAxisEvent \- Game controller axis motion event structure (event\&.caxis\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "SDL_JoystickID \fBwhich\fP"
.br
.ti -1c
.RI "Uint8 \fBaxis\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding1\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding2\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding3\fP"
.br
.ti -1c
.RI "Sint16 \fBvalue\fP"
.br
.ti -1c
.RI "Uint16 \fBpadding4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Game controller axis motion event structure (event\&.caxis\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint8 SDL_ControllerAxisEvent::axis"
The controller axis (SDL_GameControllerAxis) 
.SS "Uint32 SDL_ControllerAxisEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_ControllerAxisEvent::type"
SDL_CONTROLLERAXISMOTION 
.SS "Sint16 SDL_ControllerAxisEvent::value"
The axis value (range: -32768 to 32767) 
.SS "SDL_JoystickID SDL_ControllerAxisEvent::which"
The joystick instance id 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
