.TH "SDL_Palette" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Palette
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBncolors\fP"
.br
.ti -1c
.RI "\fBSDL_Color\fP * \fBcolors\fP"
.br
.ti -1c
.RI "Uint32 \fBversion\fP"
.br
.ti -1c
.RI "int \fBrefcount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
