.TH "SDL_MouseWheelEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MouseWheelEvent \- Mouse wheel event structure (event\&.wheel\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "Uint32 \fBwindowID\fP"
.br
.ti -1c
.RI "Uint32 \fBwhich\fP"
.br
.ti -1c
.RI "Sint32 \fBx\fP"
.br
.ti -1c
.RI "Sint32 \fBy\fP"
.br
.ti -1c
.RI "Uint32 \fBdirection\fP"
.br
.ti -1c
.RI "float \fBpreciseX\fP"
.br
.ti -1c
.RI "float \fBpreciseY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Mouse wheel event structure (event\&.wheel\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint32 SDL_MouseWheelEvent::direction"
Set to one of the SDL_MOUSEWHEEL_* defines\&. When FLIPPED the values in X and Y will be opposite\&. Multiply by -1 to change them back 
.SS "float SDL_MouseWheelEvent::preciseX"
The amount scrolled horizontally, positive to the right and negative to the left, with float precision (added in 2\&.0\&.18) 
.SS "float SDL_MouseWheelEvent::preciseY"
The amount scrolled vertically, positive away from the user and negative toward the user, with float precision (added in 2\&.0\&.18) 
.SS "Uint32 SDL_MouseWheelEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_MouseWheelEvent::type"
SDL_MOUSEWHEEL 
.SS "Uint32 SDL_MouseWheelEvent::which"
The mouse instance id, or SDL_TOUCH_MOUSEID 
.SS "Uint32 SDL_MouseWheelEvent::windowID"
The window with mouse focus, if any 
.SS "Sint32 SDL_MouseWheelEvent::x"
The amount scrolled horizontally, positive to the right and negative to the left 
.SS "Sint32 SDL_MouseWheelEvent::y"
The amount scrolled vertically, positive away from the user and negative toward the user 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
