.TH "SDL_HapticLeftRight" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_HapticLeftRight \- \fBA\fP structure containing a template for a Left/Right effect\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_haptic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint16 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBlength\fP"
.br
.ti -1c
.RI "Uint16 \fBlarge_magnitude\fP"
.br
.ti -1c
.RI "Uint16 \fBsmall_magnitude\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP structure containing a template for a Left/Right effect\&. 

This struct is exclusively for the SDL_HAPTIC_LEFTRIGHT effect\&.
.PP
The Left/Right effect is used to explicitly control the large and small motors, commonly found in modern game controllers\&. The small (right) motor is high frequency, and the large (left) motor is low frequency\&.
.PP
\fBSee also\fP
.RS 4
SDL_HAPTIC_LEFTRIGHT 
.PP
\fBSDL_HapticEffect\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Uint16 SDL_HapticLeftRight::large_magnitude"
Control of the large controller motor\&. 
.SS "Uint32 SDL_HapticLeftRight::length"
Duration of the effect in milliseconds\&. 
.SS "Uint16 SDL_HapticLeftRight::small_magnitude"
Control of the small controller motor\&. 
.SS "Uint16 SDL_HapticLeftRight::type"
SDL_HAPTIC_LEFTRIGHT 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
