.TH "SDL_JoyButtonEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_JoyButtonEvent \- Joystick button event structure (event\&.jbutton\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "SDL_JoystickID \fBwhich\fP"
.br
.ti -1c
.RI "Uint8 \fBbutton\fP"
.br
.ti -1c
.RI "Uint8 \fBstate\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding1\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Joystick button event structure (event\&.jbutton\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint8 SDL_JoyButtonEvent::button"
The joystick button index 
.SS "Uint8 SDL_JoyButtonEvent::state"
SDL_PRESSED or SDL_RELEASED 
.SS "Uint32 SDL_JoyButtonEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_JoyButtonEvent::type"
SDL_JOYBUTTONDOWN or SDL_JOYBUTTONUP 
.SS "SDL_JoystickID SDL_JoyButtonEvent::which"
The joystick instance id 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
