.TH "SDL_Rect" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Rect
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_rect\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP rectangle, with the origin at the upper left (integer)\&.
.PP
\fBSee also\fP
.RS 4
SDL_RectEmpty 
.PP
SDL_RectEquals 
.PP
SDL_HasIntersection 
.PP
SDL_IntersectRect 
.PP
SDL_IntersectRectAndLine 
.PP
SDL_UnionRect 
.PP
SDL_EnclosePoints 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
