.TH "SDL_ControllerSensorEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_ControllerSensorEvent \- Game controller sensor event structure (event\&.csensor\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "SDL_JoystickID \fBwhich\fP"
.br
.ti -1c
.RI "Sint32 \fBsensor\fP"
.br
.ti -1c
.RI "float \fBdata\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Game controller sensor event structure (event\&.csensor\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "float SDL_ControllerSensorEvent::data[3]"
Up to 3 values from the sensor, as defined in \fBSDL_sensor\&.h\fP 
.SS "Sint32 SDL_ControllerSensorEvent::sensor"
The type of the sensor, one of the values of SDL_SensorType 
.SS "Uint32 SDL_ControllerSensorEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_ControllerSensorEvent::type"
SDL_CONTROLLERSENSORUPDATE 
.SS "SDL_JoystickID SDL_ControllerSensorEvent::which"
The joystick instance id 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
