.TH "SDL_PixelFormat" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_PixelFormat
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_pixels\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBformat\fP"
.br
.ti -1c
.RI "\fBSDL_Palette\fP * \fBpalette\fP"
.br
.ti -1c
.RI "Uint8 \fBBitsPerPixel\fP"
.br
.ti -1c
.RI "Uint8 \fBBytesPerPixel\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding\fP [2]"
.br
.ti -1c
.RI "Uint32 \fBRmask\fP"
.br
.ti -1c
.RI "Uint32 \fBGmask\fP"
.br
.ti -1c
.RI "Uint32 \fBBmask\fP"
.br
.ti -1c
.RI "Uint32 \fBAmask\fP"
.br
.ti -1c
.RI "Uint8 \fBRloss\fP"
.br
.ti -1c
.RI "Uint8 \fBGloss\fP"
.br
.ti -1c
.RI "Uint8 \fBBloss\fP"
.br
.ti -1c
.RI "Uint8 \fBAloss\fP"
.br
.ti -1c
.RI "Uint8 \fBRshift\fP"
.br
.ti -1c
.RI "Uint8 \fBGshift\fP"
.br
.ti -1c
.RI "Uint8 \fBBshift\fP"
.br
.ti -1c
.RI "Uint8 \fBAshift\fP"
.br
.ti -1c
.RI "int \fBrefcount\fP"
.br
.ti -1c
.RI "struct \fBSDL_PixelFormat\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBNote\fP
.RS 4
Everything in the pixel format structure is read-only\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
