.TH "SDL_RendererInfo" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_RendererInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_render\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "Uint32 \fBflags\fP"
.br
.ti -1c
.RI "Uint32 \fBnum_texture_formats\fP"
.br
.ti -1c
.RI "Uint32 \fBtexture_formats\fP [16]"
.br
.ti -1c
.RI "int \fBmax_texture_width\fP"
.br
.ti -1c
.RI "int \fBmax_texture_height\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information on the capabilities of a render driver or context\&. 
.SH "Member Data Documentation"
.PP 
.SS "Uint32 SDL_RendererInfo::flags"
Supported SDL_RendererFlags 
.SS "int SDL_RendererInfo::max_texture_height"
The maximum texture height 
.SS "int SDL_RendererInfo::max_texture_width"
The maximum texture width 
.SS "const char* SDL_RendererInfo::name"
The name of the renderer 
.SS "Uint32 SDL_RendererInfo::num_texture_formats"
The number of available texture formats 
.SS "Uint32 SDL_RendererInfo::texture_formats[16]"
The available texture formats 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
