.TH "SDL_Vertex" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Vertex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_render\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSDL_FPoint\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBSDL_Color\fP \fBcolor\fP"
.br
.ti -1c
.RI "\fBSDL_FPoint\fP \fBtex_coord\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Vertex structure 
.SH "Member Data Documentation"
.PP 
.SS "\fBSDL_Color\fP SDL_Vertex::color"
Vertex color 
.SS "\fBSDL_FPoint\fP SDL_Vertex::position"
Vertex position, in SDL_Renderer coordinates 
.br
 
.SS "\fBSDL_FPoint\fP SDL_Vertex::tex_coord"
Normalized texture coordinates, if needed 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
