.TH "SDL_AudioSpec" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_AudioSpec
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_audio\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfreq\fP"
.br
.ti -1c
.RI "SDL_AudioFormat \fBformat\fP"
.br
.ti -1c
.RI "Uint8 \fBchannels\fP"
.br
.ti -1c
.RI "Uint8 \fBsilence\fP"
.br
.ti -1c
.RI "Uint16 \fBsamples\fP"
.br
.ti -1c
.RI "Uint16 \fBpadding\fP"
.br
.ti -1c
.RI "Uint32 \fBsize\fP"
.br
.ti -1c
.RI "SDL_AudioCallback \fBcallback\fP"
.br
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The calculated values in this structure are calculated by SDL_OpenAudio()\&.
.PP
For multi-channel audio, the default SDL channel mapping is: 2: FL FR (stereo) 3: FL FR LFE (2\&.1 surround) 4: FL FR BL BR (quad) 5: FL FR FC BL BR (quad + center) 6: FL FR FC LFE SL SR (5\&.1 surround - last two can also be BL BR) 7: FL FR FC LFE BC SL SR (6\&.1 surround) 8: FL FR FC LFE BL BR SL SR (7\&.1 surround) 
.SH "Member Data Documentation"
.PP 
.SS "SDL_AudioCallback SDL_AudioSpec::callback"
Callback that feeds the audio device (NULL to use SDL_QueueAudio())\&. 
.SS "Uint8 SDL_AudioSpec::channels"
Number of channels: 1 mono, 2 stereo 
.SS "SDL_AudioFormat SDL_AudioSpec::format"
Audio data format 
.SS "int SDL_AudioSpec::freq"
DSP frequency -- samples per second 
.SS "Uint16 SDL_AudioSpec::padding"
Necessary for some compile environments 
.SS "Uint16 SDL_AudioSpec::samples"
Audio buffer size in sample FRAMES (total samples divided by channel count) 
.SS "Uint8 SDL_AudioSpec::silence"
Audio buffer silence value (calculated) 
.SS "Uint32 SDL_AudioSpec::size"
Audio buffer size in bytes (calculated) 
.SS "void* SDL_AudioSpec::userdata"
Userdata passed to callback (ignored for NULL callbacks)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
