.TH "SDL_HapticPeriodic" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_HapticPeriodic \- \fBA\fP structure containing a template for a Periodic effect\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_haptic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint16 \fBtype\fP"
.br
.ti -1c
.RI "\fBSDL_HapticDirection\fP \fBdirection\fP"
.br
.ti -1c
.RI "Uint32 \fBlength\fP"
.br
.ti -1c
.RI "Uint16 \fBdelay\fP"
.br
.ti -1c
.RI "Uint16 \fBbutton\fP"
.br
.ti -1c
.RI "Uint16 \fBinterval\fP"
.br
.ti -1c
.RI "Uint16 \fBperiod\fP"
.br
.ti -1c
.RI "Sint16 \fBmagnitude\fP"
.br
.ti -1c
.RI "Sint16 \fBoffset\fP"
.br
.ti -1c
.RI "Uint16 \fBphase\fP"
.br
.ti -1c
.RI "Uint16 \fBattack_length\fP"
.br
.ti -1c
.RI "Uint16 \fBattack_level\fP"
.br
.ti -1c
.RI "Uint16 \fBfade_length\fP"
.br
.ti -1c
.RI "Uint16 \fBfade_level\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP structure containing a template for a Periodic effect\&. 

The struct handles the following effects:
.IP "\(bu" 2
SDL_HAPTIC_SINE
.IP "\(bu" 2
SDL_HAPTIC_LEFTRIGHT
.IP "\(bu" 2
SDL_HAPTIC_TRIANGLE
.IP "\(bu" 2
SDL_HAPTIC_SAWTOOTHUP
.IP "\(bu" 2
SDL_HAPTIC_SAWTOOTHDOWN
.PP
.PP
\fBA\fP periodic effect consists in a wave-shaped effect that repeats itself over time\&. The type determines the shape of the wave and the parameters determine the dimensions of the wave\&.
.PP
Phase is given by hundredth of a degree meaning that giving the phase a value of 9000 will displace it 25% of its period\&. Here are sample values:
.IP "\(bu" 2
0: No phase displacement\&.
.IP "\(bu" 2
9000: Displaced 25% of its period\&.
.IP "\(bu" 2
18000: Displaced 50% of its period\&.
.IP "\(bu" 2
27000: Displaced 75% of its period\&.
.IP "\(bu" 2
36000: Displaced 100% of its period, same as 0, but 0 is preferred\&.
.PP
.PP
Examples: 
.PP
.nf
SDL_HAPTIC_SINE
  __      __      __      __
 /  \\    /  \\    /  \\    /
/    \\__/    \\__/    \\__/

SDL_HAPTIC_SQUARE
 __    __    __    __    __
|  |  |  |  |  |  |  |  |  |
|  |__|  |__|  |__|  |__|  |

SDL_HAPTIC_TRIANGLE
  /\\    /\\    /\\    /\\    /\\
 /  \\  /  \\  /  \\  /  \\  /
/    \\/    \\/    \\/    \\/

SDL_HAPTIC_SAWTOOTHUP
  /|  /|  /|  /|  /|  /|  /|
 / | / | / | / | / | / | / |
/  |/  |/  |/  |/  |/  |/  |

SDL_HAPTIC_SAWTOOTHDOWN
\\  |\\  |\\  |\\  |\\  |\\  |\\  |
 \\ | \\ | \\ | \\ | \\ | \\ | \\ |
  \\|  \\|  \\|  \\|  \\|  \\|  \\|

.fi
.PP
.PP
\fBSee also\fP
.RS 4
SDL_HAPTIC_SINE 
.PP
SDL_HAPTIC_LEFTRIGHT 
.PP
SDL_HAPTIC_TRIANGLE 
.PP
SDL_HAPTIC_SAWTOOTHUP 
.PP
SDL_HAPTIC_SAWTOOTHDOWN 
.PP
\fBSDL_HapticEffect\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Uint16 SDL_HapticPeriodic::attack_length"
Duration of the attack\&. 
.SS "Uint16 SDL_HapticPeriodic::attack_level"
Level at the start of the attack\&. 
.SS "Uint16 SDL_HapticPeriodic::button"
Button that triggers the effect\&. 
.SS "Uint16 SDL_HapticPeriodic::delay"
Delay before starting the effect\&. 
.SS "\fBSDL_HapticDirection\fP SDL_HapticPeriodic::direction"
Direction of the effect\&. 
.SS "Uint16 SDL_HapticPeriodic::fade_length"
Duration of the fade\&. 
.SS "Uint16 SDL_HapticPeriodic::fade_level"
Level at the end of the fade\&. 
.SS "Uint16 SDL_HapticPeriodic::interval"
How soon it can be triggered again after button\&. 
.SS "Uint32 SDL_HapticPeriodic::length"
Duration of the effect\&. 
.SS "Sint16 SDL_HapticPeriodic::magnitude"
Peak value; if negative, equivalent to 180 degrees extra phase shift\&. 
.SS "Sint16 SDL_HapticPeriodic::offset"
Mean value of the wave\&. 
.SS "Uint16 SDL_HapticPeriodic::period"
Period of the wave\&. 
.SS "Uint16 SDL_HapticPeriodic::phase"
Positive phase shift given by hundredth of a degree\&. 
.SS "Uint16 SDL_HapticPeriodic::type"
SDL_HAPTIC_SINE, SDL_HAPTIC_LEFTRIGHT, SDL_HAPTIC_TRIANGLE, SDL_HAPTIC_SAWTOOTHUP or SDL_HAPTIC_SAWTOOTHDOWN 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
