.TH "SDL_MessageBoxData" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MessageBoxData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_messagebox\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBflags\fP"
.br
.ti -1c
.RI "SDL_Window * \fBwindow\fP"
.br
.ti -1c
.RI "const char * \fBtitle\fP"
.br
.ti -1c
.RI "const char * \fBmessage\fP"
.br
.ti -1c
.RI "int \fBnumbuttons\fP"
.br
.ti -1c
.RI "const \fBSDL_MessageBoxButtonData\fP * \fBbuttons\fP"
.br
.ti -1c
.RI "const \fBSDL_MessageBoxColorScheme\fP * \fBcolorScheme\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MessageBox structure containing title, text, window, etc\&. 
.SH "Member Data Documentation"
.PP 
.SS "const \fBSDL_MessageBoxColorScheme\fP* SDL_MessageBoxData::colorScheme"
\fBSDL_MessageBoxColorScheme\fP, can be NULL to use system settings 
.SS "Uint32 SDL_MessageBoxData::flags"
SDL_MessageBoxFlags 
.SS "const char* SDL_MessageBoxData::message"
UTF-8 message text 
.SS "const char* SDL_MessageBoxData::title"
UTF-8 title 
.SS "SDL_Window* SDL_MessageBoxData::window"
Parent window, can be NULL 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
