.TH "SDL_Point" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Point
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_rect\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The structure that defines a point (integer)
.PP
\fBSee also\fP
.RS 4
SDL_EnclosePoints 
.PP
SDL_PointInRect 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
