.TH "SDL_MessageBoxButtonData" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MessageBoxButtonData
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_messagebox\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBflags\fP"
.br
.ti -1c
.RI "int \fBbuttonid\fP"
.br
.ti -1c
.RI "const char * \fBtext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Individual button data\&. 
.SH "Member Data Documentation"
.PP 
.SS "int SDL_MessageBoxButtonData::buttonid"
User defined button id (value returned via SDL_ShowMessageBox) 
.SS "Uint32 SDL_MessageBoxButtonData::flags"
SDL_MessageBoxButtonFlags 
.SS "const char* SDL_MessageBoxButtonData::text"
The UTF-8 button text 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
