.TH "SDL_AssertData" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_AssertData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBalways_ignore\fP"
.br
.ti -1c
.RI "unsigned int \fBtrigger_count\fP"
.br
.ti -1c
.RI "const char * \fBcondition\fP"
.br
.ti -1c
.RI "const char * \fBfilename\fP"
.br
.ti -1c
.RI "int \fBlinenum\fP"
.br
.ti -1c
.RI "const char * \fBfunction\fP"
.br
.ti -1c
.RI "const struct \fBSDL_AssertData\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
