.TH "SDL_SysWMmsg" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_SysWMmsg
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_syswm\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSDL_version\fP \fBversion\fP"
.br
.ti -1c
.RI "SDL_SYSWM_TYPE \fBsubsystem\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      HWND \fBhwnd\fP"
.br
.ti -1c
.RI "      UINT \fBmsg\fP"
.br
.ti -1c
.RI "      WPARAM \fBwParam\fP"
.br
.ti -1c
.RI "      LPARAM \fBlParam\fP"
.br
.ti -1c
.RI "   } \fBwin\fP"
.br
.ti -1c
.RI "   int \fBdummy\fP"
.br
.ti -1c
.RI "} \fBmsg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The custom event structure\&. 
.SH "Member Data Documentation"
.PP 
.SS "HWND SDL_SysWMmsg::hwnd"
The window for the message 
.SS "LPARAM SDL_SysWMmsg::lParam"
LONG message parameter 
.SS "UINT SDL_SysWMmsg::msg"
The type of message 
.SS "WPARAM SDL_SysWMmsg::wParam"
WORD message parameter 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
