.TH "SDL_DisplayMode" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_DisplayMode \- The structure that defines a display mode\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_video\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBformat\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "int \fBrefresh_rate\fP"
.br
.ti -1c
.RI "void * \fBdriverdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The structure that defines a display mode\&. 


.PP
\fBSee also\fP
.RS 4
SDL_GetNumDisplayModes() 
.PP
SDL_GetDisplayMode() 
.PP
SDL_GetDesktopDisplayMode() 
.PP
SDL_GetCurrentDisplayMode() 
.PP
SDL_GetClosestDisplayMode() 
.PP
SDL_SetWindowDisplayMode() 
.PP
SDL_GetWindowDisplayMode() 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "void* SDL_DisplayMode::driverdata"
driver-specific data, initialize to 0 
.SS "Uint32 SDL_DisplayMode::format"
pixel format 
.SS "int SDL_DisplayMode::h"
height, in screen coordinates 
.SS "int SDL_DisplayMode::refresh_rate"
refresh rate (or zero for unspecified) 
.SS "int SDL_DisplayMode::w"
width, in screen coordinates 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
