.TH "SDL_Color" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Color
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_pixels\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint8 \fBr\fP"
.br
.ti -1c
.RI "Uint8 \fBg\fP"
.br
.ti -1c
.RI "Uint8 \fBb\fP"
.br
.ti -1c
.RI "Uint8 \fBa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The bits of this structure can be directly reinterpreted as an integer-packed color which uses the SDL_PIXELFORMAT_RGBA32 format (SDL_PIXELFORMAT_ABGR8888 on little-endian systems and SDL_PIXELFORMAT_RGBA8888 on big-endian systems)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
