.TH "SDL_WindowEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_WindowEvent \- Window state change event data (event\&.window\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "Uint32 \fBwindowID\fP"
.br
.ti -1c
.RI "Uint8 \fBevent\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding1\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding2\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding3\fP"
.br
.ti -1c
.RI "Sint32 \fBdata1\fP"
.br
.ti -1c
.RI "Sint32 \fBdata2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Window state change event data (event\&.window\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Sint32 SDL_WindowEvent::data1"
event dependent data 
.SS "Sint32 SDL_WindowEvent::data2"
event dependent data 
.SS "Uint8 SDL_WindowEvent::event"
SDL_WindowEventID 
.SS "Uint32 SDL_WindowEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_WindowEvent::type"
SDL_WINDOWEVENT 
.SS "Uint32 SDL_WindowEvent::windowID"
The associated window 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
