.TH "SDL_HapticCondition" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_HapticCondition \- \fBA\fP structure containing a template for a Condition effect\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_haptic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint16 \fBtype\fP"
.br
.ti -1c
.RI "\fBSDL_HapticDirection\fP \fBdirection\fP"
.br
.ti -1c
.RI "Uint32 \fBlength\fP"
.br
.ti -1c
.RI "Uint16 \fBdelay\fP"
.br
.ti -1c
.RI "Uint16 \fBbutton\fP"
.br
.ti -1c
.RI "Uint16 \fBinterval\fP"
.br
.ti -1c
.RI "Uint16 \fBright_sat\fP [3]"
.br
.ti -1c
.RI "Uint16 \fBleft_sat\fP [3]"
.br
.ti -1c
.RI "Sint16 \fBright_coeff\fP [3]"
.br
.ti -1c
.RI "Sint16 \fBleft_coeff\fP [3]"
.br
.ti -1c
.RI "Uint16 \fBdeadband\fP [3]"
.br
.ti -1c
.RI "Sint16 \fBcenter\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP structure containing a template for a Condition effect\&. 

The struct handles the following effects:
.IP "\(bu" 2
SDL_HAPTIC_SPRING: Effect based on axes position\&.
.IP "\(bu" 2
SDL_HAPTIC_DAMPER: Effect based on axes velocity\&.
.IP "\(bu" 2
SDL_HAPTIC_INERTIA: Effect based on axes acceleration\&.
.IP "\(bu" 2
SDL_HAPTIC_FRICTION: Effect based on axes movement\&.
.PP
.PP
Direction is handled by condition internals instead of a direction member\&. The condition effect specific members have three parameters\&. The first refers to the X axis, the second refers to the Y axis and the third refers to the Z axis\&. The right terms refer to the positive side of the axis and the left terms refer to the negative side of the axis\&. Please refer to the \fBSDL_HapticDirection\fP diagram for which side is positive and which is negative\&.
.PP
\fBSee also\fP
.RS 4
\fBSDL_HapticDirection\fP 
.PP
SDL_HAPTIC_SPRING 
.PP
SDL_HAPTIC_DAMPER 
.PP
SDL_HAPTIC_INERTIA 
.PP
SDL_HAPTIC_FRICTION 
.PP
\fBSDL_HapticEffect\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Uint16 SDL_HapticCondition::button"
Button that triggers the effect\&. 
.SS "Sint16 SDL_HapticCondition::center[3]"
Position of the dead zone\&. 
.SS "Uint16 SDL_HapticCondition::deadband[3]"
Size of the dead zone; max 0xFFFF: whole axis-range when 0-centered\&. 
.SS "Uint16 SDL_HapticCondition::delay"
Delay before starting the effect\&. 
.SS "\fBSDL_HapticDirection\fP SDL_HapticCondition::direction"
Direction of the effect - Not used ATM\&. 
.SS "Uint16 SDL_HapticCondition::interval"
How soon it can be triggered again after button\&. 
.SS "Sint16 SDL_HapticCondition::left_coeff[3]"
How fast to increase the force towards the negative side\&. 
.SS "Uint16 SDL_HapticCondition::left_sat[3]"
Level when joystick is to the negative side; max 0xFFFF\&. 
.SS "Uint32 SDL_HapticCondition::length"
Duration of the effect\&. 
.SS "Sint16 SDL_HapticCondition::right_coeff[3]"
How fast to increase the force towards the positive side\&. 
.SS "Uint16 SDL_HapticCondition::right_sat[3]"
Level when joystick is to the positive side; max 0xFFFF\&. 
.SS "Uint16 SDL_HapticCondition::type"
SDL_HAPTIC_SPRING, SDL_HAPTIC_DAMPER, SDL_HAPTIC_INERTIA or SDL_HAPTIC_FRICTION 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
