.TH "SDL_MouseButtonEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MouseButtonEvent \- Mouse button event structure (event\&.button\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "Uint32 \fBwindowID\fP"
.br
.ti -1c
.RI "Uint32 \fBwhich\fP"
.br
.ti -1c
.RI "Uint8 \fBbutton\fP"
.br
.ti -1c
.RI "Uint8 \fBstate\fP"
.br
.ti -1c
.RI "Uint8 \fBclicks\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding1\fP"
.br
.ti -1c
.RI "Sint32 \fBx\fP"
.br
.ti -1c
.RI "Sint32 \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Mouse button event structure (event\&.button\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint8 SDL_MouseButtonEvent::button"
The mouse button index 
.SS "Uint8 SDL_MouseButtonEvent::clicks"
1 for single-click, 2 for double-click, etc\&. 
.SS "Uint8 SDL_MouseButtonEvent::state"
SDL_PRESSED or SDL_RELEASED 
.SS "Uint32 SDL_MouseButtonEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_MouseButtonEvent::type"
SDL_MOUSEBUTTONDOWN or SDL_MOUSEBUTTONUP 
.SS "Uint32 SDL_MouseButtonEvent::which"
The mouse instance id, or SDL_TOUCH_MOUSEID 
.SS "Uint32 SDL_MouseButtonEvent::windowID"
The window with mouse focus, if any 
.SS "Sint32 SDL_MouseButtonEvent::x"
X coordinate, relative to window 
.SS "Sint32 SDL_MouseButtonEvent::y"
Y coordinate, relative to window 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
