.TH "SDL_SysWMinfo" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_SysWMinfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_syswm\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSDL_version\fP \fBversion\fP"
.br
.ti -1c
.RI "SDL_SYSWM_TYPE \fBsubsystem\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      HWND \fBwindow\fP"
.br
.ti -1c
.RI "      HDC \fBhdc\fP"
.br
.ti -1c
.RI "      HINSTANCE \fBhinstance\fP"
.br
.ti -1c
.RI "   } \fBwin\fP"
.br
.ti -1c
.RI "   Uint8 \fBdummy\fP [64]"
.br
.ti -1c
.RI "} \fBinfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The custom window manager information structure\&.
.PP
When this structure is returned, it holds information about which low level system it is using, and will be one of SDL_SYSWM_TYPE\&. 
.SH "Member Data Documentation"
.PP 
.SS "HDC SDL_SysWMinfo::hdc"
The window device context 
.SS "HINSTANCE SDL_SysWMinfo::hinstance"
The instance handle 
.SS "HWND SDL_SysWMinfo::window"
The window handle 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
