.TH "SDL_TextInputEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_TextInputEvent \- Keyboard text input event structure (event\&.text\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "Uint32 \fBwindowID\fP"
.br
.ti -1c
.RI "char \fBtext\fP [SDL_TEXTINPUTEVENT_TEXT_SIZE]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Keyboard text input event structure (event\&.text\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "char SDL_TextInputEvent::text[SDL_TEXTINPUTEVENT_TEXT_SIZE]"
The input text 
.SS "Uint32 SDL_TextInputEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_TextInputEvent::type"
SDL_TEXTINPUT 
.SS "Uint32 SDL_TextInputEvent::windowID"
The window with keyboard focus, if any 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
