.TH "SDL_ControllerTouchpadEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_ControllerTouchpadEvent \- Game controller touchpad event structure (event\&.ctouchpad\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "SDL_JoystickID \fBwhich\fP"
.br
.ti -1c
.RI "Sint32 \fBtouchpad\fP"
.br
.ti -1c
.RI "Sint32 \fBfinger\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBpressure\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Game controller touchpad event structure (event\&.ctouchpad\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Sint32 SDL_ControllerTouchpadEvent::finger"
The index of the finger on the touchpad 
.SS "float SDL_ControllerTouchpadEvent::pressure"
Normalized in the range 0\&.\&.\&.1 
.SS "Uint32 SDL_ControllerTouchpadEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Sint32 SDL_ControllerTouchpadEvent::touchpad"
The index of the touchpad 
.SS "Uint32 SDL_ControllerTouchpadEvent::type"
SDL_CONTROLLERTOUCHPADDOWN or SDL_CONTROLLERTOUCHPADMOTION or SDL_CONTROLLERTOUCHPADUP 
.SS "SDL_JoystickID SDL_ControllerTouchpadEvent::which"
The joystick instance id 
.SS "float SDL_ControllerTouchpadEvent::x"
Normalized in the range 0\&.\&.\&.1 with 0 being on the left 
.SS "float SDL_ControllerTouchpadEvent::y"
Normalized in the range 0\&.\&.\&.1 with 0 being at the top 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
