.TH "SDL_Locale" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Locale
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBlanguage\fP"
.br
.ti -1c
.RI "const char * \fBcountry\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const char* SDL_Locale::country"
\fBA\fP country, like 'US' for America\&. Can be NULL\&. 
.SS "const char* SDL_Locale::language"
\fBA\fP language name, like 'en' for English\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
