.TH "SDL_ControllerDeviceEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_ControllerDeviceEvent \- Controller device event structure (event\&.cdevice\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "Sint32 \fBwhich\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Controller device event structure (event\&.cdevice\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint32 SDL_ControllerDeviceEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_ControllerDeviceEvent::type"
SDL_CONTROLLERDEVICEADDED, SDL_CONTROLLERDEVICEREMOVED, or SDL_CONTROLLERDEVICEREMAPPED 
.SS "Sint32 SDL_ControllerDeviceEvent::which"
The joystick device index for the ADDED event, instance id for the REMOVED or REMAPPED event 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
