.TH "SDL_FRect" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_FRect
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_rect\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBw\fP"
.br
.ti -1c
.RI "float \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP rectangle, with the origin at the upper left (floating point)\&.
.PP
\fBSee also\fP
.RS 4
SDL_FRectEmpty 
.PP
SDL_FRectEquals 
.PP
SDL_FRectEqualsEpsilon 
.PP
SDL_HasIntersectionF 
.PP
SDL_IntersectFRect 
.PP
SDL_IntersectFRectAndLine 
.PP
SDL_UnionFRect 
.PP
SDL_EncloseFPoints 
.PP
SDL_PointInFRect 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
