.TH "SDL_WindowShapeMode" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_WindowShapeMode \- \fBA\fP struct that tags the \fBSDL_WindowShapeParams\fP union with an enum describing the type of its contents\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_shape\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "WindowShapeMode \fBmode\fP"
.br
.RI "The mode of these window-shape parameters\&. "
.ti -1c
.RI "\fBSDL_WindowShapeParams\fP \fBparameters\fP"
.br
.RI "Window-shape parameters\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP struct that tags the \fBSDL_WindowShapeParams\fP union with an enum describing the type of its contents\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
