.TH "SDL_ControllerButtonEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_ControllerButtonEvent \- Game controller button event structure (event\&.cbutton\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "SDL_JoystickID \fBwhich\fP"
.br
.ti -1c
.RI "Uint8 \fBbutton\fP"
.br
.ti -1c
.RI "Uint8 \fBstate\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding1\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Game controller button event structure (event\&.cbutton\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint8 SDL_ControllerButtonEvent::button"
The controller button (SDL_GameControllerButton) 
.SS "Uint8 SDL_ControllerButtonEvent::state"
SDL_PRESSED or SDL_RELEASED 
.SS "Uint32 SDL_ControllerButtonEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_ControllerButtonEvent::type"
SDL_CONTROLLERBUTTONDOWN or SDL_CONTROLLERBUTTONUP 
.SS "SDL_JoystickID SDL_ControllerButtonEvent::which"
The joystick instance id 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
