.TH "SDL_HapticRamp" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_HapticRamp \- \fBA\fP structure containing a template for a Ramp effect\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_haptic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint16 \fBtype\fP"
.br
.ti -1c
.RI "\fBSDL_HapticDirection\fP \fBdirection\fP"
.br
.ti -1c
.RI "Uint32 \fBlength\fP"
.br
.ti -1c
.RI "Uint16 \fBdelay\fP"
.br
.ti -1c
.RI "Uint16 \fBbutton\fP"
.br
.ti -1c
.RI "Uint16 \fBinterval\fP"
.br
.ti -1c
.RI "Sint16 \fBstart\fP"
.br
.ti -1c
.RI "Sint16 \fBend\fP"
.br
.ti -1c
.RI "Uint16 \fBattack_length\fP"
.br
.ti -1c
.RI "Uint16 \fBattack_level\fP"
.br
.ti -1c
.RI "Uint16 \fBfade_length\fP"
.br
.ti -1c
.RI "Uint16 \fBfade_level\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP structure containing a template for a Ramp effect\&. 

This struct is exclusively for the SDL_HAPTIC_RAMP effect\&.
.PP
The ramp effect starts at start strength and ends at end strength\&. It augments in linear fashion\&. If you use attack and fade with a ramp the effects get added to the ramp effect making the effect become quadratic instead of linear\&.
.PP
\fBSee also\fP
.RS 4
SDL_HAPTIC_RAMP 
.PP
\fBSDL_HapticEffect\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Uint16 SDL_HapticRamp::attack_length"
Duration of the attack\&. 
.SS "Uint16 SDL_HapticRamp::attack_level"
Level at the start of the attack\&. 
.SS "Uint16 SDL_HapticRamp::button"
Button that triggers the effect\&. 
.SS "Uint16 SDL_HapticRamp::delay"
Delay before starting the effect\&. 
.SS "\fBSDL_HapticDirection\fP SDL_HapticRamp::direction"
Direction of the effect\&. 
.SS "Sint16 SDL_HapticRamp::end"
Ending strength level\&. 
.SS "Uint16 SDL_HapticRamp::fade_length"
Duration of the fade\&. 
.SS "Uint16 SDL_HapticRamp::fade_level"
Level at the end of the fade\&. 
.SS "Uint16 SDL_HapticRamp::interval"
How soon it can be triggered again after button\&. 
.SS "Uint32 SDL_HapticRamp::length"
Duration of the effect\&. 
.SS "Sint16 SDL_HapticRamp::start"
Beginning strength level\&. 
.SS "Uint16 SDL_HapticRamp::type"
SDL_HAPTIC_RAMP 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
