.TH "SDL_version" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_version
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_version\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint8 \fBmajor\fP"
.br
.ti -1c
.RI "Uint8 \fBminor\fP"
.br
.ti -1c
.RI "Uint8 \fBpatch\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information about the version of SDL in use\&.
.PP
Represents the library's version as three levels: major revision (increments with massive changes, additions, and enhancements), minor revision (increments with backwards-compatible changes to the major revision), and patchlevel (increments with fixes to the minor revision)\&.
.PP
\fBSee also\fP
.RS 4
SDL_VERSION 
.PP
SDL_GetVersion 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Uint8 SDL_version::major"
major version 
.SS "Uint8 SDL_version::minor"
minor version 
.SS "Uint8 SDL_version::patch"
update version 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
