.TH "SDL_atomic_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_atomic_t \- \fBA\fP type representing an atomic integer value\&. It is a struct so people don't accidentally use numeric operations on it\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_atomic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP type representing an atomic integer value\&. It is a struct so people don't accidentally use numeric operations on it\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
