.TH "SDL_JoyAxisEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_JoyAxisEvent \- Joystick axis motion event structure (event\&.jaxis\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "SDL_JoystickID \fBwhich\fP"
.br
.ti -1c
.RI "Uint8 \fBaxis\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding1\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding2\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding3\fP"
.br
.ti -1c
.RI "Sint16 \fBvalue\fP"
.br
.ti -1c
.RI "Uint16 \fBpadding4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Joystick axis motion event structure (event\&.jaxis\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint8 SDL_JoyAxisEvent::axis"
The joystick axis index 
.SS "Uint32 SDL_JoyAxisEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_JoyAxisEvent::type"
SDL_JOYAXISMOTION 
.SS "Sint16 SDL_JoyAxisEvent::value"
The axis value (range: -32768 to 32767) 
.SS "SDL_JoystickID SDL_JoyAxisEvent::which"
The joystick instance id 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
