.TH "SDL_GameControllerButtonBind" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_GameControllerButtonBind
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_gamecontroller\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SDL_GameControllerBindType \fBbindType\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   int \fBbutton\fP"
.br
.ti -1c
.RI "   int \fBaxis\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBhat\fP"
.br
.ti -1c
.RI "      int \fBhat_mask\fP"
.br
.ti -1c
.RI "   } \fBhat\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Get the SDL joystick layer binding for this controller button/axis mapping 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
