.TH "SDL_TextEditingEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_TextEditingEvent \- Keyboard text editing event structure (event\&.edit\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "Uint32 \fBwindowID\fP"
.br
.ti -1c
.RI "char \fBtext\fP [SDL_TEXTEDITINGEVENT_TEXT_SIZE]"
.br
.ti -1c
.RI "Sint32 \fBstart\fP"
.br
.ti -1c
.RI "Sint32 \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Keyboard text editing event structure (event\&.edit\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Sint32 SDL_TextEditingEvent::length"
The length of selected editing text 
.SS "Sint32 SDL_TextEditingEvent::start"
The start cursor of selected editing text 
.SS "char SDL_TextEditingEvent::text[SDL_TEXTEDITINGEVENT_TEXT_SIZE]"
The editing text 
.SS "Uint32 SDL_TextEditingEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_TextEditingEvent::type"
SDL_TEXTEDITING 
.SS "Uint32 SDL_TextEditingEvent::windowID"
The window with keyboard focus, if any 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
