.TH "SDL_WindowShapeParams" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_WindowShapeParams \- \fBA\fP union containing parameters for shaped windows\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_shape\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint8 \fBbinarizationCutoff\fP"
.br
.RI "\fBA\fP cutoff alpha value for binarization of the window shape's alpha channel\&. "
.ti -1c
.RI "\fBSDL_Color\fP \fBcolorKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP union containing parameters for shaped windows\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
