.TH "SDL_KeyboardEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_KeyboardEvent \- Keyboard button event structure (event\&.key\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "Uint32 \fBwindowID\fP"
.br
.ti -1c
.RI "Uint8 \fBstate\fP"
.br
.ti -1c
.RI "Uint8 \fBrepeat\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding2\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding3\fP"
.br
.ti -1c
.RI "\fBSDL_Keysym\fP \fBkeysym\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Keyboard button event structure (event\&.key\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "\fBSDL_Keysym\fP SDL_KeyboardEvent::keysym"
The key that was pressed or released 
.SS "Uint8 SDL_KeyboardEvent::repeat"
Non-zero if this is a key repeat 
.SS "Uint8 SDL_KeyboardEvent::state"
SDL_PRESSED or SDL_RELEASED 
.SS "Uint32 SDL_KeyboardEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_KeyboardEvent::type"
SDL_KEYDOWN or SDL_KEYUP 
.SS "Uint32 SDL_KeyboardEvent::windowID"
The window with keyboard focus, if any 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
