.TH "SDL_HapticConstant" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_HapticConstant \- \fBA\fP structure containing a template for a Constant effect\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_haptic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint16 \fBtype\fP"
.br
.ti -1c
.RI "\fBSDL_HapticDirection\fP \fBdirection\fP"
.br
.ti -1c
.RI "Uint32 \fBlength\fP"
.br
.ti -1c
.RI "Uint16 \fBdelay\fP"
.br
.ti -1c
.RI "Uint16 \fBbutton\fP"
.br
.ti -1c
.RI "Uint16 \fBinterval\fP"
.br
.ti -1c
.RI "Sint16 \fBlevel\fP"
.br
.ti -1c
.RI "Uint16 \fBattack_length\fP"
.br
.ti -1c
.RI "Uint16 \fBattack_level\fP"
.br
.ti -1c
.RI "Uint16 \fBfade_length\fP"
.br
.ti -1c
.RI "Uint16 \fBfade_level\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP structure containing a template for a Constant effect\&. 

This struct is exclusively for the SDL_HAPTIC_CONSTANT effect\&.
.PP
\fBA\fP constant effect applies a constant force in the specified direction to the joystick\&.
.PP
\fBSee also\fP
.RS 4
SDL_HAPTIC_CONSTANT 
.PP
\fBSDL_HapticEffect\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "Uint16 SDL_HapticConstant::attack_length"
Duration of the attack\&. 
.SS "Uint16 SDL_HapticConstant::attack_level"
Level at the start of the attack\&. 
.SS "Uint16 SDL_HapticConstant::button"
Button that triggers the effect\&. 
.SS "Uint16 SDL_HapticConstant::delay"
Delay before starting the effect\&. 
.SS "\fBSDL_HapticDirection\fP SDL_HapticConstant::direction"
Direction of the effect\&. 
.SS "Uint16 SDL_HapticConstant::fade_length"
Duration of the fade\&. 
.SS "Uint16 SDL_HapticConstant::fade_level"
Level at the end of the fade\&. 
.SS "Uint16 SDL_HapticConstant::interval"
How soon it can be triggered again after button\&. 
.SS "Uint32 SDL_HapticConstant::length"
Duration of the effect\&. 
.SS "Sint16 SDL_HapticConstant::level"
Strength of the constant effect\&. 
.SS "Uint16 SDL_HapticConstant::type"
SDL_HAPTIC_CONSTANT 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
