.TH "SDL_OSEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_OSEvent \- OS Specific event\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
OS Specific event\&. 
.SH "Member Data Documentation"
.PP 
.SS "Uint32 SDL_OSEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_OSEvent::type"
SDL_QUIT 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
