.TH "SDL_JoyHatEvent" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_JoyHatEvent \- Joystick hat position change event structure (event\&.jhat\&.*)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_events\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Uint32 \fBtype\fP"
.br
.ti -1c
.RI "Uint32 \fBtimestamp\fP"
.br
.ti -1c
.RI "SDL_JoystickID \fBwhich\fP"
.br
.ti -1c
.RI "Uint8 \fBhat\fP"
.br
.ti -1c
.RI "Uint8 \fBvalue\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding1\fP"
.br
.ti -1c
.RI "Uint8 \fBpadding2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Joystick hat position change event structure (event\&.jhat\&.*) 
.SH "Member Data Documentation"
.PP 
.SS "Uint8 SDL_JoyHatEvent::hat"
The joystick hat index 
.SS "Uint32 SDL_JoyHatEvent::timestamp"
In milliseconds, populated using SDL_GetTicks() 
.SS "Uint32 SDL_JoyHatEvent::type"
SDL_JOYHATMOTION 
.SS "Uint8 SDL_JoyHatEvent::value"
The hat position value\&. 
.PP
\fBSee also\fP
.RS 4
SDL_HAT_LEFTUP SDL_HAT_UP SDL_HAT_RIGHTUP 
.PP
SDL_HAT_LEFT SDL_HAT_CENTERED SDL_HAT_RIGHT 
.PP
SDL_HAT_LEFTDOWN SDL_HAT_DOWN SDL_HAT_RIGHTDOWN
.RE
.PP
Note that zero means the POV is centered\&. 
.SS "SDL_JoystickID SDL_JoyHatEvent::which"
The joystick instance id 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
