.TH "SDLTest_TestSuiteReference" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLTest_TestSuiteReference
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_test_harness\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "SDLTest_TestCaseSetUpFp \fBtestSetUp\fP"
.br
.ti -1c
.RI "const \fBSDLTest_TestCaseReference\fP ** \fBtestCases\fP"
.br
.ti -1c
.RI "SDLTest_TestCaseTearDownFp \fBtestTearDown\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds information about a test suite (multiple test cases)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
