.TH "SDLTest_TestCaseReference" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLTest_TestCaseReference
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_test_harness\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SDLTest_TestCaseFp \fBtestCase\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBdescription\fP"
.br
.ti -1c
.RI "int \fBenabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds information about a single test case\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
