.TH "SDLTest_CommonState" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLTest_CommonState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char ** \fBargv\fP"
.br
.ti -1c
.RI "Uint32 \fBflags\fP"
.br
.ti -1c
.RI "Uint32 \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBvideodriver\fP"
.br
.ti -1c
.RI "int \fBdisplay\fP"
.br
.ti -1c
.RI "const char * \fBwindow_title\fP"
.br
.ti -1c
.RI "const char * \fBwindow_icon\fP"
.br
.ti -1c
.RI "Uint32 \fBwindow_flags\fP"
.br
.ti -1c
.RI "SDL_bool \fBflash_on_focus_loss\fP"
.br
.ti -1c
.RI "int \fBwindow_x\fP"
.br
.ti -1c
.RI "int \fBwindow_y\fP"
.br
.ti -1c
.RI "int \fBwindow_w\fP"
.br
.ti -1c
.RI "int \fBwindow_h\fP"
.br
.ti -1c
.RI "int \fBwindow_minW\fP"
.br
.ti -1c
.RI "int \fBwindow_minH\fP"
.br
.ti -1c
.RI "int \fBwindow_maxW\fP"
.br
.ti -1c
.RI "int \fBwindow_maxH\fP"
.br
.ti -1c
.RI "int \fBlogical_w\fP"
.br
.ti -1c
.RI "int \fBlogical_h\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "int \fBrefresh_rate\fP"
.br
.ti -1c
.RI "int \fBnum_windows\fP"
.br
.ti -1c
.RI "SDL_Window ** \fBwindows\fP"
.br
.ti -1c
.RI "const char * \fBrenderdriver\fP"
.br
.ti -1c
.RI "Uint32 \fBrender_flags\fP"
.br
.ti -1c
.RI "SDL_bool \fBskip_renderer\fP"
.br
.ti -1c
.RI "SDL_Renderer ** \fBrenderers\fP"
.br
.ti -1c
.RI "SDL_Texture ** \fBtargets\fP"
.br
.ti -1c
.RI "const char * \fBaudiodriver\fP"
.br
.ti -1c
.RI "\fBSDL_AudioSpec\fP \fBaudiospec\fP"
.br
.ti -1c
.RI "int \fBgl_red_size\fP"
.br
.ti -1c
.RI "int \fBgl_green_size\fP"
.br
.ti -1c
.RI "int \fBgl_blue_size\fP"
.br
.ti -1c
.RI "int \fBgl_alpha_size\fP"
.br
.ti -1c
.RI "int \fBgl_buffer_size\fP"
.br
.ti -1c
.RI "int \fBgl_depth_size\fP"
.br
.ti -1c
.RI "int \fBgl_stencil_size\fP"
.br
.ti -1c
.RI "int \fBgl_double_buffer\fP"
.br
.ti -1c
.RI "int \fBgl_accum_red_size\fP"
.br
.ti -1c
.RI "int \fBgl_accum_green_size\fP"
.br
.ti -1c
.RI "int \fBgl_accum_blue_size\fP"
.br
.ti -1c
.RI "int \fBgl_accum_alpha_size\fP"
.br
.ti -1c
.RI "int \fBgl_stereo\fP"
.br
.ti -1c
.RI "int \fBgl_multisamplebuffers\fP"
.br
.ti -1c
.RI "int \fBgl_multisamplesamples\fP"
.br
.ti -1c
.RI "int \fBgl_retained_backing\fP"
.br
.ti -1c
.RI "int \fBgl_accelerated\fP"
.br
.ti -1c
.RI "int \fBgl_major_version\fP"
.br
.ti -1c
.RI "int \fBgl_minor_version\fP"
.br
.ti -1c
.RI "int \fBgl_debug\fP"
.br
.ti -1c
.RI "int \fBgl_profile_mask\fP"
.br
.ti -1c
.RI "\fBSDL_Rect\fP \fBconfine\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
