.TH "SegmentJob" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SegmentJob
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWebPWorker\fP \fBworker\fP"
.br
.ti -1c
.RI "int \fBalphas\fP [MAX_ALPHA+1]"
.br
.ti -1c
.RI "int \fBalpha\fP"
.br
.ti -1c
.RI "int \fBuv_alpha\fP"
.br
.ti -1c
.RI "\fBVP8EncIterator\fP \fBit\fP"
.br
.ti -1c
.RI "int \fBdelta_progress\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
