.TH "SequenceTestingListener" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SequenceTestingListener
.SH SYNOPSIS
.br
.PP
.PP
Inherits testing::EmptyTestEventListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSequenceTestingListener\fP (std::vector< std::string > *vector, const char *id)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnTestProgramStart\fP (const UnitTest &) override"
.br
.ti -1c
.RI "void \fBOnTestProgramEnd\fP (const UnitTest &) override"
.br
.ti -1c
.RI "void \fBOnTestIterationStart\fP (const UnitTest &, int) override"
.br
.ti -1c
.RI "void \fBOnTestIterationEnd\fP (const UnitTest &, int) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
