.TH "SetupFailTest" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SetupFailTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtesting::Test\fP\&.
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetUpTestSuite\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBtesting::Test\fP
.in +1c
.ti -1c
.RI "static void \fBSetUpTestSuite\fP ()"
.br
.ti -1c
.RI "static void \fBTearDownTestSuite\fP ()"
.br
.ti -1c
.RI "static void \fBTearDownTestCase\fP ()"
.br
.ti -1c
.RI "static void \fBSetUpTestCase\fP ()"
.br
.ti -1c
.RI "static bool \fBHasFatalFailure\fP ()"
.br
.ti -1c
.RI "static bool \fBHasNonfatalFailure\fP ()"
.br
.ti -1c
.RI "static bool \fBIsSkipped\fP ()"
.br
.ti -1c
.RI "static bool \fBHasFailure\fP ()"
.br
.ti -1c
.RI "static void \fBRecordProperty\fP (const std::string &key, const std::string &\fBvalue\fP)"
.br
.ti -1c
.RI "static void \fBRecordProperty\fP (const std::string &key, int64_t \fBvalue\fP)"
.br
.ti -1c
.RI "static void \fBSetUpTestSuite\fP ()"
.br
.ti -1c
.RI "static void \fBTearDownTestSuite\fP ()"
.br
.ti -1c
.RI "static void \fBTearDownTestCase\fP ()"
.br
.ti -1c
.RI "static void \fBSetUpTestCase\fP ()"
.br
.ti -1c
.RI "static bool \fBHasFatalFailure\fP ()"
.br
.ti -1c
.RI "static bool \fBHasNonfatalFailure\fP ()"
.br
.ti -1c
.RI "static bool \fBIsSkipped\fP ()"
.br
.ti -1c
.RI "static bool \fBHasFailure\fP ()"
.br
.ti -1c
.RI "static void \fBRecordProperty\fP (const std::string &key, const std::string &\fBvalue\fP)"
.br
.ti -1c
.RI "static void \fBRecordProperty\fP (const std::string &key, int \fBvalue\fP)"
.br
.in -1c

Protected Member Functions inherited from \fBtesting::Test\fP
.in +1c
.ti -1c
.RI "virtual void \fBSetUp\fP ()"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetUp\fP ()"
.br
.ti -1c
.RI "virtual void \fBTearDown\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
