.TH "SFNT_HeaderRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SFNT_HeaderRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_ULong \fBformat_tag\fP"
.br
.ti -1c
.RI "FT_UShort \fBnum_tables\fP"
.br
.ti -1c
.RI "FT_UShort \fBsearch_range\fP"
.br
.ti -1c
.RI "FT_UShort \fBentry_selector\fP"
.br
.ti -1c
.RI "FT_UShort \fBrange_shift\fP"
.br
.ti -1c
.RI "FT_ULong \fBoffset\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
