.TH "SFNT_Interface_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SFNT_Interface_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TT_Loader_GotoTableFunc \fBgoto_table\fP"
.br
.ti -1c
.RI "TT_Init_Face_Func \fBinit_face\fP"
.br
.ti -1c
.RI "TT_Load_Face_Func \fBload_face\fP"
.br
.ti -1c
.RI "TT_Done_Face_Func \fBdone_face\fP"
.br
.ti -1c
.RI "FT_Module_Requester \fBget_interface\fP"
.br
.ti -1c
.RI "TT_Load_Any_Func \fBload_any\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_head\fP"
.br
.ti -1c
.RI "TT_Load_Metrics_Func \fBload_hhea\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_cmap\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_maxp\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_os2\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_post\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_name\fP"
.br
.ti -1c
.RI "TT_Free_Table_Func \fBfree_name\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_kern\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_gasp\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_pclt\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_bhed\fP"
.br
.ti -1c
.RI "TT_Load_SBit_Image_Func \fBload_sbit_image\fP"
.br
.ti -1c
.RI "TT_Get_PS_Name_Func \fBget_psname\fP"
.br
.ti -1c
.RI "TT_Free_Table_Func \fBfree_psnames\fP"
.br
.ti -1c
.RI "TT_Face_GetKerningFunc \fBget_kerning\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_font_dir\fP"
.br
.ti -1c
.RI "TT_Load_Metrics_Func \fBload_hmtx\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_eblc\fP"
.br
.ti -1c
.RI "TT_Free_Table_Func \fBfree_eblc\fP"
.br
.ti -1c
.RI "TT_Set_SBit_Strike_Func \fBset_sbit_strike\fP"
.br
.ti -1c
.RI "TT_Load_Strike_Metrics_Func \fBload_strike_metrics\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_cpal\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_colr\fP"
.br
.ti -1c
.RI "TT_Free_Table_Func \fBfree_cpal\fP"
.br
.ti -1c
.RI "TT_Free_Table_Func \fBfree_colr\fP"
.br
.ti -1c
.RI "TT_Set_Palette_Func \fBset_palette\fP"
.br
.ti -1c
.RI "TT_Get_Colr_Layer_Func \fBget_colr_layer\fP"
.br
.ti -1c
.RI "TT_Get_Color_Glyph_Paint_Func \fBget_colr_glyph_paint\fP"
.br
.ti -1c
.RI "TT_Get_Color_Glyph_ClipBox_Func \fBget_color_glyph_clipbox\fP"
.br
.ti -1c
.RI "TT_Get_Paint_Layers_Func \fBget_paint_layers\fP"
.br
.ti -1c
.RI "TT_Get_Colorline_Stops_Func \fBget_colorline_stops\fP"
.br
.ti -1c
.RI "TT_Get_Paint_Func \fBget_paint\fP"
.br
.ti -1c
.RI "TT_Blend_Colr_Func \fBcolr_blend\fP"
.br
.ti -1c
.RI "TT_Get_Metrics_Func \fBget_metrics\fP"
.br
.ti -1c
.RI "TT_Get_Name_Func \fBget_name\fP"
.br
.ti -1c
.RI "TT_Get_Name_ID_Func \fBget_name_id\fP"
.br
.ti -1c
.RI "TT_Load_Table_Func \fBload_svg\fP"
.br
.ti -1c
.RI "TT_Free_Table_Func \fBfree_svg\fP"
.br
.ti -1c
.RI "TT_Load_Svg_Doc_Func \fBload_svg_doc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
