.TH "SHA1Context" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SHA1Context
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBIntermediate_Hash\fP [SHA1HashSize/4]"
.br
.ti -1c
.RI "uint32_t \fBLength_Low\fP"
.br
.ti -1c
.RI "uint32_t \fBLength_High\fP"
.br
.ti -1c
.RI "int16_t \fBMessage_Block_Index\fP"
.br
.ti -1c
.RI "uint8_t \fBMessage_Block\fP [64]"
.br
.ti -1c
.RI "int \fBComputed\fP"
.br
.ti -1c
.RI "int \fBCorrupted\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
