.TH "sha256_state" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sha256_state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned __int64 \fBlength\fP"
.br
.ti -1c
.RI "unsigned long \fBstate\fP [8]"
.br
.ti -1c
.RI "unsigned long \fBcurlen\fP"
.br
.ti -1c
.RI "unsigned char \fBbuf\fP [64]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
