.TH "shape_options_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shape_options_t
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBshape_consumer_t< output_t >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_options\fP (\fBoption_parser_t\fP *parser)"
.br
.ti -1c
.RI "void \fBsetup_buffer\fP (\fBhb_buffer_t\fP *\fBbuffer\fP)"
.br
.ti -1c
.RI "void \fBpopulate_buffer\fP (\fBhb_buffer_t\fP *\fBbuffer\fP, const char *text, int text_len, const char *text_before, const char *text_after)"
.br
.ti -1c
.RI "hb_bool_t \fBshape\fP (\fBhb_font_t\fP *font, \fBhb_buffer_t\fP *\fBbuffer\fP, const char **error=nullptr)"
.br
.ti -1c
.RI "void \fBshape_closure\fP (const char *text, int text_len, \fBhb_font_t\fP *font, \fBhb_buffer_t\fP *\fBbuffer\fP, \fBhb_set_t\fP *glyphs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBdirection\fP = nullptr"
.br
.ti -1c
.RI "char * \fBlanguage\fP = nullptr"
.br
.ti -1c
.RI "char * \fBscript\fP = nullptr"
.br
.ti -1c
.RI "hb_bool_t \fBbot\fP = false"
.br
.ti -1c
.RI "hb_bool_t \fBeot\fP = false"
.br
.ti -1c
.RI "hb_bool_t \fBpreserve_default_ignorables\fP = false"
.br
.ti -1c
.RI "hb_bool_t \fBremove_default_ignorables\fP = false"
.br
.ti -1c
.RI "\fBhb_feature_t\fP * \fBfeatures\fP = nullptr"
.br
.ti -1c
.RI "unsigned int \fBnum_features\fP = 0"
.br
.ti -1c
.RI "char ** \fBshapers\fP = nullptr"
.br
.ti -1c
.RI "hb_bool_t \fButf8_clusters\fP = false"
.br
.ti -1c
.RI "hb_codepoint_t \fBinvisible_glyph\fP = 0"
.br
.ti -1c
.RI "hb_codepoint_t \fBnot_found_glyph\fP = 0"
.br
.ti -1c
.RI "hb_buffer_cluster_level_t \fBcluster_level\fP = HB_BUFFER_CLUSTER_LEVEL_DEFAULT"
.br
.ti -1c
.RI "hb_bool_t \fBnormalize_glyphs\fP = false"
.br
.ti -1c
.RI "hb_bool_t \fBverify\fP = false"
.br
.ti -1c
.RI "hb_bool_t \fBunsafe_to_concat\fP = false"
.br
.ti -1c
.RI "unsigned int \fBnum_iterations\fP = 1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
