.TH "shape_closure_consumer_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shape_closure_consumer_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_options\fP (struct \fBoption_parser_t\fP *parser)"
.br
.ti -1c
.RI "void \fBinit\fP (const \fBfont_options_t\fP *font_opts)"
.br
.ti -1c
.RI "template<typename text_options_type > bool \fBconsume_line\fP (text_options_type &text_opts)"
.br
.ti -1c
.RI "void \fBfinish\fP (const \fBfont_options_t\fP *font_opts)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBfailed\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBshape_options_t\fP \fBshaper\fP"
.br
.ti -1c
.RI "hb_bool_t \fBshow_glyph_names\fP = false"
.br
.ti -1c
.RI "\fBhb_set_t\fP * \fBglyphs\fP = nullptr"
.br
.ti -1c
.RI "\fBhb_font_t\fP * \fBfont\fP = nullptr"
.br
.ti -1c
.RI "\fBhb_buffer_t\fP * \fBbuffer\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
