.TH "shape_format_options_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shape_format_options_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_options\fP (\fBoption_parser_t\fP *parser)"
.br
.ti -1c
.RI "void \fBserialize\fP (\fBhb_buffer_t\fP *\fBbuffer\fP, \fBhb_font_t\fP *font, hb_buffer_serialize_format_t format, hb_buffer_serialize_flags_t flags, GString *gs)"
.br
.ti -1c
.RI "void \fBserialize_line_no\fP (unsigned int line_no, GString *gs)"
.br
.ti -1c
.RI "void \fBserialize_buffer_of_text\fP (\fBhb_buffer_t\fP *\fBbuffer\fP, unsigned int line_no, const char *text, unsigned int text_len, \fBhb_font_t\fP *font, GString *gs)"
.br
.ti -1c
.RI "void \fBserialize_message\fP (unsigned int line_no, const char *type, const char *msg, GString *gs)"
.br
.ti -1c
.RI "void \fBserialize_buffer_of_glyphs\fP (\fBhb_buffer_t\fP *\fBbuffer\fP, unsigned int line_no, const char *text, unsigned int text_len, \fBhb_font_t\fP *font, hb_buffer_serialize_format_t output_format, hb_buffer_serialize_flags_t format_flags, GString *gs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_bool_t \fBshow_glyph_names\fP = true"
.br
.ti -1c
.RI "hb_bool_t \fBshow_positions\fP = true"
.br
.ti -1c
.RI "hb_bool_t \fBshow_advances\fP = true"
.br
.ti -1c
.RI "hb_bool_t \fBshow_clusters\fP = true"
.br
.ti -1c
.RI "hb_bool_t \fBshow_text\fP = false"
.br
.ti -1c
.RI "hb_bool_t \fBshow_unicode\fP = false"
.br
.ti -1c
.RI "hb_bool_t \fBshow_line_num\fP = false"
.br
.ti -1c
.RI "hb_bool_t \fBshow_extents\fP = false"
.br
.ti -1c
.RI "hb_bool_t \fBshow_flags\fP = false"
.br
.ti -1c
.RI "hb_bool_t \fBtrace\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
