.TH "shar" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shar
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdump\fP"
.br
.ti -1c
.RI "int \fBend_of_line\fP"
.br
.ti -1c
.RI "struct \fBarchive_entry\fP * \fBentry\fP"
.br
.ti -1c
.RI "int \fBhas_data\fP"
.br
.ti -1c
.RI "char * \fBlast_dir\fP"
.br
.ti -1c
.RI "char \fBoutbuff\fP [45]"
.br
.ti -1c
.RI "size_t \fBoutpos\fP"
.br
.ti -1c
.RI "int \fBwrote_header\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBwork\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBquoted_name\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
