.TH "SingleRequest" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SingleRequest
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBHEADER_NORMAL\fP, \fBHEADER_PARTHEADER\fP, \fBHEADER_ALLBAD\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBIT\fP (header)"
.br
.ti -1c
.RI "\fBBIT\fP (content_range)"
.br
.ti -1c
.RI "\fBBIT\fP (upload_done)"
.br
.ti -1c
.RI "\fBBIT\fP (ignorebody)"
.br
.ti -1c
.RI "\fBBIT\fP (http_bodyless)"
.br
.ti -1c
.RI "\fBBIT\fP (chunk)"
.br
.ti -1c
.RI "\fBBIT\fP (ignore_cl)"
.br
.ti -1c
.RI "\fBBIT\fP (upload_chunky)"
.br
.ti -1c
.RI "\fBBIT\fP (getheader)"
.br
.ti -1c
.RI "\fBBIT\fP (forbidchunk)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "curl_off_t \fBsize\fP"
.br
.ti -1c
.RI "curl_off_t \fBmaxdownload\fP"
.br
.ti -1c
.RI "curl_off_t \fBbytecount\fP"
.br
.ti -1c
.RI "curl_off_t \fBwritebytecount\fP"
.br
.ti -1c
.RI "curl_off_t \fBheaderbytecount\fP"
.br
.ti -1c
.RI "curl_off_t \fBdeductheadercount\fP"
.br
.ti -1c
.RI "curl_off_t \fBpendingheader\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBstart\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBnow\fP"
.br
.ti -1c
.RI "enum SingleRequest:: { \&.\&.\&. }  \fBbadheader\fP"
.br
.ti -1c
.RI "int \fBheaderline\fP"
.br
.ti -1c
.RI "char * \fBstr\fP"
.br
.ti -1c
.RI "curl_off_t \fBoffset\fP"
.br
.ti -1c
.RI "int \fBhttpcode\fP"
.br
.ti -1c
.RI "int \fBkeepon\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBstart100\fP"
.br
.ti -1c
.RI "enum expect100 \fBexp100\fP"
.br
.ti -1c
.RI "enum upgrade101 \fBupgr101\fP"
.br
.ti -1c
.RI "struct \fBcontenc_writer\fP * \fBwriter_stack\fP"
.br
.ti -1c
.RI "time_t \fBtimeofdoc\fP"
.br
.ti -1c
.RI "long \fBbodywrites\fP"
.br
.ti -1c
.RI "char * \fBlocation\fP"
.br
.ti -1c
.RI "char * \fBnewurl\fP"
.br
.ti -1c
.RI "ssize_t \fBupload_present\fP"
.br
.ti -1c
.RI "char * \fBupload_fromhere\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct \fBFILEPROTO\fP * \fBfile\fP"
.br
.ti -1c
.RI "   struct \fBFTP\fP * \fBftp\fP"
.br
.ti -1c
.RI "   struct \fBHTTP\fP * \fBhttp\fP"
.br
.ti -1c
.RI "   struct \fBIMAP\fP * \fBimap\fP"
.br
.ti -1c
.RI "   struct ldapreqinfo * \fBldap\fP"
.br
.ti -1c
.RI "   struct \fBMQTT\fP * \fBmqtt\fP"
.br
.ti -1c
.RI "   struct \fBPOP3\fP * \fBpop3\fP"
.br
.ti -1c
.RI "   struct \fBRTSP\fP * \fBrtsp\fP"
.br
.ti -1c
.RI "   struct smb_request * \fBsmb\fP"
.br
.ti -1c
.RI "   struct \fBSMTP\fP * \fBsmtp\fP"
.br
.ti -1c
.RI "   struct \fBSSHPROTO\fP * \fBssh\fP"
.br
.ti -1c
.RI "   struct \fBTELNET\fP * \fBtelnet\fP"
.br
.ti -1c
.RI "} \fBp\fP"
.br
.ti -1c
.RI "struct \fBdohdata\fP * \fBdoh\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
