.TH "slow_float" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slow_float
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "constexpr \fBslow_float\fP (float val=0)"
.br
.ti -1c
.RI "\fBoperator float\fP () const"
.br
.ti -1c
.RI "auto \fBoperator\-\fP () const \-> \fBslow_float\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
