.TH "smallprng_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
smallprng_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBa\fP"
.br
.ti -1c
.RI "uint32_t \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBc\fP"
.br
.ti -1c
.RI "uint32_t \fBd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
