.TH "smb_conn" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
smb_conn
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum smb_conn_state \fBstate\fP"
.br
.ti -1c
.RI "char * \fBuser\fP"
.br
.ti -1c
.RI "char * \fBdomain\fP"
.br
.ti -1c
.RI "char * \fBshare\fP"
.br
.ti -1c
.RI "unsigned char \fBchallenge\fP [8]"
.br
.ti -1c
.RI "unsigned int \fBsession_key\fP"
.br
.ti -1c
.RI "unsigned short \fBuid\fP"
.br
.ti -1c
.RI "char * \fBrecv_buf\fP"
.br
.ti -1c
.RI "size_t \fBupload_size\fP"
.br
.ti -1c
.RI "size_t \fBsend_size\fP"
.br
.ti -1c
.RI "size_t \fBsent\fP"
.br
.ti -1c
.RI "size_t \fBgot\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
