.TH "SmoothParams" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SmoothParams
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth_\fP"
.br
.ti -1c
.RI "int \fBheight_\fP"
.br
.ti -1c
.RI "int \fBstride_\fP"
.br
.ti -1c
.RI "int \fBrow_\fP"
.br
.ti -1c
.RI "uint8_t * \fBsrc_\fP"
.br
.ti -1c
.RI "uint8_t * \fBdst_\fP"
.br
.ti -1c
.RI "int \fBradius_\fP"
.br
.ti -1c
.RI "int \fBscale_\fP"
.br
.ti -1c
.RI "void * \fBmem_\fP"
.br
.ti -1c
.RI "uint16_t * \fBstart_\fP"
.br
.ti -1c
.RI "uint16_t * \fBcur_\fP"
.br
.ti -1c
.RI "uint16_t * \fBend_\fP"
.br
.ti -1c
.RI "uint16_t * \fBtop_\fP"
.br
.ti -1c
.RI "uint16_t * \fBaverage_\fP"
.br
.ti -1c
.RI "int \fBnum_levels_\fP"
.br
.ti -1c
.RI "int \fBmin_\fP"
.br
.ti -1c
.RI "int \fBmax_\fP"
.br
.ti -1c
.RI "int \fBmin_level_dist_\fP"
.br
.ti -1c
.RI "int16_t * \fBcorrection_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
