.TH "SMTP" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SMTP
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "curl_pp_transfer \fBtransfer\fP"
.br
.ti -1c
.RI "char * \fBcustom\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBrcpt\fP"
.br
.ti -1c
.RI "bool \fBrcpt_had_ok\fP"
.br
.ti -1c
.RI "bool \fBtrailing_crlf\fP"
.br
.ti -1c
.RI "int \fBrcpt_last_error\fP"
.br
.ti -1c
.RI "size_t \fBeob\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
