.TH "some_array_t< T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
some_array_t< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBarray_iter_t\fP< T > \fBiter_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsome_array_t\fP (\fBhb_array_t\fP< T > arr_)"
.br
.ti -1c
.RI "\fBarray_iter_t\fP< T > \fBiter\fP ()"
.br
.ti -1c
.RI "\fBoperator array_iter_t< T >\fP ()"
.br
.ti -1c
.RI "\fBoperator hb_iter_t< array_iter_t< T > >\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
