.TH "sparse_block" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sparse_block
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBsparse_block\fP * \fBnext\fP"
.br
.ti -1c
.RI "int64_t \fBoffset\fP"
.br
.ti -1c
.RI "int64_t \fBremaining\fP"
.br
.ti -1c
.RI "int \fBhole\fP"
.br
.ti -1c
.RI "int \fBis_hole\fP"
.br
.ti -1c
.RI "uint64_t \fBoffset\fP"
.br
.ti -1c
.RI "uint64_t \fBremaining\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
