.TH "specs_checker< Handler >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
specs_checker< Handler >
.SH SYNOPSIS
.br
.PP
.PP
Inherits Handler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_checker\fP (const Handler &handler, detail::type arg_type)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_align\fP (align_t align)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_sign\fP (sign_t s)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_hash\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_localized\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_zero\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBend_precision\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_checker\fP (const Handler &handler, detail::type arg_type)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_align\fP (align_t align)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_sign\fP (sign_t s)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_hash\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_localized\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_zero\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBend_precision\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_checker\fP (const Handler &handler, detail::type arg_type)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_align\fP (align_t align)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_sign\fP (sign_t s)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_hash\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_localized\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_zero\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBend_precision\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_checker\fP (const Handler &handler, detail::type arg_type)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_align\fP (align_t align)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_sign\fP (sign_t s)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_hash\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_localized\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_zero\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBend_precision\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
