.TH "specs_handler< Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
specs_handler< Char >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBspecs_setter< Char >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_handler\fP (\fBbasic_format_specs\fP< Char > &specs, \fBbasic_format_parse_context\fP< Char > &parse_ctx, \fBbuffer_context\fP< Char > &ctx)"
.br
.ti -1c
.RI "template<typename Id > FMT_CONSTEXPR void \fBon_dynamic_width\fP (Id arg_id)"
.br
.ti -1c
.RI "template<typename Id > FMT_CONSTEXPR void \fBon_dynamic_precision\fP (Id arg_id)"
.br
.ti -1c
.RI "void \fBon_error\fP (const char *message)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_handler\fP (\fBbasic_format_specs\fP< Char > &specs, \fBbasic_format_parse_context\fP< Char > &parse_ctx, \fBbuffer_context\fP< Char > &ctx)"
.br
.ti -1c
.RI "template<typename Id > FMT_CONSTEXPR void \fBon_dynamic_width\fP (Id arg_id)"
.br
.ti -1c
.RI "template<typename Id > FMT_CONSTEXPR void \fBon_dynamic_precision\fP (Id arg_id)"
.br
.ti -1c
.RI "void \fBon_error\fP (const char *message)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_handler\fP (\fBbasic_format_specs\fP< Char > &specs, \fBbasic_format_parse_context\fP< Char > &parse_ctx, \fBbuffer_context\fP< Char > &ctx)"
.br
.ti -1c
.RI "template<typename Id > FMT_CONSTEXPR void \fBon_dynamic_width\fP (Id arg_id)"
.br
.ti -1c
.RI "template<typename Id > FMT_CONSTEXPR void \fBon_dynamic_precision\fP (Id arg_id)"
.br
.ti -1c
.RI "void \fBon_error\fP (const char *message)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_handler\fP (\fBbasic_format_specs\fP< Char > &specs, \fBbasic_format_parse_context\fP< Char > &parse_ctx, \fBbuffer_context\fP< Char > &ctx)"
.br
.ti -1c
.RI "template<typename Id > FMT_CONSTEXPR void \fBon_dynamic_width\fP (Id arg_id)"
.br
.ti -1c
.RI "template<typename Id > FMT_CONSTEXPR void \fBon_dynamic_precision\fP (Id arg_id)"
.br
.ti -1c
.RI "void \fBon_error\fP (const char *message)"
.br
.in -1c

Public Member Functions inherited from \fBspecs_setter< Char >\fP
.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_setter\fP (\fBbasic_format_specs\fP< Char > &specs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_setter\fP (const \fBspecs_setter\fP &other)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_align\fP (align_t align)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_fill\fP (\fBbasic_string_view\fP< Char > fill)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_sign\fP (sign_t s)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_hash\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_localized\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_zero\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_width\fP (int width)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_precision\fP (int precision)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBend_precision\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_type\fP (presentation_type type)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_setter\fP (\fBbasic_format_specs\fP< Char > &specs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_setter\fP (const \fBspecs_setter\fP &other)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_align\fP (align_t align)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_fill\fP (\fBbasic_string_view\fP< Char > fill)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_sign\fP (sign_t s)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_hash\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_localized\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_zero\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_width\fP (int width)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_precision\fP (int precision)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBend_precision\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_type\fP (presentation_type type)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_setter\fP (\fBbasic_format_specs\fP< Char > &specs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_setter\fP (const \fBspecs_setter\fP &other)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_align\fP (align_t align)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_fill\fP (\fBbasic_string_view\fP< Char > fill)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_sign\fP (sign_t s)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_hash\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_localized\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_zero\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_width\fP (int width)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_precision\fP (int precision)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBend_precision\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_type\fP (presentation_type type)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_setter\fP (\fBbasic_format_specs\fP< Char > &specs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBspecs_setter\fP (const \fBspecs_setter\fP &other)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_align\fP (align_t align)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_fill\fP (\fBbasic_string_view\fP< Char > fill)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_sign\fP (sign_t s)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_hash\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_localized\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_zero\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_width\fP (int width)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_precision\fP (int precision)"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBend_precision\fP ()"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_type\fP (presentation_type type)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBspecs_setter< Char >\fP
.in +1c
.ti -1c
.RI "\fBbasic_format_specs\fP< Char > & \fBspecs_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
