.TH "ssl_connect_data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssl_connect_data
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBIT\fP (use)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ssl_connection_state \fBstate\fP"
.br
.ti -1c
.RI "ssl_connect_state \fBconnecting_state\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
