.TH "ssl_config_data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssl_config_data
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBIT\fP (certinfo)"
.br
.ti -1c
.RI "\fBBIT\fP (falsestart)"
.br
.ti -1c
.RI "\fBBIT\fP (enable_beast)"
.br
.ti -1c
.RI "\fBBIT\fP (no_revoke)"
.br
.ti -1c
.RI "\fBBIT\fP (no_partialchain)"
.br
.ti -1c
.RI "\fBBIT\fP (revoke_best_effort)"
.br
.ti -1c
.RI "\fBBIT\fP (native_ca_store)"
.br
.ti -1c
.RI "\fBBIT\fP (auto_client_cert)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBssl_primary_config\fP \fBprimary\fP"
.br
.ti -1c
.RI "long \fBcertverifyresult\fP"
.br
.ti -1c
.RI "char * \fBCRLfile\fP"
.br
.ti -1c
.RI "curl_ssl_ctx_callback \fBfsslctx\fP"
.br
.ti -1c
.RI "void * \fBfsslctxp\fP"
.br
.ti -1c
.RI "char * \fBcert_type\fP"
.br
.ti -1c
.RI "char * \fBkey\fP"
.br
.ti -1c
.RI "struct \fBcurl_blob\fP * \fBkey_blob\fP"
.br
.ti -1c
.RI "char * \fBkey_type\fP"
.br
.ti -1c
.RI "char * \fBkey_passwd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
