.TH "ssl_primary_config" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssl_primary_config
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBIT\fP (verifypeer)"
.br
.ti -1c
.RI "\fBBIT\fP (verifyhost)"
.br
.ti -1c
.RI "\fBBIT\fP (verifystatus)"
.br
.ti -1c
.RI "\fBBIT\fP (sessionid)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBversion\fP"
.br
.ti -1c
.RI "long \fBversion_max\fP"
.br
.ti -1c
.RI "char * \fBCApath\fP"
.br
.ti -1c
.RI "char * \fBCAfile\fP"
.br
.ti -1c
.RI "char * \fBissuercert\fP"
.br
.ti -1c
.RI "char * \fBclientcert\fP"
.br
.ti -1c
.RI "char * \fBrandom_file\fP"
.br
.ti -1c
.RI "char * \fBegdsocket\fP"
.br
.ti -1c
.RI "char * \fBcipher_list\fP"
.br
.ti -1c
.RI "char * \fBcipher_list13\fP"
.br
.ti -1c
.RI "char * \fBpinned_key\fP"
.br
.ti -1c
.RI "struct \fBcurl_blob\fP * \fBcert_blob\fP"
.br
.ti -1c
.RI "struct \fBcurl_blob\fP * \fBca_info_blob\fP"
.br
.ti -1c
.RI "struct \fBcurl_blob\fP * \fBissuercert_blob\fP"
.br
.ti -1c
.RI "char * \fBcurves\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
