.TH "State" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
State
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBgetout\fP * \fBurlnode\fP"
.br
.ti -1c
.RI "struct \fBURLGlob\fP * \fBinglob\fP"
.br
.ti -1c
.RI "struct \fBURLGlob\fP * \fBurls\fP"
.br
.ti -1c
.RI "char * \fBoutfiles\fP"
.br
.ti -1c
.RI "char * \fBhttpgetfields\fP"
.br
.ti -1c
.RI "char * \fBuploadfile\fP"
.br
.ti -1c
.RI "unsigned long \fBinfilenum\fP"
.br
.ti -1c
.RI "unsigned long \fBup\fP"
.br
.ti -1c
.RI "unsigned long \fBurlnum\fP"
.br
.ti -1c
.RI "unsigned long \fBli\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
