.TH "static_tree_desc_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
static_tree_desc_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBct_data\fP * \fBstatic_tree\fP"
.br
.ti -1c
.RI "const intf * \fBextra_bits\fP"
.br
.ti -1c
.RI "int \fBextra_base\fP"
.br
.ti -1c
.RI "int \fBelems\fP"
.br
.ti -1c
.RI "int \fBmax_length\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
