.TH "stbi_io_callbacks" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbi_io_callbacks
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int(* \fBread\fP )(void *user, char *\fBdata\fP, int size)"
.br
.ti -1c
.RI "void(* \fBskip\fP )(void *user, int n)"
.br
.ti -1c
.RI "int(* \fBeof\fP )(void *user)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
