.TH "stbrp_rect" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbrp_rect
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "stbrp_coord \fBw\fP"
.br
.ti -1c
.RI "stbrp_coord \fBh\fP"
.br
.ti -1c
.RI "stbrp_coord \fBx\fP"
.br
.ti -1c
.RI "stbrp_coord \fBy\fP"
.br
.ti -1c
.RI "int \fBwas_packed\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
