.TH "stbtt_pack_context" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbtt_pack_context
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBuser_allocator_context\fP"
.br
.ti -1c
.RI "void * \fBpack_info\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBstride_in_bytes\fP"
.br
.ti -1c
.RI "int \fBpadding\fP"
.br
.ti -1c
.RI "int \fBskip_missing\fP"
.br
.ti -1c
.RI "unsigned int \fBh_oversample\fP"
.br
.ti -1c
.RI "unsigned int \fBv_oversample\fP"
.br
.ti -1c
.RI "unsigned char * \fBpixels\fP"
.br
.ti -1c
.RI "void * \fBnodes\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
