.TH "StbUndoState" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StbUndoState
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStbUndoRecord\fP \fBundo_rec\fP [STB_TEXTEDIT_UNDOSTATECOUNT]"
.br
.ti -1c
.RI "STB_TEXTEDIT_CHARTYPE \fBundo_char\fP [STB_TEXTEDIT_UNDOCHARCOUNT]"
.br
.ti -1c
.RI "short \fBundo_point\fP"
.br
.ti -1c
.RI "short \fBredo_point\fP"
.br
.ti -1c
.RI "int \fBundo_char_point\fP"
.br
.ti -1c
.RI "int \fBredo_char_point\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
