.TH "StreamEncodeContext" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StreamEncodeContext
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBWebPConfig\fP * \fBconfig_\fP"
.br
.ti -1c
.RI "const \fBWebPPicture\fP * \fBpicture_\fP"
.br
.ti -1c
.RI "\fBVP8LBitWriter\fP * \fBbw_\fP"
.br
.ti -1c
.RI "\fBVP8LEncoder\fP * \fBenc_\fP"
.br
.ti -1c
.RI "int \fBuse_cache_\fP"
.br
.ti -1c
.RI "\fBCrunchConfig\fP \fBcrunch_configs_\fP [CRUNCH_CONFIGS_MAX]"
.br
.ti -1c
.RI "int \fBnum_crunch_configs_\fP"
.br
.ti -1c
.RI "int \fBred_and_blue_always_zero_\fP"
.br
.ti -1c
.RI "WebPEncodingError \fBerr_\fP"
.br
.ti -1c
.RI "\fBWebPAuxStats\fP * \fBstats_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
