.TH "stringtable" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stringtable
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTString\fP ** \fBhash\fP"
.br
.ti -1c
.RI "int \fBnuse\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
