.TH "strip_named_arg< T, true >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strip_named_arg< T, true >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = remove_cvref_t< decltype(T::value)>"
.br
.ti -1c
.RI "using \fBtype\fP = remove_cvref_t< decltype(T::value)>"
.br
.ti -1c
.RI "using \fBtype\fP = remove_cvref_t< decltype(T::value)>"
.br
.ti -1c
.RI "using \fBtype\fP = remove_cvref_t< decltype(T::value)>"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
