.TH "SubFrameParams" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubFrameParams
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBshould_try_\fP"
.br
.ti -1c
.RI "int \fBempty_rect_allowed_\fP"
.br
.ti -1c
.RI "\fBFrameRectangle\fP \fBrect_ll_\fP"
.br
.ti -1c
.RI "\fBWebPPicture\fP \fBsub_frame_ll_\fP"
.br
.ti -1c
.RI "\fBFrameRectangle\fP \fBrect_lossy_\fP"
.br
.ti -1c
.RI "\fBWebPPicture\fP \fBsub_frame_lossy_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
