.TH "subject" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
subject
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcmark_mem\fP * \fBmem\fP"
.br
.ti -1c
.RI "\fBcmark_chunk\fP \fBinput\fP"
.br
.ti -1c
.RI "unsigned \fBflags\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "bufsize_t \fBpos\fP"
.br
.ti -1c
.RI "int \fBblock_offset\fP"
.br
.ti -1c
.RI "int \fBcolumn_offset\fP"
.br
.ti -1c
.RI "\fBcmark_reference_map\fP * \fBrefmap\fP"
.br
.ti -1c
.RI "\fBdelimiter\fP * \fBlast_delim\fP"
.br
.ti -1c
.RI "\fBbracket\fP * \fBlast_bracket\fP"
.br
.ti -1c
.RI "bufsize_t \fBbackticks\fP [MAXBACKTICKS+1]"
.br
.ti -1c
.RI "bool \fBscanned_for_backticks\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
