.TH "subset_main_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
subset_main_t
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBoption_parser_t\fP, \fBface_options_t\fP, and \fBoutput_options_t< false >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBparse_face\fP (int argc, const char *const *argv)"
.br
.ti -1c
.RI "void \fBparse\fP (int argc, char **argv)"
.br
.ti -1c
.RI "int \fBoperator()\fP (int argc, char **argv)"
.br
.ti -1c
.RI "bool \fBwrite_file\fP (const char *output_file, \fBhb_blob_t\fP *blob)"
.br
.ti -1c
.RI "void \fBadd_options\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBoption_parser_t\fP
.in +1c
.ti -1c
.RI "\fBoption_parser_t\fP (const char *parameter_string=nullptr)"
.br
.ti -1c
.RI "void \fBadd_options\fP ()"
.br
.ti -1c
.RI "template<typename Type > void \fBadd_group\fP (GOptionEntry *entries, const gchar *name, const gchar *description, const gchar *help_description, Type *closure, bool add_parse_hooks=true)"
.br
.ti -1c
.RI "template<typename Type > void \fBadd_main_group\fP (GOptionEntry *entries, Type *closure)"
.br
.ti -1c
.RI "void \fBset_summary\fP (const char *summary)"
.br
.ti -1c
.RI "void \fBset_description\fP (const char *description)"
.br
.ti -1c
.RI "void \fBfree_later\fP (char *p)"
.br
.ti -1c
.RI "bool \fBparse\fP (int *argc, char ***argv, bool ignore_error=false)"
.br
.in -1c

Public Member Functions inherited from \fBface_options_t\fP
.in +1c
.ti -1c
.RI "void \fBset_face\fP (\fBhb_face_t\fP *face_)"
.br
.ti -1c
.RI "void \fBadd_options\fP (\fBoption_parser_t\fP *parser)"
.br
.ti -1c
.RI "void \fBpost_parse\fP (GError **error)"
.br
.in -1c

Public Member Functions inherited from \fBoutput_options_t< false >\fP
.in +1c
.ti -1c
.RI "void \fBadd_options\fP (\fBoption_parser_t\fP *parser, const char **supported_formats=nullptr)"
.br
.ti -1c
.RI "void \fBpost_parse\fP (GError **error)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBnum_iterations\fP = 1"
.br
.ti -1c
.RI "\fBhb_subset_input_t\fP * \fBinput\fP = nullptr"
.br
.in -1c

Public Attributes inherited from \fBoption_parser_t\fP
.in +1c
.ti -1c
.RI "GOptionContext * \fBcontext\fP"
.br
.in -1c

Public Attributes inherited from \fBface_options_t\fP
.in +1c
.ti -1c
.RI "char * \fBfont_file\fP = nullptr"
.br
.ti -1c
.RI "unsigned \fBface_index\fP = 0"
.br
.ti -1c
.RI "\fBhb_blob_t\fP * \fBblob\fP = nullptr"
.br
.ti -1c
.RI "\fBhb_face_t\fP * \fBface\fP = nullptr"
.br
.in -1c

Public Attributes inherited from \fBoutput_options_t< false >\fP
.in +1c
.ti -1c
.RI "char * \fBoutput_file\fP"
.br
.ti -1c
.RI "char * \fBoutput_format\fP"
.br
.ti -1c
.RI "bool \fBexplicit_output_format\fP"
.br
.ti -1c
.RI "FILE * \fBout_fp\fP"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static gboolean \fBcollect_face\fP (const char *name, const char *arg, gpointer \fBdata\fP, GError **error)"
.br
.ti -1c
.RI "static gboolean \fBcollect_rest\fP (const char *name, const char *arg, gpointer \fBdata\fP, GError **error)"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBoption_parser_t\fP
.in +1c
.ti -1c
.RI "static void \fB_g_free_g_func\fP (void *p, void *G_GNUC_UNUSED)"
.br
.ti -1c
.RI "static void \fBpost_parse_\fP (void *thiz, GError **error)"
.br
.ti -1c
.RI "template<typename Type > static auto \fBpost_parse_\fP (Type *thiz, GError **error) \-> decltype(thiz\->post_parse(error))"
.br
.ti -1c
.RI "template<typename Type > static gboolean \fBpost_parse\fP (GOptionContext *context G_GNUC_UNUSED, GOptionGroup *\fBgroup\fP G_GNUC_UNUSED, gpointer \fBdata\fP, GError **error)"
.br
.in -1c

Static Public Attributes inherited from \fBface_options_t\fP
.in +1c
.ti -1c
.RI "static struct face_options_t::cache_t \fBcache\fP {}"
.br
.in -1c

Protected Attributes inherited from \fBoption_parser_t\fP
.in +1c
.ti -1c
.RI "GPtrArray * \fBto_free\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
