.TH "SVG_RendererHooks_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVG_RendererHooks_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SVG_Lib_Init_Func \fBinit_svg\fP"
.br
.ti -1c
.RI "SVG_Lib_Free_Func \fBfree_svg\fP"
.br
.ti -1c
.RI "SVG_Lib_Render_Func \fBrender_svg\fP"
.br
.ti -1c
.RI "SVG_Lib_Preset_Slot_Func \fBpreset_slot\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
