.TH "SVG_RendererRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVG_RendererRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_RendererRec\fP \fBroot\fP"
.br
.ti -1c
.RI "FT_Bool \fBloaded\fP"
.br
.ti -1c
.RI "FT_Bool \fBhooks_set\fP"
.br
.ti -1c
.RI "\fBSVG_RendererHooks\fP \fBhooks\fP"
.br
.ti -1c
.RI "FT_Pointer \fBstate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
