.TH "swig_cast_info" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
swig_cast_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBswig_type_info\fP * \fBtype\fP"
.br
.ti -1c
.RI "swig_converter_func \fBconverter\fP"
.br
.ti -1c
.RI "struct \fBswig_cast_info\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBswig_cast_info\fP * \fBprev\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
