.TH "SWIG_JavaExceptions_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SWIG_JavaExceptions_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SWIG_JavaExceptionCodes \fBcode\fP"
.br
.ti -1c
.RI "const char * \fBjava_exception\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
