.TH "swig_module_info" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
swig_module_info
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBswig_type_info\fP ** \fBtypes\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "struct \fBswig_module_info\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBswig_type_info\fP ** \fBtype_initial\fP"
.br
.ti -1c
.RI "\fBswig_cast_info\fP ** \fBcast_initial\fP"
.br
.ti -1c
.RI "void * \fBclientdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
