.TH "SwigPyObject" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SwigPyObject
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PyObject_HEAD void * \fBptr\fP"
.br
.ti -1c
.RI "\fBswig_type_info\fP * \fBty\fP"
.br
.ti -1c
.RI "int \fBown\fP"
.br
.ti -1c
.RI "PyObject * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
