.TH "swig_globalvar" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
swig_globalvar
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "PyObject *(* \fBget_attr\fP )(void)"
.br
.ti -1c
.RI "int(* \fBset_attr\fP )(PyObject *)"
.br
.ti -1c
.RI "struct \fBswig_globalvar\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
