.TH "SysFile" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SysFile
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BPTR \fBfile\fP"
.br
.ti -1c
.RI "ULONG \fBiobuf_start\fP"
.br
.ti -1c
.RI "ULONG \fBiobuf_end\fP"
.br
.ti -1c
.RI "UBYTE \fBiobuf\fP [IOBUF_SIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
