.TH "T1_CMap_ClassesRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T1_CMap_ClassesRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_CMap_Class\fP \fBstandard\fP"
.br
.ti -1c
.RI "\fBFT_CMap_Class\fP \fBexpert\fP"
.br
.ti -1c
.RI "\fBFT_CMap_Class\fP \fBcustom\fP"
.br
.ti -1c
.RI "\fBFT_CMap_Class\fP \fBunicode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
