.TH "T1_CMapStdRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T1_CMapStdRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_CMapRec\fP \fBcmap\fP"
.br
.ti -1c
.RI "const FT_UShort * \fBcode_to_sid\fP"
.br
.ti -1c
.RI "PS_Adobe_Std_StringsFunc \fBsid_to_string\fP"
.br
.ti -1c
.RI "FT_UInt \fBnum_glyphs\fP"
.br
.ti -1c
.RI "const char *const  * \fBglyph_names\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
