.TH "T1_EncodingRecRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T1_EncodingRecRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Int \fBnum_chars\fP"
.br
.ti -1c
.RI "FT_Int \fBcode_first\fP"
.br
.ti -1c
.RI "FT_Int \fBcode_last\fP"
.br
.ti -1c
.RI "FT_UShort * \fBchar_index\fP"
.br
.ti -1c
.RI "const FT_String ** \fBchar_name\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
