.TH "T2_Hints_FuncsRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
T2_Hints_FuncsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T2_Hints \fBhints\fP"
.br
.ti -1c
.RI "T2_Hints_OpenFunc \fBopen\fP"
.br
.ti -1c
.RI "T2_Hints_CloseFunc \fBclose\fP"
.br
.ti -1c
.RI "T2_Hints_StemsFunc \fBstems\fP"
.br
.ti -1c
.RI "T2_Hints_MaskFunc \fBhintmask\fP"
.br
.ti -1c
.RI "T2_Hints_CounterFunc \fBcounter\fP"
.br
.ti -1c
.RI "T2_Hints_ApplyFunc \fBapply\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
