.TH "Table" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Table
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCommonHeader\fP"
.br
.ti -1c
.RI "lu_byte \fBflags\fP"
.br
.ti -1c
.RI "lu_byte \fBlsizenode\fP"
.br
.ti -1c
.RI "unsigned int \fBalimit\fP"
.br
.ti -1c
.RI "\fBTValue\fP * \fBarray\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnode\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBlastfree\fP"
.br
.ti -1c
.RI "struct \fBTable\fP * \fBmetatable\fP"
.br
.ti -1c
.RI "\fBGCObject\fP * \fBgclist\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
