.TH "tagEXTPROPERTY" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagEXTPROPERTY
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BYTE \fBversion\fP"
.br
.ti -1c
.RI "BYTE \fBtabletIndex\fP"
.br
.ti -1c
.RI "BYTE \fBcontrolIndex\fP"
.br
.ti -1c
.RI "BYTE \fBfunctionIndex\fP"
.br
.ti -1c
.RI "WORD \fBpropertyID\fP"
.br
.ti -1c
.RI "WORD \fBreserved\fP"
.br
.ti -1c
.RI "DWORD \fBdataSize\fP"
.br
.ti -1c
.RI "BYTE \fBdata\fP [1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
