.TH "tagLOGCONTEXT" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagLOGCONTEXT
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBlcName\fP [LCNAMELEN]"
.br
.ti -1c
.RI "UINT \fBlcOptions\fP"
.br
.ti -1c
.RI "UINT \fBlcStatus\fP"
.br
.ti -1c
.RI "UINT \fBlcLocks\fP"
.br
.ti -1c
.RI "UINT \fBlcMsgBase\fP"
.br
.ti -1c
.RI "UINT \fBlcDevice\fP"
.br
.ti -1c
.RI "UINT \fBlcPktRate\fP"
.br
.ti -1c
.RI "WTPKT \fBlcPktData\fP"
.br
.ti -1c
.RI "WTPKT \fBlcPktMode\fP"
.br
.ti -1c
.RI "WTPKT \fBlcMoveMask\fP"
.br
.ti -1c
.RI "DWORD \fBlcBtnDnMask\fP"
.br
.ti -1c
.RI "DWORD \fBlcBtnUpMask\fP"
.br
.ti -1c
.RI "LONG \fBlcInOrgX\fP"
.br
.ti -1c
.RI "LONG \fBlcInOrgY\fP"
.br
.ti -1c
.RI "LONG \fBlcInOrgZ\fP"
.br
.ti -1c
.RI "LONG \fBlcInExtX\fP"
.br
.ti -1c
.RI "LONG \fBlcInExtY\fP"
.br
.ti -1c
.RI "LONG \fBlcInExtZ\fP"
.br
.ti -1c
.RI "LONG \fBlcOutOrgX\fP"
.br
.ti -1c
.RI "LONG \fBlcOutOrgY\fP"
.br
.ti -1c
.RI "LONG \fBlcOutOrgZ\fP"
.br
.ti -1c
.RI "LONG \fBlcOutExtX\fP"
.br
.ti -1c
.RI "LONG \fBlcOutExtY\fP"
.br
.ti -1c
.RI "LONG \fBlcOutExtZ\fP"
.br
.ti -1c
.RI "FIX32 \fBlcSensX\fP"
.br
.ti -1c
.RI "FIX32 \fBlcSensY\fP"
.br
.ti -1c
.RI "FIX32 \fBlcSensZ\fP"
.br
.ti -1c
.RI "BOOL \fBlcSysMode\fP"
.br
.ti -1c
.RI "int \fBlcSysOrgX\fP"
.br
.ti -1c
.RI "int \fBlcSysOrgY\fP"
.br
.ti -1c
.RI "int \fBlcSysExtX\fP"
.br
.ti -1c
.RI "int \fBlcSysExtY\fP"
.br
.ti -1c
.RI "FIX32 \fBlcSysSensX\fP"
.br
.ti -1c
.RI "FIX32 \fBlcSysSensY\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
