.TH "tar" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tar
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBarchive_string\fP \fBacl_text\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBentry_pathname\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBentry_pathname_override\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBentry_linkpath\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBentry_uname\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBentry_gname\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBlonglink\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBlongname\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBpax_header\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBpax_global\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBline\fP"
.br
.ti -1c
.RI "int \fBpax_hdrcharset_binary\fP"
.br
.ti -1c
.RI "int \fBheader_recursion_depth\fP"
.br
.ti -1c
.RI "int64_t \fBentry_bytes_remaining\fP"
.br
.ti -1c
.RI "int64_t \fBentry_offset\fP"
.br
.ti -1c
.RI "int64_t \fBentry_padding\fP"
.br
.ti -1c
.RI "int64_t \fBentry_bytes_unconsumed\fP"
.br
.ti -1c
.RI "int64_t \fBrealsize\fP"
.br
.ti -1c
.RI "int \fBsparse_allowed\fP"
.br
.ti -1c
.RI "struct \fBsparse_block\fP * \fBsparse_list\fP"
.br
.ti -1c
.RI "struct \fBsparse_block\fP * \fBsparse_last\fP"
.br
.ti -1c
.RI "int64_t \fBsparse_offset\fP"
.br
.ti -1c
.RI "int64_t \fBsparse_numbytes\fP"
.br
.ti -1c
.RI "int \fBsparse_gnu_major\fP"
.br
.ti -1c
.RI "int \fBsparse_gnu_minor\fP"
.br
.ti -1c
.RI "char \fBsparse_gnu_pending\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBlocalname\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBopt_sconv\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_acl\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_default\fP"
.br
.ti -1c
.RI "int \fBinit_default_conversion\fP"
.br
.ti -1c
.RI "int \fBcompat_2x\fP"
.br
.ti -1c
.RI "int \fBprocess_mac_extensions\fP"
.br
.ti -1c
.RI "int \fBread_concatenated_archives\fP"
.br
.ti -1c
.RI "int \fBrealsize_override\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
