.TH "TCell_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TCell_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TCoord \fBx\fP"
.br
.ti -1c
.RI "TCoord \fBcover\fP"
.br
.ti -1c
.RI "TArea \fBarea\fP"
.br
.ti -1c
.RI "\fBPCell\fP \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
