.TH "te_expr" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
te_expr
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   double \fBvalue\fP"
.br
.ti -1c
.RI "   const double * \fBbound\fP"
.br
.ti -1c
.RI "   const void * \fBfunction\fP"
.br
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "void * \fBparameters\fP [1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
