.TH "TELNET" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TELNET
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBplease_negotiate\fP"
.br
.ti -1c
.RI "int \fBalready_negotiated\fP"
.br
.ti -1c
.RI "int \fBus\fP [256]"
.br
.ti -1c
.RI "int \fBusq\fP [256]"
.br
.ti -1c
.RI "int \fBus_preferred\fP [256]"
.br
.ti -1c
.RI "int \fBhim\fP [256]"
.br
.ti -1c
.RI "int \fBhimq\fP [256]"
.br
.ti -1c
.RI "int \fBhim_preferred\fP [256]"
.br
.ti -1c
.RI "int \fBsubnegotiation\fP [256]"
.br
.ti -1c
.RI "char \fBsubopt_ttype\fP [32]"
.br
.ti -1c
.RI "char \fBsubopt_xdisploc\fP [128]"
.br
.ti -1c
.RI "unsigned short \fBsubopt_wsx\fP"
.br
.ti -1c
.RI "unsigned short \fBsubopt_wsy\fP"
.br
.ti -1c
.RI "TelnetReceive \fBtelrcv_state\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBtelnet_vars\fP"
.br
.ti -1c
.RI "unsigned char \fBsubbuffer\fP [SUBBUFSIZE]"
.br
.ti -1c
.RI "unsigned char * \fBsubpointer\fP"
.br
.ti -1c
.RI "unsigned char * \fBsubend\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
