.TH "TestListener" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestListener
.SH SYNOPSIS
.br
.PP
.PP
Inherits testing::EmptyTestEventListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestListener\fP (int *on_start_counter, bool *is_destroyed)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnTestProgramStart\fP (const UnitTest &) override"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
