.TH "test_entry" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBtestname\fP"
.br
.ti -1c
.RI "int \fBsrc_fmt\fP"
.br
.ti -1c
.RI "int \fBsrc_flags\fP"
.br
.ti -1c
.RI "int \fBop\fP"
.br
.ti -1c
.RI "int \fBmask_fmt\fP"
.br
.ti -1c
.RI "int \fBmask_flags\fP"
.br
.ti -1c
.RI "int \fBdst_fmt\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
