.TH "test_output_iterator" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_output_iterator
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBiterator_category\fP = std::output_iterator_tag"
.br
.ti -1c
.RI "using \fBvalue_type\fP = void"
.br
.ti -1c
.RI "using \fBdifference_type\fP = void"
.br
.ti -1c
.RI "using \fBpointer\fP = void"
.br
.ti -1c
.RI "using \fBreference\fP = void"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_output_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBtest_output_iterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "char & \fBoperator*\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
