.TH "testcase" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testcase
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBin\fP"
.br
.ti -1c
.RI "const char * \fBout\fP"
.br
.ti -1c
.RI "unsigned int \fBurlflags\fP"
.br
.ti -1c
.RI "unsigned int \fBgetflags\fP"
.br
.ti -1c
.RI "CURLUcode \fBucode\fP"
.br
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.ti -1c
.RI "size_t \fBbufsize\fP"
.br
.ti -1c
.RI "char * \fBrptr\fP"
.br
.ti -1c
.RI "size_t \fBrcount\fP"
.br
.ti -1c
.RI "long \fBtestno\fP"
.br
.ti -1c
.RI "int \fBofile\fP"
.br
.ti -1c
.RI "int \fBwritedelay\fP"
.br
.ti -1c
.RI "const char * \fBpattern\fP"
.br
.ti -1c
.RI "const char * \fBstring\fP"
.br
.ti -1c
.RI "int \fBresult\fP"
.br
.ti -1c
.RI "const char * \fBoptval\fP"
.br
.ti -1c
.RI "const char * \fBhost\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "bool \fBpermanent\fP"
.br
.ti -1c
.RI "const char * \fBaddress\fP [10]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
