.TH "TestData" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestData\fP (\fBhb_buffer_t\fP *buffer_, \fBhb_face_t\fP *face_, \fBhb_font_t\fP *font_, \fBhb_feature_t\fP *features_, int num_features_)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBhb_buffer_t\fP * \fBbuffer\fP"
.br
.ti -1c
.RI "\fBhb_face_t\fP * \fBface\fP"
.br
.ti -1c
.RI "\fBhb_font_t\fP * \fBfont\fP"
.br
.ti -1c
.RI "\fBhb_feature_t\fP * \fBfeatures\fP"
.br
.ti -1c
.RI "int \fBnum_features\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
