.TH "Dragon/src/testing.cpp" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dragon/src/testing.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <DGpch\&.h>\fP
.br
\fC#include 'testing\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDragon\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "DRAGON_API void \fBDragon::TestFunc\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
