.TH "test" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum class \fBformattable_scoped_enum\fP "
.br
.ti -1c
.RI "typedef size_t \fBsize_t\fP"
.br
.ti -1c
.RI "typedef ssize_t \fBssize_t\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBin\fP"
.br
.ti -1c
.RI "int \fBinlen\fP"
.br
.ti -1c
.RI "const char * \fBout\fP"
.br
.ti -1c
.RI "int \fBoutlen\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const DOHcode \fBexpected_result\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
