.TH "TestGenerationTest" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestGenerationTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestWithParam< int >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBPARAMETER_COUNT\fP }"
.br
.ti -1c
.RI "typedef \fBTestGenerationEnvironment\fP< PARAMETER_COUNT > \fBEnvironment\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP () override"
.br
.ti -1c
.RI "void \fBTearDown\fP () override"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetUpTestSuite\fP ()"
.br
.ti -1c
.RI "static void \fBTearDownTestSuite\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBcurrent_parameter_\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static vector< int > \fBcollected_parameters_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
