.TH "text_style" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
text_style
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <color\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP (emphasis em=emphasis()) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP & \fBoperator|=\fP (const \fBtext_style\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR bool \fBhas_foreground\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR bool \fBhas_background\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR bool \fBhas_emphasis\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR detail::color_type \fBget_foreground\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR detail::color_type \fBget_background\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR emphasis \fBget_emphasis\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP (emphasis em=emphasis()) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP & \fBoperator|=\fP (const \fBtext_style\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR bool \fBhas_foreground\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR bool \fBhas_background\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR bool \fBhas_emphasis\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR detail::color_type \fBget_foreground\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR detail::color_type \fBget_background\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR emphasis \fBget_emphasis\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP (emphasis em=emphasis()) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP & \fBoperator|=\fP (const \fBtext_style\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR bool \fBhas_foreground\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR bool \fBhas_background\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR bool \fBhas_emphasis\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR detail::color_type \fBget_foreground\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR detail::color_type \fBget_background\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR emphasis \fBget_emphasis\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP (emphasis em=emphasis()) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP & \fBoperator|=\fP (const \fBtext_style\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR bool \fBhas_foreground\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR bool \fBhas_background\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR bool \fBhas_emphasis\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR detail::color_type \fBget_foreground\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR detail::color_type \fBget_background\fP () const noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR emphasis \fBget_emphasis\fP () const noexcept"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP \fBoperator|\fP (\fBtext_style\fP lhs, const \fBtext_style\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP \fBfg\fP (detail::color_type foreground) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP \fBbg\fP (detail::color_type background) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP \fBoperator|\fP (\fBtext_style\fP lhs, const \fBtext_style\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP \fBfg\fP (detail::color_type foreground) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP \fBbg\fP (detail::color_type background) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP \fBoperator|\fP (\fBtext_style\fP lhs, const \fBtext_style\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP \fBfg\fP (detail::color_type foreground) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP \fBbg\fP (detail::color_type background) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP \fBoperator|\fP (\fBtext_style\fP lhs, const \fBtext_style\fP &rhs)"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP \fBfg\fP (detail::color_type foreground) noexcept"
.br
.ti -1c
.RI "FMT_CONSTEXPR \fBtext_style\fP \fBbg\fP (detail::color_type background) noexcept"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP text style consisting of foreground and background colors and emphasis\&. 
.SH "Friends And Related Function Documentation"
.PP 
.SS "FMT_CONSTEXPR \fBtext_style\fP bg (detail::color_type background)\fC [friend]\fP"
Creates a text style from the background color\&. 
.SS "FMT_CONSTEXPR \fBtext_style\fP bg (detail::color_type background)\fC [friend]\fP"
Creates a text style from the background color\&. 
.SS "FMT_CONSTEXPR \fBtext_style\fP bg (detail::color_type background)\fC [friend]\fP"
Creates a text style from the background color\&. 
.SS "FMT_CONSTEXPR \fBtext_style\fP bg (detail::color_type background)\fC [friend]\fP"
Creates a text style from the background color\&. 
.SS "FMT_CONSTEXPR \fBtext_style\fP fg (detail::color_type foreground)\fC [friend]\fP"
Creates a text style from the foreground (text) color\&. 
.SS "FMT_CONSTEXPR \fBtext_style\fP fg (detail::color_type foreground)\fC [friend]\fP"
Creates a text style from the foreground (text) color\&. 
.SS "FMT_CONSTEXPR \fBtext_style\fP fg (detail::color_type foreground)\fC [friend]\fP"
Creates a text style from the foreground (text) color\&. 
.SS "FMT_CONSTEXPR \fBtext_style\fP fg (detail::color_type foreground)\fC [friend]\fP"
Creates a text style from the foreground (text) color\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
