.TH "text_options_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
text_options_t
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBshape_text_options_t\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd_options\fP (\fBoption_parser_t\fP *parser)"
.br
.ti -1c
.RI "void \fBpost_parse\fP (GError **error G_GNUC_UNUSED)"
.br
.ti -1c
.RI "const char * \fBget_line\fP (unsigned int *len)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtext_len\fP = \-1"
.br
.ti -1c
.RI "char * \fBtext\fP = nullptr"
.br
.ti -1c
.RI "char * \fBtext_file\fP = nullptr"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
