.TH "tftp_state_data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tftp_state_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "tftp_state_t \fBstate\fP"
.br
.ti -1c
.RI "tftp_mode_t \fBmode\fP"
.br
.ti -1c
.RI "tftp_error_t \fBerror\fP"
.br
.ti -1c
.RI "tftp_event_t \fBevent\fP"
.br
.ti -1c
.RI "struct \fBCurl_easy\fP * \fBdata\fP"
.br
.ti -1c
.RI "curl_socket_t \fBsockfd\fP"
.br
.ti -1c
.RI "int \fBretries\fP"
.br
.ti -1c
.RI "int \fBretry_time\fP"
.br
.ti -1c
.RI "int \fBretry_max\fP"
.br
.ti -1c
.RI "time_t \fBrx_time\fP"
.br
.ti -1c
.RI "struct \fBCurl_sockaddr_storage\fP \fBlocal_addr\fP"
.br
.ti -1c
.RI "struct \fBCurl_sockaddr_storage\fP \fBremote_addr\fP"
.br
.ti -1c
.RI "curl_socklen_t \fBremote_addrlen\fP"
.br
.ti -1c
.RI "int \fBrbytes\fP"
.br
.ti -1c
.RI "int \fBsbytes\fP"
.br
.ti -1c
.RI "int \fBblksize\fP"
.br
.ti -1c
.RI "int \fBrequested_blksize\fP"
.br
.ti -1c
.RI "unsigned short \fBblock\fP"
.br
.ti -1c
.RI "struct \fBtftp_packet\fP \fBrpacket\fP"
.br
.ti -1c
.RI "struct \fBtftp_packet\fP \fBspacket\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
