.TH "tftphdr_storage_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tftphdr_storage_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBtftphdr\fP \fBhdr\fP"
.br
.ti -1c
.RI "char \fBstorage\fP [PKTSIZE]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
