.TH "tga_dest_struct" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tga_dest_struct
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBdjpeg_dest_struct\fP \fBpub\fP"
.br
.ti -1c
.RI "char * \fBiobuffer\fP"
.br
.ti -1c
.RI "JDIMENSION \fBbuffer_width\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
