.TH "timetest" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timetest
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnow_s\fP"
.br
.ti -1c
.RI "int \fBnow_us\fP"
.br
.ti -1c
.RI "int \fBtimeout_ms\fP"
.br
.ti -1c
.RI "int \fBconnecttimeout_ms\fP"
.br
.ti -1c
.RI "bool \fBconnecting\fP"
.br
.ti -1c
.RI "timediff_t \fBresult\fP"
.br
.ti -1c
.RI "const char * \fBcomment\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
