.TH "tm_writer< OutputIt, Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tm_writer< OutputIt, Char >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtm_writer\fP (const std::locale &loc, OutputIt out, const std::tm &tm)"
.br
.ti -1c
.RI "OutputIt \fBout\fP () const"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_text\fP (const Char *begin, const Char *end)"
.br
.ti -1c
.RI "void \fBon_abbr_weekday\fP ()"
.br
.ti -1c
.RI "void \fBon_full_weekday\fP ()"
.br
.ti -1c
.RI "void \fBon_dec0_weekday\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec1_weekday\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_abbr_month\fP ()"
.br
.ti -1c
.RI "void \fBon_full_month\fP ()"
.br
.ti -1c
.RI "void \fBon_datetime\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_loc_date\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_loc_time\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_us_date\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_date\fP ()"
.br
.ti -1c
.RI "void \fBon_utc_offset\fP ()"
.br
.ti -1c
.RI "void \fBon_tz_name\fP ()"
.br
.ti -1c
.RI "void \fBon_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_short_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_offset_year\fP ()"
.br
.ti -1c
.RI "void \fBon_century\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec_month\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec0_week_of_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec1_week_of_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_iso_week_of_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_iso_week_based_year\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_week_based_short_year\fP ()"
.br
.ti -1c
.RI "void \fBon_day_of_year\fP ()"
.br
.ti -1c
.RI "void \fBon_day_of_month\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_day_of_month_space\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_24_hour\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_12_hour\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_minute\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_second\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_12_hour_time\fP ()"
.br
.ti -1c
.RI "void \fBon_24_hour_time\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_time\fP ()"
.br
.ti -1c
.RI "void \fBon_am_pm\fP ()"
.br
.ti -1c
.RI "void \fBon_duration_value\fP ()"
.br
.ti -1c
.RI "void \fBon_duration_unit\fP ()"
.br
.ti -1c
.RI "\fBtm_writer\fP (const std::locale &loc, OutputIt out, const std::tm &tm)"
.br
.ti -1c
.RI "OutputIt \fBout\fP () const"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_text\fP (const Char *begin, const Char *end)"
.br
.ti -1c
.RI "void \fBon_abbr_weekday\fP ()"
.br
.ti -1c
.RI "void \fBon_full_weekday\fP ()"
.br
.ti -1c
.RI "void \fBon_dec0_weekday\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec1_weekday\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_abbr_month\fP ()"
.br
.ti -1c
.RI "void \fBon_full_month\fP ()"
.br
.ti -1c
.RI "void \fBon_datetime\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_loc_date\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_loc_time\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_us_date\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_date\fP ()"
.br
.ti -1c
.RI "void \fBon_utc_offset\fP ()"
.br
.ti -1c
.RI "void \fBon_tz_name\fP ()"
.br
.ti -1c
.RI "void \fBon_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_short_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_offset_year\fP ()"
.br
.ti -1c
.RI "void \fBon_century\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec_month\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec0_week_of_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec1_week_of_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_iso_week_of_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_iso_week_based_year\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_week_based_short_year\fP ()"
.br
.ti -1c
.RI "void \fBon_day_of_year\fP ()"
.br
.ti -1c
.RI "void \fBon_day_of_month\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_day_of_month_space\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_24_hour\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_12_hour\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_minute\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_second\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_12_hour_time\fP ()"
.br
.ti -1c
.RI "void \fBon_24_hour_time\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_time\fP ()"
.br
.ti -1c
.RI "void \fBon_am_pm\fP ()"
.br
.ti -1c
.RI "void \fBon_duration_value\fP ()"
.br
.ti -1c
.RI "void \fBon_duration_unit\fP ()"
.br
.ti -1c
.RI "\fBtm_writer\fP (const std::locale &loc, OutputIt out, const std::tm &tm)"
.br
.ti -1c
.RI "OutputIt \fBout\fP () const"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_text\fP (const Char *begin, const Char *end)"
.br
.ti -1c
.RI "void \fBon_abbr_weekday\fP ()"
.br
.ti -1c
.RI "void \fBon_full_weekday\fP ()"
.br
.ti -1c
.RI "void \fBon_dec0_weekday\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec1_weekday\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_abbr_month\fP ()"
.br
.ti -1c
.RI "void \fBon_full_month\fP ()"
.br
.ti -1c
.RI "void \fBon_datetime\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_loc_date\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_loc_time\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_us_date\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_date\fP ()"
.br
.ti -1c
.RI "void \fBon_utc_offset\fP ()"
.br
.ti -1c
.RI "void \fBon_tz_name\fP ()"
.br
.ti -1c
.RI "void \fBon_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_short_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_offset_year\fP ()"
.br
.ti -1c
.RI "void \fBon_century\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec_month\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec0_week_of_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec1_week_of_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_iso_week_of_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_iso_week_based_year\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_week_based_short_year\fP ()"
.br
.ti -1c
.RI "void \fBon_day_of_year\fP ()"
.br
.ti -1c
.RI "void \fBon_day_of_month\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_day_of_month_space\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_24_hour\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_12_hour\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_minute\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_second\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_12_hour_time\fP ()"
.br
.ti -1c
.RI "void \fBon_24_hour_time\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_time\fP ()"
.br
.ti -1c
.RI "void \fBon_am_pm\fP ()"
.br
.ti -1c
.RI "void \fBon_duration_value\fP ()"
.br
.ti -1c
.RI "void \fBon_duration_unit\fP ()"
.br
.ti -1c
.RI "\fBtm_writer\fP (const std::locale &loc, OutputIt out, const std::tm &tm)"
.br
.ti -1c
.RI "OutputIt \fBout\fP () const"
.br
.ti -1c
.RI "FMT_CONSTEXPR void \fBon_text\fP (const Char *begin, const Char *end)"
.br
.ti -1c
.RI "void \fBon_abbr_weekday\fP ()"
.br
.ti -1c
.RI "void \fBon_full_weekday\fP ()"
.br
.ti -1c
.RI "void \fBon_dec0_weekday\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec1_weekday\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_abbr_month\fP ()"
.br
.ti -1c
.RI "void \fBon_full_month\fP ()"
.br
.ti -1c
.RI "void \fBon_datetime\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_loc_date\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_loc_time\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_us_date\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_date\fP ()"
.br
.ti -1c
.RI "void \fBon_utc_offset\fP ()"
.br
.ti -1c
.RI "void \fBon_tz_name\fP ()"
.br
.ti -1c
.RI "void \fBon_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_short_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_offset_year\fP ()"
.br
.ti -1c
.RI "void \fBon_century\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec_month\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec0_week_of_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_dec1_week_of_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_iso_week_of_year\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_iso_week_based_year\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_week_based_short_year\fP ()"
.br
.ti -1c
.RI "void \fBon_day_of_year\fP ()"
.br
.ti -1c
.RI "void \fBon_day_of_month\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_day_of_month_space\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_24_hour\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_12_hour\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_minute\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_second\fP (numeric_system ns)"
.br
.ti -1c
.RI "void \fBon_12_hour_time\fP ()"
.br
.ti -1c
.RI "void \fBon_24_hour_time\fP ()"
.br
.ti -1c
.RI "void \fBon_iso_time\fP ()"
.br
.ti -1c
.RI "void \fBon_am_pm\fP ()"
.br
.ti -1c
.RI "void \fBon_duration_value\fP ()"
.br
.ti -1c
.RI "void \fBon_duration_unit\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
