.TH "tm_zip_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tm_zip_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uInt \fBtm_sec\fP"
.br
.ti -1c
.RI "uInt \fBtm_min\fP"
.br
.ti -1c
.RI "uInt \fBtm_hour\fP"
.br
.ti -1c
.RI "uInt \fBtm_mday\fP"
.br
.ti -1c
.RI "uInt \fBtm_mon\fP"
.br
.ti -1c
.RI "uInt \fBtm_year\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
