.TH "to_stringable" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
to_stringable
.SH SYNOPSIS
.br
.PP
.SS "Friends"

.in +1c
.ti -1c
.RI "fmt::string_view \fBto_string_view\fP (\fBto_stringable\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
