.TH "top_dict_modifiers_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
top_dict_modifiers_t
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtop_dict_modifiers_t\fP (const \fBcff1_sub_table_info_t\fP &info_, const unsigned int(&nameSIDs_)[name_dict_values_t::ValCount])"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBcff1_sub_table_info_t\fP & \fBinfo\fP"
.br
.ti -1c
.RI "const unsigned int(& \fBnameSIDs\fP )[name_dict_values_t::ValCount]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
