.TH "tree_entry" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tree_entry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBtree_entry\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBtree_entry\fP * \fBparent\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "size_t \fBdirname_length\fP"
.br
.ti -1c
.RI "dev_t \fBdev\fP"
.br
.ti -1c
.RI "ino_t \fBino\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBname\fP"
.br
.ti -1c
.RI "int64_t \fBdev\fP"
.br
.ti -1c
.RI "int64_t \fBino\fP"
.br
.ti -1c
.RI "int \fBfilesystem_id\fP"
.br
.ti -1c
.RI "int \fBsymlink_parent_fd\fP"
.br
.ti -1c
.RI "struct \fBrestore_time\fP \fBrestore_time\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
