.TH "tree" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tree
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBentry_sparse\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBtree_entry\fP * \fBstack\fP"
.br
.ti -1c
.RI "struct \fBtree_entry\fP * \fBcurrent\fP"
.br
.ti -1c
.RI "DIR * \fBd\fP"
.br
.ti -1c
.RI "int \fBinitialDirFd\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int \fBvisit_type\fP"
.br
.ti -1c
.RI "int \fBtree_errno\fP"
.br
.ti -1c
.RI "char * \fBbuff\fP"
.br
.ti -1c
.RI "const char * \fBbasename\fP"
.br
.ti -1c
.RI "size_t \fBbuff_length\fP"
.br
.ti -1c
.RI "size_t \fBpath_length\fP"
.br
.ti -1c
.RI "size_t \fBdirname_length\fP"
.br
.ti -1c
.RI "int \fBdepth\fP"
.br
.ti -1c
.RI "int \fBopenCount\fP"
.br
.ti -1c
.RI "int \fBmaxOpenCount\fP"
.br
.ti -1c
.RI "struct stat \fBlst\fP"
.br
.ti -1c
.RI "struct stat \fBst\fP"
.br
.ti -1c
.RI "struct dirent * \fBde\fP"
.br
.ti -1c
.RI "struct \fBarchive_string\fP \fBpath\fP"
.br
.ti -1c
.RI "int \fBinitial_dir_fd\fP"
.br
.ti -1c
.RI "int \fBworking_dir_fd\fP"
.br
.ti -1c
.RI "int \fBdescend\fP"
.br
.ti -1c
.RI "int \fBnlink\fP"
.br
.ti -1c
.RI "struct \fBrestore_time\fP \fBrestore_time\fP"
.br
.ti -1c
.RI "struct \fBtree::entry_sparse\fP * \fBsparse_list\fP"
.br
.ti -1c
.RI "struct \fBtree::entry_sparse\fP * \fBcurrent_sparse\fP"
.br
.ti -1c
.RI "int \fBsparse_count\fP"
.br
.ti -1c
.RI "int \fBsparse_list_size\fP"
.br
.ti -1c
.RI "char \fBinitial_symlink_mode\fP"
.br
.ti -1c
.RI "char \fBsymlink_mode\fP"
.br
.ti -1c
.RI "struct \fBfilesystem\fP * \fBcurrent_filesystem\fP"
.br
.ti -1c
.RI "struct \fBfilesystem\fP * \fBfilesystem_table\fP"
.br
.ti -1c
.RI "int \fBinitial_filesystem_id\fP"
.br
.ti -1c
.RI "int \fBcurrent_filesystem_id\fP"
.br
.ti -1c
.RI "int \fBmax_filesystem_id\fP"
.br
.ti -1c
.RI "int \fBallocated_filesystem\fP"
.br
.ti -1c
.RI "int \fBentry_fd\fP"
.br
.ti -1c
.RI "int \fBentry_eof\fP"
.br
.ti -1c
.RI "int64_t \fBentry_remaining_bytes\fP"
.br
.ti -1c
.RI "int64_t \fBentry_total\fP"
.br
.ti -1c
.RI "unsigned char * \fBentry_buff\fP"
.br
.ti -1c
.RI "size_t \fBentry_buff_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
