.TH "TString" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TString
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCommonHeader\fP"
.br
.ti -1c
.RI "lu_byte \fBextra\fP"
.br
.ti -1c
.RI "lu_byte \fBshrlen\fP"
.br
.ti -1c
.RI "unsigned int \fBhash\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   size_t \fBlnglen\fP"
.br
.ti -1c
.RI "   struct \fBTString\fP * \fBhnext\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "char \fBcontents\fP [1]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
