.TH "TT_CMap_ClassRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_CMap_ClassRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_CMap_ClassRec\fP \fBclazz\fP"
.br
.ti -1c
.RI "FT_UInt \fBformat\fP"
.br
.ti -1c
.RI "TT_CMap_ValidateFunc \fBvalidate\fP"
.br
.ti -1c
.RI "TT_CMap_Info_GetFunc \fBget_cmap_info\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
