.TH "TT_GlyphZoneRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_GlyphZoneRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Memory \fBmemory\fP"
.br
.ti -1c
.RI "FT_UShort \fBmax_points\fP"
.br
.ti -1c
.RI "FT_Short \fBmax_contours\fP"
.br
.ti -1c
.RI "FT_UShort \fBn_points\fP"
.br
.ti -1c
.RI "FT_Short \fBn_contours\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP * \fBorg\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP * \fBcur\fP"
.br
.ti -1c
.RI "\fBFT_Vector\fP * \fBorus\fP"
.br
.ti -1c
.RI "FT_Byte * \fBtags\fP"
.br
.ti -1c
.RI "FT_UShort * \fBcontours\fP"
.br
.ti -1c
.RI "FT_UShort \fBfirst_point\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
