.TH "TT_NameTableRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_NameTableRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBformat\fP"
.br
.ti -1c
.RI "FT_UInt \fBnumNameRecords\fP"
.br
.ti -1c
.RI "FT_UInt \fBstorageOffset\fP"
.br
.ti -1c
.RI "\fBTT_NameRec\fP * \fBnames\fP"
.br
.ti -1c
.RI "FT_UInt \fBnumLangTagRecords\fP"
.br
.ti -1c
.RI "\fBTT_LangTagRec\fP * \fBlangTags\fP"
.br
.ti -1c
.RI "\fBFT_Stream\fP \fBstream\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
