.TH "TT_Post_20Rec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_Post_20Rec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_UShort \fBnum_glyphs\fP"
.br
.ti -1c
.RI "FT_UShort \fBnum_names\fP"
.br
.ti -1c
.RI "FT_UShort * \fBglyph_indices\fP"
.br
.ti -1c
.RI "FT_Char ** \fBglyph_names\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
