.TH "TT_Size_Metrics_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_Size_Metrics_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Long \fBx_ratio\fP"
.br
.ti -1c
.RI "FT_Long \fBy_ratio\fP"
.br
.ti -1c
.RI "FT_UShort \fBppem\fP"
.br
.ti -1c
.RI "FT_Long \fBratio\fP"
.br
.ti -1c
.RI "FT_Fixed \fBscale\fP"
.br
.ti -1c
.RI "FT_F26Dot6 \fBcompensations\fP [4]"
.br
.ti -1c
.RI "FT_Bool \fBvalid\fP"
.br
.ti -1c
.RI "FT_Bool \fBrotated\fP"
.br
.ti -1c
.RI "FT_Bool \fBstretched\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
