.TH "TT_SBit_StrikeRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_SBit_StrikeRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Int \fBnum_ranges\fP"
.br
.ti -1c
.RI "\fBTT_SBit_Range\fP \fBsbit_ranges\fP"
.br
.ti -1c
.RI "FT_ULong \fBranges_offset\fP"
.br
.ti -1c
.RI "FT_ULong \fBcolor_ref\fP"
.br
.ti -1c
.RI "\fBTT_SBit_LineMetricsRec\fP \fBhori\fP"
.br
.ti -1c
.RI "\fBTT_SBit_LineMetricsRec\fP \fBvert\fP"
.br
.ti -1c
.RI "FT_UShort \fBstart_glyph\fP"
.br
.ti -1c
.RI "FT_UShort \fBend_glyph\fP"
.br
.ti -1c
.RI "FT_Byte \fBx_ppem\fP"
.br
.ti -1c
.RI "FT_Byte \fBy_ppem\fP"
.br
.ti -1c
.RI "FT_Byte \fBbit_depth\fP"
.br
.ti -1c
.RI "FT_Char \fBflags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
