.TH "TT_SBit_LineMetricsRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_SBit_LineMetricsRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FT_Char \fBascender\fP"
.br
.ti -1c
.RI "FT_Char \fBdescender\fP"
.br
.ti -1c
.RI "FT_Byte \fBmax_width\fP"
.br
.ti -1c
.RI "FT_Char \fBcaret_slope_numerator\fP"
.br
.ti -1c
.RI "FT_Char \fBcaret_slope_denominator\fP"
.br
.ti -1c
.RI "FT_Char \fBcaret_offset\fP"
.br
.ti -1c
.RI "FT_Char \fBmin_origin_SB\fP"
.br
.ti -1c
.RI "FT_Char \fBmin_advance_SB\fP"
.br
.ti -1c
.RI "FT_Char \fBmax_before_BL\fP"
.br
.ti -1c
.RI "FT_Char \fBmin_after_BL\fP"
.br
.ti -1c
.RI "FT_Char \fBpads\fP [2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
