.TH "TT_SizeRec_" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TT_SizeRec_
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFT_SizeRec\fP \fBroot\fP"
.br
.ti -1c
.RI "\fBFT_Size_Metrics\fP * \fBmetrics\fP"
.br
.ti -1c
.RI "\fBFT_Size_Metrics\fP \fBhinted_metrics\fP"
.br
.ti -1c
.RI "\fBTT_Size_Metrics\fP \fBttmetrics\fP"
.br
.ti -1c
.RI "FT_Byte * \fBwidthp\fP"
.br
.ti -1c
.RI "FT_ULong \fBstrike_index\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
