.TH "tuple_like" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuple_like
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<size_t N> fmt::enable_if_t< N==0, int > \fBget\fP () const noexcept"
.br
.ti -1c
.RI "template<size_t N> fmt::enable_if_t< N==1, fmt::string_view > \fBget\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "std::string \fBstr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
