.TH "tuple_join_view< Char, T >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuple_join_view< Char, T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits detail::view\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtuple_join_view\fP (const std::tuple< T\&.\&.\&. > &t, \fBbasic_string_view\fP< Char > s)"
.br
.ti -1c
.RI "\fBtuple_join_view\fP (const std::tuple< T\&.\&.\&. > &t, \fBbasic_string_view\fP< Char > s)"
.br
.ti -1c
.RI "\fBtuple_join_view\fP (const std::tuple< T\&.\&.\&. > &t, \fBbasic_string_view\fP< Char > s)"
.br
.ti -1c
.RI "\fBtuple_join_view\fP (const std::tuple< T\&.\&.\&. > &t, \fBbasic_string_view\fP< Char > s)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const std::tuple< T\&.\&.\&. > & \fBtuple\fP"
.br
.ti -1c
.RI "\fBbasic_string_view\fP< Char > \fBsep\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
