.TH "Tutorial_3::Object" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tutorial_3::Object
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBrotation_speed\fP = 0"
.br
.ti -1c
.RI "float \fBrotation\fP = 0"
.br
.ti -1c
.RI "\fBvec2\fP \fBscale\fP = \fBvec2\fP{ 1\&.0f }"
.br
.ti -1c
.RI "\fBvec2\fP \fBposition\fP = \fBvec2\fP{ 0\&.0f }"
.br
.ti -1c
.RI "ModelType \fBwhich_model\fP = ModelType::Rectangle"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
