.TH "Tutorial_0" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tutorial_0
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIProgram\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTutorial_0\fP (int viewport_width, int viewport_height)"
.br
.ti -1c
.RI "\fBTutorial_0\fP (const \fBTutorial_0\fP &)=delete"
.br
.ti -1c
.RI "\fBTutorial_0\fP & \fBoperator=\fP (const \fBTutorial_0\fP &)=delete"
.br
.ti -1c
.RI "\fBTutorial_0\fP (\fBTutorial_0\fP &&)=delete"
.br
.ti -1c
.RI "\fBTutorial_0\fP & \fBoperator=\fP (\fBTutorial_0\fP &&)=delete"
.br
.ti -1c
.RI "void \fBUpdate\fP () override"
.br
.ti -1c
.RI "void \fBDraw\fP () override"
.br
.ti -1c
.RI "void \fBImGuiDraw\fP () override"
.br
.ti -1c
.RI "void \fBHandleEvent\fP (SDL_Window &sdl_window, const \fBSDL_Event\fP &event) override"
.br
.in -1c

Public Member Functions inherited from \fBIProgram\fP
.in +1c
.ti -1c
.RI "constexpr \fBIProgram\fP (const \fBIProgram\fP &) noexcept=default"
.br
.ti -1c
.RI "constexpr \fBIProgram\fP (\fBIProgram\fP &&) noexcept=default"
.br
.ti -1c
.RI "\fBIProgram\fP & \fBoperator=\fP (const \fBIProgram\fP &) noexcept=default"
.br
.ti -1c
.RI "\fBIProgram\fP & \fBoperator=\fP (\fBIProgram\fP &&) noexcept=default"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBDraw\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBImGuiDraw\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBHandleEvent\fP (SDL_Window &sdl_window, const \fBSDL_Event\fP &event)=0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Tutorial_0::Draw ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIProgram\fP\&.
.SS "void Tutorial_0::HandleEvent (SDL_Window & sdl_window, const \fBSDL_Event\fP & event)\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIProgram\fP\&.
.SS "void Tutorial_0::ImGuiDraw ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIProgram\fP\&.
.SS "void Tutorial_0::Update ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Implements \fBIProgram\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
