.TH "type_constant< T, Char >" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
type_constant< T, Char >
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::integral_constant< type, type::custom_type >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
