.TH "unformattable" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unformattable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBunformattable_char\fP, \fBunformattable_const\fP, and \fBunformattable_pointer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
