.TH "unsshort_st" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unsshort_st
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBnum\fP"
.br
.ti -1c
.RI "const char * \fBexpected\fP"
.br
.ti -1c
.RI "char \fBresult\fP [BUFSZ]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
