.TH "unz64_file_pos_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unz64_file_pos_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ZPOS64_T \fBpos_in_zip_directory\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBnum_of_file\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
