.TH "unz64_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unz64_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBzlib_filefunc64_32_def\fP \fBz_filefunc\fP"
.br
.ti -1c
.RI "int \fBis64bitOpenFunction\fP"
.br
.ti -1c
.RI "voidpf \fBfilestream\fP"
.br
.ti -1c
.RI "\fBunz_global_info64\fP \fBgi\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBbyte_before_the_zipfile\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBnum_file\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBpos_in_central_dir\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBcurrent_file_ok\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBcentral_pos\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBsize_central_dir\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBoffset_central_dir\fP"
.br
.ti -1c
.RI "\fBunz_file_info64\fP \fBcur_file_info\fP"
.br
.ti -1c
.RI "\fBunz_file_info64_internal\fP \fBcur_file_info_internal\fP"
.br
.ti -1c
.RI "\fBfile_in_zip64_read_info_s\fP * \fBpfile_in_zip_read\fP"
.br
.ti -1c
.RI "int \fBencrypted\fP"
.br
.ti -1c
.RI "int \fBisZip64\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
