.TH "unz_file_info64_s" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
unz_file_info64_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uLong \fBversion\fP"
.br
.ti -1c
.RI "uLong \fBversion_needed\fP"
.br
.ti -1c
.RI "uLong \fBflag\fP"
.br
.ti -1c
.RI "uLong \fBcompression_method\fP"
.br
.ti -1c
.RI "uLong \fBdosDate\fP"
.br
.ti -1c
.RI "uLong \fBcrc\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBcompressed_size\fP"
.br
.ti -1c
.RI "ZPOS64_T \fBuncompressed_size\fP"
.br
.ti -1c
.RI "uLong \fBsize_filename\fP"
.br
.ti -1c
.RI "uLong \fBsize_file_extra\fP"
.br
.ti -1c
.RI "uLong \fBsize_file_comment\fP"
.br
.ti -1c
.RI "uLong \fBdisk_num_start\fP"
.br
.ti -1c
.RI "uLong \fBinternal_fa\fP"
.br
.ti -1c
.RI "uLong \fBexternal_fa\fP"
.br
.ti -1c
.RI "\fBtm_unz\fP \fBtmu_date\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
