.TH "UpVal" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UpVal
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCommonHeader\fP"
.br
.ti -1c
.RI "lu_byte \fBtbc\fP"
.br
.ti -1c
.RI "\fBTValue\fP * \fBv\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      struct \fBUpVal\fP * \fBnext\fP"
.br
.ti -1c
.RI "      struct \fBUpVal\fP ** \fBprevious\fP"
.br
.ti -1c
.RI "   } \fBopen\fP"
.br
.ti -1c
.RI "   \fBTValue\fP \fBvalue\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
