.TH "Upvaldesc" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Upvaldesc
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTString\fP * \fBname\fP"
.br
.ti -1c
.RI "lu_byte \fBinstack\fP"
.br
.ti -1c
.RI "lu_byte \fBidx\fP"
.br
.ti -1c
.RI "lu_byte \fBkind\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
