.TH "urlpieces" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
urlpieces
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBscheme\fP"
.br
.ti -1c
.RI "char * \fBhostname\fP"
.br
.ti -1c
.RI "char * \fBport\fP"
.br
.ti -1c
.RI "char * \fBuser\fP"
.br
.ti -1c
.RI "char * \fBpassword\fP"
.br
.ti -1c
.RI "char * \fBoptions\fP"
.br
.ti -1c
.RI "char * \fBpath\fP"
.br
.ti -1c
.RI "char * \fBquery\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
