.TH "URLPattern" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
URLPattern
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "URLPatternType \fBtype\fP"
.br
.ti -1c
.RI "int \fBglobindex\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      char ** \fBelements\fP"
.br
.ti -1c
.RI "      int \fBsize\fP"
.br
.ti -1c
.RI "      int \fBptr_s\fP"
.br
.ti -1c
.RI "   } \fBSet\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      char \fBmin_c\fP"
.br
.ti -1c
.RI "      char \fBmax_c\fP"
.br
.ti -1c
.RI "      char \fBptr_c\fP"
.br
.ti -1c
.RI "      int \fBstep\fP"
.br
.ti -1c
.RI "   } \fBCharRange\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      unsigned long \fBmin_n\fP"
.br
.ti -1c
.RI "      unsigned long \fBmax_n\fP"
.br
.ti -1c
.RI "      int \fBpadlength\fP"
.br
.ti -1c
.RI "      unsigned long \fBptr_n\fP"
.br
.ti -1c
.RI "      unsigned long \fBstep\fP"
.br
.ti -1c
.RI "   } \fBNumRange\fP"
.br
.ti -1c
.RI "} \fBcontent\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
