.TH "UrlState" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UrlState
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdynamically_allocated_data\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBIT\fP (prev_block_had_trailing_cr)"
.br
.ti -1c
.RI "\fBBIT\fP (multi_owned_by_easy)"
.br
.ti -1c
.RI "\fBBIT\fP (this_is_a_follow)"
.br
.ti -1c
.RI "\fBBIT\fP (refused_stream)"
.br
.ti -1c
.RI "\fBBIT\fP (errorbuf)"
.br
.ti -1c
.RI "\fBBIT\fP (allow_port)"
.br
.ti -1c
.RI "\fBBIT\fP (authproblem)"
.br
.ti -1c
.RI "\fBBIT\fP (ftp_trying_alternative)"
.br
.ti -1c
.RI "\fBBIT\fP (wildcardmatch)"
.br
.ti -1c
.RI "\fBBIT\fP (expect100header)"
.br
.ti -1c
.RI "\fBBIT\fP (disableexpect)"
.br
.ti -1c
.RI "\fBBIT\fP (use_range)"
.br
.ti -1c
.RI "\fBBIT\fP (rangestringalloc)"
.br
.ti -1c
.RI "\fBBIT\fP (done)"
.br
.ti -1c
.RI "\fBBIT\fP (stream_depends_e)"
.br
.ti -1c
.RI "\fBBIT\fP (previouslypending)"
.br
.ti -1c
.RI "\fBBIT\fP (cookie_engine)"
.br
.ti -1c
.RI "\fBBIT\fP (prefer_ascii)"
.br
.ti -1c
.RI "\fBBIT\fP (list_only)"
.br
.ti -1c
.RI "\fBBIT\fP (url_alloc)"
.br
.ti -1c
.RI "\fBBIT\fP (referer_alloc)"
.br
.ti -1c
.RI "\fBBIT\fP (wildcard_resolve)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBconncache\fP * \fBconn_cache\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBkeeps_speed\fP"
.br
.ti -1c
.RI "long \fBlastconnect_id\fP"
.br
.ti -1c
.RI "struct \fBdynbuf\fP \fBheaderb\fP"
.br
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.ti -1c
.RI "char * \fBulbuf\fP"
.br
.ti -1c
.RI "curl_off_t \fBcurrent_speed\fP"
.br
.ti -1c
.RI "char * \fBfirst_host\fP"
.br
.ti -1c
.RI "int \fBretrycount\fP"
.br
.ti -1c
.RI "int \fBfirst_remote_port\fP"
.br
.ti -1c
.RI "struct \fBCurl_ssl_session\fP * \fBsession\fP"
.br
.ti -1c
.RI "long \fBsessionage\fP"
.br
.ti -1c
.RI "struct \fBtempbuf\fP \fBtempwrite\fP [3]"
.br
.ti -1c
.RI "unsigned int \fBtempcount\fP"
.br
.ti -1c
.RI "int \fBos_errno\fP"
.br
.ti -1c
.RI "char * \fBscratch\fP"
.br
.ti -1c
.RI "long \fBfollowlocation\fP"
.br
.ti -1c
.RI "struct \fBdigestdata\fP \fBdigest\fP"
.br
.ti -1c
.RI "struct \fBdigestdata\fP \fBproxydigest\fP"
.br
.ti -1c
.RI "struct \fBauth\fP \fBauthhost\fP"
.br
.ti -1c
.RI "struct \fBauth\fP \fBauthproxy\fP"
.br
.ti -1c
.RI "struct \fBCurl_async\fP \fBasync\fP"
.br
.ti -1c
.RI "struct \fBcurltime\fP \fBexpiretime\fP"
.br
.ti -1c
.RI "struct \fBCurl_tree\fP \fBtimenode\fP"
.br
.ti -1c
.RI "struct \fBCurl_llist\fP \fBtimeoutlist\fP"
.br
.ti -1c
.RI "struct \fBtime_node\fP \fBexpires\fP [EXPIRE_LAST]"
.br
.ti -1c
.RI "char * \fBmost_recent_ftp_entrypath\fP"
.br
.ti -1c
.RI "unsigned char \fBhttpwant\fP"
.br
.ti -1c
.RI "unsigned char \fBhttpversion\fP"
.br
.ti -1c
.RI "curl_off_t \fBcrlf_conversions\fP"
.br
.ti -1c
.RI "char * \fBrange\fP"
.br
.ti -1c
.RI "curl_off_t \fBresume_from\fP"
.br
.ti -1c
.RI "long \fBrtsp_next_client_CSeq\fP"
.br
.ti -1c
.RI "long \fBrtsp_next_server_CSeq\fP"
.br
.ti -1c
.RI "long \fBrtsp_CSeq_recv\fP"
.br
.ti -1c
.RI "curl_off_t \fBinfilesize\fP"
.br
.ti -1c
.RI "size_t \fBdrain\fP"
.br
.ti -1c
.RI "curl_read_callback \fBfread_func\fP"
.br
.ti -1c
.RI "void * \fBin\fP"
.br
.ti -1c
.RI "struct \fBCurl_easy\fP * \fBstream_depends_on\fP"
.br
.ti -1c
.RI "int \fBstream_weight\fP"
.br
.ti -1c
.RI "\fBCURLU\fP * \fBuh\fP"
.br
.ti -1c
.RI "struct \fBurlpieces\fP \fBup\fP"
.br
.ti -1c
.RI "Curl_HttpReq \fBhttpreq\fP"
.br
.ti -1c
.RI "char * \fBurl\fP"
.br
.ti -1c
.RI "char * \fBreferer\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBcookielist\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBresolve\fP"
.br
.ti -1c
.RI "size_t \fBtrailers_bytes_sent\fP"
.br
.ti -1c
.RI "struct \fBdynbuf\fP \fBtrailers_buf\fP"
.br
.ti -1c
.RI "trailers_state \fBtrailers_state\fP"
.br
.ti -1c
.RI "struct \fBUrlState::dynamically_allocated_data\fP \fBaptr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
