.TH "UrlState::dynamically_allocated_data" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UrlState::dynamically_allocated_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBproxyuserpwd\fP"
.br
.ti -1c
.RI "char * \fBuagent\fP"
.br
.ti -1c
.RI "char * \fBaccept_encoding\fP"
.br
.ti -1c
.RI "char * \fBuserpwd\fP"
.br
.ti -1c
.RI "char * \fBrangeline\fP"
.br
.ti -1c
.RI "char * \fBref\fP"
.br
.ti -1c
.RI "char * \fBhost\fP"
.br
.ti -1c
.RI "char * \fBcookiehost\fP"
.br
.ti -1c
.RI "char * \fBrtsp_transport\fP"
.br
.ti -1c
.RI "char * \fBte\fP"
.br
.ti -1c
.RI "char * \fBuser\fP"
.br
.ti -1c
.RI "char * \fBpasswd\fP"
.br
.ti -1c
.RI "char * \fBproxyuser\fP"
.br
.ti -1c
.RI "char * \fBproxypasswd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
