.TH "use_shape_plan_t" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
use_shape_plan_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "hb_mask_t \fBrphf_mask\fP"
.br
.ti -1c
.RI "\fBarabic_shape_plan_t\fP * \fBarabic_plan\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
