.TH "UserDefined" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserDefined
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBIT\fP (is_fread_set)"
.br
.ti -1c
.RI "\fBBIT\fP (is_fwrite_set)"
.br
.ti -1c
.RI "\fBBIT\fP (free_referer)"
.br
.ti -1c
.RI "\fBBIT\fP (tftp_no_options)"
.br
.ti -1c
.RI "\fBBIT\fP (sep_headers)"
.br
.ti -1c
.RI "\fBBIT\fP (cookiesession)"
.br
.ti -1c
.RI "\fBBIT\fP (crlf)"
.br
.ti -1c
.RI "\fBBIT\fP (strip_path_slash)"
.br
.ti -1c
.RI "\fBBIT\fP (ssh_compression)"
.br
.ti -1c
.RI "\fBBIT\fP (get_filetime)"
.br
.ti -1c
.RI "\fBBIT\fP (tunnel_thru_httpproxy)"
.br
.ti -1c
.RI "\fBBIT\fP (prefer_ascii)"
.br
.ti -1c
.RI "\fBBIT\fP (remote_append)"
.br
.ti -1c
.RI "\fBBIT\fP (list_only)"
.br
.ti -1c
.RI "\fBBIT\fP (ftp_use_port)"
.br
.ti -1c
.RI "\fBBIT\fP (ftp_use_epsv)"
.br
.ti -1c
.RI "\fBBIT\fP (ftp_use_eprt)"
.br
.ti -1c
.RI "\fBBIT\fP (ftp_use_pret)"
.br
.ti -1c
.RI "\fBBIT\fP (ftp_skip_ip)"
.br
.ti -1c
.RI "\fBBIT\fP (hide_progress)"
.br
.ti -1c
.RI "\fBBIT\fP (http_fail_on_error)"
.br
.ti -1c
.RI "\fBBIT\fP (http_keep_sending_on_error)"
.br
.ti -1c
.RI "\fBBIT\fP (http_follow_location)"
.br
.ti -1c
.RI "\fBBIT\fP (http_transfer_encoding)"
.br
.ti -1c
.RI "\fBBIT\fP (allow_auth_to_other_hosts)"
.br
.ti -1c
.RI "\fBBIT\fP (include_header)"
.br
.ti -1c
.RI "\fBBIT\fP (http_set_referer)"
.br
.ti -1c
.RI "\fBBIT\fP (http_auto_referer)"
.br
.ti -1c
.RI "\fBBIT\fP (opt_no_body)"
.br
.ti -1c
.RI "\fBBIT\fP (upload)"
.br
.ti -1c
.RI "\fBBIT\fP (verbose)"
.br
.ti -1c
.RI "\fBBIT\fP (krb)"
.br
.ti -1c
.RI "\fBBIT\fP (reuse_forbid)"
.br
.ti -1c
.RI "\fBBIT\fP (reuse_fresh)"
.br
.ti -1c
.RI "\fBBIT\fP (no_signal)"
.br
.ti -1c
.RI "\fBBIT\fP (tcp_nodelay)"
.br
.ti -1c
.RI "\fBBIT\fP (ignorecl)"
.br
.ti -1c
.RI "\fBBIT\fP (connect_only)"
.br
.ti -1c
.RI "\fBBIT\fP (http_te_skip)"
.br
.ti -1c
.RI "\fBBIT\fP (http_ce_skip)"
.br
.ti -1c
.RI "\fBBIT\fP (proxy_transfer_mode)"
.br
.ti -1c
.RI "\fBBIT\fP (sasl_ir)"
.br
.ti -1c
.RI "\fBBIT\fP (wildcard_enabled)"
.br
.ti -1c
.RI "\fBBIT\fP (tcp_keepalive)"
.br
.ti -1c
.RI "\fBBIT\fP (tcp_fastopen)"
.br
.ti -1c
.RI "\fBBIT\fP (ssl_enable_npn)"
.br
.ti -1c
.RI "\fBBIT\fP (ssl_enable_alpn)"
.br
.ti -1c
.RI "\fBBIT\fP (path_as_is)"
.br
.ti -1c
.RI "\fBBIT\fP (pipewait)"
.br
.ti -1c
.RI "\fBBIT\fP (suppress_connect_headers)"
.br
.ti -1c
.RI "\fBBIT\fP (dns_shuffle_addresses)"
.br
.ti -1c
.RI "\fBBIT\fP (stream_depends_e)"
.br
.ti -1c
.RI "\fBBIT\fP (haproxyprotocol)"
.br
.ti -1c
.RI "\fBBIT\fP (abstract_unix_socket)"
.br
.ti -1c
.RI "\fBBIT\fP (disallow_username_in_url)"
.br
.ti -1c
.RI "\fBBIT\fP (doh)"
.br
.ti -1c
.RI "\fBBIT\fP (doh_get)"
.br
.ti -1c
.RI "\fBBIT\fP (doh_verifypeer)"
.br
.ti -1c
.RI "\fBBIT\fP (doh_verifyhost)"
.br
.ti -1c
.RI "\fBBIT\fP (doh_verifystatus)"
.br
.ti -1c
.RI "\fBBIT\fP (http09_allowed)"
.br
.ti -1c
.RI "\fBBIT\fP (mail_rcpt_allowfails)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBerr\fP"
.br
.ti -1c
.RI "void * \fBdebugdata\fP"
.br
.ti -1c
.RI "char * \fBerrorbuffer\fP"
.br
.ti -1c
.RI "long \fBproxyport\fP"
.br
.ti -1c
.RI "void * \fBout\fP"
.br
.ti -1c
.RI "void * \fBin_set\fP"
.br
.ti -1c
.RI "void * \fBwriteheader\fP"
.br
.ti -1c
.RI "void * \fBrtp_out\fP"
.br
.ti -1c
.RI "long \fBuse_port\fP"
.br
.ti -1c
.RI "unsigned long \fBhttpauth\fP"
.br
.ti -1c
.RI "unsigned long \fBproxyauth\fP"
.br
.ti -1c
.RI "unsigned long \fBsocks5auth\fP"
.br
.ti -1c
.RI "long \fBmaxredirs\fP"
.br
.ti -1c
.RI "int \fBkeep_post\fP"
.br
.ti -1c
.RI "void * \fBpostfields\fP"
.br
.ti -1c
.RI "curl_seek_callback \fBseek_func\fP"
.br
.ti -1c
.RI "curl_off_t \fBpostfieldsize\fP"
.br
.ti -1c
.RI "unsigned short \fBlocalport\fP"
.br
.ti -1c
.RI "int \fBlocalportrange\fP"
.br
.ti -1c
.RI "curl_write_callback \fBfwrite_func\fP"
.br
.ti -1c
.RI "curl_write_callback \fBfwrite_header\fP"
.br
.ti -1c
.RI "curl_write_callback \fBfwrite_rtp\fP"
.br
.ti -1c
.RI "curl_read_callback \fBfread_func_set\fP"
.br
.ti -1c
.RI "curl_progress_callback \fBfprogress\fP"
.br
.ti -1c
.RI "curl_xferinfo_callback \fBfxferinfo\fP"
.br
.ti -1c
.RI "curl_debug_callback \fBfdebug\fP"
.br
.ti -1c
.RI "curl_ioctl_callback \fBioctl_func\fP"
.br
.ti -1c
.RI "curl_sockopt_callback \fBfsockopt\fP"
.br
.ti -1c
.RI "void * \fBsockopt_client\fP"
.br
.ti -1c
.RI "curl_opensocket_callback \fBfopensocket\fP"
.br
.ti -1c
.RI "void * \fBopensocket_client\fP"
.br
.ti -1c
.RI "curl_closesocket_callback \fBfclosesocket\fP"
.br
.ti -1c
.RI "void * \fBclosesocket_client\fP"
.br
.ti -1c
.RI "void * \fBseek_client\fP"
.br
.ti -1c
.RI "curl_conv_callback \fBconvfromnetwork\fP"
.br
.ti -1c
.RI "curl_conv_callback \fBconvtonetwork\fP"
.br
.ti -1c
.RI "curl_conv_callback \fBconvfromutf8\fP"
.br
.ti -1c
.RI "curl_hstsread_callback \fBhsts_read\fP"
.br
.ti -1c
.RI "void * \fBhsts_read_userp\fP"
.br
.ti -1c
.RI "curl_hstswrite_callback \fBhsts_write\fP"
.br
.ti -1c
.RI "void * \fBhsts_write_userp\fP"
.br
.ti -1c
.RI "void * \fBprogress_client\fP"
.br
.ti -1c
.RI "void * \fBioctl_client\fP"
.br
.ti -1c
.RI "long \fBtimeout\fP"
.br
.ti -1c
.RI "long \fBconnecttimeout\fP"
.br
.ti -1c
.RI "long \fBaccepttimeout\fP"
.br
.ti -1c
.RI "long \fBhappy_eyeballs_timeout\fP"
.br
.ti -1c
.RI "long \fBserver_response_timeout\fP"
.br
.ti -1c
.RI "long \fBmaxage_conn\fP"
.br
.ti -1c
.RI "long \fBtftp_blksize\fP"
.br
.ti -1c
.RI "curl_off_t \fBfilesize\fP"
.br
.ti -1c
.RI "long \fBlow_speed_limit\fP"
.br
.ti -1c
.RI "long \fBlow_speed_time\fP"
.br
.ti -1c
.RI "curl_off_t \fBmax_send_speed\fP"
.br
.ti -1c
.RI "curl_off_t \fBmax_recv_speed\fP"
.br
.ti -1c
.RI "curl_off_t \fBset_resume_from\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBheaders\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBproxyheaders\fP"
.br
.ti -1c
.RI "struct \fBcurl_httppost\fP * \fBhttppost\fP"
.br
.ti -1c
.RI "\fBcurl_mimepart\fP \fBmimepost\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBquote\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBpostquote\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBprequote\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBsource_quote\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBsource_prequote\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBsource_postquote\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBtelnet_options\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBresolve\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBconnect_to\fP"
.br
.ti -1c
.RI "curl_TimeCond \fBtimecondition\fP"
.br
.ti -1c
.RI "curl_proxytype \fBproxytype\fP"
.br
.ti -1c
.RI "time_t \fBtimevalue\fP"
.br
.ti -1c
.RI "Curl_HttpReq \fBmethod\fP"
.br
.ti -1c
.RI "unsigned char \fBhttpwant\fP"
.br
.ti -1c
.RI "struct \fBssl_config_data\fP \fBssl\fP"
.br
.ti -1c
.RI "struct \fBssl_config_data\fP \fBproxy_ssl\fP"
.br
.ti -1c
.RI "struct \fBssl_general_config\fP \fBgeneral_ssl\fP"
.br
.ti -1c
.RI "long \fBdns_cache_timeout\fP"
.br
.ti -1c
.RI "long \fBbuffer_size\fP"
.br
.ti -1c
.RI "unsigned int \fBupload_buffer_size\fP"
.br
.ti -1c
.RI "void * \fBprivate_data\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBhttp200aliases\fP"
.br
.ti -1c
.RI "unsigned char \fBipver\fP"
.br
.ti -1c
.RI "curl_off_t \fBmax_filesize\fP"
.br
.ti -1c
.RI "curl_ftpfile \fBftp_filemethod\fP"
.br
.ti -1c
.RI "curl_ftpauth \fBftpsslauth\fP"
.br
.ti -1c
.RI "curl_ftpccc \fBftp_ccc\fP"
.br
.ti -1c
.RI "int \fBftp_create_missing_dirs\fP"
.br
.ti -1c
.RI "curl_sshkeycallback \fBssh_keyfunc\fP"
.br
.ti -1c
.RI "void * \fBssh_keyfunc_userp\fP"
.br
.ti -1c
.RI "enum CURL_NETRC_OPTION \fBuse_netrc\fP"
.br
.ti -1c
.RI "curl_usessl \fBuse_ssl\fP"
.br
.ti -1c
.RI "long \fBnew_file_perms\fP"
.br
.ti -1c
.RI "long \fBnew_directory_perms\fP"
.br
.ti -1c
.RI "long \fBssh_auth_types\fP"
.br
.ti -1c
.RI "char * \fBstr\fP [STRING_LAST]"
.br
.ti -1c
.RI "struct \fBcurl_blob\fP * \fBblobs\fP [BLOB_LAST]"
.br
.ti -1c
.RI "unsigned int \fBscope_id\fP"
.br
.ti -1c
.RI "long \fBallowed_protocols\fP"
.br
.ti -1c
.RI "long \fBredir_protocols\fP"
.br
.ti -1c
.RI "struct \fBcurl_slist\fP * \fBmail_rcpt\fP"
.br
.ti -1c
.RI "Curl_RtspReq \fBrtspreq\fP"
.br
.ti -1c
.RI "long \fBrtspversion\fP"
.br
.ti -1c
.RI "curl_chunk_bgn_callback \fBchunk_bgn\fP"
.br
.ti -1c
.RI "curl_chunk_end_callback \fBchunk_end\fP"
.br
.ti -1c
.RI "curl_fnmatch_callback \fBfnmatch\fP"
.br
.ti -1c
.RI "void * \fBfnmatch_data\fP"
.br
.ti -1c
.RI "long \fBgssapi_delegation\fP"
.br
.ti -1c
.RI "long \fBtcp_keepidle\fP"
.br
.ti -1c
.RI "long \fBtcp_keepintvl\fP"
.br
.ti -1c
.RI "size_t \fBmaxconnects\fP"
.br
.ti -1c
.RI "long \fBexpect_100_timeout\fP"
.br
.ti -1c
.RI "struct \fBCurl_easy\fP * \fBstream_depends_on\fP"
.br
.ti -1c
.RI "int \fBstream_weight\fP"
.br
.ti -1c
.RI "struct \fBCurl_http2_dep\fP * \fBstream_dependents\fP"
.br
.ti -1c
.RI "curl_resolver_start_callback \fBresolver_start\fP"
.br
.ti -1c
.RI "void * \fBresolver_start_client\fP"
.br
.ti -1c
.RI "long \fBupkeep_interval_ms\fP"
.br
.ti -1c
.RI "multidone_func \fBfmultidone\fP"
.br
.ti -1c
.RI "struct \fBCurl_easy\fP * \fBdohfor\fP"
.br
.ti -1c
.RI "\fBCURLU\fP * \fBuh\fP"
.br
.ti -1c
.RI "void * \fBtrailer_data\fP"
.br
.ti -1c
.RI "curl_trailer_callback \fBtrailer_callback\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
