.TH "ustar" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ustar
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBentry_bytes_remaining\fP"
.br
.ti -1c
.RI "uint64_t \fBentry_padding\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBopt_sconv\fP"
.br
.ti -1c
.RI "struct \fBarchive_string_conv\fP * \fBsconv_default\fP"
.br
.ti -1c
.RI "int \fBinit_default_conversion\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
