.TH "utf8_to_utf16" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utf8_to_utf16
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FMT_API \fButf8_to_utf16\fP (\fBstring_view\fP s)"
.br
.ti -1c
.RI "\fBoperator basic_string_view< wchar_t >\fP () const"
.br
.ti -1c
.RI "auto \fBsize\fP () const \-> size_t"
.br
.ti -1c
.RI "auto \fBc_str\fP () const \-> const wchar_t *"
.br
.ti -1c
.RI "auto \fBstr\fP () const \-> std::wstring"
.br
.ti -1c
.RI "FMT_API \fButf8_to_utf16\fP (\fBstring_view\fP s)"
.br
.ti -1c
.RI "\fBoperator basic_string_view< wchar_t >\fP () const"
.br
.ti -1c
.RI "auto \fBsize\fP () const \-> size_t"
.br
.ti -1c
.RI "auto \fBc_str\fP () const \-> const wchar_t *"
.br
.ti -1c
.RI "auto \fBstr\fP () const \-> std::wstring"
.br
.ti -1c
.RI "FMT_API \fButf8_to_utf16\fP (\fBstring_view\fP s)"
.br
.ti -1c
.RI "\fBoperator basic_string_view< wchar_t >\fP () const"
.br
.ti -1c
.RI "auto \fBsize\fP () const \-> size_t"
.br
.ti -1c
.RI "auto \fBc_str\fP () const \-> const wchar_t *"
.br
.ti -1c
.RI "auto \fBstr\fP () const \-> std::wstring"
.br
.ti -1c
.RI "FMT_API \fButf8_to_utf16\fP (\fBstring_view\fP s)"
.br
.ti -1c
.RI "\fBoperator basic_string_view< wchar_t >\fP () const"
.br
.ti -1c
.RI "auto \fBsize\fP () const \-> size_t"
.br
.ti -1c
.RI "auto \fBc_str\fP () const \-> const wchar_t *"
.br
.ti -1c
.RI "auto \fBstr\fP () const \-> std::wstring"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
