.TH "uudecode" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uudecode
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBtotal\fP"
.br
.ti -1c
.RI "unsigned char * \fBin_buff\fP"
.br
.ti -1c
.RI "int \fBin_cnt\fP"
.br
.ti -1c
.RI "size_t \fBin_allocated\fP"
.br
.ti -1c
.RI "unsigned char * \fBout_buff\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
