.TH "va_stack" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
va_stack
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FormatType \fBtype\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "long \fBwidth\fP"
.br
.ti -1c
.RI "long \fBprecision\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBstr\fP"
.br
.ti -1c
.RI "   void * \fBptr\fP"
.br
.ti -1c
.RI "   union {"
.br
.ti -1c
.RI "      mp_intmax_t \fBas_signed\fP"
.br
.ti -1c
.RI "      mp_uintmax_t \fBas_unsigned\fP"
.br
.ti -1c
.RI "   } \fBnum\fP"
.br
.ti -1c
.RI "   double \fBdnum\fP"
.br
.ti -1c
.RI "} \fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
