.TH "variant" 3 "Wed Feb 1 2023" "Version Version 0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
variant
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBint_type\fP, \fBstring_type\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvariant\fP (int)"
.br
.ti -1c
.RI "\fBvariant\fP (const char *)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum variant:: { \&.\&.\&. }  \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
